### PR TITLE
"Scaffold" triggers for SQL Server

### LINKED ISSUE #28185: SQL Server: Scaffold HasTrigger if the table contains triggers
Since #27372, SaveChanges fails by default on SQL Server for tables with triggers. We could detect triggers when scaffolding and scaffold HasTrigger to make the database-first story smoother. This may be a bit tricky since HasTrigger is on TableBuilder rather than directly on EntityTypeBuilder (not sure if we already have the infra for scaffolding that).

Raised by @ErikEJ in https://github.com/ErikEJ/ErikEJ/issues/1#issuecomment-1148615714

### PR DESCRIPTION
**Pull request by roji**
HasTrigger with trigger name only, to make the SQL Server SaveChanges work out of the box.

Closes #28185

### CODE REVIEW

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 1]
```diff
@@ -1295,6 +1296,48 @@ private void GetForeignKeys(DbConnection connection, IReadOnlyList<DatabaseTable
...
+
+        foreach (var tableGroup in tableGroups)
+        {
+            var tableSchema = tableGroup.Key.tableSchema;
+            var tableName = tableGroup.Key.tableName;
+
+            var table = tables.Single(t => t.Schema == tableSchema && t.Name == tableName);
+
+            var triggers = new HashSet<string>();
+            table[RelationalAnnotationNames.Triggers] = triggers;
```
Comment (roji) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:1328]: Note that the annotation value here is `HashSet<string>`, which is different from what we do via the Fluent API (`Dictionary<string, ITrigger>`), because ITrigger needs to reference an IMutableEntityType which we don't have here. The translation from this to that happens in RelationalScaffoldingModelFactory.

**Comment by roji** [comment]
Scaffolding codegen needs to happen in CSharpDbContextGenerator and not in AnnotationCodeGenerator, since on the model snapshot side special code handles triggers in CSharpSnapshotGenerator. Should have done this after @bricelam's template work :(

**Comment by AndriySvyryd** [comment]
:shipit:

**Comment by ErikEJ** [comment]
LGTM - makes using previews a better experience.

**Comment by roji** [comment]
Ready for review, unrelated Cosmos test failures due to flakiness (:angry:)

**Comment by ajcvickers** [comment]
Why are the Cosmos tests running on that build? Did we enable Cosmos there at some point and I forgot about it? @smitpatel?

**Comment by ajcvickers** [comment]
Also, it's interesting that it's new tests (`Regex_IsMatch_MethodCall...`) that are failing. Is there something different about how these tests work than the other tests? I.e. are we sure this is Cosmos flakiness and not something flaky in the new tests?

**Comment by roji** [comment]
Agree that it's strange! Though also not supposed to be related to this PR in any way...

**Comment by roji** [comment]
@smitpatel did that locally as part of #28139, PR out soon.

**Review by AndriySvyryd — APPROVED** [review]
