### PR TITLE
Query: Perform join operations when one of the source has client eval

### LINKED ISSUE #17762: Query: Translate List.Exists
```C#
        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task Where_Join_Exists_Inequality(bool isAsync)
        {
            return AssertQuery<Customer>(
                isAsync,
                cs => cs.Where(c => c.CustomerID == "ALFKI" && c.Orders.Exists(o => o.OrderDate != new DateTime(2008, 10, 24))),
                entryCount: 1);
        }
```

### LINKED ISSUE #17763: Query: NRE when projecting non-mapped property from SelectMany
query:

```cs
cs.SelectMany(c => c.Orders.Select(o => new { OrderProperty = o.ShipName, CustomerProperty = c.ContactName }))
```

exception:

```
 Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    at MemberAccessShiftingExpressionVisitor.VisitExtension(Expression node) in QueryableMethodTranslatingExpressionVisitor.cs line: 511
    at Expression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at EntityShaperExpression.VisitChildren(ExpressionVisitor visitor) in EntityShaperExpression.cs line: 25
    at ExpressionVisitor.VisitExtension(Expression node)
    at MemberAccessShiftingExpressionVisitor.VisitExtension(Expression node) in QueryableMethodTranslatingExpressionVisitor.cs line: 517
    at Expression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at ExpressionVisitor.VisitMember(MemberExpression node)
    at MemberExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
    at ExpressionVisitor.VisitNew(NewExpression node)
    at NewExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at QueryableMethodTranslatingExpressionVisitor.CombineShapers(Expression queryExpression, Expression outerShaper, Expression innerShaper, Type transparentIdentifierType) in QueryableMethodTranslatingExpressionVisitor.cs line: 489
    at QueryableMethodTranslatingExpressionVisitor.TranslateResultSelectorForJoin(ShapedQueryExpression outer, LambdaExpression resultSelector, Expression innerShaper, Type transparentIdentifierType) in QueryableMethodTranslatingExpressionVisitor.cs line: 459
    at RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelectMany(ShapedQueryExpression source, LambdaExpression collectionSelector, LambdaExpression resultSelector) in RelationalQueryableMethodTranslatingExpressionVisitor.cs line: 778
    at QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in QueryableMethodTranslatingExpressionVisitor.cs line: 351
    at RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in RelationalQueryableMethodTranslatingExpressionVisitor.cs line: 72
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in QueryableMethodTranslatingExpressionVisitor.cs line: 58
    at RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in RelationalQueryableMethodTranslatingExpressionVisitor.cs line: 72
    at MethodCallExpression.Accept(ExpressionVisitor visitor)
    at ExpressionVisitor.Visit(Expression node)
    at QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in QueryCompilationContext.cs line: 68
    at Database.CompileQuery[TResult](Expression query, Boolean async) in Database.cs line: 71
    at QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in QueryCompiler.cs line: 106
    at <>c__DisplayClass12_0`1.<ExecuteAsync>b__0() in QueryCompiler.cs line: 137
    at CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in CompiledQueryCache.cs line: 84
    at CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in CompiledQueryCache.cs line: 59
    at QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken) in QueryCompiler.cs line: 133
    at EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) in EntityQueryProvider.cs line: 98
    at EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken) in EntityQueryable`.cs line: 112
    at ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
    at EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken) in EntityFrameworkQueryableExtensions.cs line: 2019
    at EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken) in EntityFrameworkQueryableExtensions.cs line: 2050
    at QueryAsserter`1.AssertQuery[TItem1](Func`2 actualQuery, Func`2 expectedQuery, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount, Boolean isAsync, String testMethodName) in QueryAsserter.cs line: 350
    at SimpleQuerySqlServerTest.SelectMany_with_collection_being_correlated_subquery_which_references_non_mapped_properties_from_inner_and_outer_entity(Boolean isAsync) in SimpleQuerySqlServerTest.Select.cs line: 1085
    at --- End of stack trace from previous location where exception was thrown ---
```

`projectionBindingExpression.ProjectionMember` is null

### LINKED ISSUE #19247: NullReferenceException when translating nested SelectMany with Constructor calls
I'm getting a reproducible `NullReferenceException` when translating the following query...

```cs
var results3 = await context.Set<MyParentVersionEntity>()
    .Where(pv => pv.NextVersionId == null)
    .Select(pv => new MyParentDetailViewModel(
        pv.ParentId,
        pv.Name,
        pv.Parent.Children
            .SelectMany(c => c.Versions
                .Where(cv => cv.NextVersionId == null)
                .Where(cv => !cv.IsDeleted)
                .Select(cv => new MyChildIdentityViewModel(
                    cv.ChildId,
                    cv.Name)))
            .ToArray()))
    .ToArrayAsync();
```

The query runs correctly with either of the following tweaks:

Un-nesting the subquery within .SelectMany()
```cs
var results2 = await context.Set<MyParentVersionEntity>()
    .Where(pv => pv.NextVersionId == null)
    .Select(pv => new MyParentDetailViewModel(
        pv.ParentId,
        pv.Name,
        pv.Parent.Children
            .SelectMany(c => c.Versions)
            .Where(cv => cv.NextVersionId == null)
            .Where(cv => !cv.IsDeleted)
            .Select(cv => new MyChildIdentityViewModel(
                cv.ChildId,
                cv.Name))
            .ToArray()))
    .ToArrayAsync();
```

Replacing the constructor calls with anonymous objects
```cs
var results1 = await context.Set<MyParentVersionEntity>()
    .Where(pv => pv.NextVersionId == null)
    .Select(pv => new
    {
        pv.ParentId,
        pv.Name,
        Children = pv.Parent.Children
            .SelectMany(c => c.Versions
                .Where(cv => cv.NextVersionId == null)
                .Where(cv => !cv.IsDeleted)
                .Select(cv => new
                {
                    cv.ChildId,
                    cv.Name
                }))
            .ToArray()
    })
    .ToArrayAsync();
```

Full reproduction test case: https://github.com/JakenVeina/EFCoreSelectManyTest.

Stack Trace:
```
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.MemberAccessShiftingExpressionVisitor.VisitExtension(Expression node)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.CombineShapers(Expression queryExpression, Expression outerShaper, Expression innerShaper, Type transparentIdentifierType)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateResultSelectorForJoin(ShapedQueryExpression outer, LambdaExpression resultSelector, Expression innerShaper, Type transparentIdentifierType)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelectMany(ShapedQueryExpression source, LambdaExpression collectionSelector, LambdaExpression resultSelector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Query.Internal.NpgsqlSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCall)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Query.Internal.NpgsqlSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCall)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToArrayAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EFCoreSelectManyTest.Program.<Main>d__0.MoveNext() in D:\Projects\EFCoreSelectManyTest\Program.cs:line 61
```
EF Core version: 3.1.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET Core 3.0
Operating system: Windows 8.1 Pro
IDE: Visual Studio Community 2019 16.4.0

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #19247
Resolves #17763
Lays ground work for #20291
Required for #20892

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -1449,11 +1449,662 @@ private enum JoinType
             OuterApply
         }
 
+        private Expression AddJoin(
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1452]: these two need to be DRY'd at some point (can be in future commit)

Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1452]: Agreed. In the essence of time, I skipped it for now. Will do in preview7. All the methods duplicating are private so should be non-breaking to change.

File: src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs [hunk 2]
```diff
@@ -227,10 +241,29 @@ protected override Expression VisitExtension(Expression extensionExpression)
 
             if (extensionExpression is EntityShaperExpression entityShaperExpression)
             {
+                // TODO: Make this easier to understand some day.
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs:244]: Optimistic

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 3]
```diff
@@ -1449,11 +1449,662 @@ private enum JoinType
...
+            var outerClientEval = Projection.Count > 0;
+            var innerClientEval = innerSelectExpression.Projection.Count > 0;
+            var remapper = new ProjectionBindingExpressionRemappingExpressionVisitor(this);
+            var innerNullable = joinType == JoinType.LeftJoin || joinType == JoinType.OuterApply;
+
+            if (outerClientEval)
+            {
+                if (innerClientEval)
+                {
+                    var offset = Projection.Count;
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1584]: add tests for these, we only have them for client eval on inner

Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1584]: I thought about it. Not sure if it is possible right now to have it (other than the SelectMany case which causes it).
The selector on outer will always get pulled to very top so it is not possible to go through join pipeline for that during client eval since everything will be in projection which will either take CollectionProjection or SingleProjection path.
Requires https://github.com/dotnet/efcore/issues/20291 to actually add something which hits this code path. I added it as future proofing since I was thinking holistically.

Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1584]: Added note on #20291

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1452]: Tracking via #21226
