### PR TITLE
Fix performance degradation in converters because the instance was not reused

### LINKED ISSUE #36856: Performance regression with PrimitiveCollections using a complex ValueConverter
### Bug description

We have found that query performance degrades dramatically when using PrimitiveCollections with a complex ValueConverter. What takes 10 seconds under EF8 now takes over a minute in EF10.

**This is a minimal reproduction that mimics our production code** - we're seeing this same performance degradation in our real application, making it impossible to upgrade EF versions.

## The Scenario

We were able to reproduce the issue in a minimal project: https://github.com/desruc/ef-valueconverter-performance-issue

Here's an overview of the reproduction and test results:

### The Pattern

We use value objects in our domain, like this:
```csharp
public class TagId
{
    public string Value { get; }
    public TagId(string value) => Value = value;
}
```

These value objects get stored in primitive collections on owned entities:

```csharp
public class Child // Owned entity
{
    public string ChildId { get; set; }
    public List<TagId> TagIds { get; set; }
}

public class Parent
{
    public string Id { get; set; }
    public IReadOnlyList<Child> Children { get; set; } // Owns many Children
}
```

To make EF Core work, we use a generic ValueConverter:

```csharp
public class ReflectionValueConverter<T> : ValueConverter<T, string>
{
    public ReflectionValueConverter() : base(
        convertToProviderExpression: v => ((TagId)(object)v).Value,

        convertFromProviderExpression: v => (T)typeof(T)
            .GetConstructor(new[] { typeof(string) })!
            .Invoke(new object[] { v })
    )
    {
    }
}
```

The EF configuration that triggers the issue:
```csharp
builder.OwnsMany<Child>(x => x.Children, b =>
{
    // The performance killer is this line:
    b.PrimitiveCollection(p => p.TagIds)
        .ElementType()
        .HasConversion<ReflectionValueConverter<TagId>>();
});
```

### Test Data

Our reproduction creates:
- 1,000 parent records
- Each parent has 100 children
- Each child has 100 TagId objects
- **Total: 10 million primitive collection items**

### The Query
We run a simple query that loads everything:
```csharp
await context.Parents.AsSplitQuery().ToListAsync();
```

## Performance Results
| EF Version | Time |
|------------|------|
| EF8 (8.0.20) | 10.8 seconds |
| EF9 (9.0.9) | 22.8 seconds |
| EF10 (10.0.0-rc.1.25451.107) | 1 minute 20.3 seconds |

**Note:** When we tested the same scenario using `List<string>` instead of `List<TagId>` (no ValueConverter), all EF versions performed consistently fast. This confirms the regression is specifically related to ValueConverter processing, not PrimitiveCollections in general.

## Additional Observation
The performance problem largely goes away when the expression is extracted to a static method:

```csharp
public class ReflectionValueConverter<T> : ValueConverter<T, string>
{
    public ReflectionValueConverter() : base(
        convertToProviderExpression: v => ((TagId)(object)v).Value,
        convertFromProviderExpression: v => ConvertFromString(v)
    )
    {
    }

    static T ConvertFromString(string v) => (T)typeof(T)
        .GetConstructor(new[] { typeof(string) })!
        .Invoke(new object[] { v });
}
```

| EF Version | Time |
|------------|------|
| EF8 (8.0.20) | 5.7 seconds |
| EF9 (9.0.9) | 9.8 seconds |
| EF10 (10.0.0-rc.1.25451.107) | 9 seconds |

And as `List<string>` with no converter:

| EF Version | Time |
|------------|------|
| EF8 (8.0.20) | 5.1 seconds |
| EF9 (9.0.9) | 5.4 seconds |
| EF10 (10.0.0-rc.1.25451.107) | 3.1 seconds |

### EF Core version

9.0.9, 10.0.0-rc.1.25451.107

### Database provider

Microsoft.EntityFrameworkCore.SqlServer

### Target framework

.NET9.0, .NET10.0

### Operating system

MacOS

### IDE

Rider 2025.2.0.1

### PR DESCRIPTION
**Pull request by cincuranet**
Fixes #36856.

### CODE REVIEW

File: src/EFCore/Storage/ValueConversion/ValueConverter.cs [hunk 1]
```diff
@@ -255,10 +255,4 @@ var firstConverter
                 ? firstConverter.MappingHints
                 : secondConverter.MappingHints.With(firstConverter.MappingHints))!;
     }
-
-    /// <summary>
-    ///     The expression representing construction of this object.
-    /// </summary>
-    [Experimental(EFDiagnostics.PrecompiledQueryExperimental)]
-    public abstract Expression ConstructorExpression { get; }
```
Comment (AndriySvyryd) [inline src/EFCore/Storage/ValueConversion/ValueConverter.cs:263]: Keep this. It can still be useful for the compiled model, see https://github.com/dotnet/efcore/issues/36900

**Review by AndriySvyryd — APPROVED** [review]
Do you plan on porting this to GA?

File: src/EFCore/Storage/ValueConversion/ValueConverter.cs (hunk 1 above)
Comment (cincuranet) [reply src/EFCore/Storage/ValueConversion/ValueConverter.cs:263]: OK.

**Comment by cincuranet** [comment]
Yes: #36898.

File: src/EFCore/Storage/Json/JsonConvertedValueReaderWriter.cs [hunk 2]
```diff
@@ -55,5 +55,8 @@ public override Expression ConstructorExpression
         => Expression.New(
             _constructorInfo,
             ((ICompositeJsonValueReaderWriter)this).InnerReaderWriter.ConstructorExpression,
-            ((IJsonConvertedValueReaderWriter)this).Converter.ConstructorExpression);
+            // We shouldn't quote converters, because every new instance will have to compile
```
Comment (roji) [inline src/EFCore/Storage/Json/JsonConvertedValueReaderWriter.cs]: I'm definitely being pedantic, but I'd make it clear that quoting here instantiates a new instance of the converter each time, and that's the source of the perf problem (since the new instance then recompiles).

In any case, reference #36856 for the additional context (this is generally a good idea for non-trivial code - just reference the issue which justifies things and contains all the history/context).

Comment (cincuranet) [reply src/EFCore/Storage/Json/JsonConvertedValueReaderWriter.cs]: Better now?

Comment (roji) [reply src/EFCore/Storage/Json/JsonConvertedValueReaderWriter.cs]: Yep, thanks!

**Comment by cincuranet** [comment]
The `innerShaper` (where this comes from) does not go through (at the moment) `LiftableConstantProcessor`. I guess we can probably plug visitor at a different spot. Is it worth it?

**Comment by roji** [comment]
Are you sure that's the case? That in itself would mean that JSON doesn't work with precompiled queries, no?

I thought when you dump the final shaper (at the point where we also do liftable constant inlining/lifting), you can always recursively see all the shapers of all structural types in the tree, otherwise I'm a bit confused about how it's all working.

**Comment by cincuranet** [comment]
> Are you sure that's the case?

As far as I can tell.

> That in itself would mean that JSON doesn't work with precompiled queries, no?

🤷‍♂️

> I thought when you dump the final shaper (at the point where we also do liftable constant inlining/lifting), you can always recursively see all the shapers of all structural types in the tree, otherwise I'm a bit confused about how it's all working.

Sadly for you, I'm not an expert in this area.

**Comment by roji** [comment]
Well, I did a quick minimal test program that queries something that has a JSON complex type in it (full source below):

```c#
_ = await context.Blogs.ToListAsync();
```

I put a breakpoint [right before the liftable constant processor](https://github.com/dotnet/efcore/blob/main/src/EFCore/Query/QueryCompilationContext.cs#L183), and dumped the shaper with ExpressionPrinter.Print. The full dump is below, but the relevant part with the innerShaper is the following:

```c#
ShaperProcessingExpressionVisitor.IncludeJsonEntityReference<Blog, BlogDetails>(
    queryContext: queryContext, 
    keyPropertyValues: null, 
    jsonReaderData: jsonReader, 
    structuralType: instance1, 
    innerShaper: (queryContext, namelessParameter{3}, namelessParameter{4}) => 
    {
        BlogDetails entityShaperMaterializer;
        return entityShaperMaterializer = 
        {
            MaterializationContext materializationContext2;
            IComplexType entityType2;
            BlogDetails instance2;
...
```

So there's a call to [ShaperProcessingExpressionVisitor.IncludeJsonEntityReference](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ClientMethods.cs#L1131) (which is a regular .NET method, not code-generated or anything), and the innerShaper is passed in as an argument, but it's present in the shaper tree as an expression (the parameter type is `Func<QueryContext, object[]?, JsonReaderData, TRelatedStructural>`, but then in the shaper expression tree the innerShaper is an `Expression<Func<...>>`.

I think that means that the liftable constant processor recurses inside the innerShaper just like any other expression tree node - let me know if I'm missing something.

<details>
<summary>Full code</summary>

```c#
await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

_ = await context.Blogs.ToListAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().ComplexProperty(b => b.Details, b => b.ToJson());
    }
}

public class Blog
{
    public int Id { get; set; }

    public BlogDetails Details { get; set; }
}

public class BlogDetails
{
    public string Foo { get; set; }
    public int Bar { get; set; }
}
```

</details>

<details>
<summary>Full shaper dump</summary>

```c#
queryContext => SingleQueryingEnumerable.Create<Blog>(
    relationalQueryContext: (RelationalQueryContext)queryContext, 
    relationalCommandResolver: parameters => [LIFTABLE Constant: RelationalCommandCache.QueryExpression(
        Projection Mapping:
            EmptyProjectionMember -> Dictionary<IPropertyBase, int> { [Property: Blog.Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd, 0], [ComplexProperty: Blog.Details (BlogDetails) Required, 1] }
        SELECT b.Id, b.Details -> 
        FROM Blogs AS b) | Resolver: c => new RelationalCommandCache(
        c.Dependencies.MemoryCache, 
        c.RelationalDependencies.QuerySqlGeneratorFactory, 
        c.RelationalDependencies.RelationalParameterBasedSqlProcessorFactory, 
        Projection Mapping:
            EmptyProjectionMember -> Dictionary<IPropertyBase, int> { [Property: Blog.Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd, 0], [ComplexProperty: Blog.Details (BlogDetails) Required, 1] }
        SELECT b.Id, b.Details -> 
        FROM Blogs AS b, 
        False, 
        MultipleParameters
    )].GetRelationalCommandTemplate(parameters), 
    readerColumns: null, 
    shaper: (queryContext, dataReader, resultContext, resultCoordinator) => 
    {
        Blog entity;
        Stream jsonStream;
        JsonReaderData jsonReader;
        Utf8JsonReaderManager jsonReaderManager;
        jsonStream = dataReader.IsDBNull(1) ? default(MemoryStream) : SqlServerStructuralJsonTypeMapping.CreateUtf8Stream(dataReader.GetString(1));
        jsonReader = jsonStream == default(MemoryStream) ? default(JsonReaderData) : new JsonReaderData(jsonStream);
        jsonReader != default(JsonReaderData) ? 
        {
            jsonReaderManager = new Utf8JsonReaderManager(
                jsonReader, 
                queryContext.QueryLogger
            );
            jsonReaderManager.MoveNext();
            jsonReaderManager.CaptureState();
        } : default(void);
        entity = 
        {
            MaterializationContext materializationContext1;
            IEntityType entityType1;
            Blog instance1;
            InternalEntityEntry entry1;
            bool hasNullKey1;
            materializationContext1 = new MaterializationContext(
                [LIFTABLE Constant: ValueBuffer | Resolver: _ => (object)ValueBuffer.Empty], 
                queryContext.Context
            );
            instance1 = default(Blog);
            entry1 = queryContext.TryGetEntry(
                key: [LIFTABLE Constant: Key: Blog.Id PK | Resolver: c => c.Dependencies.Model.FindEntityType("Blog").FindPrimaryKey()], 
                keyValues: new object[]{ (object)dataReader.GetInt32(0) }, 
                throwOnNullKey: True, 
                hasNullKey: hasNullKey1);
            !(hasNullKey1) ? entry1 != default(InternalEntityEntry) ? 
            {
                entityType1 = entry1.EntityType;
                return instance1 = (Blog)entry1.Entity;
            } : 
            {
                ISnapshot shadowSnapshot1;
                shadowSnapshot1 = [LIFTABLE Constant: Snapshot | Resolver: _ => Snapshot.Empty];
                entityType1 = [LIFTABLE Constant: EntityType: Blog | Resolver: namelessParameter{0} => namelessParameter{0}.Dependencies.Model.FindEntityType("Blog")];
                instance1 = switch (entityType1)
                {
                    case [LIFTABLE Constant: EntityType: Blog | Resolver: namelessParameter{1} => namelessParameter{1}.Dependencies.Model.FindEntityType("Blog")]: 
                        {
                            return 
                            {
                                Blog instance;
                                instance = new Blog();
                                instance.<Id>k__BackingField = dataReader.GetInt32(0);
                                (instance is IInjectableService) ? ((IInjectableService)instance).Injected(
                                    context: materializationContext1.Context, 
                                    entity: instance, 
                                    queryTrackingBehavior: TrackAll, 
                                    structuralType: [LIFTABLE Constant: EntityType: Blog | Resolver: namelessParameter{2} => namelessParameter{2}.Dependencies.Model.FindEntityType("Blog")]) : default(void);
                                return instance;
                            }}
                    default: 
                        default(Blog)
                }
                ;
                ShaperProcessingExpressionVisitor.IncludeJsonEntityReference<Blog, BlogDetails>(
                    queryContext: queryContext, 
                    keyPropertyValues: null, 
                    jsonReaderData: jsonReader, 
                    structuralType: instance1, 
                    innerShaper: (queryContext, namelessParameter{3}, namelessParameter{4}) => 
                    {
                        BlogDetails entityShaperMaterializer;
                        return entityShaperMaterializer = 
                        {
                            MaterializationContext materializationContext2;
                            IComplexType entityType2;
                            BlogDetails instance2;
                            materializationContext2 = new MaterializationContext(
                                [LIFTABLE Constant: ValueBuffer | Resolver: _ => (object)ValueBuffer.Empty], 
                                queryContext.Context
                            );
                            instance2 = default(BlogDetails);
                            {
                                ISnapshot shadowSnapshot2;
                                shadowSnapshot2 = [LIFTABLE Constant: Snapshot | Resolver: _ => Snapshot.Empty];
                                entityType2 = [LIFTABLE Constant: ComplexType: Blog.Details#BlogDetails (BlogDetails) | Resolver: namelessParameter{5} => namelessParameter{5}.Dependencies.Model.FindEntityType("Blog").FindComplexProperty("Details").ComplexType];
                                instance2 = 
                                {
                                    Utf8JsonReaderManager jsonReaderManager;
                                    JsonTokenType tokenType;
                                    BlogDetails instance;
                                    int namelessParameter{6};
                                    string namelessParameter{7};
                                    jsonReaderManager = new Utf8JsonReaderManager(
                                        namelessParameter{4}, 
                                        queryContext.QueryLogger
                                    );
                                    tokenType = jsonReaderManager.CurrentReader.TokenType;
                                    Loop(Break: done Continue: )
                                    {
                                        {
                                            tokenType = jsonReaderManager.MoveNext();
                                            switch (tokenType)
                                            {
                                                case PropertyName: 
                                                    jsonReaderManager.CurrentReader.ValueTextEquals((ReadOnlySpan<byte>)Encoding.UTF8.GetBytes("Bar")
                                                        .AsSpan()) ? 
                                                    {
                                                        jsonReaderManager.MoveNext();
                                                        namelessParameter{6} = (int)[LIFTABLE Constant: JsonInt32ReaderWriter | Resolver: c => c.Dependencies.Model.FindEntityType("Blog").FindComplexProperty("Details").ComplexType.FindProperty("Bar").GetJsonValueReaderWriter() ?? c.Dependencies.Model.FindEntityType("Blog").FindComplexProperty("Details").ComplexType.FindProperty("Bar").GetTypeMapping().JsonValueReaderWriter].FromJsonTyped(
                                                            manager: jsonReaderManager, 
                                                            existingObject: default(object));
                                                    } : jsonReaderManager.CurrentReader.ValueTextEquals((ReadOnlySpan<byte>)Encoding.UTF8.GetBytes("Foo")
                                                        .AsSpan()) ? 
                                                    {
                                                        jsonReaderManager.MoveNext();
                                                        namelessParameter{7} = (string)[LIFTABLE Constant: JsonStringReaderWriter | Resolver: c => c.Dependencies.Model.FindEntityType("Blog").FindComplexProperty("Details").ComplexType.FindProperty("Foo").GetJsonValueReaderWriter() ?? c.Dependencies.Model.FindEntityType("Blog").FindComplexProperty("Details").ComplexType.FindProperty("Foo").GetTypeMapping().JsonValueReaderWriter].FromJsonTyped(
                                                            manager: jsonReaderManager, 
                                                            existingObject: default(object));
                                                    } : default(void)
                                                case EndObject: 
                                                    Goto(break done)
                                                default: 
                                                    {
                                                        jsonReaderManager.Skip();
                                                    }
                                            }
                                        }}
                                    jsonReaderManager.CaptureState();
                                    instance = new BlogDetails();
                                    instance.<Bar>k__BackingField = namelessParameter{6};
                                    instance.<Foo>k__BackingField = namelessParameter{7};
                                    return instance;
                                };
                                return instance2;
                            }return instance2;
                        };
                    }, 
                    fixup: (namelessParameter{8}, namelessParameter{9}) => 
                    {
                        return namelessParameter{8}.<Details>k__BackingField = namelessParameter{9};
                    }, 
                    performFixup: True);
                entry1 = entityType1 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(
                    entityType: entityType1, 
                    entity: instance1, 
                    snapshot: shadowSnapshot1);
                return instance1;
            } : default(void);
            return instance1;
        };
        return entity;
    }, 
    contextType: BlogContext, 
    standAloneStateManager: False, 
    detailedErrorsEnabled: False, 
    threadSafetyChecksEnabled: True)
```

</details>

**Comment by cincuranet** [comment]
I did override `VisitNew` in `LiftableConstantProcessor` and printed all types there. This the result.

```text
Microsoft.EntityFrameworkCore.Storage.MaterializationContext
Parent
Microsoft.EntityFrameworkCore.Storage.MaterializationContext
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.Snapshot`1[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
Child
```

The `innerShaper` I'm talking about comes from [this](https://github.com/dotnet/efcore/blob/8fb7ff77048eb9b9d794e83f060f114dfbe7990f/src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs#L1030).

Did you have something else in mind?

**Comment by roji** [comment]
OK, let's not spend more time on this.
