### PR TITLE
BulkUpdates: Add custom CommandSource and exception messages

### LINKED ISSUE #28568: Update CommandSource and failure exception for ExecuteDelete/ExecuteUpdate

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #28568

### CODE REVIEW

File: src/EFCore.Relational/Diagnostics/CommandSource.cs [hunk 1]
```diff
@@ -61,5 +61,16 @@ public enum CommandSource
...
     ///     The command was generated as part of a bulk update.
     /// </summary>
-    BulkUpdate
+    [Obsolete("Use ExecuteDelete or ExecuteUpdate instead.")]
+    BulkUpdate,
+
+    /// <summary>
+    ///     The command was generated as part of an 'ExecuteDelete' operation.
+    /// </summary>
+    ExecuteDelete = 9,
```
Comment (roji) [inline src/EFCore.Relational/Diagnostics/CommandSource.cs:70]: Is it intentional to explicitly set a value only here? I don't think we need explicit enum values here in general, but if we do, shouldn't we do it for all values?

**Review by roji — APPROVED** [review]
We should probably add tests for all this at some point.

File: src/EFCore.Relational/Diagnostics/CommandSource.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.Relational/Diagnostics/CommandSource.cs:70]: I added here so that if we accidentally remove the obsolete value, the enum doesn't change values.

Comment (smitpatel) [reply src/EFCore.Relational/Diagnostics/CommandSource.cs:70]: cc: @AndriySvyryd - Thoughts?
