### PR TITLE
Warn when uniquifying an FK column name

### LINKED ISSUE #20435: Warn when uniquifying an FK column name
Consider the case where there is a candidate FK property by name in the dependent CLR type, but it doesn't work for the FK for some other reason--commonly, that the type of the property is not compatible with the type of the PK property. In this case we currently create a shadow property with a uniquified name--e.g. `BlogId1`. I assert that this is almost always not what is wanted. We should consider making this a warning, or perhaps even an error by default.

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #20435

### CODE REVIEW

File: src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs [hunk 1]
```diff
@@ -4466,6 +4466,14 @@ public virtual bool ShouldReuniquifyTemporaryProperties(ForeignKey foreignKey)
                                     return (false, null);
                                 }
 
+                                if (index > 0)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs:4469]:
```suggestion
                                if (index == 1)
```

File: test/EFCore.Specification.Tests/Query/ManyToManyFieldsQueryFixtureBase.cs [hunk 2]
```diff
@@ -288,6 +288,13 @@ protected override void OnModelCreating(ModelBuilder modelBuilder, DbContext con
                     r => r.HasOne<EntityTwo>().WithMany().HasForeignKey(e => e.TwoId),
                     l => l.HasOne<EntityOne>().WithMany().HasForeignKey(e => e.OneId));
 
+            modelBuilder.Entity<JoinOneToThreePayloadFull>(
+                b =>
+                {
+                    b.Property(e => e.OneId);
+                    b.Property(e => e.ThreeId);
```
Comment (AndriySvyryd) [inline test/EFCore.Specification.Tests/Query/ManyToManyFieldsQueryFixtureBase.cs:295]: Why did you have to configure these?

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs (hunk 1 above)
Comment (ajcvickers) [reply src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs:4469]: Why only for 1?

File: test/EFCore.Specification.Tests/Query/ManyToManyFieldsQueryFixtureBase.cs (hunk 2 above)
Comment (ajcvickers) [reply test/EFCore.Specification.Tests/Query/ManyToManyFieldsQueryFixtureBase.cs:295]: They are fields, not properties, and hence they don't get mapped by default. However, in this case I have a note to file a bug because a) I'm not sure that they should need to be explicitly mapped first, and b) doing the same thing in the `UsingEntity` lambda (like in the case just below) doesn't work for this case and they instead have to be mapped _before_ doing the many-to-many config.

File: src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs]: `keyModifiedBaseName` won't change, so no reason to do extra work

Comment (ajcvickers) [reply src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs]: @AndriySvyryd True, but the uniquified name that goes into the exception message is different, right?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs]: Yes

Comment (ajcvickers) [reply src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs]: So...shouldn't we do for anything greater than 0 then? What am I missing?
