### PR TITLE
[release/3.1] Query: Map projection properly when joining 2 tables

### LINKED ISSUE #19616: ArgumentOutOfRangeException upon certain queries with includes
Certain queries with includes are causing an `ArgumentOutOfRangeException`.

When using OData, almost (or possibly) all queries with more than one expand of a collection and translating to SQL fails with the following error:

screencapture-localhost-15580-odata-Movies-2020-01-17-05_07_47

### Steps to reproduce

A very quick repro, download [this zip](https://github.com/dotnet/efcore/files/4075131/AspNetCore3xODataSample.Web.zip), extract it in the src folder, open `All.sln`, add the zipped project as an existing project, make sure the project references are set correctly and run. It will create a local SQL database on your machine. And it will fail to run the following query:

    http://localhost:15580/odata/Movies?$expand=Stars,Writers

If you remove either one of the expands, it works. I wasn't sure whether to post to OData or here, but I think the issue lies here.

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.5 Preview 1

### PR DESCRIPTION
**Pull request by smitpatel**
When joining 2 tables in relational, we lift the table from inner select expression and copy over projections. If one of this projection is same as any outer projection then we reuse the same projection. That means the associated indexes in inner shaper will go to different indexes rather than in linear fashion.

Fix is to remember which index each projection went and use that rather than applying an offset.

Resolves #19616

### Description

Inside Select, if subquery Select contains a constant/parameter, which is in parent Select or other subquery's Select then we project it only once in SQL causing projection indexes mismatch.

### Customer Impact

Problematic queries throws exception.

### How found

Reported by multiple customers.

### Test coverage

Added regression test for scenario in which projection indexes would become non-linear.

### Regression?

Yes. From 2.2 to 3.0

### Risk

Low. The modified codepath is being used in more than 15,000 tests. It properly takes care of existing working scenarios.

### CODE REVIEW

**Comment by ajcvickers** [comment]
Quirk?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -926,7 +928,10 @@ static Expression RemoveConvert(Expression expression)
                 AppendOrdering(new OrderingExpression(updatedColumn, ascending: true));
             }
 
-            var shaperRemapper = new ShaperRemappingExpressionVisitor(this, innerSelectExpression, indexOffset);
+            var shaperRemapper = AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue19616", out var isEnabled)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs]: @ajcvickers

**Comment by jamshedd** [comment]
Approved for 3.1.4.

**Comment by ajcvickers** [comment]
Approved by tactics for 3.1.4. Wait for branch to open before merging.
