### PR TITLE
Fix scaffolding NRT issues

### LINKED ISSUE #19496: Scaffolding: nullablility annotation issues
My VS build currently fails with this
```
4>D:\code\EntityFrameworkCore\src\EFCore.SqlServer\Scaffolding\Internal\SqlServerDatabaseModelFactory.cs(634,50,634,59): error CS8604: Possible null reference argument for parameter 'name' in 'string SqlServerDatabaseModelFactory.DisplayName(string? schema, string name)'.
4>D:\code\EntityFrameworkCore\src\EFCore.SqlServer\Scaffolding\Internal\SqlServerDatabaseModelFactory.cs(854,96,854,105): error CS8604: Possible null reference argument for parameter 'name' in 'string SqlServerDatabaseModelFactory.DisplayName(string? schema, string name)'.
4>D:\code\EntityFrameworkCore\src\EFCore.SqlServer\Scaffolding\Internal\SqlServerDatabaseModelFactory.cs(887,108,887,117): error CS8604: Possible null reference argument for parameter 'name' in 'string SqlServerDatabaseModelFactory.DisplayName(string? schema, string name)'.
4>D:\code\EntityFrameworkCore\src\EFCore.SqlServer\Scaffolding\Internal\SqlServerDatabaseModelFactory.cs(889,80,889,110): error CS8604: Possible null reference argument for parameter 'name' in 'DatabaseUniqueConstraint.DatabaseUniqueConstraint(DatabaseTable table, string name)'.
4>D:\code\EntityFrameworkCore\src\EFCore.SqlServer\Scaffolding\Internal\SqlServerDatabaseModelFactory.cs(925,86,925,95): error CS8604: Possible null reference argument for parameter 'name' in 'string SqlServerDatabaseModelFactory.DisplayName(string? schema, string name)'.
4>D:\code\EntityFrameworkCore\src\EFCore.SqlServer\Scaffolding\Internal\SqlServerDatabaseModelFactory.cs(927,58,927,77): error CS8604: Possible null reference argument for parameter 'name' in 'DatabaseIndex.DatabaseIndex(DatabaseTable table, string name)'.
4>D:\code\EntityFrameworkCore\src\EFCore.SqlServer\Scaffolding\Internal\SqlServerDatabaseModelFactory.cs(1005,59,1005,77): error CS8604: Possible null reference argument for parameter 'name' in 'string SqlServerDatabaseModelFactory.DisplayName(string? schema, string name)'.
4>D:\code\EntityFrameworkCore\src\EFCore.SqlServer\Scaffolding\Internal\SqlServerDatabaseModelFactory.cs(1020,63,1020,81): error CS8604: Possible null reference argument for parameter 'name' in 'string SqlServerDatabaseModelFactory.DisplayName(string? schema, string name)'.
4>D:\code\EntityFrameworkCore\src\EFCore.SqlServer\Scaffolding\Internal\SqlServerDatabaseModelFactory.cs(1025,68,1025,74): error CS8604: Possible null reference argument for parameter 'name' in 'DatabaseForeignKey.DatabaseForeignKey(DatabaseTable table, string name, DatabaseTable principalTable)'.
4>D:\code\EntityFrameworkCore\src\EFCore.SqlServer\Scaffolding\Internal\SqlServerDatabaseModelFactory.cs(1027,63,1027,77): error CS8604: Possible null reference argument for parameter 'onDeleteAction' in 'ReferentialAction? SqlServerDatabaseModelFactory.ConvertToReferentialAction(string onDeleteAction)'.
4>D:\code\EntityFrameworkCore\src\EFCore.SqlServer\Scaffolding\Internal\SqlServerDatabaseModelFactory.cs(1051,67,1051,85): error CS8604: Possible null reference argument for parameter 'name' in 'string SqlServerDatabaseModelFactory.DisplayName(string? schema, string name)'.

```
Source of confusion is this
https://github.com/aspnet/EntityFrameworkCore/blob/e2ba1c8dab28db719f7a58cacba98dabc23390a7/src/EFCore.SqlServer/Scaffolding/Internal/SqlDataReaderExtension.cs#L41-L48

The file is marked as nullable enable so my understanding is `T` is non-null but then it does not match annotation on method. On the other hand if this method can return null then it is being used to pass argument to a method which does not accept null.

### PR DESCRIPTION
**Pull request by roji**
That only surface in preview versions of VS.

I've fixed this by using GetFieldValue instead of GetValueOrDefault when reading the relevant database values. I've taken a look (e.g. [here](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-foreign-keys-transact-sql)) and to my understanding, the affected columns (table/index/key/constraint name, delete referential action) can never be null in the database. In at least some of the cases, our own code would anyway throw immediately afterwards if null was ever returned (@bricelam can you please confirm this looks OK?).

Fixes #19496

### CODE REVIEW

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlDataReaderExtension.cs [hunk 1]
```diff
@@ -5,6 +5,8 @@
 using System.Diagnostics.CodeAnalysis;
 using JB = JetBrains.Annotations;
 
+#nullable enable
```
Comment (smitpatel) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlDataReaderExtension.cs]: The behavior of GetValueOrDefault is still incorrect. As annotation says, it could return null. And in practice also the method is about returning null if nothing on server side but the nullability annotation does not agree with it.

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 2]
```diff
@@ -987,10 +987,10 @@ private void GetForeignKeys(DbConnection connection, IReadOnlyList<DatabaseTable
 
                 var foreignKeyGroups = tableForeignKeyGroup
                     .GroupBy(
-                        c => (Name: c.GetValueOrDefault<string>("name"),
+                        c => (Name: c.GetFieldValue<string>("name"),
                             PrincipalTableSchema: c.GetValueOrDefault<string>("principal_table_schema"),
-                            PrincipalTableName: c.GetValueOrDefault<string>("principal_table_name"),
-                            OnDeleteAction: c.GetValueOrDefault<string>("delete_referential_action_desc")));
+                            PrincipalTableName: c.GetFieldValue<string>("principal_table_name"),
+                            OnDeleteAction: c.GetFieldValue<string>("delete_referential_action_desc")));
```
Comment (smitpatel) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: on delete action can be null. There is nothing in our code says it has be to present.

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlDataReaderExtension.cs (hunk 1 above)
Comment (roji) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlDataReaderExtension.cs]: > but the nullability annotation does not agree with it.

I'm not following, which annotation doesn't agree with it? Are you referring to it being `T` instead of `T?`?

`[return: MaybeNull]` is the only way to specify - for a generic return value - that it's nullable without adding a struct/class constraint ([see this post](https://devblogs.microsoft.com/dotnet/try-out-nullable-reference-types/)). Or maybe I'm misunderstanding what you're saying?

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 2 above)
Comment (roji) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: The question here is about whether SQL Server can return null or not, not about our model or code. [That doesn't seem to be the case according to the docs](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-foreign-keys-transact-sql), but if we feel there's a risk SQL Server will return a NULL here I don't have anything against allowing for that - let me know what you prefer.

Comment (smitpatel) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: Then consumer of this code can move away from handling value we cannot encounter. Currently it returns null. If we want to make our code future proof if SqlServer change any of this then we need to open that another value can come in. I don't have preference on either way how we read value. Value read and value processing should align on properly, which is not case right now.

**Comment by smitpatel** [comment]
Thinking more about this
- We should only use GetFieldValue if we are certain that we won't encounter null in database. (Bit hard of assumption since future version of SqlServer could break things). Otherwise better to read using default and throw if we see null value. GetFieldValue would throw highly un-useful exception message.
- Scaffolding for most part ignore things which it cannot handle. So if we see null constraint name, we could log a warning and ignore that constraint.

Above is irrespective of DatabaseModel. In DatabaseModel
- It is abstraction over all relational providers, are we certain that all providers have required constraint name?
- We could also define a default behavior like, if there is no name in database, we define default one in runtime. Our scaffolding is not fully round trip-able anyway. We try to do stuff which provide most value. And scaffolding such constraint could be more useful than ignoring.
- If we decide that 2 is not worth then we can throw exception or skip during scaffolding rather than let provider think what should they do with empty name constraint.

**Comment by roji** [comment]
> We should only use GetFieldValue if we are certain that we won't encounter null in database. (Bit hard of assumption since future version of SqlServer could break things). Otherwise better to read using default and throw if we see null value. GetFieldValue would throw highly un-useful exception message.
> Scaffolding for most part ignore things which it cannot handle. So if we see null constraint name, we could log a warning and ignore that constraint.

In many cases, being very defensive against future nulls seems a bit much - I doubt we'll ever get rows describing tables where the name is null, for instance. If we're talking about  throwing a more informative exception, we could simply fix that if/when it ever actually happens. Existing code before my PR already contained various assumptions about non-nulls coming back, but if we feel it's important to be more defensive against future changes in scaffolding I can make this change.

> It is abstraction over all relational providers, are we certain that all providers have required constraint name?

See previous discussion in https://github.com/aspnet/EntityFrameworkCore/pull/19321#discussion_r357918025 and @bricelam's suggestion in https://github.com/aspnet/EntityFrameworkCore/pull/19321#discussion_r360983307. As far as I know constraint names are a standard part of SQL, I'm not aware of any exceptions.

This is also somewhat related to the conversation in https://github.com/aspnet/EntityFrameworkCore/pull/19478#discussion_r363027354 - since I can't imagine an actual valid empty string value, we use that to convey that there was no name in the database, rather than having two possible values (null and empty string). This could be used to implement your suggestion of a default constraint name at runtime.

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 2 above)
Comment (roji) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: I'm not sure I follow (see some answers below). The question of how DatabaseModel looks like is separate from how SQL Server specifically scaffolds its information, no?

**Comment by smitpatel** [comment]
Filed https://github.com/aspnet/EntityFrameworkCore/issues/19513

**Comment by roji** [comment]
@smitpatel tested on VS 16.5.0 Preview 1.0, builds fine (how do I get on the preview 2 channel?). Applied decisions from design:

* Names for indices, foreign keys etc. are now nullable (also referential action).
* Table name is non-nullable, and we assume it comes non-null from the database.
