### PR TITLE
Fix to #11502 - Allow to specify constraint name for default values

### LINKED ISSUE #11502: Allow to specify constraint name for default values
Hello,

Is there any way to specify constraint name for default values, for example:

            builder.Property(x => x.CreatedDate)
                .IsRequired()
                .HasColumnType("DATETIME")
                .HasDefaultValueSql("GETDATE()")
                .HasConstraintName("DF_MyConstraint");

Thanks

### PR DESCRIPTION
**Pull request by maumar**
Adding model builder API to allow specifying explicit constraint name when adding default value (sql) to a column. Also added switch on the model level (opt-in) to switch from system-generated constraints to generating them automatically by name and storing in the model. This is opt-in because we don't want to cause unnecessary migrations. Added de-duplication logic in the finalize model step, in case our generated names happen to clash with ones specified explicitly by user.

Model builder APIs are exposed on the SQL Server level, but a lot of piping is in relational so that providers who support named constraints can take advantage of the feature.

Also split temporal tables migration tests for SqlServer into a separate file - there were way too many tests in MigrationsSqlServerTest

Fixes #11502

### CODE REVIEW

**Comment by maumar** [comment]
@AndriySvyryd is probably the best person to look at this

File: src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs [hunk 1]
```diff
@@ -2086,4 +2086,60 @@ public static void SetJsonPropertyName(this IMutableProperty property, string? n
...
+    /// <summary>
+    ///     Generates the default constraint name based on the table and column name.
+    /// </summary>
+    /// <param name="property">The property.</param>
+    /// <param name="storeObject">The store object identifier to generate the name from.</param>
+    public static string GenerateDefaultConstraintName(this IReadOnlyProperty property, in StoreObjectIdentifier storeObject)
+    {
+        var candidate = $"DF_{storeObject.Name}_{property.GetColumnName(storeObject)}";
+
+        return candidate.Length > 120 ? candidate[..120] : candidate;
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs:2108]:
```suggestion
        return Uniquifier.Truncate(candidate, property.DeclaringType.Model.GetMaxIdentifierLength());
```

File: src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs [hunk 2]
```diff
@@ -2086,4 +2086,60 @@ public static void SetJsonPropertyName(this IMutableProperty property, string? n
...
         => property.FindAnnotation(RelationalAnnotationNames.JsonPropertyName)?.GetConfigurationSource();
+
+    /// <summary>
+    ///     Gets the default constraint name.
+    /// </summary>
+    /// <param name="property">The property.</param>
+    public static string? GetDefaultConstraintName(this IReadOnlyProperty property)
+        => (property is RuntimeProperty)
+            ? throw new InvalidOperationException(CoreStrings.RuntimeModelMissingData)
+            : (string?)property[RelationalAnnotationNames.DefaultConstraintName];
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs:2097]: Also add `GetDefaultConstraintName` that takes an `StoreObjectIdentifier` and call it here with `StoreObjectIdentifier.Create(property.DeclaringType, StoreObjectType.Table)`

That overload will return the annotation if present, otherwise it will check whether named constraints are enabled on the model and if so call `GenerateDefaultConstraintName`.

This overload should also be called from `RelationalDefaultConstraintConvention` instead of `GenerateDefaultConstraintName` to make sure that the explicit name is taken into account

**Review by AndriySvyryd — APPROVED** [review]
