### PR TITLE
Query: Rewrite Entity Equality during translation phase

### LINKED ISSUE #13568: Query with null-coalesced entity gets client-evaluated
This query throws a `QueryClientEvaluationWarning`:
```C#
Blog a = ctx.Blogs.First();
Blog b = a;
ctx.Posts.Where(p => p.Blog == (a ?? b)).Count();
```

As a workaround, I can compare the PK instead of the navigation:
```C#
decimal? a = ctx.Blogs.First().Seqnr;
decimal? b = a;
ctx.Posts.Where(p => p.Blog.Seqnr == (a ?? b)).Count();
```

EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.Oracle
Operating system: Windows 10
IDE: Visual Studio Professional 2017 15.8.6

### LINKED ISSUE #13655: 'Nullable object must have a value' on client-side evaluated filter
I strongly suspect this to be a duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/13517 and https://github.com/aspnet/EntityFrameworkCore/issues/12951
but I needed to be sure.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Nullable object must have a value.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_NoValue()
   at System.Nullable`1.get_Value()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EF.BUG.Program.Main(String[] args) in C:\Sites\RestDrivenDomain.git\EF.BUG\Program.cs:line 68

```

### Steps to reproduce
```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using System;
using System.Collections.Generic;
using System.Linq;

namespace EF.BUG
{
    public class Review
    {
        public Guid Id { get; set; }
        public Warning Warning { get; set; }

        public Review()
        {
            Id = Guid.NewGuid();
        }
    }

    public class Warning
    {
        public Guid Id { get; set; }

        public Guid ReviewId { get; set; }
        public Review Review { get; set; }

        public Warning()
        {
            Id = Guid.NewGuid();
        }
    }

    public class DataContext : DbContext
    {
        public DataContext(DbContextOptions<DataContext> options) : base(options) { }

        public DbSet<Review> Reviews { get; set; }
        public DbSet<Warning> Warnings { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var dbName = Guid.NewGuid().ToString();
            var options = new DbContextOptionsBuilder<DataContext>()
                .UseSqlServer($@"Server=(localdb)\mssqllocaldb;Database={dbName};Trusted_Connection=True;ConnectRetryCount=0")
                //.ConfigureWarnings(warnings => warnings.Throw(RelationalEventId.QueryClientEvaluationWarning))
                .Options;

            try
            {
                using (var context = new DataContext(options))
                {
                    context.Database.EnsureCreated();

                    context.Add(new Review { Warning = new Warning() });
                    context.Add(new Review());
                    context.SaveChanges();
                }

                using (var context = new DataContext(options))
                {
                    var elements = new List<Warning> { null };

                    //throws InvalidOperationException
                    //client-side evaluation
                    var result = context.Set<Review>().Where(r => !elements.Contains(r.Warning)).ToList();
                }
            }
            finally
            {
                using (var context = new DataContext(options))
                {
                    context.Database.EnsureDeleted();
                }
            }
        }
    }
}
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.7

### LINKED ISSUE #15080: QueryRewrite: when comparing entity with composite key to null, only check it's first key property, rather than all of them
Query:

```cs
from g1 in gs
join g2 in gs on g1.HasSoulPatch equals true into grouping
from g2 in grouping.DefaultIfEmpty()
orderby g2.Nickname
select g2 != null
  ? new
  {
	  g2.Nickname,
	  Five = 5
  }
  : null
```

Expected:

```sql
SELECT CASE
    WHEN [t].[Nickname] IS NOT NULL
    THEN CAST(1 AS bit) ELSE CAST(0 AS bit)
END, [t].[Nickname]
FROM [Gears] AS [g1]
LEFT JOIN (
    SELECT [g2].*
    FROM [Gears] AS [g2]
    WHERE [g2].[Discriminator] IN (N'Officer', N'Gear')
) AS [t] ON [g1].[HasSoulPatch] = CAST(1 AS bit)
WHERE [g1].[Discriminator] IN (N'Officer', N'Gear')
ORDER BY [t].[Nickname]
```

current:

```sql
SELECT CASE
    WHEN [t].[Nickname] IS NOT NULL OR [t].[SquadId] IS NOT NULL
    THEN CAST(1 AS bit) ELSE CAST(0 AS bit)
END, [t].[Nickname]
FROM [Gears] AS [g1]
LEFT JOIN (
    SELECT [g2].*
    FROM [Gears] AS [g2]
    WHERE [g2].[Discriminator] IN (N'Officer', N'Gear')
) AS [t] ON [g1].[HasSoulPatch] = CAST(1 AS bit)
WHERE [g1].[Discriminator] IN (N'Officer', N'Gear')
ORDER BY [t].[Nickname]");
```

Tests affected:
Select_null_propagation_negative4
Select_null_propagation_negative5

### LINKED ISSUE #19431: Entity Equality: ArrayLength is not an entity reference
```C#
        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task Where_ToArray_Length_member(bool async)
        {
            return AssertQuery(
                async,
                ss => ss.Set<Customer>().Select(c => ss.Set<Order>().Where(o => o.CustomerID == c.CustomerID).ToArray())
                    .Where(e => e.Length == 0));
        }
```
It incorrectly identifies `e.Length` as entity reference and tries to rewrite it to entity equality which fails.
```
 Message: 
    System.ArgumentException : Expression of type 'System.Int32' cannot be used for parameter of type 'System.Object' of method 'System.Nullable`1[System.Int32] Property[Nullable`1](System.Object, System.String)' (Parameter 'arg0')
  Stack Trace: 
    ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
    Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
    EFPropertyExtensions.CreateEFPropertyExpression(Expression target, Type propertyDeclaringType, Type propertyType, String propertyName, Boolean makeNullable) line 135
    EFPropertyExtensions.CreateEFPropertyExpression(Expression target, IPropertyBase property, Boolean makeNullable) line 103
    EntityEqualityRewritingExpressionVisitor.CreatePropertyAccessExpression(Expression target, IProperty property) line 989
    EntityEqualityRewritingExpressionVisitor.CreateKeyAccessExpression(Expression target, IReadOnlyList`1 properties) line 943
    EntityEqualityRewritingExpressionVisitor.RewriteEntityEquality(Boolean equality, IEntityType entityType, Expression left, INavigation leftNavigation, Expression right, INavigation rightNavigation, Boolean subqueryTraversed) line 923
    EntityEqualityRewritingExpressionVisitor.RewriteEquality(Boolean equality, Expression left, Expression right) line 847
    EntityEqualityRewritingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression) line 186
    BinaryExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    EntityEqualityRewritingExpressionVisitor.RewriteAndVisitLambda(LambdaExpression lambda, EntityReferenceExpression source) line 762
    EntityEqualityRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 366
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    EntityEqualityRewritingExpressionVisitor.Rewrite(Expression expression) line 52
    QueryTranslationPreprocessor.Process(Expression query) line 38
    QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) line 74
    Database.CompileQuery[TResult](Expression query, Boolean async) line 71
    QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) line 112
    <>c__DisplayClass9_0`1.<Execute>b__0() line 96
    CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) line 84
    CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) line 59
    QueryCompiler.Execute[TResult](Expression query) line 92
    EntityQueryProvider.Execute[TResult](Expression expression) line 79
    EntityQueryable`1.GetEnumerator() line 95
    LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
    EnumerableHelpers.ToArray[T](IEnumerable`1 source)
    Enumerable.ToArray[TSource](IEnumerable`1 source)
    QueryAsserter`1.AssertQuery[TResult](Func`2 actualQuery, Func`2 expectedQuery, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount, Boolean async, String testMethodName) line 91
    --- End of stack trace from previous location where exception was thrown ---

```

### LINKED ISSUE #19676: Lazy loading proxy comparison throws"could not be translated" InvalidOperationException
A where clause comparing a lazy loading proxy to a navigation property of a table is throwing an InvalidOperationException like the one below on .NET Core 3.0 and 3.1. This worked on .NET Core 2.1. While it's possible to work around this by replacing a particular instance with a key comparison, tracking down all of the instances in our project would be a lot of work.

The error also suggests that EF is trying to do a join instead of just comparing the proxy's primary key to the child table's foreign key.

The query is:
```C#
 var eventTeams = await (from Team team in _context.Teams
      where team.Event == myEvent // proxy fetched by a previous query
      select team).ToListAsync();
```

The types involved are a simple parent-child relationship:

```C#
    public class Event
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        // other columns
    }

    public class Team
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        // The event the team is a part of
        public int EventID { get; set; }

        // The event the team is a part of
        [Required]
        public virtual Event Event { get; set; }

        // Other columns
    }
```

The full exception is:
```
  'The LINQ expression 'Where<TransparentIdentifier<Team, Event>>(
    source: Join<Team, Event, Nullable<int>, TransparentIdentifier<Team, Event>>(
        outer: Cast<Team>(DbSet<Team>), 
        inner: DbSet<Event>, 
        outerKeySelector: (e) => Property<Nullable<int>>(e, "EventID"), 
        innerKeySelector: (e0) => Property<Nullable<int>>(e0, "ID"), 
        resultSelector: (o, i) => new TransparentIdentifier<Team, Event>(
            Outer = o, 
            Inner = i
        )), 
    predicate: (e) => e.Inner == (Unhandled parameter: __myEvent_0))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
  at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

### Further technical details

EF Core version: 3.1
Database provider:Microsoft.EntityFrameworkCore.SqlServer
Target framework: 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.3

### LINKED ISSUE #20164: Query: Rewrite Entity Equality
The pattern of wrapping and unwrapping is just too leaky. Way too many expressions I encountered where it leaves behind internal states causing translation failures.
Either merge into nav rewrite since it has entity info or convert to a proper reducingEV pattern.

### LINKED ISSUE #20344: Enable throwing better exceptions for specific cases of failed translation
If it cannot rewrite it should just return original tree. Let client eval deal with it.

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #15080
Implemented behavior:
- If any part of composite key is null then key is null.
- If comparing entity with null then check if "any" key value is null.
- If comparing entity with non-null then check if "all" key values are non null.

Resolves #20344
Resolves #19431
Resolves #13568
Resolves #13655
Since we already convert property access to nullable, if entity from client is null, make key value as null.

Resolves #19676
Clr type mismatch between proxy type and entity type is ignored.

Resolves #20164
Rewrites entity equality during translation

Part of #18923

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs [hunk 1]
```diff
@@ -415,21 +438,126 @@ static bool IsAggregateResultWithCustomShaper(MethodInfo method)
...
+
+            if (method.Name == nameof(object.Equals)
+                && methodCallExpression.Object != null
+                && methodCallExpression.Arguments.Count == 1)
             {
-                return null;
+                var left = Visit(methodCallExpression.Object);
+                var right = Visit(methodCallExpression.Arguments[0]);
+
+                if (TryRewriteEntityEquality(ExpressionType.Equal,
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs]: if argument doesn't get translated, it can never be EntityReferenceExpression, so it will never be translated anyway. Why call try rewrite entity equality rather than short-circuit?

Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs]: The magic lies in `left ?? methodCallExpression.Object` call.
If you are doing `c == new Customer { CustomerID = e.SomeProperty }` then right side cannot be translated. But if you apply entity equality then you would convert the whole thing to `c.CustomerID == e.SomeProperty` hence even if left or right fails to translate we still run this. If both of them does not translate then yes, we cannot translate. Though TryRewriteEntityEquality short-circuit that case at very start. Putting it inside function makes it somewhat DRY.

File: src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs [hunk 2]
```diff
@@ -415,21 +438,126 @@ static bool IsAggregateResultWithCustomShaper(MethodInfo method)
...
+                    && item is SqlExpression sqlItem)
+                {
+                    arguments = new SqlExpression[2] { sqlEnumerable, sqlItem };
+                }
+                else
                 {
                     return null;
                 }
+            }
+            else if (method.Name == nameof(IList.Contains)
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs]: that looks like a useful helper method/extension - we already do this logic in ContainsTranslator, so DRY

File: src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs [hunk 3]
```diff
@@ -684,6 +812,197 @@ private static SqlConstantExpression GetConstantOrNull(Expression expression)
...
+            var entityType = itemEntityReference.EntityType;
+            var primaryKeyProperties = entityType.FindPrimaryKey()?.Properties;
+            if (primaryKeyProperties == null)
+            {
+                throw new InvalidOperationException(CoreStrings.EntityEqualityOnKeylessEntityNotSupported(entityType.DisplayName()));
+            }
+
+            if (primaryKeyProperties.Count > 1)
+            {
+                throw new InvalidOperationException(
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs]: we should be able to translate this to EXISTS, now that it's done in translation phase, no?

File: src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs [hunk 4]
```diff
@@ -684,6 +812,197 @@ private static SqlConstantExpression GetConstantOrNull(Expression expression)
...
+            {
+                result = null;
+                return false;
+            }
+
+            if (IsNullSqlConstantExpression(left)
+                || IsNullSqlConstantExpression(right))
+            {
+                var nonNullEntityReference = IsNullSqlConstantExpression(left) ? rightEntityReference : leftEntityReference;
+                var entityType1 = nonNullEntityReference.EntityType;
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs]: declare outside the block maybe?

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs [hunk 5]
```diff
@@ -699,5 +676,188 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
+            {
+                _logger = logger;
+            }
+
+            protected override Expression VisitBinary(BinaryExpression binaryExpression)
+            {
+                if (binaryExpression.NodeType == ExpressionType.Equal
+                    || binaryExpression.NodeType == ExpressionType.NotEqual)
+                {
+                    var left = ProcessNavigationPath(binaryExpression.Left);
```
Comment (maumar) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs]: those two lines could be moved to TryRemoveNavigationComparison - DRY

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs [hunk 6]
```diff
@@ -699,5 +676,188 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
+                        result = Expression.MakeBinary(
+                            nodeType, nonNullNavigationData.Inner.Current, Expression.Constant(null, nonNullNavigationData.Inner.Type));
+
+                        return true;
+                    }
+                }
+                else if (leftNavigationData != null
+                    && rightNavigationData != null)
+                {
+                    if (leftNavigationData.Navigation?.IsCollection == true)
```
Comment (maumar) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs]: what was the reason for doing this only for collections?

File: src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs (hunk 3 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs]: https://github.com/dotnet/efcore/issues/15260 is still open tracking it.

File: src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs (hunk 4 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs]: this is lesser code :trollface:

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs (hunk 6 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs]: This PR gets parity with what we have currently in source wrt entity equality. To keep things simple I have not added any enhancement. 
The particular thing you are asking is tracked by https://github.com/dotnet/efcore/issues/11495 & https://github.com/dotnet/efcore/issues/15936

File: test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs [hunk 7]
```diff
@@ -6960,7 +6960,13 @@ public void GroupJoin_SelectMany_in_defining_query_gets_flattened()
             }
 
             AssertSql(
-                @"SELECT [c].[Id], [c].[Name], [c0].[Id], [c0].[CustomerId], [c0].[Name]
+    @"SELECT [c].[Id], [c].[Name], CASE
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs]: this case block should get optimized to [c0].[Id]

File: test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs [hunk 8]
```diff
@@ -15,6 +15,7 @@
 using Microsoft.EntityFrameworkCore.TestUtilities;
 using Microsoft.Extensions.DependencyInjection;
 using Xunit;
+using Xunit.Sdk;
```
Comment (maumar) [inline test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs]: nit: remove

File: test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs (hunk 7 above)
Comment (smitpatel) [reply test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs]: Where should that happen?
Looking at the second case block and alias-ing, it seems that whole client eval thing has changed underneath. Since it is using defining query, I did not look into trying to optimize this particular test (defining query should be dead for non-inmemory provider).
If you want we can have tracking issue to identifying this pattern in Sql to shorten it. It could also be dependency thing in null check removal.

Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs]: we already have https://github.com/dotnet/efcore/issues/19662 but I thought at least the simple property case has already been optimized. We had that for sure in the old pipeline and I know we stripped some of the functionality during pipeline redesign. I guess we stripped more than I thought ;)

Comment (smitpatel) [reply test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs]: Fixed. Not sure what was happening before this PR, had to run null check removal after introducing defining query. Overall it should improve once I can move it after nav expansion as part of #18923

Comment (smitpatel) [reply test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs]: Also it is more accurate than before since we don't ignore empty string and also preserve the aliasing.
