### PR TITLE
Query: Fix double negation in SQL generation

### LINKED ISSUE #26309: Problem with SQL-translation of double Negate: -(-column)
EFCore 6.0

Seems, your infrastructure incorrect translate the double negate operation:

**MSSQL test**

```c#
ss => ss.Set<Squad>().Where(s => -(-s.Id) == -s.Id))
```
**Error message** 
> Microsoft.Data.SqlClient.SqlException : Incorrect syntax near 'WHERE'.

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #26309

### CODE REVIEW

File: src/EFCore.Relational/Query/QuerySqlGenerator.cs [hunk 1]
```diff
@@ -676,20 +676,56 @@ protected override Expression VisitSqlUnary(SqlUnaryExpression sqlUnaryExpressio
...
+                    if (requiresBrackets)
+                    {
+                        _relationalCommandBuilder.Append("(");
+                    }
+
                     Visit(sqlUnaryExpression.Operand);
+                    if (requiresBrackets)
+                    {
+                        _relationalCommandBuilder.Append(")");
+                    }
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/QuerySqlGenerator.cs:727]: Add tests for the above 3 cases where parentheses are needed

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore.Relational/Query/QuerySqlGenerator.cs [hunk 2]
```diff
@@ -799,6 +835,13 @@ protected virtual bool RequiresParentheses(SqlExpression outerExpression, SqlExp
                         return true;
                     }
 
+                    if (sqlUnaryExpression.OperatorType == ExpressionType.Negate
+                        && outerExpression is SqlUnaryExpression { OperatorType: ExpressionType.Negate })
+                    {
+                        // double negative sign has different meaning so we need to enclose it in brackets
```
Comment (roji) [inline src/EFCore.Relational/Query/QuerySqlGenerator.cs:841]:
```suggestion
                        // double negative sign is interpreted as a comment in SQL, so we need to enclose it in brackets
```

File: src/EFCore.Relational/Query/QuerySqlGenerator.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/QuerySqlGenerator.cs:727]: The thing is they are not needed atm. It is here so that provide can influence if they need to.

Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/QuerySqlGenerator.cs:727]: Wouldn't it trigger for something like `(a == b) == (c != d)` ?

Comment (smitpatel) [reply src/EFCore.Relational/Query/QuerySqlGenerator.cs:727]: That is binary operation when left and right are also binary operation. We add brackets for that already. (This method is SqlUnary. Equal/NotEqual here represents a IS NULL a IS NOT NULL.

Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/QuerySqlGenerator.cs:727]: Gotcha
