### PR TITLE
Log warning when credentials used for reverse enigineering does not have view definition rights

### LINKED ISSUE #22842: dotnet ef dbcontext scaffold doesn't work with computed columns unless user is db_owner
To reproduce:
Create a new DB called TestDB, add table Table_1, add column "test" make primary key, run  `alter table Table_1 add CalcField as (test + 'test-o-rama')`
image

then from ef core project run 
image

Result, note `.HasComputedColumnSql` is there
image

Now run with a user that has only db_datareader and db_datawriter:
image

Everything still scaffolds, and there is no error, but the  `.HasComputedColumn` is gone, which really messes things up when trying to write back to the database since EF now tries to overwrite that column resulting in errors.
image

One would think that db_datareader would either be enough to scaffold correctly, or an error would throw.  It would be vastly preferable to not have to give everyone db_owner if they need to scaffold the DB.

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #22842

### CODE REVIEW

File: src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs [hunk 1]
```diff
@@ -70,7 +70,8 @@ private enum Id
             ReflexiveConstraintIgnored,
             DuplicateForeignKeyConstraintIgnored,
             ColumnWithoutTypeWarning,
-            ForeignKeyReferencesUnknownPrincipalTableWarning
+            ForeignKeyReferencesUnknownPrincipalTableWarning,
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs:73]: Line 36 and 37 here looks like an error waiting to happen... 
Maybe they should be removed?

File: src/EFCore.SqlServer/Properties/SqlServerStrings.resx [hunk 2]
```diff
@@ -248,6 +248,10 @@
     <value>Unable to find a table in the database matching the selected table '{table}'.</value>
     <comment>Warning SqlServerEventId.MissingTableWarning string?</comment>
   </data>
+  <data name="LogMissingViewDefinitionRights" xml:space="preserve">
+    <value>Aspects of your schema definition may be missing, as the credentials in use has not been granted 'VIEW DEFINITION' rights.</value>
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Properties/SqlServerStrings.resx:252]: Suggestions for phrasing this?

Comment (ErikEJ) [reply src/EFCore.SqlServer/Properties/SqlServerStrings.resx:252]: Could be:
Unable to reverse engineer your database, because the credentials used have not been granted 'VIEW DEFINITION' rights.

Comment (smitpatel) [reply src/EFCore.SqlServer/Properties/SqlServerStrings.resx:252]: cc: @dotnet/efteam for warning message review.

**Review by smitpatel — APPROVED** [review]

File: src/EFCore.SqlServer/Properties/SqlServerStrings.resx (hunk 2 above)
Comment (ajcvickers) [reply src/EFCore.SqlServer/Properties/SqlServerStrings.resx:252]: How about, "The database user has not been granted 'VIEW DEFINITION' rights. Scaffolding requires these rights to construct the Entity Framework model correctly. Without these rights, the parts of the scaffolded model may be missing, resulting in incorrect interactions between Entity Framework and the database at runtime."

Comment (ErikEJ) [reply src/EFCore.SqlServer/Properties/SqlServerStrings.resx:252]: LGTM, maybe just "parts" iso "the parts"?

Comment (ajcvickers) [reply src/EFCore.SqlServer/Properties/SqlServerStrings.resx:252]: @ErikEJ Corrected inline.

Comment (ErikEJ) [reply src/EFCore.SqlServer/Properties/SqlServerStrings.resx]: I have updated the message now

**Review by smitpatel — APPROVED** [review]

**Comment by smitpatel** [comment]
Thank you @ErikEJ
