### PR TITLE
Fix to #31100 - Switch to storing enums as ints in JSON instead of strings

### LINKED ISSUE #31100: Switch to storing enums as ints in JSON instead of strings
We currently serialize .NET enums into JSON as their string label; this is:

1. Incompatible with the behavior of System.Text.Json and Newtonsoft.Json, which serialize to the underlying int value.
2. Incompatible with our relational behavior, which also value-converts to the int value. This notably means that it's impossible to compare an enum value inside JSON with another enum value outside of JSON in a LINQ query.

### PR DESCRIPTION
**Pull request by maumar**
Problem was that in 7.0 we stored enums inside JSON as strings by default (by applying EnumToStringConverter by convention), but in 8.0 we are changing this to int. This is a breaking change and it's extra problematic for databases that used EF JSON functionality in 7.0. This can easily create a scenario where there is a mix of string and int representation for an enum value within the same document. (some data was added in 7.0, and then some in 8.0 before customer realized that the breaking change has been made). To mitigate this we are adding a fallback mechanism when reading enum data that is part of JSON entity. We try to read as int and if that fails we try to read again as string. This way should minimize the disruption, moreover any data saved back to the database will be saved in the new format, so over time everything should normalize. We will still throw when projecting individual enum properties of a JSON entity (as opposed to the entire entity), because materialization for this goes through different path, indistinguishable from normal enum value read from column in relational table.

Fixes #31100

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 1]
```diff
@@ -2357,6 +2362,47 @@ Expression valueExpression
...
+                && genericArgs[0] == converter.ModelClrType
+                && genericArgs[1] == converter.ProviderClrType)
+            {
+                // try
+                // {
+                //     JsonConvertedValueReaderWriter<MyEnumType, underlying_type>.FromJsonTyped(...));
+                // }
+                // catch(InvalidOperationException e)
+                // {
+                //      (MyEnumType)Enum.Parse(typeof(MyEnumType), jsonReaderManager.CurrentReader.GetString());
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:2387]: ideally, we would use `JsonConvertedReaderWriter<EnumType, string>` with the appropriate converter under the covers, but idk how to easily obtain/create one. @ajcvickers

Comment (maumar) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:2387]: EnumToStringConverter does (approx) `Enum.TryParse(out var v1) ? v1 : Enum.TryParse(ignorecase: true, out var v2) ? v2 : few_other_try_parses` - we could copy the logic, but my thought was to do the simplest/cheapest thing, since we didn't allow for any customization and only want to mitigate the legacy by-convention representation. Thoughts?

File: test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs [hunk 2]
```diff
@@ -707,6 +707,123 @@ public MyJsonEntityShadowPropertiesWithCtor(string name)
 
     #endregion
 
+    //#region EnumLegacyValues
+
+    //[ConditionalTheory]
```
Comment (maumar) [inline test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs:712]: will remove, unless we end up wanting to test for other providers also

File: test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryAdHocSqlServerTest.cs [hunk 3]
```diff
@@ -140,4 +142,158 @@ protected override void SeedShadowProperties(MyContextShadowProperties ctx)
...
+                x.Reference.ByteEnum,
+                x.Reference.LongEnum,
+                x.Reference.NullableEnum
+            });
+
+            var exception = async
+                ? await (Assert.ThrowsAsync<SqlException>(() => query.ToListAsync()))
+                : Assert.Throws<SqlException>(() => query.ToList());
+
+            // Conversion failed when converting the nvarchar value '...' to data type int
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryAdHocSqlServerTest.cs:169]: projecting enums from JSON entities directly (rather than entire JSON entity) will still throw - we use normal materialization code path here. In order to make this work we would have to add the fallback mechanism to every enum read, which seems like overkill. By making the entity working we at least provide way for people to cleanup their legacy data - by reading everything and then saving back. Does this make sense to ppl or should I add fallback for scalar reads as well?

**Comment by ajcvickers** [comment]
@AndriySvyryd @roji Took this over and updated to warn like we discussed.

File: src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs [hunk 4]
```diff
@@ -52,10 +54,17 @@ public class RelationalMapToJsonConvention : IEntityTypeAnnotationChangedConvent
...
         {
-            foreach (var enumProperty in jsonEntityType.GetDeclaredProperties().Where(p => p.ClrType.UnwrapNullableType().IsEnum))
+            foreach (var enumProperty in jsonEntityType
+                         .GetDeclaredProperties()
+                         .Where(p => p.ClrType.UnwrapNullableType().IsEnum))
             {
-                // by default store enums as strings - values should be human-readable
-                enumProperty.Builder.HasConversion(typeof(string));
+                // If the enum is mapped with no conversion, then use the reader/writer that handles legacy string values and warns.
+                if (enumProperty.GetValueConverter()?.ProviderClrType == null
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs:62]:
```suggestion
                if (enumProperty.GetValueConverter() == null
```

File: test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs (hunk 2 above)
Comment (AndriySvyryd) [reply test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs:709]: Remove

File: test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs [hunk 5]
```diff
@@ -16,8 +16,8 @@ public override async Task Add_element_to_json_collection_branch()
...
+"""
+@p0='[{"Date":"2101-01-01T00:00:00","Enum":1,"Enums":[0,-1,1],"Fraction":10.1,"NullableEnum":0,"NullableEnums":[null,-1,1],"OwnedCollectionLeaf":[{"SomethingSomething":"e1_r_c1_c1"},{"SomethingSomething":"e1_r_c1_c2"}],"OwnedReferenceLeaf":{"SomethingSomething":"e1_r_c1_r"}},{"Date":"2102-01-01T00:00:00","Enum":2,"Enums":[0,-1,1],"Fraction":10.2,"NullableEnum":1,"NullableEnums":[null,-1,1],"OwnedCollectionLeaf":[{"SomethingSomething":"e1_r_c2_c1"},{"SomethingSomething":"e1_r_c2_c2"}],"OwnedReferenceLeaf":{"SomethingSomething":"e1_r_c2_r"}},{"Date":"2010-10-10T00:00:00","Enum":2,"Enums":null,"Fraction":42.42,"NullableEnum":null,"NullableEnums":null,"OwnedCollectionLeaf":[{"SomethingSomething":"ss1"},{"SomethingSomething":"ss2"}],"OwnedReferenceLeaf":{"SomethingSomething":"ss3"}}]' (Nullable = false) (Size = 784)
```
Comment (AndriySvyryd) [inline test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs:20]: Do we have an issue tracking setting this size to something that doesn't pollute the query cache?

**Review by AndriySvyryd — APPROVED** [review]

File: test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs (hunk 5 above)
Comment (ajcvickers) [reply test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs:20]: @roji?
