### PR TITLE
Query: Disallow FromSql on owner when owned navigation is mapped to s…

### LINKED ISSUE #21769: Disallow FromSql over entity type when selecting data from owned reference navigations
``` C#
System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.FromSqlExpression' to type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression'.
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.GetPropertyExpressionsFromSubquery(IEntityType entityType, ColumnExpression identifyingColumn, Boolean nullable)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.TryExpand(Expression source, MemberIdentity member)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.WeakEntityExpandingExpressionVisitor.Expand(SelectExpression selectExpression, Expression lambdaBody)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.ExpandWeakEntities(SelectExpression selectExpression, Expression lambdaBody)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DbTest.Program.Main(String[] args) in D:\zhaoyl\source\repos\DbTest\DbTest\Program.cs:line 13
```

### Steps to reproduce
``` C#
    class Program
    {
        static void Main(string[] args)
        {
            using var db = new TestDbContext();
            db.Database.EnsureCreated();
            db.Entities.FromSqlRaw("select * from Entities").Where(a => a.Prop == "111").ToList();
            Console.ReadKey();
        }
    }

    public class Entity
    {
        public int Id { get; set; }
        public string Prop { get; set; }
    }

    public class TestDbContext :DbContext
    {
        public static readonly ILoggerFactory MyLoggerFactory = LoggerFactory.Create(builder => { builder.AddConsole(); });
        public DbSet<Entity> Entities { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=TestDb;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")
            .UseLoggerFactory(MyLoggerFactory);
        }
    }
```

### Further technical details

EF Core version: 5.0.0-preview.7.20365.15
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.6.4

### PR DESCRIPTION
**Pull request by smitpatel**
…ame table

Resolves #21769

It would still work if owned navigation data is not accessed. Though keep in mind that selecting entity will bring owned data too due to auto include

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 1]
```diff
@@ -1366,11 +1366,8 @@ private Expression TryExpand(Expression source, MemberIdentity member)
                             || (entityType.GetDiscriminatorProperty() == null
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1366]: TODO: The code above that gets `table` should also handle Function and SqlQuery mappings

Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1366]: Is it possible to get it from `_selectExpression` instead of duplicating logic?

File: src/EFCore.Relational/Properties/RelationalStrings.resx [hunk 2]
```diff
@@ -726,4 +726,7 @@
   <data name="TableValuedFunctionNonTPH" xml:space="preserve">
     <value>The element type of result of '{dbFunction}' is mapped to '{entityType}'. This is not supported since '{entityType}' is part of hierarchy and does not contain a discriminator property.</value>
   </data>
+  <data name="CustomQueryMappingOnOwner" xml:space="preserve">
+    <value>Using 'FromSqlRaw' or 'FromSqlInterpolated' on owner entity type which is also using owned reference navigation sharing same table is not supported.</value>
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Properties/RelationalStrings.resx:730]:
```suggestion
    <value>Using 'FromSqlRaw' or 'FromSqlInterpolated' on an entity type which has owned reference navigations sharing same table is not supported.</value>
```

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1366]: Exactly get what from _selectExpression?

Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1366]: The `ITableBase` if there's a `TableExpression`

Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1366]: It is chicken-egg issue. Once we know the table and see that table is being shared, we can traverse down n level to find the TableExpression which would ultimately correspond to ITableBase.
The main difficulty comes 2 fold that
- The Tables for the `_selectExpression` may not be TableExpression but rather a subquery and actual table is hiding deep.
- The tables for the `_selectExpression` are TableExpression but in TPT there would be multiple and we need to find the one which matches ITableBase of what we are looking at. Identifying projection would not help in this.

Is there something functionally wrong here right now? or is it about future proofing? If later then I would happy to look over it when we get actual case so we can better understand what information we have and how we can get it optimally, rather than trying to guess a bit right now.

**Comment by smitpatel** [comment]
> Perhaps we should also block auto-included navs to types that are sharing the same table

For FromSql scenario? Non-owned? AutoInclude API navs?

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1366]: This is future proofing. We might need a bigger refactoring to make the mappings flow where needed

**Comment by AndriySvyryd** [comment]
> For FromSql scenario? Non-owned? AutoInclude API navs?

Yeeees

**Comment by smitpatel** [comment]
That is ok. Auto-include is just one cause but otherwise any navigation usage causes us to get the other query source. For non-owned scenario, the other query source forms own query root and can have own mapping used.
As one of the options was here also in the case that we can generate join to actual table to get data. For aggregate it makes less sense to pick from 2 different sources. For non-aggregate, it would be bit too much restriction.

There is also https://github.com/dotnet/efcore/issues/14525

**Comment by AndriySvyryd** [comment]
@smitpatel I understand that it's possible, it just seems ambiguous as to what shape `FromSql` expects when there are auto-includes with table-splitting. Perhaps this (and the owned case) can be overridden by an explicit `Include`.

needs-design?

**Comment by smitpatel** [comment]
Filed #21781

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1367]: Added TODO note for now. Future is bleak. :trollface:
