### PR TITLE
[release/8.0] Fix to #29156 - TemporalAll for temporal owned entities mapped to parent table.

### LINKED ISSUE #29156: TemporalAll for temporal owned entities mapped to parent table.
Hi All,

There are several related issues, but I couldn't find any issue on this specific topic. I apologize if it's a duplicate.
I read the conversations. I do see the point regarding data inconsistencies in cases where we have to include the navigations, especially from non-temporal tables. But, how about this scenario (which is very common)

- I have defined an owned entity mapped to the same parent table.
- The parent entity is defined as temporal.
- The owned entity is defined as temporal.
- Both, the parent and owned entity have mapped the period properties to the same columns (it's an EF requirement actually).

Issues:
- I can't use TemporalAll (with or without projection).
- I can't get correct data even with a raw query.
- I can't even exclude the navigation (since it's an owned entity).

It would be great if we can get any solution. I mean even some workaround. I'm open to any ideas from the team and community.

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614
 
Microsoft.EntityFrameworkCore.SqlServer
 Version:   "7.0.0-rc.1.22426.7"

### Full sample (ready to run). I listed 6 possible options.

```c#
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

await SeedAsync();

//await Read_Version1(); // Throws
//await Read_Version2(); // Throws
//await Read_Version3(); // Throws
await Read_Version4();
await Read_Version5();
await Read_Version6();


/// Throws an exception.
/// Navigation expansion is only supported for 'AsOf' temporal operation. For other operations use join manually.
async Task Read_Version1()
{
    using var dbContext = new AppDbContext();

    var customers = await dbContext.Customers
        .TemporalAll()
        .ToListAsync();

    Print(customers);
}

/// Throws with projection too.
/// Navigation expansion is only supported for 'AsOf' temporal operation. For other operations use join manually.
async Task Read_Version2()
{
    using var dbContext = new AppDbContext();

    var customers = await dbContext.Customers
        .TemporalAll()
        .Select(x => new
        {
            Id = x.Id,
            Name = x.Name,
            Email = x.Contact.Email,
            PeriodStart = EF.Property<DateTime>(x, "PeriodStart"),
            PeriodEnd = EF.Property<DateTime>(x, "PeriodEnd")
        })
        .ToListAsync();

    Print(customers);
}

/// Throws an exception (since both the parent and the owned entity contain these columns).
/// The column 'PeriodEnd' was specified multiple times for 'c'.
async Task Read_Version3()
{
    var table = "Customers";
    using var dbContext = new AppDbContext();

    var queryString = dbContext.Customers.ToQueryString();

    var sql = queryString.Replace($"[{table}]", $"[{table}] FOR SYSTEM_TIME ALL");
    var data = await dbContext.Customers
        .FromSqlRaw(sql)
        .AsNoTracking()
        .ToListAsync();

    Print(data);
}

/// Returns incorrect data. It return 3 records, and all of them have "Email1_Updated" value for Email.
/// It takes only the recent values of the owned type and assigns to all records.
/// Also, PeriodStart and PeriodEnd are omitted from the results. 
/// I assume since FromSqlRaw operates on Set<Customer>, and those are shadow fields only?
async Task Read_Version4()
{
    var table = "Customers";
    using var dbContext = new AppDbContext();

    var queryString = dbContext.Customers
        .Select(x => new
        {
            Id = x.Id,
            Name = x.Name,
            Email = x.Contact.Email,
            PeriodStart = EF.Property<DateTime>(x, "PeriodStart"),
            PeriodEnd = EF.Property<DateTime>(x, "PeriodEnd")
        })
        .ToQueryString();

    var sql = queryString.Replace($"[{table}]", $"[{table}] FOR SYSTEM_TIME ALL");
    var data = await dbContext.Customers
        .FromSqlRaw(sql)
        .AsNoTracking()
        .ToListAsync();

    Print(data);
}

/// Same issues as version 4.
async Task Read_Version5()
{
    using var dbContext = new AppDbContext();

    var data = await dbContext.Customers
        .FromSqlRaw("SELECT [c].[Id], [c].[Name], [c].[Contact_Email], [c].[PeriodStart], [c].[PeriodEnd] FROM [Customers] FOR SYSTEM_TIME ALL AS [c]")
        .AsNoTracking()
        .ToListAsync();

    Print(data);
}

/// Finally PeriodStart and PeriodEnd are projected to the result.
/// The Email values are still incorrect.
async Task Read_Version6()
{
    using var dbContext = new AppDbContext();

    var data = await dbContext.Customers
        .FromSqlRaw("SELECT [c].[Id], [c].[Name], [c].[Contact_Email], [c].[PeriodStart], [c].[PeriodEnd] FROM [Customers] FOR SYSTEM_TIME ALL AS [c]")
        .Select(x => new
        {
            Id = x.Id,
            Name = x.Name,
            Email = x.Contact.Email,
            PeriodStart = EF.Property<DateTime>(x, "PeriodStart"),
            PeriodEnd = EF.Property<DateTime>(x, "PeriodEnd")
        })
        .ToListAsync();

    Print(data);
}


async Task SeedAsync()
{
    using var dbContext = new AppDbContext();
    await dbContext.Database.EnsureDeletedAsync();
    await dbContext.Database.EnsureCreatedAsync();
    var customer = new Customer
    {
        Name = "Customer1",
        Contact = new Contact { Email = "Email1" }
    };
    dbContext.Customers.Add(customer);
    await dbContext.SaveChangesAsync();

    customer.Name = "Customer1_Updated";
    await dbContext.SaveChangesAsync();

    customer.Contact.Email = "Email1_Updated";
    await dbContext.SaveChangesAsync();
}

static void Print<T>(T data)
{
    var result = JsonSerializer.Serialize(data, new JsonSerializerOptions
    {
        WriteIndented = true
    });

    Console.WriteLine(result);
}

class AppDbContext : DbContext
{
    public DbSet<Customer> Customers => Set<Customer>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=EFTemporalDemo;Integrated Security=SSPI;ConnectRetryCount=0;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>().ToTable(x => x.IsTemporal());
        modelBuilder.Entity<Customer>().Property<DateTime>("PeriodStart").HasColumnName("PeriodStart");
        modelBuilder.Entity<Customer>().Property<DateTime>("PeriodEnd").HasColumnName("PeriodEnd");

        modelBuilder.Entity<Customer>().OwnsOne(x => x.Contact, cb =>
        {
            cb.ToTable(x => x.IsTemporal());
            cb.Property<DateTime>("PeriodStart").HasColumnName("PeriodStart");
            cb.Property<DateTime>("PeriodEnd").HasColumnName("PeriodEnd");
        });
    }
}

class Customer
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public Contact Contact { get; set; } = default!;
}

class Contact
{
    public string? Email { get; set; }
}
```

### PR DESCRIPTION
**Pull request by maumar**
Similar to JSON entities, owned entities that are mapped to the same table as their owner should be treated as scalars for the purpose of temporal query validation - they are always in sync with the parent entity, so all operations should be allowed for them, not only AsOf.

Fixes #29156

**Risk**

Low - this is very similar to the JSON scenario fixed approved for 8.0 recently (see https://github.com/dotnet/efcore/pull/32006) - we relax the validation we had when encountering navigations with temporal operations. We normally only allow AsOf, otherwise the results are not very useful/coherent, but in case of owned entities mapped to the same table, they are always in sync with parent, so all operations are fine.

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SqlServerNavigationExpansionExtensibilityHelper.cs [hunk 1]
```diff
@@ -69,6 +71,12 @@ public override void ValidateQueryRootCreation(IEntityType entityType, EntityQue
         base.ValidateQueryRootCreation(entityType, source);
     }
 
+    private bool OwnedEntityMappedToSameTableAsOwner(IEntityType entityType)
+        => entityType.IsOwned()
+            && entityType.FindOwnership()!.PrincipalEntityType.GetTableMappings().FirstOrDefault()?.Table is ITable ownerTable
+                && entityType.GetTableMappings().FirstOrDefault()?.Table is ITable entityTable
+                && ownerTable == entityTable;
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Query/Internal/SqlServerNavigationExpansionExtensibilityHelper.cs:78]: Why are you only checking table mappings, wouldn't the same apply for entity types only mapped to views?

Comment (maumar) [reply src/EFCore.SqlServer/Query/Internal/SqlServerNavigationExpansionExtensibilityHelper.cs:78]: we don't support "temporal views" (system-versioned views?) - ViewBuilder doesn't have API to set it to temporal.

**Review by AndriySvyryd — APPROVED** [review]
