### PR TITLE
Translate DateTimeOffset.ToUnixTime[Seconds|Milliseconds] 

### LINKED ISSUE #28925: Translate DateTimeOffset.ToUnixTime[Seconds|Milliseconds]
ToUnixTime* methods on DateTimeOffset can be translated in SQL Server as `DATEDIFF(second|millisecond, '1970-01-01T00:00:00.000', [Date])`. 

This can even be done today verbosely with `EF.Functions` as `EF.Functions.DateDiffSecond(DateTimeOffset.UnixEpoch, date)`. It would be nice if translation of ToUnixTimeSeconds/ToUnixTimeMilliseconds was supported natively.

### LINKED ISSUE #28975: All entity types sharing a CLR type must be configured as owned in 'OnModelCreating'.
Using Microsoft.EntityFrameworkCore 5.0.17 we get the following error:

`Failed to construct an Repository System.InvalidOperationException: The entity type 'Theme.LastChange#ChangeTracking' is configured as owned, but the entity type 'Tag.LastChange#ChangeTracking' is not. All entity types sharing a CLR type must be configured as owned in 'OnModelCreating'.`

Can anyone please explain what this new error message is supposed to mean? 
Why would entity types sharing a CLR type need to configured as owned? Are they not the OWNER? 
Surely, the CLR type being shared is the type that needs to be configured as owned? This is being explicitly done via Fluent in the map   for the owning types (example below) so why the new error message?

```
 public void Configure(EntityTypeBuilder<Tag> builder)
        {
            builder.ToTable("Tag");
            builder.HasKey(p => p.ID);
            builder.Ignore(p => p.State);

            builder.Property(p => p.ID).HasColumnName("ID");
            builder.Property(p => p.Name).HasColumnName("Name");
            builder.Property(p => p.Description).HasColumnName("Description");
            builder.Property(p => p.OwnerID).HasColumnName("OwnerID");
            builder.OwnsOne(obj => obj.LastChange,
                changeTracking =>
                {
                    changeTracking.Property(obj => obj.CreatedBy).HasColumnName("CreatedBy");
                    changeTracking.Property(obj => obj.CreatedWhen).HasColumnName("CreatedWhen");
                    changeTracking.Property(obj => obj.ModifiedBy).HasColumnName("ModifiedBy");
                    changeTracking.Property(obj => obj.ModifiedWhen).HasColumnName("ModifiedWhen");
                });
            builder.Property(p => p.SubscriptionID).HasColumnName("SubscriptionID");
}
```

### PR DESCRIPTION
**Pull request by Marusyk**
Added translation for `DateTimeOffset.ToUnixTime[Seconds|Milliseconds]`

Fixes #28925

Could anyone help me improve the tests? 
Thank you in advance

### CODE REVIEW

**Review by roji — CHANGES_REQUESTED** [review]
See also SQLite test failures, you probably need to implement those tests and assert on them failing (unless there's a translation on SQLite as well).

File: src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs [hunk 1]
```diff
@@ -139,6 +145,19 @@ public class SqlServerDateTimeMethodTranslator : IMethodCallTranslator
                 resultTypeMapping);
         }
 
+        if (_methodInfoDateDiffMapping.TryGetValue(method, out var timePart))
+        {
+            var startDate = _sqlExpressionFactory.Constant(DateTimeOffset.UnixEpoch);
```
[the remark this answers is not in the document]
Comment (Marusyk) [reply src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs:150]: do you mean `private static readonly DateTimeOffset UnixEpoch = DateTimeOffset.UnixEpoch;`?

**Comment by ajcvickers** [comment]
Marked as `blocked` since we shouldn't merge until we are actively working in `main` again.

File: src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs:150]: The 1st.

File: src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs [hunk 2]
```diff
@@ -139,6 +147,17 @@ public class SqlServerDateTimeMethodTranslator : IMethodCallTranslator
                 resultTypeMapping);
         }
 
+        if (_methodInfoDateDiffMapping.TryGetValue(method, out var timePart))
+        {
+            return _sqlExpressionFactory.ApplyDefaultTypeMapping(
+               _sqlExpressionFactory.Function(
+                   "DATEDIFF_BIG",
+                   new[] { _sqlExpressionFactory.Fragment(timePart), UnixEpoch, instance! },
```
Comment (smitpatel) [inline src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs:155]: UnixEpoch needs to get type mapping from instance.

File: test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs [hunk 3]
```diff
@@ -1945,4 +1945,26 @@ public virtual Task Datetime_subtraction_TotalDays(bool async)
...
+
+    [ConditionalTheory]
+    [MemberData(nameof(IsAsyncData))]
+    public virtual async Task DateTimeOffset_to_unix_time_milliseconds(bool async)
+    {
+        long unixEpochMilliseconds = DateTimeOffset.UnixEpoch.ToUnixTimeMilliseconds();
+
+        await AssertQuery(
+            async,
+            ss => ss.Set<Order>().Where(c => unixEpochMilliseconds == ((DateTimeOffset)c.OrderDate.Value).ToUnixTimeMilliseconds()));
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs:1957]: GearsOfWar test base has datetimeoffset propery. Move tests there and don't add cast in test.

File: test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs [hunk 4]
```diff
@@ -756,6 +756,12 @@ public override async Task IsNullOrEmpty_negated_in_predicate(bool async)
     public override Task Datetime_subtraction_TotalDays(bool async)
         => AssertTranslationFailed(() => base.Datetime_subtraction_TotalDays(async));
 
+    public override Task DateTimeOffset_to_unix_time_milliseconds(bool async)
+        => AssertTranslationFailed(() => base.DateTimeOffset_to_unix_time_milliseconds(async));
+
+    public override Task DateTimeOffset_to_unix_time_seconds(bool async)
+        => AssertTranslationFailed(() => base.DateTimeOffset_to_unix_time_seconds(async));
```
Comment (smitpatel) [inline test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs:763]: Sqlite has `unixepoch` function. It should work at least for seconds. Implement for Sqlite too. @bricelam would know if there is a way to translate for milliseconds too. Given we are just diffing with a different date, it may be possible.

**Comment by smitpatel** [comment]
Cosmos has `DateTimeToTicks` which returns ticks since unix epoch though not sure if Cosmos can handle DateTimeOffset as a type. Add translation if it is supported.

**Comment by roji** [comment]
Converting to draft for now as we're not merging this for 7.0.

File: test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs [hunk 5]
```diff
@@ -756,6 +756,12 @@ public override async Task IsNullOrEmpty_negated_in_predicate(bool async)
     public override Task Datetime_subtraction_TotalDays(bool async)
         => AssertTranslationFailed(() => base.Datetime_subtraction_TotalDays(async));
 
+    public override Task DateTimeOffset_to_unix_time_milliseconds(bool async)
+        => AssertTranslationFailed(() => base.DateTimeOffset_to_unix_time_milliseconds(async));
```
[the remark this answers is not in the document]
Comment (Marusyk) [reply test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs:760]: to do this I need to extend the `SqliteDateTimeAddTranslator`, right?

File: src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs (hunk 2 above)
Comment (Marusyk) [reply src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs:155]: Do you mean smth like
```
var typeMapping = ExpressionExtensions.InferTypeMapping(UnixEpoch, instance!);

            instance = _sqlExpressionFactory.ApplyTypeMapping(instance, typeMapping);
            var unixEpochArgument = _sqlExpressionFactory.ApplyTypeMapping(UnixEpoch, typeMapping);

            return _sqlExpressionFactory.ApplyDefaultTypeMapping(
               _sqlExpressionFactory.Function(
                   "DATEDIFF_BIG",
                   new[] { _sqlExpressionFactory.Fragment(timePart), unixEpochArgument, instance! },
                   nullable: true,
                   argumentsPropagateNullability: new[] { false, false, true },
                   typeof(long)));
```

File: src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs [hunk 6]
```diff
@@ -19,6 +19,12 @@ public class SqliteDateTimeAddTranslator : IMethodCallTranslator
     private static readonly MethodInfo AddTicks
         = typeof(DateTime).GetRuntimeMethod(nameof(DateTime.AddTicks), new[] { typeof(long) })!;
 
+    private static readonly MethodInfo ToUnixTimeSeconds
```
Comment (Marusyk) [inline src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs:22]: Should I create the new one SqliteDateTimeMethodTranslator, rename SqliteDateTimeAddTranslator -> SqliteDateTimeMethodTranslator, or leave it as is?
could you suggest?

Comment (roji) [reply src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs:22]: I'd rename SqliteDateTimeAddTranslator to SqliteDateTimeMethodTranslator, I don't think we need more translator types here.

File: src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs [hunk 7]
```diff
@@ -60,7 +66,9 @@ public SqliteDateTimeAddTranslator(ISqlExpressionFactory sqlExpressionFactory)
             ? TranslateDateTime(instance, method, arguments)
             : method.DeclaringType == typeof(DateOnly)
                 ? TranslateDateOnly(instance, method, arguments)
-                : null;
+                : method.DeclaringType == typeof(DateTimeOffset)
+                    ? TranslateDateTimeOffset(instance, method, arguments)
+                    : null;
```
Comment (bricelam) [inline src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs:71]: Can't do this. SQLite will ignore the time zone and you'll get incorrect results.

Comment (Marusyk) [reply src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs:71]: Could you please explain? I don't have a lot of experience with MySql ☹. The main idea was to add the translation only for SQL Server

Comment (bricelam) [reply src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs:71]: The SQLite date and time functions can't work with DateTimeOffset values. DateTimeOffest includes a timezone, but the SQL functions will simply ignore it and the result will be wrong.

Personally, I'd be fine just adding the SQL Server translations in this PR and filing an issue (or keeping the existing one open) to add the SQLite ones later. @smitpatel Is there a reason they need to be added in this PR?

Comment (smitpatel) [reply src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs:71]: Fine to split into a different issue. Most times we forget to add till someone files an issue on us. So if the translation is easy and straightforward add in the same PR so feature is lighted up across providers. If translation is complex ok to defer especially for community contributions.

Comment (Marusyk) [reply src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs:71]: I don't mind to add the SQLite ones if you give me some advice

File: src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs (hunk 2 above)
Comment (Marusyk) [reply src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs:155]: @smitpatel what about this? could you suggest

**Comment by Marusyk** [comment]
Can I mark it "ready for review"?

File: src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs (hunk 7 above)
Comment (bricelam) [reply src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs]: I didn't realize there weren't corresponding methods on `DateTime`. Nothing to do on SQLite.

**Comment by bricelam** [comment]
Rebased, removed SQLite translations, and copied the type mapping from `instance` to `UnixEpoch`.

**Review by bricelam — APPROVED** [review]
