### PR TITLE
Fix to #32570 - Test/Cleanup: some adhoc tests that are provider only… because hardcoded column types etc can be moved from provider to relational/core

### LINKED ISSUE #32570: Test/Cleanup: some adhoc tests that are provider only because hardcoded column types etc can be moved from provider to relational/core
We can make model configuration step provider specific so each provider can do what's necessary, rather than do it all on the context class itself

### PR DESCRIPTION
**Pull request by maumar**
Also removed some tests from InMemory QBT - those tests were duplicated from SqlServer QBT but have been moved to AdHoc test suites and run for all providers.

Fixes #32570

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/AdHocMiscellaneousQuerySqlServerTest.cs [hunk 1]
```diff
@@ -1812,6 +1647,72 @@ public override async Task QueryBuffer_requirement_is_computed_when_querying_bas
 """);
     }
 
+    public override async Task Average_with_cast()
+    {
+        await base.Average_with_cast();
+
+        AssertSql(
+"""
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/AdHocMiscellaneousQuerySqlServerTest.cs:1655]: nit: should be indented

**Review by roji — APPROVED** [review]
