### PR TITLE
Stop appending facets to SQL Server type aliases

### LINKED ISSUE #24365: Usage of Column type will create a messed up migration
In my migration always the default scale and precision (18,2) is applied to a use defined type. In my case the UDT has does not match 18,2. So the migration cannot be applied to the database, until I remove it manually from the migration.cs file

DBContext.cs:

```
foreach (var property in _modelBuilder.Model.GetEntityTypes()
                                            .SelectMany(t => t.GetProperties())
                                            .Where(p => p.ClrType == typeof(decimal)))
{
    property.SetColumnType("DefNumeric");
}
```

Migration.cs:

```
PerIC = table.Column<decimal>(type: "DefNumeric(18,2)", nullable: false)  //Wrong
PerIC = table.Column<decimal>(type: "DefNumeric", nullable: false)        //Correct
```

Is there a way to stopp appliying the default scale & precision  autmatically to an UDT?

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #24365

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/SqlServerTypeAliasTest.cs [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+                var aliasEntityType = model.FindEntityType(typeof(TypeAliasEntity));
+                Assert.Equal("datetimeAlias", GetColumnType(aliasEntityType!, nameof(TypeAliasEntity.DateTimeAlias)));
+                Assert.Equal("datetimeoffsetAlias", GetColumnType(aliasEntityType!, nameof(TypeAliasEntity.DateTimeOffsetAlias)));
+                Assert.Equal("decimalAlias", GetColumnType(aliasEntityType!, nameof(TypeAliasEntity.DecimalAlias)));
+                Assert.Equal("doubleAlias", GetColumnType(aliasEntityType!, nameof(TypeAliasEntity.DoubleAlias)));
+                Assert.Equal("floatAlias", GetColumnType(aliasEntityType!, nameof(TypeAliasEntity.FloatAlias)));
+                Assert.Equal("binaryAlias", GetColumnType(aliasEntityType!, nameof(TypeAliasEntity.BinaryAlias)));
+                Assert.Equal("stringAlias", GetColumnType(aliasEntityType!, nameof(TypeAliasEntity.StringAlias)));
+
+                var facetedAliasEntityType = model.FindEntityType(typeof(TypeAliasEntity));
```
Comment (bricelam) [inline test/EFCore.SqlServer.FunctionalTests/SqlServerTypeAliasTest.cs:55]:
```suggestion
                var facetedAliasEntityType = model.FindEntityType(typeof(TypeAliasEntityWithFacets));
```

**Review by bricelam — APPROVED** [review]
