### PR TITLE
Fix to #27844 - EF Core 6.0 temporal table migration when altering computed column not generating correct script

### LINKED ISSUE #27844: EF Core 6.0 temporal table migration when altering computed column not generating correct script
## File a bug

Step 1 Make table temporal
Step 2 Add migration for that
Step 3 Add new computed column to the entity
step 4 Add Migration for altered column
setp 5 Generate script for migration

### Include your code

added new computed column to existing Temporal Table

```C#
entity.Property(x => x.Level).HasComputedColumnSql("Id.GetLevel() PERSISTED");
```
Generate migration 
```CMD
dotnet ef migrations add addinglevel
```
Generate migration script
```CMD
dotnet ef migrations script 20210624210145_AddTemporalSupport 20220419235406_addinglevel
Build started...
Build succeeded.
BEGIN TRANSACTION;
GO

ALTER TABLE [HierarchyNode] ADD [Level] AS Id.GetLevel() PERSISTED;
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20220419235406_addinglevel', N'6.0.4');
GO

COMMIT;
GO
```
When running migration in SQL Studio
``` 
Msg 13724, Level 16, State 1, Line 1
System-versioned table schema modification failed because adding computed column while system-versioning is ON is not supported.
```
### Expected 
Migration script to turn of versioning and alter both table and turn versioning on

EF Core version: 6.0.4
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system: Windows
IDE: (e.g. Visual Studio 2022 17.2)

### PR DESCRIPTION
**Pull request by maumar**
Working with computed column on a temporal table requires special processing - we need to disable the versioning, add the computed column to regular table and a column with the same name/type/position to the history table, but as a regular column. After all is done we re-enable versioning. Historical information on the computed column will be copied to the counterpart column in history table without issue.

One thing that we can't do is modifying computed column SQL when table is temporal. What happens in case of CCSQL modification, we drop the column and create a new one with new CCSQL. This is not an issue for regular table, because the value is computed anyway, so old value is useless. But when we drop-create column, that column gets created at the last position in the table, and so the table no longer matches it's history table exactly (positions of columns may differ). We would have to drop+recreate column on a history table, but that results in losing historical data of that column. And that is valuable data, unlike for regular table. We could enable that scenario once/if we support table rebuilds.

Fixes #27844

### CODE REVIEW

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 1]
```diff
@@ -2692,27 +2692,43 @@ private static bool HasDifferences(IEnumerable<IAnnotation> source, IEnumerable<
                             addColumnOperation.DefaultValue = DateTime.MaxValue;
                         }
 
+                        var isSparse = addColumnOperation[SqlServerAnnotationNames.Sparse] as bool? == true;
+                        var isComputed = addColumnOperation.ComputedColumnSql != null;
+
+                        if ((isSparse || isComputed)
+                            && !temporalInformation.DisabledVersioning
+                            && !temporalInformation.ShouldEnableVersioning)
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2700]: Move these checks inside `DisableVersioning`

**Review by AndriySvyryd — APPROVED** [review]

**Review by bricelam — APPROVED** [review]
