### PR TITLE
Query: Auto-buffer data readers in SqlServer when split query & MARS off

### LINKED ISSUE #21420: Configure MARS in SqlServer
Since we have split queries again, SqlServer may fail without MARS.
We could add DbOption configuration for users to tell us if they have MARS on or not.

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #21420

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SqlServerCompiledQueryCacheKeyGenerator.cs [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+
+            private bool Equals(SqlServerCompiledQueryCacheKey other)
+                => _relationalCompiledQueryCacheKey.Equals(other._relationalCompiledQueryCacheKey)
+                   && _multipleActiveResultSetsEnabled == other._multipleActiveResultSetsEnabled;
+
+            public override int GetHashCode()
+            {
+                unchecked
+                {
+                    return (_relationalCompiledQueryCacheKey.GetHashCode() * 397) ^ _multipleActiveResultSetsEnabled.GetHashCode();
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Query/Internal/SqlServerCompiledQueryCacheKeyGenerator.cs:75]:
```suggestion
                    return (_relationalCompiledQueryCacheKey.GetHashCode() * 3) ^ _multipleActiveResultSetsEnabled.GetHashCode();
```

3 is enough for a bool

Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerCompiledQueryCacheKeyGenerator.cs:75]: Why not just use HashCode.Combine?

File: src/EFCore.Relational/Storage/RelationalConnection.cs [hunk 2]
```diff
@@ -129,12 +129,8 @@ public virtual string ConnectionString
         protected virtual string GetValidatedConnectionString()
         {
             var connectionString = ConnectionString;
-            if (connectionString == null)
-            {
-                throw new InvalidOperationException(RelationalStrings.NoConnectionOrConnectionString);
-            }
 
-            return connectionString;
+            return connectionString ?? throw new InvalidOperationException(RelationalStrings.NoConnectionOrConnectionString);
```
Comment (roji) [inline src/EFCore.Relational/Storage/RelationalConnection.cs:133]: Any reason to copy to the local variable? This could just be a one-line expression-bodied method

File: src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs [hunk 3]
```diff
@@ -87,6 +88,47 @@ public virtual ISqlServerConnection CreateMasterConnection()
...
+        }
+
+        /// <summary>
+        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+        ///     any release. You should only use it directly in your code with extreme caution and knowing that
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        public virtual bool IsMultipleActiveResultSetsEnabled
+            => _multipleActiveResultSetsEnabled ??= new SqlConnectionStringBuilder(ConnectionString).MultipleActiveResultSets;
```
Comment (roji) [inline src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs:130]: So this means we parse the connection string for each SqlServerConnection, which is scoped - that's not very good for perf...

It may be worth having a dictionary mapping connection strings to whether they have MARS or not - a quick benchmark should show it's worth it.

File: src/EFCore.Relational/Storage/RelationalConnection.cs (hunk 2 above)
Comment (smitpatel) [reply src/EFCore.Relational/Storage/RelationalConnection.cs:133]: Existing code did it. I did not question the intention. 😉 

I am fine to change it if we think it is safe to do.

@AndriySvyryd @ajcvickers - Thoughts?

File: src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs (hunk 3 above)
Comment (smitpatel) [reply src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs:130]: This means we parse it only first time and any subsequent time when you change connection string or connection manually. Also it is lazily initialized so if query is not used it won't be parsed. Overall reducing the time when this code path is hit.

In general we are not catching anything when connection string is changed so I suspect that there can be various pieces which can be optimized if we want to catch older connection string. This is just adding 1 more to umbrella.

Feel free to run benchmarks, if it significant perf difference then I am also ok adding a dictionary mapping.

What does @AndriySvyryd think?

File: src/EFCore.SqlServer/Query/Internal/SqlServerCompiledQueryCacheKeyGenerator.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.SqlServer/Query/Internal/SqlServerCompiledQueryCacheKeyGenerator.cs:75]: Picked code from 2.2 It did not have HashCode.Combine back then. I will update.

File: src/EFCore.Relational/Storage/RelationalConnection.cs (hunk 2 above)
Comment (ajcvickers) [reply src/EFCore.Relational/Storage/RelationalConnection.cs:133]: It was presumably so we could check for null without evaluating the property twice.

File: src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs (hunk 3 above)
Comment (roji) [reply src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs:130]: > This means we parse it only first time and any subsequent time when you change connection string or connection manually. Also it is lazily initialized so if query is not used it won't be parsed. Overall reducing the time when this code path is hit.

But this is done for any (non-pooled) DbContext which executes a query, right? If so, I think that's not so good (DbConnectionStringBuilder is surprisingly heavy). @AndriySvyryd?

File: src/EFCore.Relational/Storage/RelationalConnection.cs (hunk 2 above)
Comment (smitpatel) [reply src/EFCore.Relational/Storage/RelationalConnection.cs:133]: I wasn't sure if compiler would evaluate it twice if used in coalesce operation so reverted the change. It was unrelated to this PR anyway.

File: src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs (hunk 3 above)
Comment (AndriySvyryd) [reply src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs:130]: Memoizing in a CuncurrentDictionary sounds reasonable here as it will be needed on almost every context instance. But context pooling would mitigate this.

Comment (smitpatel) [reply src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs]: Updated.

File: src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs [hunk 4]
```diff
@@ -87,6 +89,27 @@ public virtual ISqlServerConnection CreateMasterConnection()
...
+        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+        ///     any release. You should only use it directly in your code with extreme caution and knowing that
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        public virtual bool IsMultipleActiveResultSetsEnabled
+        {
+            get
+            {
+                var connectionString = ConnectionString;
+                if (!_multipleActiveResultSetsEnabledMap.TryGetValue(connectionString, out var value))
```
Comment (roji) [inline src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs:103]: Can use [GetOrAdd](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=netcore-3.1#System_Collections_Concurrent_ConcurrentDictionary_2_GetOrAdd__0_System_Func__0__1__) for terser code
