### PR TITLE
ReplacingEV uses two arrays instead of dictionary

### LINKED ISSUE #19737: Exponential hash code calculation in ReplacingExpressionVisitor
I have query like this, result1 success get data but result2 stuck(not throw exception and not get result).

``` C#
var trx = context.Adjustments.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = x.IsPositive ? UserActionSource.AdjustmentPlus : UserActionSource.AdjustmentMinus,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = x.CostCenterId
            }).Union(context.SupplierDownPayments.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.SupplierDownPayment,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.PurchaseRequisitions.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.PurchaseRequisition,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.PurchaseOrders.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.PurchaseOrder,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.ReceivedItems.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.ReceivedItem,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            }))
            .Union(context.Purchases.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.Purchase,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.PurchaseReceivings.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.PurchaseReceiving,
                RefCode = x.Code,
                BranchId = null,
                CostCenterId = null
            })).Union(context.PurchaseReturns.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.PurchaseReturn,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.JournalVouchers.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.JournalVoucher,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.OtherDeposits.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.OtherDeposit,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.OtherPayments.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.OtherPayment,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.WarehouseTransfers.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.WarehouseTransfer,
                RefCode = x.Code,
                BranchId = null,
                CostCenterId = null
            })).Union(context.ItemTransferIns.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.ItemTransferIn,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.ItemTransferOuts.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.ItemTransferOut,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            }));

            var result1= await (from i in trx
                      select new
                      {
                          i.Id
                      }).ToListAsync(cancellationToken);

            var result2 = await (from i in trx
                      select new
                      {
                          i.Id,
                          IsA = (from ah in context.AccountHistories where i.Id == ah.RefId select ah.Id).Count() > 0
                      }).ToListAsync(cancellationToken);
```
how to fix it?

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4

### PR DESCRIPTION
**Pull request by roji**
ReplacingExpressionVisitor held original and replacement expressions in a dictionary. Unfortunately that means hash code calculation occurs exponentially, as each TryGetValue on the dictionary must traverse the entire tree.

Replaced with two lists and a simple Equals check, which is much faster.

Fixes #19737

### CODE REVIEW

File: src/EFCore/Query/ReplacingExpressionVisitor.cs [hunk 1]
```diff
@@ -14,22 +13,24 @@ namespace Microsoft.EntityFrameworkCore.Query
...
             Check.NotNull(replacement, nameof(replacement));
             Check.NotNull(tree, nameof(tree));
 
-            return new ReplacingExpressionVisitor(
-                new Dictionary<Expression, Expression> { { original, replacement } }).Visit(tree);
+            return new ReplacingExpressionVisitor(new[] { original }, new[] { replacement }).Visit(tree);
         }
 
-        public ReplacingExpressionVisitor([NotNull] IDictionary<Expression, Expression> replacements)
+        public ReplacingExpressionVisitor([NotNull] Expression[] originals, [NotNull] Expression[] replacements)
```
Comment (smitpatel) [inline src/EFCore/Query/ReplacingExpressionVisitor.cs]: Breaking change if patching.

Comment (roji) [reply src/EFCore/Query/ReplacingExpressionVisitor.cs]: Yep. We could leave the previous constructor and build arrays out of the keys/values.

File: src/EFCore/Query/ReplacingExpressionVisitor.cs [hunk 2]
```diff
@@ -40,9 +41,12 @@ public override Expression Visit(Expression expression)
                 return expression;
             }
 
-            if (_replacements.TryGetValue(expression, out var replacement))
+            for (var i = 0; i < _originals.Length; i++)
```
Comment (AndriySvyryd) [inline src/EFCore/Query/ReplacingExpressionVisitor.cs]: Add a comment that briefly (no more than 2 lines!) explains why we are using arrays instead of dictionary
