### PR TITLE
[6.0] Fix context pooling concurrency issue

### LINKED ISSUE #26202: ObjectDisposedException on retrieval of a pooled DbContext
EF Core version: 6.0.0-rc1
Database provider: any
Target framework: .NET 6.0
Operating system: any
IDE: any

https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore/DbContext.cs#L902 - looks like `_disposed` field should be set to `false` here instead (and in the *Async version of the same method). The existing code causes any `DbContext` that was returned back to the pool to throw `ObjectDisposedException` on attempt to rent it again.

### PR DESCRIPTION
**Pull request by roji**
Fixes #26202

### Description

When using DbContext pooling, the DbContext disposal logic modifies the state after the context has been returned to the pool, creating a race condition with possible consumers renting the context out of the pool.

### Customer impact

When using DbContext pooling, an ObjectDisposedException may occur when using a pooled context. This is the kind of bug that only happens very occasionally but then will cause the application to fail unexpectedly and in a way that is difficult to diagnose. This means lack of customer reports doesn't mean it isn't impacting overall reliability of apps that use EF Core.

### How found

Customer reported.

### Regression

No; exists in 5.0 also. We intend to backport there. Does not happen on 3.1.

### Testing

Test for this scenario added in the PR.

### Risk

Low, the fix is quite simple.

We may want to revisit and simplify later, but for now here's a minimal fix.

### CODE REVIEW

File: src/EFCore/DbContext.cs [hunk 1]
```diff
@@ -956,13 +956,44 @@ private IEnumerable<IResettableService> GetResettableServices()
         /// </remarks>
         public virtual void Dispose()
         {
-            var leaseActive = _lease.IsActive;
-            var contextDisposed = leaseActive && _lease.ContextDisposed();
+            var lease = _lease;
+            var contextDisposed = lease.IsActive && _lease.IsStandalone;
```
Comment (AndriySvyryd) [inline src/EFCore/DbContext.cs:960]:
```suggestion
            var contextShouldBeDisposed = lease.IsActive && _lease.IsStandalone;
```

File: src/EFCore/DbContext.cs [hunk 2]
```diff
@@ -956,13 +956,44 @@ private IEnumerable<IResettableService> GetResettableServices()
...
+        ///     </para>
+        /// </summary>
+        /// <remarks>
+        ///     See <see href="https://aka.ms/efcore-docs-dbcontext">DbContext lifetime, configuration, and initialization</see>
+        ///     for more information.
+        /// </remarks>
+        public virtual async ValueTask DisposeAsync()
+        {
+            var lease = _lease;
+            var contextDisposed = lease.IsActive && _lease.IsStandalone;
```
Comment (AndriySvyryd) [inline src/EFCore/DbContext.cs:989]: Same here

**Review by AndriySvyryd — APPROVED** [review]

**Comment by ajcvickers** [comment]
@Pilchie For 6.0. (Also we're going to request backporting to at least 5.0.x, but we'll obviously do that separately.)

**Review by ajcvickers — APPROVED** [review]

**Comment by roji** [comment]
Squashed and rebased on latest release/6.0

**Comment by Pilchie** [comment]
Approved for EFCore 6.0 GA.
