### PR TITLE
SqlServerValueGenerationStrategy which conflicts now causes warning

### LINKED ISSUE #16814: Allow DefaultValueSql when using ForSqlServerUseSequenceHiLo
With EF Core 3.0, setting ``DefaultValueSql`` when ``ForSqlServerUseSequenceHiLo`` is used on a property (or vice versa) throws an exception. In 2.2.6 this worked fine and I was using it to set ``DefaultValueSql`` to ``"NEXT VALUE FOR [Schema].[SequenceName]"``.

```
Exception message:
   SqlServerValueGenerationStrategy cannot be set for 'Id' at the same time as DefaultValueSql. Remove one of these values.

Stack trace:
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.SqlServerStoreGenerationConvention.Validate(IConventionProperty property)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.StoreGenerationConvention.ProcessModelFinalized(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
```

### Steps to reproduce
```c#
    class Program
    {
        public static string ConnectionString = "Server=.\\SQLEXPRESS;Database=ExampleDb;MultipleActiveResultSets=true;Integrated Security=true";

        static void Main(string[] args)
        {
            var options = new DbContextOptionsBuilder()
                .UseSqlServer(ConnectionString)
                .Options;

            var db = new ExampleContext1(options);
            db.ChangeTracker.Entries();
        }
    }

    public class ExampleContext1 : DbContext
    {
        public DbSet<Example> Examples { get; set; }

        public ExampleContext1(DbContextOptions options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder
                .Entity<Example>()
                .Property(x => x.Id)
                .HasDefaultValueSql("NEXT VALUE FOR [Example_Id]")
                .ForSqlServerUseSequenceHiLo("Example_Id");

            base.OnModelCreating(modelBuilder);
        }
    }

    public class Example
    {
        public long Id { get; set; }
    }
```

### Further technical details
EF Core version: 3.0.0-preview7.19362.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.3.0. Preview 1

### PR DESCRIPTION
**Pull request by lajones**
Instead of throwing as it used to do. This fixes #16814.

By default the warning is still set up to throw, but now you could turn that off if you're sure you know what you're doing. Tests for that latter part will be forthcoming, but I wanted to get feedback that I'm going the right direction, plus agree on the message etc.

### CODE REVIEW

File: src/EFCore.SqlServer/Metadata/Conventions/SqlServerStoreGenerationConvention.cs [hunk 1]
```diff
@@ -102,25 +103,24 @@ protected override void Validate(IConventionProperty property)
             if (property.GetValueGenerationStrategyConfigurationSource() != null
                 && property.GetValueGenerationStrategy() != SqlServerValueGenerationStrategy.None)
             {
+                var generationStrategy = property.GetValueGenerationStrategy().ToString();
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Metadata/Conventions/SqlServerStoreGenerationConvention.cs]: It would be better to pass this through as `SqlServerValueGenerationStrategy` and only convert it to `string` when logging

File: src/EFCore.SqlServer/Properties/SqlServerStrings.resx [hunk 2]
```diff
@@ -241,4 +241,8 @@
   <data name="FunctionOnClient" xml:space="preserve">
     <value>The '{methodName}' method is not supported because the query has switched to client-evaluation. Inspect the log to determine which query expressions are triggering client-evaluation.</value>
   </data>
+  <data name="LogConflictingValueGenerationStrategies" xml:space="preserve">
+    <value>Both the SqlServerValueGenerationStrategy {generationStrategy} and {otherGenerationStrategy} have been set on property '{propertyName}' on entity '{entityName}'. Usually this is a mistake. Only use these at the same time if you are sure you understand the consequences.</value>
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Properties/SqlServerStrings.resx]:
```suggestion
    <value>Both the SqlServerValueGenerationStrategy {generationStrategy} and {otherGenerationStrategy} have been set on property '{propertyName}' on entity type '{entityName}'. Usually this is a mistake. Only use these at the same time if you are sure you understand the consequences.</value>
```

File: src/EFCore.SqlServer/Metadata/Conventions/SqlServerStoreGenerationConvention.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore.SqlServer/Metadata/Conventions/SqlServerStoreGenerationConvention.cs]: Will do.

File: src/EFCore.SqlServer/Properties/SqlServerStrings.resx (hunk 2 above)
Comment (lajones) [reply src/EFCore.SqlServer/Properties/SqlServerStrings.resx]: Looks good. Will do.

**Comment by lajones** [comment]
@AndriySvyryd Added 2 functional tests that it a) throws by default, b) does not throw but just logs the warning if you override the default.
