### PR TITLE
Fix to #23877 - Odata $filter and $orderby not working with Select to new DTO for one to one relationship

### LINKED ISSUE #23877: Odata $filter and $orderby not working with Select to new DTO for one to one relationship
Since I update to .NET Core $orderby and $filter does not work in this specific case, which was perfectly working before.

The DTO models

```
public class AddressDto
{
        public Guid Id { get; set; }
        public string ZipCode{ get; set; }
        public IdAndName State { get; set; }
}
```

```
public class IdAndName 
{
        public Guid Value { get; set; }
        public string Text{ get; set; }
}


// The DB model
public class AdressEntity {
            public Guid Id { get; set; }
        public string ZipCode{ get; set; }
        public Guid StateId {get;set;}
        public State State {get;set;}
}
```

// The SELECT:
```
query.Select(x =>
    new AddressDto()
    {
        Id = x.Id,
        ZipCode = x.ZipCode,
        State = x.StateId.HasValue ? new IdAndName() { Text = x.State.Name, Value= x.StateId.Value } : null,
    });
```
And the request

> api/AddressDto?$count=true&$top=20&$skip=0&$orderby=state/text%20desc&$filter=(state/value%20eq%20be78ab1e-2ae3-4754-956e-7e099ea82242) 

Which was wokring perfectly in the .NET Framework now thorws and error:

> ... .Where(t => t.Outer.Active == __TypedProperty_1 && t.Outer.StateId.HasValue ? new IdAndName { \r\n        Text = t.Inner.Name, \r\n        Value = t.Outer.StateId.Value \r\n    }\r\n     : null.Value == __TypedProperty_2)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'.

The problem is obvious. Somehow Odata sends all the null check expression in the query...

I`m not using AutoMapper, I do all converts like this with select. And with the nested collection properties everything is fine.... but with the single ones which should be easies it is NOT...

When I change the null check to be like this:

```
 query.Select(x =>
new AddressDto()
{
    Id = x.Id,
    ZipCode = x.ZipCode,
    State = x.State != null ? new IdAndName() { Text = x.State.Name, Value= x.StateId.Value } : null,
}); 
```
I get another error:

"The operands for operator 'Equal' do not match the parameters of method 'op_Equality'."

I do not think there is other way to perform null check...

### PR DESCRIPTION
**Pull request by maumar**
Problem was that during query optimization, TryOptimizeMemberAccessOverConditional could change the type of the expression (from non nullable to nullable), which then would throw when trying to re-construct the expression tree upstream.
Fix is to change the type to the original as part of TryOptimizeMemberAccessOverConditional.

Fixes #23877

### CODE REVIEW

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs [hunk 1]
```diff
@@ -300,11 +300,14 @@ protected override Expression VisitUnary(UnaryExpression unaryExpression)
...
 
                     var nullExpression = Expression.Constant(null, nonNullExpression.Type);
-
-                    return Expression.Condition(
+                    var result = Expression.Condition(
                         conditionalExpression.Test,
                         binaryTest.NodeType == ExpressionType.Equal ? nullExpression : nonNullExpression,
                         binaryTest.NodeType == ExpressionType.Equal ? nonNullExpression : nullExpression);
+
+                    return result.Type != expression.Type
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:308]: How much valid is it to convert to non-null here given conditional can return null too.

Comment (maumar) [reply src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:308]: we could keep as nullable and then compensate in all operators (binary, coalesce, unary, etc). Problem is you still run into issues if the value is projected on the top level, method call arguments etc - we would probably need to force conversion back to non-nullable there. I was worried that we would miss something and throw when trying to build the expression tree. Converting right away should be ok at least for relational, but now that I think about it, probably we should take other providers *cough* in memory *cough* into account

Comment (smitpatel) [reply src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:308]: Let's experiment more scenario around this to figure out if this is valid to make it work. In LINQ world, while it is perfectly fine to move the type back, it may clash with our null-propagation in translation.

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs [hunk 2]
```diff
@@ -128,7 +128,25 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+
+            var arguments = new Expression[methodCallExpression.Arguments.Count];
+            for (var i = 0; i < arguments.Length; i++)
+            {
+                arguments[i] = MatchExpressionType(
+                    Visit(methodCallExpression.Arguments[i]),
+                    methodCallExpression.Arguments[i].Type);
+            }
+
+            var visited = @object != null
```
Comment (maumar) [inline src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:147]: methodCallExpression.Update has object typed as Expression (non nullable), so can't use it to update for static methods

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs [hunk 3]
```diff
@@ -198,7 +221,109 @@ protected override Expression VisitUnary(UnaryExpression unaryExpression)
...
+        protected override Expression VisitLambda<T>(Expression<T> lambdaExpression)
+        {
+            Check.NotNull(lambdaExpression, nameof(lambdaExpression));
+
+            var body = Visit(lambdaExpression.Body);
+            var result = body.Type != lambdaExpression.Body.Type
+                ? Expression.Lambda(Expression.Convert(body, lambdaExpression.Body.Type), lambdaExpression.Parameters)
+                : lambdaExpression.Update(body, lambdaExpression.Parameters);
+
+            return result ?? lambdaExpression;
```
Comment (maumar) [inline src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:302]: nrt hack, is there a better way to deal with this? @roji

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs (hunk 2 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:147]: Just use update and bang it. I fixed that bug, it should flow to us at some point.

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs [hunk 4]
```diff
@@ -198,7 +221,109 @@ protected override Expression VisitUnary(UnaryExpression unaryExpression)
                         result);
             }
 
-            return base.VisitUnary(unaryExpression);
+            var operand = Visit(unaryExpression.Operand);
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:224]: inline var?

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs (hunk 3 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:302]: How is result nullable here? If it is not then bang it.

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs [hunk 5]
```diff
@@ -300,11 +425,12 @@ protected override Expression VisitUnary(UnaryExpression unaryExpression)
...
 
                     var nullExpression = Expression.Constant(null, nonNullExpression.Type);
-
-                    return Expression.Condition(
+                    var result = Expression.Condition(
                         conditionalExpression.Test,
                         binaryTest.NodeType == ExpressionType.Equal ? nullExpression : nonNullExpression,
                         binaryTest.NodeType == ExpressionType.Equal ? nonNullExpression : nullExpression);
+
+                    return result;
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:433]: inline var?

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs [hunk 6]
```diff
@@ -198,7 +221,109 @@ protected override Expression VisitUnary(UnaryExpression unaryExpression)
                         result);
             }
 
-            return base.VisitUnary(unaryExpression);
+            var operand = Visit(unaryExpression.Operand);
+
+            return unaryExpression.Update(operand);
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:226]: Update may fail if operand type is changed? Do we have a test path covering the scenario?

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs (hunk 3 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:302]: `lambdaExpression.Body.Type` === `lambdaExpression.ReturnType`

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs [hunk 7]
```diff
@@ -157,6 +175,11 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
             return visited;
         }
 
+        private Expression MatchExpressionType(Expression expression, Type typeToMatch)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:178]: You may also need to match types in
ElementInit
Member (when MemberExpression.Expression is converted to nullable)
MemberAssignment
NewArray

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs (hunk 3 above)
Comment (maumar) [reply src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:302]: not for selectmany

Comment (smitpatel) [reply src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:302]: Got any sample query? Just curious

Comment (maumar) [reply src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:302]: pretty much any selectmany query where collection is queryable. The method signature needs IEnumerable and we do that trick where we explicitly set the type of lambda for collection selectors - body is `IQueryable<Entity>` but the return type is `IEnumerable<Entity>`

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs (hunk 6 above)
Comment (maumar) [reply src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:226]: I hit this path in one of the old tests in earlier iteration - gone now. However I added explicit tests that forces this now

**Comment by maumar** [comment]
updated @smitpatel

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs [hunk 8]
```diff
@@ -198,7 +225,160 @@ protected override Expression VisitUnary(UnaryExpression unaryExpression)
...
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        protected override Expression VisitLambda<T>(Expression<T> lambdaExpression)
+        {
+            Check.NotNull(lambdaExpression, nameof(lambdaExpression));
+
+            var body = Visit(lambdaExpression.Body);
+
+            return body.Type != lambdaExpression.Body.Type
+                ? Expression.Lambda(Expression.Convert(body, lambdaExpression.Body.Type), lambdaExpression.Parameters)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:303]: Does changing type of lambda really work? It could cause errors in generic type matching. e.g. OrderBy(some int) cannot be updated without reconstructing generic type if int converts to int?

File: src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs [hunk 9]
```diff
@@ -336,6 +336,18 @@ protected override Expression VisitMember(MemberExpression memberExpression)
             Check.NotNull(memberExpression, nameof(memberExpression));
 
             var innerExpression = Visit(memberExpression.Expression);
+
+            // when visiting unary we remove converts from nullable to non-nullable
+            // however if this happens for memberExpression.Expression we are unable to bind
+            if (innerExpression != null
```
Comment (smitpatel) [inline src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs:342]: there is some null processing 2 blocks below also, merge?

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs (hunk 8 above)
Comment (maumar) [reply src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:303]: will add some tests

File: src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs (hunk 9 above)
Comment (maumar) [reply src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs:342]: will leave as is, the block I added needs to happen before we attempt to bind the member, and the block below should only happen if the binding is unsuccessful.

**Review by smitpatel — APPROVED** [review]
