### PR TITLE
Documented InvalidOperationException for QueryableExtensions methods

### LINKED ISSUE #24307: InvalidOperationException is missing from exceptions list for a lot of Queryable extensions
The issue is the same as #24242 but related to other extension methods:

- AnyAsync
- CountAsync
- LongCountAsync
- FirstOrDefaultAsync
- LastOrDefaultAsync
- SingleAsync
- MinAsync
- SumAsync
- AverageAsync

We need to add something like:

`/// <exception cref="InvalidOperationException"> <paramref name="source" /> contains no elements. </exception>`

and submit changes to https://github.com/dotnet/dotnet-api-docs

### PR DESCRIPTION
**Pull request by Marusyk**
Added InvalidOperationException to xml docs for:

- ~LastOrDefaultAsync~
- ~AverageAsync~
- MinAsync

Fixes #24307

### CODE REVIEW

**Review by roji — CHANGES_REQUESTED** [review]
LastOrDefaultAsync doesn't throw InvalidOperationException when the source is empty - it returns default.

**Review by maumar — DISMISSED** [review]

File: src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs [hunk 1]
```diff
@@ -1395,6 +1397,7 @@ public static string ToQueryString([NotNull] this IQueryable source)
         ///     The task result contains the average of the sequence of values.
         /// </returns>
         /// <exception cref="ArgumentNullException"> <paramref name="source" /> is <see langword="null" />. </exception>
+        /// <exception cref="InvalidOperationException"> <paramref name="source" /> contains no elements. </exception>
```
Comment (smitpatel) [inline src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs:1400]: This is incorrect. There is no exception thrown when sequence contains no elements if the result type is nullable.

**Review by roji — APPROVED** [review]
Thanks.
