### PR TITLE
Don't skip creating cascade delete on SQL Server when types are base-linking across tables

### LINKED ISSUE #28532: Cascade delete behavior for FK between PKs in TPT
Test `Delete_where_using_hierarchy` fails.
It is trying to delete entity which has dependent containing TPT. The failure indicates that cascade delete in TPT failed. Looking at database schema the FK doesn't contain cascade delete behavior.

```SQL
USE [TPTInheritanceTest]
GO

/****** Object:  Table [dbo].[Birds]    Script Date: 7/28/2022 10:18:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Birds](
	[Species] [nvarchar](100) NOT NULL,
	[IsFlightless] [bit] NOT NULL,
	[EagleId] [nvarchar](100) NULL,
 CONSTRAINT [PK_Birds] PRIMARY KEY CLUSTERED 
(
	[Species] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Birds]  WITH CHECK ADD  CONSTRAINT [FK_Birds_Animals_Species] FOREIGN KEY([Species])
REFERENCES [dbo].[Animals] ([Species])
GO

ALTER TABLE [dbo].[Birds] CHECK CONSTRAINT [FK_Birds_Animals_Species]
GO

ALTER TABLE [dbo].[Birds]  WITH CHECK ADD  CONSTRAINT [FK_Birds_Eagle_EagleId] FOREIGN KEY([EagleId])
REFERENCES [dbo].[Eagle] ([Species])
GO

ALTER TABLE [dbo].[Birds] CHECK CONSTRAINT [FK_Birds_Eagle_EagleId]
GO


```

### PR DESCRIPTION
**Pull request by ajcvickers**
E.g. for TPT.

Fixes #28532 (Cascade delete behavior for FK between PKs in TPT)

Note this is a breaking change--creating a cascade delete for the TPT relationship could cause a cycle with another existing cascade relationship. This is what happened with the GearsOfWar model.

### CODE REVIEW

File: src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs [hunk 1]
```diff
@@ -57,7 +57,8 @@ protected override DeleteBehavior GetTargetDeleteBehavior(IConventionForeignKey
             return deleteBehavior;
         }
 
-        if (foreignKey.IsBaseLinking())
+        if (foreignKey.IsBaseLinking()
+            && IsMappedToSameTable(foreignKey.DeclaringEntityType, foreignKey.PrincipalEntityType))
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs:61]: Base linking FKs on the same table wouldn't be created, since they are redundant, so we can just remove this

Comment (ajcvickers) [reply src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs:61]: If I remove this, then "Entity_splitting_is_stored_in_snapshot_with_tables" fails. Not sure what the correct behavior should be for entity splitting.

Comment (ajcvickers) [reply src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs:61]:
```C#
                    b.HasOne(""Microsoft.EntityFrameworkCore.Migrations.ModelSnapshotSqlServerTest+Order"", null)
                        .WithOne()
                        .HasForeignKey(""Microsoft.EntityFrameworkCore.Migrations.ModelSnapshotSqlServerTest+Order"", ""Id"")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

````

Comment (AndriySvyryd) [reply src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs:61]: It should be Cascade too

**Comment by ajcvickers** [comment]
@AndriySvyryd Updated.

**Review by AndriySvyryd — APPROVED** [review]
