### PR TITLE
Fix to #20578 - Query: filtered include fails when orderby is the last operation inside the Include

### LINKED ISSUE #20578: Query: filtered include fails when orderby is the last operation inside the Include
QueryableMethodNormalizingExpressionVisitor doesn't correctly handle difference between IOrderedEnumerable and IOrderedQueryable. This was not a serious issue before because didn't support those cases , but with filtered include we can have IOrderedEnumerable/Queryable as a terminating operation inside lambda.

### PR DESCRIPTION
**Pull request by maumar**
Problem was that when we were rewriting methods from Enumerable to Queryable we didn't correctly handle conversion from IOrderedEnumerable to IOrderedQueryable.
When that conversion happens inside lambda, the lambda expression needs to be rebuild since the types (unlike Enumerable to Queryable) are not compatible.

Resolves #20578

### CODE REVIEW

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 1]
```diff
@@ -251,6 +261,36 @@ private Expression TryConvertListContainsToQueryableContains(MethodCallExpressio
...
+        private Expression TryRewriteIncludeTypeArguments(MethodCallExpression methodCallExpression)
+        {
+            if (ClientSource(methodCallExpression.Arguments[0]))
+            {
+                // this is methodCall over closure variable or constant
+                return base.VisitMethodCall(methodCallExpression);
+            }
+
+            var source = Visit(methodCallExpression.Arguments[0]);
+            var includeLambda = methodCallExpression.Arguments[1].UnwrapLambdaFromQuote();
```
Comment (maumar) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:273]: do we care that quite is stripped here?

Comment (smitpatel) [reply src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:273]: yes, put quote back in.

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 2]
```diff
@@ -251,6 +261,36 @@ private Expression TryConvertListContainsToQueryableContains(MethodCallExpressio
                 methodCallExpression.Arguments[0]);
         }
 
+        private Expression TryRewriteIncludeTypeArguments(MethodCallExpression methodCallExpression)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:264]: Inline rather than function.
Include is always static method so no methodCallExpression.object. Visit arguments using `VisitAndConvert`
Check specifically if lambda.ReturnType is IOrderedEnumerble and visitedLambda.ReturnType is IOrderedQueryable, then only perform rewrite.

Comment (maumar) [reply src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:264]: can't use VisitAndConvert since lambda visitation needs special casing. We could override VisitLambda and convert all cases of OrderedEnumerable to OrderedQueryable, but this opens can of worms, where now we need to rewrite a bunch of other methods, whos generic types have now changed.

Comment (smitpatel) [reply src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:264]: In that case remove any special processing other than dissecting the lambda. (Like client source). And just have custom code for VisitAndConvert part I suggested.

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 3]
```diff
@@ -53,6 +53,51 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
                 visitedExpression = TryConvertListContainsToQueryableContains(methodCallExpression);
             }
 
+            if (method.DeclaringType == typeof(EntityFrameworkQueryableExtensions)
+                && method.IsGenericMethod
+                && method.GetGenericMethodDefinition() is MethodInfo genericMethod
+                && (genericMethod == EntityFrameworkQueryableExtensions.IncludeMethodInfo
+                    || genericMethod == EntityFrameworkQueryableExtensions.ThenIncludeAfterEnumerableMethodInfo
+                    || genericMethod == EntityFrameworkQueryableExtensions.ThenIncludeAfterReferenceMethodInfo)
+                && methodCallExpression.Arguments[1].UnwrapLambdaFromQuote().Body.Type is Type bodyType
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:62]: Body.Type is same as ReturnType

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 4]
```diff
@@ -53,6 +53,51 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                && bodyType.IsGenericType
+                && bodyType.GetGenericTypeDefinition() == typeof(IOrderedEnumerable<>))
+            {
+                if (ClientSource(methodCallExpression.Arguments[0]))
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:66]: Remove this.

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 5]
```diff
@@ -53,6 +53,51 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                {
+                    // this is methodCall over closure variable or constant
+                    return base.VisitMethodCall(methodCallExpression);
+                }
+
+                var source = Visit(methodCallExpression.Arguments[0]);
+                var includeLambda = methodCallExpression.Arguments[1].UnwrapLambdaFromQuote();
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:73]: Since you are already doing this, just split the if above to use this variable. (So Visit(argument[0]) would move inside this if block.

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 6]
```diff
@@ -53,6 +53,51 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+
+                // we have to rewrite the lambda to accommodate for IOrderedEnumerable<> into IOrderedQueryable<> conversion
+                var lambda = (Expression)Expression.Lambda(body, includeLambda.Parameters);
+                if (methodCallExpression.Arguments[1].NodeType == ExpressionType.Quote)
+                {
+                    lambda = Expression.Quote(lambda);
+                }
+
+                var genericArguments = methodCallExpression.Method.GetGenericArguments();
+                var genericArgumentCount = genericArguments.Count();
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:84]: array, use Length property.

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 7]
```diff
@@ -53,6 +53,51 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                var lastGenericArgument = genericArguments[genericArgumentCount - 1];
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:85]: use `[^1]`

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 8]
```diff
@@ -53,6 +53,51 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+
+                if (body.Type.IsGenericType
+                    && body.Type.GetGenericTypeDefinition() == typeof(IOrderedQueryable<>))
+                {
+                    var newGenericArguments = genericArguments.ToArray();
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:90]: Why not mutate the original array?

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 9]
```diff
@@ -53,6 +53,51 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                    newGenericArguments[genericArgumentCount - 1] = body.Type;
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:91]: For consistency, use LambdaExpression.ReturnType.

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs (hunk 8 above)
Comment (maumar) [reply src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:90]: did that initially, thought this to be cleaner. can change

Comment (smitpatel) [reply src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:90]: Avoid allocation. Just reuse especially when we are not going to use the original further.

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs (hunk 9 above)
Comment (maumar) [reply src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:91]: lambda is typed as Expression, so that I can add Quote back. will keep as is

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 10]
```diff
@@ -53,6 +53,45 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
 
+            if (method.DeclaringType == typeof(EntityFrameworkQueryableExtensions)
+                && method.IsGenericMethod
+                && method.GetGenericMethodDefinition() is MethodInfo genericMethod
+                && (genericMethod == EntityFrameworkQueryableExtensions.IncludeMethodInfo
+                    || genericMethod == EntityFrameworkQueryableExtensions.ThenIncludeAfterEnumerableMethodInfo
+                    || genericMethod == EntityFrameworkQueryableExtensions.ThenIncludeAfterReferenceMethodInfo))
+            {
+                var includeLambda = methodCallExpression.Arguments[1].UnwrapLambdaFromQuote();
+                if (includeLambda.ReturnType is Type bodyType
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:64]: You don't need to pattern match with Type, it is always a type and non-null too.

Comment (maumar) [reply src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:64]: its just to declare a variable that I reuse in the following conditions, but I guess now that the variable is simpler it prolly not justified. will change
