### PR TITLE
[SMALL] Adding some regression tests for issues that have been fixed previously

### LINKED ISSUE #14028: Lots of select operation in group by when entity has OwnsOne configuration
Hello,
      I use group by query with OnwnsOne Entity, which like this:
```c#
public partial class Fee
{
        public Guid Id { get; set; }
 
        public ShareCroppingMoney ShareCroppingMoney { get; set; } = new ShareCroppingMoney();
}

public class ShareCroppingMoney
{
	public virtual decimal TaxServiceCharge { get; set; }

	public virtual decimal Nation { get; set; }

	public virtual decimal Province { get; set; } 

	public virtual decimal City { get; set; } 

	public virtual decimal District { get; set; }

	public virtual decimal Town { get; set; } 

	public virtual decimal Industry { get; set; }

	public virtual decimal Company { get; set; } 
}


    public partial class FeeMap : IEntityTypeConfiguration<Fee>
    {


        public void Configure(EntityTypeBuilder<Fee> builder)
        {
            builder.ToTable("Fp_Fee");
            builder.HasKey(x => x.Id);

        
            builder.Property(x => x.Money).HasColumnType("decimal(18, 2)");
         
            builder.OwnsOne(x => x.ShareCroppingMoney, shareCropping =>
             {
                 shareCropping.Property(x => x.TaxServiceCharge).HasColumnType("decimal(18, 2)");
                 shareCropping.Property(x => x.Nation).HasColumnType("decimal(18, 2)");
                 shareCropping.Property(x => x.Province).HasColumnType("decimal(18, 2)");
                 shareCropping.Property(x => x.City).HasColumnType("decimal(18, 2)");
                 shareCropping.Property(x => x.District).HasColumnType("decimal(18, 2)");
                 shareCropping.Property(x => x.Town).HasColumnType("decimal(18, 2)");
                 shareCropping.Property(x => x.Industry).HasColumnType("decimal(18, 2)");
                 shareCropping.Property(x => x.Company).HasColumnType("decimal(18, 2)");
             });
        }
    }

```

Then, query like this:
```c#

            var sum = await dbContext.Fees.GroupBy(x => 1).Select(x => new
            {
                Money = x.Sum(s => s.Money),
                City = x.Sum(s => s.ShareCroppingMoney.City),
                Company = x.Sum(s => s.ShareCroppingMoney.Company),
                District = x.Sum(s => s.ShareCroppingMoney.District),
                Industry = x.Sum(s => s.ShareCroppingMoney.Industry),
                Nation = x.Sum(s => s.ShareCroppingMoney.Nation),
                Province = x.Sum(s => s.ShareCroppingMoney.Province),
                TaxServiceCharge = x.Sum(s => s.ShareCroppingMoney.TaxServiceCharge)
            }).ToListAsync();
``` 
And you will see lot of select:
image

How can I resolve this problem? Is that a bug?

### LINKED ISSUE #18346: Adding Non-Nullable Property to Discriminator Class Causes NullReferenceException in EntityLoadInfo.Materialize
I have a database table that uses a discriminator like so in `OnModelCreating`:

            builder.Entity<Business>()
                .HasDiscriminator(x => x.Type)
                .HasValue<Shop>(BusinessType.Shop)
                .HasValue<Brand>(BusinessType.Brand);

I added a bool property to the `Shop` class. The migration had `nullable: true` specified in the `AlterColumn` statement, so it was added as nullable in the database. I assume this is necessary because the bool is only on one of the classes that are stored on the same table.

When running the application it throws this exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , MaterializationContext )
   at Microsoft.EntityFrameworkCore.Query.EntityLoadInfo.Materialize()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.GetEntity(IKey key, EntityLoadInfo entityLoadInfo, Boolean queryStateManager, Boolean throwOnNullKey)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
```

Changing the type to `bool?` makes it work fine, but I would have expected an error when attempting to add the migration, not a confusing runtime NullReferenceException.

### Further technical details

EF Core version: 2.2.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 2.2
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.3

### PR DESCRIPTION
**Pull request by maumar**
Resolves #14028
Resolves #18346

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs [hunk 1]
```diff
@@ -7761,6 +7761,80 @@ private SqlServerTestStore CreateDatabase21540()
...
+        }
+
+        private SqlServerTestStore CreateDatabase18346()
+            => CreateTestStore(
+                () => new MyContext18346(_options),
+                context =>
+                {
+                    var shop1 = new Shop18346 { IsOnline = true, Name = "Amzn" };
+                    var shop2 = new Shop18346 { IsOnline = false, Name = "Mom and Pop's Shoppe" };
+                    var brand = new Brand18346 { Name = "Tsla" };
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs:7828]: Too much stock market for today? :trollface:
