### PR TITLE
Only null non-overlapping FK properties on delete/fixup, if possible

### LINKED ISSUE #23883: Set nullable properties of a composite foreign key to null when OnDeleteBehavior is ClientSetNull
If two entities are related through a composite foreign key where just some of the properties are nullable, and the user tries to remove the dependent entity using ```context.Remove(dependentEntity)```, the operation will fail. I assume this happens because EF is not recognizing that only parts of the FK are nullable and therefore should be set to null (I am assuming this from  https://github.com/dotnet/efcore/issues/22196#issuecomment-680144893).

However, if the relationship has been configured using ```OnDelete(DeleteBehaviour.ClientSetNull)```, couldn't EF just scan the properties of the FK that are nullable and set only those to null?

I am sending attached a solution that reproduces the problem and provides a workaround. I will detail it a bit below.

Consider the following entities (I've simplified it a bit, the repro contains more accurate code):
```csharp
public class RootEntity
{
    public long Id { get; set; }
    public List<DependantEntity> Dependants { get; set; }
    public List<ParentEntity> Parents { get; set; }
}

public class ParentEntity
{
    public long Id { get; set; }
    public long? DependantId { get; set; }
    public long RootId { get; set; }

    public RootEntity Root { get; set; } = null!;
    public DependantEntity? Dependant { get; set; }
}

public class DependantEntity
{
    public long Id { get; set; }
    public long RootId { get; set; }

    public RootEntity Root { get; set; } = null!;
    public ParentEntity Parent { get; set; } = null!;
}
```

With the following model configuration:
```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    modelBuilder.Entity<RootEntity>(builder =>
    {
        builder.HasKey(x => x.Id);

        builder.HasMany(x => x.Depandents).WithOne(x => x.Root)
            .HasForeignKey(x => new { x.RootId })
            .HasPrincipalKey(x => x.Id)
            .OnDelete(DeleteBehavior.Cascade);

        builder.HasMany(x => x.Parents).WithOne(x => x.Root)
            .HasForeignKey(x => new { x.RootId })
            .HasPrincipalKey(x => x.Id)
            .OnDelete(DeleteBehavior.Cascade);
    });

    modelBuilder.Entity<ParentEntity>(builder =>
    {
        builder.HasKey(x => x.Id);

        builder.HasOne(x => x.Dependant).WithOne(x => x!.Parent).IsRequired(false)
            .HasForeignKey<ParentEntity>(x => new { x.RootId, x.DependantId })
            .HasPrincipalKey<DependantEntity>(x => new { x.RootId, x.Id })
            .OnDelete(DeleteBehavior.ClientSetNull);
    });

    modelBuilder.Entity<DependantEntity>(builder =>
    {
        builder.HasKey(x => x.Id);
    });
}
```

If we run:
```csharp
using (var context = new ApplicationDbContext())
{
    context.Database.EnsureDeleted();
    context.Database.Migrate();

    RootEntity root = RootEntity.CreateNew();
    context.Add(root);
    context.SaveChanges();

    ParentEntity parent = new ParentEntity
    {
        Root = root
    };
    context.Add(parent);
    context.SaveChanges();

    DependantEntity dependant = new DependantEntity
    {
        Root = root,
        Parent = parent
    };
    context.Add(dependant);
    context.SaveChanges();

    context.Remove(dependant); // exception: The association between entity types 'RootEntity' and 'ParentEntity'
                                // has been severed, but the relationship is either marked as required or is implicitly
                                // required because the foreign key is not nullable. If the dependent/child entity should
                                // be deleted when a required relationship is severed, configure the relationship to use
                                // cascade deletes. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging'
                                // to see the key values.

    context.SaveChanges();
}
```
Then we will get the exception mentioned in the comment above.

However, EF would have been able to successfully persist the changes if it had set the navigation properties and nullable properties of the FK to null. To workaround the issue, I've changed the delete behaviour to ClientNoAction and I've overriden the ```Remove(TEntity entity)``` and ```SaveChanges``` methods as:

```csharp
public override EntityEntry<TEntity> Remove<TEntity>(TEntity entity)
{
    SetForeignKeysToNull(entity);
    return base.Remove(entity);
}

public override int SaveChanges()
{
    this.setForeignKeysInRelatedEntitiesToNullIfNeeded();
    return base.SaveChanges();
}

private void setForeignKeysInRelatedEntitiesToNullIfNeeded()
{
    var toBeRemoved = ChangeTracker.Entries().Where(x => x.State == EntityState.Deleted);
    foreach (EntityEntry entity in toBeRemoved)
        SetForeignKeysToNull(entity.Entity);
}

private void SetForeignKeysToNull<TEntity>(TEntity entity)
    where TEntity : class
{
    List<ReferenceEntry> relatedNavigations = this.ChangeTracker.Entries()
        .SelectMany(x => x.References
            .Where(y => y.CurrentValue == entity && ((INavigation)y.Metadata).ForeignKey.DeleteBehavior == DeleteBehavior.ClientNoAction))
        .ToList();

    foreach (ReferenceEntry referenceEntry in relatedNavigations)
    {
        object relatedEntity = referenceEntry.EntityEntry.Entity;

        INavigation navigation = (INavigation)referenceEntry.Metadata;
        MethodInfo? pi = navigation.PropertyInfo.GetSetMethod(nonPublic: true);
        if (pi != null)
        {
            _ = pi.Invoke(relatedEntity, new object?[] { null });
        }
        else
        {
            FieldInfo? bf = navigation.FieldInfo;
            if (bf != null)
                bf.SetValue(relatedEntity, new object?[] { null });
        }

        foreach (IProperty p in navigation.ForeignKey.Properties)
        {
            if (p.IsNullable)
            {
                MethodInfo? setter = p.PropertyInfo.GetSetMethod(nonPublic: true);
                if (setter != null)
                    _ = setter.Invoke(relatedEntity, new object?[] { null });
            }
        }
    }
}
```

With the above code, both Remove and SaveChanges work.

Wouldn't EF be able to this automatically?

May be related to #22196, #10250

[clientsetnull-compositekey-v1.zip](https://github.com/dotnet/efcore/files/5816477/clientsetnull-compositekey-v1.zip)

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #23883

This is only relevant for overlapping composite foreign keys, where nulling all FK values can also sever other relationships. Since a composite FK is null if any part is null, we avoid nulling the properties that are also shared with another foreign key.

### CODE REVIEW

File: src/EFCore/Metadata/IForeignKey.cs [hunk 1]
```diff
@@ -88,5 +88,42 @@ public interface IForeignKey : IReadOnlyForeignKey, IAnnotatable
         /// <typeparam name="TKey"> The type of key instances. </typeparam>
         /// <returns> A new factory. </returns>
         IDependentKeyValueFactory<TKey>? GetDependentKeyValueFactory<TKey>();
+
+        /// <summary>
+        ///     Finds the list of properties of this foreign key that are not also properties of another foreign key, if possible,
+        ///     otherwise returns all properties.
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/IForeignKey.cs:94]:
```suggestion
        ///     Finds the list of properties of this foreign key that are not also properties of another foreign key.
```
The non-composite case should be filtered too, since the composite one can return an empty list. Let the caller deal with this, makes this method simpler.

File: src/EFCore/Metadata/IForeignKey.cs [hunk 2]
```diff
@@ -88,5 +88,42 @@ public interface IForeignKey : IReadOnlyForeignKey, IAnnotatable
...
+        /// </summary>
+        /// <param name="fkProperties"> The foreign key properties. </param>
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/IForeignKey.cs:96]:
```suggestion
        /// <param name="fkProperties"> The non-overlapping foreign key properties. </param>
```

File: src/EFCore/Metadata/IForeignKey.cs [hunk 3]
```diff
@@ -88,5 +88,42 @@ public interface IForeignKey : IReadOnlyForeignKey, IAnnotatable
...
+        /// <param name="pkProperties"> The principal key properties. </param>
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/IForeignKey.cs:97]:
```suggestion
        /// <param name="pkProperties"> The corresponding principal key properties. </param>
```

File: src/EFCore/Metadata/IForeignKey.cs [hunk 4]
```diff
@@ -88,5 +88,42 @@ public interface IForeignKey : IReadOnlyForeignKey, IAnnotatable
...
+        void GetPropertiesWithMinimalOverlap(
+            out IReadOnlyList<IProperty> fkProperties,
+            out IReadOnlyList<IProperty> pkProperties)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/IForeignKey.cs:100]:
```suggestion
            out IReadOnlyList<IProperty> foreignKeyProperties,
            out IReadOnlyList<IProperty> principalKeyProperties)
```

File: src/EFCore/Metadata/IForeignKey.cs [hunk 5]
```diff
@@ -88,5 +88,42 @@ public interface IForeignKey : IReadOnlyForeignKey, IAnnotatable
...
+                if (dependentProperty.GetContainingForeignKeys().Count() > 1)
+                {
+                    if (ReferenceEquals(fkProperties, Properties))
+                    {
+                        fkProperties = Properties.ToList();
+                        pkProperties = PrincipalKey.Properties.ToList();
+                    }
+                    
+                    ((List<IProperty>)fkProperties).Remove(dependentProperty);
+                    ((List<IProperty>)pkProperties).Remove(PrincipalKey.Properties[i]);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/IForeignKey.cs:124]:
```suggestion
                    ((List<IProperty>)fkProperties).RemoveAt(i);
                    ((List<IProperty>)pkProperties).RemoveAt(i);
```

File: src/EFCore/Metadata/IForeignKey.cs [hunk 6]
```diff
@@ -88,5 +88,42 @@ public interface IForeignKey : IReadOnlyForeignKey, IAnnotatable
...
         /// <returns> A new factory. </returns>
         IDependentKeyValueFactory<TKey>? GetDependentKeyValueFactory<TKey>();
+
+        /// <summary>
+        ///     Finds the list of properties of this foreign key that are not also properties of another foreign key, if possible,
+        ///     otherwise returns all properties.
+        /// </summary>
+        /// <param name="fkProperties"> The foreign key properties. </param>
+        /// <param name="pkProperties"> The principal key properties. </param>
+        void GetPropertiesWithMinimalOverlap(
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/IForeignKey.cs:98]:
```suggestion
        void GetPropertiesWithoutOverlap(
```

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore/Metadata/IForeignKey.cs (hunk 1 above)
Comment (ajcvickers) [reply src/EFCore/Metadata/IForeignKey.cs:94]: The most common case here is a single property. In this case we bail out early because the set of not overlapping properties is empty, and hence we want to just use all properties--in this case one.

The next most common case here is a composite property with no overlap. In this case we also want to use all properties.

Both these cases avoid allocating since there is no change to the properties that we will use.

The uncommon cases here are where there are overlapping properties. This is the only case for which we allocate new lists. However, as you point out, this list could be empty, in which case we again will default to all properties. I'll add code to check for this case.

**Comment by ajcvickers** [comment]
@AndriySvyryd Pushed a new version

**Review by AndriySvyryd — APPROVED** [review]
Though I'd still prefer either reducing the responsibilities of `GetPropertiesWithMinimalOverlapIfPossible` to shorten the name or making it an Internal extension method

**Comment by ajcvickers** [comment]
I'll make it an internal extension method.
