### PR TITLE
Avoid using `^` and `~` when invalid because of value converters

### LINKED ISSUE #35093: The data types varchar and nvarchar are incompatible in the '^' operator
Projection to Boolean of Equals comparator of a Enum property (that has custom ValueConverter to string) with one of possibles values of Enum translates to SQL with the new XOR ('^') operator implementation, causing 'The data types varchar and nvarchar are incompatible in the '^' operator'.

```C#
dbContext.Orders.Select(order=> new OrderModel {  Paid = order.State == OrderState.Paid }).ToList();

enum OrderState { Unpaid, Paid, ... }

class OrderStateConverter : ValueConverter<OrderState, string> 
{
  private static string ConvertToString(OrderState state)
  {
      return stateswitch
      {
          OrderState.Unpaid=> "U",
          OrderState.Paid => "P",
          ....
          _ => throw new InvalidEnumArgumentException(nameof(state), (int)state, typeof(OrderState))
      };
  }
  private static OrderState ConvertToEnum(string state)
  {
       return state.ToUpperInvariant() switch
       {
           "U" => OrderState.Unpaid,
           "P" => OrderState.Paid,
            ....
           _ => throw new InvalidEnumArgumentException(...)
       };
  }
}

```
Translate to SQL as
```SQL
CAST([p0].[State] ^ N''S'' AS bit) AS [Paid]
```

EF Core version: 9.0.0
Database provider:  Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11 10.0.22631
IDE: Visual Studio 2022 17.11.6

### PR DESCRIPTION
**Pull request by ranma42**
The transformation of equality/in-equality in a (negated) XOR is only possible
when the expressions are BIT or integer types on the SQL side (i.e. taking value
conversion into account).

Similarly, the Boolean negation `NOT` can be implemented as `~` only if the
underlying expression is a BIT.

Fixes #35093.

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs [hunk 1]
```diff
@@ -206,9 +206,11 @@ protected virtual Expression VisitSqlBinary(SqlBinaryExpression binary, bool inS
 
         if (binary.OperatorType is ExpressionType.NotEqual or ExpressionType.Equal)
         {
+            var leftType = newLeft.TypeMapping?.Converter?.ProviderClrType ?? newLeft.Type;
+            var rightType = newRight.TypeMapping?.Converter?.ProviderClrType ?? newRight.Type;
             if (!inSearchConditionContext
-                && (newLeft.Type == typeof(bool) || newLeft.Type.IsEnum || newLeft.Type.IsInteger())
-                && (newRight.Type == typeof(bool) || newRight.Type.IsEnum || newRight.Type.IsInteger()))
+                && (leftType == typeof(bool) || leftType.IsEnum || leftType.IsInteger())
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs:212]: I think the IsEnum case can be removed, since now that we're looking at the provider type is should never be an enum (enums are value-converted to int)

File: src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs [hunk 2]
```diff
@@ -265,7 +267,9 @@ protected virtual Expression VisitSqlUnary(SqlUnaryExpression sqlUnaryExpression
             case ExpressionType.Not when sqlUnaryExpression.Type == typeof(bool):
             {
                 // when possible, avoid converting to/from predicate form
-                if (!inSearchConditionContext && sqlUnaryExpression.Operand is not (ExistsExpression or InExpression or LikeExpression))
+                if (!inSearchConditionContext &&
+                    sqlUnaryExpression.TypeMapping?.Converter is null &&
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs:271]: Isn't a more correct fix here to look at `sqlUnaryExpression.TypeMapping?.Converter?.ProviderClrType ?? sqlUnaryExpression.Type` above (in the `when` comparing to `typeof(bool)`)? For example, if there's a Y/N string being value converted to BIT, I think we do want this code to go through and do OnesComponent (on the database side it's just a BIT).

**Review by roji — CHANGES_REQUESTED** [review]
@ranma42 thanks for working on this and sorry it took a while to review (lots of workload at the moment post-9.0!).

See my two comments and let me know what you think... FYI the deadline for getting a fix into 9.0.1 is extremely close (ideally we'd have this finished today). If you can, please let me know if you don't have time to iterate over this right away - I'm happy to take over and do changes.

Once we're good here I'll also prepare a backport PR for 9.0.1.

File: src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs (hunk 2 above)
Comment (ranma42) [reply src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs:271]: yup, I just thought that it was not a very likely scenario; will update ASAP

**Comment by ranma42** [comment]
I will try to push the changes tonight (aka in ~4 hours)

File: src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs (hunk 2 above)
Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs:271]: You'd be surprised what people do 🤣

Comment (ranma42) [reply src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs]: I am not even sure if it is possible to build an expression in which a y/n string is being negated 🤔 
I applied your suggestion, but I don't have time to add a test for this case right now (I can work on it in the weekend, if needed).

Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs]: You're generally complete right... Though I'll point out that `Expression.Not()` has an [overload](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.not?view=net-7.0#system-linq-expressions-expression-not(system-linq-expressions-expression-system-reflection-methodinfo)) which accepts an implementing method - this allows arbitrary types to be "negatable". Similarly, IIRC user types which implement the a not operator via operator overloading should also be supported (by am no longer sure about that).

Of course, it could be argued that EF shouldn't translate negation for those cases (where the implementing method/operator obviously are not taken into account)... But this is all indeed highly academic. I also don't think a test is necesary here at this point.

**Review by roji — APPROVED** [review]
Thanks as always @ranma42!

**Comment by roji** [comment]
Backport PR: https://github.com/dotnet/efcore/pull/35241
