### PR TITLE
Fix for 10508. Create Association Entity automatically by convention.

### LINKED ISSUE #10508: Implement many-to-many relationships without mapping join table
This issue tracks work on many-to-many relationships in EF Core. Subscribe to this issue to get updates when progress is made on many-to-many relationships. This issue is locked for now to reduce noise. Please use issue #1368 for general discussion on many-to-many relationships.

### PR DESCRIPTION
**Pull request by lajones**
Fixes #10508 

Create Association Entity automatically by convention. Note: this is only the model building part - also need #19003 for the ChangeTracking part.

### CODE REVIEW

**Comment by smitpatel** [comment]
@lajones - It passed CLA check now. Probably intermittent error in the server.

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs [hunk 1]
```diff
@@ -94,6 +94,15 @@ public class CollectionCollectionBuilder
             [NotNull] Func<EntityTypeBuilder, ReferenceCollectionBuilder> configureRight,
             [NotNull] Func<EntityTypeBuilder, ReferenceCollectionBuilder> configureLeft)
         {
+            var existingAssociationEntityType = (EntityType)
+                (LeftNavigation.ForeignKey?.DeclaringEntityType
+                    ?? RightNavigation.ForeignKey?.DeclaringEntityType);
+            if (existingAssociationEntityType != null)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]:
```suggestion
            if (existingAssociationEntityType != null
                && existingAssociationEntityType.ClrType != joinEntity)
```

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: Same below

File: src/EFCore/Metadata/Conventions/BackingFieldConvention.cs [hunk 2]
```diff
@@ -80,7 +80,8 @@ private FieldInfo GetFieldToSet(IConventionPropertyBase propertyBase)
         {
             if (propertyBase == null
                 || !ConfigurationSource.Convention.Overrides(propertyBase.GetFieldInfoConfigurationSource())
-                || propertyBase.IsIndexerProperty())
+                || propertyBase.IsIndexerProperty()
+                || (propertyBase.PropertyInfo == null && propertyBase.FieldInfo == null))
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/BackingFieldConvention.cs:84]:
```suggestion
                || propertyBase.IsShadowProperty())
```

File: src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs [hunk 3]
```diff
@@ -710,7 +710,6 @@ public override IConventionNavigationBuilder OnNavigationAdded(IConventionNaviga
                     {
                         if (navigationBuilder.Metadata.Builder == null)
                         {
-                            Check.DebugAssert(false, "null builder");
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs:713]: Why was this removed?

File: src/EFCore/Metadata/Conventions/ManyToManyConvention.cs [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+
+namespace Microsoft.EntityFrameworkCore.Metadata.Conventions
+{
+    /// <summary>
+    ///     A convention which looks for matching skip navigations and automatically creates
+    ///     a many-to-many association entity with suitable foreign keys, sets the two
+    ///     matching skip navigations to use those foreign keys and makes them inverses of
+    ///     one another.
+    /// </summary>
+    public class ManyToManyConvention : ISkipNavigationAddedConvention
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/ManyToManyConvention.cs:19]:
```suggestion
    public class ManyToManyAssociationEntityTypeConvention : ISkipNavigationAddedConvention
```

File: src/EFCore/Metadata/Conventions/ManyToManyConvention.cs [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+
+            var skipNavigation = skipNavigationBuilder.Metadata;
+            if (skipNavigation.ForeignKey != null
+                || skipNavigation.TargetEntityType == skipNavigation.DeclaringEntityType
+                || !skipNavigation.IsCollection)
+            {
+                // do not create an automatic many-to-many association entity type
+                // for a self-referencing skip navigation, or for one that
+                // is already "in use" (i.e. has its Foreign Key assigned).
+                return;
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/ManyToManyConvention.cs:55]: Why not doing it for self-ref?

File: src/EFCore/Metadata/Conventions/ManyToManyConvention.cs [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+            }
+
+            var matchingSkipNavigation = skipNavigation.TargetEntityType
+                .GetSkipNavigations()
+                .FirstOrDefault(sn => sn.TargetEntityType == skipNavigation.DeclaringEntityType);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/ManyToManyConvention.cs:60]:
```suggestion
            var matchingSkipNavigation = skipNavigation.Inverse;
```

File: src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs (hunk 3 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs:713]: I'm not sure why it was in there. If you look at all the other `OnXyzRemoved()` methods they all have the same `if` but without the `DebugAssert`. In practice this happens when you add a `SkipNavigation` in a delayed batch of conventions, and then remove that `SkipNavigation` before the batch has had a chance to run. This happens now because if you are attempting to create an association entity but some portion of the set up is not yet complete and the attempt fails then we roll back the `SkipNavigation`s as well (in the cases where we created them).

File: src/EFCore/Metadata/Conventions/ManyToManyConvention.cs [hunk 7]
```diff
@@ -0,0 +1,79 @@
...
+        /// <summary>
+        ///     Called after a skip navigation is added to an entity type.
+        /// </summary>
+        /// <param name="skipNavigationBuilder"> The builder for the skip navigation. </param>
+        /// <param name="context"> Additional information associated with convention execution. </param>
+        public virtual void ProcessSkipNavigationAdded(
+            IConventionSkipNavigationBuilder skipNavigationBuilder,
+            IConventionContext<IConventionSkipNavigationBuilder> context)
+        {
+            Check.NotNull(skipNavigationBuilder, "skipNavigationBuilder");
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/ManyToManyConvention.cs:44]:
```suggestion
            Check.NotNull(skipNavigationBuilder, nameof(skipNavigationBuilder));
```

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs [hunk 8]
```diff
@@ -248,6 +249,15 @@ private IReadOnlyList<RelationshipCandidate> FindRelationshipCandidates(IConvent
                         continue;
                     }
 
+                    var existingSkipNavigation = entityType.FindSkipNavigation(navigationPropertyName);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:252]: Wrap in `if(existingNavigation == null)`

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs [hunk 9]
```diff
@@ -573,29 +583,73 @@ private IReadOnlyList<RelationshipCandidate> FindRelationshipCandidates(IConvent
...
+                                .FindDeclaredSkipNavigation(navigationPropertyName)?
+                                .ForeignKey?.DeclaringEntityType;
+                            if (associationEntityType != null)
+                            {
+                                var modelBuilder = associationEntityType.Model.Builder;
+                                // The PropertyInfo underlying this skip navigation has become
+                                // ambiguous since we used it, so remove the association entity
+                                // if it was automatically created.
+                                if (modelBuilder.RemoveAssociationEntityIfAutomaticallyCreated(
+                                        associationEntityType, true, ConfigurationSource.Convention) == null)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:611]: Also remove the skip navigations

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: Couple of questions:
1. Is this to catch if you're calling `UsingEntity()` twice? I.e. reconfiguring the same join entity type?
2. I think you're assuming that CLR type uniquely identifies the join entity type? An automatic association entity type will have CLR type `Dictionary<string, object>` and is a shared-type entity type. If you pass in a different shared-type Entity Type it would have the same CLR type but would be a different join entity type. In that case you _would_ want to remove the previous automatic one. If you pass in a non-shared-type one, then the only time this would not remove would be if you are reconfiguring the same Join Entity - hence Q1?

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs [hunk 10]
```diff
@@ -573,29 +583,73 @@ private IReadOnlyList<RelationshipCandidate> FindRelationshipCandidates(IConvent
...
 
                     foreach (var inverseProperty in relationshipCandidate.InverseProperties.ToList())
                     {
-                        var existingInverse = targetEntityType.FindDeclaredNavigation(inverseProperty.GetSimpleMemberName());
-                        if (existingInverse != null
-                            && existingInverse.ForeignKey.DeclaringEntityType.Builder
-                                .HasNoRelationship(existingInverse.ForeignKey) == null
-                            && existingInverse.ForeignKey.Builder.HasNavigation(
-                                (string)null, existingInverse.IsOnDependent) == null)
+                        var inversePropertyName = inverseProperty.GetSimpleMemberName();
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:622]: Consider extracting the body of this foreach as a method to remove duplication from above

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs [hunk 11]
```diff
@@ -725,6 +783,90 @@ private IReadOnlyList<RelationshipCandidate> FindRelationshipCandidates(IConvent
             }
         }
 
+        private void HasManyToManyRelationship(
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:786]: Inline this into `HasRelationship`

File: src/EFCore/Metadata/Conventions/ManyToManyConvention.cs (hunk 5 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/ManyToManyConvention.cs:55]: If I have 2 collection navigations pointing to an Entity Type from that same Entity Type, my expectation would be two 1:N navigations to self rather than one N:N. I guess I thought that it was ambiguous, and in ambiguous cases we do nothing and let the user decide.

File: src/EFCore/Metadata/Conventions/ManyToManyConvention.cs (hunk 6 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/ManyToManyConvention.cs:60]: I don't think the Inverse is set yet - we set it as part of matching them up.

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 9 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:611]: That's what passing `true` does. I could make it `removeSkipNavigations: true` to make it more clear.

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: 1. It's to allow to configure the entity type created automatically.
2. This method takes a `Type`, so there shouldn't be confusion.

File: src/EFCore/Metadata/Conventions/ManyToManyConvention.cs (hunk 5 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/ManyToManyConvention.cs:55]: We should discuss with the team

File: src/EFCore/Metadata/Conventions/ManyToManyConvention.cs (hunk 6 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/ManyToManyConvention.cs:60]: Ok, then move the `HasInverse` call from `Using` to `WithMany`. The user specified how the navigations are matched and we should preserve that.

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 9 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:611]: Yes, that would help

File: src/EFCore/Metadata/Conventions/ManyToManyConvention.cs (hunk 5 above)
Comment (smitpatel) [reply src/EFCore/Metadata/Conventions/ManyToManyConvention.cs:55]: Any m2m navigation pair is potentially 2 different 1:N relationships.

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs [hunk 12]
```diff
@@ -725,6 +783,90 @@ private IReadOnlyList<RelationshipCandidate> FindRelationshipCandidates(IConvent
...
+                ((InternalModelBuilder)entityTypeBuilder.ModelBuilder).AssociationEntity(
+                    (SkipNavigation)leftSkipNavigation,
+                    (SkipNavigation)rightSkipNavigation,
+                    ConfigurationSource.Convention);
+            if (associationEntityTypeBuilder == null)
+            {
+                // Failed to create the association entity type - so remove
+                // both the skip navigations we just created as well.
+                leftEntityType.RemoveSkipNavigation(leftSkipNavigation);
+                rightEntityType.RemoveSkipNavigation(rightSkipNavigation);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:866]: In what case would this actually remove the skip navigations?

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 11 above)
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:786]: Filed https://github.com/dotnet/efcore/issues/21486 to move this to the builder

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: The only time `existingAssociationEntityType.ClrType != joinEntity` would be `false` would be if you passed `Dictionary<string, object>` as `joinEntity` i.e. the entity is a shared-type entity type (STET). You're saying that means that you want to configure the existing automatic entity type.

But:
1. I don't think you want to configure the left and right FKs for an automatic join entity - the automatic join entity was created solely to have those FKs on it - so there's nothing to configure them to except what they're already configured to be. And I certainly don't want to be forced to construct those configurations just so that I can use the override with `configureAssociation`. I am planning to look into a version of `UsingEntity` which only provides `configureAssociation` to e.g. allow you to rename the join table, but that was going to be another PR.
2. Knowing that the CLR type is `Dictionary<string, object>` is not the same as knowing that the join entity is the same. Many STETs will have CLR type `Dictionary<string, object>`. What if I want to replace the automatic join entity with a different STET? In that case I _would_ need to configure the left and right FKs but I also want to remove the old automatically-created entity type and use my new one instead. To do that I would need new API to pass in enough information (either as `IEntityType` or entity type name) to uniquely identify the join entity type.

So my suggestion would be that if the `Type` passed in is one of the model's shared-types then we throw an exception here and say you need to use different API.

File: src/EFCore/Metadata/Conventions/ManyToManyConvention.cs (hunk 6 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/ManyToManyConvention.cs:60]: That should work. I'll give it a try,

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: 1. I also want to configure the FK names
2. Property bag entity types only differ based on their configuration, so there's no benefit in removing the automatically created one to replace it with a structurally identical one.

I don't mind having another overload with less parameters, but this one shouldn't do unnecessary work.

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 12 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:866]: Try debugging e.g. the test `Many_to_many_join_table_stored_in_snapshot`. In that case, this situation occurs when a 2nd entity type has been pulled in to the model because the 1st entity type references it, but `KeyDiscoveryConvention` has not yet run on the 2nd entity type - so it doesn't yet have a PK. Then the FK that uses that PK cannot be set up, `AssociationEntity()` returns `null` and we need to remove the skip navs.

Of course `KeyDiscoveryConvention` does run on 2nd entity type later, and this all gets resolved after that.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:866]: Ok, so we can remove this from here and let the association convention create it when it becomes possible

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs [hunk 13]
```diff
@@ -211,6 +212,191 @@ public InternalModelBuilder([NotNull] Model metadata)
...
+                return null;
+            }
+
+            Debug.Assert(associationEntityType.GetForeignKeys().Count() == 2,
+                "Automatically created association entity types should have exactly 2 foreign keys");
+            foreach (var fk in associationEntityType.GetForeignKeys())
+            {
+                var principalEntityType = fk.PrincipalEntityType;
+                var skipNavigation = principalEntityType
+                    .GetSkipNavigations().FirstOrDefault(sn => fk == sn.ForeignKey);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalModelBuilder.cs:382]:
```suggestion
                var skipNavigation = fk.GetReferencingSkipNavigations().FirstOrDefault();
```

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs [hunk 14]
```diff
@@ -211,6 +212,191 @@ public InternalModelBuilder([NotNull] Model metadata)
             return entityTypeWithDefiningNavigation?.Builder;
         }
 
+        private const string AssociationEntityTypeNameTemplate = "Join_{0}_{1}";
+        private const string AssociationPropertyNameTemplate = "{0}_{1}";
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalModelBuilder.cs:216]: We should discuss both of these with the team

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs [hunk 15]
```diff
@@ -211,6 +212,191 @@ public InternalModelBuilder([NotNull] Model metadata)
...
+            Check.NotNull(leftSkipNavigation, nameof(leftSkipNavigation));
+            Check.NotNull(rightSkipNavigation, nameof(rightSkipNavigation));
+
+            var leftEntityType = leftSkipNavigation.DeclaringEntityType;
+            var rightEntityType = rightSkipNavigation.DeclaringEntityType;
+
+            if (leftSkipNavigation.TargetEntityType != rightEntityType
+                || rightSkipNavigation.TargetEntityType != leftEntityType)
+            {
+                if (configurationSource != ConfigurationSource.Explicit)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalModelBuilder.cs:237]: We should throw for any configuration source. Usually we noop only when the configuration cannot be applied at the given configuration source but would work with explicit.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 14 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:216]: Sure.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 15 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:237]: I thought you said no throwing outside of ModelFinalizing because we want users to be able to go back and fix it using fluent API?

File: src/EFCore/Metadata/Conventions/ManyToManyConvention.cs (hunk 5 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/ManyToManyConvention.cs:55]: Agree we should discuss with the team.

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: I'd like to throw for now. I agree you might want to configure the FKs, but `configureRight` and `configureLeft` don't give you an existing FK and allow you to configure it, instead they give you the `EntityTypeBuilder` and expect you to _create_ the FK (which will then be assigned to the SkipNav). I think we need new API for configuring an automatically-created association entity type and its FKs, and as I say I intended that to be a different PR.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 15 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:237]: Yes, and we shouldn't call this from a convention if this is going to throw, you can add `CanHaveAssociationEntity` here or `IsCompatible` on `SkipNavigation` if necessary.

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: Sure, we can throw for now

Comment (lajones) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: @AndriySvyryd For that purpose it will be cleaner to expose `_sharedEntityClrTypes` as e.g. `Model.SharedEntityClrTypes`. Any objection? I can do it without that, but the code is ugly:
```C#
            if (model.GetEntityTypes().FirstOrDefault(e => e.HasSharedClrType && joinEntity == e.ClrType) != null)
            {
                throw new InvalidOperationException("...");
            }
```

I'd prefer:
```C#
            if (model.SharedEntityClrTypes.Contains(joinEntity))
            {
                throw new InvalidOperationException("...");
            }
```

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: Yes, you can add `IConventionModel.IsShared([NotNull] Type clrType)`

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 12 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:866]: I don't think that works. This call knows that it specifically created the skip navigations and so it is safe and correct to remove them if the attempt to create the association entity fails. But `ManyToManyAssociationEntityTypeConvention` does not know that. It just knows that some skipNavs were created before it was called - it doesn't know how. I think the convention that creates the skipNavs should be responsible for removing them if necessary.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs [hunk 16]
```diff
@@ -211,6 +212,191 @@ public InternalModelBuilder([NotNull] Model metadata)
...
+                        associationEntityTypeName));
+            }
+
+            leftSkipNavigation.SetForeignKey(leftForeignKey, configurationSource);
+            rightSkipNavigation.SetForeignKey(rightForeignKey, configurationSource);
+            leftSkipNavigation.Builder.HasInverse(rightSkipNavigation, configurationSource);
+
+            // Creating the primary key below also negates the need for an index on
+            // the properties of leftForeignKey - that index is automatically removed.
+            associationEntityTypeBuilder.PrimaryKey(
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalModelBuilder.cs:314]: This can be done in the ManyToMany convention to also cover entity types added by `UsingEntity`

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs [hunk 17]
```diff
@@ -211,6 +212,191 @@ public InternalModelBuilder([NotNull] Model metadata)
...
+                dependentEndForeignKeyPropertyNames.Add(propertyName);
+                otherIdentifiers.Add(propertyName, 0);
+            }
+
+            return associationEntityTypeBuilder
+                .HasRelationship(
+                    principalEntityType.Name,
+                    dependentEndForeignKeyPropertyNames,
+                    principalKey,
+                    configurationSource)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalModelBuilder.cs:354]: Let the builder figure out the details:
```suggestion
                .HasRelationship(principalEntityType, configurationSource)
```

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:354]: Also configure the resulting FK as non-unique

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 16 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:314]: The ManyToMany convention calls this code. But that convention is only for automatic association entity types. If you are configuring your own join entity using `UsingEntity()` then you need to make sure that the join entity has a PK (as you do currently).

Not sure what you mean about KeyDiscovery?

File: src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs [hunk 18]
```diff
@@ -122,6 +122,7 @@ public virtual bool CanSetForeignKey([CanBeNull] ForeignKey foreignKey, Configur
             return (Metadata.DeclaringEntityType
                     == (Metadata.IsOnDependent ? foreignKey.DeclaringEntityType : foreignKey.PrincipalEntityType))
                             && (Metadata.Inverse?.AssociationEntityType == null
+                                || Metadata.Inverse?.AssociationEntityType?.IsAutomaticallyCreatedAssociationEntityType == true
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs:125]: Can be simplified due to short-circuiting
```suggestion
                                || Metadata.Inverse.AssociationEntityType.IsAutomaticallyCreatedAssociationEntityType
```

File: src/EFCore/Metadata/Internal/SkipNavigation.cs [hunk 19]
```diff
@@ -193,10 +193,23 @@ public virtual ForeignKey SetForeignKey([CanBeNull] ForeignKey foreignKey, Confi
...
+
+                // Have reset the foreign key of a skip navigation on one side of an
+                // automatically created association entity. That entity is only
+                // useful if both sides are configured - so remove that
+                // entity and set the Inverse skip navigation to have no foreign key.
+                // If the user wants to set the Inverse's foreign key to also point
+                // to the new association entity they will need to do that manually.
+                AssociationEntityType.Model.Builder.RemoveAssociationEntityIfAutomaticallyCreated(
+                    AssociationEntityType, false, configurationSource);
+                Inverse.SetForeignKey(null, configurationSource);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/SkipNavigation.cs:212]: This should be done in `InternalSkipNavigationBuilder`, metadata API shouldn't have side effects (apart from conventions)

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs [hunk 20]
```diff
@@ -211,6 +212,191 @@ public InternalModelBuilder([NotNull] Model metadata)
...
+            ConfigurationSource configurationSource)
+        {
+            Check.NotNull(leftSkipNavigation, nameof(leftSkipNavigation));
+            Check.NotNull(rightSkipNavigation, nameof(rightSkipNavigation));
+
+            var leftEntityType = leftSkipNavigation.DeclaringEntityType;
+            var rightEntityType = rightSkipNavigation.DeclaringEntityType;
+
+            if (leftSkipNavigation.TargetEntityType != rightEntityType
+                || rightSkipNavigation.TargetEntityType != leftEntityType)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalModelBuilder.cs:235]: We should check `Inverse` instead. It should be set before calling this.

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 12 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:866]: What I am saying is that we shouldn't try to remove the skip navigations. Just create the association entity type if possible and let it fail in model validation if not.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 16 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:314]: `KeyDiscoveryConvention` can detect this case and configure the PK, so the user doesn't have to

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 15 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:237]: We never call this with `ConfigurationSource.Explicit` (except in the tests for that purpose). This was just in case someone called this explicitly themselves.

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: If I do that ApiConsistency requires me to pass a `bool fromDataAnnotation` parameter as well, that I neither want nor need. And if I did try to do that I think I'd need to set up a `ConfigurationSource` for each shared type and all the code to manage that. So for now just doing it on `Model` and not `IConventionModel`.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: You can override ApiConsistency by adding this method to `ApiConsistencyFixture.MetadataMethodExceptions`

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 16 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:314]: In this code I know what the PK is - it comes out naturally from creating the two FKs. So I'd prefer to set it right there. If we want to change `KeyDiscoveryConvention` to set PKs for non-automatic join entities let's do that in a separate PR.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 17 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:354]: I'd rather call the specific one - I know what properties I want to use, I know what I want the principal key to be - I'd rather call that and if it errors I know what the problem is rather than having the other API take it's best guess and possibly fail, or even worse succeed but set the wrong properties/key.

Is the purpose of setting FK to non-unique to update its `ConfigurationSource`? Otherwise I think it's would be non-unique by default.

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: But I don't need it on `IConventionModel`, only on `Model`. Is there a different reason to expose it publicly?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: It seems like a generally useful method

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 17 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:354]: You are just creating the properties to use and we already have a pattern for how they are created, we don't need to duplicate the code. There are no "wrong" properties/key here
The other overload will use the primary key if it exists and create a temporary one if it doesn't, it will only return `null` if the principal entity type is configured as keyless.

> Is the purpose of setting FK to non-unique to update its ConfigurationSource? Otherwise I think it's would be non-unique by default.

Yes

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 16 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:314]: You can file a new issue to remove this code and handle it in `KeyDiscoveryConvention`

Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:314]: As I say - I do not want to remove this code. I have the properties, I know that I want to set the PK. I do not need or want `KeyDiscoveryConvention` to do it for me - it is part of the job of _this_ code to do that. The user need do nothing.

If we want to do the above for **non**-automatically created association entities that would be a separate PR.

Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:314]: P.S. If naming this method `AutomaticallyCreatedAssociationEntity()` or `CreateAutomaticAssociationEntity()` would make it clearer then I'm happy to do that. It is used _only_ for automatic creation and not for manual creation.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:314]: If `KeyDiscoveryConvention` handles it for the explicit association entity type then it can handle it for this, therefore this code would become redundant.

The only job of this method should be creating the association entity type. We can even move the creation of the foreign keys for skip navigations to a convention

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: Wouldn't exposing the list of shared types be more useful? Then not only could you do `Contains()` but also iterate over the known list.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: One would need to know whether a type is used in a STET before creating an entity type. I can't think of a useful scenario for a list of all types used in STETs

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 16 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:314]: I'm afraid I disagree. I don't think `KeyDiscoveryConvention` should do what you're suggesting. It doesn't currently and there's been no call for it AFAIK. We just let the user decide whether or not they want to add a PK to their manually-created association entity. If they do, they add it. If they don't we don't create one. That seems perfectly fine to me. If you'd like to do that then please raise a bug and we can discuss, but at the moment my vote would be against.

The purpose of this code was just to be a central place to do what both `ManyToManyAssociationEntityTypeConvention` and `RelationshipDiscoveryConvention` need doing. That includes setting up a PK. It was not intended to supercede the manual (fluent API) way of creating association entity types, because that code needs to ask the user "what entity type shall I use?" and "what foreign keys do I set up?" whereas I already know all of that because I'm creating them. I _know_ I want to create a PK in both those cases and I know the properties I want to use. I don't see any need to wait for a different convention to do it for me.

By calling this method `AssociationEntity` have I confused you into thinking that this API is for all association entities, manual or automatic? I was just trying to find a short name that fit in with the rest of the `InternalModelBuilder` methods. But I never intended that it would apply for manual association entities and I'm happy to call it something else or move it somewhere else if that makes it clearer.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 17 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:354]: I'll do the non-unique thing.

The primary key comment is moot - I check that the PK exists (I thought it would error if it didn't exist but it doesn't matter). The real difference is in the naming of the FK properties - which I'm happy to change if the team decides they don't like the naming approach I suggested.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 20 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:235]: Done

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 16 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:314]: Filed #21500

> If they do, they add it. If they don't we don't create one. 

You can say the same for most of our conventions. We have them to avoid forcing users to write repetitive code.

> That includes setting up a PK.

We try to respect the single responsibility principle whenever practical. If a piece of functionality can be handled by a class dedicated to it then it's better to move it there.

> By calling this method AssociationEntity have I confused you into thinking that this API is for all association entities, manual or automatic?

The name and location are irrelevant for this discussion, it's about the factoring.

Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:314]: I understand factoring. The single responsibility is "create an association entity configured to work". Here we directly have the properties we need, we know we want them to be a PK in both of the cases that call this code. We don't have any usage of this where we do _not_ want a PK. It seems to me that the best factoring and best single responsibility is to have 1 place that does it i.e. here.

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:100]: I could see it being used in e.g. an error message. "Sorry, don't use that type. Here are the list of types to avoid ...". But not a big deal. I'll do it the way you want.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:107]: Did you create an issue to allow using a STET as the association entity type explicitly?

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs [hunk 21]
```diff
@@ -783,6 +727,45 @@ private IReadOnlyList<RelationshipCandidate> FindRelationshipCandidates(IConvent
             }
         }
 
+        private void RemoveHigherConfigurationSourceNavigation(
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:730]:
```suggestion
        private void RemoveNavigation(
```

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs [hunk 22]
```diff
@@ -834,37 +808,31 @@ private IReadOnlyList<RelationshipCandidate> FindRelationshipCandidates(IConvent
...
-                leftEntityType.RemoveSkipNavigation(leftSkipNavigation);
-                rightEntityType.RemoveSkipNavigation(rightSkipNavigation);
-            }
+            // also sets rightSkipNavigation's inverse
+            leftSkipNavigation.Builder.HasInverse(rightSkipNavigation, fromDataAnnotation: false);
+
+            ((InternalModelBuilder)entityTypeBuilder.ModelBuilder).HasAutomaticAssociationEntity(
+                (SkipNavigation)leftSkipNavigation,
+                (SkipNavigation)rightSkipNavigation,
+                ConfigurationSource.Convention);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:835]: This can be removed, it'll be handled by the `ManyToManyAssociationEntityTypeConvention`

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs [hunk 23]
```diff
@@ -220,33 +220,87 @@ public InternalModelBuilder([NotNull] Model metadata)
         ///     any release. You should only use it directly in your code with extreme caution and knowing that
         ///     doing so can result in application failures when updating to a new Entity Framework Core release.
         /// </summary>
-        public virtual InternalEntityTypeBuilder AssociationEntity(
+        public virtual InternalEntityTypeBuilder HasAutomaticAssociationEntity(
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]:
```suggestion
        public virtual InternalEntityTypeBuilder HasAssociationEntity(
```
The "Automatic" part is implied

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs [hunk 24]
```diff
@@ -220,33 +220,87 @@ public InternalModelBuilder([NotNull] Model metadata)
...
+
+                throw new InvalidOperationException(
+                    CoreStrings.SkipNavigationForAssociationEntityTypeHasNoInverse(
+                        rightEntityType.Name,
+                        rightSkipNavigation.Name,
+                        leftEntityType.Name,
+                        leftSkipNavigation.Name));
+            }
+
+            if (leftSkipNavigation.Inverse != rightSkipNavigation)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalModelBuilder.cs:267]: You can avoid these checks if you change the method to take a single skip navigation

File: src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs [hunk 25]
```diff
@@ -94,6 +94,17 @@ public virtual InternalSkipNavigationBuilder HasForeignKey([CanBeNull] ForeignKe
...
+                if (foreignKey != Metadata.ForeignKey
+                    && Metadata.AssociationEntityType?.IsAutomaticallyCreatedAssociationEntityType == true)
+                {
+                    // Have reset the foreign key of a skip navigation on one side of an
+                    // automatically created association entity. That entity is only
+                    // useful if both sides are configured - so remove that
+                    // entity. This will remove the Inverse's foreign key as well.
+                    Metadata.AssociationEntityType.Model.Builder.RemoveAssociationEntityIfAutomaticallyCreated(
+                        Metadata.AssociationEntityType, removeSkipNavigations: false, configurationSource);
+                }
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs:106]: Did you intend to run this only if `foreignKey` is `null`?

Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs:106]: I don't think so. If you're resetting the FK of one of the skip nav's to a different FK then the association entity's FK pointing  towards that skip nav and the skip nav's `ForeignKey` property would no longer be the same thing. At that point your association entity is broken.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs:106]: The association entity type is not restricted to only have one FK per skip navigation. You can add an FK, configure the skip navigation to use it, then remove the old FK. At this point the association entity type will be valid.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs [hunk 26]
```diff
@@ -211,6 +212,243 @@ public InternalModelBuilder([NotNull] Model metadata)
...
+                .Metadata;
+        }
+
+        /// <summary>
+        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+        ///     any release. You should only use it directly in your code with extreme caution and knowing that
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        public virtual InternalModelBuilder RemoveAssociationEntityIfAutomaticallyCreated(
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalModelBuilder.cs:418]:
```suggestion
        public virtual InternalModelBuilder RemoveAssociationEntityIfCreatedImplicitly(
```
"Automatically" is too generic, same goes for `IsAutomaticallyCreatedAssociationEntityType`

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 24 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:267]: I don't think you can. Say we just pass in `leftNavigation`. `leftNavigation.Inverse` can still be `null`. It's possible to set up `leftNavigation.Inverse` to point to a `rightNavigation` whose Inverse is `null`. Likewise that `rightNavigation`s Inverse does not have to be `leftNavigation`. So I still need all the checks.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 23 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: Really! 🤨 Obvious to anyone calling that code independent of our conventions?

File: test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs [hunk 27]
```diff
@@ -1855,8 +1855,18 @@ public virtual void Throws_on_existing_one_to_one_relationship()
...
+                // set up a 1:1 relationship using Nob.Hob and Hob.Nob
                 modelBuilder.Entity<Nob>().HasOne(e => e.Hob).WithOne(e => e.Nob);
 
+                // Now that Nob.Hob and Hob.Nob are used, Nob.Hobs and Hob.Nobs
+                // are no longer ambiguous and so we automatically create the many-to-many
+                // relationship. We want to test that the HasMany().WithOne() call
+                // causes a clash with the 1:1 relationship set up above. But if we
+                // did not call Ignore below, it would report a clash with the
+                // automatic many-to-many instead.
+                modelBuilder.Entity<Hob>().Ignore(e => e.Nobs);
```
Comment (AndriySvyryd) [inline test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs:1868]: This shouldn't be necessary, explicit `HasMany().WithOne()` call should remove the many-to-many discovered by convention

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 23 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: What else could this method do?

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 24 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:267]: That is already handled in  `ModelValidator.ValidateRelationships`.

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 22 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:835]: Ugh! This is why I didn't want `ManyToManyAssociationEntityTypeConvention` to be a convention in the first place. I wanted it to effectively be the `HasAutomaticAssociationEntity` method. This is the consequence of me giving in on that. Let me revisit on that. In two places (`RelationshipDiscoveryConvention` and at the end of `WithMany()`) we end up knowing that there are a pair of matched SkipNavigations. We want, for that pair, to create an implicit association entity type which is configured and ready to go, and to do so once.

My original approach was a method that took the two SkipNav's and just did that. Tell me again why I instead want a convention that looks at _all_ skip navigations - and even in the correct scenario tries to set this entity type up twice (once for each SkipNav)? As far as I can see it doesn't do anything that the method wouldn't do, and it does so much less performantly.

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:107]: https://github.com/dotnet/efcore/issues/9914#issuecomment-644986633 would add an overload here which takes string name of the entity type which can be STET or non-shared either.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 26 above)
Comment (smitpatel) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:418]: Why automatic, why not conventionally? 🙃

File: src/EFCore/Properties/CoreStrings.resx [hunk 28]
```diff
@@ -1421,4 +1421,16 @@
   <data name="UnhandledNavigationBase" xml:space="preserve">
     <value>Unhandled 'INavigationBase' of type '{type}'.</value>
   </data>
+  <data name="SkipNavigationForAssociationEntityTypeHasNoInverse" xml:space="preserve">
+    <value>Cannot use using skip navigation '{declaringEntityType}.{skipNavigationName}' to create an association entity type. Its inverse is not set. The inverse should be the other skip navigation, '{otherEntityType}.{otherSkipNavigationName}'.</value>
```
Comment (smitpatel) [inline src/EFCore/Properties/CoreStrings.resx:1425]: use using?

File: src/EFCore/Properties/CoreStrings.resx [hunk 29]
```diff
@@ -1421,4 +1421,16 @@
...
+  </data>
+  <data name="SkipNavigationForAssociationEntityTypeWrongInverse" xml:space="preserve">
+    <value>Cannot use using skip navigation '{declaringEntityType}.{skipNavigationName}' to create an association entity type. Its inverse is '{inverseEntityType}.{inverseSkipNavigationName}', but it should be '{otherEntityType}.{otherSkipNavigationName}'.</value>
+  </data>
+  <data name="UnableToCreateSkipNavigationForeignKeyOnAssociationEntityType" xml:space="preserve">
+    <value>Cannot create a foreign key for skip navigation '{declaringEntityType}.{skipNavigationName}' on association entity type '{associationEntityType}'. Ensure '{declaringEntityType}' has a primary key and is not ignored in the model.</value>
+  </data>
+  <data name="DoNotUseUsingEntityOnSharedClrType" xml:space="preserve">
```
Comment (smitpatel) [inline src/EFCore/Properties/CoreStrings.resx:1433]: I don't think this should be needed. There would be a central place where we would throw if code tried to call "Entity()" with clrType matching STET. This exception throwing is not unique to UsingEntity API.

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 22 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:835]: ### Why should we use conventions instead of hardcoding the configuration in builders
#### Pros

- Composability. The logic contained in a convention doesn't directly depend on logic in other conventions. This makes them easier to test and resilient to code churn.
- Extensibility. Conventions can be added, removed, replaced and reordered by providers and (soon) by users
- Efficiency. By separating the configuration change event from the code that processes it we can avoid unnecessary calls. (E,g, if a property is removed before the added event is processed then neither event needs to be processed).
- Maintainability. Having the code separated into files by functionality makes it easier to find and understand than having it spread out through builders that are separated hierarchically.

#### Cons

- They add overhead and will be slower in many cases.
- Authoring them requires better understanding of how model building works

Comment (lajones) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:835]: Yes. I understand that. But not everything requires a new convention. Responding to your points:
1. You are directly asking for `RelationshipDiscoveryConvention` to rely on `ManyToMany...Convention` - so the logic in one is directly depending on the logic in the other. It is not making it easier to test as I can testify because I'm writing the tests. All other kinds of relationships are created by this convention, why not this one?
2. Agreed. But we are already in a convention - this is just adding another one. And we're going to make it so `RelationshipDiscoveryConvention` doesn't actually discover this relationship. Instead it discovers two skip navigations and leaves it up to another convention to "discover" the relationship. And that convention doesn't know that the two skip navigations are related so it processes each of them, instead of just the pair together.
3. I pointed out how the current way results in more calls in this case.
4. My way would be maintainable - the method that does the work is 1 encapsulated method and there is no additional convention to maintain.

Both of the cons however do apply here.

I suggest we use the method approach and only switch to a convention way of doing this if and when we find a scenario that requires it.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 23 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: Create an explicit association entity. Indeed that's what I would assume it would do. You need to know that 2 skip navigations => implicit. Why not just say so?

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 24 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:267]: But I need to know it that these things are true at this point in time - which is before `ModelValidator` runs?

File: src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs (hunk 25 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs:106]: Alright. I'm not sure why you'd ever create association entity type such that you could set up 2 FKs to the same skip nav independent of the other skip nav but OK.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 26 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:418]: "Conventionally" would be fine too. "Implicitly" sounds slightly better to me so that's what I've changed it to.

File: src/EFCore/Properties/CoreStrings.resx (hunk 29 above)
Comment (lajones) [reply src/EFCore/Properties/CoreStrings.resx:1433]: This is how I agreed with @AndriySvyryd to deal with STETs. You shouldn't use this API to try to configure the existing STET, and using only CLR type we have no way of distinguishing that from any other STET.

This is not a general principal, it is specific to this particular API. We're saying we don't want you to run this overload of `UsingEntity()` using a STET. At some stage I do plan on adding other overloads of `UsingEntity()` that you could run using a STET and at that point in time I'll update this message to suggest those - see #21505 .

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 22 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:835]: > You are directly asking for RelationshipDiscoveryConvention to rely on ManyToMany...Convention - so the logic in one is directly depending on the logic in the other. 

No, I'm asking for RelationshipDiscoveryConvention to just discover the relationship (i.e. the pair of navigations that should be connected) and let other conventions figure out the details, like we already do for foreign key properties for example.

If a provider needs to define PKs in a different way (for example they need to add a partition key property) then they wouldn't have a place to change this behavior.

> I pointed out how the current way results in more calls in this case.

If one of the navigations becomes ambiguous after it was discovered and has to be removed, then we could save some time by not creating the association entity type. But yes, in most cases it will be somewhat slower.

 > My way would be maintainable - the method that does the work is 1 encapsulated method and there is no additional convention to maintain.

Decomposing methods directly increases maintainability I don't see how your argument supports your conclusion.

Are you disagreeing with the general approach of using conventions? If not then the more functionality we can move into discreet conventions the better they will work together.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 23 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: If you were to name a method that sums two numbers which one you'd prefer?
```C#
int Sum(int x, int y)
```
or
```C#
int SumTwoIntegers(int x, int y)
```

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 24 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:267]: No, you don't. The rest of the method will run fine in the scenario you described.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 23 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: This is nowhere near that clear.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 24 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:267]: At the end of the day I want two skip nav's which are inverses of one another with an association entity type with 2 foreign keys which are also the foreign keys on the skip nav's. We no longer set the two skip nav's to be inverses of one another in this method - instead it is a pre-condition. I'm just checking that the pre-condition is true.

In an earlier comment you wanted to make sure that the two skipNav's were inverses of each other before I called this method. Now you're saying it's unimportant whether they are inverses of one another? I don't understand.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:267]: > At the end of the day I want two skip nav's which are inverses of one another with an association entity type with 2 foreign keys which are also the foreign keys on the skip nav's. We no longer set the two skip nav's to be inverses of one another in this method - instead it is a pre-condition. I'm just checking that the pre-condition is true.

You can assume this is the case and check this using `Check.DebugAssert`

> In an earlier comment you wanted to make sure that the two skipNav's were inverses of each other before I called this method. Now you're saying it's unimportant whether they are inverses of one another? I don't understand.

Yes, we need to know the matching pair of navigations, one `Inverse` already contains enough information

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 22 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:835]: Now you're defining "discovering the relationship" as "discovering the skip navigations", but throughout the rest of this convention discovering a relationship means calling some version of HasRelationship() i.e. setting up the foreign key. You can't set up the foreign keys in this case without creating the association type - so that is what it should do.

I'm not disagreeing with conventions in general. I just don't think this raises to the level that makes it worth it. I disagree that every little bit of functionality that could possibly be composed elsewhere automatically needs a convention. The convention system is big and complicated in part because of that. And yes, figuring out what convention is expecting what of which other convention is hard to understand and not really documented. Expectations in one part of it are not necessarily explained when you're looking at another part of it. The more a convention depends on other conventions, the more entangled it all gets, the more easily it gets broken and the harder it gets to change any one convention because you're not sure of its effects on all the others.

All the `ManyToMany..` convention does at the moment is check the skip navigations are inverses of one another and have foreign keys (all of which I already know at the end of `RelationshipDiscoveryConvention`) and then call the same method I would have called anyway. (And then it uselessly does it again for the 2nd skip nav).

But I'm done. I'll just live with the convention. I'm clearly not convincing you.

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:107]: > Did you create an issue to allow using a STET as the association entity type explicitly?

See #21505

File: src/EFCore/Properties/CoreStrings.resx (hunk 29 above)
Comment (smitpatel) [reply src/EFCore/Properties/CoreStrings.resx:1433]: > using only CLR type we have no way of distinguishing that from any other STET.

That is true for any API which takes clr type only to configure any kind of entityType, so I am not sure why this API is special here.

Comment (lajones) [reply src/EFCore/Properties/CoreStrings.resx:1433]: See [discussion here](https://github.com/dotnet/efcore/pull/21484/files#r448609367)

File: src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:107]: @AndriySvyryd - The call to `ModelBuilder.Entity(joinEntity, ConfigurationSource.Explicit)` throw error for STET already. Do we need to throw specific exception above?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs:107]: @smitpatel No, we are only throwing until #21505 is implemented.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 23 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: Ok, that wasn't the best example. But to someone who knows what "Automatic" refers to it is clear that's the only thing it can do with the inputs. And to someone who doesn't know it doesn't add any useful information.

Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: To someone who doesn't know what "Automatic" refers to it makes you stop and think and go "What does automatic mean? Do I want that?" Maybe that stops you from calling that method and makes you look for other ways of doing what you want to do. If you do know what "Automatic" means then maybe it confirms that this is exactly what you wanted to do and not something else which you don't want (e.g. create an explicit association). And all for the small, small price of one word in a method name on an internal class.

But all of that said, the only reason I had it here was so it could be called from both conventions. Since we now only call it in `M2MConvention` shall we just move the whole method there?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: Sure, though I'd prefer that the method that calls `AddEntityType` is on `InternalModelBuilder` and exposed through `IConventionModelBuilder.Entity`

Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: At this stage I don't need to make it public, but if you think it would be useful to others, sure. All it would do is take 2 entity types, construct a name from their names and call `AddEntityType`. Let's agree on a signature so we don't go through all of this again. How about:

```C#
public IConventionEntityTypeBuilder Entity(IConventionEntityType leftEntity, IConventionEntityType rightEntity)
```

or

```C#
public IConventionEntityTypeBuilder Entity(string leftEntityName, string rightEntityName)
```

Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: At this stage I don't need to make it public, but if you think it would be useful to others, sure. 

All it would do is take 2 entity types, construct a name from their names and call `AddEntityType`. I was thinking:

```C#
public IConventionEntityTypeBuilder Entity(IConventionEntityType leftEntity, IConventionEntityType rightEntity)
```

or

```C#
public IConventionEntityTypeBuilder Entity(string leftEntityName, string rightEntityName)
```

What were you thinking of passing in?

Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: Oh. I see. The bool is `fromDataAnnotation`, and the `Type` is for `Dictionary<string, object>` and the `string` is the already constructed name. I'm fine with that, but I think that's really something @smitpatel should decide in #9914 . So if it's OK I'll just pull it all into `M2MConvention`  for now and when @smitpatel does that work we can change it to call that method.

Comment (smitpatel) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: #9914 will add 
````
        IConventionEntityTypeBuilder Entity([NotNull] string name, [NotNull] Type clrType, bool? shouldBeOwned = false, bool fromDataAnnotation = false);
```

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: Ok

Comment (smitpatel) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs:223]: If you add something which would be changed when #9914 is finished, just add TODO note with 9914 issue number. I will take care of it.

File: src/EFCore/Metadata/Internal/Model.cs [hunk 30]
```diff
@@ -754,6 +754,15 @@ public virtual bool IsIgnored(string name)
...
             => FindIgnoredConfigurationSource(GetDisplayName(type)) != null;
 
+        /// <summary>
+        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+        ///     any release. You should only use it directly in your code with extreme caution and knowing that
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        public virtual bool IsShared([NotNull] Type type)
+            => _sharedEntityClrTypes.Contains(type);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/Model.cs:764]: We should preemptively add `Dictionary<string, object>` to `_sharedEntityClrTypes` to avoid a potential breaking change in case someone manages to use it as a non-shared type

Comment (lajones) [reply src/EFCore/Metadata/Internal/Model.cs:764]: I've been hard-coding `Dictionary<string, object>` and I'd prefer to keep it somewhere as a `public static readonly` variable, called e.g. `DefaultAssociationEntityTypeClrType`. Given that you'd like it in `_sharedEntityClrTypes` how about if that variable lives on `Model`?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/Model.cs:764]: Sounds good, but call it DefaultPropertyBagType

File: test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs [hunk 31]
```diff
@@ -1837,7 +1837,11 @@ public virtual void Throws_on_existing_many_to_many()
 
                 modelBuilder.Entity<Product>();
                 modelBuilder.Entity<Category>()
-                    .HasMany(o => o.Products).WithMany(c => c.Categories);
+                    .HasMany(o => o.Products)
+                    .WithMany(c => c.Categories)
+                    .UsingEntity<ProductCategory>(
```
Comment (AndriySvyryd) [inline test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs:1842]: Does this test fail without calling `UsingEntity`?

File: src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs [hunk 32]
```diff
@@ -17,6 +19,9 @@ namespace Microsoft.EntityFrameworkCore.Metadata.Conventions
     /// </summary>
     public class ManyToManyAssociationEntityTypeConvention : ISkipNavigationAddedConvention
     {
+        private const string AssociationEntityTypeNameTemplate = "Join_{0}_{1}";
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs:22]: This should also run on `ISkipNavigationInverseChangedConvention` as the inverse might not always be set immediately.

File: test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs (hunk 31 above)
Comment (lajones) [reply test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs:1842]: Yes. I.e. if you don't do this the code at L1852 does not throw - which looked correct to me given the earlier comment that calling `WithMany().HasOne()` should override an implicit N:N. But in this test we want to check that overriding N:N with N:1 throws, so I set up an explicit association entity in order to cause that.

Comment (AndriySvyryd) [reply test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs:1842]: But this was already an explicit N:N even without `UsingEntity`, so it should've thrown

Comment (lajones) [reply test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs:1842]: I originally had that producing an AET this way made it explicit. But we had a discussion and you said that an entity produced by `HasMany().WithMany()` with no further calls should be by convention, not explicit?

Comment (AndriySvyryd) [reply test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs:1842]: Right. The AET would be implicit, but the relationship (i.e. the skip navigations) is explicit

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 21 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:730]: There are other private methods in this class called `RemoveSingleSidedBaseNavigations`, `RemoveInheritedInverseNavigations`. The way I have it seemed more consistent. Note: I'm happy to add an `s` if you like although 1 call to this method will only ever remove 1 navigation.

File: test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs (hunk 31 above)
Comment (lajones) [reply test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs:1842]: What happens if 1 of them is explicit and 1 of them is by convention?

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 21 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:730]: They don't need to be consistent as they are used differently. The name I suggested describes what it does accurately.

Comment (lajones) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:730]: Disagree. The removal is conditional. But again I'll just update it. I'm done arguing.

File: test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs (hunk 31 above)
Comment (AndriySvyryd) [reply test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs:1842]: Overriding the explicit one will throw an exception, but the implicit one wouldn't

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 21 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:730]: Right, it only removes navigations of equal or lower configuration source. You can move out `toRemoveFrom.Remove(navigationProperty)` to make it clearer

Comment (lajones) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:730]: You appear to be saying please take out the only place that actually removes a navigation from the code that you insist be called `RemoveNavigation` and somehow that will make it clearer? I'm really sorry but I honestly no longer have any idea what that means or what you want. Please just tell me what you want it to look like and I'll copy it in verbatim.

File: test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs (hunk 31 above)
Comment (lajones) [reply test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs:1842]: I will need to discuss this with you tomorrow. This causes contradictions with the code that was put in to make the test below this one work.

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 21 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:730]: The main responsibility of this method is to remove the navigation from the model (i.e. `existingNavigation.ForeignKey.DeclaringEntityType.Builder.HasNoRelationship(existingNavigation.ForeignKey)`), only if that fails (due to the navigation being of a higher configuration source) then it would mark it as non-ambiguous (i.e. `toRemoveFrom.Remove(navigationProperty)`).

If you just rename it to `RemoveNavigation` it'd be good enough as this is a private method.

File: src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs [hunk 33]
```diff
@@ -36,19 +36,36 @@ public ManyToManyAssociationEntityTypeConvention([NotNull] ProviderConventionSet
...
+        /// <inheritdoc />
+        public virtual void ProcessSkipNavigationInverseChanged(
+            IConventionSkipNavigationBuilder skipNavigationBuilder,
+            IConventionSkipNavigation inverse,
+            IConventionSkipNavigation oldInverse,
+            IConventionContext<IConventionSkipNavigation> context)
+        {
+            Check.NotNull(skipNavigationBuilder, nameof(skipNavigationBuilder));
+            Check.NotNull(inverse, nameof(inverse));
+            Check.NotNull(oldInverse, nameof(oldInverse));
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs:59]: The definition of `ISkipNavigationInverseChangedConvention.ProcessSkipNavigationInverseChanged` is wrong. Both `inverse` and `oldInverse` can be null. Same goes for `ConventionDispatcher.OnSkipNavigationInverseChanged`

File: src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs [hunk 34]
```diff
@@ -0,0 +1,188 @@
...
+                // the inverse skip navigation is already "in use"
+                // (i.e. has its Foreign Key assigned).
+                return;
+            }
+
+            Check.DebugAssert(inverseSkipNavigation.Inverse == skipNavigation,
+                "Inverse's inverse should be the original skip navigation");
+
+            var model = skipNavigation.DeclaringEntityType.Model;
+            var declaringEntityType = skipNavigation.DeclaringEntityType;
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs:99]: ordering

File: src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs [hunk 35]
```diff
@@ -151,16 +151,38 @@ private InternalForeignKeyBuilder WithOneBuilder(MemberIdentity reference)
...
-                        SkipNavigation.DeclaringEntityType.DisplayName() + "." + SkipNavigation.Name,
-                        RelatedEntityType.DisplayName() + (reference.Name == null
-                                                        ? ""
-                                                        : "." + reference.Name),
-                        SkipNavigation.DeclaringEntityType.DisplayName() + "." + SkipNavigation.Name,
-                        SkipNavigation.TargetEntityType.DisplayName() + (SkipNavigation.Inverse == null
-                                                                        ? ""
-                                                                        : "." + SkipNavigation.Inverse.Name)));
+                if (((EntityType)SkipNavigation.AssociationEntityType)?
+                    .IsImplicitlyCreatedAssociationEntityType != true)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs:155]:
```suggestion
                if (((IConventionSkipNavigation)SkipNavigation).GetConfigurationSource() == ConfigurationSource.Explicit)
```

This should fix https://github.com/dotnet/efcore/pull/21484/files/31d8567bbefb6a012cfaff7aa6adb2145422748c..e8021a3182af25122449f0133eb14ddd6d8adbea#r450544650

File: src/EFCore/Metadata/Internal/Model.cs [hunk 36]
```diff
@@ -35,6 +35,11 @@ namespace Microsoft.EntityFrameworkCore.Metadata.Internal
     /// </summary>
     public class Model : ConventionAnnotatable, IMutableModel, IConventionModel
     {
+        /// <summary>
+        /// The CLR type that is used for property bag entity types when no other type is specified.
```
Comment (smitpatel) [inline src/EFCore/Metadata/Internal/Model.cs:39]:
```suggestion
        ///     The CLR type that is used for property bag entity types when no other type is specified.
```

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 21 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:730]: Will do that. You see I thought `HasNoRelationship` was mainly about removing a FK (removing a navigation is a side-effect), and that the main responsibility was to remove higher configuration source NavProps from the `RelationshipCandidate` so that they would no longer be considered by the rest of the code. So we were talking about different removals, both of navigations.

File: src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs (hunk 33 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs:59]: I did wonder why it was defined that way. I'll update the existing code to have `[CanBeNull]` annotations and update my code to match.

File: src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs (hunk 34 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs:99]: Sorry. Had to put model back in because we moved where this method lived and missed that.

File: src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs (hunk 35 above)
Comment (lajones) [reply src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs:155]: Yep. That's what I tried and it doesn't work. It'll be easier to show you.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 14 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs]: What was the team decision WRT to FK property naming?

Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs]: See #21565 and #21567

Comment (ajcvickers) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs]: @AndriySvyryd Is there any reason we need special rules for FKs? We decided in the design meeting to just use the current rules.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs]: No. That would be my preference as well.
