### PR TITLE
Delay synthesis of join entities until entire graph is attached

### LINKED ISSUE #23339: Cannot save changes because same join entity seems to be added multiple times
I'm buliding a mobile app which syncs it's local SQLite database with a SQL database on a server through a REST API. I'm getting an exception when saving the received data. I set up a small [reproduction repo](https://github.com/xamadev/EfCoreDataSyncTrackingIssueReproduction).

My first intention was that JSON.NET creates new objects for the same entity while parsing the json if it occurs multiple times. But JSON.NET does not like described [here](https://www.newtonsoft.com/json/help/html/PreserveObjectReferences.htm). Besides the entity UnitToElement with {FK_Element: 2, FK_Unit: 1} occurs only once in the json string.

### Stack trace

```
System.InvalidOperationException: 'The instance of entity type 'UnitToElement' cannot be tracked because another instance with the key value '{FK_Element: 2, FK_Unit: 1}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.'
```

### Include provider and version information

EF Core version: 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer ,Microsoft.EntityFrameworkCore.Sqlite
Target framework:  .NET Core 3.1

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #23339

This stops the change tracker creating a join entity instance for the same join entity that is later discovered in the graph.

### CODE REVIEW

File: src/EFCore/ChangeTracking/Internal/NavigationFixer.cs [hunk 1]
```diff
@@ -28,6 +29,7 @@ namespace Microsoft.EntityFrameworkCore.ChangeTracking.Internal
     /// </summary>
     public class NavigationFixer : INavigationFixer
     {
+        private IList<Action>? _danglingJoinEntities;
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:32]: Store the arguments for `FindOrCreateJoinEntry` in a struct to avoid allocations.

File: src/EFCore/ChangeTracking/Internal/NavigationFixer.cs [hunk 2]
```diff
@@ -46,6 +48,25 @@ public class NavigationFixer : INavigationFixer
...
+        public virtual void CompleteAttachGraph()
+        {
+            if (_danglingJoinEntities != null)
+            {
+                foreach (var synthesize in _danglingJoinEntities)
+                {
+                    synthesize();
+                }
+
+                _danglingJoinEntities = null;
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:66]: Use `Clear` instead

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore/ChangeTracking/Internal/NavigationFixer.cs (hunk 2 above)
Comment (ajcvickers) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:66]: My thoughts here is that this will usually stay null, even when attaching graphs. It will only be non-null when we actually have to store a reference to a dangling join entity. So keeping it null most of the time seemed to make sense to me.

Comment (AndriySvyryd) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:66]: Yes, but once it's not null it's much more likely that we'll have to use/create the instance again.

Comment (ajcvickers) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:66]: Why so?

Comment (ajcvickers) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:66]: Thinking more, for the common case of one unit of work with one Attach graph call, this will only ever by used once anyway. But I guess if more graphs are added to the same context, then this could get used every time. I'll make the change.

Comment (AndriySvyryd) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:66]: Because there's a code path in the application that causes it, so it's likely to trigger again during the lifetime of the app

Comment (AndriySvyryd) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:66]: I'm assuming that all apps that care about performance use context pooling :trollface:

Comment (ajcvickers) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:66]: Interesting, I hadn't thought of that. This means we should also clear this when the when the context is re-cycled.

File: src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs [hunk 3]
```diff
@@ -47,27 +47,36 @@ public class EntityGraphAttacher : IEntityGraphAttacher
             EntityState targetState,
             EntityState storeGeneratedWithKeySetTargetState,
             bool forceStateWhenUnknownKey)
-            => _graphIterator.TraverseGraph(
+        {
+            rootEntry.StateManager.ResetAttachGraph();
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs:51]: If there are any danglers at this point why would we discard them?

Also shouldn't we also call `CompleteAttachGraph` on `DetectChanges`?

Comment (ajcvickers) [reply src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs]: @AndriySvyryd I thought some more about where danglers can come from and added additional test cases. This lead to a change where I made it more explicit that this is a Begin/End behavior.

**Review by AndriySvyryd — APPROVED** [review]
