### PR TITLE
Clean up and document local DetectChanges behavior, plus other API doc fixes

### LINKED ISSUE #18938: UseMemoryCache API
From @1009058470
some of .net core api's description is not clear. for example ,DbContextOptionsBuilder.UseMemoryCache(IMemoryCache) Method just show it parameters ,but i don not know how to make it parameters.
the url is https://docs.microsoft.com/zh-cn/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder-1.usememorycache?view=efcore-3.0#Microsoft_EntityFrameworkCore_DbContextOptionsBuilder_1_UseMemoryCache_Microsoft_Extensions_Caching_Memory_IMemoryCache_

Filed originally at https://github.com/MicrosoftDocs/feedback/issues/2156

### LINKED ISSUE #24972: Misleading comment, since it doesn't accept null or lambda without property.
https://github.com/dotnet/efcore/blob/6449203147298f03b34d227de1a5b48f62060bf1/src/EFCore/Metadata/Builders/CollectionNavigationBuilder%60.cs#L117

### LINKED ISSUE #26552: Add links to conceptual docs for OptionsBuilder methods
Missed them the first time through.

### LINKED ISSUE #29125: Typo on the page
image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7020a67-e052-2da1-2939-fd785681517b
* Version Independent ID: 3b1723ad-71ff-f4bc-1231-638cbed76511
* Content: [DbContextOptionsBuilder.EnableServiceProviderCaching(Boolean) Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder.enableserviceprovidercaching?view=efcore-6.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContextOptionsBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContextOptionsBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

### LINKED ISSUE #29261: Confusing doc-comments on DeleteBehavior enum
## File a bug

Although the meaning of these enum members is well explained at https://learn.microsoft.com/en-us/ef/core/saving/cascade-delete, I initially read the doc-comments on the enum. While reading just those, they didn't help me much in understanding the nuances and the differences between them. The descriptions are [almost identical for several members](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.deletebehavior?view=efcore-6.0), for example `SetNull` vs `ClientSetNull`. Another case is `Restrict` vs `NoAction`, which have an identical description. Perhaps it would be helpful to link to the explaining article from this enum or clarify the descriptions to identify in which way they are different.

Feel free to close if you believe they are good as they are, just wanted to bring this to the team's attention.

### Include provider and version information

EF Core version: 6.x

### LINKED ISSUE #29747: Add a flag for DetectChanges for local methods that may do a full scan

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #29747
Fixes #29261
Fixes #29125
Fixes #26552
Fixes #24972
Fixes #18938

### CODE REVIEW

File: src/EFCore.Abstractions/DeleteBehavior.cs [hunk 1]
```diff
@@ -25,116 +23,119 @@ namespace Microsoft.EntityFrameworkCore;
 public enum DeleteBehavior
 {
     /// <summary>
-    ///     For entities being tracked by the context, the values of foreign key properties in
-    ///     dependent entities are set to null when the related principal is deleted.
-    ///     This helps keep the graph of entities in a consistent state while they are being tracked, such that a
-    ///     fully consistent graph can then be written to the database. If a property cannot be set to null because
-    ///     it is not a nullable type, then an exception will be thrown when
-    ///     <c>SaveChanges()</c> is called.
+    ///     Sets foreign key values to null as appropriate when changes are made to tracked entities, and creates a normal, non-cascading
```
Comment (AndriySvyryd) [inline src/EFCore.Abstractions/DeleteBehavior.cs:26]:
```suggestion
    ///     Sets foreign key values to null as appropriate when changes are made to tracked entities, and creates a non-cascading
```

File: src/EFCore.Abstractions/DeleteBehavior.cs [hunk 2]
```diff
@@ -25,116 +23,119 @@ namespace Microsoft.EntityFrameworkCore;
...
     ClientSetNull,
 
     /// <summary>
-    ///     For entities being tracked by the context, the values of foreign key properties in dependent entities
-    ///     are set to null when the related principal is deleted.
-    ///     This helps keep the graph of entities in a consistent state while they are being tracked, such that a
-    ///     fully consistent graph can then be written to the database. If a property cannot be set to null because
-    ///     it is not a nullable type, then an exception will be thrown when
-    ///     <c>SaveChanges()</c> is called.
+    ///     Sets foreign key values to null as appropriate when changes are made to tracked entities, and creates a normal, non-cascading
```
Comment (AndriySvyryd) [inline src/EFCore.Abstractions/DeleteBehavior.cs:44]:
```suggestion
    ///     Sets foreign key values to <see langword="null" /> as appropriate when changes are made to tracked entities, and creates a normal, non-cascading
```
And elsewhere

File: src/EFCore/ChangeTracking/ChangeTracker.cs [hunk 3]
```diff
@@ -59,12 +59,17 @@ public class ChangeTracker : IResettableService
...
     /// </summary>
     /// <remarks>
-    ///     The default value is true. This ensures the context is aware of any changes to tracked entity instances
-    ///     before performing operations such as <see cref="DbContext.SaveChanges()" /> or returning change tracking
-    ///     information. If you disable automatic detect changes then you must ensure that
-    ///     <see cref="DetectChanges()" /> is called when entity instances have been modified.
-    ///     Failure to do so may result in some changes not being persisted during
-    ///     <see cref="DbContext.SaveChanges()" /> or out-of-date change tracking information being returned.
+    ///     <para>
+    ///         The default value is true. This ensures the context is aware of any changes to tracked entity instances
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/ChangeTracker.cs:63]:
```suggestion
    ///         The default value is <see langword="true" />. This ensures the context is aware of any changes to tracked entity instances
```

File: src/EFCore/ChangeTracking/ChangeTracker.cs [hunk 4]
```diff
@@ -140,14 +155,22 @@ public virtual CascadeTiming CascadeDeleteTiming
     /// </summary>
     /// <remarks>
     ///     <para>
+    ///         Consider using the methods of <see cref="DbSet{TEntity}.Local" /> for faster lookup of tracked entities by key, foreign key,
+    ///         or property value.
+    ///     </para>
+    ///     <para>
     ///         This method calls <see cref="DetectChanges" /> to ensure all entries returned reflect up-to-date state.
-    ///         Use <see cref="AutoDetectChangesEnabled" /> to prevent DetectChanges from being called automatically.
+    ///         Since detecting changes cane be slow, consider using <see cref="AutoDetectChangesEnabled" /> to prevent detecting changes
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/ChangeTracker.cs:163]:
```suggestion
    ///         Since detecting changes can be slow, consider temporarily setting <see cref="AutoDetectChangesEnabled" /> to <see langword="false" /> to prevent detecting changes
```

**Review by AndriySvyryd — APPROVED** [review]
