### PR TITLE
Don't discover navigations to Dictionary<> and non-owned STETs

### LINKED ISSUE #26731: EFCore 6 InMemory throw exception on ignored type lookup
Hi,
It seems like there is a regression on EFCore 6
https://github.com/erwan-joly/EF6Bug

exact same code throw an exception when doing 
``` var entityBuilder = modelBuilder.Entity(entity.ClrType);```
https://github.com/erwan-joly/EF6Bug/blob/master/InMemoryEf6/TestDbContext.cs#L34

System.InvalidOperationException: The entity type 'Dictionary<string, string>' requires a primary key to be defined.If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'.For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.

This is happening with InMemory provider and an entity created for Npgsql provider
```
[Column(TypeName = "jsonb")]
public Dictionary<string, string>? Values { get; set; } = new();
```

this type is not known by InMemory this is why we Ignore it in our InMemoryDbContext but since the upgrade to EF Core 6 it just throw an error even if we ask it to be ignored

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #26731

### CODE REVIEW

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs [hunk 1]
```diff
@@ -83,7 +83,15 @@ public RelationshipDiscoveryConvention(ProviderConventionSetBuilderDependencies
                 var navigationPropertyInfo = candidateTuple.Key;
                 var (targetClrType, shouldBeOwned) = candidateTuple.Value;
 
-                if (!IsCandidateNavigationProperty(entityTypeBuilder, navigationPropertyInfo.GetSimpleMemberName(), navigationPropertyInfo))
+                if (entityType.FindNavigation(navigationPropertyInfo) == null
+                    && entityType.FindSkipNavigation(navigationPropertyInfo) == null
+                    && !(IsCandidateNavigationProperty(entityType, targetClrType, navigationPropertyInfo.GetSimpleMemberName(), navigationPropertyInfo)
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:88]: Does pushing ! inside makes it more readable?

**Review by smitpatel — APPROVED** [review]
:shipit:

File: src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs:88]: Probably best to extract another method
