### PR TITLE
Handle shadow navigations when loading with split queries

### LINKED ISSUE #32225: Loading a Many-to-Many Collection as SplitQuery throws NullReferenceException
### Descritpion
When calling dbContext.Entry(obj).Collection(o => o.Collection).Load() a NullReferenceException is thrown when:
* The collection to be loaded is part of a many-to-many collection
* SplitQueries are used (for example when globally configured for the whole application)
* The many-to-many collection is not fully defined (the other side of the relationship has no collection backreference defined, only automatically created as shadow property)

The error was reproduced using a postreSQL as well as a sqlite database, so it is not provider specific.
I tried debugging the issue and realized that some Func parameter is null somewhere in the GetCollection() method of Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor

For a test project please refer to: https://github.com/theissto/EF_SplitQuery_LoadError

### Models for failing test case
```C#
public class ManyItemOneWithoutBackreference
{
    [Key]
    public int Id { get; set; }

    public List<ManyItemTwoWithoutBackreference> Items { get; set; } = new();
}
```

```C#
public class ManyItemTwoWithoutBackreference
{
    [Key]
    public int Id { get; set; }
}
```

### DbContext for failing test case

```C#
public class PostgreSqlDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql(
            @"User ID=SplitQueryTestUser;Server=localhost;Port=5432;Database=EF_SplitQuery_LoadError_Tests;Pooling=true;Include Error Detail=true;Command Timeout=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ManyItemOneWithoutBackreference>()
            .HasMany(mio => mio.Items)
            .WithMany();

        // modelBuilder.Entity<ManyItemOneWithBackreference>()
        //     .HasMany(mio => mio.Items)
        //     .WithMany(mit => mit.Items);
    }
}
```

### Failing test case
```C#

    [Test]
    public async Task _01_PostgreSQL_ExplicitLoad_OnManyToManyCollection_WithoutBackreference_ThrowsNoError()
    {
        var manyItemOne = new ManyItemOneWithoutBackreference()
        {
            Items = new()
            {
                new ()
            }
        };
        
        await using (var postgresDbContext = new PostgreSqlDbContext())
        {
            postgresDbContext.Add(manyItemOne);
            await postgresDbContext.SaveChangesAsync();
        }

        await using (var postgresDbContext = new PostgreSqlDbContext())
        {
            var manyItemOneFromDb = await postgresDbContext.Set<ManyItemOneWithoutBackreference>().SingleAsync(i => i.Id == manyItemOne.Id);
            var collectionQuery = postgresDbContext.Entry(manyItemOneFromDb)
                .Collection(i => i.Items)
                .Query();

            var normalQueryResult = await collectionQuery.ToListAsync();
            
            Assert.That(normalQueryResult, Has.Count.EqualTo(1));
            // Why does this throw a NullReferenceException?
            // This also happens when query behavior is configured globally and context.Entry().Collection().Load() is called.
            Assert.DoesNotThrowAsync(async () => await collectionQuery.AsSplitQuery().ToListAsync());

            var splitQueryResult = await collectionQuery.AsSplitQuery().ToListAsync();
            Assert.That(splitQueryResult, Has.Count.EqualTo(1));
        }
    }
```

### StackTrace of failing test

```
Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.GetCollection(Object instance)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.GetOrCreateCollection(Object instance, Boolean forMaterialization)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.GetOrCreate(Object entity, Boolean forMaterialization)
   at lambda_method124(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EF_SplitQuery_LoadError_Tests.PostgreSqlTests.<>c__DisplayClass1_1
```

### Models for passing test case

When the backreference is present in both sides of the relationship, no error is thrown (for proof, see test project).

```C#
public class ManyItemOneWithBackreference
{
    [Key]
    public int Id { get; set; }

    public List<ManyItemTwoWithBackreference> Items { get; set; } = new();
}
```

```C#
public class ManyItemTwoWithBackreference
{
    [Key]
    public int Id { get; set; }
    
    public List<ManyItemOneWithBackreference> Items { get; set; } = new();
}
```

### Include provider and version information

EF Core version: 7.0.13
Database provider: Microsoft.EntityFrameworkCore.Sqlite, Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET 7.0
Operating system: macOS 14.1 (23B74)
IDE: JetBrains Rider 2023.1.4

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #32225

### CODE REVIEW

File: src/EFCore/Metadata/Internal/ClrCollectionAccessor.cs [hunk 1]
```diff
@@ -137,6 +140,11 @@ private ICollection<TElement> GetOrCreateCollection(object instance, bool forMat
 
     private ICollection<TElement>? GetCollection(object instance)
     {
+        if (_shadow)
+        {
+            return (ICollection<TElement>?)_createCollection?.Invoke();
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/ClrCollectionAccessor.cs:145]: Add a comment explaining why this never returns an existing collection.

**Review by AndriySvyryd — APPROVED** [review]
