### PR TITLE
Query: Add multiple parameters if inferred type mapping differs

### LINKED ISSUE #19503: Query: Deal with same querycontext parameter having multiple inferred type mapping
```C#
var city = "Settle";
cs.Where(c => c.City == city || c.Address.Contains(city)).ToList();
```
In above query we have only 1 query context parameter for city but in SQL, city could take different inferred type mapping. We need to determine what should we do with such cases especially if one mapping is unicode and other is not.
It also intersect with the fact that currently we have 1 to 1 mapping between query context parameters and relational parameters which we can relax and use for https://github.com/aspnet/EntityFrameworkCore/issues/17948

### LINKED ISSUE #22524: Incorrect query generated when using Skip and Enum Where condition when Skip value is same as enum value
Sorry if this problem has been posted before, I couldn't find any issues with similar problem.

Ef core generates invalid SQL when the Skip value is the same as Enum value in a Where condition, when Skip statement is before the Where clause.

I added an example query that generates the expected result (at least considering how it handles the Enum value), but in my current project it is not possible to use that variant (at least not very easily). 
I don't think that it should matter in what order the Skip statement is applied, it shouldn't use the same parameter for the `offset` and `where` predicate. 
Note also that if the Skip value of the original query would be changed to anything else than 0 (the enum value) it would also generate good SQL.

In my current project the issue manifests in the final select projection. Pagination/filters are applied on the inner query and the final query uses a sub query that selects a child entity by applying a similar Enum filter. In Postgresql (database used in the project), because of type mismatch the following error is thrown: `42883: operator does not exist: text = integer` (It tries to compare enum that is stored as `text` with the integer offset parameter).

### Steps to reproduce
Query that generates incorrect SQL
``` C#
 await context.Foos.Skip(0).Where(x => x.Type == FooEnum.A).ToListAsync();
```
Sql generated (notice `@__p_0` parameter usage)
``` SQL
SELECT [t].[Id], [t].[Type]
   FROM (
     SELECT [f].[Id], [f].[Type]
     FROM [Foos] AS [f]
     ORDER BY (SELECT 1)
     OFFSET @__p_0 ROWS
 ) AS [t]
 WHERE [t].[Type] = @__p_0
```

Query that doesn't have the problem (returns expected result). Note Skip was moved after the Where condition
``` C#
 await context.Foos.Where(x => x.Type == FooEnum.A).Skip(0).ToListAsync();
```
Sql generated: 
``` SQL
SELECT [f].[Id], [f].[Type]
FROM [Foos] AS [f]
WHERE [f].[Type] = N'A'
ORDER BY (SELECT 1)
OFFSET 0 ROWS
```
I would expect even the first example to generate the same Where condition: `WHERE [f].[Type] = N'A'`.
Especially because changing the Enum (or Skip) value also generates the expected SQL:
``` C#
 await context.Foos.Skip(0).Where(x => x.Type == FooEnum.B).ToListAsync();
```
Sql generated
``` SQL
SELECT [t].[Id], [t].[Type]
  FROM (
      SELECT [f].[Id], [f].[Type]
      FROM [Foos] AS [f]
      ORDER BY (SELECT 1)
      OFFSET @__p_0 ROWS
  ) AS [t]
  WHERE [t].[Type] = N'B'
```
Or original query with Skip(1):
``` C#
 await context.Foos.Skip(1).Where(x => x.Type == FooEnum.A).ToListAsync();
```
Sql generated
``` SQL
SELECT [t].[Id], [t].[Type]
  FROM (
      SELECT [f].[Id], [f].[Type]
      FROM [Foos] AS [f]
      ORDER BY (SELECT 1)
      OFFSET @__p_0 ROWS
  ) AS [t]
  WHERE [t].[Type] = N'A'
```

Full code example project (has more variations and working examples), uses Sql server local db:
[EfCoreSkipEnumBug.zip](https://github.com/dotnet/efcore/files/5217876/EfCoreSkipEnumBug.zip)

### Further technical details

EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer & Npgsql.EntityFrameworkCore.PostgreSQL (maybe also others)
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.2

Thank you.

### LINKED ISSUE #26472: EF generates invalid SQL when using enums in projections
My team and I stumbled upon a strange behavior while optimizing our internal paging library which is currently blocking us, since we did not find any workaround.

Everytime we project data using a `.Select(...)` and that select contains an enum and its int value matches the value passed in a `.Skip()` or `.Take()` efcore generates invalid sql because it tries to insert the enum ***string*** value into the `SELECT TOP(...)`, `OFFSET ...` or `FETCH NEXT ... ROWS` expression.

image

I created a repo which reproduces this behavior: https://github.com/mariotebest/efcore_enum_bug

I'm probably missing something very obvious here because I can't imagine an issue like that would stay undetected for several ef core versions (I tried several recent 3.1.x versions on nuget).

### Include provider and version information

EF Core version: 3.1.20
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .net core 3.1
IDE: Visual Studio 2022 17.0

```
PS C:\> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  3.1.414 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

### PR DESCRIPTION
**Pull request by smitpatel**
When adding parameters from query, we check if the type mapping inside TypeMapped parameter is same, if it is not then we add another parameter with different name in SQL.

Clean up in relational parameter builder code
- Remove Dynamic parameter/ property parameter
- Obsolete TypeMappingSource from CommandBuilder
- Remove obsolete code and combine methods which were doing same work

Resolves #19503
Resolves #22524
Resolves #26472

### CODE REVIEW

File: src/EFCore.Relational/Query/QuerySqlGenerator.cs [hunk 1]
```diff
@@ -537,22 +538,47 @@ protected override Expression VisitSqlConstant(SqlConstantExpression sqlConstant
...
-            var parameterNameInCommand = _sqlGenerationHelper.GenerateParameterName(sqlParameterExpression.Name);
+            var invariantName = sqlParameterExpression.Name;
+            var parameterName = sqlParameterExpression.Name;
 
             if (_relationalCommandBuilder.Parameters
-                .All(p => p.InvariantName != sqlParameterExpression.Name))
+                .All(p => p.InvariantName != parameterName
+                        || (p is TypeMappedRelationalParameter typeMappedRelationalParameter
+                            && (typeMappedRelationalParameter.RelationalTypeMapping.StoreType != sqlParameterExpression.TypeMapping!.StoreType
+                                || typeMappedRelationalParameter.RelationalTypeMapping.Converter != sqlParameterExpression.TypeMapping!.Converter))))
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/QuerySqlGenerator.cs:548]: Filed #26581

File: src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs [hunk 2]
```diff
@@ -98,6 +98,7 @@ public static IDisposable Indent(this IRelationalCommandBuilder commandBuilder)
         ///     The name to be used for the parameter when the command is executed against the database.
         /// </param>
         /// <returns>The same builder instance so that multiple calls can be chained.</returns>
+        [Obsolete("Use overload which takes TypeMapping argument.")]
```
Comment (smitpatel) [inline src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs:101]: I would pretty much like to remove DynamicRelationalParameter code path. That code path is fully pub-ternal and this is the only public entry point. Further, this method should only be called from provider code rather than user code. Do we _really_ need to obsolete it rather than make a break? (Food for thought, whatever we obsolete now won't go away till we release EF 8.0.)

cc: @dotnet/efteam

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs [hunk 3]
```diff
@@ -4232,10 +4232,11 @@ public override async Task Comparing_to_fixed_string_parameter(bool async)
 
             AssertSql(
                 @"@__prefix_0='A' (Size = 4000)
+@__prefix_0_1='A' (Size = 5)
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:4235]: Current naming scheme will append _1, _2... as more occurrences come.
Added `_` to avoid clash if `p11` is generated from repeating parameter and also exist in query context due to many client parameters.
Starting at 1 is bit arbitrary. `prefix_0_1` looked easier to identify different from 0 starting. Plus, 0 starting in client parameters is side-effect of using the size of parameterValues collection.

Happy to change naming if someone wants it other way.

File: src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs (hunk 2 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs:101]: I'm ok with removing. Also anything obsoleted now might end up removed accidently when we remove all obsoleted code in https://github.com/dotnet/efcore/issues/22549

**Comment by smitpatel** [comment]
Actually I am gonna look more into `IRelationalParameter`

**Review by AndriySvyryd — APPROVED** [review]
