### PR TITLE
Take into account Contains item visitation in SqlNullabilityProcessor

### LINKED ISSUE #32208: SqlNullabilityProcessor ignores Contains item visitation
I am running GIT test `QueryBugsTest.Nested_contains_with_enum`. The test is executing following LINQ-
```C#
var query = context.Todos
    .Where(x => keys.Contains(todoTypes.Contains(x.Type) ? key : key))
    .ToList();
```

The test was working fine with Oracle EFCore 7 provider. However it seems there is some regression issue introduced from the relational layer in EFCore 8 daily label, due to which the test is failing.

Here is my observation.
	
SqlServer EFCore 7 provider used to generate following query for it-
```
SELECT [t].[Id], [t].[Type]
FROM [Todos] AS [t]
WHERE CASE
    WHEN [t].[Type] = 0 THEN @__key_2
    ELSE @__key_2
END IN ('0a47bcb7-a1cb-4345-8944-c58f82d6aac7', '5f221fb9-66f4-442a-92c9-d97ed5989cc7')
```

However in EFCore 8 provider, the query has been changed to-
```
SELECT [t].[Id], [t].[Type]
FROM [Todos] AS [t]
WHERE CASE
    WHEN [t].[Type] = 0 THEN @__key_2
    ELSE @__key_2
END IN (
    SELECT [k].[value]
    FROM OPENJSON(@__keys_0) WITH ([value] uniqueidentifier '$') AS [k]
)
```

For the database providers which don't support OPENJSON or similar functionality, they may want to keep on generating the query which was getting generated with EFCore 7 provider.

For Ex:- Oracle EFCore 7 provider generates following query for the test-
```
SELECT "t"."Id", "t"."Type"
FROM "Todos" "t"
WHERE CASE
    WHEN "t"."Type" = 0 THEN :key_2
    ELSE :key_2
END IN ('B7BC470ACBA145438944C58F82D6AAC7', 'B91F225FF4662A4492C9D97ED5989CC7')
```

However in EFCore 8 the query has been changed to-
```
SELECT "t"."Id", "t"."Type"
FROM "Todos" "t"
WHERE CASE
WHEN "t"."Type" IN ( ) THEN :key_2
ELSE :key_2
END IN ('B7BC470ACBA145438944C58F82D6AAC7', 'B91F225FF4662A4492C9D97ED5989CC7')
```

While debugging the relational layer code (Method `SqlNullabilityProcessor.VisitIn`) . It seems EFCore 7 used to convert certain `InExpression `to `SqlBinaryExpression`.
For Ex:- There will be two `InExpression `for the above LINQ but the inner one will be converted to `SqlBinaryExpression `and the provider will generate `[t].[Type] = 0` corresponding to the `SqlBinaryExpression`.
However in EFCore 8 provider, the converted `SqlBinaryExpression `isn't used to generate the SQL **if `InExpression.SubQuery` is null**.

Is this expected? If yes, then `InExpression.Value` field shouldn't be null (which is the case as of now). The `InExpression` which is used to generate SQL `"t"."Type" IN ( )` has null value.

This seems to be an issue from the relational layer. Please could someone clarify.

### PR DESCRIPTION
**Pull request by roji**
When visiting non-subquery InExpression in SqlNullabilityProcessor, we were ignoring the results of visiting the item.

Fixes #32208

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs [hunk 1]
```diff
@@ -1227,6 +1227,26 @@ public override async Task Project_primitive_collections_element(bool async)
...
+        await base.Nested_contains_with_Lists_and_no_inferred_type_mapping(async);
+
+        AssertSql(
+            """
+@__strings_0='["one","two","three"]' (Size = 4000)
+
+SELECT [p].[Id], [p].[Bool], [p].[Bools], [p].[DateTime], [p].[DateTimes], [p].[Enum], [p].[Enums], [p].[Int], [p].[Ints], [p].[NullableInt], [p].[NullableInts], [p].[NullableString], [p].[NullableStrings], [p].[String], [p].[Strings]
+FROM [PrimitiveCollectionsEntity] AS [p]
+WHERE CASE
+    WHEN [p].[Int] IN (1, 2, 3) THEN N'one'
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs:1241]: We should be getting OPENJSON here; this means that the array parameter is somehow not treated as a primitive query root. Opened #32215 to track.

**Review by maumar — APPROVED** [review]
