### PR TITLE
Produce uncorrelated IN for Contains with nullable item

### LINKED ISSUE #32574: Contains translates to correlated query when the item is nullable
We usually translate Contains to an uncorrelated IN subquery, e.g. `WHERE x.Item IN (SELECT value FROM OPENJSON(@p))`. However, when the item is nullable, we translate to a correlated EXISTS subquery instead: `WHERE EXISTS (SELECT value FROM OPENJSON(..) WHERE value = x.Item`.

The problem is that during translation of primitive collections, we cannot examine parameter contents, and so we must assume that there are possible nulls in the collection (unless we're dealing with a non-nullable value). Later, in SqlNullabilityProcessor, when processing the InExpression we see that both sides (item and subquery) are nullable, meaning that we can't use SQL IN for that (impossible to distinguish between a NULL result that indicates that the item wasn't found, and a NULL result that indicates that NULL was found). As a result, we currently transform the IN to an EXISTS, to make sure results are accurate.

The fix here would be to look into the parameterized collection in SqlNullabilityProcessor (where we can access parameters), and rewrite it to remove any null values, compensating with an additional OR clause. Once nulls are cleared out, we can keep the uncorrelated IN translation, rather than switching to correlated EXISTS. Note that this would be the first time we rewrite parameters in the 2nd part of the query pipeline; it also means we can't cache the resulting SQL, since the parameter rewriting must happen again for each query.

(/cc @ajcvickers regarding value converters and null: since the query pipeline cares about nulls vs. non-nulls, if value converters support converting between nulls and non-nulls, that has to happen early, otherwise we'll get incorrect results)

Note that any other type of IN+subquery will continue to be translated as before, i.e. transforming IN to correlated EXISTS when both sides are nullable. This isn't a regression from previous releases.

### PR DESCRIPTION
**Pull request by roji**
See #32574 for a description of what this does. After this, Contains over a parameter should never generate correlated EXISTS, only uncorrelated IN.

Fixes #32574

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlNullabilityProcessor.cs [hunk 1]
```diff
@@ -1953,6 +1993,133 @@ static bool TryNegate(ExpressionType expressionType, out ExpressionType result)
...
+                return true;
+            }
+
+            foundNull = true;
+
+            // TODO: We currently only have read-only access to the parameter values in the nullability processor (and in all of the
+            // 2nd-level query pipeline); to need to flow the mutable dictionary in. Note that any modification of parameter values (as
+            // here) must immediately entail DoNotCache().
+            Check.DebugAssert(ParameterValues is Dictionary<string, object?>, "ParameterValues isn't a Dictionary");
+            if (ParameterValues is not Dictionary<string, object?> mutableParameterValues)
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlNullabilityProcessor.cs:2067]: This is something I intend to clean up in a later PR, i.e. expose the mutable parameter dictionary to SqlNullabilityProcessor.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 2]
```diff
@@ -113,4 +115,36 @@ SqlServerAggregateFunctionExpression aggregateFunctionExpression
...
         => true;
+
+#pragma warning disable EF1001
+    /// <summary>
+    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+    ///     any release. You should only use it directly in your code with extreme caution and knowing that
+    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+    /// </summary>
+    protected override bool IsCollectionTable(TableExpressionBase table, [NotNullWhen(true)] out Expression? collection)
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs:126]: It's not great that providers have to override these two hooks to deal with the provider-specific primitive collection expressions; #32576 tracks doing something better here (that's why these APIs are pubternal for now).

**Review by maumar — APPROVED** [review]
