### PR TITLE
Only create additional concurrency token properties when needed

### LINKED ISSUE #21316: IsConcurrencyToken() with TPH generating incorrect migration statements?
When properties of concrete classes in a hierarchy are set as a concurrency token with `IsConcurrencyToken()`, the migrations alter the column to be not nullable. This should be relaxed so that we can have TPH with nullable columns while also using `IsConcurrencyToken()`

Models:
```c#
 public abstract class BaseClass
    {
        public string Id { get; private set; }
    }

    public class ConcreteA : BaseClass
    {
        public ConcreteATypes ATypes { get; private set; }
    }

    public enum ConcreteATypes
    {
        A1, A2, A3,

    }

    public enum ConcreteBTypes
    {
        B1, B2

    }


    public class ConcreteB : BaseClass
    {
        public ConcreteBTypes BTypes { get; private set; }
    }
```
ApplicationDbContext.cs
```c#
  static ApplicationDbContext()
        {
            NpgsqlConnection.GlobalTypeMapper.MapEnum<ConcreteATypes>();
            NpgsqlConnection.GlobalTypeMapper.MapEnum<ConcreteBTypes>();

        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.HasPostgresEnum<ConcreteATypes>();
            builder.HasPostgresEnum<ConcreteBTypes>();
            builder.Entity<ConcreteA>().HasBaseType<BaseClass>();
            builder.Entity<ConcreteB>().HasBaseType<BaseClass>();
            builder.Entity<ConcreteB>().Property(p => p.BTypes).IsConcurrencyToken();
            builder.Entity<ConcreteA>().Property(p => p.ATypes).IsConcurrencyToken();
            base.OnModelCreating(builder);
}
```

Generates:

```c#
public partial class base1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:Enum:concrete_a_types", "a1,a2,a3")
                .Annotation("Npgsql:Enum:concrete_b_types", "b1,b2");

            migrationBuilder.CreateTable(
                name: "BaseClass",
                columns: table => new
                {
                    Id = table.Column<string>(type: "text", nullable: false),
                    Discriminator = table.Column<string>(type: "text", nullable: false),
                    ATypes = table.Column<ConcreteATypes>(type: "concrete_a_types", nullable: false), //should be nullable for TPH
                    BTypes = table.Column<ConcreteBTypes>(type: "concrete_b_types", nullable: false) //should be nullable for TPH
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BaseClass", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "BaseClass");

            migrationBuilder.AlterDatabase()
                .OldAnnotation("Npgsql:Enum:concrete_a_types", "a1,a2,a3")
                .OldAnnotation("Npgsql:Enum:concrete_b_types", "b1,b2");
        }
    }
```
### Further technical details

EF Core version: 5.0.0-preview.7.20317.4
Database provider: npgsql 5.0.0-preview6-ci.20200617T130728
Target framework: .NET 5 nightly (preview 7)
Operating system: Win 10
IDE: VS 2019 16 preview 2

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Expose CreateUniqueProperty on IConventionEntityTypeBuilder

Fixes #21316

### CODE REVIEW

File: src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs [hunk 1]
```diff
@@ -43,47 +43,55 @@ public class TableSharingConcurrencyTokenConvention : IModelFinalizingConvention
...
-                                foundMappedProperty = true;
-                                break;
-                            }
-                        }
-
-                        foundMappedProperty = foundMappedProperty
-                            || entityType.GetAllBaseTypes().SelectMany(t => t.GetDeclaredProperties())
-                                .Any(p => p.GetColumnName(StoreObjectIdentifier.Table(table.Table, table.Schema)) == concurrencyColumnName);
+                        var foundMappedProperty = !IsConcurrencyTokenMissing(propertiesMappedToConcurrencyColumn, entityType, mappedTypes)
+                            || entityType.GetDeclaredProperties()
```
Comment (smitpatel) [inline src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs:85]: Is this different from entityType.GetProperties()?

Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs:85]: No
