### PR TITLE
Set the DbType on parameters wherever possible

### LINKED ISSUE #25713: [Always Encrypted] EF Core 5.0 Operand type clash : nvarchar(4000) is incompatible with decimal(19,3)
## nvarchar(4000) is incompatible with decimal(19,3) when Always Encrypted is enabled on a decimal column

If values are supplied for Dec1, Dec2, and Dec3 then the add to database call works just fine. However, when one of these columns are equal to NULL the following error is thrown.

```
SqlException: Operand type clash: nvarchar is incompatible with decimal(19,3) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'CEK_Auto1', column_encryption_key_database_name = 'Answers')
```

### Answer.cs

```C#
namespace SharedLibrary.Answer
{
    [Table("Answer", Schema = "anw")]
    public class Answer
    {
        [Key]
        public int ID {get;set;}

        [Column(TypeName = "decimal(19,3)")]
        public decimal? Dec1 { get; set; }

        [Column(TypeName = "decimal(19,3)")]
        public decimal? Dec2 { get; set; }

        [Column(TypeName = "decimal(19,3)")]
        public decimal? Dec3 { get; set; }
    }
}
```

### DBContext.cs
```C#
        ...
        protected string connectionString { get; set; }

        connectionString = "server = StorageServer; Database=Answers; uid=SomeName; password=SomePassword; encrypt=true; trustServerCertificate=true; Column Encryption Setting = enabled;"

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
            //.UseLazyLoadingProxies()
            .UseSqlServer(connectionString);
        }

        public virtual DbSet<Answer> Answers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Answer>().HasIndex(c => c.ID).IsUnique(true);
            modelBuilder.Entity<Answer>(entity =>
            {
                entity.Property(e => e.ID).ValueGeneratedOnAdd();
                entity.Property(e => e.Dec1).HasPrecision(19,3);
                entity.Property(e => e.Dec2).HasPrecision(19,3);
                entity.Property(e => e.Dec3).HasPrecision(19,3);
            }
         }
         ,,,
```

### Framework Specs

```C#

    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="5.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.9" />
```

### Error Producing Code
```C#
            DbContext smdbc = new DbContext();
            
            Answer ans = new Answer();  /// <<< Three NULL Decimal Values Here

            smdbc.Answers.Add(ans);

            smdbc.SaveChanges(); // <<<<<Error Happens Here 
```

### PR DESCRIPTION
**Pull request by ajcvickers**
For Always Encrypted

Fixes #25713

### CODE REVIEW

File: src/EFCore.Relational/Storage/CharTypeMapping.cs [hunk 1]
```diff
@@ -25,7 +25,7 @@ public class CharTypeMapping : RelationalTypeMapping
         /// <param name="dbType"> The <see cref="DbType" /> to be used. </param>
         public CharTypeMapping(
             string storeType,
-            DbType? dbType = null)
+            DbType? dbType = null) // No DbType for char
```
Comment (roji) [inline src/EFCore.Relational/Storage/CharTypeMapping.cs:28]: In SqlClient (and Npgsql), the DbType for .NET char seems to be DbType.String, in the sense that a single char maps to `CHAR(1)`.

File: src/EFCore.Relational/Storage/StringTypeMapping.cs [hunk 2]
```diff
@@ -26,7 +26,7 @@ public class StringTypeMapping : RelationalTypeMapping
         /// <param name="size"> The size of data the property is configured to store, or null if no size is configured. </param>
         public StringTypeMapping(
             string storeType,
-            DbType? dbType = null,
+            DbType? dbType,
```
Comment (roji) [inline src/EFCore.Relational/Storage/StringTypeMapping.cs:29]: Shouldn't this be DbType.String for the database-agnostic type mapping?

File: src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateTimeTypeMapping.cs [hunk 3]
```diff
@@ -24,7 +24,7 @@ public class SqliteDateTimeTypeMapping : DateTimeTypeMapping
         /// </summary>
         public SqliteDateTimeTypeMapping(
             string storeType,
-            DbType? dbType = null)
+            DbType? dbType = System.Data.DbType.DateTime2)
```
Comment (roji) [inline src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateTimeTypeMapping.cs:27]: Seems odd, DateTime2 really is a SQL Server concept even if it leaked into DbType... Consider making this DateTime (also in DateTimeTypeMapping).

(even if FWIW I don't think think Microsoft.Data.SqlClient looks at DbType (only at the CLR type), so this doesn't matter much)

**Review by roji — APPROVED** [review]

File: src/EFCore.Relational/Storage/DateTimeTypeMapping.cs [hunk 4]
```diff
@@ -26,7 +26,7 @@ public class DateTimeTypeMapping : RelationalTypeMapping
         /// <param name="dbType"> The <see cref="DbType" /> to be used. </param>
         public DateTimeTypeMapping(
             string storeType,
-            DbType? dbType = null)
+            DbType? dbType = System.Data.DbType.DateTime2)
```
Comment (roji) [inline src/EFCore.Relational/Storage/DateTimeTypeMapping.cs:29]: Yeah, I think this really should be DateTime

File: src/EFCore.Relational/Storage/StringTypeMapping.cs (hunk 2 above)
Comment (ajcvickers) [reply src/EFCore.Relational/Storage/StringTypeMapping.cs:29]: I don't think so, because C# strings could map to any of the four string DbTypes. I think it better to have providers explicitly specify what they want.

File: src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateTimeTypeMapping.cs (hunk 3 above)
Comment (ajcvickers) [reply src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateTimeTypeMapping.cs:27]: Made the default DateTime, with SQL Server overriding to DateTime2.

Comment (roji) [reply src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateTimeTypeMapping.cs:27]: Makes sense.
