### PR TITLE
Mechanism for accessing parameters and disabling SQL caching

### LINKED ISSUE #36266: Introduce safer mechanism for accessing parameters and disabling SQL caching
Our SQL cache (currently) only caches by the nullability of the parameters; that means that if anything looks at something **other** than the nullability of a parameter, we must disable SQL caching to prevent cached SQL from leaking incorrectly across queries. Currently, we have to remember to call DoNotCache() in e.g. SqlNullabilityProcessor - this is error-prone, and if we forget this it can have subtle, hard-to-detect effects.

Instead of exposing the parameters directly, we should expose a façade wrapping the parameter dictionary which:
1. Allows checking if a given parameter is null (no problem there)
2. Allows getting the full dictionary, but disables caching automatically as part of that.

This would ensure that anyone getting the parameters implicitly causes caching to be disabling, removing the possibility for this category of bugs.
 
In addition, do general clean up around the parameters dictionary, removing IParameterValues etc.. Components of the query pipeline up to the SQL cache which have access to parameters (e.g. funcletizer) should just be able to access the `Dictionary<string, object?>` directly - no need for a special API to get in the way.

This work on parameter handling in the query pipeline also goes well with #35089 which is also in 10.

### PR DESCRIPTION
**Pull request by roji**
Closes #36266

### CODE REVIEW

File: src/EFCore.Relational/Query/CacheSafeParameterFacade.cs [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    ///     Returns whether the parameter with the given name is null.
+    /// </summary>
+    /// <remarks>
+    ///     The method assumes that the parameter with the given name exists in the dictionary,
+    ///     and otherwise throws <see cref="UnreachableException" />.
+    /// </remarks>
+    public bool IsParameterNull(string parameterName)
+        => !parameters.TryGetValue(parameterName, out var value)
+            ? throw new UnreachableException($"Parameter with name '{parameterName}' does not exist.")
+            : value is null;
```
Comment (cincuranet) [inline src/EFCore.Relational/Query/CacheSafeParameterFacade.cs]: I would flip the condition so the "else" clause is the exception. But no strong feelings about it.

**Review by cincuranet — APPROVED** [review]
LGTM, minus the compilation errors.

File: src/EFCore.Relational/Query/CacheSafeParameterFacade.cs (hunk 1 above)
Comment (roji) [reply src/EFCore.Relational/Query/CacheSafeParameterFacade.cs]: Good suggestion!
