### PR TITLE
[5.0.3] Fix to #23779 - TryRewriteEntityEquality and NotEqual comparison of CompositePrimaryKey

### LINKED ISSUE #23779: TryRewriteEntityEquality and NotEqual comparison of CompositePrimaryKey
I not sure, but seems this code has mistake:

https://github.com/dotnet/efcore/blob/03c1ba5275b11963ee1d05ad388ded2fda861c1b/src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs#L1397-L1409

In case of obj1.CompositePK != obj2.CompositePK need generate SQL with **OR**:

NOT(obj1.CompositePK.part1==obj2.CompositePK.part1) OR NOT(obj1.CompositePK.part2==obj2.CompositePK.part2)

Your code generates SQL with **AND**:

NOT(obj1.CompositePK.part1==obj2.CompositePK.part1) AND NOT(obj1.CompositePK.part2==obj2.CompositePK.part2)

?

### PR DESCRIPTION
**Pull request by maumar**
When comparing composite key entities we were comparing the constituent keys and combining them with AndAlso. For not equal comparison we were still comparing the keys using !=, but we didn't flip the combining operator to OrElse.

Fixes #23779

### CODE REVIEW

**Comment by maumar** [comment]
**Description**

When comparing composite key entities we were comparing the constituent keys and combining them with AndAlso. For not equal comparison we were still comparing the keys using !=, but we didn't flip the combining operator to OrElse.

**Customer Impact**

Data corruption. Queries which compare two entities which have composite key may result incorrect results.

**How found**

Customer reported on 5.0.1.

**Test coverage**

We have added test coverage in this PR.

**Regression?**

No, this scenario was not supported in previous versions.

Risk

Low. Fix only affects one codepath (per provider) which involves flipping binary operation from AndAlso to OrElse for one particular scenario - comparing two entities with composite keys. Also added quirk to revert to earlier behavior.

File: src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs [hunk 1]
```diff
@@ -1388,10 +1389,12 @@ private bool TryRewriteEntityEquality(ExpressionType nodeType, Expression left,
                             Expression.Convert(CreatePropertyAccessExpression(left, p), typeof(object)),
                             Expression.Convert(CreatePropertyAccessExpression(right, p), typeof(object)));
 
-                        return nodeType == ExpressionType.Equal
+                        return nodeType == ExpressionType.Equal
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs:1392]:
```suggestion
                        return nodeType == ExpressionType.Equal
```

**Review by smitpatel — APPROVED** [review]
