### PR TITLE
[release/8.0] Fix to #31961 - Projection filtering on second-level reference could not be translated

### LINKED ISSUE #31961: Projection filtering on second-level reference could not be translated
Hi,

I encounter an issue when I make a query where a filter (or sort) is apply on a property of a reference of reference (second level).

The filter is apply on a projection (the three levels are transformed into DTO).

The entities are the following : 
* A customer has a non-nullable reference to a company. 
* A company has a nullable reference to a country.

The query is the following :
```csharp
context.Customers
        .Select(m => new CustomerDto()
        {
            Id = m.Id,
            CompanyId = m.CompanyId,
            Company = m.Company != null ? new CompanyDto()
            {
                Id = m.Company.Id,
                CompanyName = m.Company.CompanyName,
                CountryId = m.Company.CountryId,
                Country = new CountryDto()
                {
                    Id = m.Company.Country.Id,
                    CountryName = m.Company.Country.CountryName,
                },
            } : null,
        })
        .Where(m => m.Company!.Country!.CountryName == "COUNTRY") // It fails
        .ToArray();
```

A few investigations : 
* A filter on a property of the first-level reference works. (e.g. `m => m.Company!.CompanyName == "COMPANY"`)
* When the first-level reference is non-nullable, it works.
* When I change the type of reference properties of DTO classes from interface to implementation, the filter works : `public CountryDto? Country { get; set; }` instead of `public ICountryDto? Country { get; set; }`
* The issue may be related to the following issue but it's closed : #20826

Reproduction : https://github.com/clemvnt/efcore-projection-nested-reference

### Stack trace

```
System.InvalidOperationException: The LINQ expression 'DbSet<Customer>()
    .LeftJoin(
        inner: DbSet<Company>(),
        outerKeySelector: c => EF.Property<string>(c, "CompanyId"),
        innerKeySelector: c0 => EF.Property<string>(c0, "Id"),
        resultSelector: (o, i) => new TransparentIdentifier<Customer, Company>(
            Outer = o,
            Inner = i
        ))
    .LeftJoin(
        inner: DbSet<Country>(),
        outerKeySelector: c => EF.Property<string>(c.Inner, "CountryId"),
        innerKeySelector: c1 => EF.Property<string>(c1, "Id"),
        resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<Customer, Company>, Country>(
            Outer = o,
            Inner = i
        ))
    .Where(c => ((ICountryDto)c.Outer.Inner != null ? new CountryDto{
        Id = c.Inner.Id,
        CountryName = c.Inner.CountryName
    }
     : null).CountryName == "COUNTRY")' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0&)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in C:\Users\cbernard\source\repos\EFCore.ProjectionOnNestedReference\Program.cs:line 10
```

### Include provider and version information

EF Core version: 7.0.11
Database provider: Tested with Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore.Sqlite
Target framework: NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.7.1

### PR DESCRIPTION
**Pull request by maumar**
Problem was that optimizing visitor was looking for a very specific pattern (member access over conditional), but in this scenario conditional is wrapped around Convert node. Fix is to recognize this case also, strip convert around the conditional and apply it around non-null portion instead, before applying the member access over it.

Fixes #31961

**Risk**

Low - change is isolated to a narrow optimization (member access over conditional) that also uses type conversion (either from derived to base type or from non-nullable to nullable), and is a simple change (strip convert around convert node and apply it on the non-null part of it before applying the member access.

### CODE REVIEW

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs [hunk 1]
```diff
@@ -399,10 +399,19 @@ private static Expression MatchExpressionType(Expression expression, Type typeTo
                     ? conditionalExpression.IfFalse
                     : conditionalExpression.IfTrue;
 
+                // if we removed convert around ConditionalExpression
+                // we need to re-apply it before we apply the MemberExpression
+                // using replacing visitor to preserve the original convert node
```
Comment (maumar) [inline src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:404]: should we bother? or just strap Convert node directly and skip the visitation here?

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs [hunk 2]
```diff
@@ -399,10 +399,19 @@ private static Expression MatchExpressionType(Expression expression, Type typeTo
...
+                if (convertedType != null)
```
Comment (maumar) [inline src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:405]: using convertedType as check will not add convert if the convert was to base type/interface (UnwrapTypeConversion returns null for convertedType in that case). That should be fine - if the member access over base class was an original expression, it will also be correct when it's member access on the derived. Or should we be super defensive here and always bring back the original convert node? (can do that by comparing `inner` and `conditionalExpression` - if they are different there was a convert)

**Comment by maumar** [comment]
@roji could you take a look?

**Comment by ajcvickers** [comment]
@roji Can you take a look at this?

File: src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs [hunk 3]
```diff
@@ -375,16 +375,16 @@ private static Expression MatchExpressionType(Expression expression, Type typeTo
         // Simplify (a != null ? new { Member = b, ... } : null).Member
         // to a != null ? b : null
         // Later null check removal will simplify it further
-        if (expression is MemberExpression
+        if (expression is MemberExpression visitedMemberExpression
+            && visitedMemberExpression.Expression is Expression inner
```
Comment (roji) [inline src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs:379]: nit

```suggestion
        if (expression is MemberExpression { Expression: Expression inner } visitedMemberExpression
```

**Review by roji — APPROVED** [review]
LGTM, see comments below on the Convert node preservation.

Looking at this more generally, the optimization seems to make quite an effort to apply only when the conditional test is a comparison to null; but I'm not sure why that is - couldn't this be generalized?

i.e. instead of only applying to:

```c#
(a != null ? new { Member = b, ... } : null).Member
```

... couldn't this apply to any test expression:

```c#
(<arbitrary expression> ? new { Member = b, ... } : null).Member
```

... transforming it to:

```c#
<arbitrary expression> ? b : null
```

(this would obviously be outside the scope of this PR)

**Comment by maumar** [comment]
@roji we could try the general purpose optimization, although idk if we wouldn't be losing some context by doing it. This optimization is not mathematically correct on the Core level - we should be pushing down the member to both sides of the conditional expression. However, in case of `x != null ? x.Member : null` we recognize this as common patten to guard against null refs, so we take some liberty here. Either way, it's currently out of scope for sure.
