### PR TITLE
Lock the database while executing Migrate()

### LINKED ISSUE #33731: Implement database locking for migrations
Generally speaking, concurrent invocations of `Migrate()` will fail and possibly leave the database in a corrupted state. In order to mitigate this, we could create a temporary table using `HistoryRepository` that will serve as a lock while the migrations are applied by the process that acquired it. Providers will be able to override all related logic to instead leverage database-specific mechanisms to accomplish this.

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #33731

### CODE REVIEW

File: src/EFCore/Diagnostics/IDiagnosticsLogger.cs [hunk 1]
```diff
@@ -104,7 +104,7 @@ bool ShouldLog(EventDefinitionBase definition)
     }
 
     /// <summary>
-    ///     Determines whether or not an <see cref="EventData" /> instance is needed based on whether or
+    ///     Determines whetheran <see cref="EventData" /> instance is needed based on whether or
```
Comment (ranma42) [inline src/EFCore/Diagnostics/IDiagnosticsLogger.cs:107]:
```suggestion
    ///     Determines whether an <see cref="EventData" /> instance is needed based on whether or
```

**Comment by AndriySvyryd** [comment]
@davidfowl FYI

File: src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs [hunk 2]
```diff
@@ -90,4 +96,171 @@ public override string GetBeginIfExistsScript(string migrationId)
...
+            {
+                retryDelay = retryDelay.Add(retryDelay);
+            }
+        }
+
+        throw new TimeoutException();
+    }
+
+    private IRelationalCommand CreateLockTableCommand()
+        => Dependencies.RawSqlCommandBuilder.Build($"""
```
Comment (roji) [inline src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs:199]: nit: we usually put the triple quotes on the next line

File: src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs [hunk 3]
```diff
@@ -90,4 +96,171 @@ public override string GetBeginIfExistsScript(string migrationId)
...
+""";
+        }
+        sql += ";";
+        return Dependencies.RawSqlCommandBuilder.Build(sql);
+    }
+
+    private SqliteMigrationDatabaseLock CreateMigrationDatabaseLock()
+        => new(CreateDeleteLockCommand(), CreateRelationalCommandParameters());
+
+    private string GetLockInsertScript(HistoryRow row)
```
Comment (roji) [inline src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs:239]: dead code?

File: src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs [hunk 4]
```diff
@@ -90,4 +96,171 @@ public override string GetBeginIfExistsScript(string migrationId)
...
+        {
+            var dbLock = CreateMigrationDatabaseLock();
+            var insertCount = CreateInsertLockCommand(DateTimeOffset.UtcNow)
+                .ExecuteScalar(CreateRelationalCommandParameters());
+            if ((long)insertCount! == 1)
+            {
+                return dbLock;
+            }
+
+            using var reader = CreateGetLockCommand().ExecuteReader(CreateRelationalCommandParameters());
```
Comment (roji) [inline src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs:126]: IIUC this select out the timestamp - you could use the RETURNING clause instead in the CreateInsertLockComand just above. At that point it can be renamed to CreateInsertOrGetLockCommand().

File: src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs [hunk 5]
```diff
@@ -90,4 +96,171 @@ public override string GetBeginIfExistsScript(string migrationId)
...
+            {
+                var timestamp = reader.DbDataReader.GetFieldValue<DateTimeOffset>(1);
+                if (DateTimeOffset.UtcNow - timestamp > timeout)
+                {
+                    var id = reader.DbDataReader.GetFieldValue<int>(0);
+                    CreateDeleteLockCommand(id).ExecuteNonQuery(CreateRelationalCommandParameters());
+                }
+            }
+
+            using var waitEvent = new ManualResetEventSlim(false);
```
Comment (roji) [inline src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs:137]: Thread.Sleep?

File: src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs [hunk 6]
```diff
@@ -347,14 +347,8 @@ public override void Close()
                     // NB: Calls RemoveCommand()
                     command.Dispose();
                 }
-                else
-                {
-                    _commands.Remove(reference);
```
Comment (roji) [inline src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs:352]: Does this fix an unrelated Sqlite bug or something?

File: src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs (hunk 2 above)
Comment (AndriySvyryd) [reply src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs:199]: Seems like a waste of a newline

File: src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs (hunk 6 above)
Comment (AndriySvyryd) [reply src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs:352]: Yes, it came out in testing. It's only hit in an unsupported scenario of using the same connection from multiple threads, but at least now the exception is more relevant

File: src/EFCore.Relational/Migrations/HistoryRepository.cs [hunk 7]
```diff
@@ -171,15 +167,49 @@ public virtual async Task<bool> ExistsAsync(CancellationToken cancellationToken
...
-        return string.Concat(commandList.Select(c => c.CommandText));
+        return commandList;
     }
 
+    /// <summary>
+    ///     Gets an exclusive lock on the database.
+    /// </summary>
+    /// <param name="timeout">The time to wait for the lock before an exception is thrown.</param>
+    /// <returns>An object that can be disposed to release the lock.</returns>
+    public abstract IMigrationDatabaseLock GetDatabaseLock(TimeSpan timeout);
```
[the remark this answers is not in the document]
Comment (AndriySvyryd) [reply src/EFCore.Relational/Migrations/HistoryRepository.cs:202]: `IMigrator` is a higher-level service, I would prefer to not expose this on it. A cleaner approach would be to create a new interface, but I think it's overdesigning

File: src/EFCore.Relational/Migrations/Internal/Migrator.cs [hunk 8]
```diff
@@ -61,6 +61,14 @@ public class Migrator : IMigrator
         _activeProvider = databaseProvider.Name;
     }
 
+    /// <summary>
+    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+    ///     any release. You should only use it directly in your code with extreme caution and knowing that
+    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+    /// </summary>
+    protected virtual TimeSpan LockTimeout { get; } = TimeSpan.FromMinutes(30);
```
[the remark this answers is not in the document]
Comment (AndriySvyryd) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:70]: It's bad if the lock expires before the migration is finished (it would be worse than the current situation since now the app could be relying on this functionality). And in the vast majority of cases, it won't matter if this value is higher than it should be. So, overall, it's better to overshoot. Filed https://github.com/dotnet/efcore/issues/34196

File: src/EFCore.Relational/Migrations/HistoryRepository.cs [hunk 9]
```diff
@@ -171,15 +167,49 @@ public virtual async Task<bool> ExistsAsync(CancellationToken cancellationToken
...
+
+    /// <summary>
+    ///     Gets an exclusive lock on the database.
+    /// </summary>
+    /// <param name="timeout">The time to wait for the lock before an exception is thrown.</param>
+    /// <param name="cancellationToken">A <see cref="CancellationToken" /> to observe while waiting for the task to complete.</param>
+    /// <returns>An object that can be disposed to release the lock.</returns>
+    /// <exception cref="OperationCanceledException">If the <see cref="CancellationToken" /> is canceled.</exception>
+    public abstract Task<IMigrationDatabaseLock> GetDatabaseLockAsync(TimeSpan timeout, CancellationToken cancellationToken = default);
```
[the remark this answers is not in the document]
Comment (AndriySvyryd) [reply src/EFCore.Relational/Migrations/HistoryRepository.cs:211]: I think that this feature is fundamental enough to warrant a provider break. And without https://github.com/dotnet/efcore/issues/34090 I don't think we can have a reasonable default implementation.

File: src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs (hunk 4 above)
Comment (AndriySvyryd) [reply src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs:126]: It's only used if there's contention. I prefer to keep the happy path simple

File: src/EFCore.Relational/Migrations/Internal/Migrator.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:70]: It's hard for me to imagine scenarios where a 30-minute timeout is actuaslly useful/meaningful... A 30 minute timeout implies that for e.g. 25 minutes there are still common/useful scenarios where waiting still makes sense, since the operation would complete successfully. There are of course some very specific migrations that could take longer, but those types of migrations could just as well take hours (and need to be managed a bit differently in any case).

Another way to look at it, is that it's hard for me to imagine a scenario where the user doesn't manually do a forceful ternmination before the 30 minutes are up. If that's true, that feels like a strong indication that the timeout should be shorter.

File: src/EFCore.Relational/Migrations/HistoryRepository.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Migrations/HistoryRepository.cs]: Yeah, you're probably right, and I wouldn't want us to do #34090 just to prevent a break here. Another option here is to simply no-op (not take a lock), and simply issue a warning. After all, no-lock is exactly the situation we've been in up to now.

But I'm OK with the breaking change of adding the abstract methods.

File: src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs (hunk 4 above)
Comment (roji) [reply src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs:126]: But isn't it more complex to do the two SQL commands rather than just one that returns the timestamp?

File: src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationDatabaseLock.cs [hunk 10]
```diff
@@ -0,0 +1,42 @@
...
+    public void Dispose()
+        => relationalCommand.ExecuteScalar(relationalCommandParameters);
+
+    /// <summary>
+    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+    ///     any release. You should only use it directly in your code with extreme caution and knowing that
+    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+    /// </summary>
+    public async ValueTask DisposeAsync()
```
Comment (roji) [inline src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationDatabaseLock.cs:40]: Non-generic ValueTask is generally frowned upon except for specific cases (reduce allocations via pooling for  non-synchronous completition), which I don't think are relevant here... Consider returning Task instead.

File: src/EFCore.Sqlite.Core/Migrations/Internal/SqliteMigrationDatabaseLock.cs [hunk 11]
```diff
@@ -0,0 +1,35 @@
...
+    public void Dispose()
+        => relationalCommand.ExecuteScalar(relationalCommandParameters);
+
+    /// <summary>
+    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+    ///     any release. You should only use it directly in your code with extreme caution and knowing that
+    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+    /// </summary>
+    public async ValueTask DisposeAsync()
```
Comment (roji) [inline src/EFCore.Sqlite.Core/Migrations/Internal/SqliteMigrationDatabaseLock.cs:33]: As above, consider returning Task

File: src/EFCore.Relational/Migrations/HistoryRepository.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (AndriySvyryd) [reply src/EFCore.Relational/Migrations/HistoryRepository.cs]: `IMigrator` performs the migration and happens to use a lock while doing so. Whatever service implements locking is conceptually a dependency of `IMigrator`
Also, there should be no reason for providers to implement `IMigrator` after https://github.com/dotnet/efcore/pull/34199

File: src/EFCore.Relational/Migrations/Internal/Migrator.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (AndriySvyryd) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:70]: > There are of course some very specific migrations that could take longer, but those types of migrations could just as well take hours (and need to be managed a bit differently in any case).

We've seen reports of applications with hundreds of migrations. If anything, you are convincing me to increase the timeout

> Another way to look at it, is that it's hard for me to imagine a scenario where the user doesn't manually do a forceful termination before the 30 minutes are up.

Forceful termination during migration application is just asking for trouble, it's akin to rebooting while updating your BIOS, because it's taking too long.
The worst case for a longer then needed lock timeout is that the users needs to wait some time before retrying if a very rare catastrophic failure occurred. However, the worst case for a timeout that's too short is a corrupted database schema that needs to be fixed manually.

File: src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs (hunk 2 above)
Comment (AndriySvyryd) [reply src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs:198]: If it's going to be fixed by code cleanup, then there's no need to bring it up.

File: src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs (hunk 4 above)
Comment (AndriySvyryd) [reply src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs:126]: Yes, in the contention case. The happy path just gets an int

File: src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationDatabaseLock.cs (hunk 10 above)
Comment (AndriySvyryd) [reply src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationDatabaseLock.cs:40]: I with that I could, but that's the signature `IAsyncDisposable` enforces

File: src/EFCore.Relational/Migrations/Internal/Migrator.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (AndriySvyryd) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:70]: Made configurable in https://github.com/dotnet/efcore/pull/34199

File: src/EFCore.Relational/Migrations/HistoryRepository.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Migrations/HistoryRepository.cs]: > IMigrator performs the migration and happens to use a lock while doing so. Whatever service implements locking is conceptually a dependency of IMigrator

It seems fine to me, for a service to include mandatory extension points for things that it needs to do as its job (i.e. apply a migration). I don't see why that extension point necessarily has to be split out to another new service in this case; that would make sense to me if the locking service would be reusable from some other non-migration service, but I can't think of such a future example.

> Also, there should be no reason for providers to implement IMigrator after https://github.com/dotnet/efcore/pull/34199

Sure, but the fact that providers don't have to implement the service at that point shouldn't be a reason to put or not locking on it.

Anyway, if you're strongly against it I won't push the point.

File: src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationDatabaseLock.cs (hunk 10 above)
Comment (roji) [reply src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationDatabaseLock.cs:40]: Good point!

File: src/EFCore.Relational/Migrations/Internal/Migrator.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:70]: >> There are of course some very specific migrations that could take longer, but those types of migrations could just as well take hours (and need to be managed a bit differently in any case).
>
> We've seen reports of applications with hundreds of migrations. If anything, you are convincing me to increase the timeout

My point here is that if we're thinking about that kind of scenario, where people are applying hundreds of migrations, taking half an hour, or maybe three hours, then a timeout is useless and we should maybe even consider removing it altogether… like if you're convinced that for termination is always bad, then why have a timeout at all?

> The worst case for a longer then needed lock timeout is that the users needs to wait some time before retrying if a very rare catastrophic failure occurred. However, the worst case for a timeout that's too short is a corrupted database schema that needs to be fixed manually.

One main reason why a timeout might occur, is a network partition or another environmental problem, meaning that the operation will never ever complete. in fact, I think that's the only reason why we have a time out here in the first place, isn't it?

**Review by roji — APPROVED** [review]
LGTM, but I think we should at least bring up the question of the timeout in a design discussion, to see what everyone thinks. But I'm good with merging this now, and possibly revisiting it later and changing the behavior if we end up deciding that.

File: src/EFCore.Relational/Migrations/Internal/Migrator.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (AndriySvyryd) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:70]: > One main reason why a timeout might occur, is a network partition or another environmental problem, meaning that the operation will never ever complete. in fact, I think that's the only reason why we have a time out here in the first place, isn't it?

Yes, the timeout is for cases like such, for providers that need to release the lock on the client, like Sqlite, to be able to recover on the next run after the specified amount of time.

[the remark this answers is not in the document]
Comment (ajcvickers) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:70]: > Forceful termination during migration application is just asking for trouble, it's akin to rebooting while updating your BIOS, because it's taking too long.

If this is true, then its really bad. We know and all agree that applying migrations often take a long, long time. This means that people _will_ forcefully terminate it. We can say not too all we want; people will still do it. I would if it had only been going 5 mins and I realized something was missing.

It feels to me like any pattern that is both very slow (we can't change that) and can't be interrupted without "asking for trouble" is going to be a pit of failure.

**Comment by ajcvickers** [comment]
Just FYI @AndriySvyryd @roji this doesn't look good to me, but if you guys are for it, then I won't push back.

File: src/EFCore.Relational/Migrations/Internal/Migrator.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (AndriySvyryd) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:70]: > If this is true, then its really bad. We know and all agree that applying migrations often take a long, long time. This means that people will forcefully terminate it.

We do log when we start applying each migration, so you can see the progress. And this change isn't making this aspect worse.

**Comment by AndriySvyryd** [comment]
We'll discuss this in a design meeting. @ErikEJ if you have feedback, please speak up

File: src/EFCore.Relational/Migrations/Internal/Migrator.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:70]: Remember that in at least some databases, transactions work quite well with migrations, in which case there's no problem with early termination - the database should always be left in a consistent state (I think PG works like this). Of course, in SQL Server certain operations cannot be done within a transaction, and there we have a problem.

> We do log when we start applying each migration, so you can see the progress. And this change isn't making this aspect worse.

This definitely helps, but keep in mind scenarios where for example an index is added without the online or concurrent option, to a huge table, and then that's a single DDL statement that could take a very long time. Of course, doing this in a huge production database is probably a very bad idea.

**Comment by roji** [comment]
> Just FYI @AndriySvyryd @roji this doesn't look good to me, but if you guys are for it, then I won't push back.

Specifically for the timeout questions, or other things? Just so that we get the discussion right.

**Comment by ajcvickers** [comment]
Mostly because termination of the process is "asking for trouble."

The timeout is also an issue, but secondary to leaving the universe in a bad state if something goes wrong.

**Comment by AndriySvyryd** [comment]
> Mostly because termination of the process is "asking for trouble."

As @roji said this only applies to operations that cannot be performed in a transaction and I don't think there's anything meaningful that we can do to make it less risky.

**Comment by ErikEJ** [comment]
Is it possible to opt out of this new behaviour? 

I think this goes somewhat against the docs advice of running only generated scripts in production !?

**Comment by roji** [comment]
@ErikEJ re opting out, do you see a possible negative consequence of having the locking behavior?

While we still advise against applying migrationas at program startup, we recognize that a lot of users do so, and with this we aim to make it less problematic - let us know your thoughts.

**Comment by ErikEJ** [comment]
What happens if a lot of web servers boot and wants to run migrations with the new behaviour? If that creates a lot of app locks = consumes server resources it could be a concern.

**Comment by roji** [comment]
Isn't it always bad to run migrations concurrently without a lock? The situation today (i.e. without any protections) seems much worse than the situation after this PR… Also, note that this doesn't create a lot of locks, but rather just one - the same lock is taken by all server instances coming up, in which attempt to apply the migrations. So I can't think of a scenario with this PR makes things worse than they already are - only better...

**Comment by ErikEJ** [comment]
Assume you mean server sessions? 

Ok, so what happens for an app that can not get the lock after a timeout? Exception?

**Comment by roji** [comment]
Yes, see above for discussions around the timeout. it's a tricky question, but I think anything is better than just allowing concurrent service sessions to apply migrations and step over each other...

**Comment by ajcvickers** [comment]
> The situation today (i.e. without any protections) seems much worse than the situation after this PR… 

I disagree. It isn't worse today, because we have consistently and repeatedly told people not to do this because it isn't safe. But now we're building in recommended ways to do things...that are not safe. Not only that, but Aspire is going to force people into using unsafe mechanisms. To me, that's not making things better.

But I won't comment anymore (on the direction we're going), because the team want to go this way and Aspire is forcing it.

**Comment by roji** [comment]
@ajcvickers first, I remember a discussion where I think we all agreed that for providers that have no full transactionality protection for migrations (e.g. SQL Server), there's really nothing we can do to make things reliable - it's just not possible, etc.

That aspect of it also seems really orthogonal to whether people apply migrations at startup, whether locking is applied, etc. In other words, if you're applying migrations today via a migration bundle or SQL script, and there's a network partition, then you're left in an indeterminate, possibly inconsistent state; that's just the way things are (unless the database fully supports transactions). Nothing about Aspire, or this PR really changes that as far as I can tell...

I agree that the lock timeout raises some questions that I'd like us to discuss and find consensus on... But that's only a very specific aspect, whereas you seem to be saying that the whole approach is somehow problematic, and I think it's important for us to understand how/why.

> But I won't comment anymore (on the direction we're going), because the team want to go this way and Aspire is forcing it.

I don't think anybody is forcing us to do anything - people have been running migrations on startup despite all the guidance we've tried to give, and my memory of the design meeting is that we agreed to at least improve that scenario. In any case, I do think we should discuss if you think this is wrong.

**Comment by ajcvickers** [comment]
@roji After reviewing the code here, I have reverted to my previous opinion. But it's all good; don't need to block on me. Please proceed.

**Comment by ajcvickers** [comment]
@roji and I had a conversation about this. My main concern here is the unreliability of applying Migrations. In particular, the times we make changes on SQL Server outside of a transaction. If we can stop doing this by default, then I would be much happier with promoting (proving guidance that recommends) a mechanism that executes at runtime in the background such that if it fails it cannot leave the database in a permanently bad state. If, as Shay asserts, these are edge cases only, then a breaking change to stop handling them without an explicit opt-in should not be impactful. On the other change, if this break is impactful, then it indicates that the reliability is not just an edge case.

**Comment by AndriySvyryd** [comment]
> a breaking change to stop handling them without an explicit opt-in should not be impactful

If we do this it will fail on the first run that doesn't support transactions, the user will opt-in and then we are just back to the same behavior. Sure, the user might be more aware of the risks, but there's really nothing that they can do to mitigate them.

**Comment by ErikEJ** [comment]
Just to understand: what happens today is that all app instances attempt to apply the same migration at around the same time, either causing schema corruption or runtime errors ??

**Comment by ajcvickers** [comment]
@AndriySvyryd The fundamental point is that the opt-in should only be needed very rarely, otherwise Shay's argument falls down, and I revert to we shouldn't do this at all.

@ErikEJ This particular PR isn't about the reliability issue. The point is that if the reliability issue is so bad that the developer writing it says an abnormal termination is, "asking for trouble" then I don't think we should be going in the direction of providing guidance around this. But if we are going to provide this guidance, then the concurrency issue also needs to be solved, which is what this PR is about.

**Comment by AndriySvyryd** [comment]
> otherwise Shay's argument falls down, and I revert to we shouldn't do this at all.

We shouldn't add locking? Even though it's orthogonal? Or we shouldn't allow migration operations without transactions at all?

> @AndriySvyryd The fundamental point is that the opt-in should only be needed very rarely

Ok, so should we add a warning as error for any  non-transactional migration operation, including the ones added manually by the user, as long as it's not the only one in the migration, that says "The migration operation '{operation}' cannot be executed in a transaction. If the app is terminated or an unrecoverable error occurs while this operation is being executed then the migration will be left in a partially applied state and would need to be reverted manually before it can be applied again. Create a separate migration that contains just this operation."?

**Comment by ErikEJ** [comment]
@AndriySvyryd great idea!

**Comment by roji** [comment]
Hey all, I've got a few comments here too, will post them once I'm back at the end of the week...

**Comment by AndriySvyryd** [comment]
Added the warning in https://github.com/dotnet/efcore/pull/34199

**Comment by roji** [comment]
First, IMHO it's important to clearly distinguish between **reliability** issues when applying migrations, and **concurrency** issues; this PR attempts only to address the concurrency issues that arise when multiple server instances start up and attempt to apply migrations at startup in parallel, stepping on each others' toes. It neither improves the reliability situation nor makes it worse; that is, if a non-transactional migration is applied and a network partition occurs, the results are undefined regardless of whether the migration is applied on startup, via a SQL script, a migration bundle, etc.

In my conversation with @ajcvickers he made the point that by improving the concurrency situation, we may be making the situation worse, because any reliability issue is easier to miss when applying the migration at startup (compared to e.g. via a bundle, in a special deployment-time step). I'm not sure to what extent this is true - an error on application startup should take the application down, which should be visible to e.g. devops in a similar way as the failure of a deployment step. And in any case, if a user applies migration without any sort of health checking or mechanism to ensure that the app started successfully, IMHO all bets are off and anything we do here is probably irrelevant - such users aren't going to be deterred by at-startup migrations being unsafe in any case. In other words, I don't think anything is gained by leaving at-startup migrations unsafe concurrency-wise - we're not helping guide users away from there by doing that.

Now, to bring a bit of concreteness to the reliability question (we sometimes fall into the trap of discussing things in the abstract)... Looking at [SqlServerMigrationsSqlGenerator](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs), I can see transactions being suppressed in the following cases:

* Any DDL operation touching a memory-optimized tables ([as documented](https://learn.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/unsupported-sql-server-features-for-in-memory-oltp?view=sql-server-ver16#scenarios-not-supported))
* Database create/drop (these aren't "real" migrations and transactionality makes no sense here anyway)
* Alter database operations (i.e. change collation, edition). I'm not sure this is strictly necessary - there's some in-memory logic there, and our suppression may be for that, possibly being applied in other, unnecessary cases as well.

In other words, I think we can say that SQL Server supports transactional migrations in the vast majority of cases, and AFAIK so do the other cases; as far as I can tell, the reliability issues we've discussing can generally be considered an edge case. I'd love to be corrected if I've missed something here - I notably haven't done a thorough cross-database investigation; but if things are as they are, than I wouldn't want essentially the SQL Server in-memory table limitation to determine wide-reaching, architectural decisions in how migrations are applied etc.

Finally, I do agree that we need to discuss what exactly we want to achieve with the lock timeout added in this PR, as well as verify that the locks themselves won't create issues (if there's trouble during apply. For example, the SQL Server locking implementation uses [`sp_getapplock`](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-getapplock-transact-sql?view=sql-server-ver16); the docs state that "Locks associated with the session are released when the session is logged out.", which I read to mean that if a network partition occurs, the lock automatically gets released and shouldn't cause any trouble. But we should indeed pay attention to this aspect.

**Comment by roji** [comment]
Just for completeness, in PG there's one DDL operation (AFAIK) that can't be done inside a migration - [creation of an index concurrently](https://www.postgresql.org/docs/current/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY) (in SQL Server this is known as "online" creation (i.e. the table involved is available for regular operations while the index is being created).
