### PR TITLE
Fix doc typo

### LINKED ISSUE #25860: Typo in RelationalPropertyExtensions.IsFixedLength Doc
"as" should be "is" in the descriptions:

> Returns a flag indicating if the property **as** capable of storing only fixed-length data, such as strings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158ab06b-9877-fb31-51ad-f9782c2b698c
* Version Independent ID: 4c9bdf01-3926-f977-0227-5b3ef2bd5f3d
* Content: [RelationalPropertyExtensions.IsFixedLength Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalpropertyextensions.isfixedlength?view=efcore-5.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/RelationalPropertyExtensions.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalPropertyExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

### PR DESCRIPTION
**Pull request by roji**
Fixes #25860

### CODE REVIEW

File: src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs [hunk 1]
```diff
@@ -911,15 +911,15 @@ public static void SetDefaultValue(this IMutableProperty property, object? value
         }
 
         /// <summary>
-        ///     Returns a flag indicating if the property as capable of storing only fixed-length data, such as strings.
+        ///     Returns a flag indicating if the property is capable of storing only fixed-length data, such as strings.
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs:914]:
```suggestion
        ///     Returns a flag indicating whether the property is capable of storing only fixed-length data, such as strings.
```

File: src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs [hunk 2]
```diff
@@ -911,15 +911,15 @@ public static void SetDefaultValue(this IMutableProperty property, object? value
...
         /// </summary>
         /// <param name="property"> The property. </param>
         /// <returns> A flag indicating if the property as capable of storing only fixed-length data, such as strings. </returns>
         public static bool? IsFixedLength(this IReadOnlyProperty property)
             => (bool?)property.FindAnnotation(RelationalAnnotationNames.IsFixedLength)?.Value;
 
         /// <summary>
-        ///     Returns a flag indicating if the property as capable of storing only fixed-length data, such as strings.
+        ///     Returns a flag indicating if the property is capable of storing only fixed-length data, such as strings.
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs:922]:
```suggestion
        ///     Returns a flag indicating whether the property is capable of storing only fixed-length data, such as strings.
```

File: src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs [hunk 3]
```diff
@@ -911,15 +911,15 @@ public static void SetDefaultValue(this IMutableProperty property, object? value
...
         /// </summary>
         /// <param name="property"> The property. </param>
         /// <param name="storeObject"> The identifier of the table-like store object containing the column. </param>
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs:925]: Also fix it in the `SetIsFixedLength` methods

**Review by AndriySvyryd — APPROVED** [review]
