### PR TITLE
ExecuteUpdate: Correctly identify when we need to cause a subquery join

### LINKED ISSUE #28823: ExecuteUpdate with cross apply produces invalid SQL
On PG, test Update_with_cross_apply_set_constant produces the following SQL:

```sql
UPDATE "Customers" AS c
SET "ContactName" = 'Updated'
FROM (
    SELECT o."OrderID", o."CustomerID", o."EmployeeID", o."OrderDate"
    FROM "Orders" AS o
    WHERE o."OrderID" < 10300 AND date_part('year', o."OrderDate")::int < length(c."ContactName")::int
) AS t
WHERE c."CustomerID" LIKE 'F%'
```

This fails with the following, since c.ContactName references an outer column:

```
ERROR:  invalid reference to FROM-clause entry for table "c" at character 240
HINT:  There is an entry for table "c", but it cannot be referenced from this part of the query.
```

Originally discussed in https://github.com/npgsql/efcore.pg/pull/2475#discussion_r948507500

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #28823

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 1]
```diff
@@ -1444,6 +1445,16 @@ static Expression GetEntitySource(IModel model, Expression propertyAccessExpress
                 var entityProjectionExpression = (EntityProjectionExpression)selectExpression.GetProjection(projectionBindingExpression);
                 var column = entityProjectionExpression.BindProperty(entityShaperExpression.EntityType.GetProperties().First());
                 table = column.Table;
+                if (ReferenceEquals(selectExpression.Tables[0], table))
+                {
+                    // If the table we are looking for it first table, then we need to verify if we can lift the next table in FROM clause
+                    var secondTable = selectExpression.Tables[1];
+                    if (!(secondTable is InnerJoinExpression
+                        || secondTable is CrossJoinExpression))
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1453]:
```suggestion
                    if (secondTable is not InnerJoinExpression and not CrossJoinExpression)
```

**Review by roji — APPROVED** [review]
