### PR TITLE
Match indexer properties correctly

### LINKED ISSUE #26590: Query with n:m relation adds non-existent column
#n:m relation query statements build incorrectly

when including data from a n:m table the SQL generated includes a non-existent column, resulting in a failing SQL statement
the below code is created by dbScaffold (DDL statements at the bottom)
```csharp
 var dbContext = new myContext();
 var y = dbContext.Crashtest.
    Include(m => m.Karosserieform)
    .ToList();
```
this builds the following SQL statement which fails because there is no `CrashtestId1` column
```sql
SELECT
  [c].[CrashtestId]
 ,[c].[Bezeichnung]
 ,[t].[CrashtestId]
 ,[t].[KarosserieformId]

 ,[t].[CrashtestId1] ''<---- this line should not exist

 ,[t].[KarosserieformId0]
 ,[t].[Bezeichnung]
FROM [Crashtest] AS [c]
LEFT JOIN (SELECT
    [c0].[CrashtestId]
   ,[c0].[KarosserieformId]

   ,[c0].[CrashtestId1] ''<---- this line should not exist

   ,[k].[KarosserieformId] AS [KarosserieformId0]
   ,[k].[Bezeichnung]
  FROM [CrashtestKarosserieform] AS [c0]
  INNER JOIN [Karosserieform] AS [k]
    ON [c0].[KarosserieformId] = [k].[KarosserieformId]) AS [t]
  ON [c].[CrashtestId] = [t].[CrashtestId]
ORDER BY [c].[CrashtestId], [t].[CrashtestId], [t].[KarosserieformId]
```

Statement used for scaffolding
```shell
dotnet ef dbcontext scaffold "data source=localhost;initial catalog=dbname;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework" Microsoft.EntityFrameworkCore.SqlServer `
--output-dir "database" --table dbo.Crashtest --table dbo.CrashtestKarosserieform --table dbo.Karosserieform --data-annotations --use-database-names --force  --no-pluralize 
```

DDL-Statements:
```sql
CREATE TABLE dbo.Crashtest (
  CrashtestId INT IDENTITY
 ,Bezeichnung NVARCHAR(50) NULL
 ,CONSTRAINT pkct PRIMARY KEY CLUSTERED (CrashtestId)
) ON [PRIMARY] 
GO

CREATE TABLE dbo.Karosserieform (
  KarosserieformId INT IDENTITY
 ,Bezeichnung NVARCHAR(255) NULL
 ,CONSTRAINT pk_kf PRIMARY KEY CLUSTERED (KarosserieformId)
) ON [PRIMARY]
GO

CREATE TABLE dbo.CrashtestKarosserieform (
  CrashtestId INT NOT NULL
 ,KarosserieformId INT NOT NULL
 ,CONSTRAINT pk_link PRIMARY KEY CLUSTERED (CrashtestId, KarosserieformId)
) ON [PRIMARY]
GO

ALTER TABLE dbo.CrashtestKarosserieform
ADD CONSTRAINT fk_kf FOREIGN KEY (KarosserieformId) REFERENCES dbo.Karosserieform (KarosserieformId)
GO

ALTER TABLE dbo.CrashtestKarosserieform
ADD CONSTRAINT fk_ct FOREIGN KEY (CrashtestId) REFERENCES dbo.Crashtest (CrashtestId) ON DELETE CASCADE
GO
```

# provider and version information
EF Core version: 6.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: win 10
IDE: (e.g. Visual Studio 20202 current)

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #26590

**Description**

When an FK attribute is used with a property on a property bag entity type EF ends up creating a property with a uniquified name instead of using the specified one.

This is made worse in 6.0 because now EF scaffolds this type of configuration for existing databases.

**Customer impact**

User queries will throw exception since the new property doesn't match a column in the database

**How found**

Customer reported on 6.0

**Regression**

Yes, this worked in 5.0

**Testing**

Added test for this scenario.

**Risk**

Low, only affects property bag entities (`Dictionary<string, object>`). Also added a quirk mode.

### CODE REVIEW

File: src/EFCore/Metadata/Internal/Property.cs [hunk 1]
```diff
@@ -999,10 +999,13 @@ public static bool AreCompatible(IReadOnlyList<Property> properties, EntityType
             => properties.All(
                 property =>
                     property.IsShadowProperty()
-                    || ((property.PropertyInfo != null
-                            && entityType.GetRuntimeProperties().ContainsKey(property.Name))
-                        || (property.FieldInfo != null
-                            && entityType.GetRuntimeFields().ContainsKey(property.Name))));
+                    || (property.IsIndexerProperty()
+                        && (!AppContext.TryGetSwitch("Microsoft.Data.Sqlite.Issue26590", out var enabled) || !enabled)
```
Comment (roji) [inline src/EFCore/Metadata/Internal/Property.cs:1003]:
```suggestion
                        && (!AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue26590", out var enabled) || !enabled)
```

**Review by bricelam — APPROVED** [review]
