### PR TITLE
Fix to #29513 - Json: improve projection deduplication for scenarios containing collection indexers

### LINKED ISSUE #29513: Json: improve projection deduplication for scenarios containing collection indexers
Currently we de-duplicate projections only if the additional path doesn't contain any collection indexes. They can only appear in the "source" JSON path. We could potentially improve that. e.g.:

source: x.OwnedReference
dupe: x.OwnedReference.OwnedCollection[0]

We could also de-duplicate if source projects entire collection and the dupe projects just one of it's elements, e.g.:

source: x.OwnedCollection
dupe: x.OwnedCollection[2]

### PR DESCRIPTION
**Pull request by maumar**
Reworking shaper to properly track key values for JSON entities that are accessed via array element. Every array access needs to be recorded and incorporated into the key later. Constants can be stored directly by value, non-constants are added to projection, and we keep track of the projection index instead.

- added JsonProjectionInfo in place of a value tuple to store shaping info needed for JSON, so that it's more readable,
- reworked JsonShapingPreProcess to generate and cache key values as well as JsonElement.
- moved dangling (i.e. not coming from include on the owner entity) JSON entity processing after Include processing, so that we guarantee to have all the entities in state manager by the time we get to processing the dangling JSON stuff.

Fixes #29513

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 1]
```diff
@@ -1246,107 +1255,248 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
-            while (index <= additionalPath.Length);
+            while (index <= jsonProjectionInfo.AdditionalPath.Length);
+
+            return (currentJsonElementVariable!, currentKeyValuesVariable!);
+
+            ParameterExpression ExtractAndCacheNonConstantJsonCollectionElementAccessValue(int index)
+            {
+                if (!_jsonCollectionNonConstantElementAccessMap.TryGetValue(index, out var collectionElementAccessParameter))
+                {
+                    collectionElementAccessParameter = Expression.Parameter(typeof(int?));
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1477]: we could store these values as int, rather than int? - this way we only need to perform convert to int once (i.e. here). If the value we get for the array is null, things break anyway later.

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 2]
```diff
@@ -1246,107 +1252,248 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
         {
-            var jsonColumnProjectionIndex = projectionIndex.Item1;
-            var keyInfo = projectionIndex.Item2;
-            var additionalPath = projectionIndex.Item3;
-            var specifiedCollectionIndexesCount = projectionIndex.Item4;
+            if (_existingJsonElementMap.TryGetValue(
+                (jsonProjectionInfo.JsonColumnIndex, jsonProjectionInfo.AdditionalPath),
+                out var finalJsonElementVariable))
+            {
+                //if we already cached JsonElement then key values are guaranteed to have been cached also, as they go in tandem
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1262]:
```suggestion
                // if we already cached JsonElement then key values are guaranteed to have been cached also, as they go in tandem
```

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 3]
```diff
@@ -1246,107 +1252,248 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                var fullPathCacheKey = jsonProjectionInfo.AdditionalPath.Select(x => (x.Item2, x.Item3)).ToArray();
+                var finalKeyValuesVariable = _existingKeyValuesMap[(jsonProjectionInfo.JsonColumnIndex, fullPathCacheKey)];
+
+                // if the JsonElement variable for the full path is present in the cache,
+                // it means we already went through this processs before
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1267]:
```suggestion
                // it means we already went through this process before
```

File: src/EFCore.Relational/Query/Internal/JsonProjectionInfo.cs [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+    /// </summary>
+    public readonly List<(IProperty, int)> KeyInfo { get; init; }
+
+    /// <summary>
+    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+    ///     any release. You should only use it directly in your code with extreme caution and knowing that
+    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+    /// </summary>
+    public readonly (int?, int?)[] ArrayElementAccessInfo { get; init; }
```
Comment (roji) [inline src/EFCore.Relational/Query/Internal/JsonProjectionInfo.cs:66]: Add meaningful names to the fields of the returned value tuple, so that at call sites we don't need to do Item1/Item2

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 5]
```diff
@@ -1246,107 +1252,248 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+            // key values only changes if we access element of the array (as opposed to JSON property access)
+            do
             {
-                var projection = _selectExpression.Projection[keyInfo[i].Item2];
+                var jsonElementCacheKey = jsonProjectionInfo.AdditionalPath[..index];
+                var keyValuesCacheKey = jsonProjectionInfo.AdditionalPath[..index].Select(x => (x.Item2, x.Item3)).ToArray();
+
+                if (_existingJsonElementMap.TryGetValue(
+                    (jsonProjectionInfo.JsonColumnIndex, jsonElementCacheKey),
+                    out var exisitingJsonElementVariable))
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1289]:
```suggestion
                    out var existingJsonElementVariable))
```

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 6]
```diff
@@ -1246,107 +1252,248 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+            var currentKeyValuesVariable = default(ParameterExpression);
+            var index = 0;
+            var additionalKeyGeneratedCount = 0;
 
-            for (var i = 0; i < keyInfo.Count; i++)
+            // go through each segment in the additional path and generate JsonElement and key values
+            // store them in variables and cache them, so we can re-use it later if needed
+            // JsonElement needs to be generated for every path segment, as they are always different
+            // key values only changes if we access element of the array (as opposed to JSON property access)
+            do
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1282]: Any reason for this not to be a regular for loop? I can see `index++` in various places, these could be removed

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 7]
```diff
@@ -1246,107 +1252,248 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                // if the JsonElement variable for the full path is present in the cache,
+                // it means we already went through this processs before
+                // and have already generated all the steps leading to the result
+                // i.e. we can safely return from the pre process
+                return (finalJsonElementVariable, finalKeyValuesVariable);
+            }
 
-            var keyValuesParameter = Expression.Parameter(typeof(object[]));
-            var keyValues = new Expression[keyInfo.Count + specifiedCollectionIndexesCount];
+            var currentJsonElementVariable = default(ParameterExpression);
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1273]: Should these be named previousJsonElementVariable (or last)? Because I see them getting assigned out of the cache in the loop, and then you do `continue` (so they seem to get accessed in the next iteration loop)?

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 8]
```diff
@@ -1246,107 +1252,248 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
-                keyValues[i] = Expression.Convert(
-                    CreateGetValueExpression(
+                    index++;
+                    continue;
+                }
+
+                if (index == 0)
+                {
+                    // create the JsonElement for the initial entity
+                    var jsonElementValueExpression = CreateGetValueExpression(
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1301]: Am not sure, but... if I understand correctly, this does dbDataReader.GetFieldValue() (or whatever) multiple times, once for each thing projected out from the JSON document. Could we optimize this to get the document out once, so we only call GetFieldValue once for a given JSON column?

File: src/EFCore.Relational/Query/Internal/JsonProjectionInfo.cs [hunk 9]
```diff
@@ -0,0 +1,75 @@
...
+        int jsonColumnIndex,
+        List<(IProperty, int)> keyInfo,
+        (int?, int?)[] arrayElementAccessInfo,
+        (string?, int?, int?)[] additionalPath)
+    {
+        // projection index for json column name
+        JsonColumnIndex = jsonColumnIndex;
+
+        // list of key properties for the parent entity: property + it's projection index
+        KeyInfo = keyInfo;
```
Comment (roji) [inline src/EFCore.Relational/Query/Internal/JsonProjectionInfo.cs:30]: KeyAccessInfo (consistency with ArrayElementAccessInfo)?

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 10]
```diff
@@ -1246,107 +1252,248 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                            var missingKeyValueAssignment = Expression.Assign(
+                                Expression.MakeIndex(
+                                    currentKeyValuesVariable,
+                                    _objectArrayIndexerPropertyInfo,
+                                    new[] { Expression.Constant(currentKeyValuesCount - 1) }),
+                                Expression.Convert(
+                                    Expression.Add(elementAccessExpression, Expression.Constant(1)),
+                                    typeof(object)));
+
+                            _variables.Add(currentKeyValuesVariable);
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1437]: I don't fully understand everything that's going on here - but it seems we're generating lots of shaper code for doing stuff for each and every path segment. Just want to make sure that the actual code that gets generated at the end is efficient and doesn't contain any unneeded computation.

(some comments with generated code in C# form would help understand exactly what's going on)

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 11]
```diff
@@ -1246,107 +1252,248 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                        Expression.MakeMemberAccess(
+                            currentJsonElementVariable!,
+                            _nullableJsonElementHasValuePropertyInfo),
+                        Expression.Convert(
+                            jsonElementAccessExpressionFragment,
+                            currentJsonElementVariable!.Type),
+                        Expression.Default(currentJsonElementVariable!.Type));
+
+                    currentJsonElementVariable = Expression.Variable(
+                        typeof(JsonElement?));
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1454]:
```suggestion
                    var jsonElementValueExpression = Expression.Condition(
                        Expression.MakeMemberAccess(currentJsonElementVariable!, _nullableJsonElementHasValuePropertyInfo),
                        Expression.Convert(jsonElementAccessExpressionFragment, currentJsonElementVariable!.Type),
                        Expression.Default(currentJsonElementVariable!.Type));

                    currentJsonElementVariable = Expression.Variable(typeof(JsonElement?));
```

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 12]
```diff
@@ -1246,107 +1252,248 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
                 }
 
                 index++;
             }
-            while (index <= additionalPath.Length);
+            while (index <= jsonProjectionInfo.AdditionalPath.Length);
+
+            return (currentJsonElementVariable!, currentKeyValuesVariable!);
+
+            ParameterExpression ExtractAndCacheNonConstantJsonCollectionElementAccessValue(int index)
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1470]: I think the standard JSON naming is array (rather than the more general "collection", which doesn't imply ordering). If so we should align to that wherever we're referring to a JSON array (variable/method names, etc.)

```suggestion
            ParameterExpression ExtractAndCacheNonConstantJsonArrayElementAccessValue(int index)
```

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 13]
```diff
@@ -1665,12 +1812,21 @@ public bool ContainsCollectionMaterialization(Expression expression)
             }
         }
 
-        private sealed class ExisitingJsonElementMapKeyComparer : IEqualityComparer<(int, string[])>
+        private sealed class ExisitingJsonElementMapKeyComparer : IEqualityComparer<(int, (string?, int?, int?)[])>
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1815]: Put meaningful names on the fields

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 14]
```diff
@@ -1660,9 +1659,43 @@ ConstantExpression AddJsonProjection(JsonQueryExpression jsonQueryExpression, Js
                 keyInfo.Add((keyProperty, AddToProjection(keyColumn)));
             }
 
-            var specifiedCollectionIndexesCount = jsonScalarToAdd.Path.Count(x => x.ArrayIndex != null);
+            var arrayElementAccessInfo = new List<(int?, int?)>();
+            foreach (var elementAccessSegment in jsonScalarToAdd.Path.Where(x => x.ArrayIndex != null))
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1663]: See my comment about possibly collapsing together KeyInfo, ArrayElementAccessInfo, AdditionalPath (or maybe at least KeyInfo/ArrayElementAccessInfo). AdditionalPath already represents both property and array access, it feels like at least KeyInfo/ArrayElementAccessInfo could do the same? Or possibly just all three in a single polymorphic array...

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 15]
```diff
@@ -1660,9 +1659,43 @@ ConstantExpression AddJsonProjection(JsonQueryExpression jsonQueryExpression, Js
...
+            {
+                if (elementAccessSegment.ArrayIndex is SqlConstantExpression { Value: int intValue } sqlConstant)
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1665]: Below as well

```suggestion
                if (elementAccessSegment.ArrayIndex is SqlConstantExpression { Value: int intValue })
```

**Review by roji — COMMENTED** [review]
Looks good, and I think I'm even half-understanding it :)

See especially the comments about how to represent stuff inside JsonProjectionInfo, plus various nits.

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs (hunk 7 above)
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1273]: My thinking was current, as in the one we are currently processing. If we assign from cache means we don't need to create them (so continue to the next element in JSON path). Otherwise we do all the processing for the "current" element (creating + caching). We don't really access them in subsequent iteration of the loop, we just want to go through entire path and cache everything. Well, we do access previous key values since we use Array.Copy, but not json element variables, but apart from that we just need to variables for the complete path.

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs (hunk 8 above)
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1301]: if you are just projecting two scalars, e.g. `new { entity.Json.Name, entity.Json.Number }` there is no deduplication at all, because those get translated to simple SqlExpressions and the entire shaper code is circumvented here. However, if you are projecting json entites, then yes - we cache pretty much everything and will only read data from json column once. And the idea of deduplication is that if we read a JSON subtree, we automatically have all the info needed for every other entity within. e.g. new `{ entity.Json, entity.Json.MyReference, entity.Json.MyCollection, Foo = entity.Json.MyCollection[2] 
}` will all read just once, build/cache all the variables for paths inside, and when we are about to process `entity.Json.MyCollection`, we just read it from the cache instantly

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs (hunk 11 above)
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1454]: I personally prefer this style (either method and all args on same line, or method on separate line and every argument also on it's own line. Do we have a code rule for this or just matter of preference? If former, i'm gonna have a lot of code to fix >.<

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs (hunk 7 above)
Comment (roji) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1273]: Sounds good.

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs (hunk 8 above)
Comment (roji) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1301]: That's really nice.

I can suggest doing the same optimization also for non-entity access as well (not necessarily in the scope of this PR). Basically, we don't know how much dbDataReader.GetFieldValue costs (across providers...), so it's best to not it multiple times. In addition, if we happen to access two scalars somewhere deep inside the JSON tree, it's better to not have to traverse all of the way from the top twice, but do it once and just do the two scalar accesses at the end.

Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1301]: filed #29839

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs (hunk 10 above)
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1437]: that's correct - we generate JsonElement variable for every element in the path early on, because it's guaranteed that we will use it - since we always have to materialize all the owned entities in the aggregate. Doing it early is (arguably) more readable and also lets us avoid some tricky bugs where we try to access something that hasn't been initialized yet. 

The best way I found to figure out what's going on is put breakpoint at the line:

```
var shaper = new ShaperProcessingExpressionVisitor(this, selectExpression, _tags, splitQuery, nonComposedFromSql).ProcessShaper(
```

in `RelationalShapedQueryCompilingExpressionVisitor` class and in debugger invoke 

`new Microsoft.EntityFrameworkCore.Query.ExpressionPrinter().Print(...)` 
over the `shaper` expression.

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 16]
```diff
@@ -1246,107 +1252,248 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                        typeof(JsonElement?),
+                        property: null);
 
-            for (var i = 0; i < specifiedCollectionIndexesCount; i++)
-            {
-                keyValues[keyInfo.Count + i] = Expression.Convert(
-                    Expression.Constant(0), typeof(object));
-            }
+                    currentJsonElementVariable = Expression.Variable(
+                        typeof(JsonElement?));
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1310]: will do that in some future PR, as it's quite a bit of work. Reason why it was originally left unnamed is to avoid the clashes - let compiler handle everything and inject the indexes. I agree about readability, but we need to make sure we don't mess up or we might introduce some sneaky bugs.

[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1310]: filed #29840

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 17]
```diff
@@ -87,15 +97,24 @@ private sealed partial class ShaperProcessingExpressionVisitor : ExpressionVisit
...
-        private readonly Dictionary<ParameterExpression, (ParameterExpression, ParameterExpression)> _jsonValueBufferParameterMapping =
-            new();
+        private readonly Dictionary<ParameterExpression, (ParameterExpression, ParameterExpression)>
+            _jsonValueBufferParameterMapping = new();
 
         private readonly Dictionary<ParameterExpression, (ParameterExpression, ParameterExpression)>
             _jsonMaterializationContextParameterMapping = new();
 
-        private readonly Dictionary<(int, string[]), ParameterExpression> _existingJsonElementMap
+        // cache for the JsonElement values we have generated - storing variables that the JsonElements are assigned to
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:106]: those dictionaries are used in very narrow scope, nobody should use them in any other place. I'd personally keep the comments this way, especially that it seems to be the general way we do comments in private parts (even in this class, few lines above).

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 14 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1663]: We could combine key info and array element access info, although that also has it's drawbacks - for key, we would have both property and non-nullable constant value set, whereas for the array indexer, we would only have one of the elements in the record be non-null. I will play with it a bit and see which one feels better. It is true, that the key info was there before and array element access is what I added as a minimal impact/evolution thing. It is very likely that the code can be improved when looked at the bigger picture.

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs (hunk 17 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs]: OK, not critical.

From my perspective, as long as we're making the effort to write comments on a field, I see no reason to not just put them in xmldocs ("triple comment instead of double"), so that Intellisense shows them. It certainly helps a newcomer that needs to grok the code (like me, I know I jumped back and forth to check the comment for the field), and AFAICT seems to have no drawback.

But obviously not very important.

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs (hunk 10 above)
Comment (roji) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1435]: Thanks, makes sense.

> new Microsoft.EntityFrameworkCore.Query.ExpressionPrinter().Print(...)

I've always wondered why we don't have a static `ExpressionPrinter.Print(expression)`... 😉

Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1435]: static one would be nice :) but it does have some state (e.g. parameter names).

File: src/EFCore.Relational/Query/Internal/JsonProjectionInfo.cs [hunk 18]
```diff
@@ -41,30 +39,22 @@ namespace Microsoft.EntityFrameworkCore.Query.Internal;
...
-    ///     and the projection index is stored here
-    /// </summary>
-    /// <remarks>
-    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
-    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
-    ///     any release. You should only use it directly in your code with extreme caution and knowing that
-    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
-    /// </remarks>
-    public (int? ConstantArrayIndex, int? NonConstantArrayIndex)[] ArrayElementAccessInfo { get; }
+    public List<(IProperty? KeyProperty, int? ConstantKeyValue, int? KeyProjectionIndex)> KeyAccessInfo { get; }
```
Comment (maumar) [inline src/EFCore.Relational/Query/Internal/JsonProjectionInfo.cs:57]: maybe different order? (Constant, KeyProperty, KeyProjectionIndex) or (KeyProperty, KeyProjectionIndex, Constant) ?

**Comment by maumar** [comment]
@roji new version up - JsonProjectionInfo refactoring in separate commit, all other feedback addressed in the initial one

**Comment by maumar** [comment]
ping @roji

**Review by roji — APPROVED** [review]
