### PR TITLE
Handle complex types in GetDatabaseValues

### LINKED ISSUE #31353: Constructor calls when using inheritance with owned entities causes exceptions
## Description and Code

When using owned entities it is fairly normal to use some sort of constructor validation, like throwing `ArgumentNullException` for null values.
When an owned type like this is used in an inheritance hierarchy on a child EfCore tries to call the constructor with null values for some reason when the parent DbSet is queried. This then leads to a `ArgumentNullException`.
This only happens when entities of another type that actually have `NULL` values in their columns are also present in the table.

## Repro

A repo for the problem can be found here: https://github.com/Jejuni/EfCoreInheritanceProblem

Replace the SqlServer connection string in `MyDbContext` with a valid one for your machine.

## Code

Given these entities:

```cs
public class Name
{
    public Name(string firstName, string lastName)
    {
        FirstName = firstName ?? throw new ArgumentNullException(nameof(firstName));
        LastName = lastName ?? throw new ArgumentNullException(nameof(lastName));
    }

    public string FirstName { get; }
    public string LastName { get; }
}


public abstract class Parent
{
    public Guid Id { get; set; }
}

public class ChildOne : Parent
{
    public int Number { get; set; }
}

public class ChildTwo : Parent
{
    public Name Name { get; set; }
}
```

and this configuration:

```cs
modelBuilder.Entity<Parent>(b =>
        {
            b.HasDiscriminator<string>("Discriminator")
                .HasValue<ChildOne>("one")
                .HasValue<ChildTwo>("two");
        });

        modelBuilder.Entity<ChildTwo>(b =>
        {
            b.OwnsOne(x => x.Name, nameBuilder =>
            {
                nameBuilder.Property(x => x.FirstName);
                nameBuilder.Property(x => x.LastName);
            });
        });
```

leads to an exception when the following code is run:

```cs
await using (var ctx = new MyDbContext())
{
    await ctx.Database.EnsureDeletedAsync();
    await ctx.Database.EnsureCreatedAsync();
}

await using (var ctx2 = new MyDbContext())
{
    ctx2.ChildOnes.Add(new ChildOne { Number = 2 });

    await ctx2.SaveChangesAsync();
}

await using (var ctx3 = new MyDbContext())
{
    var childOnes = await ctx3.ChildOnes.ToListAsync();
    var childTwos = await ctx3.ChildTwos.ToListAsync();
    // NEXT LINE CAUSES EXCEPTION
    var parents = await ctx3.Parents.ToListAsync();
}
```

### Include stack traces

Stack trace shows the code thrown from user error during execution of `SingleQueryingEnumerable`:

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'firstName')
  Source=EfCoreInheritanceProblem
  StackTrace:
   at EfCoreInheritanceProblem.Name..ctor(String firstName, String lastName) in Whatever\EfCoreInheritanceProblem\EfCoreInheritanceProblem\Entities.cs:line 7
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__20.MoveNext()
```

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer, 7.0.9
Target framework: .NET 7.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.6.5

### LINKED ISSUE #32701: IndexOutOfRange for EntityEntry.GetDatabaseValues() with complex type and TPH
## Problem
I want to update the original values of an entity manually, therefore I use `GetDatabaseValues`.
Unfortunately in a specific edge case the indicies for `IProperty` on `ArrayPropertyValues` are partially invalid.
This results in an IndexOutOfRangeException because TPH properties indicies do not fit the underlying value array.
The root of the problem might be that
- complex type values are not loaded
- and the indicies TPH properties therfore do not match the value array length.

Not only does this result in an exception, this also:
- affects `EntityEntry.Reload()` because it does the same internally.
- complex property data does not get reloaded / loaded.

This problems only occures on TPH properties, there is no exception with normal entities.

## Details
The value set loaded contains all proeprties except the complex type ones.
image

But the index of the additional property of the `Supplier`-Type does returns `4` with `dbValues.Properties.ToArray()[3].GetIndex()`
which results in an IndexOutOfRangeException

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ArrayPropertyValues.get_Item(String propertyName)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntryPropertyValues.SetValues(PropertyValues propertyValues)
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\ericd\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 22
```

## Example
The following code should reproduce the exception on the line `entry.OriginalValues.SetValues(dbValues);`.
Im using .NET 8.0 with EFCore 8.0.0 and VS Studio 17.8.3.
Before running the code, migrations have to be added (`Add-Migration Init`)

``` c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsoleApp2
{
    internal class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new CustomContext())
            {
                ctx.Database.Migrate();
                ctx.Add(new Supplier() { Name = "FooBar", Address = new() { Street = "WhereEver" } });
                ctx.SaveChanges();
            }

            using (var ctx = new CustomContext())
            {
                var entry = ctx.Entry(ctx.Suppliers.First());
                var dbValues = entry.GetDatabaseValues()!;
                entry.OriginalValues.SetValues(dbValues);
            }

            Console.WriteLine("Done!");
            Console.ReadLine();
        }
    }
}

public class CustomContext : DbContext
{
    public DbSet<Contact> Contacts { get; set; }
    public DbSet<Supplier> Suppliers { get; set; }
    public DbSet<Customer> Customers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder builder)
    {
        builder.LogTo(Console.WriteLine, new[] { RelationalEventId.CommandExecuting }).EnableSensitiveDataLogging();
        builder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=TestDb;Trusted_Connection=True");
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Contact>().HasDiscriminator(e => e.Discriminator);
    }
}

public abstract class Contact
{
    public int Id { get; set; }
    public string? Discriminator { get; set; }
    public required string Name { get; set; }
    public required Address Address { get; set; }
}

public class Supplier : Contact
{
    public string? Foo { get; set; }
}

public class Customer : Contact
{
    public string? Bar { get; set; }
}

[ComplexType]
public class Address
{
    public required string Street { get; set; }
}
```

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #32701
Fixes #31353

### CODE REVIEW

File: src/EFCore/Metadata/Internal/EntityTypeExtensions.cs [hunk 1]
```diff
@@ -309,7 +309,7 @@ public static bool IsStrictlyDerivedFrom(this EntityType entityType, IReadOnlyEn
     {
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/EntityTypeExtensions.cs:309]: Consider renaming this to `CheckContains`

**Review by AndriySvyryd — APPROVED** [review]
