### PR TITLE
Fix adding value-converted rowversion column

### LINKED ISSUE #22980: IsRowVersion and HasConversion<byte[]> produce incorrect migration
### Problem description

I have a property (named `RecordVersion`) of `ulong` type, on which I do `.IsRowVersion()`and use `.HasConversion<byte[]>()`. This is recommended way afaik to have a numeric type in model, but `rowversion` in database. When I create migration with `add-migration` in package manager console, invalid migration is generated.

In migration file (`20201011132803_Initial.cs`):

            migrationBuilder.CreateTable(
                name: "ProductCategories",
                schema: "Master",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    RecordVersion = table.Column<byte[]>(nullable: false),
                    // Other properties follow.....
                },

this is the line that is causing problems:

                    RecordVersion = table.Column<byte[]>(nullable: false),

While if I use `byte[]` type in model class and not use `.HasConversion<byte[]>()`, I get slightly different line:

                    RecordVersion = table.Column<byte[]>(rowVersion: true, nullable: false),

It is interesting, that in `MyContextModelSnapshot.cs`, the property is described correctly:

                    b.Property<byte[]>("RecordVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

### What this bug causes

It's also very interesting where this bug manifests itself. Due to missing `rowVersion: true` argument, I'm getting errors when I try to add index to that property! If I use the following for that same property:

    modelBuilder.Entity(entityType).HasIndex(propName).IsUnique();

I get this error: `Column 'RecordVersion' in table 'Master.ProductCategories' is of a type that is invalid for use as a key column in an index.`

### Code to repro

This is a little too convoluted for this example maybe, but I wanted to provide code as-is. Maybe it has something to do with the fact that I use abstract base class for my entities, or whatever.

This is entity:

    public abstract class MasterEntityVersioned : MasterEntity
    {
        [Rowver]
        public ulong RecordVersion { get; set; }
    }

In `OnModelCreating` I enumerate each property with `RowverAttribute` and do on them:

                            modelBuilder.Entity(entityType)
                                .Property(propName)
                                .HasConversion<byte[]>()
                                .IsRowVersion();

and:

                            modelBuilder.Entity(entityType).HasIndex(propName).IsUnique();

### Verbose output

This is the error I get after `update-database -verbose`:

```
Column 'RecordVersion' in table 'Master.ProductCategories' is of a type that is invalid for use as a key column in an index.
```

### Provider and version information

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Win 10 latest
IDE: Visual Studio 2019

### Other info

I think this might be somewhat related to #12434, but I decided to create separate issue, because the wording in there is not too clear for me, and also this particular case has maybe some interesting details (like it messes when you create index on that `rowversion`, but works otherwise).

### LINKED ISSUE #25997: SQL Server: cannot add value-converted timestamp column
Adding a ulong property that maps to a rowversion column via value conversion fails: `Defaults cannot be created on columns of data type timestamp.`. This is because for ulong properties, the column is non-nullable (unlike byte[] without the value converter), and so EF attempts to add a DEFAULT value.

It's perfectly fine to add non-nullable timestamp columns without a default, unlike other column types (the value is presumably calculated for all row when the column is added):

```sql
CREATE TABLE Data (Id INT);
INSERT INTO Data (Id) VALUES (1);
ALTER TABLE Data ADD Foo INT NOT NULL; -- Error, DEFAULT required on non-nullable column
ALTER TABLE Data ADD Foo TIMESTAMP NOT NULL; -- Works
```

### PR DESCRIPTION
**Pull request by roji**
Fixes #25997
Closes #22980

### CODE REVIEW

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 1]
```diff
@@ -1606,7 +1606,11 @@ protected override void Generate(UpdateDataOperation operation, IModel? model, M
 
             builder.Append(operation.IsNullable ? " NULL" : " NOT NULL");
 
-            DefaultValue(operation.DefaultValue, operation.DefaultValueSql, columnType, builder);
+            if (columnType != "rowversion")
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:1609]: Should be case-insensitive

**Review by AndriySvyryd — APPROVED** [review]

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 2]
```diff
@@ -1606,7 +1606,11 @@ protected override void Generate(UpdateDataOperation operation, IModel? model, M
 
             builder.Append(operation.IsNullable ? " NULL" : " NOT NULL");
 
-            DefaultValue(operation.DefaultValue, operation.DefaultValueSql, columnType, builder);
+            if (!string.Equals(columnType, "rowversion", StringComparison.OrdinalIgnoreCase))
```
Comment (ajcvickers) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:1609]: What if the column type is "timestamp" instead of "rowversion"? They are synonyms in T-SQL.

**Review by ajcvickers — APPROVED** [review]
