### PR TITLE
[release/8.0] Fix to #32911 - Incorrect apply projection for complex properties

### LINKED ISSUE #32911: Incorrect apply projection for complex properties
When I combine ComplexProperty and AsSplitQuery with properties mapped to column with equal names, I get wrong values when reading the complex properties. Their values are equal (but they are different instances). If I don't use the AsSplitQuery or rename the columns, the results are correct. See the snippet below.

The code is using Microsoft.EntityFrameworkCore.Sqlite 8.0.1 package.

```C#
#nullable enable

void Main()
{
	using (var ctx = new MyContext())
	{
		ctx.Database.EnsureDeleted();
		ctx.Database.EnsureCreated();
		ctx.Add(new Offer 
		{
			Variations = [
				new Variation {
					Payment = new Payment(120, 100),
					Nested = new NestedEntity
					{
						Payment = new Payment(12, 10),
					},
					Nested2 = new NestedEntity2
					{
						Payment = new Payment(24, 20),
					},
				}
			]
		});
		ctx.SaveChanges();
		ctx.ChangeTracker.Clear(); // If I don't clear the change tracker, it also works.
		
		var entity = ctx.Offers
			.Include(e => e.Variations!)
				.ThenInclude(v => v.Nested)
			.Include(e => e.Variations!)
				.ThenInclude(v => v.Nested2)
			.AsSplitQuery() // If I comment this out, it works
			.Single(e => e.Id == 1);
		
		//  The values are equal even when they shouldn't be.
		Console.WriteLine($"Entity {entity.Variations?.Single().Payment}");
		Console.WriteLine($"Nested Entity {entity.Variations?.Single().Nested?.Payment}");
		Console.WriteLine($"Nested Entity2 {entity.Variations?.Single().Nested2?.Payment}");
	}
}

public class MyContext : DbContext
{
	public DbSet<Offer> Offers => Set<Offer>();
	
	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
	    optionsBuilder.UseSqlite("DataSource=Test.db");
	}
	
	protected override void OnModelCreating(ModelBuilder builder)
	{
		builder.Entity<Variation>().ComplexProperty(p => p.Payment, price =>
		{
		    price.Property(p => p.Netto).HasColumnName("payment_netto"); // If I change the column name to a different than the others, it also works
		    price.Property(p => p.Brutto).HasColumnName("payment_brutto");
		});
		builder.Entity<NestedEntity>().ComplexProperty(p => p.Payment, price =>
		{
		    price.Property(p => p.Netto).HasColumnName("payment_netto");
		    price.Property(p => p.Brutto).HasColumnName("payment_brutto");
		});
		builder.Entity<NestedEntity2>().ComplexProperty(p => p.Payment, price =>
		{
		    price.Property(p => p.Netto).HasColumnName("payment_netto");
		    price.Property(p => p.Brutto).HasColumnName("payment_brutto");
		});
	}
}

public abstract class EntityBase 
{
	[System.ComponentModel.DataAnnotations.Key]
	public int Id {get; set; }
}

public class Offer : EntityBase
{	
	public ICollection<Variation>? Variations { get; set; }
}

public class Variation : EntityBase
{
	public Payment Payment {get; set; } = new Payment(0, 0);

	public NestedEntity? Nested {get; set; }
	public NestedEntity2? Nested2 {get; set; }
}

public class NestedEntity : EntityBase
{
	public Payment Payment {get; set; } = new Payment(0, 0);
}

public class NestedEntity2 : EntityBase
{
	public Payment Payment {get; set; } = new Payment(0, 0);
}

public record Payment(decimal Netto, decimal Brutto);
```

### Include provider and version information

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.Sqlite 8.0.1
Target framework: .NET 8.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.8.5

### PR DESCRIPTION
**Pull request by maumar**
Port of https://github.com/dotnet/efcore/pull/33020 and https://github.com/dotnet/efcore/pull/33200
Fixes https://github.com/dotnet/efcore/issues/32911

**Description**

Some context:
pushdown is process we do during query translation, where a query itself becomes a source of another query above. 

```sql
SELECT c.Id, c.Name
FROM Customers AS c
WHERE c.Name = 'John'
```

becomes

```sql
SELECT subquery.Name
FROM (
    SELECT c.Id, c.Name
    FROM Customers AS c
    WHERE c.Name = 'John') AS subquery
```

We need to do this for various operations like Skip/Take/Distinct. Lifting projection is the process of extracting elements in the SELECT from the inner query (`SELECT c.Id, c.Name`) to the outer (`SELECT subquery.Name`). 

Applying projection is the process of actually populating SELECT with the column values. Initially we generate empty projection (SELECT 1) and try to populate values as late as possible - so we avoid populating with columns that are not needed in the final result.

Problem was that when we lift structural type projection during pushdown, if that projection contains complex types with the same column names (e.g. cross join of same entities - it's perfectly fine to do in a vacuum, we just alias the columns whose names are repeated) we would lift the projection incorrectly. What we do is go through all the properties, apply the corresponding columns to the `selectExpression` if needed and generate `StructuralTypeProjection` object if the projection needs to be applied one level up. For complex types we would generate a shaper expression and then run it through the same process, BUT the nested complex properties would be added to a flat structure along with the primitive properties, rather than in separate cache dedicated for complex property shapers. This was wrong and not what we expected to see, when processing this structure one level up (i.e. when applying projection to the outer select)

```sql
SELECT [applying_this_projection_was_wrong]
FROM
(
    SELECT c.Id, c.Name, c.ComplexProp, o.ComplexProp as ComplexProp0
    FROM Customers as c
    JOIN Orders as o ON ...
) as s
```

i.e. applying projection once worked fine, but doing it second time did not. The reason why is that we expected to see information about the complex type shape in the complex property shaper cache, rather than flat structure for primitives, but it wasn't there. So we assumed this is the first time we the projection is being applied, so we conjure up the complex type shaper based on table alias and `IColumn` metadata. This results in a situation, where complex property that was aliased is never picked. So we end up with:

```sql
SELECT s.Id, s.Name, s.ComplexProp -- we would also try to add s.ComplexProp again, instead of s.ComplexProp0 but of course we don't add same thing twice FROM
(
    SELECT c.Id, c.Name, c.ComplexProp, o.ComplexProp as ComplexProp0
    FROM Customers as c
    JOIN Orders as o ON ...
) as s
```
This leads to bad data - two different objects with distinct data in them are mapped to the same column in the database.

Fix is to properly build a complex type shaper structure when applying projection instead, so the structure we generate matches expectations. 

Also modified `VisitChildren` and `MakeNullable` methods on `StructuralTypeProjectionExpression` to process/preserve complex type cache information, which was previously gobbled up/ignored.

**Customer impact**
Customers using new "complex types" feature in their queries can be affected by data corruption in several different scenarios. The bug involves two or more complex types with the same structure and the query must be nested. For general case, there is no good workaround, apart from significantly rewriting the query. However some scenarios can be worked-around by slightly altering the model (renaming columns on the complex types so that they differ). Multiple customers were hit by this problem.

"Please consider backporting the fix as this bug is a showstopper for our large, long-standing LOB application. This is the last issue related to our EF6 -> EF Core port."

**How found**
Multiple customer reports on 8.

**Regression**
No, complex type support is a new feature in EF Core 8.

**Testing**
Extensive tests added.

**Risk**
Medium. This fix is definitely riskier than what we usually try to patch for EF queries. There was a design flaw in how we processed complex types, so the design had to be altered. Fix is isolated to scenarios involving complex types. When no complex types are present the code behaves exactly the same as before. However, majority of complex types scenarios are going through the new code path and potentially could be affected by unintended consequences. Added quirk as extra precaution.

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -2706,17 +2708,91 @@ private void ApplySetOperation(SetOperationType setOperationType, SelectExpressi
...
+                ProcessStructuralType(projection1, projection2);
 
-            void ProcessStructuralType(
-                StructuralTypeProjectionExpression nestedProjection1,
-                StructuralTypeProjectionExpression nestedProjection2)
+                void ProcessStructuralType(
+                    StructuralTypeProjectionExpression nestedProjection1,
+                    StructuralTypeProjectionExpression nestedProjection2)
+                {
+                    ProcessPrimitiveProperties(
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2721]: I went with the (somewhat artificial) DRY approach, but not sure if we should just have old and new code paths side by side. Thoughts? @roji @ajcvickers @AndriySvyryd

**Comment by AndriySvyryd** [comment]
Add back the examples from the description in https://github.com/dotnet/efcore/pull/33020 and try to make the description more readable, even if it's longer

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2721]: Either is fine IMO

**Review by AndriySvyryd — APPROVED** [review]

**Review by roji — APPROVED** [review]

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 1 above)
Comment (roji) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2721]: I usually lean to keeping patches simple (so more side-by-side), but this looks fine to me to.
