### PR TITLE
[release/8.0] Fix to #32235 - Buffering error in JSON deserialization with junk data

### LINKED ISSUE #32194: JSON materialization code should be resilient to incorrect JSON documents
[This JSON materialization code](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ClientMethods.cs#L939) needs to be made resilient to malformed JSON content. In general, when reading JSON tokens, we should be defensive and immediately throw for any unexpected token. We should also do a pass over other JSON processing code (especially anything with flow control/loops) and ensure that it's resilient.

Note: this was discovered while porting JSON owned entity support to PostgreSQL (test JsonQueryAdHocTestBase.Junk_in_json_basic_no_tracking). At this point I'm still investigating what caused the incorrect JSON document, but we should be resilient to this in any case.

### LINKED ISSUE #32235: Buffering error in JSON deserialization with junk data
I dug into the root cause of #32194 and I think I identified it; tl;dr, we ignore the return value of [TrySkip](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs#L1842) for unknown (junk) properties; if the buffering happens to cut an unknown property in the middle, we end up in a bad state.

To reproduce this with SQL Server, go to JsonQueryAdHocSqlServerTest, and replace SeekJunkInJson with the following:

```c#
    protected override void SeedJunkInJson(MyContextJunkInJson ctx)
        => ctx.Database.ExecuteSqlRaw(
            """
INSERT INTO [Entities] ([Collection], [CollectionWithCtor], [Reference], [ReferenceWithCtor], [Id])
VALUES(
N'[{{"JunkReference":{{"Something":"SomeValue" }},"Name":"c11","JunkProperty1":50,"Number":11.5,"JunkCollection1":[],"JunkCollection2":[{{"Foo":"junk value"}}],"NestedCollection":[{{"DoB":"2002-04-01T00:00:00","DummyProp":"Dummy value"}},{{"DoB":"2002-04-02T00:00:00","DummyReference":{{"Foo":5}}}}],"NestedReference":{{"DoB":"2002-03-01T00:00:00"}}}},{{"Name":"c12","Number":12.5,"NestedCollection":[{{"DoB":"2002-06-01T00:00:00"}},{{"DoB":"2002-06-02T00:00:00"}}],"NestedDummy":59,"NestedReference":{{"DoB":"2002-05-01T00:00:00"}}}}]',
N'[{{"MyBool":true,"Name":"c11 ctor","JunkReference":{{"Something":"SomeValue","JunkCollection":[{{"Foo":"junk value"}}]}},"NestedCollection":[{{"DoB":"2002-08-01T00:00:00"}},{{"DoB":"2002-08-02T00:00:00"}}],"NestedReference":{{"DoB":"2002-07-01T00:00:00"}}}},{{"MyBool":false,"Name":"c12 ctor","NestedCollection":[{{"DoB":"2002-10-01T00:00:00"}},{{"DoB":"2002-10-02T00:00:00"}}],"JunkCollection":[{{"Foo":"junk value"}}],"NestedReference":{{"DoB":"2002-09-01T00:00:00"}}}}]',
N'{{"Name": "r1", "Number": 1.5, "JunkReference":{{"Something": "SomeValue" }}, "JunkCollection": [{{"Foo": "junk value"}}], "NestedReference": {{"DoB": "2000-01-01T00:00:00"}}, "NestedCollection": [{{"DoB": "2000-02-01T00:00:00", "JunkReference": {{"Something": "SomeValue"}}}}, {{"DoB": "2000-02-02T00:00:00"}}]}}',
N'{{"MyBool":true,"JunkCollection":[{{"Foo":"junk value"}}],"Name":"r1 ctor","JunkReference":{{"Something":"SomeValue" }},"NestedCollection":[{{"DoB":"2001-02-01T00:00:00"}},{{"DoB":"2001-02-02T00:00:00"}}],"NestedReference":{{"JunkCollection":[{{"Foo":"junk value"}}],"DoB":"2001-01-01T00:00:00"}}}}',
1)
""");
```

The difference is in the 3rd row being inserted: the ordering is different and spaces have been added; this matches exactly the output that comes back on PostgreSQL, where the JSON data is saved in jsonb (not as text), and therefore a different representation gets returned. On this change is made, running the test Junk_in_json_basic_no_tracking triggers #32194, causing "malformed JSON" to be processed.

When the test reaches MaterializeJsonEntityCollection, the JsonReaderData contains the following: `{"DoB": "2000-02-01T00:00:00", "JunkReference": {"Something": "Som`. Note that the JunkReference data is cut off because of buffering; this is crucial to reproducing the bug (in the original SQL Server data, the entire thing is buffered and the bug does not occur).

Looking at the actual shaper, we have the following code for parsing out the MyJsonEntityJunkInJsonNested in the collection:

```
tokenType = jsonReaderManager.CurrentReader.TokenType;
Loop(Break: done Continue: )
{
	{
		tokenType = jsonReaderManager.MoveNext();
		switch (tokenType)
		{
			case PropertyName: 
				jsonReaderManager.CurrentReader.ValueTextEquals(DoB.EncodedUtf8Bytes) ? 
				{
					jsonReaderManager.MoveNext();
					namelessParameter{2} = ExpressionExtensions.ValueBufferTryReadValue<DateTime>(
						valueBuffer: materializationContext3.get_ValueBuffer(), 
						index: 3, 
						property: Property: MyEntityJunkInJson.Collection#MyJsonEntityJunkInJson.NestedCollection#MyJsonEntityJunkInJsonNested.DoB (DateTime) Required);
				} : default(void)
			case EndObject: 
				Goto(break done)
			default: 
				{
					jsonReaderManager.CurrentReader.TrySkip();
				}
		}
	}}
```

When get a property, if it's the expected `DoB` property it gets assigned; otherwise, if it's an unknown property, we simply do nothing (this is the case with JunkReference). At this point we continue to the next token, which is a StartObject, and go into the default case. We call TrySkip() **but we ignore its return value**; if the value isn't fully buffered (as in this case), the skip silently fails.

We continue looping - through the JunkReference's internal tokens, until we get to the EndObject of the **inner** JunkReference and return - but we haven't consumed the EndObject of the **outer** object itself (MyJsonEntityJunkInJsonNested). So back in MaterializeJsonEntityCollection, we do MoveNext and get the containing object's EndObject, which for our logic is malformed JSON, and we fail.

/cc @maumar @ajcvickers

### PR DESCRIPTION
**Pull request by maumar**
Fixes #32235
Fixes #32194

**Description**
When skipping unmapped json property make sure we skip it correctly (i.e. entire property is in the buffer), otherwise expand the buffer, read more and try again. Also, when materializing json collections, throw when unexpected token is encountered.

**Customer impact**
This can cause bugs when materializing entities mapped to JSON, if the JSON contains unmapped properties (junk data). Because we incorrectly skip those in some cases, we may end up in invalid state when streaming the results.

**How found**
Found by EF Core team member when implementing support for postgres.

**Regression**
Yes.

**Testing**
Added tests.

**Risk**
Low: we use the same mechanism for skipping as we do for regular reads and that works without issue. Also improved robustness of the code in other places, by throwing exceptions if somehow we end up in bad state regardless. Added quirk just in case.

### CODE REVIEW

File: src/EFCore/Storage/Json/Utf8JsonReaderManager.cs [hunk 1]
```diff
@@ -55,6 +55,18 @@ public JsonTokenType MoveNext()
         return CurrentReader.TokenType;
     }
 
+    /// <summary>
+    ///     Skip the children of the current JSON token, which may involve reading more data from the stream and creating a new <see cref="Utf8JsonReader " />
+    ///     instance in <see cref="CurrentReader" />.
+    /// </summary>
+    public void Skip()
```
Comment (maumar) [inline src/EFCore/Storage/Json/Utf8JsonReaderManager.cs:62]: ok to add this API or should I hack it in the expression tree directly?

Comment (roji) [reply src/EFCore/Storage/Json/Utf8JsonReaderManager.cs:62]: This makes sense to me as-is, aligns well with MoveNext which is already there on Utf8JsonReaderManager

**Review by roji — COMMENTED** [review]
The below looks OK to me, but I'll let @ajcvickers approve as he's more familiar with this area.

But looking at JsonCollectionReaderWriter.FromTypedJson the loop there looks like it also needs patching. For example, if an unexpected nested array (or object) is found in the middle of the JSON array, it seems like we'd just go inside and start adding its own elements. Ideally we should always have a default case for this kind of switch, etc.

**Comment by ajcvickers** [comment]
@maumar @roji I added tests and fixes for the collection reader/writer. I think this is good to go to Tactics now.

File: src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs [hunk 2]
```diff
@@ -46,11 +46,24 @@ public JsonCollectionReaderWriter(JsonValueReaderWriter<TElement> elementReaderW
             collection.Clear();
         }
 
-        while (manager.CurrentReader.TokenType != JsonTokenType.EndArray)
+        if (manager.CurrentReader.TokenType == JsonTokenType.None)
```
Comment (roji) [inline src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs:49]: I don't have context and am probably missing something, but... Does this mean that it's "unclear" whether FromJsonTyped is called with the manager already being on a token or not? Shouldn't this be a clear contract of FromJsonTyped, where MoveNext is either always called before calling FromJsonTyped, or never?

File: src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs [hunk 3]
```diff
@@ -61,6 +74,16 @@ public JsonCollectionReaderWriter(JsonValueReaderWriter<TElement> elementReaderW
...
                     collection.Add(default);
                     break;
+                case JsonTokenType.None:
+                case JsonTokenType.StartObject:
+                case JsonTokenType.EndObject:
+                case JsonTokenType.StartArray:
+                case JsonTokenType.PropertyName:
+                    throw new InvalidOperationException(
+                        CoreStrings.JsonReaderInvalidTokenType(tokenType.ToString()));
+                case JsonTokenType.Comment:
```
Comment (roji) [inline src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs:84]: Consider inversing this, i.e. have the default case throw (allowing us to not specify all the unsupported cases explicitly), and specifically do continue for comment. It's very unlikely that a JsonTokenType will be added in the future, but this would make it clearer exactly what is supported (and what isn't - default case - throws). For example, looking at the code I'm not sure if there are other token types for which we skip (like comment).

File: src/EFCore/Storage/Json/JsonNullableStructCollectionReaderWriter.cs [hunk 4]
```diff
@@ -62,6 +75,16 @@ public JsonNullableStructCollectionReaderWriter(JsonValueReaderWriter<TElement>
                 case JsonTokenType.Null:
                     collection.Add(null);
                     break;
+                case JsonTokenType.None:
+                case JsonTokenType.StartObject:
```
Comment (roji) [inline src/EFCore/Storage/Json/JsonNullableStructCollectionReaderWriter.cs:79]: Just noting that this makes it impossible to encode a scalar as e.g. an object or array, although this may be a legitimate representation. For example, it may make sense for a geometry point representation to be an array containing `[X,Y]`, or for some other complex thing to have an object representation.

In practice, we're probably unlikely to do this, since the JSON representation **usually** needs to be convertible to a relational value (when extracting a value and e.g. comparing it against something), and such a nice, structured JSON representation is unlikely to be convertible (though may it is in some cases?).

But I'm still not sure this is something that the collection reader/writer should block: if we just called into _elementReaderWriter.FromJsonTyped with StartObject, wouldn't that throw anyway if the reader expects something else (e.g. a string or int)?

**Review by roji — APPROVED** [review]
Looks OK from my end but see some comments.

File: test/EFCore.Specification.Tests/BadDataJsonDeserializationTestBase.cs [hunk 5]
```diff
@@ -0,0 +1,201 @@
...
+    {
+        public Point? Point { get; set; }
+    }
+
+    [ConditionalTheory]
+    [InlineData("""{"Prop":[-128,[0,127]]}""")]
+    [InlineData("""{"Prop":[-128,{"P":127}]}""")]
+    [InlineData("""{"Prop":[-128,],23]}""")]
+    [InlineData("""{"Prop":[-128,},23]}""")]
+    [InlineData("""{"Prop":[-128,,23]}""")]
```
Comment (maumar) [inline test/EFCore.Specification.Tests/BadDataJsonDeserializationTestBase.cs:65]: dupe

File: test/EFCore.Specification.Tests/BadDataJsonDeserializationTestBase.cs [hunk 6]
```diff
@@ -0,0 +1,201 @@
...
+    {
+        public sbyte[] Int8 { get; set; } = null!;
+    }
+
+    [ConditionalTheory]
+    [InlineData("""{"Prop":[-128,[0,127]]}""")]
+    [InlineData("""{"Prop":[-128,{"P":127}]}""")]
+    [InlineData("""{"Prop":[-128,],23]}""")]
+    [InlineData("""{"Prop":[-128,},23]}""")]
+    [InlineData("""{"Prop":[-128,,23]}""")]
```
Comment (maumar) [inline test/EFCore.Specification.Tests/BadDataJsonDeserializationTestBase.cs:83]: dupe

File: test/EFCore.Specification.Tests/BadDataJsonDeserializationTestBase.cs [hunk 7]
```diff
@@ -0,0 +1,201 @@
...
+    [InlineData("""{"Prop":[-128,,23]}""")]
+    public virtual void Throws_for_bad_collection_of_sbyte_JSON_values(string json)
```
Comment (maumar) [inline test/EFCore.Specification.Tests/BadDataJsonDeserializationTestBase.cs:67]: note that `[InlineData("""{"Prop":[-128,23],34]}""")]` doesn't throw. But that's something we can address in 9

File: src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs (hunk 2 above)
Comment (maumar) [inline src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs:49]: quirks are missing in the json reader/writer parts

Comment (ajcvickers) [reply src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs:49]: Yes, I will file a bug on this. The path for handling arrays created by query goes down one thing, while other code does anther.

File: src/EFCore/Storage/Json/JsonNullableStructCollectionReaderWriter.cs (hunk 4 above)
Comment (ajcvickers) [reply src/EFCore/Storage/Json/JsonNullableStructCollectionReaderWriter.cs:79]: This isn't supported right now without writing a different collection reader/writer, but I think we could make it work in the future. I'll file an issue.

File: test/EFCore.Specification.Tests/BadDataJsonDeserializationTestBase.cs (hunk 7 above)
Comment (ajcvickers) [reply test/EFCore.Specification.Tests/BadDataJsonDeserializationTestBase.cs:67]: This will throw higher up in the stack because an unexpected token will be found after the collection deserialization has happened.

File: src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs (hunk 2 above)
Comment (ajcvickers) [reply src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs]: @roji Looks like you already filed this here: https://github.com/dotnet/efcore/issues/32269 :-)
