### PR TITLE
[5.0.1] Fix issues with property called FooId on base type Foo in TPT

### LINKED ISSUE #23092: Fails to map property in Table-per-Type inheritance
## File a bug

Fails to map property in Table-per-Type inheritance (SQL Server provider)

```
System.InvalidOperationException: "The property 'ObjectId' on entity type 'EntityType: Object Abstract' is not mapped to the table 'Car'."
```
I think it is about the conventions. The type being named ```Object``` and assuming ``ObjectId```is a primary key that should be in the derived types table.

When I remove ```ObjectId``` everything works just fine.

I explored potential workarounds but not even renaming the column in the database an adding ```Column``` handles the problem. It still complains about not being able to map the property ```ObjectId``` to Car.

```c#
        [Column("ObjId")] // Still fails
        public int? ObjectId { get; set; }
```

### Code

```C#
    [Table("Object")]
    public abstract class Object
    {
        [Key]
        public int Id { get; set; }

        public int? ObjectId { get; set; }
    }

    [Table("Car")]
    public partial class Car : Models.Object
    {
        [StringLength(15)]
        public string Registry { get; set; }
    }
```

### Stack traces

```
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.FindSharedObjectRootProperty(IProperty property, StoreObjectIdentifier& storeObject)
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.FindSharedStoreObjectRootProperty(IProperty property, StoreObjectIdentifier& storeObject)
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.IsColumnNullable(IProperty property, StoreObjectIdentifier& storeObject)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.SqlServerIndexConvention.<>c__DisplayClass12_0.<CreateIndexFilter>b__0(IProperty property)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.SqlServerIndexConvention.CreateIndexFilter(IIndex index)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.SqlServerIndexConvention.SetIndexFilter(IConventionIndexBuilder indexBuilder, Boolean columnNameChanged)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.SqlServerIndexConvention.ProcessIndexAdded(IConventionIndexBuilder indexBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnIndexAdded(IConventionIndexBuilder indexBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnIndexAddedNode.Run(ConventionDispatcher dispatcher)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.DelayedConventionScope.Run(ConventionDispatcher dispatcher)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalizing(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IAsyncEnumerable<TEntity>.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.DataService.<Do>d__3.MoveNext() in X:\Nordengren\Yrsa\Support\ConsoleApp1\DataService.cs:line 38
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApp1.DataService.<StartAsync>d__2.MoveNext() in X:\Nordengren\Yrsa\Support\ConsoleApp1\DataService.cs:line 32
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApp1.Program.<Main>d__0.MoveNext() in X:\<Project>\ConsoleApp1\Program.cs:line 36
```

### Provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0 RC2
Operating system:
IDE: Visual Studio 2019 16.3

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #23092

**Description**

The fix does the following:
- Don't discover FK properties for an identifying FK created by convention
- Silently ignore inherited properties in TPT in `SqlServerIndexConvention` instead of throwing an exception

**Customer Impact**

Currently when there's property with name in form of *Foo*Id on base type named *Foo* in a TPT hierarchy an exception is thrown when a convention is applied. The workaround is non-obvious and might not work when there are multiple types with this pattern.

**How found**

Reported by user on RC2

**Test coverage**

This PR includes tests for the affected scenario.

**Regression?**

No, this only affects TPT - a new feature in 5.0

**Risk**

Low. The fix only affects models using TPT.

### CODE REVIEW

**Comment by ajcvickers** [comment]
@dotnet/efteam In the past we would have quirked this for safety. Should we continue to do that by default going forward?

**Comment by AndriySvyryd** [comment]
@ajcvickers Yes, but I want to do it in a separate commit to make the merging to main easier

File: src/EFCore.SqlServer/Metadata/Conventions/SqlServerIndexConvention.cs [hunk 1]
```diff
@@ -154,7 +155,7 @@ private IConventionIndexBuilder SetIndexFilter(IConventionIndexBuilder indexBuil
             var index = indexBuilder.Metadata;
             if (index.IsUnique
                 && index.IsClustered() != true
-                && index.Properties.Any(property => property.IsColumnNullable()))
+                && GetNullableColumns(index)?.Any() == true)
```
Comment (smitpatel) [inline src/EFCore.SqlServer/Metadata/Conventions/SqlServerIndexConvention.cs:159]: Reusing this computed value of GetNullableColumns in CreateIndexFilter could be useful.

File: src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs [hunk 2]
```diff
@@ -130,7 +130,13 @@ public ForeignKeyPropertyDiscoveryConvention([NotNull] ProviderConventionSetBuil
             IConventionContext context)
         {
             var foreignKey = relationshipBuilder.Metadata;
-            if (!ConfigurationSource.Convention.Overrides(foreignKey.GetPropertiesConfigurationSource()))
+            var foreignKeyProperties = FindCandidateForeignKeyProperties(relationshipBuilder.Metadata, onDependent: true);
+            var propertiesConfigurationSource = foreignKey.GetPropertiesConfigurationSource();
+            if (!ConfigurationSource.Convention.OverridesStrictly(propertiesConfigurationSource)
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs:137]: Refreshing my understanding here
Convention would not override DataAnnotation/Explicit
Convention would not override strictly Convention/DataAnnotation/Explicit 
The later implies that propertiesConfigurationSource should be null?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs:137]: Yes, but I didn't want to use `propertiesConfigurationSource != null` here in case we introduce [`Default` configuration source ](https://github.com/dotnet/efcore/issues/9329)

Comment (smitpatel) [reply src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs:137]: Next question since this condition would check that propertiesConfigurationSource is not Convention then next condition checks it again? Wouldn't that be always true?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs:137]: The next condition is still necessary as the first condition is `true` when `propertiesConfigurationSource` is `Convention`, `DataAnnotation` or `Explicit`.

**Review by smitpatel — APPROVED** [review]

**Comment by ajcvickers** [comment]
Approved by Tactics for 5.0.1.
