### PR TITLE
Fix for 20014. KeyAttribute does not override Keyless. Log warning.

### LINKED ISSUE #20014: Log a warning when KeyAttribute overrides KeylessAttribute

### PR DESCRIPTION
**Pull request by lajones**
Fixes #20014. KeyAttribute no longer overrides Keyless. And we log a warning if we see the situation.

### CODE REVIEW

**Comment by lajones** [comment]
Note: includes @smitpatel 's work from [this commit](https://github.com/dotnet/efcore/commit/5305551daa47d376c1082b4e9cdcb9badcb02639)

File: src/EFCore/Diagnostics/CoreEventId.cs [hunk 1]
```diff
@@ -615,6 +616,21 @@ private enum Id
         /// </summary>
         public static readonly EventId RedundantForeignKeyWarning = MakeModelValidationId(Id.RedundantForeignKeyWarning);
 
+        /// <summary>
+        ///     <para>
+        ///         The IsKeyless setting on the entity type is conflicting with
+        ///         an attempt to set a key on at least one of its properties.
+        ///     </para>
+        ///     <para>
+        ///         This event is in the <see cref="DbLoggerCategory.Model.Validation" /> category.
```
Comment (smitpatel) [inline src/EFCore/Diagnostics/CoreEventId.cs]: It is not model validation warning.

File: src/EFCore/Diagnostics/CoreEventId.cs [hunk 2]
```diff
@@ -615,6 +616,21 @@ private enum Id
         /// </summary>
         public static readonly EventId RedundantForeignKeyWarning = MakeModelValidationId(Id.RedundantForeignKeyWarning);
 
+        /// <summary>
+        ///     <para>
+        ///         The IsKeyless setting on the entity type is conflicting with
```
Comment (smitpatel) [inline src/EFCore/Diagnostics/CoreEventId.cs]: Error message should be more informative and connected to user. Like Entity is marked as KeyLess so ignoring KeyAttribute on property.

File: src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs [hunk 3]
```diff
@@ -42,6 +42,15 @@ public KeyAttributeConvention([NotNull] ProviderConventionSetBuilderDependencies
             IConventionContext context)
         {
             var entityType = propertyBuilder.Metadata.DeclaringEntityType;
+            if (entityType.IsKeyless
+                && entityType.GetIsKeylessConfigurationSource()
+                    .Overrides(ConfigurationSource.DataAnnotation))
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs]: Think about what should be logged message if entity is explicitly marked as keyless rather than data annotation. Both could warn differently to make it easier for user to understand the error.

Comment (lajones) [reply src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs]: Had a chat with @ajcvickers about this morning. We discussed:

1. marked as `HasNoKey` using fluent API, and (either later or earlier) marked as having a key using the `HasKey()` fluent API
2. marked as `Keyless` using data annotation and marked as having a key using the `HasKey()` fluent API
3. marked as `HasNoKey` using fluent API, and there's a `Key` data annotation
4. marked as `Keyless` using data annotation, and there's a `Key` data annotation

Situation 1: whichever fluent API is last wins and no warning (as for other fluent API).
Situation 2: the fluent API overrides the annotation - no warning and entity ends up with a key.
Situation 3: again the fluent API should win, no warning because fluent API always wins and the entity ends up with no key
Situation 4: log the warning, the `Keyless` attribute wins so the entity ends up with no key.

I need to update the PR to encode Situation 3. Let us know if you disagree.

File: src/EFCore/Diagnostics/CoreEventId.cs (hunk 2 above)
Comment (lajones) [reply src/EFCore/Diagnostics/CoreEventId.cs]: I'll update.

File: src/EFCore/Diagnostics/CoreEventId.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore/Diagnostics/CoreEventId.cs]: @AndriySvyryd knows best.

Comment (AndriySvyryd) [reply src/EFCore/Diagnostics/CoreEventId.cs]: It could be either, but we only use ModelValidation for warning that come directly from the ModelValidator

File: src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs (hunk 3 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs]: Note: it turns out that Situation 1 is not "last wins". We already throw an `InvalidOperationException` if either of these cases occurs. I'm not planning to change that.

File: src/EFCore/Diagnostics/CoreEventId.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Diagnostics/CoreEventId.cs]: Updated to use Model.

File: src/EFCore/Diagnostics/CoreEventId.cs (hunk 2 above)
Comment (lajones) [reply src/EFCore/Diagnostics/CoreEventId.cs]: Done

File: src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs (hunk 3 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs]: Done with the 2nd commit.

File: src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs [hunk 4]
```diff
@@ -42,6 +42,14 @@ public KeyAttributeConvention([NotNull] ProviderConventionSetBuilderDependencies
             IConventionContext context)
         {
             var entityType = propertyBuilder.Metadata.DeclaringEntityType;
+            if (entityType.IsKeyless
+                && ConfigurationSource.DataAnnotation == entityType.GetIsKeylessConfigurationSource())
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs]: If `GetIsKeylessConfigurationSource` is `Explicit` you can return without warning.

File: src/EFCore/Diagnostics/CoreEventId.cs [hunk 5]
```diff
@@ -102,6 +102,7 @@ private enum Id
             RequiredAttributeInverted,
             RequiredAttributeOnCollection,
             CollectionWithoutComparer,
+            ConflictingKeylessAndKeyConfigurationWarning,
```
Comment (smitpatel) [inline src/EFCore/Diagnostics/CoreEventId.cs]: Should use Attribute in the name.

File: src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs (hunk 4 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs]: Updated

File: src/EFCore/Diagnostics/CoreEventId.cs (hunk 5 above)
Comment (lajones) [reply src/EFCore/Diagnostics/CoreEventId.cs]: Updated
