### PR TITLE
Reuse some IExecutionStrategy instances.

### LINKED ISSUE #21350: Reuse ExecutionStrategy instance
It can be stored in the `DbContext`

### LINKED ISSUE #21463: GraphUpdatesSqlServerTest does not use retrying execution strategy
See https://github.com/dotnet/efcore/issues/21441

### LINKED ISSUE #23019: ExecutionStrategy.ShouldRetryOn receives a null argument with concurrency exceptions
The `ExecutionStrategy` base class automatically unwraps EF exceptions before passing them to the `ShouldRetryOn` method. The method which does the unwrapping, `CallOnWrappedException`, seems to [directly recurse](https://github.com/dotnet/efcore/blob/19a65f2/src/EFCore/Storage/ExecutionStrategy.cs#L394) on the `InnerException` property of the parent exception without checking whether it is non-null. 

This is not an issue if all instances of `DbUpdateException` have a non-null `InnerException`, but it seems that `DbUpdateConcurrencyException` exceptions thrown by the SQL Server and Sqlite providers don't include one. This causes such exceptions to be undetectable from the `ShouldRetryOn` method, when deriving from the `ExecutionStrategy` base class. 

As this violates the `[NotNull]` attribute from the method's signature, this looks like a bug either with that method, or with the `DbUpdateConcurrencyException` type which doesn't have an `InnerException`.

<details>
<summary>Code to Reproduce</summary>

```C#
// DB Model
class User
{
    public int ID { get; set; }

    [ConcurrencyCheck]
    public string Email { get; set; }
}

class MyDbContext : DbContext
{
    public DbSet<User> Users { get; set; }

    public MyDbContext(DbContextOptions options)
        : base(options)
    {

    }
}

// Custom ExecutionStrategy
class CustomExecutionStrategy : ExecutionStrategy
{
    public CustomExecutionStrategy(DbContext context, int maxRetryCount, TimeSpan maxRetryDelay)
        : base(context, maxRetryCount, maxRetryDelay)
    { }

    protected override bool ShouldRetryOn(Exception exception)
    {
        if (exception == null)
            throw new Exception("Unexpected null exception");

        return exception is DbUpdateConcurrencyException;
    }
}

// NUnit test class

[TestFixture]
class ExecutionStrategyTests2
{

    DbContextOptions dbOptions;

    [SetUp]
    public void init()
    {
        // reuse same connection & db options as we want a single in-memory DB
        var connection = new SqliteConnection("DataSource=:memory:");
        connection.Open();

        dbOptions = new DbContextOptionsBuilder()
            .UseSqlite(connection)
            .UseLoggerFactory(LoggerFactory.Create(builder => builder.AddQueryDebug()))
            .EnableSensitiveDataLogging(true)
            .Options;

        // init DB and insert a single user
        var tempContext = new MyDbContext(dbOptions);
        tempContext.Database.EnsureCreated();

        tempContext.Set<User>().Add(new User
        {
            Email = "test@example.com",
        });
        tempContext.SaveChanges();
    }

    [Test]
    public void CustomExecutionStrategy_CatchesConcurrencyException()
    {
        var contextA = new MyDbContext(dbOptions);
        var strategy = new CustomExecutionStrategy(contextA, 3, TimeSpan.FromSeconds(5));
        var attemptsMade = 0;

        strategy.Execute(() =>
        {
            var entity = contextA.Set<User>().Single();

            // simulate a concurrency exception on first attempt only
            if (attemptsMade == 0)
            {
                var contextB = new MyDbContext(dbOptions);
                contextB.Set<User>().Single().Email = "second@example.com";
                contextB.SaveChanges();
            }
            attemptsMade++;

            entity.Email = "first@example.com";
            contextA.SaveChanges();
        });

        var tempContext = new MyDbContext(dbOptions);
        var entity5 = tempContext.Set<User>().Single();
    }
}
```
</details>

<details>
<summary>Results</summary>

```
Message: 
    System.Exception : Unexpected null exception
Stack Trace: 
    CustomExecutionStrategy.ShouldRetryOn(Exception exception) line 52
    ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
    ExecutionStrategyExtensions.Execute(IExecutionStrategy strategy, Action operation)
    ExecutionStrategyTests2.CustomExecutionStrategy_CatchesConcurrencyException() line 95
```
</details> 

EF Core version: 3.1.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 4.6.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.7

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Don't pass `null` to `ExecutionStrategy.ShouldRetryOn`.
Use the currently executing execution strategy to determine whether buffering is needed.

Fixes #21350
Fixes #23019
Fixes #21463

### CODE REVIEW

File: src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs [hunk 1]
```diff
@@ -165,8 +165,9 @@ public bool MoveNext()
                     {
                         if (_dataReader == null)
                         {
-                            _relationalQueryContext.ExecutionStrategyFactory.Create()
-                                .Execute(this, static (_, enumerator) => InitializeReader(enumerator), null);
+                            var executionStrategy = _relationalQueryContext.ExecutionStrategyFactory.Create();
```
Comment (roji) [inline src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs:168]: Rather than creating and returning instances, is there a reason we can't simply store the execution strategy instance on the context (like other services), and then pass it through the query context? e.g. would we need to use the same instance concurrently, and would that be a problem?

File: src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs [hunk 2]
```diff
@@ -256,59 +273,65 @@ private bool Exists(bool retryOnNotExists)
...
-                                await _connection.CloseAsync().ConfigureAwait(false);
-                            }
-                        }
-                    }
-                }, cancellationToken);
+        private async Task<bool> ExistsAsync(bool retryOnNotExists, CancellationToken cancellationToken)
+        {
+            var executionStrategy = Dependencies.ExecutionStrategyFactory.Create();
+            var result = await executionStrategy.ExecuteAsync(
+                           DateTime.UtcNow + RetryTimeout, async (giveUp, ct) =>
```
Comment (roji) [inline src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs:280]: Indentation (here and elsewhere)?

File: src/EFCore/ChangeTracking/Internal/StateManager.cs [hunk 3]
```diff
@@ -1215,16 +1222,25 @@ private static int SaveChanges(StateManager stateManager, bool acceptAllChangesO
...
+            if (!Context.Database.AutoTransactionsEnabled)
+            {
+                return await SaveChangesAsync(this, acceptAllChangesOnSuccess, cancellationToken).ConfigureAwait(acceptAllChangesOnSuccess);
+            }
+
+            var executionStrategy = Dependencies.ExecutionStrategyFactory.Create();
+            var result = await executionStrategy.ExecuteAsync(
                     (StateManager: this, AcceptAllChangesOnSuccess: acceptAllChangesOnSuccess),
-                    (_, t, cancellationToken) => SaveChangesAsync(t.StateManager, t.AcceptAllChangesOnSuccess, cancellationToken),
+                    static (_, t, cancellationToken) => SaveChangesAsync(t.StateManager, t.AcceptAllChangesOnSuccess, cancellationToken),
```
Comment (roji) [inline src/EFCore/ChangeTracking/Internal/StateManager.cs:1237]: :+1:

**Review by ajcvickers — APPROVED** [review]

File: src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs [hunk 4]
```diff
@@ -513,12 +516,15 @@ public static void OpenConnection(this DatabaseFacade databaseFacade)
         /// <param name="cancellationToken"> A <see cref="CancellationToken" /> to observe while waiting for the task to complete. </param>
         /// <returns> A task that represents the asynchronous operation. </returns>
         /// <exception cref="OperationCanceledException"> If the <see cref="CancellationToken"/> is canceled. </exception>
-        public static Task OpenConnectionAsync(
+        public static async Task OpenConnectionAsync(
```
Comment (roji) [inline src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs:519]: Note that adding async to methods adds a slight overhead state-machine overhead, that's usually negligible but this is actually a method that will almost always complete synchronously (thanks to connection pooling). If possible, that could be a reason to prefer caching a strategy instance on context rather than creating/returning.

File: src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs [hunk 5]
```diff
@@ -563,19 +575,24 @@ public static IDbContextTransaction BeginTransaction(this DatabaseFacade databas
         ///     that represents the started transaction.
         /// </returns>
         /// <exception cref="OperationCanceledException"> If the <see cref="CancellationToken"/> is canceled. </exception>
-        public static Task<IDbContextTransaction> BeginTransactionAsync(
+        public static async Task<IDbContextTransaction> BeginTransactionAsync(
```
Comment (roji) [inline src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs:578]: Just FYI that this also always returns synchronously on Npgsql (actually beginning the transaction is deferred and batched with the next command)

File: src/EFCore/Storage/ExecutionStrategy.cs [hunk 6]
```diff
@@ -110,23 +110,39 @@ public abstract class ExecutionStrategy : IExecutionStrategy
...
         protected static bool Suspended
         {
-            get => _suspended.Value ?? false;
-            set => _suspended.Value = value;
+            get => Current != null;
+            set { }
+        }
+
+        /// <summary>
+        ///     Gets or sets the currently executing stategy. All nested calls will be handled by the outermost strategy.
```
Comment (roji) [inline src/EFCore/Storage/ExecutionStrategy.cs:127]:
```suggestion
        ///     Gets or sets the currently executing strategy. All nested calls will be handled by the outermost strategy.
```

File: src/EFCore/Storage/ExecutionStrategy.cs [hunk 7]
```diff
@@ -110,23 +110,39 @@ public abstract class ExecutionStrategy : IExecutionStrategy
         /// </summary>
         protected virtual ExecutionStrategyDependencies Dependencies { get; }
 
-        private static readonly AsyncLocal<bool?> _suspended = new();
+        private static readonly AsyncLocal<ExecutionStrategy?> _current = new();
```
Comment (roji) [inline src/EFCore/Storage/ExecutionStrategy.cs:113]: Not directly relevant to this PR, but AsyncLocal can be quite expensive (as it was with ConcurrencyDetector. That's OK in query compilation, but may be significant in ExecutionStrategy.Execute. Keeping this on the context instance may help.

Comment (AndriySvyryd) [reply src/EFCore/Storage/ExecutionStrategy.cs:113]: This has to be an `AsyncLocal` as it's also meant to detect user-initiated executions that might not be associated with any particular context (and span over multiple instances)

File: src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs]: I've made it a scoped service. It's definitely not thread-safe, but most of the places it could be used from concurrently are covered by the concurrency detector.

Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs]: Was  there a reason for it not being a service before? What is the service connection between factory and strategy now? Related in order to put an instance on QC, we don't need to make it service. QC is non-service and uses factory pattern. Also QC is per query so thread-safe.

Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs]: > Was there a reason for it not being a service before? 

Initially the execution strategy was designed to be single-use only

What is the service connection between factory and strategy now?

`IExecutionStrategy` is resolved as scoped by using the registered `IExecutionStrategyFactory`

> Related in order to put an instance on QC, we don't need to make it service. QC is non-service and uses factory pattern. Also QC is per query so thread-safe.

Sure, but if we already have a scoped instance in DI we can reuse it in QC too

Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs]: Totally fine if making it scoped service is the direction we are taking. Just wanted to point out that query shouldn't be the only reason forcing it.

File: src/EFCore/Storage/ExecutionStrategy.cs (hunk 7 above)
Comment (roji) [reply src/EFCore/Storage/ExecutionStrategy.cs:113]: Makes sense... and in any case this is opt-in (NonRetrying doesn't have this)

File: src/EFCore/Storage/Internal/ExecutionStrategyFactory.cs [hunk 8]
```diff
@@ -39,10 +42,9 @@ public ExecutionStrategyFactory(ExecutionStrategyDependencies dependencies)
...
 
         /// <summary>
-        ///     Creates a new  <see cref="IExecutionStrategy" />.
+        ///     Creates a new <see cref="IExecutionStrategy" />.
         /// </summary>
-        /// <returns>An instance of <see cref="IExecutionStrategy" />.</returns>
-        public virtual IExecutionStrategy Create()
-            => new NonRetryingExecutionStrategy(Dependencies);
+        /// <returns> An instance of <see cref="IExecutionStrategy" />. </returns>
+        public virtual IExecutionStrategy Create() => _instance;
```
Comment (roji) [inline src/EFCore/Storage/Internal/ExecutionStrategyFactory.cs:48]: :+1:

File: src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs [hunk 9]
```diff
@@ -599,16 +598,9 @@ public static IDbContextTransaction BeginTransaction(this DatabaseFacade databas
...
-            if (!(transactionManager is IRelationalTransactionManager relationalTransactionManager))
-            {
-                throw new InvalidOperationException(RelationalStrings.RelationalNotInUse);
-            }
-
-            return relationalTransactionManager.UseTransaction(transaction, transactionId);
-        }
+            => GetTransactionManager(databaseFacade) is not IRelationalTransactionManager relationalTransactionManager
+                ? throw new InvalidOperationException(RelationalStrings.RelationalNotInUse)
+                : relationalTransactionManager.UseTransaction(transaction, transactionId);
```
Comment (roji) [inline src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs:603]: nit: consider inversing logic

```suggestion
            => GetTransactionManager(databaseFacade) is IRelationalTransactionManager relationalTransactionManager
                ? relationalTransactionManager.UseTransaction(transaction, transactionId)
                : throw new InvalidOperationException(RelationalStrings.RelationalNotInUse);
```

File: src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs [hunk 10]
```diff
@@ -638,16 +630,9 @@ public static IDbContextTransaction BeginTransaction(this DatabaseFacade databas
...
-            if (!(transactionManager is IRelationalTransactionManager relationalTransactionManager))
-            {
-                throw new InvalidOperationException(RelationalStrings.RelationalNotInUse);
-            }
-
-            return relationalTransactionManager.UseTransactionAsync(transaction, transactionId, cancellationToken);
-        }
+            => GetTransactionManager(databaseFacade) is not IRelationalTransactionManager relationalTransactionManager
+                ? throw new InvalidOperationException(RelationalStrings.RelationalNotInUse)
+                : relationalTransactionManager.UseTransactionAsync(transaction, transactionId, cancellationToken);
```
Comment (roji) [inline src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs:635]: As above:

```suggestion
            => GetTransactionManager(databaseFacade) is IRelationalTransactionManager relationalTransactionManager
                ? relationalTransactionManager.UseTransactionAsync(transaction, transactionId, cancellationToken)
                : throw new InvalidOperationException(RelationalStrings.RelationalNotInUse);
```

**Review by roji — APPROVED** [review]
Look great, thanks @AndriySvyryd!
