### PR TITLE
Specific message for method translation failure

### LINKED ISSUE #21177: Helpful exception message for method translation failure
This would help pinpoint the problematic method (within a potentially large exception), and point users towards our future DbFunction docs. @JeremyLikness, can we get a new fwlink pointing to https://github.com/dotnet/EntityFramework.Docs/issues/500 for now?

Continues work started in #20612

### PR DESCRIPTION
**Pull request by roji**
Closes #21177

### CODE REVIEW

File: src/Shared/SharedTypeExtensions.cs [hunk 1]
```diff
@@ -344,5 +366,131 @@ public static bool IsQueryableType(this Type type)
...
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        public static string DisplayName([NotNull] this Type type, bool fullName = true)
+        {
+            var stringBuilder = new StringBuilder();
+            ProcessType(stringBuilder, type, fullName);
+            return stringBuilder.ToString();
+        }
+
+                private static void ProcessType(StringBuilder builder, Type type, bool fullName)
```
Comment (ilmax) [inline src/Shared/SharedTypeExtensions.cs:383]: nit: formatting looks off here

Comment (roji) [reply src/Shared/SharedTypeExtensions.cs:383]: Thanks

File: test/EFCore.Specification.Tests/CustomConvertersTestBase.cs [hunk 2]
```diff
@@ -570,8 +570,8 @@ protected class ValueWrapper
         public virtual void Collection_property_as_scalar_Any()
         {
             using var context = CreateContext();
-            Assert.Equal(
-                @"The LINQ expression 'DbSet<CollectionScalar>()    .Where(c => c.Tags        .Any())' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.",
+            Assert.Contains(
+                @"Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.",
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/CustomConvertersTestBase.cs:574]: This was by design. We should verify exception message for query as much as we can with Equal so that we know exactly what we are printing as Expression tree to user.

Comment (roji) [reply test/EFCore.Specification.Tests/CustomConvertersTestBase.cs:574]: We were already checking only a substring via QueryTestBase.AssertTranslationFailed, and @maumar seemed to think this change was OK. Strong feelings about this?
