### PR TITLE
Better handling of nullable element comparers

### LINKED ISSUE #31522: Incorrect type mapping gets created for nullable value property when using converter lambda overload
Repro:

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var array = new MyEnum?[] { MyEnum.One, MyEnum.Two };

_ = await ctx.Blogs.Where(b => array.Contains(b.NullableEnum)).ToListAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>()
            .Property(b => b.NullableEnum)
            .HasConversion(w => w.ToString(), v => Enum.Parse<MyEnum>(v));
            // Using the following line makes things work:
            // .HasConversion(typeof(EnumToStringConverter<MyEnum>));
    }
}

public class Blog
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public MyEnum? NullableEnum { get; set; }
}

public enum MyEnum
{
    One, Two
}
```

<details>
<summary>Exception</summary>

```
Unhandled exception. System.MissingMethodException: Constructor on type 'Microsoft.EntityFrameworkCore.Storage.Json.JsonNullableStructCollectionReaderWriter`3[[System.Nullable`1[[MyEnum, Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]][], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Nullable`1[[MyEnum, Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]][], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[MyEnum, Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Microsoft.EntityFrameworkCore.Storage.TypeMappingSourceBase.TryFindJsonCollectionMapping(TypeMappingInfo mappingInfo, Type modelClrType, Type providerClrType, CoreTypeMapping& elementMapping, JsonValueReaderWriter& collectionReaderWriter) in /home/roji/projects/efcore/src/EFCore/Storage/TypeMappingSourceBase.cs:line 174
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindCollectionMapping(RelationalTypeMappingInfo info, Type modelType, Type providerType, CoreTypeMapping elementMapping) in /home/roji/projects/efcore/src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs:line 228
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.<>c.<FindMappingWithConversion>b__8_0(ValueTuple`4 k, RelationalTypeMappingSource self) in /home/roji/projects/efcore/src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs:line 199
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, Type providerClrType, ValueConverter customConverter, CoreTypeMapping elementMapping) in /home/roji/projects/efcore/src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs:line 137
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(Type type, IModel model, CoreTypeMapping elementMapping) in /home/roji/projects/efcore/src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs:line 393
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.SqlServerInferredTypeMappingApplier.ApplyTypeMappingsOnOpenJsonExpression(SqlServerOpenJsonExpression openJsonExpression, IReadOnlyList`1 typeMappings) in /home/roji/projects/efcore/src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs:line 608
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.SqlServerInferredTypeMappingApplier.VisitExtension(Expression expression) in /home/roji/projects/efcore/src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs:line 571
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.<VisitChildren>g__VisitList|125_0[T](List`1 list, Boolean inPlace, Boolean& changed, <>c__DisplayClass125_0&) in /home/roji/projects/efcore/src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:line 4739
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.VisitChildren(ExpressionVisitor visitor) in /home/roji/projects/efcore/src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:line 4624
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.RelationalInferredTypeMappingApplier.VisitExtension(Expression expression) in /home/roji/projects/efcore/src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 2892
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.SqlServerInferredTypeMappingApplier.VisitExtension(Expression expression) in /home/roji/projects/efcore/src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs:line 573
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.InExpression.VisitChildren(ExpressionVisitor visitor) in /home/roji/projects/efcore/src/EFCore.Relational/Query/SqlExpressions/InExpression.cs:line 106
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.RelationalInferredTypeMappingApplier.VisitExtension(Expression expression) in /home/roji/projects/efcore/src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 2916
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.SqlServerInferredTypeMappingApplier.VisitExtension(Expression expression) in /home/roji/projects/efcore/src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs:line 573
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.VisitChildren(ExpressionVisitor visitor) in /home/roji/projects/efcore/src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:line 4554
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.RelationalInferredTypeMappingApplier.VisitExtension(Expression expression) in /home/roji/projects/efcore/src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 2892
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.SqlServerInferredTypeMappingApplier.VisitExtension(Expression expression) in /home/roji/projects/efcore/src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs:line 573
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.RelationalInferredTypeMappingApplier.VisitExtension(Expression expression) in /home/roji/projects/efcore/src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 2913
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.SqlServerInferredTypeMappingApplier.VisitExtension(Expression expression) in /home/roji/projects/efcore/src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs:line 573
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.ApplyInferredTypeMappings(Expression expression, IReadOnlyDictionary`2 inferredTypeMappings) in /home/roji/projects/efcore/src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs:line 531
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression) in /home/roji/projects/efcore/src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 90
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in /home/roji/projects/efcore/src/EFCore/Query/QueryCompilationContext.cs:line 164
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async) in /home/roji/projects/efcore/src/EFCore/Storage/Database.cs:line 66
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in /home/roji/projects/efcore/src/EFCore/Query/Internal/QueryCompiler.cs:line 82
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0() in /home/roji/projects/efcore/src/EFCore/Query/Internal/QueryCompiler.cs:line 115
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in /home/roji/projects/efcore/src/EFCore/Query/Internal/CompiledQueryCache.cs:line 66
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken) in /home/roji/projects/efcore/src/EFCore/Query/Internal/QueryCompiler.cs:line 111
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) in /home/roji/projects/efcore/src/EFCore/Query/Internal/EntityQueryProvider.cs:line 83
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken) in /home/roji/projects/efcore/src/EFCore/Query/Internal/EntityQueryable`.cs:line 96
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /home/roji/projects/test/Program.cs:line 17
   at Program.<Main>$(String[] args) in /home/roji/projects/test/Program.cs:line 17
   at Program.<Main>(String[] args)
```

</details>

When using the lambda-based HasConversion, the ModelClrType on the converter ends up being `MyEnum?`, whereas with EnumToStringConverter, it's `MyEnum`. This creates issues since both the JsonValueReaderWriter and the value comparers get created over the nullable value type, and this isn't accepted by the constructors on JsonNullableStructCollectionReaderWriter's and NullableValueTypeListComparer.

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #31522

### CODE REVIEW

File: src/EFCore/ChangeTracking/ObjectListComparer.cs [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+{
+    /// <summary>
+    ///     Creates a new instance of the list comparer.
+    /// </summary>
+    /// <param name="elementComparer">The comparer to use for comparing elements.</param>
+    public ObjectListComparer(ValueComparer elementComparer)
+        : base(
+            (a, b) => Compare(a, b, elementComparer),
+            o => GetHashCode(o, elementComparer),
+            source => Snapshot(source, elementComparer))
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/ObjectListComparer.cs:29]: Avoid using private methods in the expression trees to make the comparers compatible with compiled model.

**Review by AndriySvyryd — APPROVED** [review]
