### PR TITLE
Fix to #19731 - Discuss default null propagation strategy for functions

### LINKED ISSUE #19731: Discuss default null propagation strategy for functions
We now have the ability to specify detailed null behavior on functions (i.e. whether the function itself is nullable, and whether its propagates nulls from its parameters and instance). The current default for this - SqlExpressionFactory.Function() overloads which don't accept these settings - is for the function to be nullable, and for the parameters/instance *not* to be propagated; in other words, we have no idea about the function and when it returns null, we assume the worst, so we add null checks on the function:

```sql
WHERE (FOO(p) = x) OR ((FOO(p) IS NULL) AND (x IS NULL))")
```
(assuming x is nullable)

While this is the most conservative option, it's also problematic for perf (especially since we evaluate the function twice) and very verbose, and we think that the vast majority of functions *do* propagate nulls. We could decide to change the default to always propagate, producing:

```sql
WHERE (FOO(p) = x) OR (p IS NULL) AND (x IS NULL))")  -- When p is nullable, or:
WHERE FOO(p) = x  -- When p is non-nullable
```

Note: this will affect both UDFs and not just provider writer.

### PR DESCRIPTION
**Pull request by maumar**
- obsoleteing SqlFunction methods and ctors that don't specify nullability propagation info explicitly,
- correcting nullability for LongCount,
- changing 'NullResultAllowed' to 'Nullable' to be consistent with ColumnExpression,
- other minor perf improvements & cleanup.

Fixes #19731

### CODE REVIEW

File: src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs [hunk 1]
```diff
@@ -1287,7 +1287,7 @@ static bool TryNegate(ExpressionType expressionType, out ExpressionType result)
                                 sqlUnaryExpression.TypeMapping));
                     }
 
-                    if (!sqlFunctionExpression.NullResultAllowed)
+                    if (!sqlFunctionExpression.Nullable)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs]: `IsNullable`

**Comment by maumar** [comment]
updated
