### PR TITLE
Fix to #23779 - TryRewriteEntityEquality and NotEqual comparison of CompositePrimaryKey

### LINKED ISSUE #23779: TryRewriteEntityEquality and NotEqual comparison of CompositePrimaryKey
I not sure, but seems this code has mistake:

https://github.com/dotnet/efcore/blob/03c1ba5275b11963ee1d05ad388ded2fda861c1b/src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs#L1397-L1409

In case of obj1.CompositePK != obj2.CompositePK need generate SQL with **OR**:

NOT(obj1.CompositePK.part1==obj2.CompositePK.part1) OR NOT(obj1.CompositePK.part2==obj2.CompositePK.part2)

Your code generates SQL with **AND**:

NOT(obj1.CompositePK.part1==obj2.CompositePK.part1) AND NOT(obj1.CompositePK.part2==obj2.CompositePK.part2)

?

### PR DESCRIPTION
**Pull request by maumar**
When comparing composite key entities we were comparing the constituent keys and combining them with AndAlso. For not equal comparison we were still comparing the keys using !=, but we didn't flip the combining operator to OrElse.

Fixes #23779

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs [hunk 1]
```diff
@@ -1406,7 +1406,9 @@ private bool TryRewriteContainsEntity(Expression source, Expression item, [CA.No
                         return nodeType == ExpressionType.Equal
                             ? (Expression)comparison
                             : Expression.Not(comparison);
-                    }).Aggregate((l, r) => Expression.AndAlso(l, r)));
+                    }).Aggregate((l, r) => nodeType == ExpressionType.Equal
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs:1409]: Also update https://github.com/dotnet/efcore/blob/81aaca8fb756a0385a86cdb0893900f306f49b36/src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs#L1439-L1446

Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs:1409]: And here 
https://github.com/dotnet/efcore/blob/81aaca8fb756a0385a86cdb0893900f306f49b36/src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs#L848-L855

Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs:1409]: May odds be in your favor!

**Review by smitpatel — APPROVED** [review]

**Comment by dmitry-lipetsk** [comment]
Could you look to this code also?

https://github.com/dotnet/efcore/blob/81aaca8fb756a0385a86cdb0893900f306f49b36/src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs#L1354-L1357

It is very strange, that Equal case uses OrElse operator and NotEqual case uses AndAlso.

**Comment by maumar** [comment]
@dmitry-lipetsk wrt null comparison, this is correct. We consider null key when any of the parts has null value
