### PR TITLE
Fix for 20281. Adding HasField() method and updating tests.

### LINKED ISSUE #20281: Add HasField to NavigationBuilder to allow configuring a field that's not found by convention
@AndriySvyryd  to provide details.

### PR DESCRIPTION
**Pull request by lajones**
Fixes #20281. `NavigationBuilder` now has a `HasField()` method on it allowing the user to specify the backing field explicitly.

(Note: avoiding duplication meant pushing this code down onto `InternalPropertyBaseBuilder` and updating some other classes to call it at the same time.)

### CODE REVIEW

File: src/EFCore/Metadata/Builders/NavigationBuilder.cs [hunk 1]
```diff
@@ -103,6 +103,27 @@ public virtual NavigationBuilder UsePropertyAccessMode(PropertyAccessMode proper
...
+        ///         Sets a backing field to use for this navigation property.
+        ///     </para>
+        /// </summary>
+        /// <param name="fieldName"> The name of the field to use for this navigation property. </param>
+        /// <returns> The same builder instance so that multiple configuration calls can be chained. </returns>
+        public virtual NavigationBuilder HasField([CanBeNull] string fieldName)
+        {
+            if (NavBuilder != null)
+            {
+                NavBuilder.HasField(fieldName, ConfigurationSource.Explicit);
```
Comment (smitpatel) [inline src/EFCore/Metadata/Builders/NavigationBuilder.cs]: Can we use NavigationBuilder/SkipNavigationBuilder. Intermediate terms in a variable names should not be shortened.

Comment (lajones) [reply src/EFCore/Metadata/Builders/NavigationBuilder.cs]: I think @AndriySvyryd answered this last time. NavigationBuilder clashes with the name of the class.

Comment (smitpatel) [reply src/EFCore/Metadata/Builders/NavigationBuilder.cs]: @AndriySvyryd - do we have another alternative?

Comment (lajones) [reply src/EFCore/Metadata/Builders/NavigationBuilder.cs]: We could call them InternalNavigationBuilder/InternalSkipNavigationBuilder?

File: src/EFCore/Metadata/Internal/InternalNavigationBuilder.cs [hunk 2]
```diff
@@ -26,6 +26,15 @@ public InternalNavigationBuilder([NotNull] Navigation metadata, [NotNull] Intern
         {
         }
 
+        /// <summary>
+        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+        ///     any release. You should only use it directly in your code with extreme caution and knowing that
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        public virtual new InternalNavigationBuilder HasField([CanBeNull] string fieldName, ConfigurationSource configurationSource)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalNavigationBuilder.cs]: Also add it to `IConventionNavigationBuilder`

File: src/EFCore/Metadata/Builders/NavigationBuilder.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Builders/NavigationBuilder.cs]: Done

File: src/EFCore/Metadata/Internal/InternalNavigationBuilder.cs (hunk 2 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalNavigationBuilder.cs]: Done
