### PR TITLE
[SMALL] Fix to #30330 - Json: updating property with conversion from string to other type fails on sql server

### LINKED ISSUE #30330: Json: updating property with conversion from string to other type fails on sql server
when updating a "normal" (non-string) property, we produce the following sql:

```sql
@p0='[true]' (Nullable = false) (Size = 6)
@p1='[false]' (Nullable = false) (Size = 7)
@p2='1'

SET IMPLICIT_TRANSACTIONS OFF;
SET NOCOUNT ON;
UPDATE [JsonEntitiesAllTypes] SET [Collection] = JSON_MODIFY([Collection], 'strict $[0].TestBoolean', CAST(JSON_VALUE(@p0, '$[0]') AS bit)), [Reference] = JSON_MODIFY([Reference], 'strict $.TestBoolean', CAST(JSON_VALUE(@p1, '$[0]') AS bit))
OUTPUT 1
WHERE [Id] = @p2;
```

however if we update property that is string on client side but (say) bool on the server we issue the following:
```sql
@p0='[false]' (Nullable = false) (Size = 7)
@p1='1'

SET IMPLICIT_TRANSACTIONS OFF;
SET NOCOUNT ON;
UPDATE [JsonEntitiesConverters] SET [Reference] = JSON_MODIFY([Reference], ''strict $.StringTrueFalseConvertedToBool'', JSON_VALUE(@p0, ''$[0]''))
OUTPUT 1
WHERE [Id] = @p1;
```

i.e. we don't wrap the value in cast to a provider type, which then results in us storing it as string and causes problems when querying the values. We should look if the property has a converter and check provider type when determining if we need CAST or not.

### PR DESCRIPTION
**Pull request by maumar**
when producing update statement, when deciding whether we need CAST around the result of JSON_VALUE, we need to look if the property has converter, rather than just look at it's clr type. If the clr type is string, but it gets converted to int/bool etc we still need a CAST.

Fixes #30330

### CODE REVIEW

File: src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs [hunk 1]
```diff
@@ -154,8 +154,10 @@ protected virtual int MergeIntoMinimumThreshold
 
             if (columnModification.Property != null)
             {
-                var needsTypeConversion = columnModification.Property.ClrType.IsNumeric()
-                    || columnModification.Property.ClrType == typeof(bool);
+                var propertyClrType = columnModification.Property.GetTypeMapping().Converter?.ProviderClrType
```
Comment (roji) [inline src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs:157]: Don't we have a simply shortcut to just get the provider CLR type of a property? If not, we probably should...

File: test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs [hunk 2]
```diff
@@ -558,7 +558,7 @@ public override async Task Edit_single_property_char()
 
 SET IMPLICIT_TRANSACTIONS OFF;
 SET NOCOUNT ON;
-UPDATE [JsonEntitiesAllTypes] SET [Reference] = JSON_MODIFY([Reference], 'strict $.TestCharacter', CAST(JSON_VALUE(@p0, '$[0]') AS nvarchar(1)))
+UPDATE [JsonEntitiesAllTypes] SET [Reference] = JSON_MODIFY([Reference], 'strict $.TestCharacter', JSON_VALUE(@p0, '$[0]'))
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs:561]: Unrelated to this PR :)

I noticed that we we send a single-element JSON array wrapping the value, and then use JSON_VALUE server-side to unwrap the value. What's the reason for having to do this, i.e. why not just send the value directly and just do `JSON_MODIFY([Reference], 'strict $.TestCharacter', @p0)`? The examples for [JSON_VALUE](https://learn.microsoft.com/en-us/sql/t-sql/functions/json-value-transact-sql) just seem to show the simple, direct way...

If we did that, wouldn't we be able to just get rid of the CAST around the JSON_VALUE? I'm assuming the cast is needed because JSON_VALUE always returns nvarchar (but we need e.g. an int). But if we just embedded the value directly, it would be typed correctly and could just go directly into the document?

File: test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs [hunk 3]
```diff
@@ -1328,20 +1328,52 @@ OUTPUT 1
...
+@p1='1'
+
+SET IMPLICIT_TRANSACTIONS OFF;
+SET NOCOUNT ON;
+UPDATE [JsonEntitiesConverters] SET [Reference] = JSON_MODIFY([Reference], 'strict $.StringTrueFalseConvertedToBool', CAST(JSON_VALUE(@p0, '$[0]') AS bit))
+OUTPUT 1
+WHERE [Id] = @p1;
+""",
+                //
+                """
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs:1348]: Need to see if this can be enforced e.g. with .editorconfig

```suggestion
"""
```

File: test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs [hunk 4]
```diff
@@ -1328,20 +1328,52 @@ OUTPUT 1
...
+@p1='1'
+
+SET IMPLICIT_TRANSACTIONS OFF;
+SET NOCOUNT ON;
+UPDATE [JsonEntitiesConverters] SET [Reference] = JSON_MODIFY([Reference], 'strict $.StringYNConvertedToBool', CAST(JSON_VALUE(@p0, '$[0]') AS bit))
+OUTPUT 1
+WHERE [Id] = @p1;
+""",
+                //
+                """
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs:1372]:
```suggestion
"""
```

**Review by roji — APPROVED** [review]

**Comment by roji** [comment]
(@maumar just a ping to make sure you saw the comments above)

File: src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs (hunk 1 above)
Comment (maumar) [reply src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs:157]: this was the method suggested by @AndriySvyryd, so I guess it's the best one we've got ;)

File: test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs (hunk 2 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs:561]: When passing values directly in parameter I hit issues with some data types (DateTime, Guid). e.g. if stored directly as parameter DateTime would be stored as `"1\/1\/3000 12:34:56 PM"` (and that wouldn't round trip), whereas what we want is `"3000-01-01T12:34:56"`.  By doing the array trick we always get values in a form that is appropriate to store as json for a given data type. Perhaps we could do special casing and simplify for types that work (which is the majority). Or better yet, when/if we have dedicated type mapping for json, we would always be able to render the parameter values correctly.

Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs:561]: filed https://github.com/dotnet/efcore/issues/30410 to track this
