### PR TITLE
Fix for 18063. Add missing concurrency token properties for table splitting

### LINKED ISSUE #18063: Add missing concurrency token properties for table splitting
And document this behavior.

See https://github.com/aspnet/EntityFrameworkCore/issues/14154#issuecomment-535461203

### PR DESCRIPTION
**Pull request by lajones**
Fixes #18063 . Previously if the user was table-splitting and one or more entity types did not map to a concurrency column, we used to throw warning the user to configure the property. Now we simply add it ourselves in shadow state.

### CODE REVIEW

**Comment by ralmsdeveloper** [comment]
@ajcvickers,
if you find the time, could you look at that? I would like to end this weekend.

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs [hunk 1]
```diff
@@ -0,0 +1,189 @@
...
+namespace Microsoft.EntityFrameworkCore.Metadata.Conventions
+{
+    /// <summary>
+    ///     A convention that finds entity types which share a table
+    ///     which has a concurrency token column where those entity types
+    ///     do not have a property mapped to that column. It then
+    ///     creates a shadow concurrency property mapped to that column
+    ///     on the base-most entity type(s).
+    /// </summary>
+    public class AddConcurrencyTokenPropertiesConvention : IModelFinalizingConvention
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:20]: `TableSharingConcurrencyTokenConvention`

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs [hunk 2]
```diff
@@ -0,0 +1,189 @@
...
+
+        private void GetMappings(IConventionModel model,
+            out Dictionary<string, IList<IConventionEntityType>> tableToEntityTypes,
+            out Dictionary<string, Dictionary<string, IList<IProperty>>> concurrencyColumnsToProperties)
+        {
+            tableToEntityTypes = new Dictionary<string, IList<IConventionEntityType>>();
+            concurrencyColumnsToProperties = new Dictionary<string, Dictionary<string, IList<IProperty>>>();
+            foreach (var entityType in model.GetEntityTypes())
+            {
+                var tableName = entityType.GetSchemaQualifiedTableName();
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:127]: Use a `(name, schema)` tuple instead for perf

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs [hunk 3]
```diff
@@ -0,0 +1,189 @@
...
+                        properties.Add(property);
+                    }
+                }
+            }
+        }
+
+        // Given a (distinct) IEnumerable of EntityTypes (mapped to T),
+        // return only the mappings where the EntityType does not inherit
+        // from any other EntityType in the list.
+        private static IEnumerable<KeyValuePair<IConventionEntityType, T>> BasestEntities<T>(
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:168]: There's no need to preserve the original dictionary, so rename this to `void RemoveDerivedEntityTypes` and take the actual dictionary as the parameter

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs [hunk 4]
```diff
@@ -0,0 +1,189 @@
...
+            IEnumerable<KeyValuePair<IConventionEntityType, T>> entityTypeDictionary)
+        {
+            var toRemove = new HashSet<KeyValuePair<IConventionEntityType, T>>();
+            foreach (var entityType in entityTypeDictionary)
+            {
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:173]: skip types that have no base type

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs [hunk 5]
```diff
@@ -0,0 +1,189 @@
...
+                var otherEntityTypes = entityTypeDictionary
+                    .Except(new[] { entityType }).Except(toRemove);
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:175]: Unwrap the `Except` calls as checks in the `foreach` below as `Except` doesn't take advantage of the fact that `toRemove` is a `HashSet`

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs [hunk 6]
```diff
@@ -0,0 +1,189 @@
...
+                foreach (var otherEntityType in otherEntityTypes)
+                {
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:177]: Skip types that have an empty `GetDirectlyDerivedTypes()`

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs (hunk 4 above)
Comment (lajones) [reply src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:173]: By "skip" I think you mean "remove"? But what if the base type is mapped to a different table? I only want the base-most entities that are mapped to this particular table. They don't have to be the base-most in the whole tree.

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs (hunk 6 above)
Comment (lajones) [reply src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:177]: Not following - why?

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs [hunk 7]
```diff
@@ -0,0 +1,189 @@
...
+                        var entityType = entityTypeToExampleProperty.Key;
+                        var exampleProperty = entityTypeToExampleProperty.Value;
+                        var allExistingProperties =
+                            entityType.GetProperties().Select(p => p.Name)
+                            .Union(entityType.GetNavigations().Select(p => p.Name))
+                            .ToDictionary(s => s, s => 0);
+                        var concurrencyShadowPropertyName =
+                            Uniquifier.Uniquify(ConcurrencyPropertyPrefix + concurrencyColumnName, allExistingProperties, maxIdentifierLength);
+                        var concurrencyShadowProperty =
+                            entityType.AddProperty(concurrencyShadowPropertyName, exampleProperty.ClrType, null);
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:110]: Instead of a custom prefix use the existing unification pattern:
```
var concurrencyShadowPropertyBuilder = ((InternalEntityTypeBuilder)entityType.Builder)
                            .CreateUniqueProperty(exampleProperty.Name, exampleProperty.ClrType, !exampleProperty.IsNullable).Builder;
```

And use this builder to configure facets to make sure they are using the convention ConfigurationSource

And use the convention property

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs (hunk 6 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:177]: All the comments for this method is to improve perf

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs (hunk 4 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:173]: You are right, I forgot that I am adding TPT at this very moment 🤦‍♂️

Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:173]: What I mean by skip is to call `continue`. We know that they will not be removed, as they will always be the basest

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs (hunk 7 above)
Comment (lajones) [reply src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:110]: Happy to use `CreateUniqueProperty()` and convention property and the ConfigurationSource.

But I wanted to make it easy to spot the difference between a shadow property created by our convention and some other shadow property. Especially if we're not going to log a debug message saying we're creating it. If we use `exampleProperty.Name` above we'll end up with a Property called the same as the example property - which it may be hard to spot is something we created for you if you were just looking at the model. I'd prefer to stick with the prefix.

File: test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs [hunk 8]
```diff
@@ -971,22 +971,70 @@ public virtual void Detects_missing_concurrency_token_on_the_base_type()
...
+            var animal = model.FindEntityType(typeof(Animal));
+            var concurrencyProperty = animal.FindProperty("_concurrency_Version");
+            Assert.True(concurrencyProperty.IsConcurrencyToken);
+            Assert.True(concurrencyProperty.IsShadowProperty());
+            Assert.Equal("Version", concurrencyProperty.GetColumnName());
+            Assert.Equal(ValueGenerated.OnAddOrUpdate, concurrencyProperty.ValueGenerated);
+        }
+
+        [ConditionalFact]
+        public virtual void Missing_concurrency_token_properties_are_created_on_the_base_most_types()
```
[the remark this answers is not in the document]
Comment (lajones) [reply test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs:986]: I think that meant only 1 class in that (test) namespace though as the other conventions hadn't done that. OK with that?

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs (hunk 7 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:110]: Ok, then change the prefix it to "_implicit_" or "_convention_" to give a clue where it comes from

File: test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (AndriySvyryd) [reply test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs:986]: Yes. Soon we'll need to add a test for TPT there.

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs (hunk 6 above)
Comment (lajones) [reply src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:177]: OK. I see where you're coming from now.

File: src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs (hunk 7 above)
Comment (lajones) [reply src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:110]: Note: this adds an internal dependency - which I have to suppress. Is there a more public way of doing the same thing?

Comment (lajones) [reply src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:110]: Also just FYI - the APIs I was using before to create the property was on an `IConventionEntityType`. So I was already getting an `IConventionProperty` and all the `SetXyz()` calls already set the `ConfigurationSource`s correctly. I can be more explicit and call them with `setTypeConfigurationSource = true` and `fromDataAnnotation = false` if you'd prefer?

Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs:110]: I'll make it public later. I just wanted to be explicit about the configuration source because `CreateUniqueProperty` returns the internal `Property`, no need to specify the optional parameters.

File: test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs [hunk 9]
```diff
@@ -971,22 +971,70 @@ public virtual void Detects_missing_concurrency_token_on_the_base_type()
...
+            Assert.Equal("Version", concurrencyProperty.GetColumnName());
+            Assert.Equal(ValueGenerated.OnUpdate, concurrencyProperty.ValueGenerated);
+
+            var theMovie = model.FindEntityType(typeof(TheMovie));
+            Assert.DoesNotContain(theMovie.GetDeclaredProperties(), p => p.Name == "_concurrency_Version");
         }
 
         [ConditionalFact]
-        public virtual void Detects_missing_concurrency_token_on_the_sharing_type()
+        public virtual void Missing_concurrency_token_property_is_created_on_the_sharing_type()
```
Comment (AndriySvyryd) [inline test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs:1022]: Rename the tests to follow the pattern "Passes_for_"

Comment (lajones) [reply test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs:1022]: @AndriySvyryd Do you still want this now that those 3 tests are in a class by themselves? In the new class we are no longer testing whether validation passes - just that the shadow property is created.

File: test/EFCore.Relational.Tests/Metadata/Conventions/TableSharingConcurrencyTokenConventionTest.cs [hunk 10]
```diff
@@ -0,0 +1,159 @@
...
+
+        private ModelBuilder GetModelBuilder(DbContext dbContext = null)
+        {
+            var conventionSet = new ConventionSet();
+
+            var dependencies = CreateDependencies()
+                .With(new CurrentDbContext(dbContext ?? new DbContext(new DbContextOptions<DbContext>())));
+            var relationalDependencies = CreateRelationalDependencies();
+            var tableSharingConcurrencyTokenConvention = new TableSharingConcurrencyTokenConvention(dependencies, relationalDependencies);
+            conventionSet.ModelFinalizingConventions.Add(tableSharingConcurrencyTokenConvention);
```
Comment (AndriySvyryd) [inline test/EFCore.Relational.Tests/Metadata/Conventions/TableSharingConcurrencyTokenConventionTest.cs:148]: Also add the validation convention

File: test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs [hunk 11]
```diff
@@ -961,34 +961,6 @@ public virtual void Passes_for_compatible_duplicate_index_names_within_hierarchy
             Assert.Equal(index1.GetName(), index2.GetName());
         }
 
-        [ConditionalFact]
-        public virtual void Detects_missing_concurrency_token_on_the_base_type()
-        {
-            var modelBuilder = CreateConventionalModelBuilder();
```
Comment (AndriySvyryd) [inline test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs:967]: Change to `CreateConventionlessModelBuilder` and keep the tests. In the future conventions will be removeable.

File: src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs [hunk 12]
```diff
@@ -0,0 +1,198 @@
...
+                        var exampleProperty = entityTypeToExampleProperty.Value;
+                        var concurrencyShadowPropertyBuilder =
+#pragma warning disable EF1001 // Internal EF Core API usage.
+                            ((InternalEntityTypeBuilder)entityType.Builder).CreateUniqueProperty(
+                                ConcurrencyPropertyPrefix + exampleProperty.Name,
+                                exampleProperty.ClrType,
+                                !exampleProperty.IsNullable);
+                        concurrencyShadowPropertyBuilder.SetColumnName(concurrencyColumnName);
+                        _ = concurrencyShadowPropertyBuilder.SetIsConcurrencyToken(true, ConfigurationSource.Convention);
+                        _ = concurrencyShadowPropertyBuilder.SetValueGenerated(exampleProperty.ValueGenerated, ConfigurationSource.Convention);
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs:111]: Chain the calls together with `?.`

File: src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs [hunk 13]
```diff
@@ -0,0 +1,198 @@
...
+                    }
+                }
+            }
+        }
+
+        private void GetMappings(IConventionModel model,
+            out Dictionary<Tuple<string, string>, IList<IConventionEntityType>> tableToEntityTypes,
+            out Dictionary<Tuple<string, string>, Dictionary<string, IList<IConventionProperty>>> concurrencyColumnsToProperties)
+        {
+            tableToEntityTypes = new Dictionary<Tuple<string, string>, IList<IConventionEntityType>>();
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs:122]: Use value tuples instead
```suggestion
            tableToEntityTypes = new Dictionary<(string Table, string Schema), IList<IConventionEntityType>>();
```

File: src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs [hunk 14]
```diff
@@ -0,0 +1,198 @@
...
+        }
+
+        // Given a Dictionary of EntityTypes (mapped to T), remove
+        // any mappings where the EntityType inherits from any
+        // other EntityType in the Dictionary.
+        private static void RemoveDerivedEntityTypes<T>(
+            ref Dictionary<IConventionEntityType, T> entityTypeDictionary)
+        {
+            var toRemove = new HashSet<KeyValuePair<IConventionEntityType, T>>();
+            var entityTypesWithDerivedTypes = entityTypeDictionary.Where(e => e.Key.GetDirectlyDerivedTypes().Any());
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs:173]:
```suggestion
            var entityTypesWithDerivedTypes = entityTypeDictionary.Where(e => e.Key.GetDirectlyDerivedTypes().Any()).ToList();
```

File: test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs (hunk 11 above)
Comment (lajones) [reply test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs:967]: I'd rather combine this with your comment above. Adding in the `ValidationConvention` above will not be enough. We would also end up needing the `TypeMappingConvention` and potentially several others and at that stage it doesn't feel like a unit test any more. So I'd rather put back the original tests I deleted here and change them to expect to pass.

Comment (AndriySvyryd) [reply test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs:967]: Ok, but also keep the tests where the exception is thrown.

File: test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs [hunk 15]
```diff
@@ -1143,6 +1196,18 @@ public TestDecimalToDecimalConverter()
...
         }
 
+        protected virtual ModelBuilder CreateModelBuilderWithoutConvention(bool sensitiveDataLoggingEnabled = false)
+        {
+            var conventionSet = TestHelpers.CreateConventionalConventionSet(
+                CreateModelLogger(sensitiveDataLoggingEnabled), CreateValidationLogger(sensitiveDataLoggingEnabled));
+
+            ConventionSet.Remove(
+                conventionSet.ModelFinalizingConventions,
+                typeof(TableSharingConcurrencyTokenConvention));
```
Comment (AndriySvyryd) [inline test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs:1206]: Make this a generic argument
