### PR TITLE
Fix to #34960 - System.Text.Json.JsonReaderException: '0x00' is invalid after a single JSON value. Expected end of data

### LINKED ISSUE #34960: System.Text.Json.JsonReaderException: '0x00' is invalid after a single JSON value. Expected end of data.
### Bug description

We are using .NET 8, [Microsoft.EntityFrameworkCore.Design 8.0.4](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Design/8.0.4) and [Npgsql.EntityFrameworkCore.PostgreSQL 8.0.4](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/8.0.4). Our database is PostgreSQL 10.23.

We have a simple PostgreSQL table which was created and populated using the following SQL query:

```sql
CREATE TABLE fit3.product (
    id serial4 NOT NULL,
    config jsonb,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);
INSERT INTO fit3.product(config) VALUES (null);
INSERT INTO fit3.product(config) VALUES ('null');
INSERT INTO fit3.product(config) VALUES ('{"CPU": "ARM"}');
```

We are using database-first approach - we scaffolded the database to obtain the following C# model:

```cs
[Table("product", Schema = "fit3")]
public partial class Product
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("config", TypeName = "jsonb")]
    public string? Config { get; set; }
}
```

We also defined the following 2 classes which represent JSON for the configuration:

```cs
public partial class Product
{
    public Config? ConfigJSON { get; set; }
}

public class Config
{
    public string? CPU { get; set; }
}
```

We performed the mapping from jsonb column to our `Config` C# class inside `OnModelCreatingPartial`:

```cs
partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Product>(entity =>
    {
        entity.OwnsOne(x => x.ConfigJSON, t =>
        {
            t.ToJson("config");
        });
    });
}
```

However, when we perform the following simple query ...

```cs
var products = _fitDBContext.Products.ToList();
```

... the following exception is thrown:

```
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Net.NetworkInformation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.EntityFrameworkCore.Model.Validation: Warning: Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT p.id, p.config, p.config
FROM fit3.product AS p
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'FitView.Data.Fit.Models.FitDBContext'.
System.Text.Json.JsonReaderException: '0x00' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 4.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at lambda_method89(Closure, QueryContext, Object[], JsonReaderData)
   at lambda_method88(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()

System.Text.Json.JsonReaderException: '0x00' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 4.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at lambda_method89(Closure, QueryContext, Object[], JsonReaderData)
   at lambda_method88(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
Exception thrown: 'System.Text.Json.JsonReaderException' in Microsoft.EntityFrameworkCore.Relational.dll
```

### Provider and version information

EF Core version: 8.0.4
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 8.0.4
Target framework: .NET 8
Operating system: Windows 11 x64
IDE: Visual Studio Professional 64-bit 17.11.5

### PR DESCRIPTION
**Pull request by maumar**
When entity or collection of entities is mapped to JSON null value for that object can be represented either as relational null, or as JSON with null value inside 'null'. Problem was that IncludeJsonEntityReference and IncludeJsonEntityCollection were only checking for null value, and not for the JSON 'null'. (MaterializeJsonEntity and MaterializeJsonEntityCollection had the logic for both)

Fix is to add the missing logic so that upon encountering Null token we just return, rather than run shaper code for the entity. Also added some validation that throws if StartObject is not the first token (again, copying logic from MaterializeJsonEntity method)

Fixes #34960

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ClientMethods.cs [hunk 1]
```diff
@@ -1096,6 +1096,20 @@ public static void IncludeJsonEntityReference<TIncludingEntity, TIncludedEntity>
                 return;
             }
 
+            var manager = new Utf8JsonReaderManager(jsonReaderData, queryContext.QueryLogger);
+            var tokenType = manager.CurrentReader.TokenType;
+
+            if (tokenType == JsonTokenType.Null)
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ClientMethods.cs:1102]: nit: consider having a switch statement (multiple conditions checking the same tokenType).

File: test/EFCore.Sqlite.FunctionalTests/Query/AdHocJsonQuerySqliteTest.cs [hunk 2]
```diff
@@ -87,6 +87,21 @@ protected override async Task Seed33046(DbContext ctx)
 VALUES('[{"RoundNumber":11,"SubRounds":[{"SubRoundNumber":111},{"SubRoundNumber":112}]}]', 1)
 """);
 
+    protected override async Task Seed34960(Context34960 ctx)
+    {
+        await base.Seed34960(ctx);
+
+        // JSON nulls
```
Comment (roji) [inline test/EFCore.Sqlite.FunctionalTests/Query/AdHocJsonQuerySqliteTest.cs:94]: Also check that we throw the correct exceptions for invalid JSON (e.g. scalar, array)?

**Review by roji — APPROVED** [review]
