### PR TITLE
Fix to #26676 - EF Core 6 - IsTemporal adds an unnecessary migration when DefaultSchema is configured at the DbContext Level

### LINKED ISSUE #26676: EF Core 6 - IsTemporal adds an unnecessary migration when DefaultSchema is configured at the DbContext Level
I am seeing this incorrect behavior with EF Core 6 in relation to TemporalTables.

Consider the below code.
```
public class MyDbContext : DbContext
{
    private const string DEFAULT_SCHEMA = "app";

    public DbSet<Student> Students { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer("<ConnectionString>")
            .EnableSensitiveDataLogging()
            .LogTo(Console.WriteLine, LogLevel.Information);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema(DEFAULT_SCHEMA);

        modelBuilder.Entity<Student>(builder =>
        {
            builder.ToTable(nameof(Student), x => x.IsTemporal());
        });
    }
}

public class Student
{
    public int Id { get; set; }

    public string Name { get; set; }
}
```

Now to reproduce the issue,
1. Add a migration
2. Add just another migration
image

**Look at the highlighted line. It drops the annotation for the schema in History table.**

I can get around this issue by removing the DefaultSchema configuration from the DbCotext level and introducing it into the table level. But then that has to be done for each table :(

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Student>(builder =>
    {
        builder.ToTable(nameof(Student), DEFAULT_SCHEMA, x => x.IsTemporal());
    });
}
```
The sample executable code is attached herewith.
[EfCore6-TemporalTables.zip](https://github.com/dotnet/efcore/files/7534380/EfCore6-TemporalTables.zip)

Environment Info:
```
EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
```

### PR DESCRIPTION
**Pull request by maumar**
Problem was a discrepancy between RelationalModel build in runtime and the current model (from OnModelCreating) - relational model would set history table schema annotation using the table schema or default schema, however current model wouldn't set those annotations.
Model differ would then pick up on those differences and create migration to set the schema for history table. When building actual migration sql we already compensated for the difference and not generate actual sql code, but the problem persists.

Fix is to improve the temporal convention so that history table schema in current model (more) closely resembles the temporal table schema and therefore is similar to RelationalModel generated in runtime.

Fixes #26676

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
I assume that the issue is that migration snapshot doesn't contain the history schema annotation because it's the default. In cases like these we keep the default logic in the extensions, but add a redundant annotation using a convention, see [SqlServerValueGenerationStrategyConvention](https://github.com/dotnet/efcore/blob/197479e871148acfc882cd166e8ac28a089a30c9/src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationStrategyConvention.cs#L92)

This allows the model to be more functional if the convention is removed and potentially can be improved upon when #9329 is implemented.

File: src/EFCore.SqlServer/Extensions/SqlServerEntityTypeExtensions.cs [hunk 1]
```diff
@@ -253,7 +253,7 @@ public static void SetHistoryTableName(this IMutableEntityType entityType, strin
         => (entityType is RuntimeEntityType)
             ? throw new InvalidOperationException(CoreStrings.RuntimeModelMissingData)
             : entityType[SqlServerAnnotationNames.TemporalHistoryTableSchema] as string
-            ?? entityType[RelationalAnnotationNames.Schema] as string;
+                ?? entityType[RelationalAnnotationNames.Schema] as string;
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Extensions/SqlServerEntityTypeExtensions.cs:256]: Shouldn't this be `entityType.GetSchema()`?

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 2]
```diff
@@ -533,7 +533,8 @@ protected override void Generate(RenameSequenceOperation operation, IModel? mode
         if (operation[SqlServerAnnotationNames.IsTemporal] as bool? == true)
         {
             var historyTableSchema = operation[SqlServerAnnotationNames.TemporalHistoryTableSchema] as string
-                ?? model?.GetDefaultSchema();
+                ?? operation.Schema;
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:536]: We should still fallback to `model?.GetDefaultSchema();` for manually written migrations

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 3]
```diff
@@ -2261,7 +2262,7 @@ private static bool HasDifferences(IEnumerable<IAnnotation> source, IEnumerable<
                 schema ??= model?.GetDefaultSchema();
                 var historyTableName = operation[SqlServerAnnotationNames.TemporalHistoryTableName] as string;
                 var historyTableSchema = operation[SqlServerAnnotationNames.TemporalHistoryTableSchema] as string
-                    ?? model?.GetDefaultSchema();
+                    ?? schema;
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2265]: also here

**Review by AndriySvyryd — APPROVED** [review]
