### PR TITLE
Interceptor for DbUpdateConcurrencyException

### LINKED ISSUE #28315: Interception for DbUpdateConcurrencyException
Split from #16260

### PR DESCRIPTION
**Pull request by ajcvickers**
Part of #626
Fixes #28315
Part of #16260
Allows #10443 functionally, although not optimally

Relational version allows access to the connection, command, and reader from an async context, such that database commands could be used in the interceptor.

### CODE REVIEW

File: src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs [hunk 1]
```diff
@@ -3207,4 +3207,115 @@ private static string ColumnOrderIgnoredWarning(EventDefinitionBase definition,
...
+    /// <param name="exception">The exception that caused this event.</param>
+    /// <param name="cancellationToken">A <see cref="CancellationToken" /> to observe while waiting for the task to complete.</param>
+    /// <returns>A <see cref="Task" /> for the async result.</returns>
+    /// <exception cref="OperationCanceledException">If the <see cref="CancellationToken" /> is canceled.</exception>
+    public static ValueTask<InterceptionResult> OptimisticConcurrencyExceptionAsync(
+        this IDiagnosticsLogger<DbLoggerCategory.Update> diagnostics,
+        DbContext context,
+        RelationalDataReader reader,
+        IReadOnlyList<IUpdateEntry> entries,
+        Exception exception,
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs:3268]: Should this be more specific?

**Review by AndriySvyryd — APPROVED** [review]
