### PR TITLE
Fix to #28881 - Consider removing unnecessary CASTs around JSON_VALUE

### LINKED ISSUE #28881: Consider removing unnecessary CASTs around JSON_VALUE
We currently generate JSON queries such as the following:

```sql
SELECT [a].[Id], [a].[Name], JSON_QUERY([a].[Contact],'$')
FROM [Authors] AS [a]
WHERE CAST(JSON_VALUE([a].[Contact],'$.Address.City') AS nvarchar(max)) = N'Chigley'
```

We seem to systematically wrap JSON_VALUE with a CAST to the specific type - we should consider whether this is actually necessary and when.

Aside from the general verbosness/ugliness factor and unknown perf implications, I expect users will just follow the [SQL Server documentation for JSON indexes](https://docs.microsoft.com/en-us/sql/relational-databases/json/index-json-data?view=sql-server-ver16#example-index), which instruct users to create a virtual computed column with the JSON_VALUE expression, and create an index over that. I expect lots of users won't know to include the CAST inside their compuetd column, leading to the index not getting used.

### PR DESCRIPTION
**Pull request by maumar**
We can remove cast for string scalars, other types maybe cause conversion issues in the generated sql.

Fixes #28881

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs [hunk 1]
```diff
@@ -313,14 +313,22 @@ protected override Expression VisitJsonScalar(JsonScalarExpression jsonScalarExp
...
+                Sql.Append("JSON_VALUE(");
+            }
         }
 
         Visit(jsonScalarExpression.JsonColumn);
 
         Sql.Append($",'{string.Join("", jsonScalarExpression.Path.Select(e => e.ToString()))}')");
 
-        if (jsonScalarExpression.Type != typeof(JsonElement))
+        if (jsonScalarExpression.Type != typeof(JsonElement)
```
Comment (smitpatel) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs:330]: Do you still need first condition now?

**Comment by roji** [comment]
Great to see this.

IMHO we should consider patching this... it certainly seems low-risk, and this issue prevents indexing from being used on strings properties in JSON, as we've seen in the recent conversations on Twitter.

**Comment by maumar** [comment]
@ajcvickers to make the call if we should patch. Risk does seem low.

File: src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs (hunk 1 above)
Comment (maumar) [reply src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs]: need to filter out the non-scalars. Will unify with the check above

**Comment by roji** [comment]
@maumar let me know when you want a review on this.

**Comment by maumar** [comment]
@roji ready for the review

File: src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs [hunk 2]
```diff
@@ -313,14 +313,22 @@ protected override Expression VisitJsonScalar(JsonScalarExpression jsonScalarExp
...
+            }
         }
 
         Visit(jsonScalarExpression.JsonColumn);
 
         Sql.Append($",'{string.Join("", jsonScalarExpression.Path.Select(e => e.ToString()))}')");
 
-        if (jsonScalarExpression.Type != typeof(JsonElement))
+        if (jsonScalarExpression.TypeMapping is not SqlServerJsonTypeMapping
+            && jsonScalarExpression.TypeMapping is not StringTypeMapping)
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs:331]:
```suggestion
        if (jsonScalarExpression.TypeMapping is not SqlServerJsonTypeMapping and not StringTypeMapping)
```

File: src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs [hunk 3]
```diff
@@ -313,14 +313,22 @@ protected override Expression VisitJsonScalar(JsonScalarExpression jsonScalarExp
...
         {
-            Sql.Append("CAST(JSON_VALUE(");
+            if (jsonScalarExpression.TypeMapping is not StringTypeMapping)
+            {
+                Sql.Append("CAST(JSON_VALUE(");
+            }
+            else
+            {
+                Sql.Append("JSON_VALUE(");
+            }
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs:323]:
```suggestion
            // JSON_VALUE always returns nvarchar(4000) (https://learn.microsoft.com/sql/t-sql/functions/json-value-transact-sql),
            // so we cast the result to the expected type - except if it's a string (since the cast interferes with indexes over
            // the JSON property).
            Sql.Append(jsonScalarExpression.TypeMapping is StringTypeMapping ? "JSON_VALUE(" : "CAST(JSON_VALUE(");
```

**Review by roji — APPROVED** [review]
LGTM @maumar, but one question - this removes the cast also for cases where we have a length (e.g. `nvarchar(10)`).

I think it's a bit dubious to have this kind of type mapping on a JSON property, since it's not supported by the database in any way: JSON properties don't have types like columns, and the database never enforces a max length on them, etc. 

But regardless... We can leave the cast, in order to have the DB  truncate the string (in case someone inserted a longer value into the database). I don't think it's important to do that, mostly raising it as a question.
