### PR TITLE
Query: Convert Apply to Join for collection projection

### LINKED ISSUE #20608: Query: Convert Apply to Join for collection projection
Found when discussing filtered includes with take not working on Sqlite with @maumar 

Also customer reported here https://github.com/dotnet/efcore/issues/19178#issuecomment-612660722

### PR DESCRIPTION
**Pull request by smitpatel**
This change makes Collection projection path for single query to use AddJoin method which does conversion.
Now filtered include with Skip/Take works on Sqlite for single query scenario also.

Resolves #20608

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs [hunk 1]
```diff
@@ -4501,223 +4507,254 @@ public override async Task Filtered_include_OrderBy(bool async)
...
+                @"SELECT [l].[Id], [l].[Date], [l].[Name], [l].[OneToMany_Optional_Self_Inverse1Id], [l].[OneToMany_Required_Self_Inverse1Id], [l].[OneToOne_Optional_Self1Id], [t].[Id], [t].[Date], [t].[Level1_Optional_Id], [t].[Level1_Required_Id], [t].[Name], [t].[OneToMany_Optional_Inverse2Id], [t].[OneToMany_Optional_Self_Inverse2Id], [t].[OneToMany_Required_Inverse2Id], [t].[OneToMany_Required_Self_Inverse2Id], [t].[OneToOne_Optional_PK_Inverse2Id], [t].[OneToOne_Optional_Self2Id]
 FROM [LevelOne] AS [l]
-LEFT JOIN [LevelTwo] AS [l0] ON [l].[Id] = [l0].[OneToMany_Optional_Inverse2Id]
-ORDER BY [l].[Id], [l0].[Name], [l0].[Id]");
+LEFT JOIN (
+    SELECT [l0].[Id], [l0].[Date], [l0].[Level1_Optional_Id], [l0].[Level1_Required_Id], [l0].[Name], [l0].[OneToMany_Optional_Inverse2Id], [l0].[OneToMany_Optional_Self_Inverse2Id], [l0].[OneToMany_Required_Inverse2Id], [l0].[OneToMany_Required_Self_Inverse2Id], [l0].[OneToOne_Optional_PK_Inverse2Id], [l0].[OneToOne_Optional_Self2Id]
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs:4513]: we should avoid expanding projection for cases when its not needed (entire entity projected, no skip/take etc). can be done in the future

Comment (smitpatel) [reply test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs:4513]: #21320 #21321
