### PR TITLE
SqlServer: Generate False predicate when skip/take both are 0

### LINKED ISSUE #22525: .Take(0) after .Skip causes an SqlException on SQL Server
If you do the following: 

```
db.Articles
	.OrderBy(a => a.Published)
	.Skip(0)
	.Take(0)
	.ToList();
```

then it generates a query using ```OFFSET @__p_0 ROWS FETCH NEXT @__p_0 ROWS ONLY``` which with a zero in Take gives the error ```The number of rows provided for a FETCH clause must be greater then zero.```

If you were to perform this same query in old non-Core Entity Framework you get the expected zero rows returned to you.

### Further technical details

EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.3

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #22525

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SkipTakeCollapsingExpressionVisitor.cs [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+                            selectExpression.GroupBy.Count > 0 ? selectExpression.Predicate : _sqlExpressionFactory.Constant(false),
+                            selectExpression.GroupBy,
+                            selectExpression.GroupBy.Count > 0 ? _sqlExpressionFactory.Constant(false) : null,
+                            new List<OrderingExpression>(0),
+                            limit: null,
+                            offset: null);
+
+                    }
+
+                    bool IsZero(SqlExpression sqlExpression)
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SkipTakeCollapsingExpressionVisitor.cs:87]: And what do we do for Skip/Take with column argument :trollface:

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 2]
```diff
@@ -3152,12 +3154,12 @@ private bool Equals(SelectExpression selectExpression)
         /// <returns> This expression if no children changed, or an expression with the updated children. </returns>
         // This does not take internal states since when using this method SelectExpression should be finalized
         public SelectExpression Update(
-            [NotNull] List<ProjectionExpression> projections,
-            [NotNull] List<TableExpressionBase> tables,
+            [NotNull] IReadOnlyList<ProjectionExpression> projections,
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:3157]: Breaking change, including in obsolete method above?

File: src/EFCore.SqlServer/Query/Internal/SkipTakeCollapsingExpressionVisitor.cs [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        protected override Expression VisitExtension(Expression extensionExpression)
+        {
+            if (extensionExpression is SelectExpression selectExpression)
+            {
+                if (selectExpression.Limit != null
+                    && selectExpression.Offset != null)
+                {
+                    if (IsZero(selectExpression.Limit)
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SkipTakeCollapsingExpressionVisitor.cs:72]: nit: collapse all these conditions into a single if, reducing indentation?

File: test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs [hunk 4]
```diff
@@ -2326,6 +2327,35 @@ public virtual Task GroupBy_aggregate_join_another_GroupBy_aggregate(bool async)
                 elementSorter: o => o.Key);
         }
 
+        [ConditionalTheory]
+        [MemberData(nameof(IsAsyncData))]
+        public virtual Task GroupBy_aggregate_after_skip_0_take_0(bool async)
```
Comment (roji) [inline test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs:2332]: Not sure, but as this is a SQL Server problem, should these tests live exclusively in the SQL Server test suite?

Comment (smitpatel) [reply test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs:2332]: If it works in other providers then what is the issue verifying that?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 2 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:3157]: It is not breaking change if you follow the bases.

Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:3157]: @AndriySvyryd - Is this breaking change? Not sure how this missed API review.
For the obsolete one, it added additional NotNulls but the overload is already obsolete, not sure what would be the way to unbreak it.

Comment (roji) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:3157]: The type change is indeed only a provider-facing binary breaking change only, which should be fine. But if this method used to work for null parameters and doesn't any more, that is more problematic.

File: test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs (hunk 4 above)
Comment (roji) [reply test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs:2332]: Just the fact of adding unnecessary tests to all providers for something that is only a problem for one. I have a lot of PG-only tests which aren't added to the base classes only because EFCore.PG isn't in the EF Core repo, and SQL Server is.

It's also a form of documentation for someone reviewing the tests, to note which provider is actually affected by it etc. Just putting it in the right place.

But no strong feelings here.

**Review by roji — APPROVED** [review]
LGTM apart from the nullability change which we should decide on

**Comment by roji** [comment]
Oops, forgot to remove auto-merge :/ If needed we can discuss/amend post-merge.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 2 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:3157]: Not this method. This method was always marked with NotNull and has Check.NotNull for all the non-nullable arguments.
