### PR TITLE
Fix FreeText tests

### LINKED ISSUE #18199: FreeText_through_navigation is broken
Also `FreeText_through_navigation_with_language_terms` and `Contains_through_navigation`

>  System.InvalidOperationException : The LINQ expression 'LastOrDefault<Employee>(Select<TransparentIdentifier<Employee, Employee>, Employee>(
        source: Where<TransparentIdentifier<Employee, Employee>>(
            source: LeftJoin<Employee, Employee, Nullable<uint>, TransparentIdentifier<Employee, Employee>>(
                outer: DbSet<Employee>, 
                inner: DbSet<Employee>, 
                outerKeySelector: (e) => Property<Nullable<uint>>(e, "ReportsTo"), 
                innerKeySelector: (e0) => Property<Nullable<uint>>(e0, "EmployeeID"), 
                resultSelector: (o, i) => new TransparentIdentifier<Employee, Employee>(
                    Outer = o, 
                    Inner = i
                )), 
            predicate: (e) => FreeText(
                _: (Unhandled parameter: __Functions_0), 
                propertyReference: e.Inner.Title, 
                freeText: "President") && FreeText(
                _: (Unhandled parameter: __Functions_0), 
                propertyReference: e.Outer.Title, 
                freeText: "Inside") && e.Outer.FirstName.Contains("Lau")), 
        selector: (e) => e.Outer))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
  Stack Trace: 
    QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& ) line 51
    QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 284
    RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 72
    QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) line 68
    Database.CompileQuery[TResult](Expression query, Boolean async) line 71
    QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) line 106
    <>c__DisplayClass9_0`1.<Execute>b__0() line 96
    CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) line 84
    CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) line 59
    QueryCompiler.Execute[TResult](Expression query) line 92
    EntityQueryProvider.Execute[TResult](Expression expression) line 79
    Queryable.LastOrDefault[TSource](IQueryable`1 source)
    DbFunctionsSqlServerTest.FreeText_through_navigation() line 175

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #18199

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs [hunk 1]
```diff
@@ -225,15 +227,15 @@ public void FreeText_through_navigation_with_language_terms()
                     c => EF.Functions.FreeText(c.Manager.Title, "President", 1033)
                         && EF.Functions.FreeText(c.Title, "Inside", 1031)
                         && c.FirstName.Contains("Lau"))
-                .LastOrDefault();
+                .FirstOrDefault();
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs:230]: I reckon there is only one matching row in the table, but perhaps we should add orderby instead?

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs [hunk 2]
```diff
@@ -423,16 +425,16 @@ public void Contains_through_navigation()
                 .Where(
                     c => EF.Functions.Contains(c.Manager.Title, "President")
                         && EF.Functions.Contains(c.Title, "\"Ins*\""))
-                .LastOrDefault();
+                .FirstOrDefault();
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs:429]: same here

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs (hunk 1 above)
Comment (smitpatel) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs:230]: Isn't the operator irrelevant here?
What we are testing is translate of FreeText function. So I just added a mix rather than using LastOrDefault everywhere.
