### PR TITLE
Temporal table migrations refactor.

### LINKED ISSUE #27459: SQL Server Migrations: Review temporal table annotations
We seem to be relying heavily on column-level annotations in both the relational model and migration operations. The annotations also seem to be a bit denormalized--we repeat information about the table in each of its columns.

I feel like the memory-optimized tables feature finds a better balance by using both annotations and the backing model in its implementation.

The ultimate goal of this review would be to remove as much as we can from the scaffolded migration.

### LINKED ISSUE #29536: EF Core IsTemporal() creates huge migration
When using EF core to make a table temporal after creation of the table, EF core creates Alter column commands for each field.
This should not be necessary because Temporal is table based, not column based.
Now in the test project you can see there are not that many fields on the entity, but imagine an entity with 30 fields.
This creates a migration that is 1000+ lines of code.

In the old EF core 6 it would create a small migration, but it would recreate the same migration every time you add-migration (this has been fixed here in version 7 but introduced this "bug?")

[Project to reproduce bug](https://github.com/HellHunterMax/DatabaseSelf)

EF Core version: 7.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: windows 10
IDE: Visual Studio 2022 17.4

### LINKED ISSUE #29799: EF7 SqlServer Migration is trying to update columns on History table before creating the History table if any new columns are added in the same migration
I ran into an issue when setting a table to include it's history counterpart, where it will attempt to update the columns on the history table, before the history table is created, if there are any additional columns also being added, like `delete_date` below.

I couldn't find any know issues or roadmap items regarding Temporal/History tables and ordering of SQL queries during the `Update-Database` or `Script-Migration` process. So I don't know if this is a known issue or not, and I know Temporal tables are still being worked on overall. But here are my findings if it helps.

I am unable to upload sample project from my work machine, I might be able to reporduce it from personal machine later if needed.

Steps to reproduce:

1. Create a new table
2. Create Migration to insert new table
3. Add new column to table
4. Set table's `.IsTemporal(true)`
5. Create Migration for new column and is temporal
6. `Update-Database` will fail on second migration

Here is the generated migration from the C# changes for step 5, the second migration.

```C#
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TemporalTest.Migrations
{
    /// <inheritdoc />
    public partial class SetTemporal : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterTable(
                name: "Country")
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

            migrationBuilder.AlterColumn<string>(
                name: "iso_country_code",
                table: "Country",
                type: "nvarchar(2)",
                maxLength: 2,
                nullable: false,
                comment: "ISO standard code of the country",
                oldClrType: typeof(string),
                oldType: "nvarchar(2)",
                oldMaxLength: 2,
                oldComment: "ISO standard code of the country")
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

            migrationBuilder.AlterColumn<string>(
                name: "country_name",
                table: "Country",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: false,
                comment: "Name of the country",
                oldClrType: typeof(string),
                oldType: "nvarchar(100)",
                oldMaxLength: 100,
                oldComment: "Name of the country")
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Country",
                type: "int",
                nullable: false,
                comment: "Primary Key/Id",
                oldClrType: typeof(int),
                oldType: "int",
                oldComment: "Primary Key/Id")
                .Annotation("SqlServer:Identity", "1, 1")
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart")
                .OldAnnotation("SqlServer:Identity", "1, 1");

            migrationBuilder.AddColumn<DateTime>(
                name: "PeriodEnd",
                table: "Country",
                type: "datetime2",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified))
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

            migrationBuilder.AddColumn<DateTime>(
                name: "PeriodStart",
                table: "Country",
                type: "datetime2",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified))
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

            migrationBuilder.AddColumn<DateTime>(
                name: "delete_date",
                table: "Country",
                type: "datetime2",
                nullable: true)
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "PeriodEnd",
                table: "Country")
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

            migrationBuilder.DropColumn(
                name: "PeriodStart",
                table: "Country")
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

            migrationBuilder.DropColumn(
                name: "delete_date",
                table: "Country")
                .Annotation("SqlServer:IsTemporal", true)
                .Annotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .Annotation("SqlServer:TemporalHistoryTableSchema", null)
                .Annotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .Annotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

            migrationBuilder.AlterTable(
                name: "Country")
                .OldAnnotation("SqlServer:IsTemporal", true)
                .OldAnnotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .OldAnnotation("SqlServer:TemporalHistoryTableSchema", null)
                .OldAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .OldAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

            migrationBuilder.AlterColumn<string>(
                name: "iso_country_code",
                table: "Country",
                type: "nvarchar(2)",
                maxLength: 2,
                nullable: false,
                comment: "ISO standard code of the country",
                oldClrType: typeof(string),
                oldType: "nvarchar(2)",
                oldMaxLength: 2,
                oldComment: "ISO standard code of the country")
                .OldAnnotation("SqlServer:IsTemporal", true)
                .OldAnnotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .OldAnnotation("SqlServer:TemporalHistoryTableSchema", null)
                .OldAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .OldAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

            migrationBuilder.AlterColumn<string>(
                name: "country_name",
                table: "Country",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: false,
                comment: "Name of the country",
                oldClrType: typeof(string),
                oldType: "nvarchar(100)",
                oldMaxLength: 100,
                oldComment: "Name of the country")
                .OldAnnotation("SqlServer:IsTemporal", true)
                .OldAnnotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .OldAnnotation("SqlServer:TemporalHistoryTableSchema", null)
                .OldAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .OldAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Country",
                type: "int",
                nullable: false,
                comment: "Primary Key/Id",
                oldClrType: typeof(int),
                oldType: "int",
                oldComment: "Primary Key/Id")
                .Annotation("SqlServer:Identity", "1, 1")
                .OldAnnotation("SqlServer:Identity", "1, 1")
                .OldAnnotation("SqlServer:IsTemporal", true)
                .OldAnnotation("SqlServer:TemporalHistoryTableName", "CountryHistory")
                .OldAnnotation("SqlServer:TemporalHistoryTableSchema", null)
                .OldAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd")
                .OldAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
        }
    }
}

```

This is the SQL generated when running `Script-Migration` targeting only the above migration change.

```SQL
BEGIN TRANSACTION;
GO

ALTER TABLE [Country] ADD [PeriodEnd] datetime2 NOT NULL DEFAULT '9999-12-31T23:59:59.9999999';
GO

ALTER TABLE [Country] ADD [PeriodStart] datetime2 NOT NULL DEFAULT '0001-01-01T00:00:00.0000000';
GO

ALTER TABLE [Country] ADD [delete_date] datetime2 NULL;
GO

ALTER TABLE [CountryHistory] ADD [delete_date] datetime2 NULL;
GO

ALTER TABLE [Country] ADD PERIOD FOR SYSTEM_TIME ([PeriodStart], [PeriodEnd])
GO

ALTER TABLE [Country] ALTER COLUMN [PeriodStart] ADD HIDDEN
GO

ALTER TABLE [Country] ALTER COLUMN [PeriodEnd] ADD HIDDEN
GO

DECLARE @historyTableSchema sysname = SCHEMA_NAME()
EXEC(N'ALTER TABLE [Country] SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [' + @historyTableSchema + '].[CountryHistory]))')

GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20221208140231_SetTemporal', N'7.0.0');
GO

COMMIT;
GO
```

Here is the output when attempting to run `Update-Database` as shown on the first line.

```
PM> Update-Database -Verbose
Using project 'TemporalTest'.
Using startup project 'TemporalTest'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\GIT\Repos\TemporalTest\TemporalTest\bin\Debug\net6.0\TemporalTest.deps.json --additionalprobingpath C:\Users\wmcgowan\.nuget\packages --runtimeconfig C:\GIT\Repos\TemporalTest\TemporalTest\bin\Debug\net6.0\TemporalTest.runtimeconfig.json C:\Users\wmcgowan\.nuget\packages\microsoft.entityframeworkcore.tools\7.0.0\tools\netcoreapp2.0\any\ef.dll database update --verbose --no-color --prefix-output --assembly C:\GIT\Repos\TemporalTest\TemporalTest\bin\Debug\net6.0\TemporalTest.dll --project C:\GIT\Repos\TemporalTest\TemporalTest\TemporalTest.csproj --startup-assembly C:\GIT\Repos\TemporalTest\TemporalTest\bin\Debug\net6.0\TemporalTest.dll --startup-project C:\GIT\Repos\TemporalTest\TemporalTest\TemporalTest.csproj --project-dir C:\GIT\Repos\TemporalTest\TemporalTest\ --language C# --configuration Debug --working-dir C:\GIT\Repos\TemporalTest\TemporalTest --root-namespace TemporalTest --nullable
Using assembly 'TemporalTest'.
Using startup assembly 'TemporalTest'.
Using application base 'C:\GIT\Repos\TemporalTest\TemporalTest\bin\Debug\net6.0'.
Using working directory 'C:\GIT\Repos\TemporalTest\TemporalTest'.
Using root namespace 'TemporalTest'.
Using project directory 'C:\GIT\Repos\TemporalTest\TemporalTest\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'TemporalTest'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Found DbContext 'TestContext'.
Finding DbContext classes in the project...
Using context 'TestContext'.
Finding design-time services referenced by assembly 'TemporalTest'...
Finding design-time services referenced by assembly 'TemporalTest'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'TemporalTest'...
No design-time services were found.
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (29ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Executed DbCommand (29ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Executed DbCommand (23ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (23ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20221208140231_SetTemporal'.
Applying migration '20221208140231_SetTemporal'.
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (11ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE [Country] ADD [PeriodEnd] datetime2 NOT NULL DEFAULT '9999-12-31T23:59:59.9999999';
Executed DbCommand (11ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE [Country] ADD [PeriodEnd] datetime2 NOT NULL DEFAULT '9999-12-31T23:59:59.9999999';
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE [Country] ADD [PeriodStart] datetime2 NOT NULL DEFAULT '0001-01-01T00:00:00.0000000';
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE [Country] ADD [PeriodStart] datetime2 NOT NULL DEFAULT '0001-01-01T00:00:00.0000000';
Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE [Country] ADD [delete_date] datetime2 NULL;
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE [Country] ADD [delete_date] datetime2 NULL;
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE [CountryHistory] ADD [delete_date] datetime2 NULL;
Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE [CountryHistory] ADD [delete_date] datetime2 NULL;
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot find the object "CountryHistory" because it does not exist or you do not have permissions.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:29fb56dd-f6aa-4706-8048-069a0e4aa128
Error Number:4902,State:1,Class:16
Cannot find the object "CountryHistory" because it does not exist or you do not have permissions.
PM> 
```

EF Core version: 7.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Win 10
IDE: Visual Studio 2022 17.4.1

### PR DESCRIPTION
**Pull request by maumar**
Before we used to put temporal annotations on temporal tables and all their columns, so that it's easier to process. Problem was that this would generate very noisy migrations when converting from regular table to temporal and vice versa. Every column would have an AlterColumn operation (which we would ignore during processing, but they were nonetheless generated in migration files). Also, we were using relatively simple logic to track state of our temporal tables. Some operations require temporary disabling of the versioning/period, and we need to keep track of that so that we don't try to disable period twice, or forget to enable it later. The way we did it could lead to invalid SQL in some non-trivial scenarios (e.g. converting table to temporal and adding a new column at the same time)

The new approach is to only put temporal annotations on the table itself, and the period columns. Regular columns of the temporal table don't have any temporal annotations on them anymore and we reason about temporal information based on other table-based migration operation in the batch and, if need be, on the relational model. We also keep track of the actual temporal information for every operation (rather than keeping global dictionaries of period/version), so that complex migrations, involving multiple operations are more robust. To achieve that we compute the initial (temporal) state of all the tables involved in the migration. We scan all the table operations, and if some info is missing we get it from relational model. Then we do the proper processing of the migration operations - when we encounter table operation, we update the temporal information for that table (since table operations contain relevant temporal annotations). For all other operations we extract the current temporal state for the table involved, and reason based on that info.

Fixes #27459 - SQL Server Migrations: Review temporal table annotations 
Fixes #29536 - EF Core IsTemporal() creates huge migration 
Fixes #29799 - EF7 SqlServer Migration is trying to update columns on History table before creating the History table if any new columns are added in the same migration

### CODE REVIEW

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 1]
```diff
@@ -2347,98 +2309,313 @@ private static bool HasDifferences(IEnumerable<IAnnotation> source, IEnumerable<
...
+                {
+                    var tableName = createTableOperation.Name;
+                    var rawSchema = createTableOperation.Schema;
+                    var schema = rawSchema ?? model?.GetDefaultSchema();
+                    if (!temporalTableInformationMap.ContainsKey((tableName, rawSchema)))
+                    {
+                        var temporalTableInformation = BuildTemporalInformationFromMigrationOperation(schema, createTableOperation);
+                        temporalTableInformationMap[(tableName, rawSchema)] = temporalTableInformation;
+                    }
+                    // no need to remove from missingTemporalTableInformation - CreateTable should be first operation for this table
```
Comment (maumar) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2340]: @bricelam is it even possible to have a DROP TABLE (or RENAME TABLE) and then CREATE TABLE with the same table name and schema in one migration?

File: src/EFCore.SqlServer/Design/Internal/SqlServerCSharpRuntimeAnnotationCodeGenerator.cs [hunk 2]
```diff
@@ -89,6 +89,9 @@ public override void Generate(IColumn column, CSharpRuntimeAnnotationCodeGenerat
             annotations.Remove(SqlServerAnnotationNames.TemporalHistoryTableSchema);
             annotations.Remove(SqlServerAnnotationNames.TemporalPeriodStartColumnName);
             annotations.Remove(SqlServerAnnotationNames.TemporalPeriodEndColumnName);
+            // TODO: should we remove the legacy annotations also?
```
Comment (maumar) [inline src/EFCore.SqlServer/Design/Internal/SqlServerCSharpRuntimeAnnotationCodeGenerator.cs:92]: @AndriySvyryd

Comment (AndriySvyryd) [reply src/EFCore.SqlServer/Design/Internal/SqlServerCSharpRuntimeAnnotationCodeGenerator.cs:92]: Here we need to remove all annotations that are currently added to the relational model, but are not used at runtime (i.e. they are only for migrations)

File: src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs [hunk 3]
```diff
@@ -253,7 +253,7 @@ public override IEnumerable<IAnnotation> For(IColumn column, bool designTime)
         }
 
         var entityType = (IEntityType)column.Table.EntityTypeMappings.First().TypeBase;
-        if (entityType.IsTemporal() && designTime)
+        if (entityType.IsTemporal())
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs:256]: Why do we need to add these for the runtime relational model?

File: src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs [hunk 4]
```diff
@@ -110,29 +85,39 @@ public override IEnumerable<IAnnotation> ForRename(IColumn column)
...
+            //        SqlServerAnnotationNames.TemporalPeriodStartColumnName,
+            //        periodStartColumnName);
+            //}
+
+            //if (column[SqlServerAnnotationNames.TemporalPeriodEndColumnName] is string periodEndColumnName)
+            //{
+            //    yield return new Annotation(
+            //        SqlServerAnnotationNames.TemporalPeriodEndColumnName,
+            //        periodEndColumnName);
+            //}
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs:120]: Remove

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 5]
```diff
@@ -2347,98 +2309,313 @@ private static bool HasDifferences(IEnumerable<IAnnotation> source, IEnumerable<
...
+                    {
                         operations.Add(operation);
+                    }
 
-                        versioningMap.Remove((table, schema));
-                        periodMap.Remove((table, schema));
-                        break;
+                    // we removed the table, so we no longer need it's temporal information
+                    // there will be no more operations involving this table
+                    if (temporalTableInformationMap.ContainsKey((tableName, schema)))
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2546]: No need to call `ContainsKey` first

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 6]
```diff
@@ -2347,98 +2309,313 @@ private static bool HasDifferences(IEnumerable<IAnnotation> source, IEnumerable<
...
+                            temporalInformation,
+                            suppressTransaction,
+                            shouldEnableVersioning: true);
+                    }
+
+                    operations.Add(operation);
+
+                    // since table was renamed, update entry in the temporal info map
+                    temporalTableInformationMap[(renameTableOperation.NewName!, renameTableOperation.NewSchema)] = temporalInformation;
+                    if (temporalTableInformationMap.ContainsKey((tableName, schema)))
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2578]: Ditto

File: test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs [hunk 7]
```diff
@@ -8262,6 +8262,1098 @@ public virtual async Task Temporal_table_delete_column_rename_and_alter_period_c
 """);
     }
 
+    [ConditionalFact]
+    public virtual async Task Temporal_multiop_convert_to_temporal_and_add_new_column()
```
Comment (AndriySvyryd) [inline test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs:8266]: Add a test for going from a default temporal table (just `.IsTemporal()`) to a temporal table with period start and end

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs (hunk 3 above)
Comment (maumar) [reply src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs:256]: i just removed this check because first thing we do in the method is:
```
        if (!designTime)
        {
            yield break;
        }
```

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs (hunk 1 above)
Comment (maumar) [reply src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2340]: talked to Brice about it - we will never drop and then create the same table, which simplifies the logic a bit

File: src/EFCore.SqlServer/Design/Internal/SqlServerCSharpRuntimeAnnotationCodeGenerator.cs (hunk 2 above)
Comment (maumar) [reply src/EFCore.SqlServer/Design/Internal/SqlServerCSharpRuntimeAnnotationCodeGenerator.cs:92]: what about annotations that we used to add to the model but now we don't? Can they still be present here, in some scenarios where people upgrade EF versions?

Comment (AndriySvyryd) [reply src/EFCore.SqlServer/Design/Internal/SqlServerCSharpRuntimeAnnotationCodeGenerator.cs:92]: > Can they still be present here, in some scenarios where people upgrade EF versions?

No, only the current model can go through here.

File: src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs [hunk 8]
```diff
@@ -35,55 +35,22 @@ public override IEnumerable<IAnnotation> ForRemove(ITable table)
...
-
-            yield return new Annotation(
-                SqlServerAnnotationNames.TemporalHistoryTableName,
-                constraint.Table[SqlServerAnnotationNames.TemporalHistoryTableName]);
-
-            yield return new Annotation(
-                SqlServerAnnotationNames.TemporalHistoryTableSchema,
-                constraint.Table[SqlServerAnnotationNames.TemporalHistoryTableSchema]);
-        }
+        yield break;
```
Comment (bricelam) [inline src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs:38]: Can remove method override.

File: src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs [hunk 9]
```diff
@@ -35,55 +35,22 @@ public override IEnumerable<IAnnotation> ForRemove(ITable table)
...
     }
 
     /// <inheritdoc />
     public override IEnumerable<IAnnotation> ForRemove(IColumn column)
     {
         if (column.Table[SqlServerAnnotationNames.IsTemporal] as bool? == true)
```
Comment (bricelam) [inline src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs:44]: This check seems unnecessary (below too). Columns won't have TemporalIsPeriodStart/EndColumn annotations if they're not on a temporal table, right?

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 10]
```diff
@@ -2347,98 +2309,313 @@ private static bool HasDifferences(IEnumerable<IAnnotation> source, IEnumerable<
...
         foreach (var operation in migrationOperations)
         {
             if (operation is EnsureSchemaOperation ensureSchemaOperation)
             {
                 availableSchemas.Add(ensureSchemaOperation.Name);
             }
 
-            var isTemporal = operation[SqlServerAnnotationNames.IsTemporal] as bool? == true;
-            if (isTemporal)
+            if (operation is not ITableMigrationOperation)
```
Comment (bricelam) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2469]: I think you can capture here and avoid a cast below.

```cs
if (operation is not ITableMigrationOperation tableMigrationOperation)
```

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 11]
```diff
@@ -2347,98 +2309,313 @@ private static bool HasDifferences(IEnumerable<IAnnotation> source, IEnumerable<
...
-                        // marked as versioning disabled, so we enable it in the end for the new table
-                        versioningMap.Remove((table, schema));
-                        versioningMap[(renameTableOperation.NewName, renameTableOperation.NewSchema)] =
-                            (historyTableName!, historyTableSchema, suppressTransaction);
+                case RenameTableOperation renameTableOperation:
+                {
+                    if (temporalInformation is null)
+                    {
+                        temporalInformation = BuildTemporalInformationFromMigrationOperation(schema, renameTableOperation);
+                    }
```
Comment (bricelam) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2559]:
```suggestion
                    temporalInformation ??= BuildTemporalInformationFromMigrationOperation(schema, renameTableOperation);
```

Comment (bricelam) [reply src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2559]: (below too)

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 12]
```diff
@@ -2347,98 +2309,313 @@ private static bool HasDifferences(IEnumerable<IAnnotation> source, IEnumerable<
...
+            }
+        }
+
+        // fill the missing temporal information from Relational Model - it's the second best source we have
+        // if we can't figure out proper temporal info from table annotations,
+        // and we don't have it in relational model (for whatever reason) we assume table is not temporal
+        // this last step is purely defensive and shouldn't happen in real situations
+        foreach (var missingInfo in missingTemporalTableInformation)
+        {
+            var table = model?.GetRelationalModel().FindTable(missingInfo.TableName, missingInfo.Schema)!;
```
Comment (bricelam) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2437]: What happens if we *just* rely on the backing model? Can we remove all annotations from the operations and still make it work?

File: src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs [hunk 13]
```diff
@@ -275,12 +275,14 @@ public override IEnumerable<IAnnotation> For(IColumn column, bool designTime)
...
-            yield return new Annotation(SqlServerAnnotationNames.TemporalPeriodStartColumnName, periodStartColumnName);
-            yield return new Annotation(SqlServerAnnotationNames.TemporalPeriodEndColumnName, periodEndColumnName);
+            if (column.Name == periodStartColumnName)
+            {
+                yield return new Annotation(SqlServerAnnotationNames.TemporalIsPeriodStartColumn, true);
+            }
+            else if (column.Name == periodEndColumnName)
+            {
+                yield return new Annotation(SqlServerAnnotationNames.TemporalIsPeriodEndColumn, true);
+            }
```
Comment (bricelam) [inline src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs:285]: This change should be reflected in the SnapshotModelProcessor.

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 14]
```diff
@@ -1613,14 +1576,13 @@ protected override void Generate(UpdateDataOperation operation, IModel? model, M
             builder.Append(" SPARSE");
         }
 
-        var periodStartColumnName = operation[SqlServerAnnotationNames.TemporalPeriodStartColumnName] as string;
-        var periodEndColumnName = operation[SqlServerAnnotationNames.TemporalPeriodEndColumnName] as string;
+        var isPeriodStartColumn = operation[SqlServerAnnotationNames.TemporalIsPeriodStartColumn] as bool? == true;
+        var isPeriodEndColumn = operation[SqlServerAnnotationNames.TemporalIsPeriodEndColumn] as bool? == true;
```
Comment (bricelam) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:1580]: May still need to look at the previous annotations for existing migrations.

**Review by bricelam — APPROVED** [review]
LGTM. Just need to test scenarios with existing migrations.

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs (hunk 12 above)
Comment (bricelam) [reply src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2437]: (Not sayint I want to; just wondering how far we could move the dial.)

File: src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs (hunk 9 above)
Comment (maumar) [reply src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs:44]: yup, good point

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs (hunk 12 above)
Comment (maumar) [reply src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2437]: doesn't work for some cases, e.g. convert from non-temporal to temporal and vice versa - relational model only contains the result state, so we don't know what we are converting from

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs (hunk 11 above)
Comment (maumar) [reply src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2559]: temporalInformation is now guaranteed to be present at this point, so the check is no longer needed and I have removed it

File: src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs (hunk 13 above)
Comment (bricelam) [reply src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs:285]: After chatting about this, it looks like it will be handled when we create the relational model for the snapshot. We shouldn't need to update SnapshotModelProcessor.

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 15]
```diff
@@ -2347,98 +2320,288 @@ private IReadOnlyList<MigrationOperation> RewriteOperations(
...
+                    {
                         operations.Add(operation);
+                    }
 
-                        versioningMap.Remove((table, schema));
-                        periodMap.Remove((table, schema));
-                        break;
+                    // we removed the table, so we no longer need it's temporal information
+                    // there will be no more operations involving this table
+                    temporalTableInformationMap.Remove((tableName, schema));
```
Comment (roji) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2543]: If the same table is dropped and then created, this causes the CreateTable operation to throw as the table is no longer in `temporalTableInformationMap`; this is the cause for #35162.
