### PR TITLE
Fix to #1833 - Support filtered Include

### LINKED ISSUE #1833: Support filtered Include
We keep this issue to track specifying filters inline when you specify eager loading in a query. However there are many scenarios that can be satisfied with global query filters:

## Please learn about [global query filters](https://docs.microsoft.com/ef/core/querying/filters)

We are seeing that a large portion of the scenarios customers want this feature for can already be better addressed using [global query filters](https://docs.microsoft.com/ef/core/querying/filters). Please try to understand that feature before you add your vote to this issue. 

We are keeping this issue open **only to represent the ability to specify filters on Include on a per-query basis**, which we understand can be convenient on some cases. 

## Original issue:

Doing a `.Where()` inside a `.Include()` is allowed (by the syntax, it fails in execution). However, if you then follow that up with a `.ThenInclude()`, like so:

``` csharp
.Include(t => t.Ratings.Where(r => !r.IsDeleted))
.ThenInclude(r => r.User)
```

You get the following error:

> 'IEnumerable<Rating>' does not contain a definition for 'User' and no extension method 'User' accepting a first argument of type 'IEnumerable<Rating>' could be found (are you missing a using directive or an assembly reference?)

Is this something you're aware of and going to allow in a future version, or am I just doing something wrong and It's already supported?

### PR DESCRIPTION
**Pull request by maumar**
Allows for additional operations to be specified inside Include/ThenInclude expression when the navigation is a collection:
- Where,
- OrderBy(Descending)/ThenBy(Descending),
- Skip,
- Take.

Those additional operations are treated like any other within the query, so translation restrictions apply.

Collections included using new filter operations are considered to be loaded.

Only one filter is allowed per navigation. In cases where same navigation is included multiple times (e.g. Include(A).ThenInclude(A_B).Include(A).ThenInclude(A_C)) filter should only be applied once.
Alternatively the same exact filter should be applied to all.

### CODE REVIEW

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs [hunk 1]
```diff
@@ -92,11 +94,24 @@ public IncludeTreeNode(IEntityType entityType, EntityReference entityReference)
...
-                    return existingValue;
+                    if (filterExpression == null)
+                    {
+                        return existingValue;
+                    }
+
+                    if (existingValue.FilterExpression != null
+                        && filterExpression != null)
+                    {
+                        throw new NotSupportedException("Multiple filtered include calls on same navigation are not supported.");
```
Comment (maumar) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs]: TODO: will do the proper infra for exceptions

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs [hunk 2]
```diff
@@ -92,11 +94,24 @@ public IncludeTreeNode(IEntityType entityType, EntityReference entityReference)
...
+                    }
+
+                    // if stored entry doesn't have filter expression, but the new one does
+                    // remove the old one, so the new one can be added in its place
+                    Remove(navigation);
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs]: Don't

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs [hunk 3]
```diff
@@ -1473,13 +1486,35 @@ private IncludeTreeNode PopulateIncludeTree(IncludeTreeNode includeTreeNode, Exp
...
 
                     break;
+
+                case MethodCallExpression methodCallExpression
+                    when methodCallExpression.Method.DeclaringType == typeof(Queryable):
+                {
+                    if (!methodCallExpression.Method.IsGenericMethod
+                        || !_supportedFilteredIncludeOperations.Contains(methodCallExpression.Method.GetGenericMethodDefinition()))
+                    {
+                        throw new NotSupportedException("Unsupported operation inside Include call: " + methodCallExpression.Method.Name + ".");
```
Comment (maumar) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: TODO: will do the proper infra for exceptions

File: test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs [hunk 4]
```diff
@@ -4980,5 +4980,284 @@ public virtual Task Contains_over_optional_navigation_with_null_entity_reference
...
+            var query = ctx.LevelOne.Select(l1 => new
+            {
+                l1.Id,
+                FullInclude = ctx.LevelTwo.Include(l2 => l2.OneToMany_Optional2).ToList(),
+                FilteredInclude = ctx.LevelTwo.Include(l2 => l2.OneToMany_Optional2.Where(x => x.Id != l1.Id)).ToList() });
+            var result = query.ToList();
+        }
+
+        [ConditionalFact]
+        public virtual void Filtered_include_is_considered_loaded()
```
Comment (maumar) [inline test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs]: @ajcvickers any more scenarios around collection being loaded?

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs [hunk 5]
```diff
@@ -1473,13 +1486,35 @@ private IncludeTreeNode PopulateIncludeTree(IncludeTreeNode includeTreeNode, Exp
...
+                    }
+
+                    var prm = Expression.Parameter(methodCallExpression.Arguments[0].Type, "prm");
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: don't name it. You can run into clashes

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs [hunk 6]
```diff
@@ -1473,13 +1486,35 @@ private IncludeTreeNode PopulateIncludeTree(IncludeTreeNode includeTreeNode, Exp
...
+                    var body = ReplacingExpressionVisitor.Replace(methodCallExpression.Arguments[0], prm, methodCallExpression);
+
+                    if (filterExpression != null)
+                    {
+                        body = ReplacingExpressionVisitor.Replace(filterExpression.Parameters[0], body, filterExpression.Body);
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: Instead of recreating this way, consider building up bottom to top

Comment (maumar) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: will leave as is. There are some problems with bottom up, i.e. AddNavigation method needs to know if the navigation has a query filter (and throw if multiple query filters are defined for the same navigation), so the filtered include information needs to propagate down to the root anyway

**Comment by maumar** [comment]
new version up @smitpatel

**Comment by smitpatel** [comment]
and all checks failed 😄

File: src/EFCore/Properties/CoreStrings.resx [hunk 7]
```diff
@@ -1290,6 +1290,12 @@
   <data name="IncludeOnNonEntity" xml:space="preserve">
     <value>Include has been used on non entity queryable.</value>
   </data>
+  <data name="MultipleFilteredIncludesOnSameNavigation" xml:space="preserve">
+    <value>Multiple filtered include operations on the same navigation '{navigationName}' are not supported.</value>
```
Comment (smitpatel) [inline src/EFCore/Properties/CoreStrings.resx]: If we are supporting more than just where then we need to create a new term rather than filtered include
@dotnet/efcore

**Comment by maumar** [comment]
fixed again, missed one of the sqlite tests - they all need to be skipped cause lack of apply

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs (hunk 6 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: bad perf.
And throwing can still be done in bottom to top. It is about how you are separating navigation from the filter expression. Once you have both information you can still throw if multiple includes used.

File: src/EFCore/Properties/CoreStrings.resx (hunk 7 above)
Comment (maumar) [reply src/EFCore/Properties/CoreStrings.resx]: "the spirit" of the feature is still about filter. Ordering is only added for suppose of Skip/Take, so maybe keeping the name is not so bad. We will never have projections in there, that's for sure so its not like we are future-proofing with the less specific name. 

However I'm fine if ppl think otherwise. Something like "modified include", "altered include", "composable include"?

Comment (smitpatel) [reply src/EFCore/Properties/CoreStrings.resx]: Conditional include.

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs (hunk 6 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: You shouldn't need to use ReplacingExpressionVisitor here.

File: src/EFCore/Properties/CoreStrings.resx (hunk 7 above)
Comment (AndriySvyryd) [reply src/EFCore/Properties/CoreStrings.resx]: "Extended include", "augmented include"
But taking a step back we don't support multiple normal includes on the same navigation either, so perhaps just make the message more generic

Comment (maumar) [reply src/EFCore/Properties/CoreStrings.resx]: works for me. lets see what others say

**Comment by maumar** [comment]
another version up @smitpatel

File: src/EFCore/Properties/CoreStrings.resx (hunk 7 above)
Comment (maumar) [reply src/EFCore/Properties/CoreStrings.resx]: we support it in a sense that it doesn't throw :)

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs (hunk 6 above)
Comment (maumar) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: added a decidated method, not as robust as the visitor but should be fine since we only support very limited set of operations

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs [hunk 8]
```diff
@@ -1473,16 +1486,60 @@ private IncludeTreeNode PopulateIncludeTree(IncludeTreeNode includeTreeNode, Exp
...
+                    {
+                        throw new NotSupportedException(CoreStrings.FilteredIncludeOperationNotSupported(methodCallExpression.Method.Name));
+                    }
+
+                    var result = PopulateIncludeTree(includeTreeNode, methodCallExpression.Arguments[0], withFilter: true);
+
+                    // we only need to attach filter expression at the top level
+                    if (!withFilter)
+                    {
+                        var body = ReplaceMethodChainRoot(expression, result.FilterExpression.Parameters[0]);
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: Why do you need recursive function for this? The recursion of tree traversal is already covered by PopulateIncludeTree.

Comment (maumar) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: rewrite only happens on the top level, so it needs to be recursive there. This way we don't need to re-create a lambda every time. Doing it at every level is more elegant but worse perf :trollface:

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs [hunk 9]
```diff
@@ -159,16 +160,21 @@ private Expression TryExpandNavigation(Expression root, MemberIdentity memberIde
...
 
                     var ownedExpansion = new OwnedNavigationReference(root, navigation, ownedEntityReference);
                     if (navigation.IsCollection)
                     {
                         var elementType = ownedExpansion.Type.TryGetSequenceType();
-                        var subquery = Expression.Call(
-                            QueryableMethods.AsQueryable.MakeGenericMethod(elementType),
-                            ownedExpansion);
+
+                        var subquery = filterExpression != null
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs]: Move whole processing to `IncludeExpandingExpressionVisitor`
Intercept MaterializeCollectionNavigation coming out from a nav expansion and attach the filter on that subquery.

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs [hunk 10]
```diff
@@ -1445,12 +1458,12 @@ var outboundNavigations
...
             foreach (var navigation in outboundNavigations)
             {
-                var addedIncludeTreeNode = includeTreeNode.AddNavigation(navigation);
+                var addedIncludeTreeNode = includeTreeNode.AddNavigation(navigation, withFilter: false);
                 PopulateEagerLoadedNavigations(addedIncludeTreeNode);
             }
         }
 
-        private IncludeTreeNode PopulateIncludeTree(IncludeTreeNode includeTreeNode, Expression expression)
+        private IncludeTreeNode PopulateIncludeTree(IncludeTreeNode includeTreeNode, Expression expression, bool withFilter)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: Remove parameter withFilter. MemberExpression would just get/create new IncludeTreeNode.
When processing methodcall, see if source is MemberExpression, if filter is already present then throw exception on it.

Also remove case for parameter expression rather short in memberexpression if innerExpression is parameter.
That would avoid processing of include like `Include(e => e.Orders).ThenInclude(e => e.AsQueryable().Where())` which is invalid. Also add a regression test for it.

File: test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs [hunk 11]
```diff
@@ -4980,5 +4980,284 @@ public virtual Task Contains_over_optional_navigation_with_null_entity_reference
...
+                {
+                    new ExpectedFilteredInclude<Level1, Level2>(
+                        e => e.OneToMany_Optional1,
+                        "OneToMany_Optional1",
+                        includeFilter: x => x.OrderBy(x => x.Name).Skip(1).Take(3))
+                });
+        }
+
+        [ConditionalFact]
+        public virtual void Filtered_include_Skip_without_OrderBy()
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs]: Also take without orderby

File: test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs [hunk 12]
```diff
@@ -4980,5 +4980,284 @@ public virtual Task Contains_over_optional_navigation_with_null_entity_reference
...
+                        "OneToMany_Optional1",
+                        includeFilter: x => x.Where(x => x.Name != "Bar").OrderByDescending(x => x.Name).Skip(1))
+                });
+        }
+
+        [ConditionalTheory]
+        [MemberData(nameof(IsAsyncData))]
+        public virtual async Task Filtered_include_filter_set_on_same_navigation_twice(bool async)
+        {
+            var message = (await Assert.ThrowsAsync<NotSupportedException>(
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs]: InvalidOperationException. We don't throw NotSupportedExceptions.

File: test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs [hunk 13]
```diff
@@ -4980,5 +4980,284 @@ public virtual Task Contains_over_optional_navigation_with_null_entity_reference
...
+
+        [ConditionalTheory]
+        [MemberData(nameof(IsAsyncData))]
+        public virtual Task Filtered_include_and_non_filtered_include_on_same_navigation2(bool async)
+        {
+            return AssertIncludeQuery(
+                async,
+                ss => ss.Set<Level1>()
+                    .Include(l1 => l1.OneToMany_Optional1.Where(x => x.Name != "Foo").OrderBy(x => x.Id).Take(3))
+                    .Include(l1 => l1.OneToMany_Optional1),
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs]: Also add a test with ThenInclude after this. The reason user may need to use same include without filter again is ThenInclude.

File: test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs [hunk 14]
```diff
@@ -4980,5 +4980,284 @@ public virtual Task Contains_over_optional_navigation_with_null_entity_reference
...
+            foreach (var resultElement in result)
+            {
+                var entry = ctx.Entry(resultElement);
+                Assert.True(entry.Navigation("OneToMany_Optional1").IsLoaded);
+            }
+        }
+
+        [ConditionalTheory]
+        [MemberData(nameof(IsAsyncData))]
+        public virtual async Task Filtered_include_with_Distinct_throws(bool async)
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs]: Add a test where navigation is registered as reference navigation in EF Core metadata but implements IEnumerable<> and will allow you to write filtered include syntax. (Essentially filterExpression when put on non collection navigation should throw.

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs (hunk 9 above)
Comment (maumar) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs]: result of the nav expansion can be a nested MaterializeCollectionNavigation (e.g. two include collection based off of same root entity). So I would have to visit the entire expression. Why do you think current approach is problematic?

Comment (smitpatel) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs]: Filters are part of include, Includes are expanded by IncludingExpandingEV which utilizes ExpandingEV. These to be inside ExpandingEV is wrong separation.
How is nesting done? inner level or outer level? From my understanding, TryExpandNavigation would expand only 1 navigation at time. So you can always intercept and process it. If there are multiple expansion then the existing MCE would be put inside EntityExpression of outer Include. May be nesting could be changed so that you can always unwrap first one. If all these does not make sense then let me know I can look into it too. 😄

File: src/EFCore/Properties/CoreStrings.resx (hunk 7 above)
Comment (maumar) [reply src/EFCore/Properties/CoreStrings.resx]: new message:

Different filters 'navigation
    .Where(x => x.Name != "Bar")
    .OrderByDescending(x => x.Name)
    .Take(3)' and 'navigation
    .Where(x => x.Name != "Foo")
    .OrderBy(x => x.Id)
    .Take(3)' have been applied on the same included navigation. Only one unique filter per navigation is allowed. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.

File: src/EFCore/Properties/CoreStrings.resx [hunk 15]
```diff
@@ -747,8 +747,8 @@
   <data name="AmbiguousForeignKeyPropertyCandidates" xml:space="preserve">
     <value>Both relationships between '{firstDependentToPrincipalNavigationSpecification}' and '{firstPrincipalToDependentNavigationSpecification}' and between '{secondDependentToPrincipalNavigationSpecification}' and '{secondPrincipalToDependentNavigationSpecification}' could use {foreignKeyProperties} as the foreign key. To resolve this configure the foreign key properties explicitly on at least one of the relationships.</value>
   </data>
-  <data name="InvalidIncludeLambdaExpression" xml:space="preserve">
-    <value>The {methodName} property lambda expression '{includeLambdaExpression}' is invalid. The expression should represent a property access: 't =&gt; t.MyProperty'. To target navigations declared on derived types, specify an explicitly typed lambda parameter of the target type, E.g. '(Derived d) =&gt; d.MyProperty'. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.</value>
+  <data name="InvalidIncludeExpression" xml:space="preserve">
```
Comment (maumar) [inline src/EFCore/Properties/CoreStrings.resx]: TMI?

**Comment by maumar** [comment]
new version up @smitpatel

File: test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs (hunk 14 above)
Comment (maumar) [reply test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs]: Do people actually do that? Seems like very contrived scenario.

Comment (smitpatel) [reply test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs]: It's negative case example. Rather than ignoring (which what we are doing currently when we see non-navigation in Include, we should change that), we can throw a better error message.

Comment (smitpatel) [reply test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs]: On note of reference nav which implements IEnumerable, it is not impossible.

File: src/EFCore/Properties/CoreStrings.resx [hunk 16]
```diff
@@ -747,8 +747,8 @@
...
+    <value>The expression '{expression}' is invalid inside Include operation. The expression should represent a property access: 't =&gt; t.MyProperty'. To target navigations declared on derived types, specify an explicitly typed lambda parameter of the target type, E.g. '(Derived d) =&gt; d.MyProperty'. Collection navigation access can be filtered by composing Where, OrderBy(Descending), ThenBy(Descending), Skip or Take operations. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.</value>
```
Comment (smitpatel) [inline src/EFCore/Properties/CoreStrings.resx]: Do we not support `t => ((Derived)t).DerivedNav`? 
@dotnet/efcore for exception message review.

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs [hunk 17]
```diff
@@ -532,6 +531,20 @@ private Expression ExpandIncludesHelper(Expression root, EntityReference entityR
                         included = ExpandIncludesHelper(included, innerEntityReference);
                     }
 
+                    if (included is MaterializeCollectionNavigationExpression materializeCollectionNavigation)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs]: Make it else if. Previous if checks IsCollection, non collection would not generate MCNE. Short-circuit.

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs [hunk 18]
```diff
@@ -786,19 +800,92 @@ private NavigationExpansionExpression ProcessInclude(NavigationExpansionExpressi
...
+                        methodCallExpression.Update(methodCallExpression.Object, arguments),
+                        filterExpression.Parameters);
+
+                    return (result, filterExpression);
+                }
+
+                throw new InvalidOperationException(CoreStrings.InvalidIncludeExpression(includeExpression));
+            }
+
+            Expression FormatFilter(Expression expression)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: Where is this used?

File: test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs [hunk 19]
```diff
@@ -4980,5 +4980,461 @@ public virtual Task Contains_over_optional_navigation_with_null_entity_reference
...
+            using var ctx = CreateContext();
+            var query = ctx.LevelOne.Include(l1 => l1.OneToMany_Optional1.Skip(1));
+            var result = query.ToList();
+        }
+
+        [ConditionalFact]
+        public virtual void Filtered_include_Take_without_OrderBy()
+        {
+            using var ctx = CreateContext();
+            var query = ctx.LevelOne.Include(l1 => l1.OneToMany_Optional1.Skip(1));
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs]: Use take. 🤦‍♂

File: test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs [hunk 20]
```diff
@@ -4980,5 +4980,461 @@ public virtual Task Contains_over_optional_navigation_with_null_entity_reference
...
+            var result = query.ToList();
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs]: verify result no?

File: test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs [hunk 21]
```diff
@@ -34,5 +34,27 @@ public override Task Include_inside_subquery(bool async)
...
         public override Task SelectMany_with_outside_reference_to_joined_table_correctly_translated_to_apply(bool async) => null;
         public override Task Nested_SelectMany_correlated_with_join_table_correctly_translated_to_apply(bool async) => null;
+        public override void Filtered_include_Skip_without_OrderBy() { }
+        public override void Filtered_include_Take_without_OrderBy() { }
+        public override Task Filtered_include_after_different_filtered_include_same_level(bool async) => null;
+        public override Task Filtered_include_after_different_filtered_include_different_level(bool async) => null;
+        public override Task Filtered_include_after_reference_navigation(bool async) => null;
+        public override Task Filtered_include_and_non_filtered_include_on_same_navigation1(bool async) => null;
+        public override Task Filtered_include_and_non_filtered_include_on_same_navigation2(bool async) => null;
+        public override Task Filtered_include_basic_OrderBy_Take(bool async) => null;
```
Comment (smitpatel) [inline test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs]: Does some of this work? Especially Take? Do we not convert it to Left join using window function?

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs (hunk 18 above)
Comment (maumar) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: exception message

File: test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs (hunk 20 above)
Comment (maumar) [reply test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs]: can't really guarantee without orderby, just eyeballing the sql

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs [hunk 22]
```diff
@@ -786,19 +800,92 @@ private NavigationExpansionExpression ProcessInclude(NavigationExpansionExpressi
...
+
                     entityReference.SetLastInclude(lastIncludeTree);
                 }
 
                 return source;
             }
 
             throw new InvalidOperationException(CoreStrings.IncludeOnNonEntity);
+
+            (Expression result, LambdaExpression filterExpression) ExtractIncludeFilter(Expression currentExpression, Expression includeExpression)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: static?

File: test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs (hunk 21 above)
Comment (maumar) [reply test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs]: i re-checked, they all fail with APPLY errors

Comment (smitpatel) [reply test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs]: File an issue, I will debug.

File: src/EFCore/Properties/CoreStrings.resx (hunk 16 above)
Comment (maumar) [reply src/EFCore/Properties/CoreStrings.resx]: yup, fixed

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs (hunk 17 above)
Comment (maumar) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs]: i actually did that initially. Breaks for entity.Include(e => e.Reference.Collection.Where(...)) since the previous block handles first navigation (reference) and then calls ExpandIncludesHelper again on the following collection.

**Comment by onurh** [comment]
Are you planning to put this any 3.x version?

**Comment by roji** [comment]
@onurh no, this new feature will not be backported to any 3.x version. However, consider trying out the 5.0 previews - they are generally well-tested and work well.
