### PR TITLE
Fix key generation validation for TPC.

### LINKED ISSUE #31629: Incorrect warning for TPC and Guid Id
I get the following error when I generate the initial migration for my model: "The entity type 'xxx' is using the table per concrete type mapping strategy, but property 'Id' is configured with an incompatible database-generated default. Configure a compatible value generation strategy if available, or use non-generated key values."

Here 'xxx' is a concrete entity type. I am indeed using Type-Per-Concrete Class for all entities in the model. The Id property is declared in an abstract base class as shown in the listing below. The generated model snapshot from the migration includes b => b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT") for the "xxx" entity.

        [Key]
        public Guid Id {
            get { 
                return this._id;
            }
            private set {
                ...
            }
        }
        private Guid _id;

Can you tell me what is going wrong here? I'm not clear what the message means -- what incompatibility is being referred to? Isn't the Guid supposed to be database generated? 

One other question, relating to the fact that I am using SQLite. I noticed some talk out there about the Guid being stored in uppercase instead of standard lower case by SQLite, and this causing various problems during update. See [19651](https://github.com/dotnet/efcore/issues/19651) and [this StackOverflow discussion](https://stackoverflow.com/questions/69209096/guid-values-stored-in-uppercase-by-ef-core-5-and-sqlite). However these references are a bit old, and I am not clear what the final resolution of these questions is. At one point (unfortunately not reproducible) I saw an upper case Guid values in my database and I received an error message saying that 0 rows were updated instead of 1, which fits the problem description in these articles. What is the current advice in relation to casing the Guid?  

P.S. Since SQLite doesn't support autoincrement or named increment sequences, as far as I can tell the only real option is to use Guid for the Id. If there are alternatives I would be interested.

### PR DESCRIPTION
**Pull request by cincuranet**
* This makes sure we're validating only root entity.
* For TPC the `entityType.GetTableName() != null` already covered.

Fixes #31629

### CODE REVIEW

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs [hunk 1]
```diff
@@ -1940,8 +1940,8 @@ private static bool IsIdentifyingPrincipal(IEntityType dependentEntityType, IEnt
         IKey key,
         IDiagnosticsLogger<DbLoggerCategory.Model.Validation> logger)
     {
-        if (entityType.GetTableName() != null
-            && (string?)entityType[RelationalAnnotationNames.MappingStrategy] == RelationalAnnotationNames.TpcMappingStrategy)
+        if ((string?)entityType[RelationalAnnotationNames.MappingStrategy] == RelationalAnnotationNames.TpcMappingStrategy
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:1943]: Use `entityType.GetMappingStrategy()` instead.

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 1 above)
Comment (cincuranet) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:1943]: Do you want me to change it only here in this PR or in all places (because the indexer is used in other places as well) in this file in separate PR?

Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:1943]: Only here. I'm not sure whether the other uses are incorrect
