### PR TITLE
Fix casted collections of enums as primitive collections.

### LINKED ISSUE #35777: EFCore 8.0.13 Linq query using Enum.GetValues().Cast<int>() fails
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EFCore-8013-Linq-query-using-EnumGetV/10860797)._

---
Example of EFCore Linq request that works in .Net 6.0.36

```
JobDetails = await dbCtx.JobDetails
   .AsNoTracking()
   .Where(j => Enum.GetValues<JobType.IceRcti>().Cast<int>().Contains(j.JobTypeId))
   .FirstOrDefaultAsync();
```
The above fails after upgrading the project to .Net 8.0.13 with EFCore 8.0.13. To get it to work again, I had to provide an additional ".ToList()" in the pipeline.

```
JobDetails = await dbCtx.JobDetails
   .AsNoTracking()
   .Where(j => Enum.GetValues<JobType.IceRcti>().Cast<int>().ToList().Contains(j.JobTypeId))
   .FirstOrDefaultAsync();
```

The SQL produced with the .ToList() resulted in a nice "JobTypeId in (1, 2, 3, 4)" style predicate.

I could get the original method to work without the .ToList(), but had to extract and assign a variable (IEnumerable&lt;int&gt; jobTypes) outside of the Linq expression first, and then use the variable within the expression. The SQL produced using the IEnumerable&lt;int&gt; was quite ugly though.
```
Code:
IEnumerable<int> jobTypes = Enum.GetValues<JobType.IceAP>().Cast<int>();
JobDetails = await dbCtx.JobDetails
   .AsNoTracking()
   .Where(j => jobTypes.Contains(j.JobTypeId))
   .FirstOrDefaultAsync();

Predicate produced in SQL:
[j].[JobTypeId] IN (
    SELECT [j0].[value]
    FROM OPENJSON(@__jobTypes_0) WITH ([value] int '$') AS [j0]
)
```

---
#### Feedback Bot on 2/28/2025, 03:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

### PR DESCRIPTION
**Pull request by cincuranet**
Fixes #35777.

### CODE REVIEW

File: src/EFCore/Query/QueryRootProcessor.cs [hunk 1]
```diff
@@ -103,7 +103,18 @@ private Expression VisitQueryRootCandidate(Expression expression, Type elementCl
                 var valueExpressions = new List<ConstantExpression>();
                 foreach (var value in values)
                 {
-                    valueExpressions.Add(Expression.Constant(value, elementClrType));
+                    var valueToAdd = value;
+
+                    if (value is not null)
+                    {
+                        var valueClrType = value.GetType();
+                        if (valueClrType != elementClrType.UnwrapNullableType() && valueClrType.IsEnum)
```
[the remark this answers is not in the document]
Comment (cincuranet) [reply src/EFCore/Query/QueryRootProcessor.cs:111]: That's what `UnwrapNullableType` is doing.

File: src/EFCore/Query/QueryRootProcessor.cs [hunk 2]
```diff
@@ -103,7 +103,18 @@ private Expression VisitQueryRootCandidate(Expression expression, Type elementCl
                 var valueExpressions = new List<ConstantExpression>();
                 foreach (var value in values)
                 {
-                    valueExpressions.Add(Expression.Constant(value, elementClrType));
+                    var valueToAdd = value;
+
+                    if (value is not null)
```
Comment (roji) [inline src/EFCore/Query/QueryRootProcessor.cs:108]: Can you include a comment explaining what's going on, context etc.?

File: test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs [hunk 3]
```diff
@@ -1497,6 +1497,20 @@ public virtual Task Nested_contains_with_arrays_and_no_inferred_type_mapping(boo
...
+    [ConditionalTheory]
+    [MemberData(nameof(IsAsyncData))]
+    public virtual Task Values_of_enum_casted_to_underlying_value_Contains(bool async)
+        => AssertQuery(
+            async,
+            ss => ss.Set<PrimitiveCollectionsEntity>().Where(x => Enum.GetValues<MyEnum>().Cast<int>().Contains(x.Int)));
+
+    [ConditionalTheory]
+    [MemberData(nameof(IsAsyncData))]
+    public virtual Task Values_of_enum_casted_to_underlying_value_Count(bool async)
```
Comment (roji) [inline test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs:1509]: Why the two tests? Is there something Count covers that Contains doesn't? If not really, better just have one and remove Contains/Count from the test name, as it's not relevant etc.

File: src/EFCore/Query/QueryRootProcessor.cs [hunk 4]
```diff
@@ -103,7 +103,18 @@ private Expression VisitQueryRootCandidate(Expression expression, Type elementCl
...
+                    {
+                        var valueClrType = value.GetType();
```
Comment (roji) [inline src/EFCore/Query/QueryRootProcessor.cs:110]: Just a thought - given that the code below only takes effect when `valueClrType.IsEnum`, can we lift this GetType() out of the loop (all elements are of the same type) to not do it again for each element?

**Review by roji — APPROVED** [review]
LGTM after comments are addressed, thanks!

File: test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs (hunk 3 above)
Comment (roji) [reply test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs:1509]: OK. AFAICT the code change happens far before there's any distinction between Contains and others (am I wrong?), so I don't think any actual coverage is added - like I wouldn't want to see systematic duplication of all primitive collection tests for Contains just because we have that SQL simplification in place for it...

But if you feel it's important for this case I'm OK with it.

Comment (cincuranet) [reply test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs:1509]: Yes it happens before.

> I wouldn't want to see systematic duplication of all primitive collection tests for Contains

OK

File: src/EFCore/Query/QueryRootProcessor.cs (hunk 4 above)
Comment (cincuranet) [reply src/EFCore/Query/QueryRootProcessor.cs:110]: Kind of. But we would have to find first non-null value in `values`. Or cache the value.

Can you explain what are you trying to achieve here? Avoid call to `GetType()`? For performance reasons? Is it really going to make difference here?

Comment (cincuranet) [reply src/EFCore/Query/QueryRootProcessor.cs]: Do you like [this](https://github.com/dotnet/efcore/pull/35839/commits/369c1cbee2cbb99aee84f9e4862a3769853e211e) more? For me the code is now uglier and less readable.

Might not even have performance benefit, because of the added conditional.

Comment (roji) [reply src/EFCore/Query/QueryRootProcessor.cs]: I do prefer it, since it makes it clear that there can't be different types (that can even be Debug.Asserted if we want).

> Might not even have performance benefit, because of the added conditional.

I'm gonna guess doing GetType() every time is heavier than a single conditional...

But I'm really OK either way.
