### PR TITLE
Remove regex from SqlServerMigrationsSqlGenerator

### LINKED ISSUE #16175: RegexMatchTimeoutException for SqlServerMigrationsSqlGenerator
```
System.Text.RegularExpressions.RegexMatchTimeoutException: The RegEx engine has timed out while trying to match a pattern to an input string. This can occur for many reasons, including very large inputs or excessive backtracking caused by nested quantifiers, back-references and other factors.
   at System.Text.RegularExpressions.RegexRunner.DoCheckTimeout()
   at System.Text.RegularExpressions.RegexInterpreter.Go()
   at System.Text.RegularExpressions.RegexRunner.Scan(Regex regex, String text, Int32 textbeg, Int32 textend, Int32 textstart, Int32 prevlen, Boolean quick, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run(Boolean quick, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat)
   at System.Text.RegularExpressions.Regex.Match(String input, Int32 startat)
   at System.Text.RegularExpressions.RegexReplacement.Replace(Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement, RegexOptions options, TimeSpan matchTimeout)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(SqlOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__73_25(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass13_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
```
Version: 2.2.4
Provider: SqlServer

I have some fairly large initial Migrations to set up some static data (approx 100,000 lines):

```C#
    public partial class InitialStateStaticData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {            
            var sql = @"
                <snip>
            ";
            migrationBuilder.Sql(sql, true); 
        }

        // ...
    }
```
The error seems to be coming from the fact that there is a limited 1000ms timeout on the regex parsing of this.

https://github.com/aspnet/EntityFrameworkCore/blob/f9d1df40fed1e1d7780553c3f9c1813e81eca1aa/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L1105

To mitigate this I added more GO statements into my SQL to avoid it, which worked fine.  That was until I deployed it into an Azure Function and now presumably because of the lower CPU/Mem I am running into issues.

Obviously I am looking in to way I could reduce the 100,000 lines and/or increasing resources, but it might also be helpful if this Timeout was overidable somehow (if the value wasn't set at all I could have used the `REGEX_DEFAULT_MATCH_TIMEOUT` Environment variable), perhaps in the `migrationBuilder.Sql(` method call?

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #16175

### CODE REVIEW

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 1]
```diff
@@ -1398,49 +1397,47 @@ protected override void Generate(AlterTableOperation operation, IModel? model, M
...
-            @"^\s*(GO[ \t]+[0-9]+|GO)(?:\s+|$)",
-            RegexOptions.IgnoreCase | RegexOptions.Multiline,
-            TimeSpan.FromMilliseconds(1000.0));
-        for (var i = 0; i < batches.Length; i++)
-        {
-            if (batches[i].StartsWith("GO", StringComparison.OrdinalIgnoreCase)
-                || string.IsNullOrWhiteSpace(batches[i]))
+        var preBatched = operation.Sql
+            .Replace("\\\n", "")
+            .Replace("\\\r\n", "")
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:1402]:
```suggestion
            .Replace("\\\r\n", "")
            .Replace("\\\n", "")
```

Comment (ajcvickers) [reply src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:1402]: Why this change?

**Review by AndriySvyryd — APPROVED** [review]
