### PR TITLE
[release/9.0] Fix to #34760 - NullReferenceException for a custom ValueConverter in EF Core 9 RC 1.

### LINKED ISSUE #34760: `NullReferenceException` for a custom `ValueConverter` in EF Core 9 RC 1.
The `csproj` and code to reproduce:

```cs
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0-rc.1.24451.1">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0-rc.1.24451.1" />
    </ItemGroup>

</Project>
```

```cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

var db = new BookContext();

await db.Books.AddAsync( new Book()
{
    CreationDate = DateTime.Now
});

await db.SaveChangesAsync();

var result =  await db.Books
    .GroupBy(t => t.Id)
    .Select(g => new
    {
        Day = g.Min(t => t.CreationDate)
    })
    .ToListAsync();

public class BookContext : DbContext
{
    public DbSet<Book> Books { get; set; }

    public string DbPath { get; }

    public BookContext()
    {
        var folder = Environment.SpecialFolder.LocalApplicationData;
        var path = Environment.GetFolderPath(folder);
        DbPath = Path.Join(path, "book.db");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Book>().Property(e => e.CreationDate).HasConversion(new MyDateTimeValueConverter(new MyDatetimeConverter()));
    }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlite($"Data Source={DbPath}", builder => builder.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)).EnableDetailedErrors();
}

public class MyDateTimeValueConverter : ValueConverter<DateTime, DateTime>
{
    public MyDateTimeValueConverter(MyDatetimeConverter myDatetimeConverter, ConverterMappingHints? mappingHints = null)
        : base(
            x => myDatetimeConverter.Normalize(x),
            x => myDatetimeConverter.Normalize(x),
            mappingHints)
    {
    }
}

public class Book
{
    public Guid Id { get; set; }

    public virtual DateTime CreationDate { get;  set; }
}


public class MyDatetimeConverter
{
    public virtual DateTime Normalize(DateTime dateTime)
    {
        return dateTime.Date;
    }
}

```

```cs
Unhandled exception. System.InvalidOperationException: An error occurred while reading a database value. The expected type was 'System.Nullable`1[System.DateTime]' but the actual value was null.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method34(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   --- End of inner exception stack trace ---
   at lambda_method34(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in ConsoleApp\ConsoleApp\Program.cs:line 13
   at Program.<Main>(String[] args)

```

---

It works if I create the `MyDatetimeConverter()` object in the expression parameter.
And the all code works in EF Core 8.0.

```cs
public class MyDateTimeValueConverter : ValueConverter<DateTime, DateTime>
{
    public MyDateTimeValueConverter(MyDatetimeConverter myDatetimeConverter, ConverterMappingHints? mappingHints = null)
        : base(
            x => new MyDatetimeConverter().Normalize(x),
            x => new MyDatetimeConverter().Normalize(x),
            mappingHints)
    {
    }
}
```

### PR DESCRIPTION
**Pull request by maumar**
**Description**

For AOT/precompiled queries we now do special processing (lifting) of all non-literal constants. We essentially provide a way to resolve the constant from well established entry points, e.g. model. Problem happens for cases where we are projecting a property with a custom converter but do it in such a way that we lose the IProperty information (e.g. by projecting individual property, rather than as part of an entity) Without IProperty information we can't reliably extract the proper type mapping for that property and as a result we don't know what custom converter to use. What we used to do is "guess" the type mapping based on CLR type of the property. This is pretty much always wrong, and it also broke non-precompiled scenarios. Fix is to just use ConvertFromProviderExpression expression irrespective of whether it contains closures or not. We only do that if we don't have the IProperty information. This also requires disabling non-literal constant validation we do in the post processing, as now some queries may contain "unliftable" constants. We should re-enable the validation once the issue is properly addressed (#33517)

Fixes #34760

**Customer impact**
Projecting a property with custom converter could sometimes fail with (NRE). Workaround was to modify the converter so that it doesn't use a closure variable, which is tedious, not intuitive and has perf impact.

**How found**
Customer reported on EF 9 RC1

**Regression**
Yes, from EF 8

**Testing**
Test added, both regular and precompiled query cases.

**Risk**
Low. Very targeted change. We revert to EF8 behavior for the affected scenarios. Precompiled query will not work, but it is an experimental feature in EF9 and this scenario was already broken before the fix.

### CODE REVIEW

File: src/EFCore/Query/LiftableConstantProcessor.cs [hunk 1]
```diff
@@ -256,11 +256,17 @@ protected override Expression VisitMember(MemberExpression memberExpression)
...
-    {
-        _unsupportedConstantChecker.Check(node);
-        return node;
-    }
+    // issue #34760 - disabling the liftable constant verification because we sometimes are forced to
+    // use them (when type mapping has custom converter but we can't reliably get the correct type mapping
+    // when building the shaper) - if that converter uses a closure, we will embed it in the shaper
+    // we don't have a reasonalbe alternative currently
+    // Once #33517 is done, we should re-enable this check
+    //protected override Expression VisitConstant(ConstantExpression node)
```
Comment (maumar) [inline src/EFCore/Query/LiftableConstantProcessor.cs:264]: any ideas how to disable the liftable constant validation in a more targeted way? Maybe not a big deal since we still throw a reasonable exception.

File: test/EFCore.Relational.Specification.Tests/Query/PrecompiledQueryRelationalTestBase.cs [hunk 2]
```diff
@@ -1177,6 +1222,12 @@ protected override void OnModelCreating(ModelBuilder modelBuilder)
                 });
             modelBuilder.Entity<Blog>().HasMany(x => x.Posts).WithOne(x => x.Blog).OnDelete(DeleteBehavior.Cascade);
             modelBuilder.Entity<Post>().Property(x => x.Id).ValueGeneratedNever();
+            modelBuilder.Entity<Tag>(b =>
+            {
+                b.Property(x => x.Id).ValueGeneratedNever();
+                b.Property(x => x.CreateDate).HasConversion(new MyDateTimeValueConverterWithClosure(new MyDatetimeConverter()));
```
Comment (roji) [inline test/EFCore.Relational.Specification.Tests/Query/PrecompiledQueryRelationalTestBase.cs:1228]: IMHO this is exactly the kind of case where we should a non-shared test - this modifies the shared model with something that's very specific to a single test (e.g. a converter with a closure). I think AdHocPrecompiledQueryRelationalTestBase is a better place for this kind of thing.

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 3]
```diff
@@ -2743,9 +2743,11 @@ Expression valueExpression
...
                 // and only resort to unreliable TypeMappingSource lookup, if the converter expression captures "forbidden" constant
                 // see issue #33517 for more details
-                var requiresLiftableConstant =
-                    new ConstantValidator().RequiresLiftableConstant(converter.ConvertFromProviderExpression.Body);
-                if (property != null || requiresLiftableConstant)
+                // UPDATE: instead of guessing the type mapping in case where we don't have IProperty and converter uses non-literal constant,
+                // we just revert to the pre-AOT behavior, i.e. we still use converter.ConvertFromProviderExpression
+                // this will not work for precompiled query (which realistically was already broken for this scenario - type mapping we "guess"
+                // is pretty much always wrong), but regular case (not pre-compiled) will continue to work. 
+                if (property != null)
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:2750]: Should CreateTypeMappingExpression() be modified (or just inlined) since it no longer needs to handle the unknown type mapping case? At the very least, comment out the parts that are no longer needed?

File: src/EFCore/Query/LiftableConstantProcessor.cs (hunk 1 above)
Comment (roji) [reply src/EFCore/Query/LiftableConstantProcessor.cs:264]: I think I need more context here: would this check throw exactly in the case we don't support, i.e. capturing value converter without a property? What scenario fails if this isn't commented out?

**Review by roji — APPROVED** [review]
Looks good overall, thanks @maumar. See question about disabling the check inside LiftableConstantProcessor, otherwise just a testing suggestion.

File: src/EFCore/Query/LiftableConstantProcessor.cs (hunk 1 above)
Comment (maumar) [reply src/EFCore/Query/LiftableConstantProcessor.cs:264]: the scenario in question, it fails for any non-literal constant in the expression. The scenario in this issue is the only one unaccounted for (that we know of). There are few other constants that we can't lift, but those are well known NTS types, so we can filter them out in a targeted way:

```
    protected override Expression VisitMember(MemberExpression memberExpression)
        => memberExpression is { Expression: ConstantExpression, Type.Name: "SqlServerBytesReader" or "GaiaGeoReader" }
            ? memberExpression
            : base.VisitMember(memberExpression);
```

Comment (roji) [reply src/EFCore/Query/LiftableConstantProcessor.cs:264]: Right, but so why do we need to comment out the VisitConstant here? Don't we want it to fail for this case, because it's unsupported (at the moment)?

Comment (maumar) [reply src/EFCore/Query/LiftableConstantProcessor.cs:264]: this visitor runs both for pre-compiled and normal scenarios. (albeit in debug time) We want this scenario to pass for non-precompiled. I think the idea is to make sure that we have consistent behavior between regular and precompiled queries. The visitor is supposed to ensure that we don't end up in a situation that a scenario works for regular case but suddenly starts failing for pre-compiled, because some constant wasn't properly lifted.

Comment (roji) [reply src/EFCore/Query/LiftableConstantProcessor.cs:264]: OK, I see - thanks (I think I forgot some of this stuff in the meantime).

Yeah, I don't think it's possible to do a more targeted ignore, unfortnuately - at this visitation there's just an expression tree, with no special way to distinguish between unsupported captured variables inside value converters and other unsupported constants.

I guess we'll indeed need to disable this verification for now.
