### PR TITLE
Fix to #31365 - Query: add support for projecting JSON entities that have been composed on

### LINKED ISSUE #31365: Query: add support for projecting JSON entities that have been composed on
We support projecting entities which own JSON entities, we also support projecting those entities directly accessed from the owner, as well indexing into individual elements. 
However, when to-be-projected JSON entity was accessed via some query operation (e.g. filter, paging, etc) we convert the JSON column into query root using OPENJSON/json_each. This makes it so that the entity looks as if it was a normal entity to the materializer.
Normal entities go through different materialization codepath than JSON entities. 

- normal entities have all the Include calls preserved and each entity/collection in the include chain is generated separately. JSON only keeps the root level includes at the query level, and the materializer itself generates all the necessary includes.
- JSON entities, specifically collections contain synthesized (key) properties that don't correspond to any column in the database. Materializer for JSON knows to disregard them, but materializer for normal entity tries to extract value from column for every property in the entity.

### PR DESCRIPTION
**Pull request by maumar**
Adding new materialization path for JSON entities that have been converted to query roots - they look like normal entity, but materialization is somewhat different.
We need to prune synthesized key properties from materializer code (as they are not associated with any column, but rather made up on the fly)
Also added code to include all the child navigations. For normal entities we have IncludeExpressions in the shaper expression, but for JSON we prune all includes and build them in the materializer.

Fix is to recognize the scenario (entity projection but the entity is mapped to JSON) during apply projection phase and generate all the necessary info needed rather than just dictionary of property to index maps like we do for regular entity.
Then when we build materializer we use that info to prune the synthesized properties from key check and re-use existing include JSON entity code to add child navigations.

Fixes #31365

### CODE REVIEW

**Comment by maumar** [comment]
@roji, turned out bit easier than I thought (knock on wood) there are still some tests failing due to some bad assumptions in the JSON post processor. Also SelectMany is still broken (will take a look), and it looks like OPENJSON with WITH needs to add AS JSON for the primitve collection properties, otherwise they come out as null (at least in some scenarios). But when I do that, I run into some bad state in the JSON post processor. Also code still needs some major cleanup, as I hacked it rather quickly ^^'

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -1614,23 +1749,83 @@ Expression CopyProjectionToOuter(SelectExpression innerSelectExpression, Express
...
-            }
+                var dictionary = new Dictionary<IProperty, int>();
+                var childJsonProjectionInfos = new List<JsonProjectionInfo>();
+                var ownerEntity = entityProjectionExpression.EntityType;
 
-            if (entityProjectionExpression.DiscriminatorExpression != null)
-            {
-                AddToProjection(entityProjectionExpression.DiscriminatorExpression, DiscriminatorColumnAlias);
+                //achievement unlocked ;P
+                do
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1764]: :trollface:

File: src/EFCore.Relational/Query/JsonQueryExpression.cs [hunk 2]
```diff
@@ -145,11 +152,11 @@ public virtual JsonQueryExpression BindNavigation(INavigation navigation)
...
 
         var newKeyPropertyMap = new Dictionary<IProperty, ColumnExpression>();
-        var targetPrimaryKeyProperties = targetEntityType.FindPrimaryKey()!.Properties.Take(_keyPropertyMap.Count);
-        var sourcePrimaryKeyProperties = EntityType.FindPrimaryKey()!.Properties.Take(_keyPropertyMap.Count);
+        var targetPrimaryKeyProperties = targetEntityType.FindPrimaryKey()!.Properties.Take(KeyPropertyMap.Count);
+        var sourcePrimaryKeyProperties = EntityType.FindPrimaryKey()!.Properties.Take(KeyPropertyMap.Count);
         foreach (var (target, source) in targetPrimaryKeyProperties.Zip(sourcePrimaryKeyProperties, (t, s) => (t, s)))
         {
-            newKeyPropertyMap[target] = _keyPropertyMap[source];
+            newKeyPropertyMap[target] = KeyPropertyMap[source];
```
Comment (ilmax) [inline src/EFCore.Relational/Query/JsonQueryExpression.cs:159]: nit: If accessing KeyPropertyMap is considered to be somehow expensive due to the virtual call, it can be cached into a local here

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 1 above)
Comment (roji) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1764]: Ahahahaha :+1:

Comment (roji) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1764]: I'm 100% we'll figure out why this is somehow incorrect and needs to be a regular while

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 3]
```diff
@@ -2251,6 +2277,42 @@ static TableExpressionBase FindRootTableExpressionForColumn(ColumnExpression col
...
+                entityType = entityType.GetRootType().GetDerivedTypesInclusive()
+                    .FirstOrDefault(et => et.ClrType == convertedType);
+
+                if (entityType == null)
+                {
+                    return null;
+                }
+            }
+
+            // TODO: Check that the property is a primitive collection property directly once we have that in metadata, rather than
```
Comment (ajcvickers) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:2305]: I will take care of this.

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs [hunk 4]
```diff
@@ -208,6 +210,102 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
+        foreach (var property in GetAllPropertiesInHierarchy(jsonQueryExpression.EntityType))
+        {
+            if (property.GetJsonPropertyName() is string jsonPropertyName)
+            {
+                columnInfos.Add(new()
+                {
+                    Name = jsonPropertyName,
+                    TypeMapping = property.GetRelationalTypeMapping(),
+                    Path = new PathSegment[] { new(jsonPropertyName) },
+                    //AsJson = property.GetRelationalTypeMapping().ElementTypeMapping is not null
```
Comment (ajcvickers) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs:240]: ?

**Review by ajcvickers — APPROVED** [review]
:sheep: :it:

**Comment by roji** [comment]
Ahh, the season of :sheep: :it: has begun :)

@maumar will also review shortly for the SelectExpression parts.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 5]
```diff
@@ -1737,29 +1749,83 @@ Expression CopyProjectionToOuter(SelectExpression innerSelectExpression, Express
...
+            // so it requires different materialization path than regular entity
+            // e.g. we need to also add all the child navigations, JSON entity builds all the includes as part of it's own materializer
+            // rather than relying on IncludeExpressions in the shaper query
+            // also, we don't want to add projection map for synthesized keys, whereas regular entity needs to project every single property it has
+            if (entityProjectionExpression.EntityType.IsMappedToJson())
             {
-                if (entityProjectionExpression.EntityType.IsMappedToJson()
-                    && property.IsOrdinalKeyProperty())
+                var dictionary = new Dictionary<IProperty, int>();
+                var childJsonProjectionInfos = new List<JsonProjectionInfo>();
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1760]: Unused

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 6]
```diff
@@ -1737,29 +1749,83 @@ Expression CopyProjectionToOuter(SelectExpression innerSelectExpression, Express
...
+                var keyPropertyCount = ownerEntity.FindPrimaryKey()!.Properties.Count;
+                foreach (var property in entityProjectionExpression.EntityType.FindPrimaryKey()!.Properties.Take(keyPropertyCount))
+                {
+                    dictionary[property] = AddToProjection(entityProjectionExpression.BindProperty(property), null);
+                }
 
-            if (entityProjectionExpression.DiscriminatorExpression != null)
-            {
-                AddToProjection(entityProjectionExpression.DiscriminatorExpression, DiscriminatorColumnAlias);
+                foreach (var property in entityProjectionExpression.EntityType.GetDeclaredProperties().Where(p => p.GetJsonPropertyName() is not null))
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1780]: Can use Concat to merge the two foreaches

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 7]
```diff
@@ -2120,6 +2168,44 @@ ParameterExpression ExtractAndCacheNonConstantJsonArrayElementAccessValue(int in
...
+                        Left: MethodCallExpression { Method: { IsGenericMethod: true } method } methodCallExpression,
+                        Right: ConstantExpression { Value: null }
+                    }
+                    && method.GetGenericMethodDefinition() == Infrastructure.ExpressionExtensions.ValueBufferTryReadValueMethod
+                    && ((ConstantExpression)methodCallExpression.Arguments[2]).Value is IProperty property)
+                {
+                    // 
+                    return _mappedProperties.Contains(property)
+                        ? binaryExpression
+                        : Expression.Constant(true);
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:2202]:
```suggestion
                        : Constant(true);
```

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 8]
```diff
@@ -2120,6 +2168,44 @@ ParameterExpression ExtractAndCacheNonConstantJsonArrayElementAccessValue(int in
...
+                // if the key is one of the mapped ones, we leave the expression as is, otherwise replace with Constant(true)
+                // i.e. removing it
+                if (binaryExpression is
+                    {
+                        NodeType: ExpressionType.NotEqual,
+                        Left: MethodCallExpression { Method: { IsGenericMethod: true } method } methodCallExpression,
+                        Right: ConstantExpression { Value: null }
+                    }
+                    && method.GetGenericMethodDefinition() == Infrastructure.ExpressionExtensions.ValueBufferTryReadValueMethod
+                    && ((ConstantExpression)methodCallExpression.Arguments[2]).Value is IProperty property)
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:2197]:
```suggestion
                        Left: MethodCallExpression
                        {
                            Method: { IsGenericMethod: true } method,
                            Arguments: [_, _, ConstantExpression { Value: IProperty property }]
                        },
                        Right: ConstantExpression { Value: null }
                    }
                    && method.GetGenericMethodDefinition() == Infrastructure.ExpressionExtensions.ValueBufferTryReadValueMethod)
```

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 9]
```diff
@@ -2120,6 +2168,44 @@ ParameterExpression ExtractAndCacheNonConstantJsonArrayElementAccessValue(int in
...
+        private sealed class QueryableJsonEntityMaterializerRewriter : ExpressionVisitor
+        {
+            private readonly List<IProperty> _mappedProperties;
+
+            public QueryableJsonEntityMaterializerRewriter(List<IProperty> mappedProperties)
+            {
+                _mappedProperties = mappedProperties;
+            }
+
+            public BlockExpression Rewrite(BlockExpression jsonEntityShaperMaterializer)
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:2180]: not used?

**Review by roji — APPROVED** [review]
My understanding here is pretty vague... But looks OK :)

Let's think about cleanup later when everything is calmer.

**Comment by roji** [comment]
@maumar FYI #31369 has been merged, this can now be rebased over main.

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs (hunk 4 above)
Comment (maumar) [reply src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs:240]: when using OPENJSON with WITH we need to mark primitive collections with AS JSON keyword, otherwise they come out as null. When I do it, we hit some bad assumptions in the json post processor, so I commented it temporarily. Will uncomment and fix json post processor in the final version.

Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs:240]: Note that I made some minor changes in #31369 to the JSON postprocessor, these could in theory be related (so rebase in any case).

Anyway, let me know if you want my help with this tomorrow.

File: src/EFCore.Relational/Query/JsonQueryExpression.cs (hunk 2 above)
Comment (maumar) [reply src/EFCore.Relational/Query/JsonQueryExpression.cs:159]: I'll leave it to our Resident Optimization Justification Investigator to decide, @roji

**Comment by maumar** [comment]
rebased and updated, please take a final look @roji @ajcvickers

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 10]
```diff
@@ -2120,6 +2167,62 @@ ParameterExpression ExtractAndCacheNonConstantJsonArrayElementAccessValue(int in
...
+                        ? binaryExpression
+                        : Constant(true);
+                }
+
+                return base.VisitBinary(binaryExpression);
+            }
+
+            protected override Expression VisitMethodCall(MethodCallExpression methodCallExpression)
+            {
+                if (methodCallExpression is
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:2211]: this *should* be good enough - just replace reference to the ordinal key with default value for the type we expect. In case of key comparison (handled above) we make an exception because we need to convert `key != null` into true, rather than `null != null` which would have been false. In general, since this materialization path is always for non-tracking, we shouldn't have too many instances of the keys present, one other place that I haven't yet tested would be materialization interceptor. @ajcvickers

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 11]
```diff
@@ -789,7 +789,9 @@ public void ApplyDistinct()
                         // for JSON entities identifier is the key that was generated when we convert from json to query root (OPENJSON, json_each, etc)
                         // but we can't use it for distinct, as it would warp the results
                         // instead, we will treat every non-key property as identifier
-                        foreach (var property in entityProjection.EntityType.GetDeclaredProperties().Where(p => !p.IsPrimaryKey()))
+
+                        // TODO: hack/workaround, see #31398
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:793]: FYI

File: src/EFCore.SqlServer/Query/Internal/SqlServerJsonPostprocessor.cs [hunk 12]
```diff
@@ -239,8 +239,10 @@ static bool IsKeyColumn(SqlExpression sqlExpression, TableExpressionBase table)
                 columnExpression.Table, "value", columnExpression.Type, _nvarcharMaxTypeMapping, columnExpression.IsNullable);
 
             Check.DebugAssert(columnInfo.Path is not null, "Path shouldn't be null in OPENJSON WITH");
-            Check.DebugAssert(!columnInfo.AsJson, "AS JSON signifies an owned sub-entity being projected out of OPENJSON/WITH. "
-                + "Columns referring to that must be wrapped be Json{Scalar,Query}Expression and will have been already dealt with above");
+            //Check.DebugAssert(
```
Comment (maumar) [inline src/EFCore.SqlServer/Query/Internal/SqlServerJsonPostprocessor.cs:242]: @roji uncomment to see a bunch of tests failing due to incorrect assumptions we had in the post processor.

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs (hunk 10 above)
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:2211]: update: added test for materialization interceptor - works like a charm
