### PR TITLE
[6.0] Respect AsNoTrackingWithIdentityResolution in AsTracking method

### LINKED ISSUE #26227: Why is AsNoTrackingWithIdentityResolution() different to .AsTracking(QueryTrackingBehavior.NoTrackingWithIdentityResolution)?
## Ask a question

I'm trying to resolve an issue in which I need EF Core to be able to resolve a recursive one-to-many relationship: 

I've set up this simple test:

```csharp
[Test]
public async Task Temp()
{
    var productTypes = await Query(context => context.ProductTypes
        //.AsTracking(QueryTrackingBehavior.NoTrackingWithIdentityResolution)
        .AsNoTrackingWithIdentityResolution()
        .Include(pt => pt.Group)
        .ThenInclude(x => x.Variants.Where(v => v.IsAvailable))
        .Where(pt => pt.IsAvailable)
        .ToListAsync());

    var trackerGroup = productTypes.Single(x => x.Key == "Tracker");
    trackerGroup.Variants.Count.ShouldBe(3);
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerRetrieveThreeYear");
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerMonitorThreeYear");
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerLocateThreeYear");
}
```

If I run that, then the query executes fine and the test passes.

If instead I run:

```csharp
[Test]
public async Task Temp()
{
    var productTypes = await Query(context => context.ProductTypes
        .AsTracking(QueryTrackingBehavior.NoTrackingWithIdentityResolution)
        //.AsNoTrackingWithIdentityResolution()
        .Include(pt => pt.Group)
        .ThenInclude(x => x.Variants.Where(v => v.IsAvailable))
        .Where(pt => pt.IsAvailable)
        .ToListAsync());

    var trackerGroup = productTypes.Single(x => x.Key == "Tracker");
    trackerGroup.Variants.Count.ShouldBe(3);
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerRetrieveThreeYear");
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerMonitorThreeYear");
    trackerGroup.Variants.ShouldContain(x => x.Key == "TrackerLocateThreeYear");
}
```

Then the test fails with this exception:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The Include path 'Group->Variants' results in a cycle. Cycles are not allowed in no-tracking queries; either use a tracking query or remove the cycle.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.VerifyNoCycles(IncludeTreeNode includeTreeNode)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.ExpandInclude(Expression root, EntityReference entityReference)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.IncludeExpandingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.ExpandingExpressionVisitor.Expand(Expression expression, Boolean applyIncludes)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.PendingSelectorExpandingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.Expand(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ArnoldClark.Sales.Commissions.ApplicationServices.Tests.ApplicationTesting.<>c__DisplayClass14_0`1.<<Query>b__0>d.MoveNext() in C:\Projects\sales-commissions\tests\ArnoldClark.Sales.Commissions.ApplicationServices.Tests\ApplicationTesting.cs:line 139

  This exception was originally thrown at this call stack:
    [External Code]
    ArnoldClark.Sales.Commissions.ApplicationServices.Tests.ApplicationTesting.Query.AnonymousMethod__0(ArnoldClark.Sales.Commissions.Infrastructure.Data.CommissionsContext) in ApplicationTesting.cs
```

This is very unexpected behaviour as I assumed `AsNoTrackingWithIdentityResolution()` was just a helpful shortcut for `AsTracking(QueryTrackingBehavior.NoTrackingWithIdentityResolution)`.

EF Core version: 5.0.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.11.3

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #26227.

This fixes a :facepalm: bug where calling `AsTracking` with `NoTrackingWithIdentityResolution` was not being respecting and the query would be executed with `NoTracking` instead.

### CODE REVIEW

**Comment by ajcvickers** [comment]
@Pilchie for 6.0.

File: src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs [hunk 1]
```diff
@@ -2985,7 +2985,9 @@ IEnumerator IEnumerable.GetEnumerator()
             where TEntity : class
             => track == QueryTrackingBehavior.TrackAll
                 ? source.AsTracking()
-                : source.AsNoTracking();
+                : track == QueryTrackingBehavior.NoTrackingWithIdentityResolution
+                    ? source.AsNoTrackingWithIdentityResolution()
+                    : source.AsNoTracking();
```
Comment (TAGC) [inline src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs:2990]: Ain't my business how you choose to fix this but I'm bored because I'm I'm a long car ride and won't get home until 1 AM.

Isn't this way of fixing it sort of asking for this bug to happen again a few years down the line? If another option gets added to the enum and you forget to update this method it could lead to it silently picking an option different to the one you expect.

I'd personally go for doing what ReSharper defaults to which is switching on the enum value with an exception being thrown in the default clause, so it would be very noticeable if this method forgets to be updated the next time the enum is.

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs (hunk 1 above)
Comment (roji) [reply src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs:2990]: Switch expression?

Comment (TAGC) [reply src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs:2990]: @roji yeah exactly

Comment (TAGC) [reply src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs:2990]: This is what I've added as a temporary measure in my codebase, just as a reference for what I mean:

```csharp

        private static IQueryable<T> WithTrackingBehaviour<T>(
            this IQueryable<T> query,
            QueryTrackingBehavior trackingBehavior) where T : class
        {
            return trackingBehavior switch
            {
                QueryTrackingBehavior.TrackAll => query.AsTracking(),
                QueryTrackingBehavior.NoTracking => query.AsNoTracking(),
                QueryTrackingBehavior.NoTrackingWithIdentityResolution => query.AsNoTrackingWithIdentityResolution(),
                _ => throw new ArgumentOutOfRangeException(nameof(trackingBehavior), trackingBehavior, message: null),
            };
        }
    }
```

**Comment by Pilchie** [comment]
Approved for EF Core 6.0 GA.

**Comment by roji** [comment]
@ajcvickers do we want to backport this?

**Comment by ajcvickers** [comment]
@roji We decided not in triage. The workaround is really easy. And it could break existing apps by silently changing behavior, even though the behavior is technically wrong.

**Comment by roji** [comment]
Right, sorry - forgot.
