### PR TITLE
Query: Translate aggregate over grouping element in separate pass

### LINKED ISSUE #19683: Query: inconsistent behavior between relational and InMemory/L2O for queries grouping by a constant
In relational we ignore groupby constant or parameter, so we just generate simple select. However, on InMemory and Linq2Objects we generate a single grouping with the key.

### LINKED ISSUE #23601: sub-select + group-by leads to InvalidCastException
Tested on:
EFCore Version: SqlServer-5.0.0

Repository to reproduce:
https://github.com/morinow/EF-GroupByError

I have the following data model:

Simple entity
```csharp
public class Entity
{
  public Guid Id { get; set; }
  public string Name { get; set; }
  public ICollection<EntityTag> Tags { get; set; }
}
```
One-to-many tags for entity
```csharp
public class EntityTag
{
  public Guid EntityId { get; set; }
  public Entity Entity { get; set; }
  public string Tag { get; set; }
}
```

I am projecting the entity to the following DTO:
```csharp
public class EntityDto
{
  public Guid Id { get; set; }
  public string Name { get; set; }
  public IEnumerable<string> Tags { get; set; }
}
```
with the following query:
```csharp
return this.context.Entities
           .Select(e => new EntityDto
           {
             Id = e.Id,
             Name = e.Name,
             Tags = e.Tags.Select(t => t.Tag)
           });
```

When trying to group the entities by name and apply a **count** aggregation on the buckets...
```csharp
return this.context.Entities
           .Select(e => new EntityDto
           {
             Id = e.Id,
             Name = e.Name,
             Tags = e.Tags.Select(t => t.Tag)
           })
           .GroupBy(e => e.Name)
           .Select(g => new
           {
             Name = g.Key,
             Count = g.Count()
           });
```
... the following error appears:
```csharp
System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.ColumnExpression' to type 'System.Linq.Expressions.ConstantExpression'.
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.GetProjectionIndex(ProjectionBindingExpression projectionBindingExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression, RelationalCommandCache& relationalCommandCache, LambdaExpression& relatedDataLoaders)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at SampleApp.Controllers.SampleController.GroupEntities(Boolean tags) in C:\Development\Work\WAVE\EF-GroupByError\SampleApp\Controllers\SampleController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

When I leave out the filling of the property **Tags**, the query works just fine.

### LINKED ISSUE #27132: Relational: GroupBy aggregate lifting
The visitor has bunch of issues while trying to find correct parent group by query
- If parent was pushed down for whatever reason.
- If the grouping subquery changed table alias due to uniquification

An ideal but bit costly solution would be avoid doing the lift in first place. If the queryable translation did 2-way running translation for aggregate/non-aggregate scenario both then we don't need to do lifting as correct SQL would be automatically generated. This could also help in custom aggregate operation translation support.

### LINKED ISSUE #27266: Stop referring to ungrouped columns from outer query in subquery
PostgreSQL seems to be particularly strict around subqueries and GROUP BY. The following query (full repro below):

```c#
from s in (from i in ctx.Invoices
        group i by i.History.Month
        into g
        select new
        {
            Month = g.Key,
            Total = g.Sum(p => p.Amount),
        })
    select new
    {
        s.Month,
        s.Total,
        Payment = ctx.Payments.Where(p => p.History.Month == s.Month).Sum(p => p.Amount)
    }
```

... generates the following SQL on PostgreSQL:

```sql
SELECT date_part('month', i."History")::INT AS "Month", COALESCE(SUM(i."Amount"), 0)::INT AS "Total", (
    SELECT COALESCE(SUM(p."Amount"), 0)::INT
    FROM "Payments" AS p
    WHERE date_part('month', p."History")::INT = date_part('month', i."History")::INT) AS "Payment"
FROM "Invoices" AS i
GROUP BY date_part('month', i."History")::INT
```

... and errors with the following: `subquery uses ungrouped column "i.History" from outer query`.

The same works fine on SQL Server, SQLite and MariaDB.

Note also that the current SQL is less efficient even when supported, since the same expression gets evaluated more than once (see https://github.com/dotnet/efcore/issues/27266#issuecomment-1022365293).

See suggested alternative SQL by @mojtabakaviani in https://github.com/npgsql/efcore.pg/issues/2236#issue-1112392955.

<details>
<summary>Full repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var query = from s in (from i in ctx.Invoices
        group i by i.History.Month
        into g
        select new
        {
            Month = g.Key,
            Total = g.Sum(p => p.Amount),
        })
    select new
    {
        s.Month,
        s.Total,
        Payment = ctx.Payments.Where(p => p.History.Month == s.Month).Sum(p => p.Amount)
    };

_ = query.ToList();

public class BlogContext : DbContext
{
    public DbSet<Invoice> Invoices { get; set; }
    public DbSet<Payment> Payments { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            // .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .UseNpgsql(@"Host=localhost;Username=test;Password=test")
            // .UseSqlite("Data Source=/tmp/foo.sql")
            // .UseMySql("Server=localhost;user=test;password=test;database=test", new MariaDbServerVersion("10.5"))
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Invoice
{
    public int Id { get; set; }
    public int Amount { get; set; }

    public DateTime History { get; set; }
}

public class Payment
{
    public int Id { get; set; }
    public int Amount { get; set; }

    public DateTime History { get; set; }
}
```

</details>

Raised by @mojtabakaviani in https://github.com/npgsql/efcore.pg/issues/2236

### LINKED ISSUE #27433: Bug report: When Substring is used in GroupBy, the query is not created correctly 6.0.2
This problem only occurs in version 6.0.2 and does not occur in version 6.0.1.

### Repro

ConsoleApp.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="6.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="6.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>
</Project>
```

ApplicationDbContext.cs:
```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace ConsoleApp1.Data
{
    public class ApplicationDbContext : DbContext
    {
        public virtual DbSet<Model.DepartmentStaff> CustomerSystemStaff { get; set; }
        public virtual DbSet<Model.Department> Departments { get; set; }
        public virtual DbSet<Model.TicketTask> TicketTasks { get; set; }
        public ApplicationDbContext() : base(GetOptions())
        {
        }
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
               .UseSqlServer("Data Source=.;Initial Catalog=test;User ID=sa;Password=100+200");

            optionsBuilder
             .UseSqlServer(o =>
                 o.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)
             );
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Model.Department>()
            .HasMany<Model.DepartmentStaff>(g => g._DepartmentStaff)
            .WithOne(s => s.Department)
            .HasForeignKey(s => s.DepartmentID)
            .OnDelete(DeleteBehavior.Cascade);


            modelBuilder.Entity<Model.Department>()
            .HasMany<Model.TicketTask>(g => g._TicketTaskActDepartment)
            .WithOne(s => s.ActDepartment)
            .HasForeignKey(s => s.ActDepartmentID)
            .OnDelete(DeleteBehavior.NoAction);

            modelBuilder.Entity<Model.ApplicationUser>()
            .HasMany<Model.Department>(g => g._DepartmentUserManager)
            .WithOne(s => s.UserManager)
            .HasForeignKey(s => s.UserManagerID)
            .OnDelete(DeleteBehavior.NoAction);

            modelBuilder.Entity<Model.ApplicationUser>()
            .HasMany<Model.DepartmentStaff>(g => g._DepartmentStaffUser)
            .WithOne(s => s.User)
            .HasForeignKey(s => s.UserID)
            .OnDelete(DeleteBehavior.NoAction);

            modelBuilder.Entity<Model.ApplicationUser>()
            .HasMany<Model.TicketTask>(g => g._TicketTaskActUser)
            .WithOne(s => s.ActUser)
            .HasForeignKey(s => s.ActUserID)
            .OnDelete(DeleteBehavior.NoAction);


            modelBuilder.Entity<Model.Department>()
            .HasMany<Model.Department>(g => g._Children)
            .WithOne(s => s.Parent)
            .HasForeignKey(s => s.ParentId)
            .OnDelete(DeleteBehavior.NoAction);



            modelBuilder.Entity<Model.TicketTask>().Property(m => m.InsertedDatePersian).HasComputedColumnSql("(format([InsertedDate],'yyyy/MM/dd HH:mm:ss','fa'))").HasColumnName("InsertedDatePersian");
            modelBuilder.Entity<Model.TicketTask>().Property(m => m.DoneDatePersian).HasComputedColumnSql("(format([DoneDate],'yyyy/MM/dd HH:mm:ss','fa'))").HasColumnName("DoneDatePersian");


        }
        private static DbContextOptions<ApplicationDbContext> GetOptions()
        {
            return SqlServerDbContextOptionsExtensions.UseSqlServer(new DbContextOptionsBuilder<ApplicationDbContext>(), "Data Source=.;Initial Catalog=test;User ID=sa;Password=100+200").Options;
        }
    }
}
```

ApplicationUser.cs:
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model
{
    public class ApplicationUser 
    {

        public ApplicationUser()
        {

            this._DepartmentUserManager = new HashSet<Model.Department>();

            this._DepartmentStaffUser = new HashSet<Model.DepartmentStaff>();
            this._TicketTaskActUser = new HashSet<Model.TicketTask>();

        }

        public virtual ICollection<Model.Department> _DepartmentUserManager { get; set; }
        public virtual ICollection<Model.DepartmentStaff> _DepartmentStaffUser { get; set; }
        public virtual ICollection<Model.TicketTask> _TicketTaskActUser { get; set; }



        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

    }
}
```

Department.cs:
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Model
{
    [Table("Department")]
    public class Department
    {

        public Department()
        {
            this._DepartmentStaff = new HashSet<Model.DepartmentStaff>();
            this._TicketTaskActDepartment = new HashSet<Model.TicketTask>();
            this._Children = new HashSet<Model.Department>();

        }

        public virtual ICollection<Model.DepartmentStaff> _DepartmentStaff { get; set; }
        public virtual ICollection<Model.TicketTask> _TicketTaskActDepartment { get; set; }
        public virtual ICollection<Model.Department> _Children { get; set; }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string Title { get; set; }

        public int? UserManagerID { get; set; }
        public virtual Model.ApplicationUser UserManager { get; set; }

        public int? ParentId { get; set; }
        public virtual Model.Department Parent { get; set; }

    }
}
```

DepartmentStaff.cs:
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace Model
{
    [Table("DepartmentStaff")]
    public class DepartmentStaff
    {

        public int ID { get; set; }


        public int DepartmentID { get; set; }
        public virtual Model.Department Department { get; set; }


        public int UserID { get; set; }
        public virtual Model.ApplicationUser User { get; set; }


    }
}
```

Task.cs:
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace Model
{
    [Table("TicketTask")]
    public class TicketTask
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        public int TicketID { get; set; }
        //public virtual Model.Ticket Ticket { get; set; }

        [Column(TypeName = "DateTime")]
        public DateTime InsertedDate { get; set; }

        public int? ActDepartmentID { get; set; }
        public virtual Model.Department ActDepartment { get; set; }

        public int? ActUserID { get; set; }
        public virtual Model.ApplicationUser ActUser { get; set; }

        public bool isDone { get; set; }

        [Column(TypeName = "DateTime")]
        public DateTime? DoneDate { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public string InsertedDatePersian { get; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public string DoneDatePersian { get; }

    }
}
```

Program.cs:
```C#
using Microsoft.EntityFrameworkCore;

var _context = new  ConsoleApp1.Data.ApplicationDbContext();

var query = _context
    .TicketTasks
    .Where(x => x.isDone == false && (x.ActDepartment._DepartmentStaff.Any(c => c.UserID == 4) || x.ActUserID == 4))
    .GroupBy(x => x.InsertedDatePersian.Substring(0, 10))
    .Select(g => new { Date = g.Key, Count = g.Count() })
    .AsQueryable();

var queryString = query.ToQueryString();

var r = await query.ToListAsync();
```

### Error
```
Column 'TicketTask.InsertedDatePersian' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
```

### Query String

Query created in version 6.0.1:
```sql
SELECT SUBSTRING([t].[InsertedDatePersian], 0 + 1, 10) AS [Date], COUNT(*) AS [Count]
FROM [TicketTask] AS [t]
LEFT JOIN [Department] AS [d] ON [t].[ActDepartmentID] = [d].[ID]
WHERE ([t].[isDone] = CAST(0 AS bit)) AND (EXISTS (
    SELECT 1
    FROM [DepartmentStaff] AS [d0]
    WHERE ([d].[ID] IS NOT NULL AND ([d].[ID] = [d0].[DepartmentID])) AND ([d0].[UserID] = 4)) OR ([t].[ActUserID] = 4))
GROUP BY SUBSTRING([t].[InsertedDatePersian], 0 + 1, 10)
```

Query created in version 6.0.2:
```sql
SELECT SUBSTRING([t].[InsertedDatePersian], 0 + 1, 10) AS [Date], (
    SELECT COUNT(*)
    FROM [TicketTask] AS [t0]
    LEFT JOIN [Department] AS [d1] ON [t0].[ActDepartmentID] = [d1].[ID]
    WHERE (([t0].[isDone] = CAST(0 AS bit)) AND (EXISTS (
        SELECT 1
        FROM [DepartmentStaff] AS [d2]
        WHERE (([d1].[ID] IS NOT NULL) AND ([d1].[ID] = [d2].[DepartmentID])) AND ([d2].[UserID] = 4)) OR ([t0].[ActUserID] = 4))) AND ((SUBSTRING([t].[InsertedDatePersian], 0 + 1, 10) = SUBSTRING([t0].[InsertedDatePersian], 0 + 1, 10)) OR (([t].[InsertedDatePersian] IS NULL) AND ([t0].[InsertedDatePersian] IS NULL)))) AS [Count]
FROM [TicketTask] AS [t]
LEFT JOIN [Department] AS [d] ON [t].[ActDepartmentID] = [d].[ID]
WHERE ([t].[isDone] = CAST(0 AS bit)) AND (EXISTS (
    SELECT 1
    FROM [DepartmentStaff] AS [d0]
    WHERE (([d].[ID] IS NOT NULL) AND ([d].[ID] = [d0].[DepartmentID])) AND ([d0].[UserID] = 4)) OR ([t].[ActUserID] = 4))
GROUP BY SUBSTRING([t].[InsertedDatePersian], 0 + 1, 10)
```

### Include provider and version information

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)
Operating system:
IDE: (e.g. Visual Studio 2022 17.0.6)

### LINKED ISSUE #27721: GroupBy one field, selecting a sub collection for the data that is grouped and paging the groupby return no result for the sub collection.
Well, a line of code is a thousand words :)
```
DbSet<Membre>()
.GroupBy(m => m.Prenom)
.Select(grp => new { grp.Key, data = grp.Select(m => m.Prenom).ToList() })
.Take(10)
.ToList();
```

The query has been simplified to the smallest possible.

No exception is thrown but the result contains empty collections (the field `data` is always an empty collection.  If I do a group by over more that one field ex: m => new {m.Nom, m.Prenom}, it works.  It works also if I remove the `Take`

A very weird thing is that it does that for specific fields.  If I replace to `GroupBy(m => m.Nom)...` it works.  The field `Nom` is identical (except for the name) as the `Prenom` field.  It fails for other fields.

EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET 6.0)
Operating system: Windows 10
IDE: Visual Studio 2022 17.1.2

### LINKED ISSUE #27796: Queryable.Count throws exception when used with GroupBy and Select with constructor arguments
### Include your code

```csharp
Result.cs
public class Result
{
    public long Id { get; set; }

    public Result(long id)
    {
        Id = id;
    }

    public Result()
    {
        
    }
}
....
// Error Here
 var x = _context.Products
            .GroupBy(x => x.Id)
            .Select(x => new Result(x.Key))
            .Count();
```
The above code throws an exception. The problem seems to be occuring when using GroupBy followed by Select where we are selecting using Constructor arguments as in above code and then performing a Count operation.
The workaround for now is to use object initializer syntax. That seems to be functioning correctly.

This worked perfectly in Ef 5 and should be working in ef 6 as well. 

Repro: https://github.com/RehmatFalcon/ef-err-group-by

> You can view the `HomeController#Index` to see the error.

### Include stack traces

Include the full exception message and stack trace for any exception you encounter.

Use triple-tick fences for stack traces. For example:

```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Linq.Expressions.ExpressionExtensions.GetConstantValue[T](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.GetProjectionIndex(ProjectionBindingExpression projectionBindingExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression, RelationalCommandCache& relationalCommandCache, LambdaExpression& relatedDataLoaders, Int32& collectionId)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Repro.Controllers.HomeController.Index() in D:\Experiments\Repro\Repro\Controllers\HomeController.cs:line 36
   at lambda_method1(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Include provider and version information

EF Core version: 6
Database provider: (e.g. npgsql) --tested with NPGSQL and SQLITE
Target framework: (e.g. .NET 6.0)

### LINKED ISSUE #27801: GroupBy generates invalid SQL when using null/default values
EF Core version: `6.0.3`
Database provider: `Microsoft.EntityFrameworkCore.SqlServer`
Target framework: `.NET 6.0`
Operating system: Windows 11
IDE: Visual Studio 2022

Greetings,
I have the following entity:
```C#
public class UserAction
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public int Action { get; set; }
}
```
I am trying to pull some records from the database, with a `GroupBy` statement, where the grouped-by columns are sort-of dynamic.
This is achieved by another helper class:
```C#
public class UserActionsQuery
{
    public bool GroupByAction { get; set; }
    public bool GroupByUser { get; set; }
}
```
When both `GroupByAction` and `GroupByUser` properties are `true`, there are no issues.
When `GroupByUser` property, for example, is `false` - EF Core seems to generate invalid SQL.
Here is the code that pulls the aggregated records:
```C#
var query = new UserActionsQuery { GroupByAction = true };
context.UserActions.AsNoTracking()
    .GroupBy(
        x => new
        {
            UserId = query.GroupByUser ? (int?)x.UserId : null,
            Action = query.GroupByAction ? (int?)x.Action : null,
        },
        x => x,
        (key, items) => new { UserId = key.UserId, Action = key.Action, Count = items.Count() }
    ).ToArray();
```

The exception that is received is:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): The multi-part identifier "u.Action" could not be bound.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
```
The SQL that EF Core generates is as follows (clearly invalid because of `[u].[Action]`):
```SQL
-- net 6 + ef core 6
SELECT NULL AS [UserId], [u].[Action], COUNT(*) AS [Count]
FROM (
    SELECT [u].[Action], NULL AS [UserId0]
    FROM [UserActions] AS [u]
) AS [t]
GROUP BY [t].[UserId0], [t].[Action]
```
On a side note, the same code run under `.NET 5.0` with `EF Core 5.0.0`, produces this SQL, which seems to be fine:
```SQL
-- net 5 + ef core 5
SELECT NULL AS UserId, u.Action, COUNT(*) AS Count
FROM UserActions AS u
GROUP BY u.Action
```

Please excuse me if this is a duplicate, or if I'm doing something wrong, thank you.

### PR DESCRIPTION
**Pull request by smitpatel**
Design:
- Introduce `SqlEnumerableExpression` - a holder class which indicates the `SqlExpression` is in form of a enumerable (or group) coming as a result of whole table selection or a grouping element. It also stores details about if `Distinct` is applied over grouping or if there are any orderings.
- Due to above `DistinctExpression` has been removed. The token while used to denote `Distinct` over grouping element were not valid in other parts of SQL tree hence it makes more sense to combine it with `SqlEnumerableExpression`.
- To support dual pass, `GroupByShaperExpression` contains 2 forms of grouping element. One element selector form which correlates directly with the parent grouped query, second subquery form which correlates to parent grouped query through a correlation predicate. Element selector is first used to translate aggregation. If that fails we use subquery form to translate as a subquery. Due to 2 forms of same component, GroupByShaperExpression disallows calling into VisitChildren method, any visitor which is visiting a tree containing GroupByShaperExpression (which appears only in `QueryExpression.ShaperExpression` or LINQ expression after remapping but before translation) must intercept the tree and either ignore or process it appropriately.
- An internal visitor (`GroupByAggregateChainProcessor`) inside SqlTranslator visits and process chain of queryable operations on a grouping element before aggregate is called and condense it into `SqlEnumerableExpression` which is then passed to method which translates aggregate. This visitor only processes Where/Distinct/Select for now. Future PR will add processing for OrderBy/ThenBy(Descending) operations to generate orderings.
- Side-effect above is that joins expanded over the grouping element (due to navigations used on aggregate chain), doesn't translate to aggregate anymore since we need to translate the join on parent query, remove the translated join if the chain didn't end in aggregate and also de-dupe same joins. Filing issue to improve this in future. Due to fragile nature of matching to lift the join, we shouldn't try to lift joins.
- To support custom aggregate operations, we will either reused `IMethodCallTranslator` or create a parallel structure for aggregate methods and call into it from SqlTranslator by passing translated SqlEnumerableExpression as appropriate.
- For complex grouping key, we cause a pushdown so that we can reference the grouping key through columns only. This allows us to reference the grouping key in correlation predicate for subquery without generating invalid SQL in many cases.
- With complex grouping key converting to columns, now we are able to correctly generate identifiers for grouping queries which makes more queries with correlated collections (where either parent or inner both queries can be groupby query) translatable.
- Erase client projection when applying aggregate operation over GroupBy result.
- When processing result selector in GroupBy use the updated key selector if the select expression was pushed down.

Resolves #27132
Resolves #27266
Resolves #27433
Resolves #23601
Resolves #27721
Resolves #27796
Resolves #27801
Resolves #19683

Relates to #22957

### CODE REVIEW

File: src/EFCore.Relational/Query/QuerySqlGenerator.cs [hunk 1]
```diff
@@ -506,6 +506,31 @@ protected override Expression VisitSqlBinary(SqlBinaryExpression sqlBinaryExpres
...
     }
 
+    /// <inheritdoc />
+    protected override Expression VisitSqlEnumerable(SqlEnumerableExpression sqlEnumerableExpression)
+    {
+        if (sqlEnumerableExpression.Orderings.Count != 0)
+        {
+            // TODO: Throw error here because we don't know how to print orderings.
+            // Though providers can override this method and generate orderings if they have a way to print it.
+            throw new InvalidOperationException();
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/QuerySqlGenerator.cs:516]: @dotnet/efteam - To suggest exception message.

Comment (roji) [reply src/EFCore.Relational/Query/QuerySqlGenerator.cs:516]: Maybe "The OrderBy operator isn't supported with the aggregate function being used."?

It's a bit problematic that we're not showing the function name... But probably not critical.

BTW I took a quick look, and in SQL Server and PG the ordering isn't expressed on the enumerable parameter, but on the aggregate expression (=function) as a whole (see samples below)... I think that's OK - the provider's translator's responsibility would be to remove the ordering from the SqlEnumerableExpression and to put it on the provider-specific SqlAggregateFunctionExpression, where it would get generated to SQL. Does that correspond to what you want here @smitpatel?

[SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-agg-transact-sql?view=sql-server-ver15#f-generate-a-sorted-list-of-emails-per-towns):

```sql
SELECT TOP 10 City, STRING_AGG(CONVERT(NVARCHAR(max), EmailAddress), ';') WITHIN GROUP (ORDER BY EmailAddress ASC) AS Emails 
FROM Person.BusinessEntityAddress AS BEA  
INNER JOIN Person.Address AS A ON BEA.AddressID = A.AddressID
INNER JOIN Person.EmailAddress AS EA ON BEA.BusinessEntityID = EA.BusinessEntityID 
GROUP BY City;
```

[PostgreSQL](https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-AGGREGATES):

```sql
SELECT string_agg(a, ',' ORDER BY a) FROM table;
```

Comment (smitpatel) [reply src/EFCore.Relational/Query/QuerySqlGenerator.cs:516]: Yes, that is kinda intentional. We put ordering on SqlEnumerable because that is our holder object in a way to pass all information from the groupingElement chain to MethodCallTranslator. All the cases we have discussed where Orderings is indeed used has somewhat fancier syntax which is not covered by our SqlFunction either so provider would need to add custom expression anyway. If we had a better place to put orderings, we could have utilized it. For now, it is either on SqlEnumerable or we pass it separately (which complicates things quite a bit by having 2 lists which remains in sync).
It is translator's responsibility to process ordering and do what is needed.
Open to ideas if we have a better place to put orderings.

Comment (roji) [reply src/EFCore.Relational/Query/QuerySqlGenerator.cs:516]: LGTM

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs [hunk 2]
```diff
@@ -188,15 +203,70 @@ private sealed class SqlRemappingVisitor : ExpressionVisitor
...
+            private readonly HashSet<SqlExpression> _correlatedTerms;
+            private bool _doesNotContainLocalTerms;
+
+            public EnclosingTermFindingVisitor(HashSet<SqlExpression> correlatedTerms)
+            {
+                _correlatedTerms = correlatedTerms;
+                _doesNotContainLocalTerms = true;
+            }
+
+            [return: NotNullIfNotNull("node")]
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs:242]: nit: typo

File: src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs [hunk 3]
```diff
@@ -1457,12 +1467,260 @@ public Expression Convert(Type type)
...
+                nameof(Queryable.LongCount) => _sqlTranslatingExpressionVisitor.TranslateLongCount(sqlExpression),
+                nameof(Queryable.Max) => _sqlTranslatingExpressionVisitor.TranslateMax(sqlExpression),
+                nameof(Queryable.Min) => _sqlTranslatingExpressionVisitor.TranslateMin(sqlExpression),
+                nameof(Queryable.Sum) => _sqlTranslatingExpressionVisitor.TranslateSum(sqlExpression),
+                _ => null,
+            };
+        }
+    }
+
+    private sealed class GroupAggregetingElementExpression : Expression
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs:1661]: GroupAggregatingElementExpression

File: src/EFCore.Relational/Query/QuerySqlGenerator.cs [hunk 4]
```diff
@@ -506,6 +506,31 @@ protected override Expression VisitSqlBinary(SqlBinaryExpression sqlBinaryExpres
...
+        }
+
+        if (sqlEnumerableExpression.IsDistinct)
```
Comment (roji) [inline src/EFCore.Relational/Query/QuerySqlGenerator.cs:519]: I looked into this in #27948...

PG is the only DB which permits DISTINCT in an aggregate function with multiple enumerable parameters - and the DISTINCT operators over the input row, rather than on the specific argument:

```sql
-- Works:
SELECT json_object_agg(DISTINCT jkey, jval) FROM data;
-- DISTINCT on a specific argument is not supported:
SELECT json_object_agg(jkey, DISTINCT jval) FROM data;
```

So in theory, the current code would be inappropriate e.g. if there's an aggregate function where the enumerable paramter isn't the first.

But that's all pretty theoretical. In practice, I think the current code is ok and will cover current known functions.

File: src/EFCore.Relational/Query/SqlExpressions/SqlEnumerableExpression.cs [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+        => sqlExpression != SqlExpression || !orderings.SequenceEqual(Orderings)
+            ? new SqlEnumerableExpression(sqlExpression, IsDistinct, orderings)
+            : this;
+
+    /// <inheritdoc />
+    protected override void Print(ExpressionPrinter expressionPrinter)
+    {
+        if (IsDistinct)
+        {
+            expressionPrinter.Append("DISTICT (");
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlExpressions/SqlEnumerableExpression.cs:72]:
```suggestion
            expressionPrinter.Append("DISTINCT (");
```

**Review by maumar — APPROVED** [review]

File: src/EFCore.Relational/Query/QuerySqlGenerator.cs (hunk 4 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/QuerySqlGenerator.cs:519]: Leaving code as is now and we will resolve #27948 before 7.0. I have some ideas around it, I will present in design meeting.

Comment (roji) [reply src/EFCore.Relational/Query/QuerySqlGenerator.cs:519]: Sounds good! Looking forward to hearing your ideas.

**Comment by ColinZeb** [comment]
Is this expected to be released to 7.0 prview5?
Is there any plan to release to 6.0.5?
