### PR TITLE
Stop moving pending selector after DefaultIfEmpty in nav expansion

### LINKED ISSUE #36208: NavigationExpandingExpressionVisitor moves Select() behind DefaultIfEmpty()
### Question

Hello, 

I am currently writing an EntityFramework Provider. While translating the expression produced by NorthwindSelectQueryTestBase.SelectMany_correlated_with_outer_3, I noticed that the NavigationExpandingExpressionVisitor moves the .Select(o => c.City) behind the .DefaultIfEmpty().

I'm probably missing something, but this seems wrong, as 
Enumerable.Empty<object>().DefaultIfEmpty().Select(x => "foo")
is not the same as
Enumerable.Empty<object>().Select(x => "foo").DefaultIfEmpty()

So now I'm left wondering how to handle this, because there are valid uses for both cases. Once the NavigationExpandingExpressionVisitor transforms the expression however I can no longer distinguish between these cases.

From what I've seen SQL-Server translates in a kind of wierd way:

SELECT [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region], [o0].[City] AS [o]
FROM [Customers] AS [c]
OUTER APPLY (
    SELECT [c].[City]
    FROM [Orders] AS [o]
    WHERE [c].[CustomerID] = [o].[CustomerID]
) AS [o0]

I would expect if I have 1 customer with 2 orders to get 2 result rows, SQL-Server produces only one row.

I would be very thankful if you could give me some pointers on what the actual behaviour should be.

Best Regards

### Your code

```csharp
NorthwindSelectQueryTestBase.SelectMany_correlated_with_outer_3:

from c in ss.Set<Customer>()
from o in ss.Set<Order>().Where(o => c.CustomerID == o.CustomerID).Select(o => c.City).DefaultIfEmpty()
select new { c, o }

Here's what the query looks like just before and after the call to the NavigationExpandingExpressionVisitor in QueryTranslationPreprocessor.cs Process(Expression query)

Before NavigationExpandingExpressionVisitor:

[Microsoft.EntityFrameworkCore.Query.EntityQueryRootExpression]
  .SelectMany(c => 
    [Microsoft.EntityFrameworkCore.Query.EntityQueryRootExpression]
      .Where(o => (c.CustomerID == o.CustomerID))
      .Select(o => c.City)
      .DefaultIfEmpty(), 
    (c, o) => new <>f__AnonymousType0`2(c = c, o = o)
  )

After NavigationExpandingExpressionVisitor:

[Microsoft.EntityFrameworkCore.Query.EntityQueryRootExpression]
  .SelectMany(c => 
    [Microsoft.EntityFrameworkCore.Query.EntityQueryRootExpression]
      .Where(o => (c.CustomerID == o.CustomerID))
      .DefaultIfEmpty()
      .Select(o => c.City),
    (c, c) => new TransparentIdentifier`2(Outer = c, Inner = c))
  .Select(ti => new <>f__AnonymousType0`2(c = ti.Outer, o = ti.Inner))
```

### Stack traces

```text

```

### Verbose output

```text

```

### EF Core version

9.0.0

### Database provider

_No response_

### Target framework

.NET 9.0

### Operating system

_No response_

### IDE

_No response_

### PR DESCRIPTION
**Pull request by roji**
This changes the NavigationExpandingExpressionVisitor around DefaultIfEmpty, applying any pending selector; this prevents any Select prior to the DIE from being moved after it.

This unfortunately caused some complications... Nav expansion was also previously responsible for adding a coalesce for value types, and relied on the fact that the Select gets moved after the DIE. Now that the Select stays before the DIE, the coalesce gets optimized away as it's not yet needed (the column hasn't yet been made nullable by DIE).

This logic doesn't strictly-speaking belong in nav expansion (or anywhere in preprocessing), and this PR moves it to the translation phase of DIE instead (translation was already handling making projected columns nullable, and is the right place for also applying a COALESCE when necessary).

Fixes #36208

### CODE REVIEW

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs [hunk 1]
```diff
@@ -966,23 +966,21 @@ private Expression ProcessContains(NavigationExpansionExpression source, Express
...
+        source = (NavigationExpansionExpression)_pendingSelectorExpandingExpressionVisitor.Visit(source);
+        var newStructure = SnapshotExpression(source.PendingSelector);
+        newStructure = _entityReferenceOptionalMarkingExpressionVisitor.Visit(newStructure);
+        var queryable = Reduce(source);
 
-        var pendingSelector = source.PendingSelector;
-        _entityReferenceOptionalMarkingExpressionVisitor.Visit(pendingSelector);
-        if (!pendingSelector.Type.IsNullableType())
-        {
-            pendingSelector = Expression.Coalesce(
```
Comment (roji) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs:978]: Note the removal of Coalesce which was added (see main PR notes for context).

**Review by cincuranet — APPROVED** [review]
