### PR TITLE
Query: Infer type mapping from IDbFunction while translating

### LINKED ISSUE #27524: RelationalMethodCallTranslatorProvider and explicit typeMapping
Hi,
is it on purpose that `dbFunction.TypeMapping` is not passed in into these calls, but the default `null` is used?

https://github.com/dotnet/efcore/blob/f8585c2166974887eac17063a7b180316a537218/src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs#L78-L91

We have some SQL function returning `string[]`, and have to use `HasDbFunction` with a more complex `HasTranslation` instead of the simple fluent API, presumably because of this.

### LINKED ISSUE #27954: Function StoreType is ignored for DateTime
I Have an Entity:

```c#
public class MyEntity 
{
    public int Id { get; set; } 
    public DateTime SomeDate { get; set; }
    public static DateTime Modify(DateTime date) => throw new NotSupportedException();
}
```

with configuration:

```c#
modelBuilder.ToTable("MyEntity", "dbo");
modelBuilder.HasKey(x => x.Id);
modelBuilder.Property(x => x.SomeDate).HasColumnType("datetime");
```

SQL scalar value function:
function [dbo].[ModifyDate] (@dt datetime) returns datetime

and a mapping to static method

```c#
modelBuilder
                .HasDbFunction(
                    typeof(MyEntity).GetMethod(nameof(MyEntity.Modify)))
                .HasName("ModifyDate")
                .HasStoreType("datetime")
                .HasSchema("dbo");
```

LINQ to SQL query:

```c#
var date = new DateTime(...);
DbSet<MyEntity>().Where(x => x.SomeDate == date).ToArray();
```

works correctly, but

```
DbSet<MyEntity>().Where(x => MyEntity.Modify(x.SomeDate) == date).ToArray();
```

fails with SqlException saying that it cannot convert string to a datetime.

The reason of SqlException is that ef core ignores function StoreType and converts 'date' to DateTime2
string representation 2011-05-15T18:54:00.0000000Z while in the first case it is 2011-05-15T18:54:00.000

### PR DESCRIPTION
**Pull request by smitpatel**
- We use TypeMapping if configured on the DbFunction, or
- We try to get it if store type is specified
- If neither of above work then we do the default type mapping based on return type

Resolves https://github.com/dotnet/efcore/issues/27954
Resolves https://github.com/dotnet/efcore/issues/27524

### CODE REVIEW

File: src/EFCore.Relational/Metadata/Conventions/ScalarDbFunctionTypeMappingConvention.cs [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+        IConventionDbFunctionBuilder dbFunctionBuilder)
+    {
+        var function = dbFunctionBuilder.Metadata;
+        if (!function.IsScalar
+            || function.StoreType == null)
+        {
+            return;
+        }
+
+        var typeMapping = ((IRelationalTypeMappingSource)Dependencies.TypeMappingSource).FindMapping(function.ReturnType, function.StoreType);
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/ScalarDbFunctionTypeMappingConvention.cs:59]: Instead of adding a convention it would be better to fix the logic in https://github.com/dotnet/efcore/blob/0d1d602d72fefe14f12a86410ec70394ec8151e0/src/EFCore.Relational/Metadata/Internal/DbFunction.cs#L542
and https://github.com/dotnet/efcore/blob/0d1d602d72fefe14f12a86410ec70394ec8151e0/src/EFCore.Relational/Metadata/RuntimeDbFunction.cs#L101

Comment (smitpatel) [reply src/EFCore.Relational/Metadata/Conventions/ScalarDbFunctionTypeMappingConvention.cs:59]: I am fine with either. It felt like that we have the TypeMapping property but we never populated it. If we go non-convention route, we should obsolete and later remove the property if we don't plan to populate it.

Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Conventions/ScalarDbFunctionTypeMappingConvention.cs:59]: The property is still potentially useful for workarounds
The usage pattern will change with https://github.com/dotnet/efcore/issues/9329

Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Conventions/ScalarDbFunctionTypeMappingConvention.cs]: In what cases it's not set? We throw in model validation for null TypeMapping

Comment (smitpatel) [reply src/EFCore.Relational/Metadata/Conventions/ScalarDbFunctionTypeMappingConvention.cs]: Where do we set it? 😄 Couldn't figure that out. But if we are setting it somewhere then I can just use it rather than trying to find.

Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Conventions/ScalarDbFunctionTypeMappingConvention.cs]: We "set" it at 
https://github.com/dotnet/efcore/blob/0d1d602d72fefe14f12a86410ec70394ec8151e0/src/EFCore.Relational/Metadata/Internal/DbFunction.cs#L542
and https://github.com/dotnet/efcore/blob/0d1d602d72fefe14f12a86410ec70394ec8151e0/src/EFCore.Relational/Metadata/RuntimeDbFunction.cs#L101

**Review by AndriySvyryd — APPROVED** [review]

File: test/EFCore.Relational.Specification.Tests/Query/SimpleQueryRelationalTestBase.cs [hunk 2]
```diff
@@ -49,6 +51,56 @@ protected override void OnModelCreating(ModelBuilder modelBuilder)
...
+            }
+
+            public DbSet<MyEntity> MyEntities { get; set; }
+
+            protected override void OnModelCreating(ModelBuilder modelBuilder)
+            {
+                modelBuilder
+                    .HasDbFunction(typeof(MyEntity).GetMethod(nameof(MyEntity.Modify)))
+                    .HasName("ModifyDate")
+                    .HasStoreType("datetime")
```
Comment (roji) [inline test/EFCore.Relational.Specification.Tests/Query/SimpleQueryRelationalTestBase.cs:92]: :crying_cat_face: 

Not easy to override this for databases which don't have a `datetime` store type... In any case, this test seems a bit SQL Server-specific, do we want to move it therE?

Comment (AndriySvyryd) [reply test/EFCore.Relational.Specification.Tests/Query/SimpleQueryRelationalTestBase.cs:92]: `HasStoreType(null)` should work
