### PR TITLE
Throw a better exception when the model is read-only.

### LINKED ISSUE #15812: Improve the exception message when altering a read-only model
### Problem
I have a method for change table name dynamically

```c#
        private static RelationalEntityTypeAnnotations GetRelationalEntityType(this DbContext dbContext, Type type)
        {
            return dbContext.Model.FindEntityType(type).Relational() as RelationalEntityTypeAnnotations;
        }

        public static void ChangeTable(this DbContext dbContext, Type type, string tableName)
        {

            var relational = dbContext.GetRelationalEntityType(type);
            if (relational != null)
            {
                relational.TableName = tableName;
            }
        }

        public static DbSet<TEntity> ChangeTable<TEntity>(this DbSet<TEntity> dbSet, string tableName) where TEntity : class
        {
            var dbContext = dbSet.GetService<ICurrentDbContext>().Context;
            dbContext.ChangeTable(typeof(TEntity), tableName);
            return dbSet;
        }
```

the above code work fine in 2.X

but in 3.0 preview5 will throw an exception

```
System.NullReferenceException : Object reference not set to an instance of an object.
  堆栈跟踪: 
    在 EntityType.OnAnnotationSet(String name, Annotation annotation, Annotation oldAnnotation)
    在 Annotatable.SetAnnotation(String name, Object value)
    在 RelationalAnnotations.SetAnnotation(String annotationName, Object value)
    在 RelationalEntityTypeAnnotations.set_TableName(String value)
    在 DbExtensions.ChangeTable(DbContext dbContext, Type type, String tableName) 在 DbExtensions.cs 行: 39
    在 DbExtensions.ChangeTable[TEntity](DbSet`1 dbSet, String tableName) 在 DbExtensions.cs 行: 30
    在 DbExtensionsTest.ChangeTable_SqlServer() 在 DbExtensionsTest.cs 行: 23
    在 DbExtensionsTest.ChangeTable_SqlServer() 在 DbExtensionsTest.cs 行: 31
    在 --- End of stack trace from previous location where exception was thrown ---
```

### Further technical details
EF Core version:3.0.0-preview5.19227.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer or Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10
IDE: Visual Studio 2019 16.2.0 Preview 1.0

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #15812

### CODE REVIEW

File: src/EFCore/Infrastructure/Annotatable.cs [hunk 1]
```diff
@@ -33,6 +33,26 @@ public class Annotatable : IMutableAnnotatable
...
+        ///     </para>
+        /// </summary>
+        protected virtual bool IsReadonly => false;
+
+        /// <summary>
+        ///     Throws if the model is not read-only.
+        /// </summary>
+        protected virtual void EnsureReadonly(bool shouldBeReadonly = true)
+        {
+            if (!shouldBeReadonly && IsReadonly)
```
Comment (roji) [inline src/EFCore/Infrastructure/Annotatable.cs:50]: Shouldn't this also throw when shouldBeReadonly is true but IsReadonly is false? Or if we only use this to ensure wriability, we can just have an EnsureWritable instead (might be a good idea to have that regardless, as it's called so many times)

**Review by roji — APPROVED** [review]

File: src/EFCore/Infrastructure/Annotatable.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore/Infrastructure/Annotatable.cs:50]: I'll do the former in the next PR
