### PR TITLE
Fix for 4050. IndexAttribute.

### LINKED ISSUE #4050: Support an [Index] attribute
We didn't bring this over from EF6.x because it had a lot of issues... but opening this issue to track the possibility of adding it in the future since a number of folks have asked for it (see discussion on #1698).

### PR DESCRIPTION
**Pull request by lajones**
Fixes #4050 - allow an index to be configured using an `IndexAttribute`.

~~(Note: there's some support for TPT which doesn't work yet - marked by TODO's. I can add those in once PR #20938 is checked in).~~ PR #20938 is checked in - TPT support now included.

### CODE REVIEW

File: src/EFCore/Metadata/Conventions/IndexEntityTypeAttributeConvention.cs [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+            IConventionContext<IConventionEntityTypeBuilder> context)
+        {
+            var entityType = entityTypeBuilder.Metadata;
+            var ignoredMembers = entityType.GetIgnoredMembers();
+            var indexProperties = new List<IConventionProperty>();
+            foreach (var memberName in attribute.MemberNames)
+            {
+                if (string.IsNullOrWhiteSpace(memberName))
+                {
+                    throw new InvalidOperationException(
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/IndexEntityTypeAttributeConvention.cs:41]: Conventions should log warning rather than throw exception.

Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexEntityTypeAttributeConvention.cs:41]: Not sure why you are saying that? There are many conventions that throw.

Comment (smitpatel) [reply src/EFCore/Metadata/Conventions/IndexEntityTypeAttributeConvention.cs:41]: From what I remember, only `IModelFinalizingConvention`  (or the newer `IModelFinalizedConvention`) throws. If a convention arrives at something incorrect configuration, user can still correct it using fluent API. Hence conventions are not supposed to throw exceptions till OnModelCreating is run.
For conventions which applies attribute, we log a warning, ignore them. It is same logic as only ConfigurationSource.Explicit throws but other 2 configuration source don't throw exceptions.

Of course, @AndriySvyryd knows what to do.

Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexEntityTypeAttributeConvention.cs:41]: OK. I'll defer to @AndriySvyryd, but here the user is mis-using the `IndexAttribute` (see the test cases) - I think it's clearer to tell them to go back and update how they use the attribute.

File: src/EFCore.Abstractions/IndexAttribute.cs [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+using System;
+using JetBrains.Annotations;
+using Microsoft.EntityFrameworkCore.Utilities;
+
+namespace Microsoft.EntityFrameworkCore
+{
+    /// <summary>
+    ///     Specifies an index to be generated in the database.
+    /// </summary>
+    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
```
Comment (roji) [inline src/EFCore.Abstractions/IndexAttribute.cs:13]: We need to think about inheritability here (true by default, probably should be false). Specifically, for a TPH hierarchy, if [Index] is specified on a base class, it should definitely only lead to us creating only one index.

File: src/EFCore.Abstractions/IndexAttribute.cs [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+        public IndexAttribute(params string[] memberNames)
+        {
+            Check.NotEmpty(memberNames, nameof(memberNames));
+            MemberNames = memberNames;
+        }
+
+        /// <summary>
+        ///     The members which constitute the index, in order.
+        /// </summary>
+        public virtual string[] MemberNames { get; }
```
Comment (roji) [inline src/EFCore.Abstractions/IndexAttribute.cs:29]: I think in general our attributes are sealed and therefore also non-virtual (and exception seems to be DbFunction, which seems to be this way mainly to not break). This think [Index] should be sealed as well.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs [hunk 4]
```diff
@@ -748,5 +749,73 @@ protected virtual object GetDefaultColumnValue([NotNull] IProperty property)
...
+                        var tablesMappedToMemberCount = tablesMappedToMember.Count();
+                        if (tablesMappedToMemberCount == 0)
+                        {
+                            throw new InvalidOperationException(
+                                RelationalStrings.IndexMemberNotMappedToAnyTable(
+                                    entityType.DisplayName(),
+                                    Format(index.Properties.Select(p => p.Name)),
+                                    member.Name));
+                        }
+                        else if (tablesMappedToMemberCount > 1)
```
Comment (roji) [inline src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:783]: nit: else not needed

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs [hunk 5]
```diff
@@ -748,5 +749,73 @@ protected virtual object GetDefaultColumnValue([NotNull] IProperty property)
...
+            [NotNull] IModel model, [NotNull] IDiagnosticsLogger<DbLoggerCategory.Model.Validation> logger)
+        {
+            Check.NotNull(model, nameof(model));
+
+            foreach (var entityType in model.GetEntityTypes())
+            {
+                foreach (var index in entityType.GetIndexes())
+                {
+                    (string MemberName, string Table, string Schema) existingTableMapping = (null, null, null);
+                    foreach (var member in index.Properties)
```
Comment (roji) [inline src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: nit: rename member to property?

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs [hunk 6]
```diff
@@ -748,5 +749,73 @@ protected virtual object GetDefaultColumnValue([NotNull] IProperty property)
...
+                    {
+                        //TODO - update to use table-schema override of GetColumn() below when PR #20938 is checked in
+                        var tablesMappedToMember = member.DeclaringEntityType.GetDerivedTypesInclusive()
```
Comment (roji) [inline src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:771]: Multiple enumeration of this LINQ, probably need to do ToArray

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs [hunk 7]
```diff
@@ -748,5 +749,73 @@ protected virtual object GetDefaultColumnValue([NotNull] IProperty property)
...
+        protected virtual void ValidateIndexMembersOnSameTable(
+            [NotNull] IModel model, [NotNull] IDiagnosticsLogger<DbLoggerCategory.Model.Validation> logger)
+        {
+            Check.NotNull(model, nameof(model));
+
+            foreach (var entityType in model.GetEntityTypes())
+            {
+                foreach (var index in entityType.GetIndexes())
+                {
+                    (string MemberName, string Table, string Schema) existingTableMapping = (null, null, null);
```
Comment (roji) [inline src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:767]: Rather than getting the table and schema name, it's probably better to use the relational model, i.e. do GetTableMappings and check that they point to the same ITable instance etc.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs [hunk 8]
```diff
@@ -748,5 +749,73 @@ protected virtual object GetDefaultColumnValue([NotNull] IProperty property)
...
+                        var tablesMappedToMember = member.DeclaringEntityType.GetDerivedTypesInclusive()
+                            .Select(t => (t.GetTableName(), t.GetSchema())).Distinct()
+                            .Where(n => member.GetColumnName(/* n.Item1, n.Item2 */) != null);
+                        var tablesMappedToMemberCount = tablesMappedToMember.Count();
+                        if (tablesMappedToMemberCount == 0)
+                        {
+                            throw new InvalidOperationException(
+                                RelationalStrings.IndexMemberNotMappedToAnyTable(
+                                    entityType.DisplayName(),
+                                    Format(index.Properties.Select(p => p.Name)),
```
Comment (roji) [inline src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:780]: The index name is missing here (and below). It may also be better to omit the entire property list when there's a specific offending property in it.

File: src/EFCore.Relational/Properties/RelationalStrings.resx [hunk 9]
```diff
@@ -584,4 +584,13 @@
   <data name="DbFunctionAggregateCustomTranslation" xml:space="preserve">
     <value>Cannot set custom translation on the DbFunction '{function}' since it is an aggregate function.</value>
   </data>
+  <data name="IndexMemberNotMappedToAnyTable" xml:space="preserve">
+    <value>An index on the entity type '{entityType}' specifies members {indexMemberList}. But the property or field with name '{memberName}' is not mapped to a column in any table. Please use only members mapped to a column.</value>
```
Comment (roji) [inline src/EFCore.Relational/Properties/RelationalStrings.resx:588]: nit: missing quotes around indexMemberList (but consider removing altogether as the memberName is already there)

File: src/EFCore.Abstractions/IndexAttribute.cs (hunk 2 above)
Comment (lajones) [reply src/EFCore.Abstractions/IndexAttribute.cs:13]: Agreed. Will look into this.

File: src/EFCore.Abstractions/IndexAttribute.cs (hunk 3 above)
Comment (lajones) [reply src/EFCore.Abstractions/IndexAttribute.cs:29]: Darn. I meant to do that but forgot. Will do.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 5 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: I think `index.Properties` can refer to a field, but due to historic reasons is called `Properties`. I'll check but I think `member` is more accurate.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 7 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:767]: Curious. Why is that better?

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 5 above)
Comment (roji) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: Specifically in this context, we're looking at the model and index.Properties is a list of IProperty no? If so, I think we should be talking about properties rather than members.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 8 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:780]: No, this was deliberate. The name of an index is optional. The thing that makes an index unique (and defines it when there are multiple indexes) is the ordered list of properties. I thought about having a different message if there was also a name, but in the end I decided to keep it simple.

File: src/EFCore.Relational/Properties/RelationalStrings.resx (hunk 9 above)
Comment (lajones) [reply src/EFCore.Relational/Properties/RelationalStrings.resx:588]: `indexMemberList` doesn't need quotes - it looks something like `{'member1', 'member2', ...}` (the same way other member/property-lists are defined for other messages).

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 5 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: Yes, but `IProperty` can represent a member - it was named `IProperty` historically and too late to change it now, but see the following from `IPropertyBase`:

```C#
        /// <summary>
        ///     Gets the <see cref="PropertyInfo" /> for the underlying CLR property for this property-like object.
        ///     This may be <see langword="null" /> for shadow properties or if mapped directly to a field.
        /// </summary>
        PropertyInfo PropertyInfo { get; }

        /// <summary>
        ///     Gets the <see cref="FieldInfo" /> for the underlying CLR field for this property-like object.
        ///     This may be <see langword="null" /> for shadow properties or if the backing field is not known.
        /// </summary>
        FieldInfo FieldInfo { get; }
```

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 6 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:771]: I either do `Count()` followed by `Select()`, or I do `Count()` followed by `Single()`. I'm not altering the enumeration while I do any of that - so I thought that was safe?

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 8 above)
Comment (roji) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:780]: It seems like if the user took the trouble to define a name for the index, that name should be logged... And indeed if it is, then the set of properties seem redundant as the name is sufficient.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 7 above)
Comment (roji) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:767]: It's the same functionally, but we now have a 1st-class relational model which represents the tables and columns mapped to by entities. Rather than getting the schema/name for entities - which itself goes through the relational model - and then doing distinct on those, it seems more appropriate to just look at the tables directly. Basically the same reason we prefer to compare two objects by reference rather than comparing their string names, even if those string names are guaranteed to be unique.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 6 above)
Comment (roji) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:771]: Oh it's safe - it's just that since LINQ is lazy, your expression is evaluated twice - once for the Count, and once for the Select below. That means you're walking the type hierarchy, projecting the schema/table, doing distinct and filtering twice instead of once.

File: src/EFCore/Metadata/Conventions/IndexEntityTypeAttributeConvention.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexEntityTypeAttributeConvention.cs:41]: Thought about this a bit more. I think the white-space check should stay here (and still throw) - as that's clearly immediate misuse of the attribute, but the ignored check and the non-existent property check could be changed if something in a later convention changed whether a property was ignored or e.g. changed a base-type. So how about I move those 2 checks to an implementation of `IModelFinalizingConvention` (in the same class) and then there's no problem with throwing.

File: src/EFCore.Abstractions/IndexAttribute.cs (hunk 2 above)
Comment (AndriySvyryd) [reply src/EFCore.Abstractions/IndexAttribute.cs:13]: We should still create the index if the attribute is specified on an unmapped base class. Calling `.HasIndex` with the same properties will return the existing one, so there's nothing to do here (except adding some tests).

File: src/EFCore.Abstractions/IndexAttribute.cs [hunk 10]
```diff
@@ -0,0 +1,42 @@
...
+        /// <summary>
+        ///     The name of the index in the database.
+        /// </summary>
+        public virtual string Name { get; [param: NotNull] set; }
+
+
+        /// <summary>
+        ///     Whether the index is unique.
+        /// </summary>
+        public virtual bool IsUnique { get; set; }
```
Comment (AndriySvyryd) [inline src/EFCore.Abstractions/IndexAttribute.cs:40]: This should be `bool?`

File: src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs [hunk 11]
```diff
@@ -745,17 +745,32 @@ protected virtual void GenerateKeyAnnotations([NotNull] IKey key, [NotNull] Inde
             stringBuilder
                 .AppendLine()
                 .Append(builderName)
-                .Append(".HasIndex(")
+                .Append(".")
+                .Append(nameof(EntityTypeBuilder.HasIndex))
```
Comment (AndriySvyryd) [inline src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs:749]: We were are using a literal here on purpose. We want tests the fail if this method is renamed.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 8 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:780]: Agreed (sort of).

There's nothing stopping you giving 2 indexes the same name. There are scenarios where e.g. an entity defines properties `A`, `B`, `C` and `D`, where there's an index on `{A, B}` and another on `{C, D}`. If `A` and `B` are mapped to `Table1` and `C` and `D` are mapped to `Table2`, then it's perfectly fine for them to have the same index name (note: I'm not saying I think that's a good idea, I'm just saying we should not forbid it - and specifically that if that was the case in an existing DB then we should allow an entity that does that).

That said, that scenario is not likely, and I agree that, if the index name exists, outputting it in the error message would help you identify the index, so I'll do that. I think the set of properties should not be omitted - as that is the one unique identifier in the scenario above - but where the index name exists I'll feature it at the start of the error message.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 7 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:767]: Sounds good to me. But I'd like to check with @AndriySvyryd - I got the code at L771 from him and his TPT PR #20938 has a lot of code that depends on `(tableName, schema)` in this same way.

File: src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs [hunk 12]
```diff
@@ -408,7 +408,15 @@ private void GenerateEntityType(IEntityType entityType, bool useDataAnnotations)
 
             foreach (var index in entityType.GetIndexes())
             {
-                GenerateIndex(index);
+                // If there are annotations that cannot be represented
+                // using an IndexAttribute then use fluent API even
+                // if useDataAnnotations is true.
+                if (!useDataAnnotations
+                    || index.GetAnnotations().Any(
+                        a => !RelationalAnnotationNames.TableIndexMappings.Equals(a.Name, StringComparison.Ordinal)))
```
Comment (AndriySvyryd) [inline src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs:416]: Extract this to avoid potential errors if we add another handled annotation.

File: src/EFCore/Metadata/Internal/Index.cs [hunk 13]
```diff
@@ -138,6 +141,44 @@ public virtual bool IsUnique
...
 
+        /// <summary>
+        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+        ///     any release. You should only use it directly in your code with extreme caution and knowing that
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        public virtual string Name
+        {
+            get => _name;
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/Index.cs:152]:
```suggestion
            get => _name ?? this.GetDefaultName()
```

File: src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs [hunk 14]
```diff
@@ -22,9 +23,8 @@ public static class RelationalIndexExtensions
         /// </summary>
         /// <param name="index"> The index. </param>
         /// <returns> The name for this index. </returns>
-        public static string GetName([NotNull] this IIndex index) =>
-            (string)index[RelationalAnnotationNames.Name]
-            ?? index.GetDefaultName();
+        public static string GetName([NotNull] this IIndex index)
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs:26]: Obsolete this too

Comment (AndriySvyryd) [reply src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs:26]: And replace it with GetDatabaseName()

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 7 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:767]: Relational model is not available before validation is finished

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 5 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: This should be `property`. Entity type members are properties, service properties and navigations

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 8 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:780]: More info in exception is good even if sometimes redundant. However this should be a warning instead, in principle there's nothing wrong with having an unmapped index.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs [hunk 15]
```diff
@@ -748,5 +749,73 @@ protected virtual object GetDefaultColumnValue([NotNull] IProperty property)
...
+                                    member.Name));
+                        }
+                        else if (tablesMappedToMemberCount > 1)
+                        {
+                            throw new InvalidOperationException(
+                                RelationalStrings.IndexMemberMappedToMultipleTables(
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:786]: This is not an error, with TPC it will be unavoidable

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs [hunk 16]
```diff
@@ -748,5 +749,73 @@ protected virtual object GetDefaultColumnValue([NotNull] IProperty property)
...
+
+                        var table = tablesMappedToMember.Single();
+                        if (existingTableMapping.MemberName == null)
+                        {
+                            existingTableMapping = (member.Name, table.Item1, table.Item2);
+                        }
+                        else if (!string.Equals(existingTableMapping.Table, table.Item1, StringComparison.Ordinal)
+                            || !string.Equals(existingTableMapping.Schema, table.Item2, StringComparison.Ordinal))
+                        {
+                            throw new InvalidOperationException(
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:801]: This should be a warning. An index could have valid mapping in one table, but not another

File: src/EFCore/Metadata/Builders/IndexBuilder.cs [hunk 17]
```diff
@@ -74,6 +74,21 @@ public virtual IndexBuilder IsUnique(bool unique = true)
             return this;
         }
 
+        /// <summary>
+        ///     Configures the name of this index.
+        /// </summary>
+        /// <param name="name">
+        ///     The name of this index (can be <see langword="null"/>
+        ///     to indicate that a unique name should be generated).
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Builders/IndexBuilder.cs:82]: Drop the parenthesis

File: src/EFCore.Abstractions/IndexAttribute.cs [hunk 18]
```diff
@@ -0,0 +1,42 @@
...
+            MemberNames = memberNames;
+        }
+
+        /// <summary>
+        ///     The members which constitute the index, in order.
+        /// </summary>
+        public virtual string[] MemberNames { get; }
+
+        /// <summary>
+        ///     The name of the index in the database.
```
Comment (AndriySvyryd) [inline src/EFCore.Abstractions/IndexAttribute.cs:32]:
```suggestion
        ///     The name of the index.
```

File: src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs (hunk 11 above)
Comment (lajones) [reply src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs:749]: OK. I'll put it back and add a comment.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 8 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:780]: Can you give me an example of what scenario would produce this? I was wondering in the tests how to produce this result and that will help me understand better what to do here. At the end of the day we want to produce SQL for an index that will specify a number of columns. If this property does not map to any column in any table then I'm not sure what SQL we would produce?

File: src/EFCore/Metadata/Conventions/IndexEntityTypeAttributeConvention.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/IndexEntityTypeAttributeConvention.cs:41]: Move the first exception to `IndexAttribute`. Move the other two to `ProcessModelFinalizing`.
Make the second one log at `Information` level. And only if `HasIndex` returns `null`

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 8 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:780]: You'd need to call `.ToTable(null)` on the declaring entity type

Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:780]: Also, call `index.Properties.Format()` instead

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 5 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: @AndriySvyryd Are you saying that if an entity has a field you want me to refer to it as a property? I find that confusing because it doesn't agree with the C# definition. I agree `propertyOrField` would be more precise than `member`, but we've used `member` for this concept in the past (I'm thinking about the work I did on #11410).

File: test/EFCore.Relational.Tests/Metadata/RelationalMetadataBuilderExtensionsTest.cs [hunk 19]
```diff
@@ -147,6 +147,7 @@ public void Can_access_index()
             entityTypeBuilder.Property(typeof(int), "Id", ConfigurationSource.Convention);
             var indexBuilder = entityTypeBuilder.HasIndex(new[] { "Id" }, ConfigurationSource.Convention);
 
+#pragma warning disable CS0618 // Type or member is obsolete
```
Comment (AndriySvyryd) [inline test/EFCore.Relational.Tests/Metadata/RelationalMetadataBuilderExtensionsTest.cs:150]: Use new API instead

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 5 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: No, we are talking about entity type properties not CLR properties here (IProperty vs IPropertyInfo)

File: src/EFCore.Abstractions/IndexAttribute.cs (hunk 2 above)
Comment (lajones) [reply src/EFCore.Abstractions/IndexAttribute.cs:13]: Agreed. And agree I should add some tests for this scenario. But we'd be wasting our time to define the index multiple times. Is there a reason to _not_ set `Inherit = false` in the `AttributeUsage` for `IndexAttribute` so that when I ask for the IndexAttributes on a given entity type I only get the ones on that entity type and not on its base-type(s)?

File: src/EFCore.Abstractions/IndexAttribute.cs (hunk 10 above)
Comment (lajones) [reply src/EFCore.Abstractions/IndexAttribute.cs:40]: I didn't find I needed this. What scenario are you trying to cover? `[Index(property)]` means the same as  `[Index(property, IsUnique = false)]`.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 15 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:786]: This was the scenario we discussed. Since we don't support TPC yet I thought we were going to throw here and I'd raise an issue to discuss what to do in the future when this scenario becomes available.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 16 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:801]: Not understanding. At the end of the day we'll need to produce a SQL INDEX statement on one table - if the members map to different tables then that seems like an invalid scenario?

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 15 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:786]: All the scenarios that would hit this are valid, the check to discuss is the next one where the index could be valid in one of the tables but not the others

File: src/EFCore/Metadata/Builders/IndexBuilder.cs (hunk 17 above)
Comment (lajones) [reply src/EFCore/Metadata/Builders/IndexBuilder.cs:82]: OK. Will replace with "which".

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 16 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:801]: Consider this model A { Id }, B : A { Name}, mapped as TPT. B has an IndexAttribute for { Name, Id }.
This index can't be created in the table for A, because Name is not mapped there, but it's valid in table for B and there's no other way of specifying it.

File: src/EFCore.Abstractions/IndexAttribute.cs (hunk 10 above)
Comment (AndriySvyryd) [reply src/EFCore.Abstractions/IndexAttribute.cs:40]: Without this a convention wouldn't be able to configure the index as unique

File: test/EFCore.Relational.Tests/Metadata/RelationalMetadataBuilderExtensionsTest.cs (hunk 19 above)
Comment (lajones) [reply test/EFCore.Relational.Tests/Metadata/RelationalMetadataBuilderExtensionsTest.cs:150]: So I did this to test that the old (obsolete) methods still worked (which I remember you wanting on another PR). The new ways of getting/setting the name are tested elsewhere. If you don't need such tests then I think we're better off just removing them.

File: src/EFCore.Abstractions/IndexAttribute.cs (hunk 2 above)
Comment (AndriySvyryd) [reply src/EFCore.Abstractions/IndexAttribute.cs:13]: As I said the scenario we should support is `IndexAttribute` on an unmapped base type

File: test/EFCore.Relational.Tests/Metadata/RelationalMetadataBuilderExtensionsTest.cs (hunk 19 above)
Comment (AndriySvyryd) [reply test/EFCore.Relational.Tests/Metadata/RelationalMetadataBuilderExtensionsTest.cs:150]: Ok, you can keep them

**Comment by AndriySvyryd** [comment]
After this is checked in consider allowing multiple indexes on the same properties (part of #4150) as that would break the new API introduced in this PR if done after 5.0

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 5 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: OK. It seems to me that what you're saying is:

- On a CLR class a `member` is defined (by the CLR spec) to mean a field, or a property (which is _not_ a field), or an event or ...
- On an Entity Type _we have defined_ `member` to mean a property, a service property, a navigation or a skip navigation. And _we have defined_ `property` such that it means "a public field on the CLR type on which the entity is based", or "a CLR property on the CLR type...", or a shadow property or a "CLR property with a backing CLR field" - which we call `IProperty`.

Is that correct?

Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: yes

Comment (roji) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: That's pretty close to how I understand it. The key is that the (conceptual?) model is separate from CLR types and uses different terminology. That's why a model property may not correspond to any CLR member (shadow), for example.

Comment (smitpatel) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: C-Space, O-Space & S-Space.

Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:768]: OK. My understanding previously was that Property was just called Property for historical reasons - because some time, way back, we didn't originally allow fields. But I will adopt this way of thinking.

File: src/EFCore.Abstractions/IndexAttribute.cs (hunk 10 above)
Comment (lajones) [reply src/EFCore.Abstractions/IndexAttribute.cs:40]: `bool?` not allowed as attribute named parameter. Adding a method `GetIsUnique()` instead.

File: src/EFCore/Metadata/Conventions/IndexEntityTypeAttributeConvention.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexEntityTypeAttributeConvention.cs]: I moved the check of no white-space into the attribute as requested - however please note I could throw a much more helpful error message if I did this in the convention.

The other two have been moved to `IndexAttributeConvention`. They are both errors - I'd like to discuss the level of these as I believe that the most likely scenario for both "mapped to ignored property" and "mapped to non-existent property" is the user had a typo, or referenced an ignored property by mistake. Note: if they absolutely have to do either of those things then they can override the log message to be at a different level.

File: src/EFCore.Abstractions/IndexAttribute.cs (hunk 2 above)
Comment (lajones) [reply src/EFCore.Abstractions/IndexAttribute.cs:15]: We allow inheritance of the attribute and there is now a test for this.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 15 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs]: The "index property mapped to multiple tables" error has gone away. We now check for "at least one table to which all properties can map". If you'd like an `info` or `verbose` message to say "the index properties map to more than 1 table" then that would be easy to add back in.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 16 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs]: This scenario now has a test produced no error. Note, the similar TPT scenario where A { Id, Other }, B : A { Name} with index on { Other, Name } does still error as there is no single table containing both Other and Name.

File: src/EFCore/Diagnostics/CoreLoggerExtensions.cs [hunk 20]
```diff
@@ -2996,5 +2996,106 @@ private static string ConflictingKeylessAndKeyAttributesWarning(EventDefinitionB
...
+            var d = (EventDefinition<string, string, string, string>)definition;
+            var p = (IndexInvalidPropertyEventData)payload;
+            return d.GenerateMessage(
+                p.Name,
+                p.EntityType.DisplayName(),
+                p.PropertyNames.Format(),
+                p.InvalidPropertyName);
+        }
+
+        private static string Format(string[] names)
```
Comment (lajones) [inline src/EFCore/Diagnostics/CoreLoggerExtensions.cs:3098]: I missed this - I'll remove it since no longer used.

File: src/EFCore/Extensions/TupleExtensions.cs [hunk 21]
```diff
@@ -0,0 +1,36 @@
...
+    /// </summary>
+    public static class TupleExtensions
+    {
+        /// <summary>
+        ///     Creates a formatted string representation of the given tables such as is useful
+        ///     when throwing exceptions.
+        /// </summary>
+        /// <param name="tables"> The (Table, Schema) tuples to format. </param>
+        /// <returns> The string representation. </returns>
+        public static string FormatTables([NotNull] this IEnumerable<(string Table, string Schema)> tables)
```
Comment (smitpatel) [inline src/EFCore/Extensions/TupleExtensions.cs:22]: This should not be core level, Table/Schema is relational concept. Also make this public internal unless used outside relational.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 15 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs]: We now log info message if all of the properties constituting the index do not map to anything and log an error if some of them map and some don't. Error for "mapped to non-overlapping tables" is still there too.

File: src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs [hunk 22]
```diff
@@ -128,5 +129,11 @@ public class CSharpModelGenerator : ModelCodeGenerator
 
             return resultingFiles;
         }
+
+        /// <summary>
+        /// The set of annotations ignored for the purposes of code generation for indexes.
+        /// </summary>
+        public static IEnumerable<string> IgnoredIndexAnnotations
```
Comment (AndriySvyryd) [inline src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs:136]: Make this an `IReadOnlyList<string>`

File: src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs [hunk 23]
```diff
@@ -777,10 +789,8 @@ protected virtual void GenerateKeyAnnotations([NotNull] IKey key, [NotNull] Inde
 
             IgnoreAnnotations(
                 annotations,
-                RelationalAnnotationNames.TableIndexMappings);
+                CSharpModelGenerator.IgnoredIndexAnnotations.ToArray());
```
Comment (AndriySvyryd) [inline src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs:792]: Add an overload of `IgnoredIndexAnnotations` that takes an `IReadOnlyList<string>`

Comment (lajones) [reply src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs:792]: Did you mean an overload of `IgnoreAnnotations`?

File: src/EFCore.Relational/Extensions/Internal/TupleExtensions.cs [hunk 24]
```diff
@@ -0,0 +1,38 @@
...
+using System.Linq;
+using JetBrains.Annotations;
+
+// ReSharper disable once CheckNamespace
+namespace Microsoft.EntityFrameworkCore.Internal
+{
+    /// <summary>
+    ///     Extension methods for tuples.
+    /// </summary>
+    public static class TupleExtensions
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Extensions/Internal/TupleExtensions.cs:14]: Add the pubternal doc comment on every member

File: src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs (hunk 23 above)
Comment (AndriySvyryd) [reply src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs:792]: Yes 😃

File: src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs [hunk 25]
```diff
@@ -38,8 +46,7 @@ public static string GetName([NotNull] this IIndex index)
             [NotNull] this IIndex index,
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs:46]: Rename this to `GetDatabaseName`

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs [hunk 26]
```diff
@@ -911,5 +913,114 @@ private void ValidateTPHMapping(IEntityType rootEntityType, bool forTables)
...
+                foreach (var index in entityType.GetIndexes()
+                    .Where(i => ConfigurationSource.Convention != ((IConventionIndex)i).GetConfigurationSource()))
+                {
+                    IProperty propertyNotMappedToAnyTable = null;
+                    Tuple<string, List<(string Table, string Schema)>> firstPropertyTables = null;
+                    Tuple<string, List<(string Table, string Schema)>> lastPropertyTables = null;
+                    HashSet<(string Table, string Schema)> overlappingTables = null;
+                    foreach (var property in index.Properties)
+                    {
+                        var tablesMappedToProperty = property.DeclaringEntityType.GetDerivedTypesInclusive()
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:939]:
```suggestion
                        var tablesMappedToProperty = entityType.GetDerivedTypesInclusive()
```

We should only look at the entity types where the index is present.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs [hunk 27]
```diff
@@ -911,5 +913,114 @@ private void ValidateTPHMapping(IEntityType rootEntityType, bool forTables)
...
+        /// <param name="model"> The model to validate. </param>
+        /// <param name="logger"> The logger to use. </param>
+        protected virtual void ValidateIndexProperties(
+            [NotNull] IModel model, [NotNull] IDiagnosticsLogger<DbLoggerCategory.Model.Validation> logger)
+        {
+            Check.NotNull(model, nameof(model));
+
+            foreach (var entityType in model.GetEntityTypes())
+            {
+                foreach (var index in entityType.GetIndexes()
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:930]:
```suggestion
                foreach (var index in entityType.GetDeclaredIndexes()
```

No need to check inherited indexes again

File: src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs (hunk 25 above)
Comment (lajones) [reply src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs:46]: Let me do this as a separate PR. It isn't central to what I'm doing, and I found the last change to `GetDabaseName()` added a lot of files to the PR and made merging more difficult.

File: src/EFCore.Relational/Properties/RelationalStrings.resx [hunk 28]
```diff
@@ -606,4 +606,16 @@
   <data name="PropertyNotMappedToTable" xml:space="preserve">
     <value>The property '{property}' on entity type '{entityType}' is not mapped to the table '{table}'.</value>
   </data>
+  <data name="LogAllIndexPropertiesNotToMappedToAnyTable" xml:space="preserve">
+    <value>The index named '{indexName}' on the entity type '{entityType}' specifies properties {indexPropertiesList}. None of these properties are mapped to a column in any table. This index will not be created in the database.</value>
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Properties/RelationalStrings.resx:610]: `indexName` might be null, this will look ugly. Instead use `indexSpecification` that will be `indexName: {indexProperties}` if indexName is not null or just `{indexProperties}`

File: src/EFCore.Relational/Properties/RelationalStrings.resx [hunk 29]
```diff
@@ -606,4 +606,16 @@
...
+    <comment>Information RelationalEventId.AllIndexPropertiesNotToMappedToAnyTable string string string</comment>
+  </data>
+  <data name="LogIndexPropertiesBothMappedAndNotMappedToTable" xml:space="preserve">
+    <value>The index named '{indexName}' on the entity type '{entityType}' specifies properties {indexPropertiesList}. Some properties are mapped to a column in a table, but the property '{propertyName}' is not. Either all or none of the properties should be mapped.</value>
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Properties/RelationalStrings.resx:614]:
```suggestion
    <value>The index named '{indexName}' on the entity type '{entityType}' specifies properties {indexPropertiesList}. Some properties are mapped to a column in a table, but the property '{propertyName}' is not. All of the properties should be mapped for the index to be created in the database.</value>
```

File: src/EFCore.Relational/Properties/RelationalStrings.resx (hunk 28 above)
Comment (lajones) [reply src/EFCore.Relational/Properties/RelationalStrings.resx:610]: @roji - please chime in - this was designed this way because of your previous comments about needing the name.

I thought about this a lot. `indexSpecification` doesn't work. It is possible for 2 indexes with different property lists to have the same name - so we always need to include the propertyList - it is the unique identifier of the index. Also when you refer to `indexName` you really want to say "the index named `indexName`", when you use `indexProperties` you really want to say "specifies properties `indexProperties`" or "specified by properties `indexProperties`".

I studied the output messages a lot. Normally I would agree with you but in this case and I was fine with the name being blank or null when the user had not set `index.Name` - I even thought it was better that way. However if we want to avoid that then one other approach is to have 2 log messages for each of the events. One which looks like the above and one which looks like:

```
The unnamed index on the entity type '{entityType}' specifies properties {indexPropertiesList}... 
```

I'd be fine doing that too.

File: src/EFCore/Extensions/PropertyExtensions.cs [hunk 30]
```diff
@@ -400,6 +400,19 @@ public static string Format([NotNull] this IEnumerable<IPropertyBase> properties
                         p => "'" + p.Name + "'" + (includeTypes ? " : " + p.ClrType.DisplayName(fullName: false) : "")))
                 + "}";
 
+        /// <summary>
+        ///     Creates a formatted string representation of the given
+        ///     property names such as is useful when throwing exceptions.
+        /// </summary>
+        /// <param name="propertyNames"> The names of the properties to format. </param>
+        /// <returns> The string representation. </returns>
+        public static string Format([NotNull] this IEnumerable<string> propertyNames)
```
Comment (AndriySvyryd) [inline src/EFCore/Extensions/PropertyExtensions.cs:409]: This is too broad, better to keep as private or real internal

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 26 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:939]: Either this or the comment below about `GetDeclaredIndexes()` causes the test Detects_index_properties_mapped_to_different_tables_in_TPT_hierarchy to fail. I'll have to look into this.

File: src/EFCore.Relational/Properties/RelationalStrings.resx (hunk 28 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Properties/RelationalStrings.resx:610]: I'm fine with having two messages for each event

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs [hunk 31]
```diff
@@ -0,0 +1,90 @@
...
+
+                            indexProperties.Add(property);
+                        }
+
+                        var indexBuilder = entityType.Builder.HasIndex(indexProperties, fromDataAnnotation: true);
+                        if (indexBuilder != null)
+                        {
+                            if (indexAttribute.Name != null)
+                            {
+                                indexBuilder.HasName(indexAttribute.Name, fromDataAnnotation: true);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:77]:
```suggestion
                                indexBuilder = indexBuilder.HasName(indexAttribute.Name, fromDataAnnotation: true);
```

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs [hunk 32]
```diff
@@ -0,0 +1,90 @@
...
+                            }
+
+                            if (indexAttribute.GetIsUnique().HasValue)
+                            {
+                                indexBuilder.IsUnique(indexAttribute.GetIsUnique().Value, fromDataAnnotation: true);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:82]:
```suggestion
                                indexBuilder?.IsUnique(indexAttribute.GetIsUnique().Value, fromDataAnnotation: true);
```

File: src/EFCore/Extensions/PropertyExtensions.cs (hunk 30 above)
Comment (lajones) [reply src/EFCore/Extensions/PropertyExtensions.cs:409]: `private` causes me to have to replicate this everywhere - which is what I was trying to avoid. Even real internal causes this method to not be reachable in Relational. How about a separate pubternal class?

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs (hunk 32 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:82]: Is this just a style thing? I.e. are you suggesting getting rid of the `if (indexBuilder != null)` and using `indexBuilder?` throughout instead?

File: src/EFCore.Relational/Properties/RelationalStrings.resx (hunk 28 above)
Comment (roji) [reply src/EFCore.Relational/Properties/RelationalStrings.resx:610]: I agree with @AndriySvyryd.. Basically, if the indexName is provided, it should appear in the message - and if not, it shouldn't (otherwise there's a weird blank). If the indexName isn't provided, then the properties are necessary in order to identify it. If both are provided, I would lean towards omitting the properties, but I think it's fine to include both (it doesn't hurt).

Comment (lajones) [reply src/EFCore.Relational/Properties/RelationalStrings.resx:610]: @roji - is this is OK with you too?

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 26 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:939]: I see. You can leave it as is then.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 27 above)
Comment (lajones) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:930]: This works - must be the comment above that causes the test Detects_index_properties_mapped_to_different_tables_in_TPT_hierarchy to fail.

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs (hunk 26 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:939]: We'll need to do something different here for TPC, but we'll see when we get there.

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs (hunk 31 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:77]: Looked at this a bit more. I'd like to not do that. If for any reason `HasName()` returns `null` (say because the name has been overridden by fluent API), that is not a good reason to not set `IsUnique()` next.

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs (hunk 32 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:82]: Would like to leave this as is - see previous comment.

File: src/EFCore/Extensions/PropertyExtensions.cs (hunk 30 above)
Comment (AndriySvyryd) [reply src/EFCore/Extensions/PropertyExtensions.cs:409]: real internal classes can be placed in Shared to make them accessible to all projects

File: src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs (hunk 25 above)
Comment (lajones) [reply src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs:46]: Raised #21072 to track this.

**Comment by lajones** [comment]
> After this is checked in consider allowing multiple indexes on the same properties (part of #4150) as that would break the new API introduced in this PR if done after 5.0

I've set #4150 to be reconsidered at the next triage meeting.
