### PR TITLE
Fix to #22049 - Query: consider updating select expression identifiers when projecting a subset of column and adding distinct

### LINKED ISSUE #22049: Query: consider updating select expression identifiers when projecting a subset of column and adding distinct
Currently we use keys of all entities in chain as identifiers for the select expression. This becomes a problem when applying distinct - if the keys are not part of the projection we can no longer identify it. However in case of distinct we could change identifiers to become all of the projected (at least in some cases). need to investigate whether its correct thing to do for complex scenarios (nav chains?) and what is perf impact

### LINKED ISSUE #24288: Query: add collection join tries to convert correlated collection from APPLY to JOIN for subqueries with Distinct and GroupBy, which is incorrect
When correlated collection is converted to JOIN, the join predicate element is added to the projection of the subquery. However, this can't be done in case of groupby (can end up adding property that is not part of the grouping key) and distinct (changes the result of distinct operation).

We should only be converting to JOIN if the join predicate is already part of the grouping/projection, otherwise keep as APPLY.

### PR DESCRIPTION
**Pull request by maumar**
As fix to #15873 we started blocking some scenarios that used to work (by accident) - when we have a subquery using Distinct or GroupBy that doesn't happen to have any duplicates.

Fix is to enable those scenarios (and others) by modifying identifier columns in case of distinct and group by, if the original identifiers are not already present. In case of distinct, the entire projection becomes unique identifier, as distinct guarantees it to be unique.
In case of groupby, the grouping key becomes the identifier - since we only support grouping key or group aggregate in the projection, we are also guaranteed to have 1 row per unique grouping key.

Also fix to #24288 - Query: add collection join tries to convert correlated collection from APPLY to JOIN for subqueries with Distinct and GroupBy, which is incorrect

we would always try to convert subquery with groupby and distinct from apply to join, however we can only do this if the projection already contains the join key. Otherwise, adding the join key to the projection would change the meaning of operation in case of distinct and create invalid query in case of group by (projecting column that is not part of grouping key or aggregate).

Fixes #22049
Fixes #24288

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -1119,6 +1119,20 @@ private ColumnExpression GenerateOuterColumn(SqlExpression projection, string? a
                     // if we can't propagate any identifier - clear them all instead
                     // when adding collection join we detect this and throw appropriate exception
                     _identifier.Clear();
+
+                    if (IsDistinct
+                        && projectionMap.Select(p => p.Value).All(x => x is ColumnExpression))
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1124]: is it ever possible for projection map to be something else than columns (in the pushdown scenario?)

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 2]
```diff
@@ -1635,24 +1649,70 @@ static Expression RemoveConvert(Expression expression)
...
-                    || selectExpression.GroupBy.Count > 0)
+                if (innerSelectExpression.IsDistinct
+                    || innerSelectExpression.GroupBy.Count > 0)
                 {
-                    var innerSelectProjectionExpressions = selectExpression._projection.Select(p => p.Expression).ToList();
-                    foreach (var innerSelectIdentifier in selectExpression._identifier)
+                    var (identifiersInProjection, missingIdentifier) = IdentifiersInProjection(innerSelectExpression);
+
+                    if (!identifiersInProjection
+                        // TODO: nre hack
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1660]: if identifiersInProjection is false then missingIdentifier is never null - is there a way to bind those 2 values together nrt-wise?

File: test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs [hunk 3]
```diff
@@ -21,39 +21,73 @@ protected GearsOfWarQueryRelationalTestBase(TFixture fixture)
...
+
+
+
+
+
+
+
+
+
+        //[ConditionalTheory]
```
Comment (maumar) [inline test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs:56]: will double check if we still need these

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1124]: entity projection?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 4]
```diff
@@ -1635,24 +1649,70 @@ static Expression RemoveConvert(Expression expression)
...
+                                throw new InvalidOperationException(
+                                    RelationalStrings.UnableToTranslateSubqueryWithGroupBy(
+                                        missingIdentifier.Table.Alias + "." + missingIdentifier.Name));
+                            }
                         }
                     }
                 }
             }
+
+            static (bool result, ColumnExpression? missingIdentifier) IdentifiersInProjection(SelectExpression selectExpression)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1701]: Make missingIdentifier out ColumnExpression? and put [CA.NotNullWhen(true)] on it.

**Comment by Emill** [comment]
Some test cases in terms of GearsOfWar below that covers the case when applying distinct after adding a collection. I think they should all fail with some reasonable error message to the user, since this kind of expressions can't generally be expressed with standard SQL and joins. Currently the PR does not cover the last two correctly (generates a SQL query that does not give the correct results), and gives an inappropriate error message in my opinion for the first ("not projecting all key columns for distinct/group by...").

```C#
ss.Set<Gear>().Select(g => g.Weapons).Distinct()

ss.Set<Gear>().Select(g => new { g.LeaderNickname, g.Weapons }).Distinct()

ss.Set<Gear>().Select(g => new { g.LeaderNickname, Weapons = g.Weapons.Where(w => w.Id > g.SquadId) }).Distinct()
```

SQL query for the second one:

```SQL
SELECT [t].[LeaderNickname], [w].[Id], [w].[AmmunitionType], [w].[IsAutomatic], [w].[Name], [w].[OwnerFullName], [w].[SynergyWithId]
FROM (
    SELECT DISTINCT [g].[LeaderNickname], [g].[FullName]
    FROM [Gears] AS [g]
) AS [t]
LEFT JOIN [Weapons] AS [w] ON [t].[FullName] = [w].[OwnerFullName]
ORDER BY [t].[LeaderNickname], [w].[Id]
```

As you can see, the columns used in the join predicate are added to the distinct column list (FullName acts as key), which will not lead to the correct results. For example, if the Weapons table is empty but the Gears table is not, the result will contain too many rows.

**Comment by maumar** [comment]
leaning towards blocking every scenario that projects collection followed by distinct. Basically during queryable method translation, in TranslateDistinct check for collection shapers inside ShaperExpression and throw accordingly. @smitpatel thoughts?

**Comment by smitpatel** [comment]
Do whatever is most beneficial to customers according to you.

**Comment by maumar** [comment]
updated

File: src/EFCore.Relational/Properties/RelationalStrings.resx [hunk 5]
```diff
@@ -621,8 +621,14 @@
   <data name="MissingConcurrencyColumn" xml:space="preserve">
     <value>Entity type '{entityType}' doesn't contain a property mapped to the store-generated concurrency token column '{missingColumn}' which is used by another entity type sharing the table '{table}'. Add a store-generated property to '{entityType}' which is mapped to the same column; it may be in shadow state.</value>
   </data>
-  <data name="MissingIdentifyingProjectionInDistinctGroupBySubquery" xml:space="preserve">
-    <value>Unable to translate a collection subquery in a projection since it uses 'Distinct' or 'Group By' operations and doesn't project key columns of all tables required to generate results on the client side. Missing column: {column}. Either add column(s) to the projection or rewrite the query to not use the 'GroupBy'/'Distinct' operation.</value>
+  <data name="UnableToTranslateSubqueryWithDistinct" xml:space="preserve">
```
Comment (smitpatel) [inline src/EFCore.Relational/Properties/RelationalStrings.resx:624]: @dotnet/efteam for "Exception message review"

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 6]
```diff
@@ -387,11 +387,33 @@ private static ShapedQueryExpression CreateShapedQueryExpression(IEntityType ent
         {
             Check.NotNull(source, nameof(source));
 
+            var collectionShaperExpressionFinder = new CollectionShaperExpressionFinder();
+            collectionShaperExpressionFinder.Visit(source.ShaperExpression);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:391]: Does checking for _pendingCollection count inside SelectExpression directly work?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 7]
```diff
@@ -1635,24 +1649,72 @@ static Expression RemoveConvert(Expression expression)
...
-                        if (!innerSelectProjectionExpressions.Contains(innerSelectIdentifier.Column)
-                            && (selectExpression.GroupBy.Count == 0
-                                || !selectExpression.GroupBy.Contains(innerSelectIdentifier.Column)))
+                        if (innerSelectExpression.IsDistinct)
                         {
-                            throw new InvalidOperationException(RelationalStrings.MissingIdentifyingProjectionInDistinctGroupBySubquery(
-                                innerSelectIdentifier.Column.Table.Alias + "." + innerSelectIdentifier.Column.Name));
+                            if (innerSelectExpression._projection.All(p => p.Expression is ColumnExpression))
+                            {
+                                innerSelectExpression._identifier.Clear();
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1663]: This could be somewhat faulty since _identifier can contain childIdentifier if there are multiple nested collections. Unless that scenario is blocked by earlier distinct on collection check.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 8]
```diff
@@ -1709,12 +1771,54 @@ private static SqlExpression MakeNullable(SqlExpression sqlExpression)
...
+                }
+
                 selectExpression.Predicate = predicate;
 
                 return joinPredicate;
             }
 
             return null;
+
+            static List<ColumnExpression> InnerKeyColumns(IEnumerable<TableExpressionBase> tables, SqlExpression joinPredicate)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1805]: too many list allocations in this method. Instead pass a list from outside and populate that list instead.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 9]
```diff
@@ -1709,12 +1771,54 @@ private static SqlExpression MakeNullable(SqlExpression sqlExpression)
...
+                    // we are guaranteed that the join key will be in the projection
+                    // even if currently the projection is not populated
+                    if (selectExpression.Tables.Count != 1
+                        || selectExpression._projectionMapping.Count != 1
+                        || selectExpression._projectionMapping.First().Value is not EntityProjectionExpression)
+                    {
+                        var innerKeyColumns = InnerKeyColumns(selectExpression.Tables, joinPredicate);
+                        foreach (var innerColumn in innerKeyColumns)
+                        {
+                            if (!selectExpression.Projection.Select(p => p.Expression).Contains(innerColumn))
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1790]: Save the result of Projection.Select outside.
Projection would only be populated if client eval or _projectionMapping is applied.

File: test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs [hunk 10]
```diff
@@ -140,6 +126,103 @@ public virtual async Task Project_discriminator_columns(bool async)
                 elementSorter: e => e.Name);
         }
 
+        [ConditionalTheory]
+        [MemberData(nameof(IsAsyncData))]
+        public virtual async Task Projecting_correlated_collection_followed_by_Distinct(bool async)
+        {
+            var message = (await Assert.ThrowsAsync<NotSupportedException>(
```
Comment (smitpatel) [inline test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs:133]: move test to base and let providers decide exception or results?

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs (hunk 6 above)
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:391]: i will test

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 7 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1663]: i will add tests with 3 levels of navs - collections should be blocked but will double check.

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs (hunk 6 above)
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:391]: @smitpatel that could work, but pendingCollection is not available in this context (private field on SelectExpression). I could expose it, but I don't think its worth for such a niche case

Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:391]: This is throwing an exception, just move the check inside ApplyDistinct function call. Also change exception message type to InvalidOperationException.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 7 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1663]: i've added a bunch of tests and so far i can't create a scenario where _childIdentifier would be non-empty at this point (when there is Distinct in the query). We have a number of tests where the _childIdentifier contains some elements (mostly include queries but also some normal correlated collection scenarios), but every time I try to add distinct to it, _childIdentifiers are gone, and are only added further down in the ApplyCollectionJoin method. Can you think of a scenario with GroupBy/Distinct where _childIdentifers would have something?

Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1663]: - GroupBy currently have aggregate only so there won't be nested collection.
- If I understand correctly about check of Distinct above then we may be throwing when Distinct is there and there is also nested collection.

Just add a note here which summarizes above so we know for future if we change above things.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 11]
```diff
@@ -349,33 +349,44 @@ public void ApplyProjection()
                 return;
             }
 
+            _projectionMapping = ApplyProjectionInternal(_projectionMapping, Alias, _projection);
+        }
+
+        private static Dictionary<ProjectionMember, Expression> ApplyProjectionInternal(
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:355]: DRY'd it - not the prettiest, but we won't forget to change the other place if/when add to projection gets updated in the future

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 9 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1817]: This is still pending. Avoid computing part of before Contains inside a loop.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 12]
```diff
@@ -1709,12 +1798,63 @@ private static SqlExpression MakeNullable(SqlExpression sqlExpression)
...
+                            if (!selectExpression.Projection.Select(p => p.Expression).Contains(innerColumn))
+                            {
+                                return null;
+                            }
+                        }
+                    }
+                    else
+                    {
+                        var projection = new List<ProjectionExpression>();
+                        ApplyProjectionInternal(selectExpression._projectionMapping, selectExpression.Alias, projection);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1826]: just traverse the _projectionMapping to collect columns from entity projection. You don't need any processing of add to real projection.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 9 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs]: combined both cases

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 13]
```diff
@@ -1709,12 +1782,78 @@ private static SqlExpression MakeNullable(SqlExpression sqlExpression)
...
+                {
+                    if (mappingElement.Value is EntityProjectionExpression entityProjection)
+                    {
+                        foreach (var property in GetAllPropertiesInHierarchy(entityProjection.EntityType))
+                        {
+                            result.Add(entityProjection.BindProperty(property));
+                        }
+
+                        if (entityProjection.DiscriminatorExpression != null
+                            && entityProjection.DiscriminatorExpression is ColumnExpression discriminatorColumn)
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1844]: can DiscriminatorExpression ever be a column at this point?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 14]
```diff
@@ -1709,12 +1782,78 @@ private static SqlExpression MakeNullable(SqlExpression sqlExpression)
...
+                    || selectExpression.GroupBy.Count > 0))
+                {
+                    var innerKeyColumns = new List<ColumnExpression>();
+                    InnerKeyColumns(selectExpression.Tables, joinPredicate, innerKeyColumns);
+
+                    // if projection has already been applied we can use it directly
+                    // otherwise we extract future projection columns from projection mapping
+                    // and based on that we determine whether we can convert from APPLY to JOIN
+                    var projectionColumns = selectExpression.Projection.Count > 0
+                        ? selectExpression.Projection.Select(p => p.Expression).OfType<ColumnExpression>()
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1798]: Why OfType here?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 13 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1844]: Yes, if the inner was pushed down.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 14 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1798]: We only match projection elements with JOIN predicate elements which are columns. It's more for intent, but not needed - will remove.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1130]: can you put projectionMap.Select(p => p.Value) in a variable outside foreach loop and reuse

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 14 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1798]: Shouldn't we avoid conversion if there are non-column expressions which we don't/can't process below? OfType will filter out and ignore anything else which could be blocking.

**Review by smitpatel — APPROVED** [review]

File: src/EFCore.Relational/Properties/RelationalStrings.resx (hunk 5 above)
Comment (smitpatel) [reply src/EFCore.Relational/Properties/RelationalStrings.resx:624]: Don't forget this part 😉
