### PR TITLE
Fix to #19883 - Query: null semantics should keep track of columns that are guaranteed to be null and remove redundant IS NULL/ IS NOT NULL checks

### LINKED ISSUE #19410: LINQ/SQLITE: Unnecessary IS NULL term generated for linq clause !string.isnullorempty()
Hi,
Using AspnetCore 3.1 with Linq/SQLite, I have a SQL strangely generated for a simple clause.
I have a simple table containing 2 text fields : COUNTRY and ISOCOUNTRY.
I want to get all rows where COUNTRY is not null and not empty:

```c#
VisitorsByCountry = _dataDbContext.Visitors
    .AsNoTracking()
    // Fix for NULL values on ordinal 11
    .Select(v => new { v.Country, v.IsoCountry })
    .Where(v => !string.IsNullOrEmpty(v.Country))
    .AsEnumerable(); // Fix for EF 3.0 not supporting ClientSide GroupBy
```

When I look into the SQL generated for the Where(v => !string.IsNullOrEmpty(v.Country)) :

```sql
SELECT "v"."Country", "v"."IsoCountry"
FROM "Visitors" AS "v"
WHERE "v"."Country" IS NOT NULL AND (("v"."Country" <> '') OR "v"."Country" IS NULL)
```

The Where clause should be like: `WHERE "v"."Country" IS NOT NULL AND "v"."Country" <> ''`

Regards

### LINKED ISSUE #19883: Query: null semantics should keep track of columns that are guaranteed to be null and remove redundant IS NULL/ IS NOT NULL checks
Currently null semantics keeps track of columns that are nullable, but we know that they can't be null, e.g. 

```cs
customers.Select(c => c.Name != null && c.Name.Length == 7)
```

since we performed c.Name != null, we know that c.Name in the right side of && operation can't be null.

We should also do this for columns that are guaranteed to be null:

```
customers.Select(c => c.Name == null && c.Name.Length == 7) //second c.Name must be null
customers.Select(c => c.Name == null || c.Name.Length == 7) // second c.Name can't be null
```

### PR DESCRIPTION
**Pull request by maumar**
Adding a list of columns guaranteed to be null in the given subtree. When processing right side of the || operator, we can convert those to non-nullable columns and therefore improve the generated sql.

Fixes #19883
Fixes #19410

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlNullabilityProcessor.cs [hunk 1]
```diff
@@ -342,13 +345,13 @@ protected virtual SelectExpression Visit(SelectExpression selectExpression)
         /// <returns> An optimized sql expression. </returns>
         [return: NotNullIfNotNull("sqlExpression")]
         protected virtual SqlExpression? Visit(SqlExpression? sqlExpression, bool allowOptimizedExpansion, out bool nullable)
-            => Visit(sqlExpression, allowOptimizedExpansion, preserveNonNullableColumns: false, out nullable);
+            => Visit(sqlExpression, allowOptimizedExpansion, preserveNullabilityColumnInformation: false, out nullable);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlNullabilityProcessor.cs:348]: preserveColumnNullabilityInformation ((or something better))

File: src/EFCore.Relational/Query/SqlNullabilityProcessor.cs [hunk 2]
```diff
@@ -462,6 +469,22 @@ protected virtual SqlExpression VisitCase(CaseExpression caseExpression, bool al
...
+                // if the case expression represents conditional (i.e. test ? ifTrue, ifFalse) after we process first WhenClase (representing ifTrue)
+                // we can invert the null value column info into non-nullable
+                // ifTrue has processed the path where they could be null, so the only thing that is left for else is the path where they are all non-null
+                // a == null || b == null
+                // ? a != c // a could be null here (but not always is)
+                // : b != d // b can never be null here
+                if (whenClauses.Count == 1
+                    && caseExpression.ElseResult != null)
+                {
+                    _nonNullableColumns.AddRange(_nullValueColumns.ToList());
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlNullabilityProcessor.cs:481]: likely not whole list but elements which were added while Visiting Test. so add skip with earlier count.

File: src/EFCore.Relational/Query/SqlNullabilityProcessor.cs [hunk 3]
```diff
@@ -830,16 +853,30 @@ protected virtual SqlExpression VisitLike(LikeExpression likeExpression, bool al
...
                 RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
             }
 
-            var right = Visit(sqlBinaryExpression.Right, allowOptimizedExpansion, preserveNonNullableColumns: true, out var rightNullable);
+            if (sqlBinaryExpression.OperatorType == ExpressionType.OrElse)
+            {
+                // in case of OrElse, we can assume all null value columns on the left side can be treated as non-nullable on the right
+                // e.g. (a == null || b == null) || f(a, b)
+                // f(a, b) will only be executed if a != null and b != null
+                _nonNullableColumns.AddRange(_nullValueColumns);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlNullabilityProcessor.cs:872]: only columns which were added from left

**Comment by maumar** [comment]
@smitpatel  ping

File: src/EFCore.Relational/Query/SqlNullabilityProcessor.cs [hunk 4]
```diff
@@ -476,6 +484,9 @@ protected virtual SqlExpression VisitCase(CaseExpression caseExpression, bool al
                 nullable |= elseResultNullable;
             }
 
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlNullabilityProcessor.cs:487]: good catch

**Review by smitpatel — APPROVED** [review]
