### PR TITLE
Fix savepoint bugs

### LINKED ISSUE #21340: Savepoints should not be be rolled back/released if the connection is closed
Our SQL Server ExecutionStrategyTests are incomplete because TestRelationalTransaction [mistakenly exposes AreSavepointsSupported=false](https://github.com/dotnet/efcore/blob/master/test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalTransaction.cs#L86).

Once this is fixed, tests in ExecutionStrategyTest fail because of `ExecuteNonQuery requires an open and available Connection. The connection's current state is closed.`. This is because [BatchExecutor](https://github.com/dotnet/efcore/blob/14f13ef6dfb0aae7e2faedfb0de604070fc5d101/src/EFCore.Relational/Update/Internal/BatchExecutor.cs#L102) attempts to roll back to the savepoint on exception, but if the ADO connection has been closed because of the exception this triggers an error. The same does not occur for regular transaction rollback, because disposing the transaction always completes without an exception, even if the connection is closed.

Options for dealing with this:

* Check if the ADO connection is still open before attempting to roll back to the savepoint (or release it). Note that the RelationalConnection is unaware that its ADO connection is closed; should we detect this situation and propagate the closing to the RelationalConnection?
* Swallow any exceptions coming out of the rollback/release. This uses exceptions for flow control which isn't ideal.

As an aside, I'm wondering if we should look into a better API for System.Data (https://github.com/dotnet/runtime/issues/33397). A CreateSavepoint API could return a disposable, providing similar semantics to transaction itself. Specifically, disposing it would automatically rollback and never produce an exception (at the price of an extra allocation for the disposable). EF Core would still have to support older providers so this is a bit orthogonal.

PS We should also consider promoting ExecutionStrategyTest to a derivable test suite rather than making it a SQL Server only thing.

### PR DESCRIPTION
**Pull request by roji**
* Check that DbConnection is Open before attempting to rollback and/or release a savepoint, and swallow any exceptions that bubble up from those operations.
    * Swallowed exceptions are logged, currently with Debug level - the idea is that the main exception is going to typically explain why any savepoint operation failed anyway, so users shouldn't be too interested in this. Open to changing this though.
* Call close on IRelationalConnection after releasing savepoint to make sure open/close are balanced.

Closes #21340

### CODE REVIEW

File: src/EFCore.Relational/Update/Internal/BatchExecutor.cs [hunk 1]
```diff
@@ -172,25 +201,43 @@ public BatchExecutor([NotNull] ICurrentDbContext currentContext)
...
-                    await transaction.ReleaseSavepointAsync(SavepointName, cancellationToken).ConfigureAwait(false);
-                }
-                else if (beganTransaction)
+                if (beganTransaction)
                 {
                     await transaction.DisposeAsync().ConfigureAwait(false);
                 }
                 else
                 {
+                    if (createdSavepoint)
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Update/Internal/BatchExecutor.cs:226]: Flatten
