### PR TITLE
Stop throwing eagerly when looking up a ValueGenerator

### LINKED ISSUE #32892: System.NotSupportedException: The property 'X.Y' does not have a value set and no value generator is available for properties of type 'bool'.
Hello, 

Please forgive me for copy paste. At the begining I've [reported it in EFCorePowerTools](https://github.com/ErikEJ/EFCorePowerTools/issues/2121). but it seems like this bug could be in Entity Framework Core.

I came across this exception today.

System.NotSupportedException: The property 'Join.PrimaryGroup' does not have a value set and no value generator is available for properties of type 'bool'. Either set a value for the property before adding the entity or configure a value generator for properties of type 'bool' in 'OnModelCreating'.

### Technical details

- EF Core Power Tools version: 2.6.72

- Exact Visual Studio version: Microsoft Visual Studio Professional 2022 (64-bit) - 17.8.5

- Database engine: SQL Server 2019

- EF Core version in use: 
Microsoft.EntityFrameworkCore.SqlServer 8.0.1
Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite 8.0.1

### Steps to reproduce a bug

**Create two tables:**
```sql
CREATE SCHEMA Testing;
GO

CREATE TABLE [Testing].[List](
	[Id] [uniqueidentifier] NOT NULL,
	[Description] [nvarchar](max) NULL,
 CONSTRAINT [PK_TestingList] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [Testing].[List] ADD  DEFAULT (newsequentialid()) FOR [Id]
GO

ALTER TABLE [Testing].[List]  WITH CHECK ADD  CONSTRAINT [CK_ID] CHECK  (([Id]<>'00000000-0000-0000-0000-000000000000'))
GO

ALTER TABLE [Testing].[List] CHECK CONSTRAINT [CK_ID]
GO


CREATE TABLE [Testing].[Joins](
	[TargetId] [uniqueidentifier] NOT NULL,
	[SourceId] [uniqueidentifier] NOT NULL,
	[PrimaryGroup] [bit] NOT NULL,
 CONSTRAINT [PK_Way] PRIMARY KEY CLUSTERED 
(
	[TargetId] ASC,
	[SourceId] ASC,
	[PrimaryGroup] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Testing].[Joins] ADD  DEFAULT ((1)) FOR [PrimaryGroup]
GO
```

**Add some data to table List e.g.**
```
Id	Description
18C2810D-58B9-EE11-B82E-000C296039A5	Test1
19C2810D-58B9-EE11-B82E-000C296039A5	Test2
1AC2810D-58B9-EE11-B82E-000C296039A5	Test3
1BC2810D-58B9-EE11-B82E-000C296039A5	Test4
5B72CC13-58B9-EE11-B82E-000C296039A5	Test5
```
**Scaffold db by Reverse Enginering in Powertools**
efpt.config.json config:
```json
{
   "CodeGenerationMode": 4,
   "ContextClassName": "TestContext",
   "ContextNamespace": null,
   "DefaultDacpacSchema": null,
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": null,
   "OutputContextPath": null,
   "OutputPath": "Models",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "DB",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 2,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": null,
   "Tables": [
      {
         "Name": "[Testing].[Joins]",
         "ObjectType": 0
      },
      {
         "Name": "[Testing].[List]",
         "ObjectType": 0
      }
   ],
   "UiHint": "win-sql\\mssqlserver2019.Test.dbo",
   "UncountableWords": null,
   "UseBoolPropertiesWithoutDefaultSql": true,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": false,
   "UseDbContextSplitting": false,
   "UseDecimalDataAnnotationForSprocResult": true,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": true,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": true,
   "UseNoDefaultConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UseSchemaFolders": true,
   "UseSchemaNamespaces": false,
   "UseSpatial": true,
   "UseT4": false
}
```
**Should get classes:**
```C#
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DB.Models;

public partial class TestContext : DbContext
{
    public TestContext(DbContextOptions<TestContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Join> Joins { get; set; }

    public virtual DbSet<List> Lists { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Join>(entity =>
        {
            entity.HasKey(e => new { e.TargetId, e.SourceId, e.PrimaryGroup }).HasName("PK_Way");

            entity.ToTable("Joins", "Testing");

            entity.Property(e => e.PrimaryGroup).HasDefaultValue(true);
        });

        modelBuilder.Entity<List>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_TestingList");

            entity.ToTable("List", "Testing");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.Models;

public partial class List
{
    public Guid Id { get; set; }

    public string Description { get; set; }
}

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB.Models;

public partial class Join
{
    public Guid TargetId { get; set; }

    public Guid SourceId { get; set; }

    public bool PrimaryGroup { get; set; }
}
```
**Create simple C# console app:**
```C#
using DB.Models;
using Microsoft.EntityFrameworkCore;

try
{
    var connectionString = "your connection string here";
    var optionsBuilder = new DbContextOptionsBuilder<TestContext>();
    optionsBuilder.UseSqlServer(connectionString);
    using var db = new TestContext(optionsBuilder.Options);

    var list = db.Lists.ToList();
    foreach (var listItem in list)
        Console.WriteLine($"{listItem.Id} : {listItem.Description}");

    var join = new Join { SourceId = list[0].Id, TargetId = list[1].Id, PrimaryGroup = true };
    db.Joins.Add(join);

    db.SaveChanges();
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}
```

SaveChanges throws exception mentioned at top of this post.

Meaby bool/bit column in primary key can be guilty and should be handled differently?

Best regards Marcin

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #32892

The issue was introduced by the fix for stable/unstable values. In that fix, we were missing that a value generator exists and influences whether the generated value is considered stable or not. However, some types, most notably bools, don't have a default generator. This is fine, it just means that there isn't a generator to use.

I removed the exception entirely because we never now throw if we can't find a generator--it's always okay. This is technically a breaking change, and people do create their own selectors, so we should probably doc it.

### CODE REVIEW

**Comment by SamMonoRT** [comment]
The #32892 has been marked as a Servicing Consider 8.0.x label. The description above indicates this is a breaking change.
Question - Do we really want to backport this?

**Comment by AndriySvyryd** [comment]
I think we should still throw this for non-composite keys, as it would be a more useful exception than a "key not set"

**Comment by ajcvickers** [comment]
@AndriySvyryd @SamMonoRT New version up that retains the behavior of throwing for non-composite keys. Also changed the break into an obsolete.

We can't port this directly to release/8.0, but if this is the correct fix going forward, then I'll look at the port next.

File: src/EFCore/ValueGeneration/IValueGeneratorSelector.cs [hunk 1]
```diff
@@ -35,5 +35,34 @@ public interface IValueGeneratorSelector
...
+    /// </summary>
+    /// <param name="property">The property to get the value generator for.</param>
+    /// <param name="typeBase">
+    ///     The entity type that the value generator will be used for. When called on inherited properties on derived entity types,
+    ///     this entity type may be different from the declared entity type on <paramref name="property" />
+    /// </param>
+    /// <param name="valueGenerator">The value generator, or <see langword="null"/> if none is available.</param>
+    /// <returns><see langword="true"/> if a value generator was selected; <see langword="false"/> if none was available.</returns>
+    bool TrySelect(IProperty property, ITypeBase typeBase, out ValueGenerator? valueGenerator)
+    {
```
Comment (AndriySvyryd) [inline src/EFCore/ValueGeneration/IValueGeneratorSelector.cs:52]: I don't see value in having this implementation in main. All providers should reimplement it anyway when they upgrade.
