### PR TITLE
Fix for 19670. ForeignKeyAttributeConvention run when new Navigation is added.

### LINKED ISSUE #19670: ForeignKeyAttributeConvention should also run when a navigation is added

### PR DESCRIPTION
**Pull request by lajones**
Fixes #19670 

Update `ForeignKeyAttributeConvention` to also run when a new navigation is added.

### CODE REVIEW

File: src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs [hunk 1]
```diff
@@ -50,6 +50,39 @@ public ForeignKeyAttributeConvention([NotNull] ProviderConventionSetBuilderDepen
...
+            {
+                var newNavigationBuilder = onDependent
+                    ? newRelationshipBuilder.Metadata.DependentToPrincipal.Builder
+                    : newRelationshipBuilder.Metadata.PrincipalToDependent.Builder;
+                context.StopProcessingIfChanged(newNavigationBuilder);
+            }
+        }
+
+        private IConventionForeignKeyBuilder UpdateRelationshipBuilder<TBuilder>(
+            IConventionForeignKeyBuilder relationshipBuilder, IConventionContext<TBuilder> context)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs:83]: You can use a non-generic `IConventionContext` here

Comment (lajones) [reply src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs]: Done
