### PR TITLE
Fix value generation with converter between different numeric types

### LINKED ISSUE #29406: HasConversion is not used in the provider value comparer
EF Core version: 7.0.0-rc.2.22472.11
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 2011
IDE: Visual Studio 2022 17.3.1

When upgrading from EFCore 6 to the release candidate I got the following exception:
```
---> System.AggregateException: One or more errors occurred. (Unable to cast object of type 'System.Decimal' to type 'System.Int64'.)
---> System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Int64'.
   at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer`1.Equals(Object left, Object right)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ValueGenerationManager.Generate(InternalEntityEntry entry, Boolean includePrimaryKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, Nullable`1 fallbackState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
```

I found already the origin but let me give you some code first. We have the following entity:
```C#
public record MyRecord
{
  public long MyKey { get; set; }
  public long OtherData { get; set; }
}
```

In the SQL database table both values (MyKey and OtherData) are of the type numeric(18,0) which is interpreted in EFCore as the datatype **decimal**. Because a direct cast between long and decimal is not possible a **conversion** has always to be done between those data types for comparison and so on. Thus, in the corresponding DbContext I defined the following:
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
  modelBuilder.Entity<MyRecord>(entity =>
  {
    entity.HasKey(e => e.MyKey);
    entity.Property(e => e.MyKey)
        .ValueGeneratedOnAdd()
        .HasPrecision(18, 0)
        .HasColumnName("MyKey")
        .HasConversion(v => new decimal(v), v => decimal.ToInt64(v));
  
    entity.Property(e => e.OtherData)
                  .IsRequired()
                  .HasPrecision(18, 0)
                  .HasColumnName("OtherData")
                  .HasConversion(v => new decimal(v), v => decimal.ToInt64(v));
  }
}
```

However, I found that this conversion is not taken into account anymore for the provider value comparer in EFCore 7. So, I was overwriting the methods Snapshot, GetHashCode and Equals in a derived class and used that instead of the default one. The following code works:
```C#
public class MyDbContext : DbContext
{
  ... Some general stuff

  private class MyValueComparer<T> : ValueComparer<T>
  {
    public MyValueComparer(Expression<Func<T, T, bool>> equalsExpression, Expression<Func<T, int>> hashCodeExpression, Expression<Func<T, T>> snapshotExpression) : base(equalsExpression, hashCodeExpression, snapshotExpression)
  {}
  
    public override object Snapshot(object instance)
    {
        if (instance is decimal instance1)
        {
            return Snapshot(decimal.ToInt64(instance1));
        }
        else
        {
            return Snapshot((T)instance);
        }
    }
  
    public override int GetHashCode(object instance)
    {
        if (instance is decimal instance1)
        {
            return GetHashCode(decimal.ToInt64(instance1));
        }
        else
        {
            return GetHashCode((T)instance);
        }
    }
  
    public override bool Equals(object left, object right)
    {
        var v1Null = left == null;
        var v2Null = right == null;
  
        var t1 = left?.GetType();
        var t2 = right?.GetType();
  
        if (right is null)
        {
            return v1Null;
        }
        else if (right is decimal right1)
        {
            return !v1Null && Equals((T)left, decimal.ToInt64(right1));
        }
        else
        {
            return !v1Null && Equals((T)left, (T)right);
        }
    }
  }

  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    modelBuilder.Entity<MyRecord>(entity =>
    {
      var keyComparer = new MyValueComparer<long>(
                (l, r) => l == r,
                v => v.GetHashCode(),
                v => v);

            var keyConverter = new ValueConverter<long, decimal>(
                v => new decimal(v),
                v => decimal.ToInt64(v));

      entity.HasKey(e => e.MyKey);
      entity.Property(e => e.MyKey)
          .ValueGeneratedOnAdd()
          .HasPrecision(18, 0)
          .HasColumnName("MyKey")
          .HasConversion(keyConverter, keyComparer);
    
      entity.Property(e => e.OtherData)
                    .IsRequired()
                    .HasPrecision(18, 0)
                    .HasColumnName("OtherData")
                    .HasConversion(v => new decimal(v), v => decimal.ToInt64(v));
    }
  }
```

So, I guess the bug is that the provider value comparer does not use the defined conversion in the corresponding methods or before those are called.

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #29406

The value generator selection was returning a generator for the converted type, when a value for the non-converted type should have been used.

### CODE REVIEW

File: src/EFCore/ValueGeneration/TemporaryNumberValueGeneratorFactory.cs [hunk 1]
```diff
@@ -27,70 +27,91 @@ public class TemporaryNumberValueGeneratorFactory : ValueGeneratorFactory
...
-            return new TemporaryFloatValueGenerator();
-        }
-
-        if (type == typeof(double))
-        {
-            return new TemporaryDoubleValueGenerator();
+            generator = TryCreate();
+            if (generator != null)
+            {
+                return generator;
```
Comment (AndriySvyryd) [inline src/EFCore/ValueGeneration/TemporaryNumberValueGeneratorFactory.cs:44]: When does this path get used? Wouldn't it result in the same exception?

Comment (ajcvickers) [reply src/EFCore/ValueGeneration/TemporaryNumberValueGeneratorFactory.cs:44]: No, because this path is used when the generator is being created for the converted value--for example, when an int is wrapped in a class. For that path, the generator is used `WithConverter`.

Comment (AndriySvyryd) [reply src/EFCore/ValueGeneration/TemporaryNumberValueGeneratorFactory.cs:44]: Smells like bad coupling. I think there could be more issues hiding here. This makes https://github.com/dotnet/efcore/issues/25926 more useful.

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore/ValueGeneration/TemporaryNumberValueGeneratorFactory.cs (hunk 1 above)
Comment (ajcvickers) [reply src/EFCore/ValueGeneration/TemporaryNumberValueGeneratorFactory.cs:44]: It is. I started down the rabbit hole of changing the signature here, but it was quite breaking, and so went for this fix for now. It may be worth revisiting.
