### PR TITLE
[release/6.0] Fix to #27072 - Suboptimal SQL generation for query with optional navigation, its collection navigation and lateral join

### LINKED ISSUE #27072: Suboptimal SQL generation for query with optional navigation, its collection navigation and lateral join
Consider the following code:

```C#
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

using var db = new Context();

var result = db.Set<EntityOne>()
    .Select(o => new
    {
        Ids = o.Two!.Children!.Select(c => new { ChildId = c.Id, ParentId = o.Two.Id }),
    });

System.Console.WriteLine(result.ToQueryString());

public class Context : DbContext
{
    private static ILoggerFactory LoggerFactory => new ServiceCollection().AddLogging(l => l.AddConsole().SetMinimumLevel(LogLevel.Trace)).BuildServiceProvider().GetRequiredService<ILoggerFactory>();

    public DbSet<EntityOne> Ones => Set<EntityOne>();
    public DbSet<EntityTwo> Twos => Set<EntityTwo>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseNpgsql("Host=stub")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(LoggerFactory);
    }
}

public class EntityOne
{
    public int Id { get; set; }

    public int? TwoId { get; set; }

    [ForeignKey(nameof(TwoId))]
    public EntityTwo? Two { get; set; }
}

public class EntityTwo
{
    public int Id { get; set; }

    public int? ParentId { get; set; }

    [ForeignKey(nameof(ParentId))]
    public EntityTwo? Parent { get; set; }

    [InverseProperty(nameof(Parent))]
    public ICollection<EntityTwo>? Children { get; set; }
}
```

The generated SQL is:
```sql
SELECT o."Id", t."Id", t0."ChildId", t0."ParentId"
FROM "Ones" AS o
LEFT JOIN "Twos" AS t ON o."TwoId" = t."Id"
LEFT JOIN LATERAL (
    SELECT t1."Id" AS "ChildId", t."Id" AS "ParentId"
    FROM "Twos" AS t1
    WHERE (t."Id" = t1."ParentId") OR ((t."Id" IS NULL) AND (t1."ParentId" IS NULL))
) AS t0 ON TRUE
ORDER BY o."Id", t."Id"
```

It is very suboptimal, since due to the unnecessary `OR ((t."Id" IS NULL) AND (t1."ParentId" IS NULL))` clause in the inner query, it will iterate over all `EntityTwo` having `ParentId = null` for every `EntityOne` with `TwoId = null`, creating a new output row on every iteration.

It's possible to get rid of the iteration in the database with a workaround like:
```c#
db.Set<EntityOne>()
    .Select(o => new
    {
        Ids = o.Two!.Children!.Where(c => c.ParentId != null).Select(c => new { ChildId = c.Id, ParentId = o.Two.Id }),
    });
```

### provider and version information

EF Core version: 6.0.1
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 6.0.2
Target framework: .NET 6

### PR DESCRIPTION
**Pull request by maumar**
Fixes #27072

**Description**

When expanding collection navigation we added a check to filter out rows for which parent value is null and only afterwards match inner and outer keys. This could happen when chaining collection navigation after optional reference. Problem was that during translation we try to convert the collection subquery to a join and if that succeeds we don't need the null check anymore - joins key comparison doesn't match nulls. However, we also remove the null check when we are not able to convert to JOIN and use APPLY instead.

Fix is to save the original predicate before we try to extract the join predicate and then for APPLY case re-apply the original predicate and only use the extracted join predicate for the JOIN case.

**Customer impact**

Customers running query with affected scenarios can receive incorrect results.

**How found**

Customer reported on 6.0

**Regression**

No. 

**Testing**

Added test for user reported scenario. Several existing tests also cover the code path (and had the generated sql changed as a result), but they didn't have specific data to manifest the data corruption.

**Risk**

Low risk. We are re-applying the original predicate without doing any additional processing on it. Also added quirk to revert to previous behavior.

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -2171,7 +2175,18 @@ private enum JoinType
                             return;
                         }
 
-                        innerSelectExpression.ApplyPredicate(joinPredicate);
+                        if (!AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue27072", out var enabled27072) || !enabled27072)
+                        {
+                            if (originalInnerSelectPredicate != null)
+                            {
+                                innerSelectExpression.Predicate = originalInnerSelectPredicate;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2182]: Predicate or Having

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs [hunk 2]
```diff
@@ -1640,7 +1637,7 @@ public override async Task Correlated_collection_after_distinct_not_containing_o
 OUTER APPLY (
     SELECT [t].[OrderDate] AS [Outer1], [t].[CustomerID] AS [Outer2], [o0].[OrderID] AS [Inner], [o0].[OrderDate]
     FROM [Orders] AS [o0]
-    WHERE [o0].[OrderID] IN (10248, 10249, 10250) AND (([t].[CustomerID] = [o0].[CustomerID]) OR (([t].[CustomerID] IS NULL) AND ([o0].[CustomerID] IS NULL)))
+    WHERE (([o0].[CustomerID] = [t].[CustomerID]) OR (([o0].[CustomerID] IS NULL) AND ([t].[CustomerID] IS NULL))) AND [o0].[OrderID] IN (10248, 10249, 10250)
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs:1640]: Is this null checks required for the case?

Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs:1640]: the comparison has been explicitly defined in the query. we only do the trick with null check when we expand navigations. Arguably we could try to detect the pattern and apply the filter here also, but I'd say it outside of the scope of this issue

**Review by smitpatel — APPROVED** [review]
