### PR TITLE
[SMALL] Fix to #19801 - Query: add validation to warn about required navigations pointing to entity with query filter

### LINKED ISSUE #19801: Query: add validation to warn about required navigations pointing to entity with query filter
When model has required navigation which points to the entity, which has query filter we could run into a problematic situation. If the entity is filtered out by query filter we run into referential integrity issue (required entity is not there), so currently we remove the parent entity also. This might be unexpected - we should detect this case during model validation. 

Ideally this case would be handled by having a query filter also on the other side of the navigation, effectively filtering out entities whose other side of the navigation has been pruned by it's query filter (soft cascade delete of sorts)

### PR DESCRIPTION
**Pull request by maumar**
Warning is issued for required navigations for which required side has query filter and the optional side doesn't.
When both sides define query filters we assume they are correct, i.e. we don't peek inside the filters to make sure they are consistent.

Fixes #19801

### CODE REVIEW

**Comment by maumar** [comment]
ping

File: src/EFCore/Diagnostics/CoreEventId.cs [hunk 1]
```diff
@@ -646,6 +647,22 @@ private enum Id
         /// </summary>
         public static readonly EventId ConflictingKeylessAndKeyAttributesWarning = MakeModelId(Id.ConflictingKeylessAndKeyAttributesWarning);
 
+        /// <summary>
+        ///     <para>
+        ///         Required navigation with principal entity having global query filter defined
+        ///         and the principal entity not having a matching filter
```
Comment (lajones) [inline src/EFCore/Diagnostics/CoreEventId.cs:653]: Principal mentioned twice? Should one of them be declaring?

File: src/EFCore/Properties/CoreStrings.resx [hunk 2]
```diff
@@ -1375,6 +1375,10 @@
     <value>Conflicting attributes have been applied: the 'Key' attribute on property '{property}' and the 'Keyless' attribute on its entity '{entity}'. Note that the entity will have no key unless you use fluent API to override this.</value>
     <comment>Warning CoreEventId.ConflictingKeylessAndKeyAttributesWarning string string</comment>
   </data>
+  <data name="LogPossibleIncorrectRequiredNavigationWithQueryFilterInteraction" xml:space="preserve">
+    <value>Entitiy '{principalEntityType}' has global query filter defined and is a required end of a relationship with the entity '{declaringEntityType}'. This may lead to unexpected results when the required entity is filtered out. Either use optional navigation or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.</value>
```
Comment (lajones) [inline src/EFCore/Properties/CoreStrings.resx:1379]: Nit: Entitiy -> Entity
