### PR TITLE
[6.0] Fix to #26166 - Idempotent migration script generates problematic temporal table alter statement

### LINKED ISSUE #26166: Idempotent migration script generates problematic temporal table alter statement
When executing generated idempotent migration scripts including temporal table operations, a runtime error is encountered whereby a previously run operation is being executed again.

The generated script section:
``` sql
IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20210923063806_TemporalTables')
BEGIN
    ALTER TABLE [Users] ADD PERIOD FOR SYSTEM_TIME ([_PeriodStart], [_PeriodEnd])
END;
GO
```

Causes an error on the _second_ run:
```
Temporal SYSTEM_TIME period is already defined on table 'X.dbo.Users'.
```

Potentially relevant discussion: https://dba.stackexchange.com/questions/226186/cant-stop-execution-of-add-period

--

.NET SDK: `6.0.100-rc.2.21458.9`
`dotnet-ef` tool: `6.0.0-rc.2.21470.27`
Database provider: `Microsoft.EntityFrameworkCore.SqlServer`
Target framework: .NET 6
Operating system: Windows 11 Pro 21H2
IDE: Visual Studio 2022 17.0.0 Preview 4.0

### PR DESCRIPTION
**Pull request by maumar**
Problem was that for idempotent migration scripts that convert non-temporal table to temporal we need to wrap the period switching statement in exec. Otherwise sql parser(?) complains that the command is invalid because period already exists. This is a false negative - the statement will not actually execute if this migration has already been applied. Exec fixes the problem since the statement inside it can't be parsed. This is how we deal with similar issues in other places in the code.

Fixes #26166

### CODE REVIEW

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 1]
```diff
@@ -2697,18 +2698,29 @@ void DisablePeriod(string table, string? schema, string periodStartColumnName, s
...
+                    .Append("ALTER TABLE ")
+                    .Append(Dependencies.SqlGenerationHelper.DelimitIdentifier(table, schema))
+                    .Append(" ADD PERIOD FOR SYSTEM_TIME (")
+                    .Append(Dependencies.SqlGenerationHelper.DelimitIdentifier(periodStartColumnName))
+                    .Append(", ")
+                    .Append(Dependencies.SqlGenerationHelper.DelimitIdentifier(periodEndColumnName))
+                    .Append(")")
+                    .ToString();
+
+                if (options.HasFlag(MigrationsSqlGenerationOptions.Idempotent))
```
Comment (maumar) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs:2711]: I tested disable period, as well as enable/disable versioning - they all work. Only enable period causes issues it seems

**Comment by Pilchie** [comment]
Scenario approved for EFCore 6.0, pending code review sign-off.

**Review by AndriySvyryd — APPROVED** [review]

**Review by bricelam — COMMENTED** [review]
:shipit:
