### PR TITLE
[SMALL] Fix to #30358 - Duplicate table alias in generated select query (An item with the same key has already been added)

### LINKED ISSUE #30358: Duplicate table alias in generated select query (An item with the same key has already been added)
## EF Core Query results in argument exception `An item with the same key has already been added. Key: c0` 

caused by generated duplicate table alias

### Code

Query causing the problem:

``` CSharp
        var query = dbContext.ContainerConfigurations
            .AsSplitQuery()
            .Include(e => e.Container)
                .ThenInclude(e => e.HardwareUnit)
                    .ThenInclude(e => e.CurrentConfiguration)
            .Where(e => e.Fraction == entity);

        query.ToQueryString();
```

Solution with test failing with duplicate table alias:

[EFCoreDuplicateTableAlias.zip](https://github.com/dotnet/efcore/files/10844601/EFCoreDuplicateTableAlias.zip)

The issue manifested after upgrading from EF Core 6 to EF Core 7.
With MySQL Pomelo provider, the issue manifests both for split and non-split query. 
For SQLite provider (unit test) it fails with split query.

It may be related to global query filters as removing the filters makes the issue go away.

### Stack trace

```
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added. Key: c0
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ColumnExpressionReplacingExpressionVisitor..ctor(SelectExpression oldSelectExpression, IEnumerable`1 newTableReferences)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.CloningExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.InnerJoinExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.CloningExpressionVisitor.Visit(Expression expression)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__65`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Utilities.EnumerableExtensions.ToList[TSource](IEnumerable source)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.CloningExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyProjection(Expression shaperExpression, ResultCardinality resultCardinality, QuerySplittingBehavior querySplittingBehavior)
   at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionProjectionApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Sqlite.Query.Internal.SqliteQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(IQueryable source)
   at eGateDigi.Web.Services.Containers.Configuration.UpdateFractionHandler.<Handle>d__3.MoveNext() in C:\Code\eGateDigi\eGateDigi.Web\UpdateFraction.cs:line 89
```

### Provider and version information

EF Core version: 7.0.3
Database provider: Microsoft.EntityFrameworkCore.SqLite 7.0.3
Target framework: .NET 7.0
Operating system: Windows 10 19044.2604
IDE: Visual Studio 2022 17.4

### PR DESCRIPTION
**Pull request by maumar**
We were not updating usedAliases list as we uniquify tabke aliases after combining two sources because of JOIN. If the resulting query also needs owned type expanded (when owned type is mapped to a separate table - this expansion happens in translation rather than nav expansion), additional table generated could have incorrect alias. Fix is to update the usedAliases list as we make changes to aliases, so that when new tables are added we generate new aliases correctly.

Fixes #30358

### CODE REVIEW

**Comment by maumar** [comment]
@ajcvickers patch? it's a regression from 6 and fix is small/safe.

File: test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs [hunk 1]
```diff
@@ -180,4 +180,23 @@ public override async Task Owned_entity_with_all_null_properties_property_access
 FROM [RotRutCases] AS [r]
 """);
     }
+
+    public override async Task Join_selects_with_duplicating_aliases_and_owned_expansion__uniquifies_correctly(bool async)
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs:184]:
```suggestion
    public override async Task Join_selects_with_duplicating_aliases_and_owned_expansion_uniquifies_correctly(bool async)
```

File: test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs [hunk 2]
```diff
@@ -180,4 +180,23 @@ public override async Task Owned_entity_with_all_null_properties_property_access
...
+    SELECT [m0].[Id], [m0].[Affiliation], [m0].[Name], [m1].[Magus30358Id], [m1].[Name] AS [Name0]
+    FROM [Magi] AS [m0]
+    LEFT JOIN [MagicTools] AS [m1] ON [m0].[Id] = [m1].[Magus30358Id]
+    WHERE [m0].[Name] LIKE N'%Bayaz%'
+) AS [t] ON [m].[RulerOf] = [t].[Affiliation]
+""");
+    }
+
+
 }
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs:202]:
```suggestion
    }
}
```

**Review by roji — APPROVED** [review]

**Comment by ajcvickers** [comment]
@maumar Sure, sounds like a good candidate.
