### PR TITLE
Fix to #20003 - Convert multiple equality/in-equality on same column joined by Or/Else into SQL IN expression

### LINKED ISSUE #20003: Convert multiple equality/in-equality on same column joined by Or/Else into SQL IN expression
We generate some Where expressions dynamically in our product. In some situations we pass a long list of values. 
In 2.2 this translated into an `IN` expression and was handled correctly.
In 3.1 it translates to a series of OR expressions with each consecutive expression being nested in brackets.
The following example produces drastically different SQL code. This also reproduces when we use Devart Oracle provider.

### Steps to reproduce

Both `Where` clauses in the example produce identical SQL in each .NET Core version.

``` C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Linq;
using System;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq.Dynamic.Core;

namespace joingroupcountquery
{
    class Program
    {
        static void Main(string[] args)
        {
            var seeder = new Seeder();
            seeder.Seed();
            new Logic().ExecuteQuery();
            Console.WriteLine("Hello World!");
        }
    }

    public class Logic
    {
        public IList<Dto> ExecuteQuery()
        {
            using (var dbContext = new MyDbContext())
            {
                return dbContext.Items
                .Where("Id in(4,5,1,7,12,15)")
                //.Where(i => (i.Id == 4 || i.Id == 5 || i.Id == 1 || i.Id == 7 || i.Id == 12 || i.Id == 15))
                .Select(i => new Dto { Id = i.Id })
                .ToList();
            }
        }
    }

    public class Dto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int GroupCount { get; set; }
        public int CategoryCount { get; set; }
    }

    public class Seeder
    {
        public void Seed()
        {
            using (var dbContext = new MyDbContext())
            {
                if (!dbContext.Items.Any())
                {
                    for (int i = 0; i < 10; i++)
                    {
                        var rand = new Random();
                        int group = rand.Next() % 4;
                        int cat = rand.Next() % 3;
                        var item = new Item { GroupId = group, CategoryId = cat, Name = $"Item {i}" };
                        dbContext.Items.Add(item);
                    }
                }
                if (!dbContext.Groups.Any())
                {
                    for (int i = 0; i < 4; i++)
                    {
                        var group = new Group { Name = $"Group {i}" };
                        dbContext.Groups.Add(group);
                    }
                }
                if (!dbContext.Categories.Any())
                {
                    for (int i = 0; i < 3; i++)
                    {
                        var category = new Category { Name = $"Category {i}" };
                        dbContext.Categories.Add(category);
                    }
                }
                dbContext.SaveChanges();
            }
        }
    }

    public class Item
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
    }

    public class Group
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class MyDbContext : DbContext
    {
        public static readonly ILoggerFactory loggerFactory = LoggerFactory.Create(builder =>
        {
            builder.AddConsole();
        });

        public DbSet<Item> Items { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<Category> Categories { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new ItemConfiguration());
            modelBuilder.ApplyConfiguration(new GroupConfiguration());
            modelBuilder.ApplyConfiguration(new CategoryConfiguration());
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseLoggerFactory(loggerFactory)
                .EnableSensitiveDataLogging()
                .UseSqlServer(@"Server=.;Database=JoinGroupCount;User Id=sa;Password=password");
        }
    }

    public class ItemConfiguration : IEntityTypeConfiguration<Item>
    {
        public void Configure(EntityTypeBuilder<Item> builder)
        {
            builder.ToTable("Item");
            builder.HasKey(o => o.Id);
            builder.Property(t => t.Id).HasColumnName("id").ValueGeneratedOnAdd();
            builder.Property(t => t.GroupId).HasColumnName("groupId");
            builder.Property(t => t.CategoryId).HasColumnName("categoryId");
            builder.Property(t => t.Name).HasColumnName("name");
        }
    }

    public class GroupConfiguration : IEntityTypeConfiguration<Group>
    {
        public void Configure(EntityTypeBuilder<Group> builder)
        {
            builder.ToTable("Group");
            builder.HasKey(o => o.Id);
            builder.Property(t => t.Id).HasColumnName("id").ValueGeneratedOnAdd();
            builder.Property(t => t.Name).HasColumnName("name");
        }
    }

    public class CategoryConfiguration : IEntityTypeConfiguration<Category>
    {
        public void Configure(EntityTypeBuilder<Category> builder)
        {
            builder.ToTable("Category");
            builder.HasKey(o => o.Id);
            builder.Property(t => t.Id).HasColumnName("id").ValueGeneratedOnAdd();
            builder.Property(t => t.Name).HasColumnName("name");
        }
    }
}

```

.NET Core 3.1:
```SQL
      SELECT [i].[id] AS [Id]
      FROM [Item] AS [i]
      WHERE ((((([i].[id] = 4) OR ([i].[id] = 5)) OR ([i].[id] = 1)) OR ([i].[id] = 7)) OR ([i].[id] = 12)) OR ([i].[id] = 15)
```

.NET Core 2.2:
```SQL
      SELECT [i].[id]
      FROM [Item] AS [i]
      WHERE [i].[id] IN (4, 5, 1, 7, 12, 15)
```

With enough elements in the `IN` expression, we end up exceeding the allowed nest depth and the SQL server throws an exception.

I'm not sure whether this a dup, but I couldn't find any other open issues describing this problem.

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer, Devart Oracle provider
Target framework: .NET Core 3.1.2
Operating system: Visual Studio 2019 16.4, Visual Studio Code

### PR DESCRIPTION
**Pull request by maumar**
Various optimizations to queries with IN:
- a == X || a == Y -> a IN (X, Y)
- a != X && a != Y -> a NOT IN (X, Y)
- a IN (X) -> a == X
- a IN (X, Y) || a IN (Z, W) -> a IN (X, Y, Z, W)
- a IN (X, Y, Z) && a IN (Y, Z, W) -> a IN (Y, Z)

Fixes #20003

### CODE REVIEW

File: src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs [hunk 1]
```diff
@@ -0,0 +1,348 @@
...
+                    || sqlBinaryExpression.OperatorType == ExpressionType.LessThan
+                    || sqlBinaryExpression.OperatorType == ExpressionType.LessThanOrEqual))
+            {
+                return OptimizeCompareTo(
+                    sqlBinaryExpression,
+                    intValue,
+                    caseComponent);
+            }
+
+            var left = (SqlExpression)Visit(sqlBinaryExpression.Left);
```
Comment (maumar) [inline src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs:228]: this is the part that was added

File: src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs [hunk 2]
```diff
@@ -0,0 +1,348 @@
...
+            if (sqlBinaryExpression.OperatorType == ExpressionType.AndAlso
+                 || sqlBinaryExpression.OperatorType == ExpressionType.OrElse)
+            {
+                var leftCandidateInfo = GetInExressionCandidateInfo(left);
+                var rightCandidateInfo = GetInExressionCandidateInfo(right);
+                if (leftCandidateInfo.optimizeCandidate && rightCandidateInfo.optimizeCandidate
+                    && leftCandidateInfo.columnExpression == rightCandidateInfo.columnExpression
+                    && leftCandidateInfo.operationType == rightCandidateInfo.operationType)
+                {
+                    var leftConstantIsArray = leftCandidateInfo.constantExpression.Value is Array;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs:240]: I have doubts regarding this being an array (rather than enumerable)
And usage of method.Invoke.

Comment (maumar) [reply src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs]: updated

File: src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs [hunk 3]
```diff
@@ -0,0 +1,399 @@
...
+
+            return result;
+        }
+
+        private List<object> BuildListFromEnumerable(IEnumerable collection)
+        {
+            List<object> result;
+            if (collection is List<object> list)
+            {
+                result = list;
```
Comment (maumar) [inline src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs:351]: should be ok to do this, but could always create new instance, just to be safe - thoughts?

File: src/EFCore.Relational/Query/SqlNullabilityProcessor.cs [hunk 4]
```diff
@@ -648,6 +656,19 @@ protected virtual SqlExpression VisitIn([NotNull] InExpression inExpression, boo
...
+            {
+                return inValuesList.Count == 1
+                    ? inExpression.IsNegated
+                        ? (SqlExpression)_sqlExpressionFactory.NotEqual(
+                            inExpression.Item,
+                            _sqlExpressionFactory.Constant(inValuesList[0], inValuesExpression.TypeMapping))
+                        : _sqlExpressionFactory.Equal(
+                            inExpression.Item,
+                            _sqlExpressionFactory.Constant(inValuesList[0], inExpression.Values.TypeMapping))
+                    : inExpression.Update(inExpression.Item, inValuesExpression, subquery: null);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlNullabilityProcessor.cs:670]: You already update the inExpression before passing in here, remove duplicated update.

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs [hunk 5]
```diff
@@ -892,7 +892,7 @@ public override async Task Contains_with_local_collection_complex_predicate_and(
             AssertSql(
                 @"SELECT [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
 FROM [Customers] AS [c]
-WHERE (([c].[CustomerID] = N'ALFKI') OR ([c].[CustomerID] = N'ABCDE')) AND [c].[CustomerID] IN (N'ABCDE', N'ALFKI')");
+WHERE [c].[CustomerID] IN (N'ALFKI', N'ABCDE') AND [c].[CustomerID] IN (N'ABCDE', N'ALFKI')");
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs:895]: No further optimization?

File: src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs [hunk 6]
```diff
@@ -0,0 +1,399 @@
...
+
+                            resultArray = AddToCollection((IEnumerable)leftValue, rightValue);
+                        }
+
+                        return _sqlExpressionFactory.In(
+                            leftCandidateInfo.columnExpression,
+                            _sqlExpressionFactory.Constant(resultArray, leftCandidateInfo.constantExpression.TypeMapping),
+                            leftCandidateInfo.operationType == ExpressionType.NotEqual);
+                    }
+                    else if (leftConstantIsEnumerable && rightConstantIsEnumerable)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs:283]: Where are you checking that operator between both InExpression?

File: src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs [hunk 7]
```diff
@@ -0,0 +1,399 @@
...
+            if (sqlBinaryExpression.OperatorType == ExpressionType.AndAlso
+                 || sqlBinaryExpression.OperatorType == ExpressionType.OrElse)
+            {
+                var leftCandidateInfo = GetInExressionCandidateInfo(left);
+                var rightCandidateInfo = GetInExressionCandidateInfo(right);
+                if (leftCandidateInfo.optimizeCandidate && rightCandidateInfo.optimizeCandidate
+                    && leftCandidateInfo.columnExpression == rightCandidateInfo.columnExpression
+                    && leftCandidateInfo.operationType == rightCandidateInfo.operationType)
+                {
+                    var leftConstantIsEnumerable = leftCandidateInfo.constantExpression.Value is IEnumerable
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs:234]: return the object value back from GetInExpressionCandidateInfo thing.

Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs:234]: And separate out type mapping.

File: src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs [hunk 8]
```diff
@@ -0,0 +1,399 @@
...
+                foreach (var collectionElement in collection)
+                {
+                    result.Add(collectionElement);
+                }
+            }
+
+            return result;
+        }
+
+        private (bool optimizeCandidate, ColumnExpression columnExpression, SqlConstantExpression constantExpression, ExpressionType operationType) GetInExressionCandidateInfo(SqlExpression sqlExpression)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs:365]: tuple members are uppercase.

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs (hunk 5 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs:895]: its parameter collection - we don't have access to the contents at the time we perform the optimization.

File: src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs (hunk 6 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs:283]: we know operators on both candidates are the same (line 232), `IN || IN` and `NOT IN && NOT IN` are handled in the if block (242, 243), so this must be the other 2 possibilites (`NOT IN || NOT IN` or `IN && IN`)

**Comment by maumar** [comment]
@smitpatel updated
