### PR TITLE
Redo SQL tree pruning

### LINKED ISSUE #31083: Prune all SelectExpressions, not just those in Tables
Our current pruning logic currently only operates on SelectExpressions which are present in the Tables list of other SelectExpressions; it notably doesn't handle subqueries embedded e.g. in the predicate.

For example, given the following entity type:

```c#
public class Blog
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public int Unneeded { get; set; }
}
```

... and the following query:

```c#
_ = ctx.Blogs
    .OrderBy(b => b.Id)
    .Take(10)
    .Take(5) // Causes pushdown
    .Select(b => b.Name)
    .ToList();
```

... the Unneeded column gets properly pruned from the projection:

```sql
SELECT TOP(@__p_1) [t].[Name]
FROM (
    SELECT TOP(@__p_0) [b].[Id], [b].[Name]
    FROM [Blogs] AS [b]
    ORDER BY [b].[Id]
) AS [t]
ORDER BY [t].[Id]
```

But if you place the same thing inside a subquery:

```c#
_ = ctx.Blogs
    .Where(b => ctx.Blogs
        .OrderBy(b => b.Id)
        .Take(10)
        .Take(5) // Causes pushdown
        .Select(b => b.Name)
        .First() == "foo")
    .ToList();
```

... that yields the following SQL, which does project Unneeded:

```sql
SELECT [b].[Id], [b].[Name], [b].[Unneeded]
FROM [Blogs] AS [b]
WHERE (
    SELECT TOP(1) [t0].[Name]
    FROM (
        SELECT TOP(5) [t].[Name], [t].[Id]
        FROM (
            SELECT TOP(10) [b0].[Id], [b0].[Name], [b0].[Unneeded]
            FROM [Blogs] AS [b0]
            ORDER BY [b0].[Id]
        ) AS [t]
        ORDER BY [t].[Id]
    ) AS [t0]
    ORDER BY [t0].[Id]) = N'foo'
```

The reason for this is that the pruning logic isn't implemented as a proper visitor which visits the entire tree; instead, SelectExpressionPruningExpressionVisitor (in postprocessing) calls [SelectExpression.Prune](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs#L3977); this recurses into Tables, but not into the other parts of the query.

We should extract the pruning logic out to SelectExpressionPruningExpressionVisitor, taking care with SelectExpression private state etc. Note https://github.com/dotnet/efcore/issues/31049#issuecomment-1592948285 which is similar, abuot allowing providers to add other pruning logic.

### LINKED ISSUE #31407: Improve pruning to properly support ExecuteUpdate
#31406, allowed ExecuteUpdate with entity splitting (as long as all updated columns are on the same table). While this works well, if you try to change columns on a non-main (split) table on SQL Server, this fails (see test NonSharedModelBulkUpdatesTestBase.Update_single_table_in_entity_with_entity_splitting); - this does work on SQLite, due to a different query shape.

The root cause here is that we generate an INNER JOIN between the main table and the split table, where the split table is the one being updated. When we prune the expression after translation (SelectExpressionPruningExpressionVisitor), we don't find any reference to the joined table **within the SelectExpression**: the only references are from the UpdateExpression's column setters, but the pruning visitor doesn't see them.

The proper fix here would be to make pruning a proper visitor, with specific handling for ExecuteUpdate. More generally, we should consider not having UpdateExpression be a wrapper around SelectExpression, but its own expression type that directly contains its elements. This may involve significant work as all postprocessing visitors would need to handle it properly, but it's the more correct representation and would prevent bugs like this from the get-go.

See also:
* [#31083](https://github.com/dotnet/efcore/issues/31083), which is related (pruning also doesn't visit all SelectExpressions since it isn't a real visitor).
* [#31049](https://github.com/dotnet/efcore/issues/31049#issuecomment-1592948285), which is about extracting the visitation out of SelectExpression so that providers can extend for provider-specific expressions (such as OPENJSON).

### PR DESCRIPTION
**Pull request by roji**
* Notes on the previous pruning design:
	* The design wasn't visitor based, but rather manual recursing into the tables of the selects. This had several disadvantages, e.g. not pruning in subqueries which aren't tables, and not allowing the pruning mechanism to be extended by providers.
	* It was also based on a separate pass for finding which columns are referenced on which table (ColumnExpressionFindingExpressionVisitor); this was done for each select as we recursed down, revisiting the same nested nodes again and again.
* This rewrite does the following:
	* Replace SelectExpressionPruningExpressionVisitor with SqlTreePruner, which is a real visitor that visits everywhere, pruning places we didn't prune before.
	* This also means it can be extended by providers (e.g. OPENJSON pruning, [#32668](https://github.com/dotnet/efcore/issues/32668)).
	* The visitor is implemented as a single pass, both discovering column references and performing the actual pruning (better performance).
* Note that pruning still mutates the SelectExpression rather than creating an immutable copy, as before. I did this mainly because that's how things currently work, and changing that would mean wider changes.
	* Specifically, if there are multi-referenced selects, TableAliasVerifyingExpressionVisitor (which comes right afterwards) has logic for handling that; but if pruning duplicates the multi-referenced select, we end up with two different select instances in the tree with the same alias, tripping up assertions (see similarity with [this problem](https://github.com/dotnet/efcore/issues/32234#issuecomment-1806153111)).
	* We should revisit all of this after removing multi-referenced selects, which would be part of [#32277](https://github.com/dotnet/efcore/issues/32277).

@ajcvickers you may be interested in taking a look, this is query stuff but relatively scoped to a specific problem etc.

Two additional pruning-related PRs also coming up based on this one.

Closes #31083
Fixes #31407

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs [hunk 1]
```diff
@@ -21,6 +21,8 @@ public class SqlServerQuerySqlGenerator : QuerySqlGenerator
     private readonly ISqlGenerationHelper _sqlGenerationHelper;
     private readonly int _sqlServerCompatibilityLevel;
 
+    private bool _withinTable;
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs:24]: The changes for SQL Server generation are unfortunate and tricky...

SQL Server is very strict and does not allow a projection without an alias within a table subquery (`SELECT ... FROM (SELECT 1 ...))`); we already had special logic for generating `1 AS empty` to work around this, but the logic for when to do this was incomplete. The pruning introduced in this PR caused selects within set operations to also possibly get their projection completely trimmed away, but our logic didn't catch that (this was an already-existing, possibly latent bug).

As a result, we need to do visitor state hacks to detect when the empty projection is directly in a subquery table, to generate `AS empty` only when needed.

File: test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqlServerTest.cs [hunk 2]
```diff
@@ -90,10 +90,19 @@ public override async Task Update_main_table_in_entity_with_entity_splitting(boo
 """);
     }
 
-    // #31407
-    public override Task Update_non_main_table_in_entity_with_entity_splitting(bool async)
-        => Assert.ThrowsAnyAsync<Exception>(
-            () => base.Update_non_main_table_in_entity_with_entity_splitting(async));
+    public override async Task Update_non_main_table_in_entity_with_entity_splitting(bool async)
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqlServerTest.cs:93]: Fix for #31407

File: test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqlServerTest.cs [hunk 3]
```diff
@@ -42,9 +42,6 @@ public override async Task Delete_where_using_hierarchy(bool async)
 WHERE (
     SELECT COUNT(*)
     FROM [Animals] AS [a]
-    LEFT JOIN [Birds] AS [b] ON [a].[Id] = [b].[Id]
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqlServerTest.cs:45]: We weren't doing any pruning in subqueries that weren't table subqueries (this one is a scalar subquery inside the predicate).

File: test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs [hunk 4]
```diff
@@ -1074,9 +1074,18 @@ public override async Task Json_collection_OrderByDescending_Skip_ElementAt(bool
 WHERE (
     SELECT [t].[c]
     FROM (
-        SELECT JSON_VALUE([o].[value], '$.OwnedReferenceLeaf.SomethingSomething') AS [c], [o].[key], CAST(JSON_VALUE([o].[value], '$.Date') AS datetime2) AS [c0]
-        FROM OPENJSON([j].[OwnedReferenceRoot], '$.OwnedCollectionBranch') AS [o]
-        ORDER BY CAST(JSON_VALUE([o].[value], '$.Date') AS datetime2) DESC
+        SELECT JSON_VALUE([o].[OwnedReferenceLeaf], '$.SomethingSomething') AS [c], [o].[Date] AS [c0]
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs:1077]: This "expansion" from WITH-less OPENJSON to WITH-ful is actually an improvement; an upcoming PR will also prune unreferenced columns from the WITH column list.

File: test/EFCore.SqlServer.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqlServerTest.cs [hunk 5]
```diff
@@ -331,7 +331,7 @@ public virtual async Task Ordered_array_of_string()
 WHERE (
     SELECT COUNT(*)
     FROM (
-        SELECT [s].[value], [s].[key], CAST([s].[key] AS int) AS [c]
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqlServerTest.cs:334]: @maumar we discussed pruning these - so here we go :) I'm not sure any more if we opened an issue to track this (couldn't find one in a quick search)

File: test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs [hunk 6]
```diff
@@ -2556,21 +2556,21 @@ public override async Task Concat_anonymous_with_count(bool async)
             """
 SELECT COUNT(*)
 FROM (
-    SELECT [t].[Nickname], [t].[SquadId], [t].[AssignedCityName], [t].[CityOfBirthName], [t].[FullName], [t].[HasSoulPatch], [t].[LeaderNickname], [t].[LeaderSquadId], [t].[Rank], [t].[Discriminator], [t].[Nickname] AS [Name]
+    SELECT 1 AS empty
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs:2559]: Nice example where having COUNT(*) at the top causes all projections inside to get pruned

File: src/EFCore.Relational/Query/SqlTreePruner.cs [hunk 7]
```diff
@@ -0,0 +1,153 @@
...
+                return base.VisitExtension(node);
+        }
+    }
+
+    private SelectExpression PruneTopLevelSelect(SelectExpression select)
+    {
+#if DEBUG
+        _removedAliases = new();
+#endif
+        select = select.PruneToplevel(this, ReferencedColumnMap, _removedAliases);
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/SqlTreePruner.cs:146]: Why do you pass in `ReferencedColumnMap` instead of it just being public on the pruner?

Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/SqlTreePruner.cs:146]: Same goes for `_removedAliases`.

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore.Relational/Query/SqlTreePruner.cs (hunk 7 above)
Comment (roji) [reply src/EFCore.Relational/Query/SqlTreePruner.cs:146]: The place where I hope we land in, long-term, is for the pruning code to move out of SelectExpression altogether and into SqlTreePruner (#31049), this way that visitor contains all the pruning-related logic. Aside from better factoring (not have a god object SelectExpression), it would also allow providers to override/change the pruning behavior for SelectExpression, which is currently impossible (because SelectExpression state is private - #31049 starts changing that).

When we get to that place, ReferencedColumnMap and _removedAliases would no longer make sense as public, since they're only relevant internally (protected) to drive the pruning process. So at least the way I see it, the current state should be temporary.

Of course, we can still expose these publicly now (with [EntityFrameworkInternal]) and change this later, no problem - let me know if you prefer it that way. I'll hold off merging for now (also to allow others to take a look if they want).

Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/SqlTreePruner.cs:146]: I'd prefer them to be public if you think that the full refactoring won't be done for 9.0, but this isn't blocking in any way

Comment (roji) [reply src/EFCore.Relational/Query/SqlTreePruner.cs:146]: Sure, will make the change.

File: src/EFCore.Relational/Query/SqlTreePruner.cs [hunk 8]
```diff
@@ -0,0 +1,157 @@
...
+                    PruneTopLevelSelect(updateExpression.SelectExpression),
+                    visitedSetters);
+
+            // The following remaining cases deal with recursive visitation (i.e. non-top-level things)
+
+            // For any column we encounter, register it in the referenced column map, which records the aliases referenced on each table.
+            case ColumnExpression column:
+                RegisterTable(column.Table.UnwrapJoin());
+
+                void RegisterTable(TableExpressionBase table)
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/SqlTreePruner.cs:86]: I missed this initially. Please move to the end of the method.

Comment (roji) [reply src/EFCore.Relational/Query/SqlTreePruner.cs:86]: Doing in #32688
