### PR TITLE
Fix to #33443 - JSON path is not properly formatted

### LINKED ISSUE #33443: JSON path is not properly formatted.
## File a bug

I have a case where I have a JSON column that has JSON from Newtonsoft that is intended to be converted to XML, so has properties starting with a @ signifying an attribute and a #text meaning innerText.  This all works fine, except when I try and project the object with the weird property names and find they are not liked by JSON Path.  

The fix though appears very simple 🤞, the names just need to be enclosed with double quotes.   i.e.  
```
$.@language' => $."@language"',
```

```sql
SELECT TOP(2) [e].[Id], [t].[@language], [t].[#text]
      FROM [people].[ExtendedData] AS [e]
      INNER JOIN [people].[ExtendedDataType] AS [e0] ON [e].[ExtendedDataTypeId] = [e0].[Id]
      CROSS APPLY OPENJSON([e].[EntityData], '$.name.text') WITH (
          [@language] nvarchar(max) '$.@language',
          [#text] nvarchar(max) '$.#text'
      ) AS [t]
      WHERE [e0].[Name] = N'xferTransferItem' AND [e].[ExternalId] = N'1001'
```

Becomes

```sql
SELECT TOP(2) [e].[Id], [t].[@language], [t].[#text]
      FROM [people].[ExtendedData] AS [e]
      INNER JOIN [people].[ExtendedDataType] AS [e0] ON [e].[ExtendedDataTypeId] = [e0].[Id]
      CROSS APPLY OPENJSON([e].[EntityData], '$.name.text') WITH (
          [@language] nvarchar(max) '$."@language"',
          [#text] nvarchar(max) '$."#text"'
      ) AS [t]
      WHERE [e0].[Name] = N'xferTransferItem' AND [e].[ExternalId] = N'1001'
```

### Sample of my application:

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

Console.WriteLine("Hello, World!");

var ctx = new MyContext(new DbContextOptionsBuilder<MyContext>()
    .LogTo(Console.WriteLine, (_, level) => level == LogLevel.Information)
    .EnableSensitiveDataLogging()
    .UseSqlServer("Server=...")
          .Options);

var item = await ctx.ExtendedData
    .AsNoTracking()
    .Where(x => x.ExtendedDataType.Name == "xferTransferItem" && x.ExternalId == "1001")
    .SelectMany(x => x.EntityData.Name.Items)
    .SingleAsync(x => x.Language == "en");

Console.WriteLine(item.Value);


public partial class MyContext : DbContext
{
    public virtual DbSet<ExtendedData> ExtendedData { get; set; }
    public virtual DbSet<ExtendedDataType> ExtendedDataTypes { get; set; }

    public MyContext(DbContextOptions options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ExtendedData>()
            .OwnsOne(e => e.EntityData, b1 => 
            { 
                b1.OwnsOne(ed => ed.Name, b2 => b2.OwnsMany(i => i.Items));
                b1.ToJson();
            });
    }
}

[Table("ExtendedData", Schema = "people")]
public class ExtendedData
{
    public Guid Id { get; set; }
    public string ExternalId { get; set; }
    public OrgLevel EntityData { get; set; }
    public Guid TenantId { get; set; }
    public Guid ConnectedEntityId { get; set; }
    public Guid ExtendedDataTypeId { get; set; }


    public ExtendedDataType ExtendedDataType { get; set; } = null!;

}

[Table("ExtendedDataType", Schema = "people")]
public class ExtendedDataType
{
    public Guid Id { get; private set; }
    public Guid TenantId { get; private set; }
    public string Name { get; private set; }
    public Guid ExtensionPointId { get; private set; }

    public ICollection<ExtendedData> ExtendedData { get; } = new List<ExtendedData>(); 
}


public class OrgLevel 
{
    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("depth")]
    public string Depth { get; set; }

    [JsonPropertyName("name")]
    public TranslatableString Name { get; set; }
}

public class TranslatableString
{
    [JsonPropertyName("text")]
    public List<TranslatableStringItem> Items { get; set; } = new();
}

public class TranslatableStringItem
{
    [JsonPropertyName("@language")]
    public string Language { get; set; }

    [JsonPropertyName("#text")]
    public string Value { get; set; }
}
```

### Include stack traces

```
Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=JSON path is not properly formatted. Unexpected character '@' is found at position 2.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.ReadAsyncExecute(Task task, Object state)
   at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](SqlDataReaderBaseAsyncCallContext`1 context)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleAsync>d__14`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleAsync>d__14`1.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Repos\tmp\EfJsonColumns\EfJsonColumns\Program.cs:line 16

```

### Include verbose output

```
info: 31/03/2024 16:43:29.441 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (52ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT TOP(2) [e].[Id], [t].[@language], [t].[#text]
      FROM [people].[ExtendedData] AS [e]
      INNER JOIN [people].[ExtendedDataType] AS [e0] ON [e].[ExtendedDataTypeId] = [e0].[Id]
      CROSS APPLY OPENJSON([e].[EntityData], '$.name.text') WITH (
          [@language] nvarchar(max) '$.@language',
          [#text] nvarchar(max) '$.#text'
      ) AS [t]
      WHERE [e0].[Name] = N'xferTransferItem' AND [e].[ExternalId] = N'1001' AND [t].[@language] = N'en'
```

value of json in EnityData field

```json
{
    "depth": "3",
    "name": {
        "text": [
            {
                "@language": "en",
                "#text": "Diane's Kitchen"
            }
        ]
    },
    "id": "1010"
}
```

### Include provider and version information

EF Core version: 8.0.3
Database provider:Microsoft.EntityFrameworkCore.SqlServer using AzureSQL
Target framework: .NET 8.0
Operating system: W11
IDE: Visual Studio 2022 17.9.5

### PR DESCRIPTION
**Pull request by maumar**
Queries extracting data from JSON properties containing special characters must escape references to those properties in JSON path. Moreover, the values we use in JSON paths must correspond to how we store those properties in database. When we serialize JSON-mapped entity into JSON string, many special (unicode) characters are stored in the \uxxxx form. Lastly in the shaper, when reading json data from the stream we need to make sure to correctly match the property names using Utf8JsonReader. ValueTextEquals un-escapes the property names before comparison, the Span representing the property name must also be un-escaped.

Fixes #33443

### CODE REVIEW

File: src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs [hunk 1]
```diff
@@ -180,6 +181,47 @@ public virtual void DelimitIdentifier(StringBuilder builder, string name, string
         DelimitIdentifier(builder, name);
     }
 
+    /// <summary>
+    ///     Generates the escaped SQL representation of an identifier (column name, table name, etc.).
+    /// </summary>
+    /// <param name="identifier">The identifier to be escaped.</param>
+    /// <returns>The generated string.</returns>
+    public virtual string EscapeJsonPathElement(string identifier)
+        => JsonEncodedText.Encode(identifier).Value.Replace("\"", "\\\"", StringComparison.Ordinal);
```
Comment (roji) [inline src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs:190]: Do we actually need to escape double-quotes? Don't they get replaced with `\u0022`in JsonEncodedText.Encode anyway?

File: src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs [hunk 2]
```diff
@@ -180,6 +181,47 @@ public virtual void DelimitIdentifier(StringBuilder builder, string name, string
         DelimitIdentifier(builder, name);
     }
 
+    /// <summary>
+    ///     Generates the escaped SQL representation of an identifier (column name, table name, etc.).
+    /// </summary>
+    /// <param name="identifier">The identifier to be escaped.</param>
+    /// <returns>The generated string.</returns>
+    public virtual string EscapeJsonPathElement(string identifier)
```
Comment (roji) [inline src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs:189]: Do we need the two EscapeJsonPathElement separately, given that they're only called from DelimitJsonPathElement?

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 3]
```diff
@@ -1929,20 +1941,15 @@ void ProcessFixup(IDictionary<string, LambdaExpression> fixupMap)
...
-                                                    Default(typeof(JavaScriptEncoder))),
-                                                typeof(object)),
-                                            Parameter(typeof(MaterializerLiftableConstantContext), "_")),
-                                        jsonPropertyName + "EncodedProperty",
-                                        typeof(JsonEncodedText)),
-                                    JsonEncodedTextEncodedUtf8BytesProperty)));
+
+                                Convert(
+                                    Call(
+                                    ByteArrayAsSpanMethod,
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1947]: indentation

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 4]
```diff
@@ -78,6 +79,17 @@ public sealed partial class ShaperProcessingExpressionVisitor : ExpressionVisito
         private static readonly MethodInfo Utf8JsonReaderValueTextEqualsMethod
             = typeof(Utf8JsonReader).GetMethod(nameof(Utf8JsonReader.ValueTextEquals), [typeof(ReadOnlySpan<byte>)])!;
 
+        private static readonly PropertyInfo EncodingUtf8Property
+            = typeof(Encoding).GetProperty(nameof(Encoding.UTF8))!;
+
+        private static readonly MethodInfo Utf8GetBytesMethod
+            = typeof(Encoding).GetMethod(nameof(Encoding.GetBytes), [typeof(string)])!;
+
+        private static readonly MethodInfo ByteArrayAsSpanMethod = typeof(MemoryExtensions).GetMethods().Where(x => x.Name == nameof(MemoryExtensions.AsSpan) && x.GetGenericArguments().Count() == 1)
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:88]:
```suggestion
        private static readonly MethodInfo ByteArrayAsSpanMethod = typeof(MemoryExtensions).GetMethods()
            .Where(x => x.Name == nameof(MemoryExtensions.AsSpan) && x.GetGenericArguments().Count() == 1)
```

**Review by roji — APPROVED** [review]
This is tricky stuff....! LGTM (modulo nits/small stuff below).

I'm a bit worried about unescaped JSON that users put in their databases (without going through our SaveChanges). For people doing that, this PR will be a breaking change - the new query and shaper will start failing, if I understand correctly. I still think this is correct as our stuff should work consistently with itself, and we currently save escaped JSON to the database, but this may mean that we should implement #32152 for 9.0 as well, since that would give users a way forward (i.e. they'd disable escaping throughout our entire stack).

File: test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs [hunk 5]
```diff
@@ -2423,7 +2423,7 @@ public override async Task Json_predicate_on_int32(bool async)
         await base.Json_predicate_on_int32(async);
 
         AssertSql(
-            """
+"""
```
[the remark this answers is not in the document]
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs:2426]: ahh, that's my bad. I'm pretty sure I manually "fixed" the indentation, because this is how baseline generator originally prints it out. From what I saw we some places have indent, some don't. I'm ok to unify on indent - will fix here and when I see no indent from now on.

[the remark this answers is not in the document]
Comment (roji) [reply test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs:2426]: Sure thing - not really your fault... When I first did the switch to the new raw literal stirngs, I actually preferred it without indentation, but it wasn't possible to get the code cleanup to do things that way... So we switched to identation at some point.

File: src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs (hunk 2 above)
Comment (maumar) [reply src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs:189]: I was following the pattern of EscapeIdentifier, but you are right it won't be needed for JSON escaping.

File: src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs (hunk 1 above)
Comment (maumar) [reply src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs:190]: good catch, added it when experimenting with different escaping methods, before landing on JsonEncodedTest.

File: src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs [hunk 6]
```diff
@@ -180,6 +181,47 @@ public virtual void DelimitIdentifier(StringBuilder builder, string name, string
...
+        builder.Append(encodedIdentifier);
+    }
+
+    /// <summary>
+    ///     Writes the delimited SQL representation of an element in a JSON path.
+    /// </summary>
+    /// <param name="pathElement">The JSON path element to delimit.</param>
+    /// <returns>The generated string.</returns>
+    public virtual string DelimitJsonPathElement(string pathElement)
+        => pathElement.Any(x => !char.IsAsciiLetterOrDigit(x))
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs:209]: I actually prefer Any, since it's terse. It short circuits so there shouldn't be a perf hit - any reason why you had loop in mind?

[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs:198]: Mainly the fact that LINQ operators cause needless allocations, and this seems like an extremely trivial for loop - even if it adds a couple more lines of code. But not insisting.

[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs:198]: fair enough

**Comment by magahl** [comment]
We had an existing model that had a string property (wich was serialized json) in a Json model. Before it encoded it with a `\"` but now it will be a `\\u0022.`

When i send back my data to the client (Blazor Server) for DeSerialization it now crashes. since the "string" property contains \\u0022 instead of \". 

I havae searched the internet for an reason and this is the best lead so far, but im not certain this is the cause. All we really have done is upgrade the framework to net 9 RC1

Code used to dersilize:
`var model = JSonSerializer.Serialize<Model>(jsonString)`
