### PR TITLE
Fixup navigations to/from join entity when new many-to-many relationship is created

### LINKED ISSUE #26779: Many To Many Exception when adding and removing same entity
## File a bug

Not sure if this is bug, but I noticed different behavior when using many-to-many feature in "old" and "new" way.

If I configure many-to-many in "old" way with third model defined (Post, Tag, PostTag) and test adding and removing same PostTag, everything works as expected. Nothing is changed and no saves are necessary.

But if I do it "new" way without third model defined (only Post and Tag) and test adding Tag to Post and then removing the same Tag from same Post I get exception when trying to save changes, because context tries to delete PostTag entity which does not exists in database.

### Include your code

Example code can be found in [https://github.com/DanielBlazevic/EFCoreTest](https://github.com/DanielBlazevic/EFCoreTest)

```C#
    static void SeedData()
    {
        var ctx = new Context();

        ctx.Database.EnsureDeleted();
        ctx.Database.EnsureCreated();

        var post = new Post() { Title = "Post 1" };

        var tag = new Tag() { Text = "Tag 1" };

        ctx.Add(post);
        ctx.Add(tag);

        ctx.SaveChanges();
    }
```
"Old" way:
```C#
    static void Main(string[] args)
    {
        SeedData();

        var ctx = new Context();

        var post = ctx.Posts.First();

        var tag = ctx.Tags.First();

        var postTag = new PostTag() { Post = post, Tag = tag };

        post.PostTags.Add(postTag);

        ctx.ChangeTracker.DetectChanges();

        Console.WriteLine(ctx.ChangeTracker.DebugView.LongView);

        post.PostTags.Remove(postTag);

        ctx.ChangeTracker.DetectChanges();

        Console.WriteLine(ctx.ChangeTracker.DebugView.LongView);

        ctx.SaveChanges(); // <- Nothing to save, no exception
    }
```

"New" way:
```C#
    static void Main(string[] args)
    {
        SeedData();

        var ctx = new Context();

        var post = ctx.Posts.First();

        var tag = ctx.Tags.First();

        post.Tags.Add(tag);

        ctx.ChangeTracker.DetectChanges();

        Console.WriteLine(ctx.ChangeTracker.DebugView.LongView);

        post.Tags.Remove(tag);

        ctx.ChangeTracker.DetectChanges();

        Console.WriteLine(ctx.ChangeTracker.DebugView.LongView);

        ctx.SaveChanges(); // <- Tries to delete PostTag entity, Exception here
    }
```

### Exception

```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: 'The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.'
```

### Include provider and version information

EF Core version: 6
Database provider: Microsoft.EntityFrameworkCore.SqlServer / Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0
Operating system: Windows 10 x64
IDE: Visual Studio 2022

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #26779

Also cleanup of delay-fixup/suspended detection logic, and tests for #26074.

### CODE REVIEW

File: src/EFCore/ChangeTracking/Internal/NavigationFixer.cs [hunk 1]
```diff
@@ -52,23 +55,18 @@ public virtual void BeginAttachGraph()
...
     /// </summary>
-    public virtual void CompleteAttachGraph()
+    public virtual void CompleteDelayedFixup()
     {
         _inAttachGraph = false;
-        try
+        if (_danglingJoinEntities != null)
         {
-            if (_danglingJoinEntities != null)
+            var dangles = _danglingJoinEntities.ToList();
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:63]: Why are you changing this? Is there a way that something could be added to `_danglingJoinEntities` during `CompleteDelayedFixup()`?

File: src/EFCore/ChangeTracking/Internal/NavigationFixer.cs [hunk 2]
```diff
@@ -52,23 +55,18 @@ public virtual void BeginAttachGraph()
     ///     any release. You should only use it directly in your code with extreme caution and knowing that
     ///     doing so can result in application failures when updating to a new Entity Framework Core release.
     /// </summary>
-    public virtual void CompleteAttachGraph()
+    public virtual void CompleteDelayedFixup()
     {
         _inAttachGraph = false;
-        try
+        if (_danglingJoinEntities != null)
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:61]: `_danglingJoinEntities` always stores a call to `FindOrCreateJoinEntry`. To reduce allocations store just the arguments instead.

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore/ChangeTracking/Internal/NavigationFixer.cs (hunk 1 above)
Comment (ajcvickers) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:63]: I don't believe so. However, `BeginDelayedFixup` can be called again, and we clear any existing danglers when this happens. This shouldn't be needed if everything is working correctly, but it is there against the possibility that some error happens when, for example, attaching the graph, and we leave the collection in a bad state. We could not do this, but it felt slightly more robust to keep doing it.

Comment (AndriySvyryd) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:63]: I agree that this is more robust, but I'd prefer us to throw when an error happens rather than try to keep consistency.

You could throw in `BeginDelayedFixup` if `_inAttachGraph` is `false` and `_danglingJoinEntities` is not empty

Comment (ajcvickers) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:73]: Done.

File: src/EFCore/ChangeTracking/Internal/NavigationFixer.cs (hunk 2 above)
Comment (ajcvickers) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:71]: Done.

File: src/EFCore/ChangeTracking/Internal/NavigationFixer.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:73]: You don't need to call `ToList()` anymore.

Also could avoid some allocations if you don't null-out `_danglingJoinEntities`

Comment (ajcvickers) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:73]: Do you think it's better to keep the list around (even though it may not be used again, or not used for some time) rather than create a new one if we happen to need it again? (I've been wondering about this.)

Comment (AndriySvyryd) [reply src/EFCore/ChangeTracking/Internal/NavigationFixer.cs:73]: I think that the chance of the list being used goes up significantly after it has been used once.
