### PR TITLE
[Release/3.1] ReplacingEV uses two arrays instead of dictionary (#19858)

### LINKED ISSUE #19737: Exponential hash code calculation in ReplacingExpressionVisitor
I have query like this, result1 success get data but result2 stuck(not throw exception and not get result).

``` C#
var trx = context.Adjustments.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = x.IsPositive ? UserActionSource.AdjustmentPlus : UserActionSource.AdjustmentMinus,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = x.CostCenterId
            }).Union(context.SupplierDownPayments.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.SupplierDownPayment,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.PurchaseRequisitions.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.PurchaseRequisition,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.PurchaseOrders.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.PurchaseOrder,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.ReceivedItems.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.ReceivedItem,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            }))
            .Union(context.Purchases.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.Purchase,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.PurchaseReceivings.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.PurchaseReceiving,
                RefCode = x.Code,
                BranchId = null,
                CostCenterId = null
            })).Union(context.PurchaseReturns.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.PurchaseReturn,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.JournalVouchers.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.JournalVoucher,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.OtherDeposits.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.OtherDeposit,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.OtherPayments.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.OtherPayment,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.WarehouseTransfers.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.WarehouseTransfer,
                RefCode = x.Code,
                BranchId = null,
                CostCenterId = null
            })).Union(context.ItemTransferIns.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.ItemTransferIn,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            })).Union(context.ItemTransferOuts.Select(x => new TransactionRef
            {
                Id = x.Id,
                Source = UserActionSource.ItemTransferOut,
                RefCode = x.Code,
                BranchId = x.BranchId,
                CostCenterId = null
            }));

            var result1= await (from i in trx
                      select new
                      {
                          i.Id
                      }).ToListAsync(cancellationToken);

            var result2 = await (from i in trx
                      select new
                      {
                          i.Id,
                          IsA = (from ah in context.AccountHistories where i.Id == ah.RefId select ah.Id).Count() > 0
                      }).ToListAsync(cancellationToken);
```
how to fix it?

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4

### PR DESCRIPTION
**Pull request by roji**
ReplacingExpressionVisitor held original and replacement expressions in a dictionary. Unfortunately that means hash code calculation occurs exponentially, as each TryGetValue on the dictionary must traverse the entire tree.

Replaced with two lists and a simple Equals check, which is much faster.

Fixes #19737

(cherry picked from commit 7c9fc8acfa4fc36131ba07bc6c52b83b3fae439f)

### CODE REVIEW

**Comment by roji** [comment]
Description
When some operators (e.g. Where) are composed over a deep, self-referencing LINQ query tree, hashcode calculation can make translation time exponential and make compilation grind to a halt.

Customer Impact
Query compilation can hang for extremely long times before even sending a SQL query to the database.

How found
Reported by a customer.

Test coverage
Perf issue, only produced by some specific operators (e.g. Where) composed over a deep, self-referencing query tree.

Regression?
Not known.

Risk
Low. Controlled, pointed change to a simple expression visitor which replaces nodes in the tree.

**Comment by ajcvickers** [comment]
@roji Can you "quirk" the fix. That is, put the change behind an `AppContext.TryGetSwitch" like Smit has done here: https://github.com/dotnet/efcore/pull/19871/files#diff-baecacd4cd9354c21b22e390097a8d79R511

The new behavior should be enabled by default. When the quirk switch is set, then we should revert to the pre-patch behavior. This allows customers to switch back to the old behavior if we accidentally broke something. These switches never make it into master--they are specifically there for the patches only.

**Comment by roji** [comment]
@ajcvickers done, though this is a bit more complicated then just one condition. Tested that with and without quirks things work as expected, but would be good to get another pair of eyes.

File: src/EFCore/Query/ReplacingExpressionVisitor.cs [hunk 1]
```diff
@@ -14,20 +15,41 @@ public class ReplacingExpressionVisitor : ExpressionVisitor
...
         public static Expression Replace(Expression original, Expression replacement, Expression tree)
         {
             return new ReplacingExpressionVisitor(new[] { original }, new[] { replacement }).Visit(tree);
         }
 
         public ReplacingExpressionVisitor(Expression[] originals, Expression[] replacements)
         {
-            _originals = originals;
-            _replacements = replacements;
+            if (AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue19737", out var isEnabled) && isEnabled)
```
Comment (smitpatel) [inline src/EFCore/Query/ReplacingExpressionVisitor.cs]: Should store this in a field.

Comment (roji) [reply src/EFCore/Query/ReplacingExpressionVisitor.cs]: Thanks, done. Should do the same in https://github.com/dotnet/efcore/pull/19871/files#diff-baecacd4cd9354c21b22e390097a8d79R511?

Comment (smitpatel) [reply src/EFCore/Query/ReplacingExpressionVisitor.cs]: low value since used at only one place 😛 
But if @AndriySvyryd agrees, you can add commit on that PR.

Comment (AndriySvyryd) [reply src/EFCore/Query/ReplacingExpressionVisitor.cs]: That path isn't hot enough to warrant this

**Comment by ajcvickers** [comment]
@roji Can you create an issue to add this scenario to the perf tests? We should then have some coverage that this doesn't regress.

**Comment by roji** [comment]
I was just thinking that, opened #19908.

**Comment by ajcvickers** [comment]
@roji @smitpatel Approved by Tactics and branches are open; let's try to get this merged ~~today~~ ASAP since it's already night for you. Not that that seems to matter. ;-)
