### PR TITLE
Fix to #20322 - Print Switch in expression tree

### LINKED ISSUE #20322: Print Switch in expression tree
Our ExpressionPrinter ignores it and print string representation of it.
Sample output
```
switch (discriminator) { ... }
```
highly useful :trollface:

### PR DESCRIPTION
**Pull request by maumar**
Adding proper handling for SwitchExpresions.

Resolves #20322

### CODE REVIEW

File: src/EFCore/Query/ExpressionPrinter.cs [hunk 1]
```diff
@@ -928,6 +932,48 @@ protected override Expression VisitTypeBinary(TypeBinaryExpression typeBinaryExp
...
+            foreach (var @case in switchExpression.Cases)
+            {
+                foreach (var testValue in @case.TestValues)
+                {
+                    _stringBuilder.Append("case ");
+                    Visit(testValue);
+                    _stringBuilder.AppendLine(": ");
+                }
+
+                using (var indent = _stringBuilder.Indent())
```
Comment (smitpatel) [inline src/EFCore/Query/ExpressionPrinter.cs]: Can remove the variable indent. It should work without putting the value in variable.

File: test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs [hunk 2]
```diff
@@ -3,6 +3,7 @@
 
 using System;
 using System.Collections.Generic;
+using System.Diagnostics;
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs]: Remove
