### PR TITLE
Fix ESCAPE clause for Azure Synapse.

### LINKED ISSUE #33555: StartsWith/EndsWith/Contains with parameter fails on Azure Synapse because ESCAPE isn't supported there
I am using Microsoft.EntityFrameworkCore.SqlServer v8.0.4 to run queries against an Azure Synapse SQL database.  The SQL generated for a parameter used as the pattern for StartsWith/EndsWith/Contains automagically gets rewritten to escape any wildchars.

However, the LIKE keyword's `ESCAPE` clause syntax is not supported by Azure Synapse:  [LIKE (Transact-SQL) - SQL Server](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=azure-sqldw-latest#syntax)

Is there a way to suppress the generation of the `ESCAPE` clause?

Repro:

```csharp
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var s = "foo";
_ = await ctx.Blogs.Where(b => b.Name.Contains(s)).ToListAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\MSSQLLocalDB; Database=test; Trusted_Connection=True;")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

This produces the following query:

```sql
Executed DbCommand (84ms) [Parameters=[@__s_0_contains='%foo%' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SELECT [b].[Id], [b].[Name]
FROM [Blogs] AS [b]
WHERE [b].[Name] LIKE @__s_0_contains ESCAPE N'\'
```

Azure Synapse would be fine with the generated SQL if it did not include `ESCAPE N'\'`

NOTE:  I am greatly indebted to @roji for #32432    😄

### PR DESCRIPTION
**Pull request by cincuranet**
Fixes #33555

### CODE REVIEW

**Review by roji — CHANGES_REQUESTED** [review]
This looks like it just omits the ESCAPE clause for Synapse; doesn't that mean that bad results would be returned? In other words, the ESCAPE isn't needed to get the correct results, why do we have it there in the first place?

I think the fix needed here is to vary our **translation** for Synapse, translating to correct (but inferior) SQL which doesn't depend on LIKE+ESCAPE. You can look at pre-8.0 EF to see what we were doing (as this is a regression in 8.0).

File: test/EFCore.SqlServer.FunctionalTests/Query/NonSharedAzureSynapseQuerySqlServerTest.cs [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+        => TestSqlLoggerFactory.AssertBaseline(expected);
+
+    [ConditionalTheory]
+    [MemberData(nameof(IsAsyncData))]
+    public virtual async Task No_like_escape_StartsWith(bool async)
+    {
+        var contextFactory = await InitializeAsync<NoEscapeContext>();
+        using var context = contextFactory.CreateContext();
+
+        var foo = "aaa";
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/NonSharedAzureSynapseQuerySqlServerTest.cs:32]: Try putting an actual wildcard here (e.g. `%`) - the test should fail.

**Comment by cincuranet** [comment]
I took the previous translation and put it into `TryTranslateStartsEndsWithContainsOldStyle` (and downstream). No major refactoring or anything like that, because I don't want to introduce bugs.

**Review by roji — CHANGES_REQUESTED** [review]
If I look at the existing TryTranslateStartsEndsWithContains, doesn't the default case ("The pattern is a column or a complex expression") already contain exactly the logic we need? Any particular reason to duplicate the entire function for Synapse, rather than just jump to that case whenever we're on Synapse and would need to use ESCAPE? I don't really see any risk problem here...

**Comment by cincuranet** [comment]
Now it's using the code from the original `default` case, but also has some optimizations based on the fact that for a constant pattern we can omit some checks.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs [hunk 2]
```diff
@@ -295,30 +295,35 @@ bool TryTranslateStartsEndsWithContains(
...
-                                _sqlExpressionFactory.Constant(
-                                    methodType switch
-                                    {
-                                        StartsEndsWithContains.StartsWith => s + '%',
-                                        StartsEndsWithContains.EndsWith => '%' + s,
-                                        StartsEndsWithContains.Contains => $"%{s}%",
-
-                                        _ => throw new ArgumentOutOfRangeException(nameof(methodType), methodType, null)
-                                    })),
+                        string s when !s.Any(IsLikeWildChar) => _sqlExpressionFactory.Like(
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs:298]: nit: move `=>` to the next line

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs [hunk 3]
```diff
@@ -354,61 +362,78 @@ when patternParameter.Name.StartsWith(QueryCompilationContext.QueryParameterPref
...
+                                        nullable: true,
+                                        argumentsPropagateNullability: new[] { true, true },
+                                        typeof(int)),
+                                    _sqlExpressionFactory.Constant(0))),
+
+                    // For Contains, just use CHARINDEX and check if the result is greater than 0.
+                    // Add a check to return null when the pattern is an empty string (and the string isn't null)
+                    StartsEndsWithContains.Contains
+                        => _sqlExpressionFactory.AndAlso(
+                            _sqlExpressionFactory.IsNotNull(translatedInstance),
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs:419]: Most of this is duplicated - extract out the common code and only compose the additional Like on it as needed with an if (so this switch expression would become a switch statement, I think).

**Review by roji — CHANGES_REQUESTED** [review]
LGTM, see mostly nits

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs (hunk 2 above)
Comment (cincuranet) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs:298]: What are the rules? For example the cases above all start on the same line.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs (hunk 3 above)
Comment (cincuranet) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs:419]: What _additional Like_ are you talking about?

Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs:419]: This case (Contains without patternIsNonEmptyConstantString) - returns the exact same expression tree as the above case (Contains with patternIsNonEmptyConstantString), except that it adds the Like on top, no?

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs (hunk 2 above)
Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs:298]: Probably the rules are a bit hazy... I generally tend to do single-line if the whole thing fits on a single line, but when it's multi-line as in this case, putting the Like here makes the indentation harder to follow for the next lines... if you move the `=> (` to the next line, it's one readable block with the standard increasing indentation as you go in, rather than with `_sqlExpressionFactory.Like` much more inside/ahead than the following lines.

Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs:298]: That's just nits, if you're against it can leave as-is.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs (hunk 3 above)
Comment (cincuranet) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs:420]: Nope. Also the not null check for `translatedPattern` is not inside there and hence also the `AndAlso` is not there. Only thing that might make sense to extract is the `GreaterThan` with `CHARINDEX`. Do you want at least this piece extracted?

Comment (cincuranet) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs:420]: Hmm, it is somewhat nicer with the `GreaterThan` with `CHARINDEX` extracted. I'll leave it there and let's see what you think.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs [hunk 4]
```diff
@@ -421,20 +414,26 @@ StartsEndsWithContains.Contains when patternIsNonEmptyConstantString
...
                                     _sqlExpressionFactory.Like(
                                         translatedPattern,
                                         _sqlExpressionFactory.Constant(string.Empty, stringTypeMapping))))),
 
                     _ => throw new UnreachableException()
                 };
+
+                SqlExpression CharIndexGreaterThanZero()
+                {
+                    return
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs:427]: nit: expression-bodied

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs (hunk 3 above)
Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs:413]: My bad, I didn't look carefully enough.. Looks good to me as-is - whatever you prefer here.

**Review by roji — APPROVED** [review]

File: test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQueryAzureSynapseTest.cs [hunk 5]
```diff
@@ -0,0 +1,599 @@
...
+namespace Microsoft.EntityFrameworkCore.Query;
+
+#nullable disable
+
+public class FunkyDataQueryAzureSynapseTest : FunkyDataQuerySqlServerBaseTest<FunkyDataQueryAzureSynapseTest.FunkyDataQueryAzureSynapseFixture>
+{
+    public FunkyDataQueryAzureSynapseTest(FunkyDataQueryAzureSynapseFixture fixture, ITestOutputHelper testOutputHelper)
+        : base(fixture, testOutputHelper)
+    {
+    }
```
Comment (AndriySvyryd) [inline test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQueryAzureSynapseTest.cs:13]: Use a different `StoreName` for these, otherwise initialization becomes a race condition: https://dev.azure.com/dnceng-public/public/_build/results?buildId=784149&view=ms.vss-test-web.build-test-results-tab

Comment (AndriySvyryd) [reply test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQueryAzureSynapseTest.cs:13]: Also add a condition so these tests only run when targeting AzureSynapse, see `SqlServerCondition.IsSqlAzure`

Comment (cincuranet) [reply test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQueryAzureSynapseTest.cs:13]: #34506

Comment (roji) [reply test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQueryAzureSynapseTest.cs:13]: Good catch with the store name...

We don't ever actually run our tests against Synapse, and even though we would in an ideal world, I'm not sure that's going to happen in the near future... In the meantime, this at least allows us to assert on SQL baselines for cases that we know are problematic...
