### PR TITLE
Fix to #35007 - EF Core fails to translate LINQ query to SQL if JOIN contains multiple columns

### LINKED ISSUE #35007: EF Core fails to translate LINQ query to SQL if JOIN contains multiple columns
## File a bug

EF Core fails to translate LINQ query to SQL if JOIN contains multiple columns.

### Include your code

LINQ that fails:

```csharp
var query = dbContext
            .Set<RestrictionOriginator>()
            .AsNoTracking()
            .Join(dbContext.Set<Tenant>(), x => x.TenantId, x => x.Id, (originator, tenant) => new
            {
                originator,
                tenant
            })
            .GroupJoin(dbContext.Set<RestrictionOriginatorCountInProperty>(),
                x => new { x.originator.TenantId, x.originator.OriginatorId },
                x => new { x.TenantId, x.OriginatorId },
                (x, counts) => new
                {
                    x.originator.Id,
                    x.originator.OriginatorId,
                    x.originator.TenantId,
                    x.tenant.Name,
                    // ReSharper disable PossibleMultipleEnumeration
                    RestrictionsCount = counts.Sum(c => c.EntitiesCount),
                    RestrictionDaysCount = counts.Sum(c => c.DaysCount)
                    // ReSharper restore PossibleMultipleEnumeration
                })
            .ToQueryString();
```

If I rewrite it a bit then it is translated successfully:

```csharp
        var query = dbContext
            .Set<RestrictionOriginator>()
            .AsNoTracking()
            .Join(dbContext.Set<Tenant>(), x => x.TenantId, x => x.Id, (originator, tenant) => new
            {
                originator,
                tenant
            })
            .GroupJoin(dbContext.Set<RestrictionOriginatorCountInProperty>(),
                x => x.tenant.Id,
                x => x.TenantId,
                (x, counts) => new
                {
                    x.originator.Id,
                    x.originator.OriginatorId,
                    x.originator.TenantId,
                    x.tenant.Name,
                    // ReSharper disable PossibleMultipleEnumeration
                    RestrictionsCount = counts.Where(c => c.OriginatorId == x.originator.OriginatorId).Sum(c => c.EntitiesCount),
                    RestrictionDaysCount = counts.Where(c => c.OriginatorId == x.originator.OriginatorId).Sum(c => c.DaysCount)
                    // ReSharper restore PossibleMultipleEnumeration
                })
            .ToQueryString();
```

then generated SQL is

```sql
SELECT r."Id", r."OriginatorId", r."TenantId", t."Name", (
    SELECT COALESCE(sum(r0."EntitiesCount"), 0.0)::bigint
    FROM "RateManager"."RestrictionOriginatorCountInProperty" AS r0
    WHERE t."Id" = r0."TenantId" AND r0."OriginatorId" = r."OriginatorId") AS "RestrictionsCount", (
    SELECT COALESCE(sum(r1."DaysCount"), 0.0)::bigint
    FROM "RateManager"."RestrictionOriginatorCountInProperty" AS r1
    WHERE t."Id" = r1."TenantId" AND r1."OriginatorId" = r."OriginatorId") AS "RestrictionDaysCount"
FROM "RateManager"."RestrictionOriginator" AS r
INNER JOIN "RateManager"."Tenant" AS t ON r."TenantId" = t."Id"
```

### Include stack traces

```
System.InvalidOperationException
The LINQ expression 'DbSet<RestrictionOriginatorCountInProperty>()
    .Where(r0 => !(object.Equals(
        objA: new { 
            TenantId = StructuralTypeShaperExpression: 
                AboveCloud.RateManager.Restrictions.Originators.RestrictionOriginator
                ValueBufferExpression: 
                    ProjectionBindingExpression: Outer
                IsNullable: False
            .TenantId, 
            OriginatorId = StructuralTypeShaperExpression: 
                AboveCloud.RateManager.Restrictions.Originators.RestrictionOriginator
                ValueBufferExpression: 
                    ProjectionBindingExpression: Outer
                IsNullable: False
            .OriginatorId
         }, 
        objB: null)) && object.Equals(
        objA: new { 
            TenantId = StructuralTypeShaperExpression: 
                AboveCloud.RateManager.Restrictions.Originators.RestrictionOriginator
                ValueBufferExpression: 
                    ProjectionBindingExpression: Outer
                IsNullable: False
            .TenantId, 
            OriginatorId = StructuralTypeShaperExpression: 
                AboveCloud.RateManager.Restrictions.Originators.RestrictionOriginator
                ValueBufferExpression: 
                    ProjectionBindingExpression: Outer
                IsNullable: False
            .OriginatorId
         }, 
        objB: new { 
            TenantId = r0.TenantId, 
            OriginatorId = r0.OriginatorId
         }))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Query.Internal.NpgsqlSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateProjection(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(IQueryable source)
```

### Include provider and version information

EF Core version: 8.0.6.0
Database provider: (e.g. Npgsql.EntitiFrameworkCore.PostgreSQL)
Target framework: (e.g. .NET 8.0)
Operating system: 10.0.19045.0
IDE: Rider 2024.2.5

### PR DESCRIPTION
**Pull request by maumar**
Problem was in the GroupJoinConvertingExpressionVisitor where we convert GroupJoin key selectors into the correlation predicate for result selector subqueries. We blindly copy them over and in case of composite key selectors which fail to translate later in the pipeline (can't translate equals on anonymous object that is not a constant). Normally when processing regular joins we have logic that breaks up anonymous objects into constituent parts and compare them one by one instead (CreateJoinPredicate). However by the time we get to the translation we are dealing with a subquery with a Where predicate - we don't know at that point that it came from GroupJoin.

Fix is to tweak the logic in GroupJoinConvertingExpressionVisitor to break apart anonymous objects, like we do in CreateJoinPredicate

Fixes #35007

### CODE REVIEW

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 1]
```diff
@@ -753,17 +754,52 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
-                            outerKeySelector.Body,
-                            Expression.Constant(null),
-                            negated: true),
-                        ExpressionExtensions.CreateEqualsExpression(
-                            outerKeySelector.Body,
-                            innerKeySelector.Body)));
+                Expression correlationPredicate;
+                if (outerKeySelector.Body is NewExpression { Arguments: ReadOnlyCollection<Expression> outerArguments }
+                    && innerKeySelector.Body is NewExpression { Arguments: ReadOnlyCollection<Expression> innerArguments }
+                    && outerArguments.Count == innerArguments.Count
```
Comment (roji) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs:760]: If the argument counter is different, then the equality will always fail - so we could just have a false predicate. Similarly, if the count is 0, the equality will always succeed and we could have a true predicate.

Though since I think this code will probably go away (see review), we don't necessarily have to go the extra mile here.

**Review by roji — APPROVED** [review]
> which fail to translate later in the pipeline (can't translate equals on anonymous object that is not a constant).

Wow, I was just doing a very deep dive into NewExpression handling as part of #35038!

My current thinking is that we should actually "translate" NewExpression in RelationalSqlTranslatingExpressionVisitor, including when it's not a constant. Of course, there's no actual SQL translation to NewExpression, but then we support StructuralTypeShaperExpression RelationalSqlTranslatingExpressionVisitor (so that we can bind properties on it) - so we already support handling non-SQL expression types in that visitor. This would allow us to:
* Cleanly handle member access over NewExpression in RelationalSqlTranslatingExpressionVisitor, without any hacks (this is currently simplified away in... ReplacingExpressionVisitor...)
* Not have special handling logic for NewExpression in RelationalProjectionBindingExpressionVisitor (for `Select(b => new { })`), in TranslateGroupBy (for `GroupBy(b => new { })`)
* Go in the direction of allowing users to express row value syntax `(a,b) > (1,2)` via anonymous objects (#26822).
* Support equality of NewExpression (`Where(b => new { b.X, b.Y } == new { c.X, c.Y }`). I don't think it's a specific goal to specifically support this somewhat convoluted syntax (though it's valid); but it should allow handling the GroupJoin problem in this issue without the special handling you're adding.

In any case, that's all thoughts and plans - I think it's fine to merge this, and then if all goes well I'll remove the code when I add support for NewExpression comparison.
