### PR TITLE
[6.0] Fix to #26084 - Query: SqlExpressionFactory doesn't apply type mapping to InExpression

### LINKED ISSUE #26084: Query: SqlExpressionFactory doesn't apply type mapping to InExpression
I have an enum and an extension method like this:

```csharp
public enum State { None = 0, Foo = 1, Bar = 2, Baz = 3, ... };
public static bool IsValidState(this State state) => state == State.Foo || state == State.Bar;
```
I'd like to map this extension method to be able to use it in Linq queries. Basically, I'd like this :
```csharp
.Where(e => e.State.IsValidState())
```
to be translated to the following SQL :
```sql
WHERE [e].[State] IN (1, 2)
```

I tried this:

```csharp
            var validStates = new[] { State.Bar, State.Baz };
            modelBuilder.HasDbFunction(() => State.None.IsValidState())
                .HasTranslation(args => new InExpression(
                    args.First(),
                    new SqlConstantExpression(Expression.Constant(validStates), args.First().TypeMapping),
                    negated: false,
                    typeMapping: null));
```

But I still get an error saying the query can't be translated. I suspect it's because I didn't specify a type mapping, but I don't know what type mapping to provide.

How to do this?

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows
IDE: JetBrains Rider

### PR DESCRIPTION
**Pull request by maumar**
We were not applying mapping to InExpression and it's constituents which could lead to failed translations when these expressions were constructed manually (e.g. as part of UDF translation)

Fixes #26084

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlExpressionFactory.cs [hunk 1]
```diff
@@ -232,6 +233,30 @@ private SqlExpression ApplyTypeMappingOnLike(LikeExpression likeExpression)
...
+            if (inExpression.Values != null)
+            {
+                var values = ApplyTypeMapping(inExpression.Values, itemTypeMapping);
+
+                return item != inExpression.Item || values != inExpression.Values || inExpression.TypeMapping != _boolTypeMapping
+                    ? new InExpression(item, values, inExpression.IsNegated, _boolTypeMapping)
+                    : inExpression;
+            }
+
+            return item != inExpression.Item || inExpression.TypeMapping != _boolTypeMapping
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressionFactory.cs:255]: do we need to do something about subquery case? Or will Select always have proper mappings? (since the ctor is not public) @smitpatel

File: src/EFCore.Relational/Query/SqlExpressionFactory.cs [hunk 2]
```diff
@@ -232,6 +233,30 @@ private SqlExpression ApplyTypeMappingOnLike(LikeExpression likeExpression)
                 resultTypeMapping);
         }
 
+        private SqlExpression ApplyTypeMappingOnIn(InExpression inExpression)
+        {
+            var itemTypeMapping = (inExpression.Values != null
+                ? ExpressionExtensions.InferTypeMapping(inExpression.Item, inExpression.Values)
+                : inExpression.Subquery != null
+                    ? ExpressionExtensions.InferTypeMapping(inExpression.Item, inExpression.Subquery.Projection.Single().Expression)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionFactory.cs:241]: use 0 index

File: src/EFCore.Relational/Query/SqlExpressionFactory.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressionFactory.cs:255]: Select should be fine.

**Review by smitpatel — APPROVED** [review]

**Comment by maumar** [comment]
@Pilchie for approval into 6.0 - low risk, low impact issue

**Comment by Pilchie** [comment]
Approved for EFCore 6.0
