### PR TITLE
Fixes around scaffolding collations

### LINKED ISSUE #25418: Database collation is scaffolded as a raw annotation and not with the Fluent API
We currently get:

```c#
modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");
```

... instead of:

```c#
modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");
```

Raised in #25404

### LINKED ISSUE #25419: Database collation is always scaffolded, even when it is the server collation (default)
We shouldn't scaffold the database collation when it's equal to the server collation (which is determined by the machine on which SQL Server is installed).

Raised in #25404

### PR DESCRIPTION
**Pull request by roji**
* Database-level collation is scaffolded to the Fluent API call, instead of to a raw annotation.
* Don't scaffold database collation when it is identical to the server collation (i.e. is the default).

Fixes #25418
Fixes #25419

Note that we have a test the the database collation isn't scaffolded when it's the default, but no coverage for when it's different, since our DatabaseModelFactoryTest tests don't create new databases. I've manually verified this works.

### CODE REVIEW

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 1]
```diff
@@ -131,7 +131,13 @@ public override DatabaseModel Create(DbConnection connection, DatabaseModelFacto
 
                 databaseModel.DatabaseName = connection.Database;
                 databaseModel.DefaultSchema = GetDefaultSchema(connection);
-                databaseModel.Collation = GetCollation(connection);
+
+                var serverCollation = GetServerCollation(connection);
+                var databaseCollation = GetDatabaseCollation(connection);
+                if (databaseCollation is not null && databaseCollation != serverCollation)
+                {
+                    databaseModel.Collation = GetDatabaseCollation(connection);
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:139]: Duplicate database call to get collation?

Comment (roji) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:139]: Oops, bad copy-pasta, thanks...

**Review by bricelam — APPROVED** [review]
