### PR TITLE
Fix to #12657 - Query: logic protecting SUM from returning null doesn't work for complex scenarios

### LINKED ISSUE #12657: Query: logic protecting SUM from returning null doesn't work for complex scenarios
query:

```cs
from c in cs
select new
{
   Sum = c.Orders.Sum(o => o.OrderID) + 1
}
```

throws:
Nullable object must have a value.

query plan:
```
(QueryContext queryContext) => IAsyncEnumerable<<>f__AnonymousType225<int>> _InterceptExceptions(
|__ source: IAsyncEnumerable<<>f__AnonymousType225<int>> _ShapedQuery(
|   |__ queryContext: queryContext, 
|   |__ shaperCommandContext: SelectExpression: 
|   |       SELECT (
|   |           SELECT SUM([o].[OrderID])
|   |           FROM [Orders] AS [o]
|   |           WHERE [c].[CustomerID] = [o].[CustomerID]
|   |       ) + 1 AS [Sum]
|   |       FROM [Customers] AS [c], 
|   |__ shaper: (QueryContext queryContext | ValueBuffer c) => new { (int)Nullable<int> TryReadValue(c, 0, null) }), 
|__ contextType: TestModels.Northwind.NorthwindRelationalContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: Unhandled parameter: queryContext)
```

instead we should generate coalesce 0 as well:

```
(QueryContext queryContext) => IAsyncEnumerable<<>f__AnonymousType225<int>> _InterceptExceptions(
|__ source: IAsyncEnumerable<<>f__AnonymousType225<int>> _ShapedQuery(
|   |__ queryContext: queryContext, 
|   |__ shaperCommandContext: SelectExpression: 
|   |       SELECT (
|   |           SELECT SUM([o].[OrderID])
|   |           FROM [Orders] AS [o]
|   |           WHERE [c].[CustomerID] = [o].[CustomerID]
|   |       ) + 1 AS [Sum]
|   |       FROM [Customers] AS [c], 
|   |__ shaper: (QueryContext queryContext | ValueBuffer c) => new { (int)Nullable<int> TryReadValue(c, 0, null) ?? default(int) }), 
|__ contextType: TestModels.Northwind.NorthwindRelationalContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: Unhandled parameter: queryContext)
```

### PR DESCRIPTION
**Pull request by maumar**
Adding COALESCE around SUM sql function expression

Fixes #12657

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlNullabilityProcessor.cs [hunk 1]
```diff
@@ -918,8 +918,13 @@ SqlExpression AddNullConcatenationProtection(SqlExpression argument, RelationalT
                 arguments[i] = Visit(sqlFunctionExpression.Arguments[i], out _);
             }
 
-
-            return sqlFunctionExpression.Update(instance, arguments);
+            return sqlFunctionExpression.IsBuiltIn
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlNullabilityProcessor.cs:921]: I'm on the fence here - we do provide Sum translation into SqlFunction "SUM" in relational, but if there is a provider that translates it to a different function it would have to rewrite the entire visit sql function method, so that SUM doesn't get coalesce wrapped around it incorrectly. thoughts? @roji @smitpatel

File: test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs [hunk 2]
```diff
@@ -975,7 +975,7 @@ public override async Task Result_operator_nav_prop_reference_optional_Sum(bool
             await base.Result_operator_nav_prop_reference_optional_Sum(async);
 
             AssertSql(
-                @"SELECT SUM([l0].[Level1_Required_Id])
+                @"SELECT COALESCE(SUM([l0].[Level1_Required_Id]), 0)
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs:978]: I might try a more sophisticated logic, so that we don't put COALESCE for every sum - i think we only need it for subquery scenarios, but will investigate. Thoughts?

File: src/EFCore.Relational/Query/SqlNullabilityProcessor.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlNullabilityProcessor.cs:921]: For best solution it would be good to put at translation of sum but there is going to be some refactoring coming in when implementing more group by operation and #20633 may be needed for it.

I think this is ok compromise for now, it may not be the best solution but avoids wrong results for customers.

Comment (roji) [reply src/EFCore.Relational/Query/SqlNullabilityProcessor.cs:921]: Of a provider translates to different function, wouldn't they just be responsible for applying the same coalscing in their own nullability processor?
