### PR TITLE
Take min/max batch size into account again for seeding

### LINKED ISSUE #28876: Seeding no longer takes max batch size into account
Adding >1000 rows of seed data to a single entity generates a migration that fails. Should the resulting migration be splitting inserts into batches of 1000 records?:
```using Microsoft.EntityFrameworkCore;

using var test = new BloggingContext();
await test.Database.MigrateAsync();

class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; } = null!;

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlServer(@"Server=localhost,53133;Database=EFTest;Trusted_Connection=True;Encrypt=false;MultipleActiveResultSets=true;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var blogs = Enumerable.Range(1, 1001)
            .Select(x => new Blog(x));

        modelBuilder.Entity<Blog>()
            .HasData(blogs);
    }
}

record Blog(int BlogId);
```

```
Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): The number of row value expressions in the INSERT statement exceeds the maximum allowed number of 1000 row values.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\xxxxx\source\repos\EFTest\Program.cs:line 4
   at Program.<Main>(String[] args)
ClientConnectionId:
Error Number:10738,State:1,Class:15
```

EF Core version: 7.0.0-preview.7.22376.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows
IDE: None (command line)

### PR DESCRIPTION
**Pull request by roji**
Made MigrationsModelDiffer.GetDataOperations pass through our normal batching logic again, by splitting CommandBatchPreparer.BatchCommands to allow the logic to be called without IUpdateEntries.

On a side note, I was surprised to see we actually have seeding-specific logic for bulk insert... Seeding isn't supposed to be high-perf, and we specifically discourage having a large number of rows (e.g. huge context snapshots), which is where bulk inserting makes the most sense... I'd consider removing it altogether, to simplify the code and avoid bugs (like this one).

Fixes #28876

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
Weren't you able to split the  batches in `MigrationsSqlGenerator.GenerateModificationCommands`? We do want the data operations to be in one "batch" in the migration for readability

**Comment by roji** [comment]
Sorry, didn't have that in mind when implementing - I agree it's better (and doesn't bake the max batch size into the scaffolded migrations).

Though note that we don't "batch" updates/deletes in the migration for readability, though we could pretty easily do the same we're doing there for inserts. Let me know if you want me to do that.

**Comment by AndriySvyryd** [comment]
> Though note that we don't "batch" updates/deletes in the migration for readability, though we could pretty easily do the same we're doing there for inserts. Let me know if you want me to do that.

I'm not sure about updates, since they could be very different in shape, but we should definitely do it for deletes. However, it's better to file an issue to do it later since batch deletion would be a lot less common than batch insert in seeding.

**Comment by roji** [comment]
> However, it's better to file an issue to do it later since batch deletion would be a lot less common than batch insert in seeding.

Not to be a troll, but every batch insert in Up means batch delete in Down :trollface: 

But of course it's true that Up actually gets used a lot more than Down.

#28956

File: src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs [hunk 1]
```diff
@@ -2190,17 +2190,11 @@ private void AddSeedData(IEntityType entityType, Dictionary<ITable, IRowIdentity
...
-                EntityState.Unchanged => false,
-                EntityState.Deleted => diffContext.FindDrop(r.Table!) == null,
-                _ => throw new InvalidOperationException($"Unexpected entity state: {r.EntityState}")
-            };
-        });
+        var commands = identityMaps.Values
+            .SelectMany(m => m.Rows)
+            .Where(
+                r => r.EntityState is EntityState.Added or EntityState.Modified
+                    || r.EntityState is EntityState.Deleted && diffContext.FindDrop(r.Table!) == null);
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs:2197]: We need some redundant parentheses here. 😉

File: src/EFCore.Relational/Update/ICommandBatchPreparer.cs [hunk 2]
```diff
@@ -34,4 +34,17 @@ public interface ICommandBatchPreparer
...
+    /// <summary>
+    ///     Given a set of modification commands, returns one more ready-to-execute batches for those commands, taking into account e.g.
+    ///     maximum batch sizes and other batching constraints.
+    /// </summary>
+    /// <param name="commandSet">The set of commands to be organized in batches.</param>
+    /// <param name="moreCommandSets">Whether more command sets are expected after this one within the same save operation.</param>
+    /// <param name="parameterNameGenerator">An optional parameter name generator.</param>
+    /// <returns>The list of batches to execute.</returns>
+    IEnumerable<ModificationCommandBatch> CreateCommandBatches(
+        List<IReadOnlyModificationCommand> commandSet,
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Update/ICommandBatchPreparer.cs:47]: I think this could be an `IEnumerable`

Comment (AndriySvyryd) [reply src/EFCore.Relational/Update/ICommandBatchPreparer.cs:47]: See https://github.com/dotnet/efcore/issues/19710#issuecomment-682186513

File: src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs [hunk 3]
```diff
@@ -70,91 +70,106 @@ public CommandBatchPreparer(CommandBatchPreparerDependencies dependencies)
...
         for (var commandSetIndex = 0; commandSetIndex < commandSets.Count; commandSetIndex++)
         {
-            var commandSet = commandSets[commandSetIndex];
+            var hasMoreCommandSets = commandSetIndex < commandSets.Count - 1;
 
-            var batch = Dependencies.ModificationCommandBatchFactory.Create();
-            foreach (var modificationCommand in commandSet)
+            foreach (var batch in CreateCommandBatches(commandSets[commandSetIndex], hasMoreCommandSets, parameterNameGenerator))
             {
-                (modificationCommand as ModificationCommand)?.AssertColumnsNotInitialized();
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs:78]: We should keep this assert, consider adding a private method with a corresponding `bool` parameter

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs (hunk 3 above)
Comment (roji) [reply src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs:78]: I guess we could just iterate over all the commands above in BatchCommands and assert this (when calling into CreateCommandBatches from the seeding path, columns are already calculated). Does that sound ok, or do you have something better in mind?

Comment (AndriySvyryd) [reply src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs:78]: I was thinking about factoring out a method with a corresponding bool parameter that indicates whether to assert to avoid double enumeration

Comment (roji) [reply src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs:78]: Am not getting it :sweat_smile: Let's chat later today.

(the double enumeration would only be in DEBUG and the command set is List, so it seems very unlikely to impact test performance in a meaningful way)
