### PR TITLE
Fix to #34211 - Issue occurs when trying to generate query string when mapping entity with json to a view with a custom schema

### LINKED ISSUE #34211: Issue occurs when trying to generate query string when mapping entity with json to a view with a custom schema
**Description**: Issue occurs when trying to generate query string. We are trying to generate query based on `OwnsMany` relationship on JSON column. Data is consumed through view. If everything is in the default DB schema it works fine. However, if view is in different DB schema then exception occurs. 

**Note**: Undesirable workaround is to use `modelBuilder.HasDefaultSchema("Catalog")` as this functionality seems to be working only in default DB schema.

**Repro**:

1. Create Database
2. Create Catalog schema
3. You may create table - but as query is not executed, it is not necessary
4. Execute following code:

```c#

public class ApplicationDbContext(string connectionString) : DbContext
{
    public DbSet<Item> ItemsView => Set<Item>();

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlServer(connectionString);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Item>()
            .ToView(nameof(ItemsView), "Catalog");
        
        modelBuilder.Entity<Item>()
            .OwnsMany(x => x.Locations, builder =>
            {
                builder.ToJson();
            });
        
        base.OnModelCreating(modelBuilder);
    }
}

public sealed class Item
{
    public Guid Id { get; private set; }
    public List<Location> Locations { get; private set; } = default!;

    public Item(List<Location> locations)
    {
        Locations = locations;
    }

    public Item()
    {
    }
}

public sealed class Location
{
    public string City { get; private set; } = default!;
    public string Address { get; private set; } = default!;

    public Location(string city, string address)
    {
        City = city;
        Address = address;
    }

    public Location()
    {
    }
}

var context = new ApplicationDbContext("Server=(localdb)\\MSSQLLocalDB;Database=issue-reproduce");

var queryItems = context.ItemsView;

Console.WriteLine($"Items query ({queryItems.ToQueryString()})");

var items = queryItems.ToList();

Console.WriteLine($"Total items ({items.Count})");


Console.ReadLine();


```

**Exception**:

```

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.AddJsonNavigationBindings(IEntityType entityType, StructuralTypeProjectionExpression projection, Dictionary`2 propertyExpressions, TableReferenceExpression tableReferenceExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.<.ctor>g__GenerateNonHierarchyNonSplittingEntityType|26_0(ITableBase table, TableExpressionBase tableExpression, <>c__DisplayClass26_0&)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression..ctor(IEntityType entityType, ISqlExpressionFactory sqlExpressionFactory)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressionFactory.Select(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.CreateShapedQueryExpression(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(IQueryable source)
   at Program.<Main>$(String[] args) in C:\dev\projects\EfCoreJsonSchemaIssue\Program.cs:line 8

```

**Expected**: Query string

**EF Core version:**
Database provider: `Microsoft.EntityFrameworkCore.SqlServer 8.0.7`
Target framework: `.NET 8.0`

### PR DESCRIPTION
**Pull request by maumar**
Problem was in database model processing. When then entity is mapped to json, and its owner is mapped to a view, we should map that entity to the same view as the owner. We have a logic that looks at the annotation on the entity first, and if that's not found, try to compute the view name and view schema based on the owner (or use defaults). We were computing the view name correctly, but there was a problem is schema computation. Logic was that if the entity is owned AND if that ownership is unique (i.e. 1-1 owned mapping) we could look for the parent's schema. However, we should also do this for 1-many ownership that is mapped to JSON.

Fix is to add the missing condition, to make it consistent with other places in the code.

Fixes #34211

### CODE REVIEW

File: src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs [hunk 1]
```diff
@@ -356,7 +356,7 @@ public static void SetViewName(this IMutableEntityType entityType, string? name)
     public static string? GetDefaultViewSchema(this IReadOnlyEntityType entityType)
     {
         var ownership = entityType.FindOwnership();
-        if (ownership is { IsUnique: true })
+        if (ownership != null && (ownership.IsUnique || entityType.IsMappedToJson()))
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs:359]: For `GetDefaultSchema` we don't even check that the ownership is unique, we should do the same here. Even for non-owned collections we should map to a view in the same schema (but with a different name)

**Review by AndriySvyryd — APPROVED** [review]

**Comment by SamMonoRT** [comment]
@maumar - failures seem related.

**Comment by maumar** [comment]
@SamMonoRT the test failures here are due to the fix itself. Scenario is a bit more complicated, will wait till @AndriySvyryd is back to discuss how to best approach it.

**Comment by SamMonoRT** [comment]
Ok, if the fix is complicated and risky, at this time I'll propose not taking for EF9.0 given the uncertainty.
