### PR TITLE
[6.0.2] Query: Defer inline-ing owned navigation expansion till all joins are generated

### LINKED ISSUE #26592: efcore6 produces wrong SELECT SQL when Where/OrderBy clauses are applied to Owned properties followed by .Take()
Hi everyone,

I found a bug in efcore6 that now produces an invalid SELECT statement when filtering/sorting on owned types stored on other tables.
In particular, the bug happens when **more than one** owned type is linked to an entity and the where clause is applied NOT to the last owned property, followed by a .Take() clause.

Can you please check this behavior? Thanks in advance!

### Example
A Company entity that can be either a Customer, a Supplier or both.
Additional Customer data and Supplier data are stored in separate tables with a 1..1 relationship with the Company table.
These tables are configured as Owned properties of Customer:

```C#
/// <summary>
/// Entity representing a company. 
/// A company can be either a customer, a supplier, or both.
/// If the company is a cutomer and/or a supplier, additional data describing customer/supplier is stored in
/// owned types CustomerData and SupplierData, stored in two separate tables with a 1..1 relationship with Company
/// </summary>
public class Company
{
    public int Id { get; set; }

    public string? Name { get; set; }
    public CustomerData? CustomerData { get; set; }
    public SupplierData? SupplierData { get; set; }
}

/// <summary>
/// Owned 1 of Company in 1..1 relationship, on another table
/// </summary>
public class CustomerData
{
    public int Id { get; set; }
    public string? AdditionalCustomerData { get; set; }

}

 /// <summary>
 /// Owned 2 of Company in 1..1 relationship, on another table
 /// </summary>
 public class SupplierData
 {
     public int Id { get; set; }
     public string? AdditionalSupplierData { get; set; }

 }
```

Mapping:

```C#
internal class CompanyMapping : IEntityTypeConfiguration<Company>
{
    public void Configure(EntityTypeBuilder<Company> builder)
    {
        builder.ToTable("Companies");

        builder.HasKey(r => r.Id);
        builder.Property(r=>r.Id).UseIdentityColumn();

        builder.OwnsOne(r => r.CustomerData,
            b =>
            {
                b.ToTable("CustomerData");

                b.HasKey(r => r.Id);

                b.WithOwner().HasForeignKey(r => r.Id).HasPrincipalKey(r => r.Id);
            });

        builder.OwnsOne(r => r.SupplierData,
            b =>
            {
                b.ToTable("SupplierData");

                b.HasKey(r => r.Id);

                b.WithOwner().HasForeignKey(r => r.Id).HasPrincipalKey(r => r.Id);
            });
    }
}
```

Executing the following query

```C#
var ctx = GetDbContext();

var q = ctx.Companies
        .Where(r => r.CustomerData != null)
        .Take(10);

var results = await q.ToArrayAsync();

```
will produce the following wrong SQL when using efcore6:
``` SQL
-- sql generated by efcore6 (wrong)
-- Columns of the first owned type are NOT included in the inner select, so they are not available in the outer select
-- A left join is also missing from the outer select
DECLARE @__p_0 int = 10;

SELECT[t].[Id], [t].[Name], [c0].[Id], [c0].[AdditionalCustomerData], [s].[Id], [s].[AdditionalSupplierData]
FROM(
    SELECT TOP(@__p_0)[c].[Id], [c].[Name]
    FROM[Companies] AS[c]
    LEFT JOIN[CustomerData] AS[c0] ON[c].[Id] = [c0].[Id]
    WHERE[c0].[Id] IS NOT NULL
) AS[t]
LEFT JOIN[SupplierData] AS[s] ON[t].[Id] = [s].[Id]

-- Error: The multi-part identifier "c0.AdditionalCustomerData" could not be bound.
```

the same query works as expected in efcore5, producing the following valid SQL:
``` SQL
-- sql generated by efcore5 (working)
DECLARE @__p_0 int = 10;

SELECT[t].[Id], [t].[Name], [t].[Id0], [t].[AdditionalCustomerData], [s0].[Id], [s0].[AdditionalSupplierData]
FROM(
    SELECT TOP(@__p_0)[c].[Id], [c].[Name], [c0].[Id] AS[Id0], [c0].[AdditionalCustomerData]
    FROM[Companies] AS[c]
    LEFT JOIN[CustomerData] AS[c0] ON[c].[Id] = [c0].[Id]
    WHERE[c0].[Id] IS NOT NULL
) AS[t]
LEFT JOIN[SupplierData] AS[s] ON[t].[Id] = [s].[Id]
LEFT JOIN[SupplierData] AS[s0] ON[t].[Id] = [s0].[Id]

```

## Attached solution

[EfCore6Bugs.zip](https://github.com/dotnet/efcore/files/7505549/EfCore6Bugs.zip)

The solution contains projects targeting .net5.0 with efcore 5.0.12 and .net6.0 with efcore 6.0.0.  
The first project contains the DbContext, the second one is a simple unit test.

On test initialization, an `EfCore6Bugs` database will be created on (LocalDb)\\MSSQLLocalDB (please customize the connection string in `TestDataContext.cs` as needed) applying migrations for the DbContext.
Unit tests should all be successful for .net5.0 (efcore5), while **EfCore6ClausesOnFirstOwnedFails** will fail for .net6.0 (efcore6)

### PR DESCRIPTION
**Pull request by smitpatel**
Issue: Expanding owned navigations in relational falls into 3 categories
- Collection navigation - which always generates a subquery. The predicate is generated in LINQ to allow mutation of outer SelectExpression
- Reference navigation sharing table - which picks column from same table without needing to add additional join. This only mutate the projection list for SelectExpression at subquery level
- Reference navigation mapped to separate table - which generates additional joins. Generating join can cause push down on outer SelectExpression if it has facets (e.g. limit/offset). This pushdown causes owned expansion from category 2 to be outdated and invalid SQL since they get pushed down to subquery. While their relevant entity projection is updated inside SelectExpression we already inlined older object in the tree at this point.

In order to avoid issue with outdated owned expansion, we defer actual inline-ing while processing owned navigations so that all navigations are expanded (causing any mutation on SelectExpression) before we inline values.

This PR introduces DeferredOwnedExpansionExpression which remembers the source projection binding to SelectExpression (which will remain accurate through pushdown), and navigation chain to traverse entity projections to reach entity shaper for final owned navigation. This way, we get up-to-date information from SelectExpression after all joins are generated.
We also find updated entity projection through binding after we generate a join if pushdown was required.

Resolves #26592

The issue was also present in 5.0 release causing non-performant SQL rather than invalid SQL. During 5.0 we expanded owned navigations again while during client eval phase (which happens in customer scenario due to include). This caused to earlier owned reference to have correct columns. Though the entity projection for owner was changed due to pushdown so we didn't add latter reference navigation binding in correct entity projection causing us to expand it again during 2nd pass.

The exact same issue doesn't occur for InMemory provider (due to slightly different implementation) though we should also make InMemory provider work this way, which we can do in 7.0.

**Description**

In a query if owned reference navigations mapped to separate tables are expanded at different time with a subquery causing operation in between (like skip/take/distinct), then the columns of already expanded reference navigation are incorrect.

**Customer impact**

Query with such scenario will generate invalid SQL causing an exception.

**How found**

Customer reported on 6.0 package.

**Regression**

Partially. If the query doesn't have any form of client eval then it fails in 5.0 with same error. If it has client eval then it translated in 5.0 with inefficient SQL.

**Testing**

Added test for the scenario. Also there are existing tests to validate expansion working correctly in usual cases.

**Risk**

Medium. This PR changes how owned navigations are expanded in relational layer. While we have good test coverage, this is still significant impact code path. We have added quirk in order to revert to previous behavior if any issue arises.

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 1]
```diff
@@ -1141,11 +1142,14 @@ private sealed class SharedTypeEntityExpandingExpressionVisitor : ExpressionVisi
...
             private static readonly MethodInfo _objectEqualsMethodInfo
                 = typeof(object).GetRequiredRuntimeMethod(nameof(object.Equals), typeof(object), typeof(object));
+            private static readonly bool _useOldBehavior = AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue26592", out var enabled)
+                && enabled;
 
             private readonly RelationalSqlTranslatingExpressionVisitor _sqlTranslator;
             private readonly ISqlExpressionFactory _sqlExpressionFactory;
 
             private SelectExpression _selectExpression;
+            private DeferredOwnedExpansionRemovingVisitor _visitor;
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1152]: nit: deferredOwnedExpansionRemover

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 2]
```diff
@@ -1208,179 +1212,459 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
+                                || _selectExpression.IsDistinct
+                                || _selectExpression.GroupBy.Count > 0;
+                            _selectExpression.AddLeftJoin(innerSelectExpression, joinPredicate);
+
+                            // If pushdown was required on SelectExpression then we need to fetch the updated entity projection
+                            if (pushdownRequired)
+                            {
+                                if (doee is not null)
+                                {
+                                    entityShaperExpression = _visitor.UnwrapDeferredEntityProjectionExpression(doee);
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1552]: this nested codepath is not hit by any of our tests

Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1552]: Will add test for it. It should happen when expanding 2 navigations on same level which are defined on owned entity itself so 2 levels deep.

Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs]: Added test covering this path.

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 3]
```diff
@@ -1208,179 +1212,459 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
+
+                        var correlationPredicate = Expression.Lambda(predicate, correlationPredicateParameter);
+
+                        return Expression.Call(
+                            QueryableMethods.Where.MakeGenericMethod(innerSequenceType),
+                            innerShapedQuery,
+                            Expression.Quote(correlationPredicate));
+                    }
+
+                    var entityProjectionExpression = GetEntityProjectionExpression(entityShaperExpression);
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1477]: Seems to be a refactor/cleanup? If so, maybe consider doing later in main, this could also make the scope of the quirk much smaller?

**Review by roji — COMMENTED** [review]
Here are some nits, I don't have enough grasp of this area to fully grok everything - but it seems to make sense to me.

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 4]
```diff
@@ -1141,11 +1142,14 @@ private sealed class SharedTypeEntityExpandingExpressionVisitor : ExpressionVisi
         {
             private static readonly MethodInfo _objectEqualsMethodInfo
                 = typeof(object).GetRequiredRuntimeMethod(nameof(object.Equals), typeof(object), typeof(object));
+            private static readonly bool _useOldBehavior = AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue26592", out var enabled)
```
[the remark this answers is not in the document]
Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1145]: temporary code in release branch, scoped inside a private class. Unless we add something else to patch inside this class, this is fine.

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 5]
```diff
@@ -1208,179 +1212,459 @@ protected override Expression VisitExtension(Expression extensionExpression)
 
             private Expression? TryExpand(Expression? source, MemberIdentity member)
             {
-                source = source.UnwrapTypeConversion(out var convertedType);
-                if (source is not EntityShaperExpression entityShaperExpression)
+                if (_useOldBehavior)
```
[the remark this answers is not in the document]
Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1215]: I tried the first way but there were multiple sites and certain variables which occur only in one path. I split with if so that it is also easier to see what is the final code and easier to merge to release.
https://github.com/dotnet/efcore/pull/26617/files?w=1 should remove old path indentation diff.

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs (hunk 3 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1477]: This is inside new code path only. Old code path keep things in same way.

**Comment by jamshedd** [comment]
Risk is M rather than low so fix in main and wait to see more reports.

**Comment by ChristopherHaws** [comment]
Is this really medium risk? This issue is going to probably require us to downgrade our application from .NET 6 to .NET 5. =/

**Review by AndriySvyryd — APPROVED** [review]
