### PR TITLE
Handle view mapping in ExecuteDelete/Update translation

### LINKED ISSUE #34677: ExecuteUpdate/Delete attempt to update the view, not the table
## File a bug

According to [the documentation](https://learn.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#view-mapping):

> Mapping to a view will remove the default table mapping, but the entity type can also be mapped to a table explicitly. In this case the query mapping will be used for queries and **the table mapping will be used for updates.**

However, ExecuteUpdate does not respect this - it updates the view, not the table.

### Include your code

Instructions:

- Add Microsoft.EntityFrameworkCore.Sqlite Nuget package
- Add Microsoft.EntityFrameworkCore.Tools Nuget package
- Paste the code below into Program.cs in a console application
- Run `add-migration InitialCreate` followed by `update-database`
- Run the application

```C#
using Microsoft.EntityFrameworkCore;


using var db = new BloggingContext();

db.Database.ExecuteSql($"CREATE VIEW IF NOT EXISTS BlogsView AS SELECT * FROM Blogs");

var blog = new Blog { Url = "http://blogs.msdn.com/adonet" };
db.Add(blog);
db.SaveChanges();

blog.Url = "http://blogs.msdn.com/adonet2";
db.SaveChanges(); // Updates the Blogs table

// The following attempts to update the BlogsView view, not the Blogs table as expected.
// In SqLite, this throws an exception because views can not be updated.
// In Sql Server, it might succeed depending on the definition of the view
db.Blogs.ExecuteUpdate(properties => properties.SetProperty(b => b.Url, "http://blogs.msdn.com/adonet3"));


public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    public string DbPath { get; }

    public BloggingContext()
    {
        var folder = Environment.SpecialFolder.LocalApplicationData;
        var path = Environment.GetFolderPath(folder);
        DbPath = System.IO.Path.Join(path, "blogging.db");
    }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlite($"Data Source={DbPath}");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>()
            .ToTable("Blogs")
            .ToView("BlogsView");
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; } = "";
}

```

### Include stack traces

When running this against SqLite, the following exception is generated:

```
Microsoft.Data.Sqlite.SqliteException
  HResult=0x80004005
  Message=SQLite Error 1: 'cannot modify BlogsView because it is a view'.
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__64.MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.<GetStatements>d__54.MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.<>c.<NonQueryResult>b__13_0(DbContext _, ValueTuple`3 state)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.NonQueryResult(RelationalQueryContext relationalQueryContext, RelationalCommandCache relationalCommandCache, Type contextType, CommandSource commandSource, Boolean threadSafetyChecksEnabled)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.ExecuteUpdate[TSource](IQueryable`1 source, Expression`1 setPropertyCalls)
   at Program.<Main>$(String[] args) in C:\.......\Program.cs:line 18
```

### Include provider and version information

EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqLite
Target framework: .Net 8
Operating system: Windows 11
IDE: Visual Studio 2022 17.11.3

### PR DESCRIPTION
**Pull request by roji**
ExecuteDelete/Update take as input the SelectExpression that was translated so far, just prior to their appearance; that SelectExpression is assumed to be reading the tables, so references views rather than tables.

Note that the query may reference multiples tables. The additional tables (not the one being mutated) do need to be views, as we're reading from them. But during translation, we don't know which table is being updated - the user can start from one root, and project out a navigation to be deleted. So we only know the target table at the end of translation.

So the approach here is to detect the case where the table to be changed is a view, find the table corresponding to that view, and replace it in the SelectExpression.

Note that handling ExecuteUpdate where the property to set is a complex type and there's a vide mapping isn't yet supported; this is blocking on #34706.

Closes #34677

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteUpdate.cs [hunk 1]
```diff
@@ -118,10 +121,71 @@ bool TranslateSetters(
...
+                        var tableExpression = select.GetTable(column, out var tableIndex);
+                        if (tableExpression.UnwrapJoin() is TableExpression { Table: not ITable } unwrappedTableExpression)
+                        {
+                            // If the entity is also mapped to a view, the SelectExpression will refer to the view instead, since
+                            // translation happens with the assumption that we're querying, not deleting.
+                            // For this case, we must replace the TableExpression in the SelectExpression - referring to the view - with the
+                            // one that refers to the mutable table.
+
+                            // Get the column on the (mutable) table which corresponds to the property being set
+                            var targetColumnModel = property.DeclaringType.GetTableMappings()
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteUpdate.cs:161]: @AndriySvyryd PTAL, this code finds the mutable table column corresponding to the view column that we got from query translation (so that we can modify the SelectExpression to reference the table instead of the view).

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteDelete.cs [hunk 2]
```diff
@@ -39,54 +39,86 @@ public partial class RelationalQueryableMethodTranslatingExpressionVisitor
...
+        // Find the table model that maps to the entity type; there must be exactly one (e.g. no entity splitting).
+        ITable targetTable;
+        switch (entityType.GetTableMappings().ToList())
         {
-            AddTranslationErrorDetails(
-                RelationalStrings.ExecuteOperationOnEntitySplitting(
-                    nameof(EntityFrameworkQueryableExtensions.ExecuteDelete), entityType.DisplayName()));
-            return null;
+            case []:
+                throw new NotImplementedException(); // TODO: Throw message to indicate that the entity type is not mapped to any table.
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteDelete.cs:47]: throw new InvalidOperationException(
                                    RelationalStrings.ExecuteUpdateOnEntityNotMappedToTable(entityType.DisplayName()));

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteDelete.cs [hunk 3]
```diff
@@ -39,54 +39,86 @@ public partial class RelationalQueryableMethodTranslatingExpressionVisitor
...
-            return new NonQueryExpression(new DeleteExpression(tableExpression, selectExpression));
-
-            static bool AreOtherNonOwnedEntityTypesInTheTable(IEntityType rootType, ITableBase table)
+            // Finally, check if the provider has a native translation for the delete represented by the select expression.
+            // The default relational implementation handles simple, universally-supported cases (i.e. no operators except for predicate).
+            // Providers may override IsValidSelectExpressionForExecuteDelete to add support for more cases via provider-specific DELETE syntax.
+            if (IsValidSelectExpressionForExecuteDelete(selectExpression))
             {
-                foreach (var entityTypeMapping in table.EntityTypeMappings)
+                if (AreOtherNonOwnedEntityTypesInTheTable(entityType.GetRootType(), unwrappedTableExpression.Table))
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteDelete.cs:106]:
```suggestion
                if (AreOtherNonOwnedEntityTypesInTheTable(entityType.GetRootType(), targetTable))
```

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteUpdate.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteUpdate.cs:161]: There could be multiple column mappings for the same property, but they should still point to the same column, so you should call `FirstOrDefault` instead. Or use `GroupBy` to be safe

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteUpdate.cs [hunk 4]
```diff
@@ -118,10 +121,72 @@ bool TranslateSetters(
...
+
+                            if (targetColumnModel is null)
+                            {
+                                throw new InvalidOperationException(
+                                    RelationalStrings.ExecuteUpdateOnEntityNotMappedToTable(property.DeclaringType.DisplayName()));
+                            }
+
+                            if (targetColumnModel.Name != column.Name)
+                            {
+                                // If we ever allow mapping the same property to different column names on the view and table, we'll need
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteUpdate.cs:173]: We definitely allow this already
```
modelBuilder.Entity<Cat>()
    .ToTable("Cat", b => b.Property(c => c.Name).HasColumnName("Name"))
    .ToView("CatView", b => b.Property(c => c.Name).HasColumnName("ViewName"));
```

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 5]
```diff
@@ -2698,12 +2712,21 @@ public static StructuralTypeShaperExpression GenerateComplexPropertyShaperExpres
...
     {
-        foreach (var table in Tables)
+        for (var i = 0; i < _tables.Count; i++)
         {
+            var table = _tables[i];
             if (table.UnwrapJoin().Alias == column.TableAlias)
             {
-                return table;
+                tableIndex = i;
+                return _tables[i];
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2729]:
```suggestion
                return table;
```

File: src/EFCore/Query/QueryHelpers.cs [hunk 6]
```diff
@@ -0,0 +1,63 @@
...
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.Diagnostics.CodeAnalysis;
+
+namespace Microsoft.EntityFrameworkCore.Query;
+
+/// <summary>
+///     Various helpers for query translation.
+/// </summary>
+public static class QueryHelpers
```
Comment (AndriySvyryd) [inline src/EFCore/Query/QueryHelpers.cs:11]: ⚠️⚠️⚠️ API Review alert ⚠️⚠️⚠️

File: test/EFCore.Relational.Specification.Tests/BulkUpdates/NonSharedModelBulkUpdatesRelationalTestBase.cs [hunk 7]
```diff
@@ -84,6 +86,86 @@ await AssertUpdate(
...
+            async,
+            contextFactory.CreateContext,
+            ss => ss.Foos,
+            s => s.SetProperty(f => f.Data, "Updated"),
+            rowsAffectedCount: 1);
+    }
+
+    [ConditionalTheory] // #34677, #34706
+    [MemberData(nameof(IsAsyncData))]
+    public virtual async Task Update_complex_type_type_with_view_mapping(bool async)
```
Comment (AndriySvyryd) [inline test/EFCore.Relational.Specification.Tests/BulkUpdates/NonSharedModelBulkUpdatesRelationalTestBase.cs:118]:
```suggestion
    public virtual async Task Update_complex_type_with_view_mapping(bool async)
```

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore/Query/QueryHelpers.cs (hunk 6 above)
Comment (roji) [reply src/EFCore/Query/QueryHelpers.cs:11]: Yep :) This is indeed a thing I wanted to discuss (the naming may need to have EF in it or similar).

Note that the helper method inside - IsMemberAccess - uses extension methods like TryGetEFPropertyArguments, which are completely public (on ExpressionExtension). I think this violates our principle of not exposing public extension methods over non-EF types - users get these in Intellisense when working with extensions. Of course, all this stuff is meant to be provider-facing, we should consider cleaning it up.

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteUpdate.cs (hunk 4 above)
Comment (roji) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteUpdate.cs:173]: Thanks... Opened #34713 to track this separately, will probably submit a PR for that soon.

Comment (roji) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteUpdate.cs:173]: Note that this affects other columns in the tree, not just the ones in the update setters, which is what this check looks at. Will remove it for now.

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteUpdate.cs (hunk 1 above)
Comment (roji) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.ExecuteUpdate.cs:161]: So you're saying there can be multiple column mappings, specifying the same property and same column (basically duplicates)? Does that serve an actual purpose?

Anyway, changed the code to:

```c#
var targetColumnModel = property.DeclaringType.GetTableMappings()
    .SelectMany(tm => tm.ColumnMappings)
    .Where(cm => cm.Property == property)
    .Select(cm => cm.Column)
    .SingleOrDefault();
```
