### PR TITLE
Query: Do not generate server side joins for optional dependents

### LINKED ISSUE #18299: Query on owned entity produces overly complicated SQL
When querying an entity and filtering on an owned entity the SQL query that is produced includes a `LEFT JOIN` that could be avoided.

### Steps to reproduce

Entites:

```cs
class Order
{
    public int Id { get; set; }
    public string Title { get; set; }
    public Address Address { get; set; }
}

class Address
{
    public string Street { get; set; }
    public string City { get; set; }
}
```

Model configuration:

```cs
modelBuilder.Entity<Order>().OwnsOne(x => x.Address);
```

The database table that is created looks like this:

immagine

A simple query like:

```cs
context.Orders.Where(x => x.Address == null).ToList();
```

Produces this SQL:

```sql
SELECT o."Id", o."Title", t."Id", t."Address_City", t."Address_Street"
      FROM "Orders" AS o
      LEFT JOIN (
          SELECT o0."Id", o0."Address_City", o0."Address_Street", o1."Id" AS "Id0"
          FROM "Orders" AS o0
          INNER JOIN "Orders" AS o1 ON o0."Id" = o1."Id"
          WHERE (o0."Address_Street" IS NOT NULL) OR (o0."Address_City" IS NOT NULL)
      ) AS t ON o."Id" = t."Id"
      WHERE (t."Id" IS NULL)
```

Which is overly complicated. The columns `Address_City` and `Address_Street` are available on the `Orders` table without any JOIN.

Same thing when querying a specific owned entity property:

```cs
context.Orders.Where(x => x.Address.City == "Rome").ToList();
```

```sql
SELECT o."Id", o."Title", t."Id", t."Address_City", t."Address_Street"
      FROM "Orders" AS o
      LEFT JOIN (
          SELECT o0."Id", o0."Address_City", o0."Address_Street", o1."Id" AS "Id0"
          FROM "Orders" AS o0
          INNER JOIN "Orders" AS o1 ON o0."Id" = o1."Id"
          WHERE (o0."Address_Street" IS NOT NULL) OR (o0."Address_City" IS NOT NULL)
      ) AS t ON o."Id" = t."Id"
      WHERE (t."Address_City" = 'Rome') AND (t."Address_City" IS NOT NULL)
```

### Further technical details

Example project (PostgreSQL): [EfCoreOwnedEntity.zip](https://github.com/aspnet/EntityFrameworkCore/files/3708574/EfCoreOwnedEntity.zip)

EF Core version: 3.0.0
Database provider: **Npgsql.EntityFrameworkCore.PostgreSQL** 3.0.1
Target framework: .NET Core 3.0
Operating system: Windows 10 1903
IDE: e.g. Visual Studio 2019 16.3.2

### LINKED ISSUE #20332: Query: Define set of conditions for materialization on EntityShaper
- Entity is not coming from left join, has a key and key value contains null then we throw
- Entity is coming from left join, has a key and key value contains null then return null
- Entity has valid key and is not optional dependent which is sharing same table, then we materialize (this cover required dependents too)
- Entity is optional dependent with table splitting and has a valid key, then we materialize if excluding PK, all of the required columns have value or any of optional column has non-null value else we return null
- Entity is keyless, coming from left join and all properties are null then we return null, we materialize all other keyless entities

In addition to above to support #10140 the flexible mapping condition would become part of it.

EntityShaper will contain a lambda of `Func<ValueBuffer, IEntityType>`
The lambda returns IEntityType based on above set of conditions telling which entityType to materialize. If there is not entityType should be materialized (e.g. optional dependent), then it returns null. If there is no matching entityType and null cannot be returned (basically unknown discriminator value), it throws exception.

Core EntityShaper contains conditions for discriminator/keyless entityType.
Relational EntityShaper will extend and add conditions for required/optional dependents when table splitting.

@AndriySvyryd - Can you review conditions at the start if that matches what we decided in meeting?

### LINKED ISSUE #20338: Query: Cases of table splitting when table cannot give all the columns
Most notably if Distinct is applied causing pushdown.

### PR DESCRIPTION
**Pull request by smitpatel**
Fix involves:
- Adding additional materialization conditions for relational layer when table splitting is used. See #20332 for conditions
- Create EntityProjection using the same table when both types are sharing the table.
- Fix a bug in shaper when null entityType is returned from materialization condition, don't call StartTracking.
- Assign nullability to PK column correctly for optional dependents so we don't project it twice.
- Disabled Sql assertion in OwnedQuerySqlServerTest. Will enable after model update as described in #20336, #20343

Resolves #18299
Resolves #20338
Resolves #20332

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs [hunk 1]
```diff
@@ -1924,7 +1924,7 @@ SELECT COUNT(*)
         }
 
         private void AssertSql(params string[] expected)
-             => Fixture.TestSqlLoggerFactory.AssertBaseline(expected);
+        { }//=> Fixture.TestSqlLoggerFactory.AssertBaseline(expected);
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs]: revert

File: src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+            [NotNull] IEntityType entityType,
+            [NotNull] Expression valueBufferExpression,
+            bool nullable,
+            [NotNull] LambdaExpression discriminatorCondition)
+            : base(entityType, valueBufferExpression, nullable,
+                  discriminatorCondition ?? GenerateMaterializationCondition(Check.NotNull(entityType, nameof(entityType)), nullable))
+        {
+        }
+
+        private static LambdaExpression GenerateMaterializationCondition(IEntityType entityType, bool nullable)
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs]: I don't like the code duplication between this and `ShapedQueryCompilingExpressionVisitor`, but don't have specific suggestions at this point

File: test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs (hunk 1 above)
Comment (smitpatel) [reply test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs]: Refer to commit message.

File: src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs (hunk 2 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs]: You mean EntityShaperExpression?

Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs]: Whatever I reviewed previously looked very similar

Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs]: Found a way to make it DRY. Will submit a PR.
