### PR TITLE
Fix result mapping string size in SQL Server string aggregate translator

### LINKED ISSUE #29229: SqlServerStringAggregateMethodTranslator.cs has Size backwards
## File a bug

If it's unicode the size should be 4000.
This seems to set the size to 8000.
If it's not Unicode, the size should be 8000.
This code below appears to set the size to 4000.

        // STRING_AGG enlarges the return type size (e.g. for input VARCHAR(5), it returns VARCHAR(8000)).
        // See https://docs.microsoft.com/sql/t-sql/functions/string-agg-transact-sql#return-types
        var resultTypeMapping = sqlExpression.TypeMapping;
        if (resultTypeMapping?.Size != null)
        {
            if (**resultTypeMapping.IsUnicode** && resultTypeMapping.Size < 8000)
            {
                resultTypeMapping = _typeMappingSource.FindMapping(
                    typeof(string),
                    resultTypeMapping.StoreTypeNameBase,
                    unicode: true,
                    size: 8000);
            }
            else if (**!resultTypeMapping.IsUnicode** && resultTypeMapping.Size < 4000)
            {
                resultTypeMapping = _typeMappingSource.FindMapping(
                    typeof(string),
                    resultTypeMapping.StoreTypeNameBase,
                    unicode: false,
                    size: 4000);
            }
        }

### PR DESCRIPTION
**Pull request by roji**
Fixes #29229

**Description**

When translating SQL Server aggregate string methods (string.Join, string.Concat), the maximum size for unicode/non-unicode strings is reversed, leading to an incorrect type mapping for the result

**Customer impact**

Reproducing an observable bug here isn't trivial (and may not be possible), since SqlServerStringTypeMapping has checks and doesn't take the incorrect size into account. However, the fix is trivial and ensures the correctness of the type mapping.

**How found**

Customer reported.

**Regression**

No, new feature (aggregate string function translation.

**Testing**

New testing added.

**Risk**

Very low; small self-evident fix in new code introduced for a new 7.0 feature only.

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SqlServerStringAggregateMethodTranslator.cs [hunk 1]
```diff
@@ -61,21 +61,21 @@ public class SqlServerStringAggregateMethodTranslator : IAggregateMethodCallTran
         var resultTypeMapping = sqlExpression.TypeMapping;
         if (resultTypeMapping?.Size != null)
         {
-            if (resultTypeMapping.IsUnicode && resultTypeMapping.Size < 8000)
+            if (resultTypeMapping.IsUnicode && resultTypeMapping.Size < 4000)
```
Comment (ajcvickers) [inline src/EFCore.SqlServer/Query/Internal/SqlServerStringAggregateMethodTranslator.cs:64]: Shouldn't this be `<=`

Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerStringAggregateMethodTranslator.cs:64]: I think that if it's equal to 4000 (for unicode), it's OK to just retain the original mapping of the operand expression (assigned just above), bubbling it up, no?

**Review by ajcvickers — APPROVED** [review]
