### PR TITLE
Don't consider a generated value stable just because it was explicitly set

### LINKED ISSUE #32084: Differnce in behavior between TPH and TPT/TPC with new entity added through navigation property
## File a bug

I'm having an issue where TPH works but TPT/TPC does not. When I'm creating a new entity and adding it by assigning it to navigation property.

### Include your code

Full code to reproduce : https://github.com/Euphoric/EfCore.InheritanceIssue/blob/main/EfCore.InheritanceIssue/EfCore.InheritanceIssue/Program.cs

The relevant pieces are :

```C#

public class ParentEntity
{
    public Guid Id { get; set; }
    public ChildBaseEntity? Child { get; set; }
}

public abstract class ChildBaseEntity
{
    public Guid Id { get; set; }
    public Guid ParentId { get; set; }
}

public class ChildEntity : ChildBaseEntity
{
    public String? ChildValue { get; set; }
}

public class TestDbContext : DbContext
{
    public TestDbContext(DbContextOptions options)
        : base(options)
    {
    }

    public DbSet<ParentEntity> Parents { get; private set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var parent = modelBuilder.Entity<ParentEntity>();
        parent.HasOne(x => x.Child)
            .WithOne()
            .HasForeignKey<ChildBaseEntity>(x=>x.ParentId)
            ;
        var childBase = modelBuilder.Entity<ChildBaseEntity>();
        //childBase.UseTphMappingStrategy(); // Case 1 : Works correctly
        //childBase.UseTptMappingStrategy(); // Case 2 : Doesn't work
        childBase.UseTpcMappingStrategy(); // Case 3 : Doesn't work
        
        var child = modelBuilder.Entity<ChildEntity>();
        child.HasBaseType<ChildBaseEntity>();
    }
}

// And when executed:

var parentId = Guid.NewGuid();
context.Parents.Add(new ParentEntity {Id = parentId});

var parent = await context.Parents.FindAsync(parentId);
var child = new ChildEntity {Id = Guid.NewGuid(), ParentId = parent!.Id, ChildValue = "test value"};
//await context.Set<ChildBaseEntity>().AddAsync(child); // fixes
parent.Child = child;
await context.SaveChangesAsync();
```

When using TPH, this code works as expected.
But when using TPT or TPC this code fails when trying to save changes:
```
     An exception occurred in the database while saving changes for context type 'EfCore.InheritanceIssue.TestDbContext'.
      Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understandi
         at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader, Boolean async, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

Looking at log, the difference is that for TPH, EF generates INSERT:

```
      Executed DbCommand (6ms) [Parameters=[@p0='?' (DbType = Guid), @p1='?', @p2='?', @p3='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      INSERT INTO "ChildBaseEntity" ("Id", "ChildValue", "Discriminator", "ParentId")
      VALUES (@p0, @p1, @p2, @p3);
```

But for TPC, EF generates UPDATE, even though the row was never inserted before:

```
      Executed DbCommand (8ms) [Parameters=[@p2='?' (DbType = Guid), @p0='?', @p1='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      UPDATE "ChildEntity" SET "ChildValue" = @p0, "ParentId" = @p1
      WHERE "Id" = @p2;
```

I have also verified this is issue on both PosgreSql and SqlServer.

### Workaround

Adding the child entity explicity fixes the issue and makes EF insert it as new entity.

### Question

Is this expected behavior?
If yes, is it possible to configure EF so it maps to table-per-concretetype and works correctly even without adding the new referenced entity explicitly?

### Include provider and version information

EF Core version: 7.0.12
Database provider: PostgreSql, SqlServer
Target framework: .NET 7
Operating system: Windows 10
IDE: Rider 2023.2.2

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #32084

### CODE REVIEW

File: src/EFCore/ChangeTracking/Internal/ValueGenerationManager.cs [hunk 1]
```diff
@@ -96,15 +96,23 @@ public virtual bool Generate(InternalEntityEntry entry, bool includePrimaryKey =
...
         {
+            var valueGenerator = GetValueGenerator(property);
+            if (valueGenerator.GeneratesStableValues)
+            {
+                hasStableValues = true;
+            }
+            else
+            {
+                hasNonStableValues = true;
+            }
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/Internal/ValueGenerationManager.cs:107]: You can remove the duplicate code below

**Comment by AndriySvyryd** [comment]
> Or does there also have to be a stable generator in there for the break you are thinking of?

Sorry, it just needs to be one stable generator, like the one we use in Cosmos.

**Comment by ajcvickers** [comment]
> > Or does there also have to be a stable generator in there for the break you are thinking of?
> 
> Sorry, it just needs to be one stable generator, like the one we use in Cosmos.

So you mean PK: yes; FK: no; Explicit value: no; stable generator: yes?

**Comment by ajcvickers** [comment]
@AndriySvyryd Wrote taste cases that execute this path. The behavior has changed when detecting changes and a new entity is found that has an explicitly set stable value for its PK. We previous detected this as Modified, as we would if the value was non-stable and explicitly set, but the presence of a stable value does not indicate that the entity must already exist, so the correct thing to do is fall back to Added.
