### PR TITLE
Fix SQL Server Contains whitespace issues

### LINKED ISSUE #19402: Incorrect string matching behavior on SQL Server with whitespace patterns
I'm getting wrong results from database when trying to filter string (`Contains`, `StartsWith`, `EndsWith`, etc) with spaces.

### Steps to reproduce
I'm build query like:
``` C#
var test = "  ";
var venues = await context.Venues.Where(x => x.Name.Contains(test)).ToListAsync(cancellationToken);
```
Which gets translated to:
```SQL
SELECT [v].[Id], [v].[Name]
FROM [Venues] AS [v]
WHERE (@__test_0 = N'') OR CHARINDEX(@__test_0, [v].[Name]) > 0
```

This query returns all rows from database when `@__test_0` contains spaces.

### Further technical details

EF Core version: 3.1.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1

### PR DESCRIPTION
**Pull request by roji**
* Translate to LIKE instead of CHARINDEX for constant patterns
* Change empty string compensation from equality to LIKE

### StartsWith/EndsWith

*EDIT:* This can't currently be fixed, and not just because of the compensation - the main translation - `LEFT(LEN))` - also doesn't work for whitespace-only patterns (see https://github.com/dotnet/efcore~/pull/21097#issuecomment-637031454). Nothing to do about this for now.

~StartsWith/EndsWith still isn't fixed with regards to empty string compensation, so a whitespace-only pattern returns all rows. I can't change it to use LIKE, since the compensation happens in preprocessing. Our options:~

~1. Keep things the same, so we have false positives when the pattern is whitespace-only (all rows returned)~
~2. Remove the compensation, so we'll have a false negative for empty string - seems less problematic than the false positives, but is also a breaking change.~
~3. Find some way to move the empty-string compensation from preprocessing to translation, in which case we can switch to LIKE just like Contains.~

~Since we haven't had complaints, I say we leave it like this for now (option 1).~

### StartsWith/EndsWith/ContainsWith with null pattern

Need to decide on what happens with StartsWith/EndsWith/Contains and null patterns. StartsWith/EndsWith translated this to the LIKE with null, and this PR changes Contains to do the same. LIKE is different from equality in that it doesn't get null-compensated (as we recently decided). Options:

* Leave as-is
* Simply return a false constant for null patterns - works for constants/patterns but not for columns (unusual case).
* Specifically compensate for null pattern in translation, which doesn't seem right (should be in SqlNullabilityProcessor, what about respecting relation null semantics...)
String_contains_on_argument_with_wildcard_column_negated

Fixes #19402

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs [hunk 1]
```diff
@@ -1725,7 +1725,7 @@ public override async Task Non_unicode_string_literals_is_used_for_non_unicode_c
             AssertSql(
                 @"SELECT [c].[Name], [c].[Location], [c].[Nation]
 FROM [Cities] AS [c]
-WHERE CHARINDEX('Add', COALESCE([c].[Location], '') + 'Added') > 0");
+WHERE COALESCE([c].[Location], '') + 'Added' LIKE '%Add%'");
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs:1728]: The lack of parentheses here smells bad, no?

**Comment by smitpatel** [comment]
> Find some way to move the empty-string compensation from preprocessing to translation

What "compensation" happens in preprocessing and why is it problematic?

File: src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs [hunk 2]
```diff
@@ -283,26 +283,29 @@ public virtual SqlExpression Translate(SqlExpression instance, MethodInfo method
 
                 if (pattern is SqlConstantExpression constantPattern)
                 {
-                    // Intentionally string.Empty since we don't want to match nulls here.
-#pragma warning disable CA1820 // Test for empty strings using string length
-                    if ((string)constantPattern.Value == string.Empty)
-#pragma warning restore CA1820 // Test for empty strings using string length
+                    if (!(constantPattern.Value is string patternValue))
```
Comment (smitpatel) [inline src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs:286]: Why string.Contains pattern is non string value?

**Comment by roji** [comment]
Am referring to [this stuff](https://github.com/dotnet/efcore/blob/7cb52b388a2d9fd8f9c2c499ef3ffb9753d9932a/src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs#L62), which we've discussed before (and I still don't completely get). This PR changes Contains translation to generate `pattern LIKE ''` for the empty string compensation, but in the case of StartsWith/EndsWith I can't do that.

File: src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs (hunk 2 above)
Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs:286]: It's just a null check

**Comment by smitpatel** [comment]
Now explain why cannot you do that because of that line?

**Comment by roji** [comment]
The preprocessor injects an equality comparison to empty string, which I can't change to LIKE in preprocessing, because it's an SQL expression. I also can't convert all string equality to LIKE later (as in #19881), since we decided not to touch arbitrary equality - only StartsWith/EndsWith/Contains.

I guess I can convert only string equality to empty string in SQL Server, though - is this what you think we should do? It would be a bit odd to special-case empty string that way, but is possible (if so, do you prefer me doing this in translation or postprocessing)?

Otherwise, if you have something else in mind, can you please explain?

**Comment by smitpatel** [comment]
>  I also can't convert all string equality to LIKE later (as in #19881), since we decided not to touch arbitrary equality - only StartsWith/EndsWith/Contains.

Then how does that preprocessing is blocking you? It is still keeping StartsWith/EndsWith call in the tree which you can convert to Like expression later. It adds comparison to string.Empty but string.Empty comparison is not same as whitespace issue. It is same as any other string.Empty comparison with column.

**Comment by roji** [comment]
The comparison of the pattern to string.Empty is what's causing the whitespace issue, since when the pattern is white-space only, this returns true. 

Let's do a quick call after triage later, probably more efficient.

**Comment by smitpatel** [comment]
Bring it to design meeting this Wednesday.

**Comment by roji** [comment]
@smitpatel I discussed with @maumar who gave me some ideas, looked deeper, and we can't really fix this regardless of anything happening in preprocessing. Even if we forget about the empty string compensation, StartsWith/EndsWith translates to `LEFT(value, LEN(pattern)) = pattern`, which will falsely return true for any whitespace-only pattern. So regardless of the empty string compensation, the main translation is faulty. I think we should leave this for now.

@maumar @smitpatel there's still the 2nd question above, i.e. what to do with null patterns.

PS For reference, here's @maumar's explanation on the special preprocessing behavior for StartsWith/EndsWith: https://github.com/dotnet/efcore/issues/19120#issuecomment-571819557. According to it, we should be able to move the empty string compensation into translation in the future if we ever need to.

**Comment by smitpatel** [comment]
> Bring it to design meeting this Wednesday.

**Comment by roji** [comment]
I don't think anybody wants/needs to hear about this within the team except for us 3, but whatever you prefer.

File: test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs (hunk 1 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs:1728]: would be nicer with ()s, yeah. We already have a method in sql gen for that (RequiresBrackets) that we can use for Match operand in like

File: test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs [hunk 3]
```diff
@@ -157,6 +157,16 @@ public virtual Task String_FirstOrDefault_MethodCall(bool async)
                 entryCount: 10);
         }
 
+        [ConditionalTheory]
+        [MemberData(nameof(IsAsyncData))]
+        public virtual Task String_Contains_Parameter_with_whitespace(bool async)
+        {
+            var pattern = "     ";
```
Comment (maumar) [inline test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs:164]: do we have a test like this but with constant, rather than parameter?

Comment (roji) [reply test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs:173]: Added this
