### PR TITLE
Robust ordering on key properties

### LINKED ISSUE #13507: Use the configured ValueComparer in ModificationCommandComparer

### LINKED ISSUE #19638: Cosmos provider builds/uses wrong model when keys have value converters
See `KeysWithConvertersCosmosTest`. 

The same tests with the SQL Server provider build a model where the entity types look like this:
```
  EntityType: BytesStructKeyOptionalDependent
    Properties: 
      Id (BytesStructKey) Required PK AfterSave:Throw
      PrincipalId (Nullable<BytesStructKey>) FK Index
    Navigations: 
      Principal (BytesStructKeyPrincipal) ToPrincipal BytesStructKeyPrincipal Inverse: OptionalDependents
    Keys: 
      Id PK
    Foreign keys: 
      BytesStructKeyOptionalDependent {'PrincipalId'} -> BytesStructKeyPrincipal {'Id'} ToDependent: OptionalDependents ToPrincipal: Principal
    Indexes: 
      PrincipalId
  EntityType: BytesStructKeyPrincipal
    Properties: 
      Id (BytesStructKey) Required PK AfterSave:Throw
      Foo (string)
    Navigations: 
      OptionalDependents (ICollection<BytesStructKeyOptionalDependent>) Collection ToDependent BytesStructKeyOptionalDependent Inverse: Principal
      RequiredDependents (ICollection<BytesStructKeyRequiredDependent>) Collection ToDependent BytesStructKeyRequiredDependent Inverse: Principal
    Keys: 
      Id PK
  EntityType: BytesStructKeyRequiredDependent
    Properties: 
      Id (BytesStructKey) Required PK AfterSave:Throw
      PrincipalId (BytesStructKey) Required FK Index
    Navigations: 
      Principal (BytesStructKeyPrincipal) ToPrincipal BytesStructKeyPrincipal Inverse: RequiredDependents
    Keys: 
      Id PK
    Foreign keys: 
      BytesStructKeyRequiredDependent {'PrincipalId'} -> BytesStructKeyPrincipal {'Id'} ToDependent: RequiredDependents ToPrincipal: Principal
    Indexes: 
      PrincipalId
```

~~The Cosmos model either has an erroneous string AK property on each entity type:~~

Edit: The model is as expected:  https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli#working-with-disconnected-entities

```
  EntityType: BytesStructKeyOptionalDependent
    Properties: 
      Id (BytesStructKey) Required PK AfterSave:Throw
      Discriminator (no field, string) Shadow Required
      PrincipalId (Nullable<BytesStructKey>) FK Index
      __jObject (no field, JObject) Shadow BeforeSave:Ignore AfterSave:Ignore ValueGenerated.OnAddOrUpdate
      id (no field, string) Shadow Required AlternateKey AfterSave:Throw
    Navigations: 
      Principal (BytesStructKeyPrincipal) ToPrincipal BytesStructKeyPrincipal Inverse: OptionalDependents
    Keys: 
      Id PK
      id
    Foreign keys: 
      BytesStructKeyOptionalDependent {'PrincipalId'} -> BytesStructKeyPrincipal {'Id'} ToDependent: OptionalDependents ToPrincipal: Principal
    Indexes: 
      PrincipalId
  EntityType: BytesStructKeyPrincipal
    Properties: 
      Id (BytesStructKey) Required PK AfterSave:Throw
      Discriminator (no field, string) Shadow Required
      Foo (string)
      __jObject (no field, JObject) Shadow BeforeSave:Ignore AfterSave:Ignore ValueGenerated.OnAddOrUpdate
      id (no field, string) Shadow Required AlternateKey AfterSave:Throw
    Navigations: 
      OptionalDependents (ICollection<BytesStructKeyOptionalDependent>) Collection ToDependent BytesStructKeyOptionalDependent Inverse: Principal
      RequiredDependents (ICollection<BytesStructKeyRequiredDependent>) Collection ToDependent BytesStructKeyRequiredDependent Inverse: Principal
    Keys: 
      Id PK
      id
  EntityType: BytesStructKeyRequiredDependent
    Properties: 
      Id (BytesStructKey) Required PK AfterSave:Throw
      Discriminator (no field, string) Shadow Required
      PrincipalId (BytesStructKey) Required FK Index
      __jObject (no field, JObject) Shadow BeforeSave:Ignore AfterSave:Ignore ValueGenerated.OnAddOrUpdate
      id (no field, string) Shadow Required AlternateKey AfterSave:Throw
    Navigations: 
      Principal (BytesStructKeyPrincipal) ToPrincipal BytesStructKeyPrincipal Inverse: RequiredDependents
    Keys: 
      Id PK
      id
    Foreign keys: 
      BytesStructKeyRequiredDependent {'PrincipalId'} -> BytesStructKeyPrincipal {'Id'} ToDependent: RequiredDependents ToPrincipal: Principal
    Indexes: 
      PrincipalId
```

Or something is wrong about how it is being used:

```
Microsoft.EntityFrameworkCore.Cosmos.KeysWithConvertersCosmosTest.Can_insert_and_read_back_with_struct_key_and_optional_dependents

System.InvalidOperationException : The instance of entity type 'IntStructKeyPrincipal' cannot be tracked because another instance with the key value '{id: IntStructKeyPrincipal|Microsoft.EntityFrameworkCore.KeysWithConvertersTestBase`1+IntStructKey[Microsoft.EntityFrameworkCore.Cosmos.KeysWithConvertersCosmosTest+KeysWithConvertersCosmosFixture]}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry) in C:\aspnet\EntityFrameworkCore\src\EFCore\ChangeTracking\Internal\IdentityMap.cs:line 258
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate) in C:\aspnet\EntityFrameworkCore\src\EFCore\ChangeTracking\Internal\IdentityMap.cs:line 278
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry) in C:\aspnet\EntityFrameworkCore\src\EFCore\ChangeTracking\Internal\IdentityMap.cs:line 230
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry) in C:\aspnet\EntityFrameworkCore\src\EFCore\ChangeTracking\Internal\NullableKeyIdentityMap.cs:line 59
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry) in C:\aspnet\EntityFrameworkCore\src\EFCore\ChangeTracking\Internal\StateManager.cs:line 574
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties) in C:\aspnet\EntityFrameworkCore\src\EFCore\ChangeTracking\Internal\InternalEntityEntry.cs:line 296
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey) in C:\aspnet\EntityFrameworkCore\src\EFCore\ChangeTracking\Internal\InternalEntityEntry.cs:line 142
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node) in C:\aspnet\EntityFrameworkCore\src\EFCore\ChangeTracking\Internal\EntityGraphAttacher.cs:line 94
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode) in C:\aspnet\EntityFrameworkCore\src\EFCore\ChangeTracking\Internal\EntityEntryGraphIterator.cs:line 39
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey) in C:\aspnet\EntityFrameworkCore\src\EFCore\ChangeTracking\Internal\EntityGraphAttacher.cs:line 50
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState) in C:\aspnet\EntityFrameworkCore\src\EFCore\DbContext.cs:line 800
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates(IEnumerable`1 entities, EntityState entityState) in C:\aspnet\EntityFrameworkCore\src\EFCore\DbContext.cs:line 1372
   at Microsoft.EntityFrameworkCore.DbContext.AddRange(IEnumerable`1 entities) in C:\aspnet\EntityFrameworkCore\src\EFCore\DbContext.cs:line 1386
   at Microsoft.EntityFrameworkCore.DbContext.AddRange(Object[] entities) in C:\aspnet\EntityFrameworkCore\src\EFCore\DbContext.cs:line 1244
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.AddRange(TEntity[] entities) in C:\aspnet\EntityFrameworkCore\src\EFCore\Internal\InternalDbSet.cs:line 220
   at Microsoft.EntityFrameworkCore.KeysWithConvertersTestBase`1.InsertOptionalGraph[TPrincipal,TDependent]() in C:\aspnet\EntityFrameworkCore\test\EFCore.Specification.Tests\KeysWithConvertersTestBase.cs:line 1540
   at Microsoft.EntityFrameworkCore.KeysWithConvertersTestBase`1.Can_insert_and_read_back_with_struct_key_and_optional_dependents() in C:\aspnet\EntityFrameworkCore\test\EFCore.Specification.Tests\KeysWithConvertersTestBase.cs:line 27
```

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #13507
Fixes #19638

See also #19641

Basic logic is:
* If model type implements some sort of IComparable, then use it
* Otherwise, if provider type implement some sore of IComparable, then use it
* Otherwise fail in model validation

Also added new test suite specifically for different types of keys with and without conversions.

### CODE REVIEW

File: src/EFCore/Extensions/PropertyExtensions.cs [hunk 1]
```diff
@@ -271,25 +271,58 @@ public static Type GetProviderClrType([NotNull] this IProperty property)
...
 
         /// <summary>
         ///     Gets the <see cref="ValueComparer" /> to use for structural copies for this property, or <c>null</c> if none is set.
         /// </summary>
         /// <param name="property"> The property. </param>
+        /// <param name="fallback"> If true, then the key comparer is returned when the structural comparer is not set. </param>
         /// <returns> The comparer, or <c>null</c> if none has been set. </returns>
-        public static ValueComparer GetStructuralValueComparer([NotNull] this IProperty property)
-            => (ValueComparer)Check.NotNull(property, nameof(property))[CoreAnnotationNames.StructuralValueComparer];
+        public static ValueComparer GetStructuralValueComparer([NotNull] this IProperty property, bool fallback = true)
```
Comment (AndriySvyryd) [inline src/EFCore/Extensions/PropertyExtensions.cs]: When would one need to call `GetValueComparer` or `GetKeyValueComparer` that can't be replaced with `GetStructuralValueComparer` ?

**Comment by AndriySvyryd** [comment]
Filed https://github.com/dotnet/efcore/issues/19650 in case you want to tackle it too

File: src/EFCore/Extensions/PropertyExtensions.cs (hunk 1 above)
Comment (ajcvickers) [reply src/EFCore/Extensions/PropertyExtensions.cs]: Well...since you asked...

Consumers (EF Code) should call:
* GetStructuralValueComparer when is is required that values are compared structurally (i.e. deeply)
* GetKeyValueComparer when comparing keys, which usually is done structurally, but may not be.
* GetValueComparer when doing "normal" DetectChanges comparisons--often are not structural.

Then the fallbacks work by not requiring a structural comparer to be set if the key one will work, and not requiring a key one if the normal one will work.

Finally, if the application explicitly sets a value comparer, then we use that for all comparisons rather than using any comparer from the type mappings. This means for most cases people just need to write one, correct ValueComparer and set it. Users will only need to set the other kinds if they explicitly want to optimize DetectChanges or key comparions, which will be rare.

Comment (AndriySvyryd) [reply src/EFCore/Extensions/PropertyExtensions.cs]: > - GetKeyValueComparer when comparing keys, which usually is done structurally, but may not be.
> - GetValueComparer when doing "normal" DetectChanges comparisons--often are not structural.

It's still not clear to me why not using the StructuralValueComparer when one is available is ok for those cases. Is it just for perf and we assume that the values are immutable? Seems like there's potentially a bug there.

Comment (ajcvickers) [reply src/EFCore/Extensions/PropertyExtensions.cs]: @AndriySvyryd I ran the code with all calls for structural comparers replaced with calls for key comparers. Tests failed in the in-memory database because the key comparer for byte arrays does not do a deep snapshot of the byte array. This is by-design because, as you say, the value is supposed to be immutable and we don't want the overhead of copying the array. (This is similar to the case for concurrency tokens that we discussed a while back.)

However, we could change that. It would be unlikely to have a huge perf impact on binary keys because binary keys are usually very short. Also, binary keys in of themselves are rare. Also, there are other ways to handle performant, immutable binary keys by using type converters, setting your own comparer (except when testing with the in-memory store), or by overriding type mappings.

If you agree that we should do this, then I'll create a separate PR for it after merging, since this is already a decent sized change.

This is where structural comparers went in: https://github.com/dotnet/efcore/commit/c9284b7950f27c08e8f58d5ad3d071fb898e8cd1

> This change introduces a new ValueComparer type that can be used when deep copies are needed. Neither the regular or the key comparer can be relied on to work this way, hence the need for a new one. There is no reliable way to know if such a comparer is needed, so it's up to the application/provider setting up the type mapping to provide one if needed.
