### PR TITLE
Query: Correct translation of SqlServer ToString

### LINKED ISSUE #20433: Incorrect UInt64 ToString SQL generation
LINQ query with UInt64.ToString() to MS SQL Server with lagre property value produces flawed SQL code leading to exception.

### Steps to reproduce

Suppose simple entity:
``` C#
    public class DemoEntity
    {
        [Key,
        DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public Int64 LongProperty { get; set; }

        public UInt64 ULongProperty { get; set; }
    }
```
with simple DbContext using `UseSqlServer()`.

`Add-Migration` results with `LongProperty` as `bigint` and `ULongProperty` as `decimal(20, 0)`.

<details><summary>ModelSnapshot.BuildModel</summary>

``` C#
modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ForEFCoreGithubIssue.DemoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("LongProperty")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ULongProperty")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Data");
                });
```
</details>

Sample database has an least one row with `LongProperty` equals to `Int64.MaxValue` and `ULongProperty` equals to `UInt64.MaxValue`.

Then query
``` C#
string needle = "1";
context.Data.Where(x => x.ULongProperty.ToString().Contains(needle))
```
produces
``` SQL
SELECT [d].[Id], [d].[LongProperty], [d].[ULongProperty]
FROM [Data] AS [d]
WHERE (@__needle_0 = N'') OR (CHARINDEX(@__needle_0, CONVERT(VARCHAR(19), [d].[ULongProperty])) > 0)
```
that leads to Microsoft.Data.SqlClient.SqlException "Arithmetic overflow error converting numeric to data type varchar.".

<details><summary>Note</summary>

Note that
``` C#
string needle = "1";
context.Data.Where(x => x.LongProperty.ToString().Contains(needle))
```
produces
``` SQL
SELECT [d].[Id], [d].[LongProperty], [d].[ULongProperty]
FROM [Data] AS [d]
WHERE (@__needle_0 = N'') OR (CHARINDEX(@__needle_0, CONVERT(VARCHAR(20), [d].[LongProperty])) > 0)
 ```
that works fine.

</details>

The problem is that for `ULongProperty` generated SQL query assumes 19 character length string, which is too short. Manual row SQL query replaced with `VARCHAR(20)` works fine.

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer v.3.1.3
Target framework: .NET Core 3.1
Operating system: MS Windows 10 1909
IDE: MS VS Community 2019 16.5.1
DB: MS SQL LocalDB 14.0.1000.169

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #20433

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs [hunk 1]
```diff
@@ -13,28 +13,28 @@ namespace Microsoft.EntityFrameworkCore.SqlServer.Query.Internal
 {
     public class SqlServerObjectToStringTranslator : IMethodCallTranslator
     {
-        private const int DefaultLength = 100;
+        private const int _defaultLength = 100;
```
Comment (maumar) [inline src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs]: We are not very consistent, but majority of const fields are pascal case. Pinging Chief Consistncy Officer @AndriySvyryd

Comment (AndriySvyryd) [reply src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs]: I thought we had an .editorconfig rule for this. Make sure it's working.

Comment (smitpatel) [reply src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs]: Added rule in editor config.
any non-private field -> PascalCase
Any private field with const -> PascalCase
Any private field other than covered above -> _camelCase.
