### PR TITLE
Close the DbConnection when returning a context with a DbConnection to the pool

### LINKED ISSUE #27308: Do some reasonable connection cleanup when returning a context with a DbConnection to the pool
I'm migrating my application from .net 5.0 and EF Core 5.0.13 to .net 6.0 and EF Core 6.0.1
In my code I use raw ADO syntax (Database.GetDbConnection()) and TransactionScope for ambient transaction.
I update counter in transaction and throw Exception inside uncommited transaction.
I expect that my counter won't change.
But it happens.
When I use DbContext without pool - everything is OK.
Also context.Database.EnlistTransaction(Transaction.Current) will fix problem. 
It also helps to downgrade to EF Core 5.0.13

### My simplified application
DDL
```sql
CREATE TABLE TestTable(
    Id  BIGINT IDENTITY (1, 1) NOT NULL,    
    SomeValue INT NOT NULL DEFAULT(0),
    CONSTRAINT Test PRIMARY KEY CLUSTERED (ID ASC)
)
INSERT INTO TestTable(SomeValue) Values(0)
--SELECT * from TestTable
```

My project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.13" />  will fix issue-->
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.1" />
  </ItemGroup>

</Project>

```

```C#
using System.Data;
using System.Transactions;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using IsolationLevel = System.Transactions.IsolationLevel;

var connectionString = "Data Source=localhost;Initial Catalog=MyDb;Integrated Security=True;";
var services = new ServiceCollection();
services.AddDbContextPool<MyDbContext>(builder => builder.UseSqlServer(connectionString));
//services.AddSqlServer<MyDbContext>(connectionString); // will fix issue
await using var sp = services.BuildServiceProvider();
for (var i = 0; i < 4; i++)
{
    await using var scope = sp.CreateAsyncScope();
    try
    {
        await UpdateAsync(scope.ServiceProvider);
    }
    catch (Exception e)
    {
        Console.WriteLine(e.Message);
    }
    await PrintValueAsync(sp);
}

static async Task UpdateAsync(IServiceProvider serviceProvider)
{
    var context = serviceProvider.GetRequiredService<MyDbContext>();
    using var ts = new TransactionScope(TransactionScopeOption.Required,
        new TransactionOptions()
        {
            IsolationLevel = IsolationLevel.ReadCommitted
        },
        TransactionScopeAsyncFlowOption.Enabled);
    var connection = context.Database.GetDbConnection();
    if (connection.State == ConnectionState.Closed)
    {
        await connection.OpenAsync();
    }
    //context.Database.EnlistTransaction(Transaction.Current); //will fix issue
    await using var command = connection.CreateCommand();
    command.CommandText = @"
MERGE dbo.TestTable AS target 
    USING (VALUES(@Id)) 
    AS source (Id)
ON (target.Id = source.Id)
WHEN MATCHED THEN
    UPDATE SET SomeValue = SomeValue + 1
OUTPUT inserted.SomeValue;
";
    command.Parameters.Add(new SqlParameter("Id", SqlDbType.BigInt)
    {
        Value = 1
    });
 
    var result = await command.ExecuteScalarAsync();
    Console.WriteLine($"result inside transaction {result}");
    throw new Exception("Some exception");
    ts.Complete();
}

static async Task PrintValueAsync(IServiceProvider serviceProvider)
{
    var context = serviceProvider.GetRequiredService<MyDbContext>();
    var connection = context.Database.GetDbConnection();
    if (connection.State == ConnectionState.Closed)
    {
        await connection.OpenAsync();
    }
    await using var command = connection.CreateCommand();
    command.CommandText = "SELECT SomeValue FROM TestTable WHERE Id=1";
    var result = await command.ExecuteScalarAsync();
    Console.WriteLine($"result without transaction {result}");
}

public sealed class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions options): base(options){}
}
```

### my app output

```
result inside transaction 1
Some exception
result without transaction 0
result inside transaction 1
Some exception
result without transaction 1
result inside transaction 2
Some exception
result without transaction 2
result inside transaction 3
Some exception
result without transaction 3
```
###  SQL Profiler
image

but i expect the following output
```
result inside transaction 1
Some exception
result without transaction 0
result inside transaction 1
Some exception
result without transaction 0
result inside transaction 1
Some exception
result without transaction 0
result inside transaction 1
Some exception
result without transaction 0
```

### Include provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows 10 version 1909
IDE:  Visual Studio 2022 17.0.5
dotnet --list-sdks
3.1.202 [C:\Program Files\dotnet\sdk]
5.0.403 [C:\Program Files\dotnet\sdk]
6.0.101 [C:\Program Files\dotnet\sdk]

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #27308

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs [hunk 1]
```diff
@@ -1384,6 +1386,309 @@ public async Task Provider_services_are_reset_with_factory(bool async, bool with
...
     }
 
+    [ConditionalTheory] // Issue #27308.
+    [InlineData(false, false)]
+    [InlineData(true, false)]
+    [InlineData(false, true)]
+    [InlineData(true, true)]
+    public async Task Handle_open_connection_when_returning_to_pool_for_owned_connection(bool async, bool openWithEf)
+    {
+        //using var connection = new SqlConnection(SqlServerNorthwindTestStoreFactory.NorthwindConnectionString);
```
Comment (AndriySvyryd) [inline test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs:1396]: 👀

Comment (ajcvickers) [reply test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs:1396]: Will remove.

**Review by AndriySvyryd — APPROVED** [review]
