### PR TITLE
Make sure migration model has type mapping

### LINKED ISSUE #20517: Entity Framework Core - Code-First throws exception
Good afternoon!

I don't know if somebody else run into the same problem with Code-First DB or I just missed something:

I updated to the latest 5.0...preview Nugets last week, and I tried to update my database (SQL Server 14.0.2027). The "add-migration" command created the migration file correctly, but the update-database command throws exception (I added a new property to one of my model, but the Package Manager Console said: invalid column).

I checked it, but is was a simple int column, it was valid... I cleared my DB, cleared the migration folder (and restarted my system...), and call the process (add-migration + update-database) again on the empty database. It throws another exception: after the "Applying migration..." line it throws a "System.IndexOutOfRangeException: Index was outside the bounds of the array".

If I downgrade the Nugets to the latest stable versions (3.1.3), the Code-First steps work well, create the tables and seeds the default data without any problem.

I tried it with the newest Nugets (published on April 2), but throws the same exception on an empty DB:

```
PM> update-database
Build started...
Build succeeded.
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 5.0.0-preview.2.20159.4 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (26ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (100ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (204ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [__EFMigrationsHistory] (
          [MigrationId] nvarchar(150) NOT NULL,
          [ProductVersion] nvarchar(32) NOT NULL,
          CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
      );
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (18ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (9ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20200403163437_Init'.
Applying migration '20200403163437_Init'.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.EntityFrameworkCore.Migrations.Operations.InsertDataOperation.GenerateModificationCommands(IModel model)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(InsertDataOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__71_28(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass15_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Index was outside the bounds of the array.
```

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #20517

### CODE REVIEW

File: src/EFCore.Relational/Migrations/Internal/Migrator.cs [hunk 1]
```diff
@@ -419,9 +426,33 @@ protected virtual IReadOnlyList<MigrationCommand> GenerateUpSql([NotNull] Migrat
...
             return _migrationsSqlGenerator
-                .Generate(migration.DownOperations, previousMigration?.TargetModel)
+                .Generate(migration.DownOperations, FinalizeModel(previousMigration?.TargetModel))
                 .Concat(new[] { new MigrationCommand(deleteCommand, _currentContext.Context, _commandLogger) })
                 .ToList();
         }
+
+        private IModel FinalizeModel(IModel model)
+        {
+            if (model is IConventionModel conventionModel)
```
Comment (lajones) [inline src/EFCore.Relational/Migrations/Internal/Migrator.cs:436]: Should this be a `Check()` instead? When is it not an `IConventionModel`?

Comment (AndriySvyryd) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:436]: The method takes an `IModel`, so enforcing that it has to be an `IConventionModel` goes against Liskov's principle. Even though in all practical scenarios in would be one.

Comment (lajones) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:436]: `Check.DebugAssert()` then? My point is that if the model is _not_ an `IConventionModel` and you expect this code to do something, it will fail to do so silently, and that could be hard to track down later.

If there are valid scenarios where this would not be an `IConventionModel` and this code _should_ do nothing, then you can ignore this comment. I just wasn't sure what those would be.

Comment (AndriySvyryd) [reply src/EFCore.Relational/Migrations/Internal/Migrator.cs:436]: If it's not an `IConventionModel` we can't do anything to it, so we'll just assume that it already has the expected annotations, if it doesn't it will be obvious from the exception messages thrown after this.

**Comment by AndriySvyryd** [comment]
Better late than never 😆

**Comment by bricelam** [comment]
lol, yep. Slowly catching up...
