### PR TITLE
Fix to #32911 - ComplexProperty with AsSplitQuery

### LINKED ISSUE #32911: Incorrect apply projection for complex properties
When I combine ComplexProperty and AsSplitQuery with properties mapped to column with equal names, I get wrong values when reading the complex properties. Their values are equal (but they are different instances). If I don't use the AsSplitQuery or rename the columns, the results are correct. See the snippet below.

The code is using Microsoft.EntityFrameworkCore.Sqlite 8.0.1 package.

```C#
#nullable enable

void Main()
{
	using (var ctx = new MyContext())
	{
		ctx.Database.EnsureDeleted();
		ctx.Database.EnsureCreated();
		ctx.Add(new Offer 
		{
			Variations = [
				new Variation {
					Payment = new Payment(120, 100),
					Nested = new NestedEntity
					{
						Payment = new Payment(12, 10),
					},
					Nested2 = new NestedEntity2
					{
						Payment = new Payment(24, 20),
					},
				}
			]
		});
		ctx.SaveChanges();
		ctx.ChangeTracker.Clear(); // If I don't clear the change tracker, it also works.
		
		var entity = ctx.Offers
			.Include(e => e.Variations!)
				.ThenInclude(v => v.Nested)
			.Include(e => e.Variations!)
				.ThenInclude(v => v.Nested2)
			.AsSplitQuery() // If I comment this out, it works
			.Single(e => e.Id == 1);
		
		//  The values are equal even when they shouldn't be.
		Console.WriteLine($"Entity {entity.Variations?.Single().Payment}");
		Console.WriteLine($"Nested Entity {entity.Variations?.Single().Nested?.Payment}");
		Console.WriteLine($"Nested Entity2 {entity.Variations?.Single().Nested2?.Payment}");
	}
}

public class MyContext : DbContext
{
	public DbSet<Offer> Offers => Set<Offer>();
	
	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
	    optionsBuilder.UseSqlite("DataSource=Test.db");
	}
	
	protected override void OnModelCreating(ModelBuilder builder)
	{
		builder.Entity<Variation>().ComplexProperty(p => p.Payment, price =>
		{
		    price.Property(p => p.Netto).HasColumnName("payment_netto"); // If I change the column name to a different than the others, it also works
		    price.Property(p => p.Brutto).HasColumnName("payment_brutto");
		});
		builder.Entity<NestedEntity>().ComplexProperty(p => p.Payment, price =>
		{
		    price.Property(p => p.Netto).HasColumnName("payment_netto");
		    price.Property(p => p.Brutto).HasColumnName("payment_brutto");
		});
		builder.Entity<NestedEntity2>().ComplexProperty(p => p.Payment, price =>
		{
		    price.Property(p => p.Netto).HasColumnName("payment_netto");
		    price.Property(p => p.Brutto).HasColumnName("payment_brutto");
		});
	}
}

public abstract class EntityBase 
{
	[System.ComponentModel.DataAnnotations.Key]
	public int Id {get; set; }
}

public class Offer : EntityBase
{	
	public ICollection<Variation>? Variations { get; set; }
}

public class Variation : EntityBase
{
	public Payment Payment {get; set; } = new Payment(0, 0);

	public NestedEntity? Nested {get; set; }
	public NestedEntity2? Nested2 {get; set; }
}

public class NestedEntity : EntityBase
{
	public Payment Payment {get; set; } = new Payment(0, 0);
}

public class NestedEntity2 : EntityBase
{
	public Payment Payment {get; set; } = new Payment(0, 0);
}

public record Payment(decimal Netto, decimal Brutto);
```

### Include provider and version information

EF Core version: 8.0.1
Database provider: Microsoft.EntityFrameworkCore.Sqlite 8.0.1
Target framework: .NET 8.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.8.5

### PR DESCRIPTION
**Pull request by maumar**
Problem was that when we lift structural type projection during pushdown, if that projection contains complex types with the same column names (e.g. cross join of same entities - it's perfectly fine to do in a vacuum, we just alias the columns whose names are repeated) we would lift the projection incorrectly. What we do is go through all the properties, apply the corresponding columns to the selectExpression if needed and generate StructuralTypeProjection object if the projection needs to be applied one level up. For complex types we would generate a shaper expression and then run it through the same process, BUT the nested complex properties would be added to a flat structure along with the primitive properties, rather than in separate cache dedicated for complex property shapers. This was wrong and not what we expected to see, when processing this structure one level up (i.e. when applying projection to the outer select)

```sql
SELECT [applying_this_projection_was_wrong]
FROM
(
    SELECT c.Id, c.Name, c.ComplexProp, o.ComplexProp as ComplexProp0
    FROM Customers as c
    JOIN Orders as o ON ...
) as s
```

i.e. applying projection once worked fine, but doing it second time did not. The reason why is that we expected to see information about the complex type shape in the complex property shaper cache, rather than flat structure for primitives, but it wasn't there. So we assumed this is the first time we the projection is being applied, so we conjure up the complex type shaper based on table alias and IColumn metadata. This results in a situation, where complex property that was aliased is never picked. So we end up with:

```sql
SELECT s.Id, s.Name, s.ComplexProp -- we would also try to add s.ComplexProp again, instead of s.ComplexProp0 but of course we don't add same thing twice FROM
(
    SELECT c.Id, c.Name, c.ComplexProp, o.ComplexProp as ComplexProp0
    FROM Customers as c
    JOIN Orders as o ON ...
) as s
```
This leads to bad data - two different objects with distinct data in them are mapped to the same column in the database.

Fix is to property build a complex type shaper structure when applying projection instead, so the structure we generate matches expectations. 

Also modified VisitChildren and MakeNullable methods on StructuralTypeProjectionExpression to process/preserve complex type cache information, which was previously gobbled up/ignored.

Fixes #32911

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -2141,52 +2142,68 @@ public void ApplyUnion(SelectExpression source2, bool distinct)
...
-                "Set operation over entity projections with different table map counts");
-            Check.DebugAssert(
-                projection1.TableMap.Keys.All(t => projection2.TableMap.ContainsKey(t)),
-                "Set operation over entity projections with table map discrepancy");
+                    var resultComplexProjection = ProcessStructuralType(
+                        (StructuralTypeProjectionExpression)complexPropertyShaper1.ValueBufferExpression,
+                        (StructuralTypeProjectionExpression)complexPropertyShaper2.ValueBufferExpression);
 
-            var tableMap = projection1.TableMap.ToDictionary(kvp => kvp.Key, _ => setOperationAlias);
+                    var resultComplexShaper = new RelationalStructuralTypeShaperExpression(
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2154]: or should we just do complexPropertyShaper1.Update(resultComplexProjection) ?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 2]
```diff
@@ -2141,52 +2142,68 @@ public void ApplyUnion(SelectExpression source2, bool distinct)
...
 
-            var outerProjection = new StructuralTypeProjectionExpression(
-                projection1.StructuralType, propertyExpressions, tableMap, nullable: false, discriminatorExpression);
+                Check.DebugAssert(
+                    structuralProjection1.TableMap.Count == structuralProjection2.TableMap.Count,
+                    "Set operation over entity projections with different table map counts");
+                Check.DebugAssert(
+                    structuralProjection1.TableMap.Keys.All(t => structuralProjection2.TableMap.ContainsKey(t)),
+                    "Set operation over entity projections with table map discrepancy");
+                Check.DebugAssert(
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2168]: idk if these are needed, could already be enforced elsewhere

**Comment by maumar** [comment]
found some more issues around this, converting to draft for now

File: src/EFCore.Relational/Query/StructuralTypeProjectionExpression.cs [hunk 3]
```diff
@@ -124,6 +151,18 @@ protected override Expression VisitChildren(ExpressionVisitor visitor)
             propertyExpressionMap[property] = newExpression;
         }
 
+        var complexPropertyCache = default(Dictionary<IComplexProperty, StructuralTypeShaperExpression>);
```
Comment (maumar) [inline src/EFCore.Relational/Query/StructuralTypeProjectionExpression.cs:154]: this is a bit scary @roji

**Comment by roji** [comment]
@maumar wrote some thoughts offline, let's discuss.

**Review by roji — APPROVED** [review]
As discussed offline, this seems like an OK fix. The one possible issue is the very eager recursive generation of the entire complex type tree, which isn't great perf-wise; ideally we'd only generate shapers more lazily, as they are being bound in the query (as we do for (non-JSON) owned entity types).

But it seems like this adds considerable complexity, so let's go with this for now - we can revisit this when we work on complex type JSON mapping. I also have some more extreme query architecture thoughts about doing things simpler (fully separate query from shaper side, have the query always have its projection populated, and reference columns in that projection by position from the shaper). If that happens we'll redo most of this anyway.

Thanks for working on this @maumar - this was my design fail for complex types in 8.0...
