### PR TITLE
NullReferenceException when trying to seed a keyless entity #23030

### LINKED ISSUE #23030: NullReferenceException when trying to seed a keyless entity
Repro:

```c#

await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(...);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>()
            .HasNoKey()
            .HasData(new Blog { Name = "foo" });
    }
}

public class Blog
{
    public string Name { get; set; }
}
```

Happens on both the latest 5.0 and 3.1.

### PR DESCRIPTION
**Pull request by umitkavala**
Fixes #23030
I'm not sure about tests. Is it enough or correct place? I've changed base class so implemented classes also should change.
Maybe we can create new test class?

### CODE REVIEW

**Comment by umitkavala** [comment]
SqlServer & SqlLite tests passed but InMemory couldn't because its depend on CreateFactory has key. 
I assume this fix should apply for all DB types right? 
```c#
private Func<IInMemoryTable> CreateTable([NotNull] IEntityType entityType, IInMemoryTable baseTable)
=> (Func<IInMemoryTable>)typeof(InMemoryTableFactory).GetTypeInfo()
	.GetDeclaredMethod(nameof(CreateFactory))
	.MakeGenericMethod(entityType.FindPrimaryKey().GetKeyType())
	.Invoke(null, new object[] { entityType, baseTable, _sensitiveLoggingEnabled, _nullabilityCheckEnabled });

[UsedImplicitly]
private static Func<IInMemoryTable> CreateFactory<TKey>(
IEntityType entityType,
IInMemoryTable baseTable,
bool sensitiveLoggingEnabled,
bool nullabilityCheckEnabled)
=> () => new InMemoryTable<TKey>(entityType, baseTable, sensitiveLoggingEnabled, nullabilityCheckEnabled);
```

**Comment by ajcvickers** [comment]
@umitkavala This does not look like the correct fix. The comment from Smit in #23030 says:

> Keyless entities don't have keys so they cannot be seeded using state manager based seeding implementation.
> Should throw a better validation or need different implementation for seeding.

This means the correct resolution for this bug is to throw an InvalidOperationException with a message indicating that seeding keyless entity types are not supported.

**Comment by umitkavala** [comment]
@ajcvickers Sure. I'll implement that way. I couldn't make sure that's why I've created as draft. And this rule apply for all right? SqlServer, InMemory, SqlLite. So in that case test I can add test case to the SeedingTestBase.cs

**Comment by ajcvickers** [comment]
@umitkavala Sounds good.

**Comment by umitkavala** [comment]
I did required changes.

File: src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs [hunk 1]
```diff
@@ -1585,7 +1585,11 @@ public virtual bool IsKeyUnknown
         {
             get
             {
-                var keyProperties = ((EntityType)EntityType).FindPrimaryKey().Properties;
+                var keyProperties = ((EntityType)EntityType).FindPrimaryKey()?.Properties;
+                if (keyProperties == null)
```
Comment (smitpatel) [inline src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs:1589]: The exception should be thrown from either HasData call on entity type which is configured as keyless or in model validation. The latter would help if an entity type is configured with HasData before being marked as keyless.

@AndriySvyryd - Where should we put it?

Comment (AndriySvyryd) [reply src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs:1589]: Doing it in ModelValidator would be best

Comment (umitkavala) [reply src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs:1589]: I'll move it to ModelValidator than.

Comment (umitkavala) [reply src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs]: done

File: src/EFCore/Infrastructure/ModelValidator.cs [hunk 2]
```diff
@@ -1110,6 +1111,29 @@ protected virtual void ValidateData([NotNull] IModel model, [NotNull] IDiagnosti
             }
         }
 
+        /// <summary>
+        ///     Validates the key of seeding data in the model
+        /// </summary>
+        /// <param name="model"> The model to validate. </param>
+        /// <param name="logger"> The logger to use. </param>
+        protected virtual void ValidateKeylessSeed([NotNull] IModel model, [NotNull] IDiagnosticsLogger<DbLoggerCategory.Model.Validation> logger)
```
Comment (smitpatel) [inline src/EFCore/Infrastructure/ModelValidator.cs:1119]: This should go inside ValidateData method. Currently we are skipping over keyless entity. We should validate no has data at the same time.

Comment (umitkavala) [reply src/EFCore/Infrastructure/ModelValidator.cs:1119]: I can access IsKeyless with IConventionModel. If I move this into ValidateData;
image
It will check after data validation right?

Comment (smitpatel) [reply src/EFCore/Infrastructure/ModelValidator.cs:1119]: There is key==null check already which is same as entityType.IsKeyless. It will go inside that if block and not separate like above.

**Comment by umitkavala** [comment]
Can I convert this draft to PR for final review?

File: src/EFCore/Properties/CoreStrings.resx [hunk 3]
```diff
@@ -1318,6 +1318,9 @@
   <data name="SeedDatumSignedNumericValue" xml:space="preserve">
     <value>The seed entity for entity type '{entityType}' cannot be added because a non-zero value is required for property '{property}'. Consider providing a negative value to avoid collisions with non-seed data.</value>
   </data>
+  <data name="SeedKeylessEntity" xml:space="preserve">
+    <value>The seed entity for entity type '{entityType}' cannot be added because keyless entity types are not supported. Consider providing a key to seed data or use this entity for query only.</value>
```
Comment (AndriySvyryd) [inline src/EFCore/Properties/CoreStrings.resx:1322]:
```suggestion
    <value>The seed entity for entity type '{entityType}' cannot be added because keyless entity types are not supported. Consider providing a key or removing the seed data.</value>
```

File: test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs [hunk 4]
```diff
@@ -16,6 +19,15 @@ protected override SeedingContext CreateContextWithEmptyDatabase(string testId)
...
         }
 
+        protected override KeylessSeedingContext CreateKeylessContextWithEmptyDatabase(string testId)
+        {
+            var context = new KeylessSeedingInMemoryContext(testId);
+
+            context.Database.EnsureClean();
+
+            return context;
+        }
```
Comment (AndriySvyryd) [inline test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:29]: This can go in the base class

**Review by AndriySvyryd — APPROVED** [review]

File: test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs [hunk 5]
```diff
@@ -8,6 +8,9 @@ public class SeedingInMemoryTest : SeedingTestBase
         protected override SeedingContext CreateContextWithEmptyDatabase(string testId)
             => new SeedingInMemoryContext(testId);
 
+        protected override KeylessSeedingContext CreateKeylessContextWithEmptyDatabase(string testId)
+        => new KeylessSeedingInMemoryContext(testId);
```
Comment (smitpatel) [inline test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs:12]:
```suggestion
            => new KeylessSeedingInMemoryContext(testId);
```

File: test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs [hunk 6]
```diff
@@ -18,5 +21,15 @@ public SeedingInMemoryContext(string testId)
             protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
                 => optionsBuilder.UseInMemoryDatabase($"Seeds{TestId}");
         }
+        protected class KeylessSeedingInMemoryContext : KeylessSeedingContext
```
Comment (smitpatel) [inline test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs:24]:
```suggestion

        protected class KeylessSeedingInMemoryContext : KeylessSeedingContext
```

File: test/EFCore.Specification.Tests/SeedingTestBase.cs [hunk 7]
```diff
@@ -31,8 +33,32 @@ public virtual async Task Seeding_does_not_leave_context_contaminated(bool async
...
+                    using var context = CreateKeylessContextWithEmptyDatabase(async ? "1A" : "1S");
+                    var _ = async
+                        ? await context.Database.EnsureCreatedResilientlyAsync()
+                        : context.Database.EnsureCreatedResiliently();
+
+                    Assert.Empty(context.ChangeTracker.Entries());
+
+                    var seeds = context.Set<KeylessSeed>().OrderBy(e => e.Species).ToList();
+
+                    Assert.Empty(seeds);
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/SeedingTestBase.cs:53]:
```suggestion
                    using var context = CreateKeylessContextWithEmptyDatabase(async ? "1A" : "1S");
                    var _ = async
                        ? await context.Database.EnsureCreatedResilientlyAsync()
                        : context.Database.EnsureCreatedResiliently();
```

File: test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs [hunk 8]
```diff
@@ -26,5 +38,16 @@ public SeedingSqlServerContext(string testId)
             protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
                 => optionsBuilder.UseSqlServer(SqlServerTestStore.CreateConnectionString($"Seeds{TestId}"));
         }
+        protected class KeylessSeedingInMemoryContext : KeylessSeedingContext
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:41]:
```suggestion

        protected class KeylessSeedingInMemoryContext : KeylessSeedingContext
```

File: test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs [hunk 9]
```diff
@@ -26,5 +38,16 @@ public SeedingSqlServerContext(string testId)
...
+        {
+            public KeylessSeedingInMemoryContext(string testId)
+                : base(testId)
+            {
+            }
+
+            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
+                => optionsBuilder.UseSqlServer(SqlServerTestStore.CreateConnectionString($"Seeds{TestId}"));
+        }
+
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:51]:
```suggestion
```

File: test/EFCore.Sqlite.FunctionalTests/SeedingSqliteTest.cs [hunk 10]
```diff
@@ -14,13 +14,32 @@ protected override SeedingContext CreateContextWithEmptyDatabase(string testId)
...
         {
             public SeedingSqliteContext(string testId)
                 : base(testId)
             {
             }
 
+            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
+                => optionsBuilder.UseSqlite(($"Data Source = Seeds{TestId}.db"));
+        }
+        protected class KeylessSeedingInMemoryContext : KeylessSeedingContext
```
Comment (smitpatel) [inline test/EFCore.Sqlite.FunctionalTests/SeedingSqliteTest.cs:36]:
```suggestion

        protected class KeylessSeedingInMemoryContext : KeylessSeedingContext
```

File: test/EFCore.Sqlite.FunctionalTests/SeedingSqliteTest.cs [hunk 11]
```diff
@@ -14,13 +14,32 @@ protected override SeedingContext CreateContextWithEmptyDatabase(string testId)
...
+        {
+            public KeylessSeedingInMemoryContext(string testId)
```
Comment (smitpatel) [inline test/EFCore.Sqlite.FunctionalTests/SeedingSqliteTest.cs:38]: Use a different database name like InMemory

File: test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs [hunk 12]
```diff
@@ -246,6 +246,10 @@ protected class Product
             [NotMapped]
             public virtual ICollection<Order> Orders { get; set; }
         }
+        protected class KeylessSeed
```
Comment (smitpatel) [inline test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs:249]:
```suggestion

        protected class KeylessSeed
```

File: test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs [hunk 13]
```diff
@@ -26,5 +38,16 @@ public SeedingSqlServerContext(string testId)
...
         }
+        protected class KeylessSeedingInMemoryContext : KeylessSeedingContext
+        {
+            public KeylessSeedingInMemoryContext(string testId)
+                : base(testId)
+            {
+            }
+
+            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
+                => optionsBuilder.UseSqlServer(SqlServerTestStore.CreateConnectionString($"Seeds{TestId}"));
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:49]: Use a different database name like InMemory

File: test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs (hunk 8 above)
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:41]: Rename the context name

File: test/EFCore.Sqlite.FunctionalTests/SeedingSqliteTest.cs (hunk 10 above)
Comment (smitpatel) [inline test/EFCore.Sqlite.FunctionalTests/SeedingSqliteTest.cs:36]: Rename the context name

File: test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs (hunk 13 above)
Comment (umitkavala) [reply test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:50]: done

File: test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs (hunk 8 above)
Comment (umitkavala) [reply test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:42]: done

File: test/EFCore.Sqlite.FunctionalTests/SeedingSqliteTest.cs (hunk 10 above)
Comment (umitkavala) [reply test/EFCore.Sqlite.FunctionalTests/SeedingSqliteTest.cs:37]: done

File: test/EFCore.Sqlite.FunctionalTests/SeedingSqliteTest.cs (hunk 11 above)
Comment (umitkavala) [reply test/EFCore.Sqlite.FunctionalTests/SeedingSqliteTest.cs:39]: done

File: test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs (hunk 4 above)
Comment (umitkavala) [reply test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:29]: So I need to move extensions EnsureClean to the base for Sqlite and Sqlserver?

Comment (AndriySvyryd) [reply test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:29]: You can use `TestStore.Clean` instead, see other test classes

Comment (umitkavala) [reply test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:29]: I just little bit stuck here. I've looked at other test classes; only 2 of them using TestStore.Clean but eventually they call  EnsureClean methods:
https://github.com/dotnet/efcore/blob/2e9d93925c6a1a1be9b9bef7ad8af93589e72477/test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs#L142

So what I understand is; I need to inject TestStore to **SeedingTestBase** and call TestStore.Clean(context) for each test (below) and this will call Clean method for SqlServerTestStore or SqliteTestStore.
```c#
        public virtual async Task Seeding_does_not_leave_context_contaminated(bool async)

        public virtual async Task Seeding_keyless_entity_throws_exception(bool async)
 
```

Comment (AndriySvyryd) [reply test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:29]: Yes, but if you're still having issues making it work you can leave the duplicate code

Comment (umitkavala) [reply test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs]: I think I figured it out.

File: test/EFCore.Specification.Tests/SeedingTestBase.cs [hunk 14]
```diff
@@ -31,8 +35,29 @@ public virtual async Task Seeding_does_not_leave_context_contaminated(bool async
...
+        public virtual async Task Seeding_keyless_entity_throws_exception(bool async)
+        {
+            var exception = await Assert.ThrowsAsync<InvalidOperationException>(
+                async () =>
+                {
+                    using var context = CreateKeylessContextWithEmptyDatabase(async ? "1A" : "1S");
+                    var _ = async
+                        ? await context.Database.EnsureCreatedResilientlyAsync()
+                        : context.Database.EnsureCreatedResiliently();
+                    TestStore.Clean(context);
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/SeedingTestBase.cs:50]: This code won't be executed as EnsureCreated will throw before.

Comment (umitkavala) [reply test/EFCore.Specification.Tests/SeedingTestBase.cs]: done.

**Comment by umitkavala** [comment]
Hi @AndriySvyryd, I think this PR is ready.

File: test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs [hunk 15]
```diff
@@ -1,13 +1,20 @@
 // Copyright (c) .NET Foundation. All rights reserved.
 // Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
 
+using Microsoft.EntityFrameworkCore.TestUtilities;
+
 namespace Microsoft.EntityFrameworkCore
 {
     public class SeedingInMemoryTest : SeedingTestBase
     {
+        protected override TestStore TestStore => InMemoryTestStore.Create("inMemoryTestStore");
```
Comment (AndriySvyryd) [inline test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs:10]:
```suggestion
        protected override TestStore TestStore => InMemoryTestStore.Create("SeedingTest");
```

File: test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs [hunk 16]
```diff
@@ -1,20 +1,22 @@
...
+using Xunit;
 
 namespace Microsoft.EntityFrameworkCore
 {
     public class SeedingSqlServerTest : SeedingTestBase
     {
-        protected override SeedingContext CreateContextWithEmptyDatabase(string testId)
-        {
-            var context = new SeedingSqlServerContext(testId);
+        protected override TestStore TestStore => SqlServerTestStore.Create("sqlServerTestStore");
```
Comment (AndriySvyryd) [inline test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:13]:
```suggestion
        protected override TestStore TestStore => SqlServerTestStore.Create("SeedingTest");
```

File: test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs [hunk 17]
```diff
@@ -18,5 +25,16 @@ public SeedingInMemoryContext(string testId)
             protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
                 => optionsBuilder.UseInMemoryDatabase($"Seeds{TestId}");
```
Comment (AndriySvyryd) [inline test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs:26]:
```suggestion
                => optionsBuilder.UseInMemoryDatabase("SeedingTest");
```

File: test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs [hunk 18]
```diff
@@ -18,5 +25,16 @@ public SeedingInMemoryContext(string testId)
...
+
+        protected class KeylessSeedingInMemoryContext : KeylessSeedingContext
+        {
+            public KeylessSeedingInMemoryContext(string testId)
+                : base(testId)
+            {
+            }
+
+            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
+                => optionsBuilder.UseInMemoryDatabase($"KeylessSeeds{TestId}");
```
Comment (AndriySvyryd) [inline test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs:37]:
```suggestion
                => optionsBuilder.UseInMemoryDatabase("SeedingTest");
```

File: test/EFCore.Specification.Tests/SeedingTestBase.cs [hunk 19]
```diff
@@ -54,5 +78,26 @@ protected class Seed
 
             public string Species { get; set; }
         }
+
+        protected abstract class KeylessSeedingContext : DbContext
+        {
+            public string TestId { get; }
+
+            protected KeylessSeedingContext(string testId)
+                => TestId = testId;
```
Comment (AndriySvyryd) [inline test/EFCore.Specification.Tests/SeedingTestBase.cs:87]:
```suggestion
            protected KeylessSeedingContext(DbContextOptions options)
                : base(options)
            {
            }
```

File: test/EFCore.Specification.Tests/SeedingTestBase.cs [hunk 20]
```diff
@@ -31,8 +34,29 @@ public virtual async Task Seeding_does_not_leave_context_contaminated(bool async
...
+                        : context.Database.EnsureCreatedResiliently();
+                });
+            Assert.Equal(CoreStrings.SeedKeylessEntity(nameof(KeylessSeed)), exception.Message);
+        }
+
+        protected abstract TestStore TestStore { get; }
+
         protected abstract SeedingContext CreateContextWithEmptyDatabase(string testId);
 
+        protected abstract KeylessSeedingContext CreateKeylessContextWithEmptyDatabase(string testId);
```
Comment (AndriySvyryd) [inline test/EFCore.Specification.Tests/SeedingTestBase.cs:58]:
```suggestion
        protected virtual KeylessSeedingContext CreateKeylessContextWithEmptyDatabase()
            => new KeylessSeedingContext(TestStore.AddProviderOptions(new DbContextOptionsBuilder()).Options)
```

Comment (umitkavala) [reply test/EFCore.Specification.Tests/SeedingTestBase.cs:58]: KeylessSeedingContext won't be abstract anymore and we won't need KeylessSeedingContext implementations on other classes (KeylessSeedingSqlServerContext, KeylessSeedingSqliteContext, KeylessSeedingInMemoryContext)
```c#
public class KeylessSeedingContext : DbContext
        {
            public KeylessSeedingContext(DbContextOptions options)
                : base(options)
            {
            }
```

File: test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs (hunk 15 above)
Comment (umitkavala) [reply test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs:10]: done

File: test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs (hunk 16 above)
Comment (umitkavala) [reply test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs:13]: done

File: test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs (hunk 17 above)
Comment (umitkavala) [reply test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs:26]: done

File: test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs (hunk 18 above)
Comment (umitkavala) [reply test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs:37]: done

File: test/EFCore.Specification.Tests/SeedingTestBase.cs (hunk 19 above)
Comment (umitkavala) [reply test/EFCore.Specification.Tests/SeedingTestBase.cs:87]: done

**Review by AndriySvyryd — APPROVED** [review]

**Comment by AndriySvyryd** [comment]
Thanks for your contribution

**Comment by umitkavala** [comment]
Thanks.
