### PR TITLE
Fixed lazy loading thread safety

### LINKED ISSUE #35528: Lazy loading is not thread safe
### Bug description

When acessing a lazy loading property that is kinda heavy do load (a lot of data in the db), and doing it with heavy concurrency, the lazy loader fails

sometimes the lazy loading property becomes null, and then after a short period of time it gets the value
and sometimes the lazy loader throw exeptions

### Your code

```csharp
I unfortly cant show the exact code because it's from my job, but it is basically that


var someEntity = _dbContext.SomeDbSet.FirstOrDefault();

var parallelOptions = new ParallelOptions { MaxDegreeOfParallelism = 1000 };
  Parallel.For(0, 60000, parallelOptions, i =>
  {
     var var1 =  someEntity.SomeLazyLoadICollection;
     var var2 =  someEntity.SomeLazyLoadICollection2;
     var var3 =  someEntity.SomeLazyLoadProp;
     var var4 =  someEntity.SomeLazyLoadICollection3;
     var var5 =  someEntity.SomeLazyLoadICollection4;
     var var6 =  someEntity.SomeLazyLoadICollection5;
  });
```

### Stack traces

```text

```

### Verbose output

```text

```

### EF Core version

9.0.1

### Database provider

Microsoft.EntityFrameworkCore.SqlServer

### Target framework

.NET 9.0

### Operating system

Windows 10

### IDE

Visual Studio 2022 17.12.4

### PR DESCRIPTION
**Pull request by henriquewr**
Added sync for lazy loading

Fixes #35528

### CODE REVIEW

**Comment by henriquewr** [comment]
@dotnet-policy-service agree

File: src/EFCore/Infrastructure/Internal/LazyLoader.cs [hunk 1]
```diff
@@ -107,31 +109,48 @@ public virtual void Load(object entity, [CallerMemberName] string navigationName
         Check.NotEmpty(navigationName, nameof(navigationName));
 
         var navEntry = (entity, navigationName);
-        if (_isLoading.TryAdd(navEntry, true))
+
+        var willWait = true;
+        TaskCompletionSource taskCompletionSource;
+
+        lock (_isLoadingLock)
```
Comment (henriquewr) [inline src/EFCore/Infrastructure/Internal/LazyLoader.cs:116]: i don't know exactly why
but i need do lock the access to the GetOrAdd, otherwise the code breaks again
my guess it's because of the implementation of GetOrAdd which are 2 separete methods

```
if (!TryGetValueInternal(tables, key, hashcode, out TValue? resultingValue))
{
    TryAddInternal(tables, key, hashcode, valueFactory(key), updateIfExists: false, acquireLock: true, out resultingValue);
}
```

**Comment by AndriySvyryd** [comment]
@henriquewr Could you explain what the issue in the original code was? It seems that it made some incorrect assumption, but I don't see what it was exactly

**Comment by AndriySvyryd** [comment]
Oh, I see. While it prevented a second thread from loading it didn't make it wait for the first thread to finish.

**Comment by henriquewr** [comment]
@AndriySvyryd Exacly that what i was going to say

File: test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs [hunk 2]
```diff
@@ -67,6 +68,70 @@ public virtual void Can_use_proxies_from_multiple_threads_when_navigations_alrea
         Task.WaitAll(tests.Select(Task.Run).ToArray());
     }
 
+    [ConditionalTheory] // Issue #35528
+    [InlineData(false)]
+    [InlineData(true)]
+    public virtual void Lazy_loading_is_thread_safe(bool noTracking)
```
Comment (AndriySvyryd) [inline test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs:74]: Add an async version

File: test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs [hunk 3]
```diff
@@ -67,6 +68,70 @@ public virtual void Can_use_proxies_from_multiple_threads_when_navigations_alrea
...
+                Assert.Equal(singleShadowFk, parent2.SingleShadowFk!.Id);
+                Assert.Equal(childrenCompositeKey, parent2.ChildrenCompositeKey!.Select(x => x.Id).OrderBy(x => x).ToList());
+                Assert.Equal(singleCompositeKey, parent2.SingleCompositeKey!.Id);
+                Assert.Equal(withRecursiveProperty, parent2.WithRecursiveProperty!.Id);
+                Assert.Equal(manyChildren, parent2.ManyChildren!.Select(x => x.Id).OrderBy(x => x).ToList());
+            });
+        }
+        catch (Exception ex)
+        {
+            Assert.Fail($"Lazy loading is not thread safe exception: {ex.Message}");
```
[the remark this answers is not in the document]
Comment (henriquewr) [reply test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs]: Fixed in the last commit

File: test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs (hunk 2 above)
Comment (henriquewr) [reply test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs]: Fixed in the last commit

File: src/EFCore/Infrastructure/Internal/LazyLoader.cs [hunk 4]
```diff
@@ -150,31 +178,52 @@ public virtual async Task LoadAsync(
...
         {
-            try
+            ref var refIsLoadingValue = ref CollectionsMarshal.GetValueRefOrAddDefault(_isLoading, navEntry, out exists);
+            if (!exists)
             {
-                // ShouldLoad is called after _isLoading.Add because it could attempt to load the property. See #13138.
-                if (ShouldLoad(entity, navigationName, out var entry))
+                refIsLoadingValue = (new TaskCompletionSource(), Environment.CurrentManagedThreadId);
```
Comment (AndriySvyryd) [inline src/EFCore/Infrastructure/Internal/LazyLoader.cs:190]: Instead of storing the thread id in `_isLoading` consider storing `navEntry` in an `AsyncLocal` list, basically keeping a stack of nested calls

File: src/EFCore/Infrastructure/Internal/LazyLoader.cs [hunk 5]
```diff
@@ -107,30 +110,55 @@ public virtual void Load(object entity, [CallerMemberName] string navigationName
...
+            {
+                refIsLoadingValue = (new(), new());
+            }
+            isLoadingValue = refIsLoadingValue!;
+            isLoadingValue.Depth.Value++;
+        }
+
+        if (exists)
+        {
+            if (isLoadingValue.Depth.Value == 1)
```
Comment (AndriySvyryd) [inline src/EFCore/Infrastructure/Internal/LazyLoader.cs:130]: This is an interesting optimization. It definitely warrants a comment on how it works as the next person to read this code will be very confused.

@roji @cincuranet What's your opinion of this usage of `AsyncLocal`?

**Comment by AndriySvyryd** [comment]
Thanks for your contribution!

**Comment by henriquewr** [comment]
You're welcome, I'm happy to contribute
