### PR TITLE
[release/7.0] Fix to #29279 - EF7 - GroupBy on Json column property + First/FirstOrDefault generates incorrect SQL

### LINKED ISSUE #29279: EF7 - GroupBy on Json column property + First/FirstOrDefault generates incorrect SQL
I've attached a minimal repo that produces the exception.

https://github.com/alienwareone/EfCoreGroupByJsonColumnProperty

### PR DESCRIPTION
**Pull request by maumar**
Problem was that in VisitChildren for JsonQueryExpression we were not passing key columns stored in _keyPropertyMap thru the visitor, so the aliases got out of sync. Fix is to process these key columns also and then update the JsonQueryExpression with new map if any of the columns have been modified by the visitor.

Fixes #29279

### Customer impact

Exception in a relatively simple GroupBy + paging scenario involving new JSON mapping feature.

### How found

Found by a customer testing EF7 bits.

### Regression

No, this is in the new feature.

### Testing

New testing added for the reported scenario and additional cases around it.

### Risk

Low, only affects JSON scenarios (code change is in the new class that only gets created to traverse JSON expressions). It should be safe to pass key columns through the visitor - we already do that for the JSON column. Could be unnecessary work, but safe.

### CODE REVIEW

File: src/EFCore.Relational/Query/JsonQueryExpression.cs [hunk 1]
```diff
@@ -195,9 +195,19 @@ public virtual void Print(ExpressionPrinter expressionPrinter)
...
+            newKeyPropertyMap[property] = newColumn;
+            if (newColumn != column)
+            {
+                changed = true;
+            }
+        }
 
-        // TODO: also visit columns in the _keyPropertyMap?
-        return Update(jsonColumn, _keyPropertyMap);
+        return Update(jsonColumn, changed ? newKeyPropertyMap : _keyPropertyMap);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/JsonQueryExpression.cs:210]: - You populate the newKeyPropertyMap regardless of changed so conditional is not necessary.
- Update does deep comparison on the map, since you already know based on changed if it is changed or not, consider inline-ing the new call rather than calling update.

**Review by smitpatel — APPROVED** [review]
