### PR TITLE
Fix to #28595 - Use partial updates for JSON

### LINKED ISSUE #28595: Use partial updates for JSON

### PR DESCRIPTION
**Pull request by maumar**
Currently, whenever we update/add/delete part of aggregate mapped to JSON column, we were replacing the entire structure.
Improvement is to use JSON_MODIFY which can alter just a portion of JSON structure, give a JSON path.
We analyze the entries that are being edited and for each JSON column we find the common denominator that needs to be replaced to accommodate all the requested changes

Note: Whenever we add/remove element from a collection we need to replace the entire collection in order to populate ordinal key values properly.
Also, modifying a single property is not yet supported - the smallest fragment that will be replaced is one that represents an entity.

Fixes #28595

### CODE REVIEW

File: src/EFCore.Relational/Update/ModificationCommand.cs [hunk 1]
```diff
@@ -290,74 +312,107 @@ private List<IColumnModification> GenerateColumnModifications()
...
+                if (!jsonEntry && entry.EntityType.IsMappedToJson())
+                {
+                    jsonEntry = true;
+                }
             }
         }
 
-        var processedJsonNavigations = new List<INavigation>();
-        foreach (var entry in _entries)
+        var jsonColumnsUpdateMap = new Dictionary<string, List<JsonPartialUpdatePathEntry>>();
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Update/ModificationCommand.cs:323]: Declare inside `if`

File: src/EFCore.Relational/Update/ModificationCommand.cs [hunk 2]
```diff
@@ -250,13 +251,34 @@ public virtual IColumnModification AddColumnModification(in ColumnModificationPa
     protected virtual IColumnModification CreateColumnModification(in ColumnModificationParameters columnModificationParameters)
         => new ColumnModification(columnModificationParameters);
 
+    private sealed class JsonPartialUpdatePathEntry
```
Comment (smitpatel) [inline src/EFCore.Relational/Update/ModificationCommand.cs:254]: may be record?

File: src/EFCore.Relational/Update/ModificationCommand.cs [hunk 3]
```diff
@@ -290,74 +312,107 @@ private List<IColumnModification> GenerateColumnModifications()
...
                 }
 
-                var navigation = currentOwnership.GetNavigation(pointsToPrincipal: false)!;
-                if (processedJsonNavigations.Contains(navigation))
+                if (jsonColumnsUpdateMap.TryGetValue(jsonColumn, out var currentJsonPartialUpdateInfo))
                 {
-                    continue;
+                    jsonPartialUpdateInfo = FindCommonJsonPartialUpdateInfo(
+                        currentJsonPartialUpdateInfo,
+                        jsonPartialUpdateInfo);
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Update/ModificationCommand.cs:345]: So this we collapse all modifications for a given column into one call. Is there an issue tracking making this more fine-grained and issuing multiple `JSON_MODIFY`?

File: src/EFCore.Relational/Update/ModificationCommand.cs [hunk 4]
```diff
@@ -290,74 +312,107 @@ private List<IColumnModification> GenerateColumnModifications()
...
+                }
 
-                var json = CreateJson(
-                    navigationValue,
-                    currentEntry,
-                    currentOwnership.DeclaringEntityType,
-                    ordinal: null,
-                    isCollection: navigation.IsCollection);
+                var jsonPathString = string.Join(
+                    ".", updatePath.Select(x => x.PropertyName + (x.Ordinal != null ? "[" + x.Ordinal + "]" : "")));
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Update/ModificationCommand.cs:391]: Do we need to refactor this out (as well as the initial "$") for other providers to customize? Or this actually the same everywhere?
@roji

Comment (AndriySvyryd) [reply src/EFCore.Relational/Update/ModificationCommand.cs:391]: Do we have an issue to support non-primitive collections indexed by arbitrary values in JSON and not just ordinal?

File: src/EFCore.Relational/Update/ModificationCommand.cs (hunk 3 above)
Comment (maumar) [reply src/EFCore.Relational/Update/ModificationCommand.cs:345]: will file one

Comment (maumar) [reply src/EFCore.Relational/Update/ModificationCommand.cs:345]: #28855 28855

File: src/EFCore.Relational/Update/ModificationCommand.cs (hunk 2 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Update/ModificationCommand.cs:254]: struct

File: src/EFCore.Relational/Update/ModificationCommand.cs [hunk 5]
```diff
@@ -250,13 +251,34 @@ public virtual IColumnModification AddColumnModification(in ColumnModificationPa
     protected virtual IColumnModification CreateColumnModification(in ColumnModificationParameters columnModificationParameters)
         => new ColumnModification(columnModificationParameters);
 
+    private sealed record JsonPartialUpdatePathEntry
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Update/ModificationCommand.cs:254]:
```suggestion
    private record struct JsonPartialUpdatePathEntry
```

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore.Relational/Update/ModificationCommand.cs (hunk 4 above)
Comment (maumar) [reply src/EFCore.Relational/Update/ModificationCommand.cs:391]: we only have #28594 for using persisting key props

Comment (maumar) [reply src/EFCore.Relational/Update/ModificationCommand.cs:391]: #28861

Comment (maumar) [reply src/EFCore.Relational/Update/ModificationCommand.cs:391]: https://github.com/dotnet/efcore/issues/4021#issuecomment-1033896410 - seems that json path is roughly the same everywhere, according to @roji's write-up for the big json issue
