### PR TITLE
Fix to #30922 - Most cases of projecting a primitive collection don't work

### LINKED ISSUE #30922: Most cases of projecting a primitive collection don't work
```C#
using (var context = new SomeDbContext())
{
    context.Database.EnsureDeleted();
    context.Database.EnsureCreated();

    var days = await context.Walks
        .Select(e => e.DaysVisited.OrderBy(e => e.Day).ToList())
        .ToListAsync();
}

public class DogWalk
{
    public int Id { get; set; }
    public List<DateOnly> DaysVisited { get; private set; } = new();
}

public class SomeDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Database=AllTogetherNow")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    public DbSet<DogWalk> Walks => Set<DogWalk>();
}
```

```
Unhandled exception. System.InvalidOperationException: Unable to translate a collection subquery in a projection since either parent or the subquery doesn't project necessary information required to uniquely identify it and correctly generate results on the client side. This can happen when trying to correlate
on keyless entity type. This can also happen for some cases of projection before 'Distinct' or some shapes of grouping key in case of 'GroupBy'. These should either contain all key properties of the entity that the operation is applied on, or only contain simple property access expressions.
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyProjection(Expression shaperExpression, ResultCardinality resultCardinality, QuerySplittingBehavior querySplittingBehavior)
   at Microsoft.EntityFrameworkCore.Query.Internal.SelectExpressionProjectionApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\local\code\AllTogetherNow\Daily\Daily.cs:line 14
   at Program.<Main>(String[] args)
```

### PR DESCRIPTION
**Pull request by maumar**
Problem was that for cases that compose on the collection of primitives and then project it, we need identifier to properly bucket the results. On SqlServer we can use hidden key column that is a result of OPENJSON - we need something that is unique so we can't use the value itself. Fix is to add identifier to the SelectExpression based on OPENJSON and also modify the logic that figures out if we need key (and thus need to revert to OPENJSON without WITH clause). Also some minor fixes around nullability - when projecting element of a collection of primitives using OUTER APPLY/JOIN we must set the projection binding to nullable, as the value can always be null, in case of empty collection.

Fixes #30922

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -2352,6 +2401,10 @@ private void ApplySetOperation(SetOperationType setOperationType, SelectExpressi
                 else if (otherExpressions.All(e => e is ColumnExpression))
                 {
                     _identifier.AddRange(entityProjectionIdentifiers.Zip(entityProjectionValueComparers));
+
+                    //TODO:
+                    // Parameter_collection_in_subquery_Union_column_collection_as_compiled_query
+                    // type mapping for the value column is null here
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2407]: @roji

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs [hunk 2]
```diff
@@ -111,30 +112,72 @@ public Expression Process(Expression expression)
...
-                case SelectExpression
+                case SelectExpression selectExpression:
                 {
-                    Tables: [SqlServerOpenJsonExpression { ColumnInfos: not null } openJsonExpression, ..],
-                    Orderings:
-                    [
+                    var newTables = new List<TableExpressionBase>();
+                    var castsToApply = new Dictionary<(SqlServerOpenJsonExpression, string), RelationalTypeMapping>();
+
+                    foreach (var table in selectExpression.Tables)
```
Comment (maumar) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:120]: this requires "some" cleanup

File: test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs [hunk 3]
```diff
@@ -480,6 +480,26 @@ public override Task Parameter_collection_in_subquery_Count_as_compiled_query(bo
     public override Task Column_collection_in_subquery_Union_parameter_collection(bool async)
         => AssertCompatibilityLevelTooLow(() => base.Column_collection_in_subquery_Union_parameter_collection(async));
 
+    public override Task Project_collection_of_ints_simple(bool async)
+    {
+        return base.Project_collection_of_ints_simple(async);
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs:485]: @roji those scenarios don't work on old sql - expected?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 4]
```diff
@@ -130,6 +130,51 @@ internal SelectExpression(SqlExpression? projection)
...
+    /// </summary>
+    /// <param name="identidierColumnName">The name of the column to use as identifier.</param>
+    /// <param name="identifierColumnType">The type of the column to use as identifier.</param>
+    /// <param name="identifierColumnTypeMapping">The type mapping of the column to use as identifier.</param>
+    /// <param name="tableExpression">The table expression.</param>
+    /// <param name="columnName">The name of the column to add as the projection.</param>
+    /// <param name="columnType">The type of the column to add as the projection.</param>
+    /// <param name="columnTypeMapping">The type mapping of the column to add as the projection.</param>
+    /// <param name="isColumnNullable">Whether the column projected out is nullable.</param>
+    public SelectExpression(
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:145]: could/will collapse both ctors and add defaults for identifier columns

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 5]
```diff
@@ -1180,7 +1225,11 @@ static Expression RemoveConvert(Expression expression)
                     {
                         var innerSelectExpression = (SelectExpression)shapedQueryExpression.QueryExpression;
                         if (_identifier.Count == 0
-                            || innerSelectExpression._identifier.Count == 0)
+                            || (innerSelectExpression is not SelectExpression
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1228]: will remove

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs [hunk 6]
```diff
@@ -111,30 +112,72 @@ public Expression Process(Expression expression)
...
+                                newTables.Add(newTable);
+
+                                foreach (var column in openJsonExpression.ColumnInfos!)
+                                {
+                                    var typeMapping = _typeMappingSource.FindMapping(column.StoreType);
+                                    Check.DebugAssert(
+                                        typeMapping is not null,
+                                        $"Could not find mapping for store type {column.StoreType} when converting OPENJSON/WITH");
+
+                                    castsToApply.Add((newOpenJsonExpression, column.Name), typeMapping);
```
Comment (maumar) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:168]: actually now that I think about it, I can just store casts directly in  _castsToApply, since we don't call visit until we are done with all the processing anyway

**Comment by maumar** [comment]
@roji ready for review

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 7]
```diff
@@ -128,6 +134,18 @@ internal SelectExpression(SqlExpression? projection)
             isColumnNullable ?? columnType.IsNullableType());
 
         _projectionMapping[new ProjectionMember()] = columnExpression;
+
+        if (identifierColumnName != null && identifierColumnType != null && identifierColumnTypeMapping != null)
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:138]: Maybe make sure that either all or none are provided (but again this should be cleaned up later anyway so...)

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 8]
```diff
@@ -2156,7 +2174,10 @@ public void ApplyIntersect(SelectExpression source2, bool distinct)
     public void ApplyUnion(SelectExpression source2, bool distinct)
         => ApplySetOperation(SetOperationType.Union, source2, distinct);
 
-    private void ApplySetOperation(SetOperationType setOperationType, SelectExpression select2, bool distinct)
+    private void ApplySetOperation(
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2177]: nit: can stay on same line (doesn't pass 120) unless you feel strongly

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 9]
```diff
@@ -2308,7 +2329,12 @@ private void ApplySetOperation(SetOperationType setOperationType, SelectExpressi
                     }
                 }
 
-                otherExpressions.Add(outerProjection);
+                // we need comparer (that we get from type mapping) for identifiers
+                // it may happen that one side of the set operation comes from collection parameter
+                // and therefore doesn't have type mapping (yet - we infer those after the translation is complete)
+                // but for set operation at least one side should have type mapping, otherwise whole thing would have been parameterized out
+                var outerTypeMapping = innerProjection1.Expression.TypeMapping ?? innerProjection2.Expression.TypeMapping!;
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2336]: Looks correct, but with compiled query it's technically possible to have both sides coming from a parameter/primitive collection (we don't parameterize that way with compiled queries).

I think that for this case it's valid to just get the default type mapping for the CLR type from the type mapping source (what else could we possibly do), but since it's a super-exotic edge-case we can also comment that possibility and throw ("A set operation requires at least one column with a valid type mapping in one of its sides").

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs [hunk 10]
```diff
@@ -112,75 +113,125 @@ public Expression Process(Expression expression)
...
-                    Tables: [SqlServerOpenJsonExpression { ColumnInfos: not null } openJsonExpression, ..],
-                    Orderings:
-                    [
+                    var newTables = new List<TableExpressionBase>();
+                    var appliedCasts = new List<(SqlServerOpenJsonExpression, string)>();
+                    var tablesChanged = false;
+
+                    foreach (var table in selectExpression.Tables)
+                    {
+                        if (table is SqlServerOpenJsonExpression { ColumnInfos: not null }
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:124]: nit: can unwrap the join first to simplify the match (we maybe even have an extension for that?)

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs [hunk 11]
```diff
@@ -112,75 +113,125 @@ public Expression Process(Expression expression)
...
+                            or JoinExpressionBase { Table: SqlServerOpenJsonExpression { ColumnInfos: not null } })
                         {
-                            Expression: SqlUnaryExpression
+                            var keyReferencedInOrderings = selectExpression.Orderings.Any(o => o.Expression is SqlUnaryExpression
+                            {
+                                OperatorType: ExpressionType.Convert,
+                                Operand: ColumnExpression { Name: "key", Table: var keyColumnTable }
+                            } && keyColumnTable == table);
+
+                            var keyReferencedInProjection = selectExpression.Projection.Any(p => p.Expression is ColumnExpression
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:133]: Just checking: is it enough to check that the key is directly there, i.e. it will never be wrapped deeper in an expression?  I think it's OK since our logic is the one that adds it to the projection (never the user), but just checking).

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs [hunk 12]
```diff
@@ -112,75 +113,125 @@ public Expression Process(Expression expression)
...
+                            { Name: "key", Table: var keyColumnTable } && keyColumnTable == table);
+
+                            var keyWithConvertReferencedInProjection = selectExpression.Projection.Any(p => p.Expression is SqlUnaryExpression
                             {
                                 OperatorType: ExpressionType.Convert,
                                 Operand: ColumnExpression { Name: "key", Table: var keyColumnTable }
+                            } && keyColumnTable == table);
+
+                            if (keyReferencedInOrderings || keyReferencedInProjection || keyWithConvertReferencedInProjection)
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:142]: I don't think we care whether the key appeared in the orderings or the projection, so we should be able to just merge the 3 checks above (with the help of a local function):

```c#
if (selectExpression.Orderings.Select(o => o.Expression)
    .Concat(selectExpression.Projection.Select(p => p.Expression))
    .Any(c => IsKeyColumn(table)))
{
}
```

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs [hunk 13]
```diff
@@ -112,75 +113,125 @@ public Expression Process(Expression expression)
                 case ShapedQueryExpression shapedQueryExpression:
                     return shapedQueryExpression.UpdateQueryExpression(Visit(shapedQueryExpression.QueryExpression));
 
-                case SelectExpression
+                case SelectExpression selectExpression:
                 {
-                    Tables: [SqlServerOpenJsonExpression { ColumnInfos: not null } openJsonExpression, ..],
-                    Orderings:
-                    [
+                    var newTables = new List<TableExpressionBase>();
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:118]: We very rarely need to actually rewrite the SelectExpression (the vast majority won't have an OPENJSON, and one that really needs to be rewritten at that...). So we can initialize these to null, and only instantiate the Lists (and populate) the first time a table needs to be rewritten. Same thing conceptually as #31065.

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs [hunk 14]
```diff
@@ -112,75 +113,125 @@ public Expression Process(Expression expression)
...
+                                        throw new InvalidOperationException(SqlServerStrings.QueryingOrderedBinaryJsonCollectionsNotSupported);
+                                    }
+
+                                    _castsToApply.Add((newOpenJsonExpression, column.Name), typeMapping);
+                                    appliedCasts.Add((newOpenJsonExpression, column.Name));
+                                }
+                            }
+                            else
+                            {
+                                newTables.Add(table);
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:185]: Instead of having two elses here for just adding the table, you can put a `continue` right after the column foreach above, and leave just one newTables.Add() below (i.e. the code will just always flow down to it unless it entered both conditions above)

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs [hunk 15]
```diff
@@ -112,75 +113,125 @@ public Expression Process(Expression expression)
...
+                        return _sqlExpressionFactory.Convert(columnExpression, columnExpression.Type, typeMapping);
+                    }
+
+                    if (columnExpression.Table is JoinExpressionBase { Table: SqlServerOpenJsonExpression innerOpenJsonTable }
+                        && _castsToApply.TryGetValue((innerOpenJsonTable, columnExpression.Name), out var innerTypeMapping))
+                    {
+                        return _sqlExpressionFactory.Convert(columnExpression, columnExpression.Type, innerTypeMapping);
+                    }
+
+                    return base.Visit(expression);
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:234]:
```suggestion
                    return columnExpression.Table switch
                    {
                        SqlServerOpenJsonExpression openJsonTable
                            when _castsToApply.TryGetValue((openJsonTable, columnExpression.Name), out var typeMapping)
                            => _sqlExpressionFactory.Convert(columnExpression, columnExpression.Type, typeMapping),

                        JoinExpressionBase { Table: SqlServerOpenJsonExpression innerOpenJsonTable }
                            when _castsToApply.TryGetValue((innerOpenJsonTable, columnExpression.Name), out var innerTypeMapping)
                            => _sqlExpressionFactory.Convert(columnExpression, columnExpression.Type, innerTypeMapping),

                        _ => base.Visit(expression)
                    };
```

File: test/EFCore.SqlServer.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqlServerTest.cs [hunk 16]
```diff
@@ -344,7 +344,7 @@ public virtual async Task Ordered_array_of_string()
 WHERE (
     SELECT COUNT(*)
     FROM (
-        SELECT CAST([s].[value] AS nvarchar(max)) AS [value], CAST([s].[key] AS int) AS [c]
+        SELECT CAST([s].[value] AS nvarchar(max)) AS [value], [s].[key], CAST([s].[key] AS int) AS [c]
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqlServerTest.cs:347]: Yeah, a bit ugly to be projecting twice :) But no biggie.

**Review by roji — APPROVED** [review]
Thanks @maumar, looking good! Mainly nits below.

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs (hunk 11 above)
Comment (maumar) [reply src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:133]: we do the check for select expression whose table is OpenJsonExpression, so it can't be any deeper. Assuming that thee is in a consistent state, even if the key value was somehow added above, it should be present on the bottom level also.

File: test/EFCore.SqlServer.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqlServerTest.cs (hunk 16 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqlServerTest.cs:347]: Yeah, but making identifiers into non-ColumnExpression is tricky, I tried it once and failed. Fun fact, Sqlite is "superior" here, since the key column is a number so no need for cast and we can de-duplicate.

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs (hunk 10 above)
Comment (maumar) [reply src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:124]: we need to remember if a given OPEN JSON is "naked" or in join, when we later rebuild it, also for purpose of matching the aliases we need the wrapping join

Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:124]: Makes sense, missed that!

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs (hunk 13 above)
Comment (maumar) [reply src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs:118]: not a fan of this optimization if this particular context - we add to the list in two places so the code needs to be duplicated, no?

File: test/EFCore.SqlServer.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqlServerTest.cs (hunk 16 above)
Comment (roji) [reply test/EFCore.SqlServer.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqlServerTest.cs:335]: Yeah, I can see that this puts some strain on our existing architecture :) Nice that at least Sqlite work well. Maybe open an issue tracking improving this?

Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqlServerTest.cs:335]: https://github.com/dotnet/efcore/issues/31326
