### PR TITLE
TrimStart and TrimEnd with optional char array implementation for SQL Server

### LINKED ISSUE #22924: SQL Server: Translate string.TrimStart/End overloads accepting characters to trim
# string.TrimStart not working in where
Using string.TrimStart inside a where close not working
(But it's work in a select)

## Code

```C#
var testData = "1";
var testRequest = await this._context.Table
       .Where(q => q.Code.TrimStart('F') == testData)
       .FirstOrDefaultAsync();
```

## Stack traces

```
System.InvalidOperationException: The LINQ expression 'DbSet<Table>
    .Where(f => f.Code.TrimStart(F) == __testData_0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```
### Provider and version information

EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.3

### PR DESCRIPTION
**Pull request by abdielcs**
Fixes #22924

- [X ] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [ ] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ X] The code builds and tests pass locally (also verified by our automated build checks)
- [X ] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [X ] Tests for the changes have been added (for bug fixes / features)
- [X ] Code follows the same patterns and style as existing code in this repo

### CODE REVIEW

**Comment by abdielcs** [comment]
@dotnet-policy-service agree

**Comment by abdielcs** [comment]
Hi, I can't find which test failed or the log. It seems to be in EFCore.SqlServer.FunctionalTests, but since everything works fine in my local environment, it would be great to see which test failed in the CI for a clue. Any help would be appreciated.

**Review by cincuranet — APPROVED** [review]

**Comment by cincuranet** [comment]
@maumar or @roji  can I get 2nd set of eyes. Otherwise LGTM.

File: src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs [hunk 1]
```diff
@@ -357,4 +422,16 @@ public SqlServerStringMethodTranslator(ISqlExpressionFactory sqlExpressionFactor
...
     }
+
+    private bool CheckTrimStartTrimEndWithArgsCompatibilityLevel()
+        => CheckCompatibilityLevel(160, SqlServerStrings.TrimStartTrimEndWithArgsCompatibilityLevelTooLow);
+
+    private bool CheckCompatibilityLevel(int compatibilityLevel, Func<object?, string> compatibilityTooLowFunction)
+    {
+        if (_sqlServerSingletonOptions.CompatibilityLevel < compatibilityLevel)
+        {
+            throw new InvalidOperationException(compatibilityTooLowFunction(compatibilityLevel));
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs:433]: This would fail any queries using these functions with a low compatibility level; as @stevendarby [pointed out](https://github.com/dotnet/efcore/issues/22924#issuecomment-2093473994), this would be a breaking change if anyone is currently using these functions via client evaluation (in the final projection).

Ideally, we'd be able to log a translation failure here that would only get reported if the method call **isn't** in the final projection, to both avoid the breaking change and report an error when not in the final projection; but our error reporting infra doesn't yet support this.

So I **think** it makes most sense to simply not throw here for now, to allow client eval in the final projection, at the price of a slightly cryptic SQL Server error when this is used elsewhere on older databases.

File: src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs [hunk 2]
```diff
@@ -194,9 +205,35 @@ public SqlServerStringMethodTranslator(ISqlExpressionFactory sqlExpressionFactor
...
+                    nullable: true,
+                    argumentsPropagateNullability: new[] { true, true },
+                    instance.Type,
+                    instance.TypeMapping);
+            }
+
+            if (TrimStartMethodInfoWithCharArrayArg.Equals(method)
+                && CheckTrimStartTrimEndWithArgsCompatibilityLevel())
+            {
+                var firstArgumentValue = (arguments[0] as SqlConstantExpression)?.Value as char[];
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs:223]: What happens if the argument isn't a constant? This looks like it would translate to a NULL, yielding incorrect results?

**Review by roji — CHANGES_REQUESTED** [review]
Thanks, here are some comments from me.

Note that there's also #22927 for Trim (as opposed to TrimStart/End) - it would be good to add this translation too (though it doesn't have to happen in the same PR).

File: src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs (hunk 1 above)
Comment (abdielcs) [reply src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs]: So, I rolled back the throwing of the exception gracefully to avoid the breaking change.

File: src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs (hunk 2 above)
Comment (abdielcs) [reply src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs]: I decided to reuse the same code used in SQLite for resolve the Trim expressions, since it make sense. Is mostly the same code, I'm not sure if must be placed in some utility class for reusing code between providers, possibly not.

**Comment by abdielcs** [comment]
> Thanks, here are some comments from me.
> 
> Note that there's also #22927 for Trim (as opposed to TrimStart/End) - it would be good to add this translation too (though it doesn't have to happen in the same PR).

Yes, I saw the Trim, but since it has a different syntax in the new version, it is unlikely that it can be done in the same way. So, @roji, if you agree, I would prefer to address it after finishing these.

For some reason, my SQLite tests are failing again. Maybe I'm doing something wrong in the merge or something?

File: src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs [hunk 3]
```diff
@@ -1,6 +1,7 @@
 // Licensed to the .NET Foundation under one or more agreements.
 // The .NET Foundation licenses this file to you under the MIT license.
 
+using Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal;
```
Comment (cincuranet) [inline src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs:4]: nit: Add empty line after using.

File: src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs [hunk 4]
```diff
@@ -181,33 +192,22 @@ public SqlServerStringMethodTranslator(ISqlExpressionFactory sqlExpressionFactor
...
-                    "LTRIM",
-                    new[] { instance },
-                    nullable: true,
-                    argumentsPropagateNullability: new[] { true },
-                    instance.Type,
-                    instance.TypeMapping);
-            }
+                if (TrimStartMethodInfoWithoutArgs.Equals(method)
+                || TrimStartMethodInfoWithCharArg.Equals(method)
+                || TrimStartMethodInfoWithCharArrayArg.Equals(method))
```
Comment (cincuranet) [inline src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs:199]: nit: Missing indentation.

File: src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs [hunk 5]
```diff
@@ -358,4 +358,46 @@ public SqlServerStringMethodTranslator(ISqlExpressionFactory sqlExpressionFactor
...
+        if (typeMapping == null)
+        {
+            return null;
+        }
+
+        var sqlArguments = new List<SqlExpression> { instance };
+        if (arguments.Count == 1)
+        {
+            var constantValue = (arguments[0] as SqlConstantExpression)?.Value;
+            var charactersToTrim = new List<char>();
```
Comment (cincuranet) [inline src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs:374]: I think `StringBuilder` here would be better fit.

**Review by cincuranet — APPROVED** [review]

File: src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs [hunk 6]
```diff
@@ -186,33 +198,22 @@ public SqlServerStringMethodTranslator(ISqlExpressionFactory sqlExpressionFactor
                     instance.TypeMapping);
             }
 
-            if (TrimStartMethodInfoWithoutArgs.Equals(method)
-                || (TrimStartMethodInfoWithCharArrayArg.Equals(method)
-                    // SqlServer LTRIM does not take arguments
-                    && ((arguments[0] as SqlConstantExpression)?.Value as Array)?.Length == 0))
+            if (_sqlServerSingletonOptions.CompatibilityLevel >= 160)
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs:201]: This looks like it places the existing TrimStart translation - without args - inside the condition for the compatibility level, although that translation is fine for old versions; `LTRIM(x)` was always supported, `LTRIM(x, y)` is the new thing that's only supported in SQL Server 2022. So it seems like the compatibility level check should only apply when the argument isn't an empty array constant...

**Review by roji — CHANGES_REQUESTED** [review]

File: src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs [hunk 7]
```diff
@@ -187,31 +199,19 @@ public SqlServerStringMethodTranslator(ISqlExpressionFactory sqlExpressionFactor
             }
 
             if (TrimStartMethodInfoWithoutArgs.Equals(method)
-                || (TrimStartMethodInfoWithCharArrayArg.Equals(method)
-                    // SqlServer LTRIM does not take arguments
-                    && ((arguments[0] as SqlConstantExpression)?.Value as Array)?.Length == 0))
+                || (_sqlServerSingletonOptions.CompatibilityLevel >= 160
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs:205]: It's a bit of an annoying little detail, but the previous code did translate TrimStartMethodInfoWithCharArrayArg as long as the first argument is an empty array constant. I don't think it was an important thing to do, but once it's there I don't think we should be removing it (it's a very minor but also needless breaking change). So can we please preserve the previous behavior, and only put the new translation inside the CompatibilityLevel condition?

**Review by roji — APPROVED** [review]
Thanks, this is very close - see note below. I'll just go ahead and fix the remaining issue plus some cleanup.

Thanks for your contribution!

**Comment by maumar** [comment]
I disabled auto merge, please check in after https://github.com/dotnet/efcore/pull/34043
