### PR TITLE
[release/8.0] Make Contains work again over hierarchyid

### LINKED ISSUE #31912: Hierarchyid in a parameter collection does not work in 8.0-rc1 with MSSQL
Repro code:
https://gist.github.com/bachratyg/d3a985224d29c48f51df8f7b1e49a32d

The same query expression (obviously different sql) used to work with EFC7.0 and EntityFrameworkCore.SqlServer.HierarchyId 4.0.0.

This is the generated query:
```sql
DECLARE @__ids_0 nvarchar(4000) = N'["/1/","/2/"]';

SELECT [s].[Id], [s].[Name]
FROM [Stuffs] AS [s]
WHERE [s].[Id] IN (
    SELECT [i].[value]
    FROM OPENJSON(@__ids_0) WITH ([value] hierarchyid '$') AS [i]
)
```
SQL Server returns the following error:
```
CLR types cannot be used as column types in OPENJSON function with explicit schema.
CLR types are not supported in WITH clause.
```

If the type of `[value]` is changed from `hierarchyid` to `nvarchar(max)` on the last line implicit conversion kicks in and the command runs just fine with the new pattern. Query plan looks the same. Or simply just revert to the old behavior for types that are not supposed to work. I'm guessing spatial is in the same bucket.

<details><summary>Environment</summary>
<p>
EF Core version: 8.0.0-rc.1.23419.6<br/>
Database provider: Microsoft.EntityFrameworkCore.SqlServer<br/>
Target framework: .NET 8.0-rc1<br/>
SQL Server: 16.0.1050.5
</p>
</details>

### PR DESCRIPTION
**Pull request by roji**
Fixes #31912

### Description

The primitive collection improvements to 8.0 changed the translation of Contains to use OPENJSON with WITH, but that's incompatible with hierarchyid (SQL Server CLR type).

### Customer impact

Queries which apply Contains to a parameter list of HierarchyId no longer work in 8.0.

### How found

Customer reported.

### Regression

Yes (when the community hierarchyid package was used)

### Testing

Added.

### Risk

Very low, the mechanism to transform the incompatible OPENJSON with WITH to OPENJSON without WITH already existed for other purposes; this change only extends its usage for hierarchyid.

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SqlServerJsonPostprocessor.cs [hunk 1]
```diff
@@ -79,14 +82,17 @@ public virtual Expression Process(Expression expression)
...
-                            .Concat(selectExpression.Projection.Select(p => p.Expression))
-                            .Any(x => IsKeyColumn(x, table)))
+                    if (table.UnwrapJoin() is SqlServerOpenJsonExpression { ColumnInfos: not null } openJsonExpression
+                        && (
+                            // Condition 1: an ordering still refers to the OPENJSON's [key] column - ordering needs to be preserved.
+                            selectExpression.Orderings.Select(o => o.Expression)
+                                .Concat(selectExpression.Projection.Select(p => p.Expression))
+                                .Any(x => IsKeyColumn(x, table))
+                            ||
+                            // Condition 2: a column type in the WITH clause is a SQL Server "CLR type"  (spatial types, hierarchy id).
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Query/Internal/SqlServerJsonPostprocessor.cs:92]: Remove "spatial types" from comment?

**Review by ajcvickers — APPROVED** [review]

**Comment by ajcvickers** [comment]
@roji This is approved by Tactics.

**Comment by IT-CASADO** [comment]
This is still broken in some use cases. In my case with some **.Includes** and **.AsSplitQuery()**.

```
var result = await query
   .Include()
   .AsSplitQuery()       
   .ToListAsync(cancellationToken);
```

This results to follwoing two queries.

```
exec sp_executesql N'SELECT [i].[Id], [i].[NodeId]
FROM [Initiative] AS [i]

WHERE [i].[NodeId] IN (
    SELECT CAST([q].[value] AS hierarchyid) AS [value]
    FROM OPENJSON(@__qFiltered_1) AS [q]
)'

,N'@__qFiltered_1 nvarchar(4000)',@__qFiltered_1=N'["/3/1/1/"]'


exec sp_executesql N'SELECT [i].[Id], [i].[NodeId]
FROM [Initiative] AS [i]
INNER JOIN [InitiativeDimensionValue] AS [t] ON [i].[Id] = [t].[InitiativeId]

WHERE [i].[NodeId] IN (
    SELECT [q].[value]
    FROM OPENJSON(@__qFiltered_4) WITH ([value] hierarchyid ''$'') AS [q]         --> this is wrong
)'

,N'@__qFiltered_1 nvarchar(4000)',@__qFiltered_1=N'["/3/1/1/"]'
```

Unfortunately the second query is still using the WITH syntax.

**Comment by roji** [comment]
@IT-CASADO can you please open a new issue for this, including a minimal, runnable code sample? Then I can look at fixing that case as well.
