### PR TITLE
List<T> as inline collections implementation.

### LINKED ISSUE #32413: Fully support inline List (and other non-array) collections as inline collection query roots
For example, the following fails:

```c#
_ = ctx.Projects.Where(b => new List<int> { 1, b.Int }.Where(b => b > 1).Contains(2)).ToList();
```

... whereas the following works:

```c#
_ = ctx.Projects.Where(b => new[] { 1, b.Int }.Where(b => b > 1).Contains(2)).ToList();
```
---

First, QueryRootProcessor.VisitQueryRootCandidate recognizes NewArrayExpression (inline array) and converts it to InlineQueryRootExpression; but it does not do so for an inline List, and possibly other IList collection types.

Then, in QueryableMethodNormalizingEV, we identify List.Contains and convert it to Queryable.Contains ([code](https://github.com/dotnet/efcore/blob/main/src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs#L429)):

```c#
var ids = new List<int> { 1, 2 };
_ = ctx.Blogs.Where(b => ids.Contains(b.Id)).ToList();
```

This is important for recognizing the Contains as a queryable operator later, etc.

However, we specifically exclude this normalization when the instance is a NewExpression or MemberInitExpression:

```c#
_ = ctx.Blogs.Where(b => new List<int> { 1, 2 }.Contains(b.Id)).ToList();
```

That means that Contains is processed as enumerable rather than queryable, ending up in ContainsTranslator (which we eventually want to remove).

I'm not sure why we made these specific exclusions, any idea @maumar?

### PR DESCRIPTION
**Pull request by cincuranet**
Explicitly handling only what implements `IList<T>` (per https://github.com/dotnet/efcore/issues/32413#issuecomment-2034721904).

The tests are exercising also code path for #33466.

Fixes #32413

### CODE REVIEW

File: src/EFCore/Query/QueryRootProcessor.cs [hunk 1]
```diff
@@ -115,6 +116,11 @@ private Expression VisitQueryRootCandidate(Expression expression, Type elementCl
                 && ShouldConvertToParameterQueryRoot(parameterExpression):
                 return new ParameterQueryRootExpression(parameterExpression.Type.GetSequenceType(), parameterExpression);
 
+            case ListInitExpression listInitExpression
+                when listInitExpression.Type.TryGetElementType(typeof(IList<>)) is not null
+                && ShouldConvertToInlineQueryRoot(listInitExpression):
+                return new InlineQueryRootExpression(listInitExpression.Initializers.Select(x => x.Arguments[0]).ToList(), elementClrType);
```
Comment (roji) [inline src/EFCore/Query/QueryRootProcessor.cs:122]: Could be slightly safer to simply not convert if any of the initializers have multiple expressions. I know you're checking just about that `IList<>` is implemented, but in theory some concrete implementation of that could have an Add() overload allowing that.

File: src/EFCore/Query/QueryRootProcessor.cs [hunk 2]
```diff
@@ -127,6 +133,13 @@ private Expression VisitQueryRootCandidate(Expression expression, Type elementCl
     protected virtual bool ShouldConvertToInlineQueryRoot(NewArrayExpression newArrayExpression)
         => false;
 
+    /// <summary>
+    ///     Determines whether a <see cref="ListInitExpression" /> should be converted to a <see cref="InlineQueryRootExpression" />.
+    /// </summary>
+    /// <param name="listInitExpression">The new array expression that's a candidate for conversion to a query root.</param>
+    protected virtual bool ShouldConvertToInlineQueryRoot(ListInitExpression listInitExpression)
```
Comment (roji) [inline src/EFCore/Query/QueryRootProcessor.cs:140]: I think we should consider just changing the parameter of the existing ShouldConvertToInlineQueryRoot to Expression instead of introducing a new overload... I added these "ShouldConvert" methods when implementing primitive collections mainly as a way to not affect providers which haven't opted into primitive collections, i.e. to prevent Cosmos/InMemory from suddenly getting unknown InlineQueryRootExpression and needing to handle them (would be a big breaking change). The expression argument is there just in case it's needed, but no actual provider actually looks at them currently (and I can't really think why they would).

So yeah, it would be a slight provider-facing breaking change, but these are very specific APIs which no provider currently implements AFAIK, except our own providers.

File: test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs [hunk 3]
```diff
@@ -138,6 +138,17 @@ public virtual async Task Inline_collection_Contains_with_mixed_value_types(bool
             ss => ss.Set<PrimitiveCollectionsEntity>().Where(c => new[] { 999, i, c.Id, c.Id + c.Int }.Contains(c.Int)));
     }
 
+    [ConditionalTheory]
+    [MemberData(nameof(IsAsyncData))]
+    public virtual async Task Inline_collection_List_Contains_with_mixed_value_types(bool async)
```
Comment (roji) [inline test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs:143]: 👍 

Maybe rename the existing non-List tests to add `_array` into their names

**Review by roji — APPROVED** [review]
LGTM, see mainly proposal to keep a single ShouldConvert overload here.

File: src/EFCore/Query/QueryRootProcessor.cs (hunk 2 above)
Comment (cincuranet) [reply src/EFCore/Query/QueryRootProcessor.cs:140]: SGTM

File: test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs (hunk 3 above)
Comment (cincuranet) [reply test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs:143]: I thought about it, but ultimately decided not to do it for 2 reasons.
1. Maybe half of these (inline collection) tests are not related to using array _specifically_, but simply testing that it is doing the right thing. That's also the reason I added the _List_ tests only where it matters, not for every place where array is used.
2. It would be, IMO unnecessary, breaking change for provider writers.

But I don't have strong opinion against doing it. Let me know your final decision.

Comment (roji) [reply test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs:143]: No strong opinion here either - I'm good with leaving as-is too.

File: src/EFCore/Query/QueryRootProcessor.cs (hunk 1 above)
Comment (cincuranet) [reply src/EFCore/Query/QueryRootProcessor.cs:122]: If you have custom `IList<T>` implementation you'll get exception:
```
System.InvalidOperationException : The LINQ expression 'DbSet<PrimitiveCollectionsEntity>()
    .Where(p => new MyList`1() {Void Add(Int32, Int32)(999, 1), Void Add(Int32, Int32)(__i_0, 1), Void Add(Int32, Int32)(p.Id, 1), Void Add(Int32)((p.Id + p.Int))}
    .Contains(p.Int))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

But you can still derive from `List<T>` and then it's going to reach this place and work incorrectly. 

I'll add the check for `Arguments == 1`.
