### PR TITLE
Redo SQL table alias management

### LINKED ISSUE #26104: GroupBy debug assert: Missing alias in the list: p1,p
Found working on samples for RC1, then running them as tests on main.

```
System.InvalidOperationException
Missing alias in the list: p1,p
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.TableAliasVerifyingExpressionVisitor.ScopedVisitor.EntryPoint(Expression expression) in C:\dotnet\efcore\src\EFCore.Relational\Query\RelationalQueryTranslationPostprocessor.cs:line 128
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.TableAliasVerifyingExpressionVisitor.UniquifyAliasInSelectExpression(Expression selectExpression) in C:\dotnet\efcore\src\EFCore.Relational\Query\RelationalQueryTranslationPostprocessor.cs:line 104
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.TableAliasVerifyingExpressionVisitor.Visit(Expression expression) in C:\dotnet\efcore\src\EFCore.Relational\Query\RelationalQueryTranslationPostprocessor.cs:line 89
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query) in C:\dotnet\efcore\src\EFCore.Relational\Query\RelationalQueryTranslationPostprocessor.cs:line 52
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in C:\dotnet\efcore\src\EFCore\Query\QueryCompilationContext.cs:line 190
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async) in C:\dotnet\efcore\src\EFCore\Storage\Database.cs:line 76
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in C:\dotnet\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 111
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0() in C:\dotnet\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 95
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in C:\dotnet\efcore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 74
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in C:\dotnet\efcore\src\EFCore\Query\Internal\QueryCompiler.cs:line 91
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in C:\dotnet\efcore\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 78
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator() in C:\dotnet\efcore\src\EFCore\Query\Internal\EntityQueryable`.cs:line 90
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GroupBySample.Translate_GroupBy_followed_by_FirstOrDefault_over_group() in C:\dotnet\efcore\test\EFCore.SqlServer.FunctionalTests\SqlServerEndToEndTest.cs:line 31
```

```C#
public class GroupBySample
{
    [ConditionalFact]
    public void Translate_GroupBy_followed_by_FirstOrDefault_over_group()
    {
        Console.WriteLine($">>>> Sample: {nameof(Translate_GroupBy_followed_by_FirstOrDefault_over_group)}");
        Console.WriteLine();

        Helpers.RecreateCleanDatabase();
        Helpers.PopulateDatabase();

        // Example 3. From #12640
        using (var context = new ShoesContext())
        {
            #region GroupBy3
            var people = context.People
                .Where(e => e.MiddleInitial == "Q" && e.Age == 20)
                .GroupBy(e => e.LastName)
                .Select(g => g.First().LastName)
                .OrderBy(e => e.Length)
                .ToList();
            #endregion
        
            Console.WriteLine();
        
            foreach (var person in people)
            {
                Console.WriteLine(person);
            }
        
            Console.WriteLine();
        }
        
        // Example 5. From #12601
        using (var context = new ShoesContext())
        {
            #region GroupBy5
            var results = context.People
                .GroupBy(e => e.FirstName)
                .Select(g => g.First().LastName)
                .OrderBy(e => e)
                .ToList();
            #endregion
        
            Console.WriteLine();
            
            foreach (var result in results)
            {
                Console.WriteLine(result);
            }
        
            Console.WriteLine();
        }

        // Example 6. From #12600
        using (var context = new ShoesContext())
        {
            #region GrouoBy6
            var results = context.People.Where(e => e.Age == 20)
                .GroupBy(e => e.Id)
                .Select(g => g.First().MiddleInitial)
                .OrderBy(e => e)
                .ToList();
            #endregion
        
            Console.WriteLine();
        
            foreach (var result in results)
            {
                Console.WriteLine(result);
            }
        
            Console.WriteLine();
        }
    }

    public static class Helpers
    {
        public static void RecreateCleanDatabase()
        {
            using var context = new ShoesContext(quiet: true);

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }

        public static void PopulateDatabase()
        {
            using var context = new ShoesContext(quiet: true);

            context.AddRange(
                new Person
                {
                    FirstName = "Jim",
                    MiddleInitial = "A",
                    LastName = "Bob",
                    Age = 20,
                    Feet = new Feet { Size = 11 },
                    Shoes = { new() { Style = "Sneakers", Age = 19 }, new() { Style = "Dress", Age = 20 } }
                },
                new Person
                {
                    FirstName = "Tom",
                    MiddleInitial = "A",
                    LastName = "Bob",
                    Age = 20,
                    Feet = new Feet { Size = 12 },
                    Shoes = { new() { Style = "Sneakers", Age = 21 }, new() { Style = "Dress", Age = 19 } }
                },
                new Person
                {
                    FirstName = "Ben",
                    MiddleInitial = "Q",
                    LastName = "Bob",
                    Age = 20,
                    Feet = new Feet { Size = 12 },
                    Shoes = { new() { Style = "Sneakers", Age = 20 }, new() { Style = "Dress", Age = 21 } }
                },
                new Person
                {
                    FirstName = "Jim",
                    MiddleInitial = "Q",
                    LastName = "Jon",
                    Age = 20,
                    Feet = new Feet { Size = 11 },
                    Shoes = { new() { Style = "Sneakers", Age = 19 }, new() { Style = "Dress", Age = 20 } }
                },
                new Person
                {
                    FirstName = "Tom",
                    MiddleInitial = "A",
                    LastName = "Jon",
                    Age = 21,
                    Feet = new Feet { Size = 11 },
                    Shoes = { new() { Style = "Sneakers", Age = 21 }, new() { Style = "Dress", Age = 19 } }
                },
                new Person
                {
                    FirstName = "Ben",
                    MiddleInitial = "A",
                    LastName = "Jon",
                    Age = 21,
                    Feet = new Feet { Size = 12 },
                    Shoes = { new() { Style = "Sneakers", Age = 20 }, new() { Style = "Dress", Age = 21 } }
                },
                new Person
                {
                    FirstName = "Jim",
                    MiddleInitial = "Q",
                    LastName = "Don",
                    Age = 21,
                    Feet = new Feet { Size = 12 },
                    Shoes = { new() { Style = "Sneakers", Age = 19 }, new() { Style = "Dress", Age = 20 } }
                },
                new Person
                {
                    FirstName = "Tom",
                    MiddleInitial = "Q",
                    LastName = "Don",
                    Age = 21,
                    Feet = new Feet { Size = 11 },
                    Shoes = { new() { Style = "Sneakers", Age = 21 }, new() { Style = "Dress", Age = 19 } }
                },
                new Person
                {
                    FirstName = "Ben",
                    MiddleInitial = "A",
                    LastName = "Don",
                    Age = 21,
                    Feet = new Feet { Size = 11 },
                    Shoes = { new() { Style = "Sneakers", Age = 20 }, new() { Style = "Dress", Age = 21 } }
                },
                new Person
                {
                    FirstName = "Jim",
                    MiddleInitial = "A",
                    LastName = "Zee",
                    Age = 21,
                    Feet = new Feet { Size = 12 },
                    Shoes = { new() { Style = "Sneakers", Age = 19 }, new() { Style = "Dress", Age = 20 } }
                },
                new Person
                {
                    FirstName = "Tom",
                    MiddleInitial = "Q",
                    LastName = "Zee",
                    Age = 21,
                    Feet = new Feet { Size = 12 },
                    Shoes = { new() { Style = "Sneakers", Age = 21 }, new() { Style = "Dress", Age = 19 } }
                },
                new Person
                {
                    FirstName = "Ben",
                    MiddleInitial = "Q",
                    LastName = "Zee",
                    Age = 21,
                    Feet = new Feet { Size = 11 },
                    Shoes = { new() { Style = "Sneakers", Age = 20 }, new() { Style = "Dress", Age = 21 } }
                });

            context.SaveChanges();
        }
    }

    #region Model
    public class Person
    {
        public int Id { get; set; }
        public int Age { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleInitial { get; set; }
        public Feet Feet { get; set; }
        public ICollection<Shoes> Shoes { get; } = new List<Shoes>();
    }

    public class Shoes
    {
        public int Id { get; set; }
        public int Age { get; set; }
        public string Style { get; set; }
        public Person Person { get; set; }
    }

    public class Feet
    {
        public int Id { get; set; }
        public int Size { get; set; }
        public Person Person { get; set; }
    }
    #endregion

    public class ShoesContext : DbContext
    {
        public DbSet<Person> People { get; set; }
        public DbSet<Shoes> Shoes { get; set; }
        public DbSet<Feet> Feet { get; set; }

        private readonly bool _quiet;

        public ShoesContext(bool quiet = false)
        {
            _quiet = quiet;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .EnableSensitiveDataLogging()
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFCoreSample");

            if (!_quiet)
            {
                optionsBuilder.LogTo(Console.WriteLine, new[] { RelationalEventId.CommandExecuted });
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Feet>().HasOne(e => e.Person).WithOne(e => e.Feet).HasForeignKey<Feet>();
        }
    }
}
```

### LINKED ISSUE #32757: Query contains non-consecutive table aliases when tables are pruned
**Note: I do not think this is a bug**

We generate table aliases based on the first character of the table name, followed by an incrementing counter for uniquification; aliases are thus generally consecutive (we even have DEBUG-only checks that attempt to validate this).

However, when a table gets pruned, that causes a "hole" in the alias numbering. For example, with the following contrived TPT query:

```c#
_ = ctx.Blogs.Count(b =>
    ctx.Blogs.Count(b => b.Name == "foo") == 0 && ctx.BlogsExtraSpecial.Count(b => b.Name == "foo") == 0);
```

<details>
<summary>Full repro</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

_ = ctx.Blogs.Count(b =>
    ctx.Blogs.Count(b => b.Name == "foo") == 0 && ctx.BlogsExtraSpecial.Count(b => b.Name == "foo") == 0);

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<BlogSpecial> BlogsSpecial { get; set; }
    public DbSet<BlogExtraSpecial> BlogsExtraSpecial { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().UseTptMappingStrategy();
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class BlogSpecial : Blog
{
    public string SpecialProperty { get; set; }
}

public class BlogExtraSpecial : BlogSpecial
{
    public string ExtraSpecialProperty { get; set; }
}
```

</details>

... we generate the following SQL:

```sql
SELECT COUNT(*)
FROM [Blogs] AS [b]
WHERE (
    SELECT COUNT(*)
    FROM [Blogs] AS [b2]
    WHERE [b2].[Name] = N'foo') = 0 AND (
    SELECT COUNT(*)
    FROM [Blogs] AS [b5]
```

... with only [b], [b2] and [b5]. This is because ctx.Blogs generally causes 3 tables to be added (entire TPT hierarchy), but `COUNT(*)` causes the child tables to be pruned, isnce the only referenced property is in the root (Name).

I do not really consider this a bug, but there's some effort in the code to maintain consecutive aliases. Fully maintaining that in all cases requires another pass to check and rewrite aliases, and that doesn't seem worth it.

### LINKED ISSUE #32784: Clean table alias generation and generate unique aliases up-front
Table aliases need to be unique in the SQL tree (at least within a given SELECT) Our current table alias management works as follows:

* SelectExpression has private `_usedAliases` state that tracks which aliases have already been used.
* During translation, tables are created with aliases that don't yet take into account aliases used further up. As a result, when a new SQL clause (predicate, ordering...) is added to a SelectExpression, we run a visitor (AliasUniquifier) over the clause, which accepts the containing select's `_usedAliases` and rewrites aliases recursively inside the clause to make sure they don't conflict.
* This has the following consequences:
    * This notably means that the same node can get visited multiple times for uniquification, as tree fragments get added to a select, and then that select gets added to another select, and so on.
    * Since we uniquify aliases late - after the table has already been created - the alias is mutable, and AliasUniquifier simply sets it. This is one place where our SQL tree isn't fully immutable, and can cause the usual issues related to mutability.
    * When we added support for UpdateExpression, we forgot to invoke the AliasUniquifier, causing [#31208](https://github.com/dotnet/efcore/issues/31208).

We're now exploring ways to simplify the query tree and its processing, and specifically to get rid of TableReferenceExpression and have ColumnExpression just contain its table alias directly as a string. For this to be feasible, the alias on a table cannot change after its constructed, since a column may already be referencing it via its alias (or more precisely, it can be changed, but then we need to recursively look for column in the tree and change them as well). We also generally want to make things more immutable, as well as remove private state from SelectExpression, making it more like a regular expression.

As a result, we should do the following:

* When instantiating a table, pass an already generated, fully unique alias to it.
    * This allows referencing the table immediately from a column, and removes the need to do alias uniquification in an additional pass every time we add a clause to a SelectExpression.
* Track used aliases globally in the query, rather than storing that state on SelectExpression.
    * We'll do this by introducing a new SqlAliasManager service, which is owned by QueryCompilationContext (so scoped to the entire compilation). The holds the state of which aliases are already in use, and is responsible for generating unique ones.
    * This also concentrates alias generation in a single, pluggable place - the actual policy for generating aliases (i.e. take the 1st character and lower-case) is currently spread all over the place, including in table expression types. Providers/users will be able to replace this service to plug in new alias generation policies.
* Tables can get pruned out of the tree because they're not needed. In this case, we currently leave gaps in the alias numbering ([#32757](https://github.com/dotnet/efcore/issues/32757))
    * While this in itself isn't a big problem, uniquifying aliases eagerly as proposed above causes even more gaps, since during translation we sometimes translate a fragment and then throw it away (or retranslate it). This causes the alias to be considered "taken", although it never actually made its way into the tree.
    * To make things nice and consecutive, we'll add a post-processing step where SqlAliasManager gets a chance to go over the tree and rewrite, or "finalize" aliases. This will close any numbering gaps, and can also do fancier things in the future, like turn some aliases into wider, multi-character ones for readability rather than just adding numbers ([#31134](https://github.com/dotnet/efcore/issues/31134)).
    * Note that alias post-processing is fully optional - removing that step would never cause any queries to break, since aliases are already uniquified at the very start. It would just cause uglier/less consecutive aliases to be generated.

### PR DESCRIPTION
**Pull request by roji**
Note to reviewers: since we now generate unique aliases early - before constructing the table - and not later in a separate visitation, the alias ordering is changing (deeper nested tables have lower numbers); that's why so many SQL baselines are changing in this PR.

Closes #32784
Fixes #32757
Part of #32778
Fixes #26104

### CODE REVIEW

File: src/EFCore.Relational/Query/ISqlExpressionFactory.cs [hunk 1]
```diff
@@ -460,29 +460,31 @@ public interface ISqlExpressionFactory
...
+    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+    ///     any release. You should only use it directly in your code with extreme caution and knowing that
+    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
     /// </summary>
-    /// <param name="projection">A <see cref="SqlExpression" /> to project.</param>
-    /// <returns>An expression representing a SELECT in a SQL tree.</returns>
-    SelectExpression Select(SqlExpression? projection);
+    [EntityFrameworkInternal]
+    SelectExpression Select(SqlExpression? projection, SqlAliasManager sqlAliasManager);
```
Comment (roji) [inline src/EFCore.Relational/Query/ISqlExpressionFactory.cs:469]: In the longer-term plan, these are temporary - Select shouldn't be constructing tables within itself as it's doing now, but those tables should rather be constructed outside, i.e. in RelationalQueryableMethodTranslatingEV.

File: src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs [hunk 2]
```diff
@@ -37,24 +39,24 @@ public class RelationalQueryTranslationPostprocessor : QueryTranslationPostproce
...
-        // Verifies that all table aliases are uniquely assigned without skipping over
-        // Which points to possible mutation of a SelectExpression being used in multiple places.
-        new TableAliasVerifyingExpressionVisitor().Visit(query);
+        new SelectExpressionMutableVerifyingExpressionVisitor().Visit(query4);
 #endif
 
-        query = new SqlExpressionSimplifyingExpressionVisitor(RelationalDependencies.SqlExpressionFactory, _useRelationalNulls)
-            .Visit(query);
-        query = new RelationalValueConverterCompensatingExpressionVisitor(RelationalDependencies.SqlExpressionFactory).Visit(query);
+        var query5 = new SqlExpressionSimplifyingExpressionVisitor(RelationalDependencies.SqlExpressionFactory, _useRelationalNulls)
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs:55]: Changed to make it easier to debug and compare multiple versions of the tree in the various phases.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 3]
```diff
@@ -4536,6 +4538,28 @@ public void Prune(SqlTreePruner pruningVisitor, bool pruneProjection)
...
     }
 
+    /// <summary>
+    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+    ///     any release. You should only use it directly in your code with extreme caution and knowing that
+    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+    /// </summary>
+    [EntityFrameworkInternal]
+    public void ChangeTableAlias(int tableIndex, string newAlias, HashSet<TableReferenceExpression> visitedTableReferences)
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:4548]: This is a very temporary hack to allow SqlAliasManager to change the alias during post-processing. The subsequent PR will remove TableReferenceExpression altogether and this will go away.

File: src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs [hunk 4]
```diff
@@ -37,24 +39,24 @@ public class RelationalQueryTranslationPostprocessor : QueryTranslationPostproce
...
+
+        // TODO: This - and all the verifications below - should happen after all visitors have run, including provider-specific ones.
+        var query4 = _sqlAliasManager.PostprocessAliases(query3);
 
 #if DEBUG
         // Verifies that all SelectExpression are marked as immutable after this point.
-        new SelectExpressionMutableVerifyingExpressionVisitor().Visit(query);
-        // Verifies that all table aliases are uniquely assigned without skipping over
-        // Which points to possible mutation of a SelectExpression being used in multiple places.
-        new TableAliasVerifyingExpressionVisitor().Visit(query);
```
Comment (roji) [inline src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs:50]: This verification visitor no longer makes sense, but I'll be introducing something better to check correct table/column scoping, after TableReferenceExpression is gone.

File: test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs [hunk 5]
```diff
@@ -1345,15 +1345,15 @@ public override async Task Json_multiple_collection_projections(bool async)
     {
         await base.Json_multiple_collection_projections(async);
 
-        AssertSql(
-            """
-SELECT [j].[Id], [t].[Id], [t].[SomethingSomething], [t].[key], [t0].[Id], [t0].[Name], [t0].[Names], [t0].[Number], [t0].[Numbers], [t0].[c], [t0].[c0], [t1].[key], [t1].[Id], [t1].[Date], [t1].[Enum], [t1].[Enums], [t1].[Fraction], [t1].[NullableEnum], [t1].[NullableEnums], [t1].[c], [t1].[c0], [t1].[key0], [j0].[Id], [j0].[Name], [j0].[ParentId]
+AssertSql(
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs:1348]: nit: missing tab

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 6]
```diff
@@ -191,8 +200,10 @@ when entityQueryRootExpression.GetType() == typeof(EntityQueryRootExpression)
                         RelationalStrings.SqlQueryUnmappedType(sqlQueryRootExpression.ElementType.DisplayName()));
                 }
 
+                var alias = _sqlAliasManager.GenerateTableAlias("t");
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:203]: "table" ?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs [hunk 7]
```diff
@@ -860,21 +823,15 @@ public TpcTableExpressionRemovingExpressionVisitor(HashSet<string> usedAliases)
...
-                        // If we are lifting then we remove the alias for tpc because it will be unused.
-                        _usedAliases.Remove(tpcTablesExpression.Alias);
-                    }
-
                     RemapProjections(reindexingMap, firstSelectExpression);
                     var result = subSelectExpressions[0];
                     for (var i = 1; i < subSelectExpressions.Count; i++)
                     {
-                        var setOperationAlias = GenerateUniqueAlias(_usedAliases, "t");
+                        var setOperationAlias = _sqlAliasManager.GenerateTableAlias("t");
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs:830]: table

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 8]
```diff
@@ -349,7 +362,7 @@ internal SelectExpression(IEntityType entityType, ISqlExpressionFactory sqlExpre
                     }
 
                     // We only assign unique alias to Tpc
-                    var tableAlias = GenerateUniqueAlias(_usedAliases, "t");
+                    var tableAlias = _sqlAliasManager.GenerateTableAlias("t");
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:365]: table

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 9]
```diff
@@ -2566,10 +2581,9 @@ private void ApplySetOperation(SetOperationType setOperationType, SelectExpressi
             throw new InvalidOperationException(RelationalStrings.ProjectionMappingCountMismatch);
         }
 
-        var setOperationAlias = GenerateUniqueAlias(_usedAliases, "t");
+        var setOperationAlias = _sqlAliasManager.GenerateTableAlias("t");
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2584]: "table"

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 10]
```diff
@@ -3954,17 +3969,16 @@ public void PushdownIntoSubquery()
     /// <param name="liftOrderings">Whether orderings on the query should be lifted out of the subquery.</param>
     private SqlRemappingVisitor PushdownIntoSubqueryInternal(bool liftOrderings = true)
     {
-        var subqueryAlias = GenerateUniqueAlias(_usedAliases, "t");
+        var subqueryAlias = _sqlAliasManager.GenerateTableAlias("t");
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:3972]: "table"

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 11]
```diff
@@ -349,7 +362,7 @@ internal SelectExpression(IEntityType entityType, ISqlExpressionFactory sqlExpre
                     }
 
                     // We only assign unique alias to Tpc
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:364]: is this comment still true?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 12]
```diff
@@ -1094,7 +1118,7 @@ void ProcessTypeProjection(StructuralTypeProjectionExpression projection)
                 && (containsSingleResult || containsCollection))
             {
                 // SingleResult can lift collection from inner
-                cloningExpressionVisitor = new CloningExpressionVisitor();
+                cloningExpressionVisitor = new CloningExpressionVisitor(sqlAliasManager: null);
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1121]: maybe add brief comment here as well, why alias manager is null

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 13]
```diff
@@ -2586,17 +2600,13 @@ private void ApplySetOperation(SetOperationType setOperationType, SelectExpressi
...
 
-            // We have to unique-fy left side since those projections were never uniquified
-            // Right side is unique already when we did it when running select2 through it.
-            innerColumn1 = (SqlExpression)aliasUniquifier.Visit(innerColumn1);
-
-            var alias = GenerateUniqueColumnAlias(
+            var projectionAlias = GenerateUniqueColumnAlias(
                 projectionMember.Last?.Name
                 ?? (innerColumn1 as ColumnExpression)?.Name
                 ?? "c");
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2606]: "column"

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 14]
```diff
@@ -280,11 +291,13 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
         {
             var tableAlias = sqlExpression switch
             {
-                ColumnExpression c => c.Name[..1].ToLowerInvariant(),
-                JsonScalarExpression { Path: [.., { PropertyName: string propertyName }] } => propertyName[..1].ToLowerInvariant(),
+                ColumnExpression c => c.Name,
+                JsonScalarExpression { Path: [.., { PropertyName: string propertyName }] } => propertyName,
                 _ => "j"
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:296]: "json" ? (not sure if this is right meaningful name for this or if it matters at all, we never seem to hit this code in our tests

**Review by maumar — APPROVED** [review]

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs (hunk 14 above)
Comment (roji) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:296]: Good catch. This method is generally for when a member access resolves to an IProperty that's a primitive collection. The usual cases are a direct collection column access (e.g. JSON primitive collection column) - in which case we take the column name - or JsonScalarExpression (access a primitive collection within an owned JSON document) - in which case we take the last property name of the path.

I did some improvements to this code, to better handle JsonScalarExpression ending with array access: get the last path segment with a name, if there is none, calculate the alias from the JsonScalarExpression's Json expression (this is e.g. for a JSON array access directly inside an owned JSON document). I also handling for when the primitive collection is a result of a scalar subquery (e.g. `Where(b => b.Posts.First().Tags[0] == "foo")`). Finally, I changed the default from "j" to "collection", since it may not be JSON at all (e.g. on PostgreSQL).

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs (hunk 6 above)
Comment (roji) [reply src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:203]: Good suggestion... I went over the places where we generate generic "t" as the alias, and changed them to fit the actual table (e.g. for set operations it will now be "union" for unions, "intersect" for intersect etc.)

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 11 above)
Comment (roji) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:364]: Yeah, removed - thanks.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 12 above)
Comment (roji) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1121]: Good idea, done.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 13 above)
Comment (roji) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2606]: Note that this PR doesn't do anything to projection (column) aliases, only to table aliases; opened #32821 to track managing projection aliases via the new manager as well.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 10 above)
Comment (roji) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:3972]: Here I went the extra mile - if the subquery being pushed down contains a single table, we lift up its own alias to also become the enclosing subquery's alias (plus uniquification of course). This should make it easier to understand what actual data the subquery is bubbling up - especially if we implement wider aliases.

**Review by maumar — APPROVED** [review]

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 15]
```diff
@@ -2648,7 +2661,6 @@ private void ApplySetOperation(SetOperationType setOperationType, SelectExpressi
 
         // We generate actual set operation after applying projection to lift group by aggregate
         // select1 already has unique aliases. We unique-fy select2 and set operation alias.
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2663]: `// select1 and select2 already has unique aliases. We unique-fy set operation alias.`

Comment (roji) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2663]: Done in #32812
