### PR TITLE
Fix to #18211 - Throw better exception for Last without order by

### LINKED ISSUE #18211: Throw better exception for Last without order by
Currently it throws error as ran into client eval. It would be more useful to say that Last is used without order by.

This line should throw exception rather than returning null. (Returning null throws client eval message.

https://github.com/aspnet/EntityFrameworkCore/blob/d005f540471db0b891efb6fdc1cc0c6fc3b21657/src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs#L543-L546

Also cosmos does not verify for ordering before LastOrDefault. Should probably do that too.

### PR DESCRIPTION
**Pull request by Muppets**
Summary of the changes
 - Added throw to TranslateLastOrDefault to give a friendly exception

Not great at exception message text at the best of times. I went with:

When performing a Last() operation, you must include an OrderBy clause.

I'm open to suggestions on better text!

Fixes #18211

### CODE REVIEW

**Comment by ajcvickers** [comment]
@maumar Can you take a look at this PR? Looks decent to me, but it is query. ;-)

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs [hunk 1]
```diff
@@ -655,6 +655,11 @@ public override async Task Last(bool async)
 ORDER BY [c].[ContactName] DESC");
         }
 
+        public override Task Last_when_no_order_by(bool async)
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs]: remove the override

File: src/EFCore/Properties/CoreStrings.resx [hunk 2]
```diff
@@ -1266,4 +1266,7 @@
   <data name="SkipNavigationInUseBySkipNavigation" xml:space="preserve">
     <value>The skip navigation '{skipNavigation}' cannot be removed because it is set as the inverse of the skip navigation '{inverseSkipNavigation}' on '{referencingEntityType}'. All referencing skip navigations must be removed before this skip navigation can be removed.</value>
   </data>
+  <data name="LastUsedWithoutOrderBy" xml:space="preserve">
+    <value>When performing a Last() operation, you must include an OrderBy clause.</value>
```
Comment (maumar) [inline src/EFCore/Properties/CoreStrings.resx]: How about (since the exception affects both methods): 
Queries performing 'Last' and 'LastOrDefault' operations must contain an OrderBy clause.

**Comment by maumar** [comment]
some minor changes, looks good otherwise!

File: src/EFCore/Properties/CoreStrings.resx (hunk 2 above)
Comment (smitpatel) [reply src/EFCore/Properties/CoreStrings.resx]: Contain is too broad. This could fail in projection when doing on subquery and outer has an orderby. Should mention before in some way.

File: test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs [hunk 3]
```diff
@@ -976,13 +976,15 @@ public virtual Task Last(bool async)
...
         [ConditionalTheory]
         [MemberData(nameof(IsAsyncData))]
-        public virtual Task Last_when_no_order_by(bool async)
-        {
-            return AssertTranslationFailed(
-                () => AssertLast(
-                    async,
-                    ss => ss.Set<Customer>().Where(c => c.CustomerID == "ALFKI"),
-                    entryCount: 1));
+        public virtual async Task Last_when_no_order_by(bool async)
```
Comment (smitpatel) [inline test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs]: Also add a test for LastOrDefault.

File: src/EFCore/Properties/CoreStrings.resx (hunk 2 above)
Comment (Muppets) [reply src/EFCore/Properties/CoreStrings.resx]: I've changed it to "Queries performing 'Last' and 'LastOrDefault' operations must contain an OrderBy clause." for now. I couldn't come up with anything better that says include it before.

Comment (smitpatel) [reply src/EFCore/Properties/CoreStrings.resx]: Make method name a paraemter.
"Queries performing '{method}' operation must have a deterministic sort order. Rewrite the query to apply an OrderBy clause on the sequence before calling '{method}'."

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 4]
```diff
@@ -552,7 +552,14 @@ private SqlExpression CreateJoinPredicate(Expression outerKey, Expression innerK
...
             {
-                return null;
+                var methodName = nameof(Queryable.Last);
+
+                if (returnDefault)
+                {
+                    methodName = nameof(Queryable.LastOrDefault);
+                }
+
+                throw new InvalidOperationException(CoreStrings.LastUsedWithoutOrderBy(methodName));
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs]:
```suggestion
                throw new InvalidOperationException(CoreStrings.LastUsedWithoutOrderBy(returnDefault ? nameof(Queryable.LastOrDefault) : nameof(Queryable.Last));
```

**Comment by Muppets** [comment]
Squashed and good to go!

**Comment by smitpatel** [comment]
@Muppets - Thanks
