### PR TITLE
SqlServer: date constant in DateAdd method is always datetime

### LINKED ISSUE #17507: DateTime.AddX failure
Describe what is not working as expected.

Using EFCore to timeshift timestamps does not work as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting date and/or time from character string.
```

### Steps to reproduce

```c#
            var slotSize = 2.0;
            var test = context.Records.Select(record => new
            {
                Timestamp = record.Timestamp,
                Test = new DateTime(1900, 1, 1)
                .AddMinutes(
                    Math.Round(
                        SqlServerDbFunctionsExtensions.DateDiffMinute(
                            null,
                            new DateTime(1900, 1, 1),
                            record.Timestamp) / slotSize,
                        0)
                    * slotSize)
            })
            .ToList();
```

The above generates SQL like this...
SELECT [record].[Timestamp], DATEADD(minute, ROUND(DATEDIFF(MINUTE, '1900-01-01T00:00:00.0000000', [record].[Timestamp]) / @__slotSize_0, 0) * @__slotSize_0, '1900-01-01T00:00:00.0000000') AS [Test]
FROM [Records] AS [record]

The issue is specifically in the DATEADD where it puts the second argument as '1900-01-01T00:00:00.0000000'.  
If I manually change that to be '1900-01-01T00:00:00.000' the query executes fine.  
Also, using DateTime.Now works as expected because the generated SQL contains GETDATE().
Additionally, referencing from another field also works fine, but it seems to be impossible to have a defined date like this which I need to do in order to time shift my actual dates to group them efficiently to the nearest slot size for dashboarding purposes.

I've also tried changing the DateTimeKind and can get it to render different output, but it's still invalid.  I am totally blocked on my project due to this bug.  Is there a workaround I can use or am I just doing something wrong?

To further complicate this, the above is a repro, in my actual code I'm generating this whole thing from an expression tree.

### Further technical details
EF Core version: 2.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #17507

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs [hunk 1]
```diff
@@ -74,24 +79,32 @@ public SqlServerDateTimeMethodTranslator([NotNull] ISqlExpressionFactory sqlExpr
...
-                            instance.Type,
-                            instance.TypeMapping);
+                        || (double)sqlConstant.Value <= int.MinValue))
+                {
+                    return null;
+                }
+
+                if (instance is SqlConstantExpression instanceConstant)
+                {
+                    instance = instanceConstant.ApplyTypeMapping(_typeMappingSource.FindMapping(typeof(DateTime), "datetime"));
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs:93]: :nauseated_face:

**Review by roji — APPROVED** [review]
