### PR TITLE
Fix to #30410 - JSON: optimize update path for single property element - don't wrap the value in json array

### LINKED ISSUE #30410: JSON: optimize update path for single property element - don't wrap the value in json array
Currently when updating single property inside json, we create parameter value as JSON array and put the value in it, then extract it in the update statement. This is because we want to guarantee the correct format of the value that we want to update (if we rely on database casting from a given type to string, we may end up in bad format and data gets corrupted. This only happens for some data types on sql server (guid, datetime, datetime offset) - so maybe we can special case. But need to look at Sqlite. Alternatively, if/when we have dedicated type mapping for json, we might be able to always generate parameter string value in correct format to be stored inside JSON.

### PR DESCRIPTION
**Pull request by maumar**
Rather than generate a JSON parameter and extract correct value from it, we generate the parameter value directly. Special casing is handled on the provider level by *ModificationCommand and *UpdateSqlGenerator

Fixes #30410

### CODE REVIEW

File: src/EFCore.Relational/Update/ModificationCommand.cs [hunk 1]
```diff
@@ -699,14 +700,23 @@ void HandleColumnModification(IColumnMappingBase columnMapping)
...
-        => JsonValue.Create(propertyValue);
+    protected virtual object? GenerateValueForSinglePropertyUpdate(IProperty property, object? propertyValue)
+    {
+        var propertyProviderClrType = (property.GetTypeMapping().Converter?.ProviderClrType ?? property.ClrType).UnwrapNullableType();
+
+        return (propertyProviderClrType == typeof(DateTime)
+            || propertyProviderClrType == typeof(DateTimeOffset)
+            || propertyProviderClrType == typeof(TimeSpan)
+            || propertyProviderClrType == typeof(Guid))
+            ? JsonValue.Create(propertyValue)?.ToJsonString().Replace("\"", "")
```
Comment (maumar) [inline src/EFCore.Relational/Update/ModificationCommand.cs:717]: problem?

**Comment by maumar** [comment]
@bricelam yes, temporary until we figure out the correct type mapping infra for JSON. Once we have it, the mapping itself should be able to render the correct representation of the parameter value and that entire internal API can be removed

File: test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs [hunk 2]
```diff
@@ -482,13 +482,13 @@ public override async Task Edit_single_numeric_property()
...
-@p0='[1024]' (Nullable = false) (Size = 6)
-@p1='[999]' (Nullable = false) (Size = 5)
+@p0='1024' (DbType = String)
+@p1='999' (DbType = String)
 @p2='1'
 
 SET IMPLICIT_TRANSACTIONS OFF;
 SET NOCOUNT ON;
-UPDATE [JsonEntitiesBasic] SET [OwnedCollectionRoot] = JSON_MODIFY([OwnedCollectionRoot], 'strict $[1].Number', CAST(JSON_VALUE(@p0, '$[0]') AS int)), [OwnedReferenceRoot] = JSON_MODIFY([OwnedReferenceRoot], 'strict $.Number', CAST(JSON_VALUE(@p1, '$[0]') AS int))
+UPDATE [JsonEntitiesBasic] SET [OwnedCollectionRoot] = JSON_MODIFY([OwnedCollectionRoot], 'strict $[1].Number', CAST(@p0 AS int)), [OwnedReferenceRoot] = JSON_MODIFY([OwnedReferenceRoot], 'strict $.Number', CAST(@p1 AS int))
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs:491]: I guess I'm still not clear on why we're sending 1024 as a string parameter, and then casting server side - can't we just send an int parameter instead? Effectively the following:

```sql
DECLARE @value INT = 1024;
SELECT JSON_MODIFY('{ "Number" : 1, "Bool" : true }', 'strict $.Number', @value);
```

Result: `{ "Number" : 1024, "Bool" : true }`

In other words, JSON_MODIFY knows how to get a nice (non-JSON!) SqlParameter value and convert it to the right JSON representation. Essentially the same thing we were just discussing for OPENJSON, but the other way around (OPENJSON converts a JSON value to a non-JSON SQL Server value).

This even works well for bool:

```sql
DECLARE @value BIT = 0;
SELECT JSON_MODIFY('{ "Number" : 1, "Bool" : true }', 'strict $.Bool', @value);
```

Result: `{ "Number" : 1, "Bool" : false }`

(but maybe the idea is for this to be resolved in a next PR)

**Review by roji — APPROVED** [review]
Thanks, this indeed looks much better. I'm not looking too closely at the implementation since it's a temporary situation before we properly solve the JSON type mapping infra stuff.

Note the comment below though (which can be handled separately from this PR)

File: test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs (hunk 2 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs:491]: we don't have type mapping for int/bool/etc in this context. The only type mapping we have is the json column one, so all parameters are created based on it. This should all be solved with proper mapping for json.
