### PR TITLE
Query: Defer inline-ing owned navigation expansion till all joins are…

### LINKED ISSUE #26592: efcore6 produces wrong SELECT SQL when Where/OrderBy clauses are applied to Owned properties followed by .Take()
Hi everyone,

I found a bug in efcore6 that now produces an invalid SELECT statement when filtering/sorting on owned types stored on other tables.
In particular, the bug happens when **more than one** owned type is linked to an entity and the where clause is applied NOT to the last owned property, followed by a .Take() clause.

Can you please check this behavior? Thanks in advance!

### Example
A Company entity that can be either a Customer, a Supplier or both.
Additional Customer data and Supplier data are stored in separate tables with a 1..1 relationship with the Company table.
These tables are configured as Owned properties of Customer:

```C#
/// <summary>
/// Entity representing a company. 
/// A company can be either a customer, a supplier, or both.
/// If the company is a cutomer and/or a supplier, additional data describing customer/supplier is stored in
/// owned types CustomerData and SupplierData, stored in two separate tables with a 1..1 relationship with Company
/// </summary>
public class Company
{
    public int Id { get; set; }

    public string? Name { get; set; }
    public CustomerData? CustomerData { get; set; }
    public SupplierData? SupplierData { get; set; }
}

/// <summary>
/// Owned 1 of Company in 1..1 relationship, on another table
/// </summary>
public class CustomerData
{
    public int Id { get; set; }
    public string? AdditionalCustomerData { get; set; }

}

 /// <summary>
 /// Owned 2 of Company in 1..1 relationship, on another table
 /// </summary>
 public class SupplierData
 {
     public int Id { get; set; }
     public string? AdditionalSupplierData { get; set; }

 }
```

Mapping:

```C#
internal class CompanyMapping : IEntityTypeConfiguration<Company>
{
    public void Configure(EntityTypeBuilder<Company> builder)
    {
        builder.ToTable("Companies");

        builder.HasKey(r => r.Id);
        builder.Property(r=>r.Id).UseIdentityColumn();

        builder.OwnsOne(r => r.CustomerData,
            b =>
            {
                b.ToTable("CustomerData");

                b.HasKey(r => r.Id);

                b.WithOwner().HasForeignKey(r => r.Id).HasPrincipalKey(r => r.Id);
            });

        builder.OwnsOne(r => r.SupplierData,
            b =>
            {
                b.ToTable("SupplierData");

                b.HasKey(r => r.Id);

                b.WithOwner().HasForeignKey(r => r.Id).HasPrincipalKey(r => r.Id);
            });
    }
}
```

Executing the following query

```C#
var ctx = GetDbContext();

var q = ctx.Companies
        .Where(r => r.CustomerData != null)
        .Take(10);

var results = await q.ToArrayAsync();

```
will produce the following wrong SQL when using efcore6:
``` SQL
-- sql generated by efcore6 (wrong)
-- Columns of the first owned type are NOT included in the inner select, so they are not available in the outer select
-- A left join is also missing from the outer select
DECLARE @__p_0 int = 10;

SELECT[t].[Id], [t].[Name], [c0].[Id], [c0].[AdditionalCustomerData], [s].[Id], [s].[AdditionalSupplierData]
FROM(
    SELECT TOP(@__p_0)[c].[Id], [c].[Name]
    FROM[Companies] AS[c]
    LEFT JOIN[CustomerData] AS[c0] ON[c].[Id] = [c0].[Id]
    WHERE[c0].[Id] IS NOT NULL
) AS[t]
LEFT JOIN[SupplierData] AS[s] ON[t].[Id] = [s].[Id]

-- Error: The multi-part identifier "c0.AdditionalCustomerData" could not be bound.
```

the same query works as expected in efcore5, producing the following valid SQL:
``` SQL
-- sql generated by efcore5 (working)
DECLARE @__p_0 int = 10;

SELECT[t].[Id], [t].[Name], [t].[Id0], [t].[AdditionalCustomerData], [s0].[Id], [s0].[AdditionalSupplierData]
FROM(
    SELECT TOP(@__p_0)[c].[Id], [c].[Name], [c0].[Id] AS[Id0], [c0].[AdditionalCustomerData]
    FROM[Companies] AS[c]
    LEFT JOIN[CustomerData] AS[c0] ON[c].[Id] = [c0].[Id]
    WHERE[c0].[Id] IS NOT NULL
) AS[t]
LEFT JOIN[SupplierData] AS[s] ON[t].[Id] = [s].[Id]
LEFT JOIN[SupplierData] AS[s0] ON[t].[Id] = [s0].[Id]

```

## Attached solution

[EfCore6Bugs.zip](https://github.com/dotnet/efcore/files/7505549/EfCore6Bugs.zip)

The solution contains projects targeting .net5.0 with efcore 5.0.12 and .net6.0 with efcore 6.0.0.  
The first project contains the DbContext, the second one is a simple unit test.

On test initialization, an `EfCore6Bugs` database will be created on (LocalDb)\\MSSQLLocalDB (please customize the connection string in `TestDataContext.cs` as needed) applying migrations for the DbContext.
Unit tests should all be successful for .net5.0 (efcore5), while **EfCore6ClausesOnFirstOwnedFails** will fail for .net6.0 (efcore6)

### PR DESCRIPTION
**Pull request by smitpatel**
… generated

Issue: Expanding owned navigations in relational falls into 3 categories
- Collection navigation - which always generates a subquery. The predicate is generated in LINQ to allow mutation of outer SelectExpression
- Reference navigation sharing table - which picks column from same table without needing to add additional join. This only mutate the projection list for SelectExpression at subquery level
- Reference navigation mapped to separate table - which generates additional joins. Generating join can cause push down on outer SelectExpression if it has facets (e.g. limit/offset). This pushdown causes owned expansion from category 2 to be outdated and invalid SQL since they get pushed down to subquery. While their relevant entity projection is updated inside SelectExpression we already inlined older object in the tree at this point.

In order to avoid issue with outdated owned expansion, we defer actual inline-ing while processing owned navigations so that all navigations are expanded (causing any mutation on SelectExpression) before we inline values.

This PR introduces DeferredOwnedExpansionExpression which remembers the source projection binding to SelectExpression (which will remain accurate through pushdown), and navigation chain to traverse entity projections to reach entity shaper for final owned navigation. This way, we get up-to-date information from SelectExpression after all joins are generated.
We also find updated entity projection through binding after we generate a join if pushdown was required.

Resolves #26592

The issue was also present in 5.0 release causing non-performant SQL rather than invalid SQL. During 5.0 we expanded owned navigations again while during client eval phase (which happens in customer scenario due to include). This caused to earlier owned reference to have correct columns. Though the entity projection for owner was changed due to pushdown so we didn't add latter reference navigation binding in correct entity projection causing us to expand it again during 2nd pass.
The exact same issue doesn't occur for InMemory provider (due to slightly different implementation) though we should also make InMemory provider work this way, submitting in a different PR in case we need to cherry-pick this for patch.

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 1]
```diff
@@ -1206,7 +1204,23 @@ protected override Expression VisitExtension(Expression extensionExpression)
                             makeNullable);
 
                         var joinPredicate = _sqlTranslator.Translate(Expression.Equal(outerKey, innerKey))!;
+                        // Following conditions should match conditions for pushdown on outer during SelectExpression.AddJoin method
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs:1207]: should we add a helper method on select expression for this? (maybe also same thing for pushdown?)

**Comment by smitpatel** [comment]
Some day team will approve this PR. 😢

**Review by AndriySvyryd — APPROVED** [review]
