### PR TITLE
Fix for 15958. Do not allow the user to register proxy types.

### LINKED ISSUE #15958: `NullReferenceException` when attempting to explicitly map a proxy type
Attempting to create an application that connects to two databases seems to fail. For example, if I try to connect to SQLite and InMemory database at the same time (other combinations also fail), attempt to access ChangeTracker on the second DbContext results in a System.NullReferenceException: 'Object reference not set to an instance of an object.' This exception appears to happen in the ChangeTracker getter.

See the exception details below:

```
Exception message: System.NullReferenceException: 'Object reference not set to an instance of an object.'
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyParameterBindingFactory.GetCandidatePropertyNames(String parameterName)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyParameterBindingFactory.TryBindParameter(IMutableEntityType entityType, Type parameterType, String parameterName)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ConstructorBindingFactory.<>c__DisplayClass3_0.<TryBindConstructor>b__0(ParameterInfo p)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ConstructorBindingFactory.TryBindConstructor(IMutableEntityType entityType, ConstructorInfo constructor, ConstructorBinding& binding, IEnumerable`1& failedBindings)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConstructorBindingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator, DiagnosticsLoggers loggers)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator, DiagnosticsLoggers loggers)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at EFCoreTester.Program.<Main>d__0.MoveNext() in C:\Users\ilyabasin\Documents\Projects\TDM.Core\Frameworks\Testers\EFCoreTester\Program.cs:line 30

```

### Steps to reproduce
The error is easy to reproduce. 

Use the following code snippet to reproduce:

```c#
            using (var context = new InMemoryDbContext())
            {
                var ct = context.ChangeTracker;
                context.Set<Author>().Add(new Author { Name = "Author1" });
                await context.SaveChangesAsync();
            }

            using (var context = new SqliteDbContext())
            {
                var ct = context.ChangeTracker;
                context.Set<Author>().Add(new Author { Name = "Author2" });
                await context.SaveChangesAsync();
            }
```
Both SqliteDbContext and InMemoryDbContext are plain vanilla. Just note that I have lazy loading turned on for both contexts. 

### Further technical details
EF Core version: 3.0.0-preview5.19227.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite & Microsoft.EntityFrameworkCore.InMemory 
Operating system: Windows 10
IDE: Visual Studio 2019 Preview

### PR DESCRIPTION
**Pull request by lajones**
Fixes #15958. Do not allow the user to register dynamically-generated proxy types in the ModelBuilder.

### CODE REVIEW

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs [hunk 1]
```diff
@@ -63,6 +65,13 @@ public InternalModelBuilder([NotNull] Model metadata)
         private InternalEntityTypeBuilder Entity(
             in TypeIdentity type, ConfigurationSource configurationSource, bool? shouldBeOwned)
         {
+            if (DynamicProxyGenAssemblyName.Equals(
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalModelBuilder.cs]: This should be done in the `EntityType` constructor to cover all scenarios.

Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs]: @ajcvickers What do you think? The `EntityType` constructor as @AndriySvyryd says would cover more scenarios.

Comment (ajcvickers) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs]: @lajones Yes. The bug indicated a bad model. We should prevent building bad models, not just throw a better exception if the model is bad.

File: src/EFCore.Design/Design/Internal/MigrationsOperations.cs [hunk 2]
```diff
@@ -90,6 +90,13 @@ public class MigrationsOperations
             var subNamespace = SubnamespaceFromOutputPath(outputDir);
 
             using var context = _contextOperations.CreateContext(contextType);
+            var contextClassName = context.GetType().Name;
+            if (string.Equals(name, contextClassName, StringComparison.Ordinal))
+            {
+                throw new OperationException(
+                    DesignStrings.ConflictingContextAndMigrationName(name));
+            }
+
```
Comment (lajones) [inline src/EFCore.Design/Design/Internal/MigrationsOperations.cs]: Ignore this. I appear to have pulled in a change from another branch somehow. Will fix before check in.

File: src/EFCore.Design/Properties/DesignStrings.resx [hunk 3]
```diff
@@ -363,4 +363,7 @@ Change your target project to the migrations project by using the Package Manage
   <data name="UnhandledEnumValue" xml:space="preserve">
     <value>Unhandled enum value '{enumValue}'.</value>
   </data>
+  <data name="ConflictingContextAndMigrationName" xml:space="preserve">
+    <value>The name you have chosen for the migration, '{name}', is the same as the context class name. Please choose a different name for your migration. Might we suggest 'InitialCreate' for your first migration?</value>
+  </data>
```
Comment (lajones) [inline src/EFCore.Design/Properties/DesignStrings.resx]: Ignore this. I appear to have pulled in a change from another branch somehow. Will fix before check in.

File: src/EFCore/Metadata/Internal/InternalModelBuilder.cs (hunk 1 above)
Comment (lajones) [reply src/EFCore/Metadata/Internal/InternalModelBuilder.cs]: Updated.

File: src/EFCore.Design/Design/Internal/MigrationsOperations.cs (hunk 2 above)
Comment (AndriySvyryd) [reply src/EFCore.Design/Design/Internal/MigrationsOperations.cs]: You should squash and rebase on latest master

Comment (lajones) [reply src/EFCore.Design/Design/Internal/MigrationsOperations.cs]: I've force-pushed this branch - this issue has gone away.
