### PR TITLE
[release/8.0] Fix to #30589 - Query/Json: improve JSON entity/collection comparisons to null (fails currently for optional dependent with all nullable properties)

### LINKED ISSUE #30589: Query/Json: improve JSON entity/collection comparisons to null (fails currently for optional dependent with all nullable properties)
I'm using EFCore 7.

I have a ef core model likes below, the column `Address` that allows json string or null:
```csharp
  modelBuilder.Entity<User>(e =>
  {
      e.OwnsOne(p => p.Address, b => b.ToJson());
  });

public partial class User
{
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; } = null!;
    ...
    public UserAddress? Address { get; set; } = null!;
}
```

And I faced two questions:

1. When I executed the query likes below:
```csharp
_labDBContext.Users.Select(x => new Model_User()
{
    Name = x.Name,
     ...
    UserAddress = x.Address
}).ToList();
```
I would get error message `variable '' of type 'IScom_Test_API.Models.DBModels.LabDB.UserAddress' referenced from scope '', but it is not defined`

but if I change to the code as below, it will work as expected:
```csharp
_labDBContext.Users.Select(x => new Model_User()
{
    Name = x.Name,
     ...
    UserAddress = new()
    {
        City = x.Address.City,
        Country = x.Address.Country
    }
}).ToList();
```
I'm not sure if there's any problem or limitation about EFCore's `Select` function or not?

2. And I have another code as below, the same, want to select or filter the IQuerable variable with a json column `Address`:
```csharp
_labDBContext.Users.Where(x => x.Address == null).ToList();
```

It'll also return the errors, 
`Error creating query string: The LINQ expression 'DbSet<User>()
    .Where(u => EF.Property<UserAddress>(u, "Address") == null)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information..`
    
I think the reasons that caused the two questions are similar, does anyone knows why would it  cause error if I want to manipulate a json column?

### PR DESCRIPTION
**Pull request by maumar**
Fixes #30589

**Description**

Handling of optional dependent json entity was incorrect. We were using the same logic as for regular entities, however in case of JSON we don't have the same issues. We can simply compare the json column to null, or navigate to appropriate json property inside the column and compare that to null. Additionally, this should give exactly the same results as LINQ to objects - we don't have the problem where we can't distinguish null entity from entity with all values being null, if they are all optional.

**Customer impact**

Translation error for optional dependent JSON entities being compared to null, if all the properties are nullable. Inefficient sql generated when there are some non-nullable properties.

**How found**

Customer report on 7.0

**Regression**

No. JSON has been added in 7.0

**Testing**

Added regression tests for affected scenarios.

**Risk**

Very low: Fix is isolated to only affect scenarios where we compare JSON entity to null, and it is very simple - just compare the JSON column or appropriate JSON_QUERY to null. Before we would apply the same logic as for regular entities (looking at individual columns), which was much more complicated (on top of not being 100% correct)

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs [hunk 1]
```diff
@@ -1755,6 +1755,25 @@ bool TryRewriteEntityEquality([NotNullWhen(true)] out Expression? result)
             {
                 var nonNullEntityReference = (IsNullSqlConstantExpression(left) ? rightReference : leftReference)!;
                 var nullComparedEntityType = (IEntityType)nonNullEntityReference.StructuralType;
+
+                if (nullComparedEntityType.IsMappedToJson()
+                    && nonNullEntityReference.Parameter is not null
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs:1760]: @roji that's good enough check?

File: test/EFCore.SqlServer.FunctionalTests/Query/OptionalDependentQuerySqlServerTest.cs [hunk 2]
```diff
@@ -55,7 +65,7 @@ public override async Task Filter_optional_dependent_with_some_required_compared
 """
 SELECT [e].[Id], [e].[Name], [e].[Json]
 FROM [EntitiesSomeRequired] AS [e]
-WHERE CAST(JSON_VALUE([e].[Json], '$.ReqProp') AS float) IS NULL
+WHERE [e].[Json] IS NULL
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/OptionalDependentQuerySqlServerTest.cs:68]: Really nice improvement!

File: test/EFCore.SqlServer.FunctionalTests/Query/OptionalDependentQuerySqlServerTest.cs [hunk 3]
```diff
@@ -86,15 +101,20 @@ public override async Task Filter_nested_optional_dependent_with_all_optional_co
 """
 SELECT [e].[Id], [e].[Name], [e].[Json]
 FROM [EntitiesAllOptional] AS [e]
-WHERE CAST(JSON_VALUE([e].[Json], '$.OpNested2.ReqNested1') AS bit) IS NOT NULL AND CAST(JSON_VALUE([e].[Json], '$.OpNested2.ReqNested2') AS datetime2) IS NOT NULL
+WHERE JSON_QUERY([e].[Json], '$.OpNav2') IS NOT NULL
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/OptionalDependentQuerySqlServerTest.cs:104]: Even nicer improvement

File: src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs (hunk 1 above)
Comment (roji) [reply src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs:1760]: Yeah, LGTM!

On the nit side of things, pattern matching:

```c#
                if (nullComparedEntityType.IsMappedToJson()
                    && nonNullEntityReference is { Parameter.ValueBufferExpression: JsonQueryExpression jsonQueryExpression })
```

In fact, if the entity reference here is JsonQueryExpression as its ValueBufferExpression, I'm thinking that the entity type *must* be mapped to JSON, so the IsMappedToJson() bit may make sense as an assertion rather than a check. But of course it's OK to leave like this.

**Review by roji — APPROVED** [review]
