### PR TITLE
Fix bugs in SQL Server bulk insert management

### LINKED ISSUE #27840: Parameter and SQL length check don't take pending bulk insert commands into account
This means that if a user adds a massive amount of INSERTs, we would attempt to add them in a single batch even if they go over the parameter limit (2100), which would fail.

### LINKED ISSUE #28712: Rolling back a bulk insert command doesn't work
When a command is added to a batch which goes over a limit (e.g. too many commands, too many parameters), we "roll it back", resetting the batch's state as if that command wasn't added. When adding a bulk-insert command for SQL Server, this isn't done properly: the command is removed from the SQL Server pending commands list, but the base rollback tasks are skipped. As a result, the batch state partially remains as if the command has been successfully added.

### PR DESCRIPTION
**Pull request by roji**
For the parameter check, we previously added the parameters only when the pending bulk insert commands were applied; this is why they weren't being taken into account for the parameter limit check. The fix here is to move parameter adding to when the bulk insert command is added, just like any normal command; only the SQL addition is deferred.

Note that this won't support fancy bulk strategies, such as a single array parameter for multiple rows in PostgreSQL. But other things have to be done for that anyway, and this seems like an acceptable fix for now.

Fixes #27840
Fixes #28712

### CODE REVIEW

File: src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs [hunk 1]
```diff
@@ -73,9 +77,32 @@ protected override void RollbackLastCommand()
...
+                * (
+                    numColumns * 128 // column name lengths
+                    + 128 // schema name length
+                    + 128 // table name length
+                    + numColumns * 6 // column parameter placeholders
+                    + 300 // some extra fixed overhead
+                );
+        }
+
+        return sqlLength < MaxScriptLength;
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs:104]: We probably should log to Debug the reason why a batch is broken up, but this can be done later

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs (hunk 1 above)
Comment (roji) [reply src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs:104]: > but this can be done later

Like everything involving a new logging event, this now has a hard dependency on 28603 :rofl: 

#28717
