### PR TITLE
Fix for 19608. Truncate/Uniquify Sequence Names.

### LINKED ISSUE #19608: Truncate and uniquify sequence names
See https://github.com/npgsql/efcore.pg/issues/1198#issuecomment-574903194

### PR DESCRIPTION
**Pull request by lajones**
Fixes #19608 

Truncate and uniquify Sequence Names within each schema.

### CODE REVIEW

File: src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+            ref SortedDictionary<(string Name, string Schema), Sequence> modelSequences)
+        {
+            var sequenceNamesInSchema = new Dictionary<string, int>();
+            var sequencesToRemove = new List<(string Name, string Schema)>();
+            var sequencesToAdd = new Dictionary<(string Name, string Schema), Sequence>();
+            foreach (var sequenceNameToSequence in sequenceNameToSequences)
+            {
+                var originalSequenceName = sequenceNameToSequence.Key;
+                var newSequenceName =
+                    Uniquifier.Uniquify(originalSequenceName, sequenceNamesInSchema, maxLength);
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs:90]: You only need to do this if name is shorter than `maxLength` since there aren't any duplicates initially.

File: src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+        public virtual void ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext<IConventionModelBuilder> context)
+        {
+            var model = modelBuilder.Metadata;
+            var modelSequences =
+                (SortedDictionary<(string Name, string Schema), Sequence>)model[RelationalAnnotationNames.Sequences];
+
+            if (modelSequences != null)
+            {
+                var schemaToSequenceNameToSequences = new Dictionary<string, Dictionary<string, Sequence>>();
+                var nullSchemaSequenceNameToSequences = new Dictionary<string, Sequence>();
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs:47]: No need to build extra dictionaries, just use `modelSequences`, see https://github.com/dotnet/efcore/blob/0d76bbf45a42148924b413ef8f37bf49c1ce10d3/src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs#L91

File: src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+        public virtual void ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext<IConventionModelBuilder> context)
+        {
+            var model = modelBuilder.Metadata;
+            var modelSequences =
+                (SortedDictionary<(string Name, string Schema), Sequence>)model[RelationalAnnotationNames.Sequences];
+
+            if (modelSequences != null)
+            {
+                var maxLength = model.GetMaxIdentifierLength();
+                foreach (var sequence in modelSequences.ToList())
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs:48]: Don't call `ToList`, put the sequences that need to be removed in a new list instead. In the vast majority of cases no sequences need to be removed.

File: src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+                {
+                    var originalSequenceName = sequence.Key.Name;
+                    if (originalSequenceName.Length > maxLength)
+                    {
+                        var schemaName = sequence.Key.Schema;
+                        var modelSequencesExceptSelf = modelSequences
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs:54]: No need to exclude the original name. It's over the length limit so it would never be a candidate for the new name.

File: src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs (hunk 3 above)
Comment (lajones) [reply src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs:48]: OK. But I was trying to avoid that as I thought that was what you didn't like last time. Maybe I misread your comment. I'll update.

Comment (lajones) [reply src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs:48]: However that does cause a new issue. Previously the new uniquified name would be in modelSequences for the next iteration, and hence would stop anything else from uniquifying to the same thing. If I collect a list of elements to remove and add (but don't actually add or remove them just yet) then, to prevent the problem above, I must add the added ones to the dictionary of "already-used names" every time I loop. I can do this with a `Union()` but not sure whether that has any better performance than just using `ToList()` in the first place. I would only be doing that for the iterations which require uniquifying - so I'm going to assume that's probably better.

Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs:48]: Not sure why you would need to use Union, add the new one after removing the old one

Comment (lajones) [reply src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs:48]: I have a test case which fails if you don't.

I can't alter `modelSequences` while iterating over it (without using `ToList()`). So I have to collect the list of elements to remove and elements to add. If I create a new element which has name uniquified name `nnnnn` and in a later iteration I come across another sequence whose name would also uniquify to `nnnnn` I need to stop that. Only way of stopping (AFAICS) is to pass in the list of "new uniquified names" in addition to the original names i.e. `Union()`.

Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs:48]: You don't need to generate the new name when iterating over modelSequences. Do it while iterating over the sequences to remove

File: src/EFCore.Relational/Metadata/Internal/Sequence.cs [hunk 5]
```diff
@@ -138,6 +138,35 @@ public Sequence([NotNull] IModel model, [NotNull] string annotationName)
             Builder = new InternalSequenceBuilder(this, ((IConventionModel)model).Builder);
         }
 
+        /// <summary>
+        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+        ///     any release. You should only use it directly in your code with extreme caution and knowing that
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        public static Sequence WithNewName([NotNull] Sequence sequence, [NotNull] string name)
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Internal/Sequence.cs:147]: Make `_name` mutable and have this method do the remove and add to the sequences dictionary

Comment (lajones) [reply src/EFCore.Relational/Metadata/Internal/Sequence.cs:147]: `static` to match `AddSequence()` and `RemoveSequence()`, or non-`static` so we don't have to pass the `Sequence` we're updating in?

Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Internal/Sequence.cs:147]: static would be fine

File: src/EFCore.Relational/Metadata/Internal/Sequence.cs [hunk 6]
```diff
@@ -187,6 +186,36 @@ public static Sequence FindSequence([NotNull] IModel model, [NotNull] string nam
             return sequence;
         }
 
+        /// <summary>
+        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+        ///     any release. You should only use it directly in your code with extreme caution and knowing that
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        public static Sequence UpdateSequence(
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Metadata/Internal/Sequence.cs:195]: `SetName`
