### PR TITLE
[5.0.2] Stop marking the inverse navigation as loaded when loading a many-to-many navigation

### LINKED ISSUE #23475: Many-to-many lazy (and explicit) loading not working as expected
Using these model classes

```C#
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EFGetStarted
{
    public class BloggingContext : DbContext
    {
        public DbSet<Student> Students { get; set; }
        public DbSet<Course> Courses { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseLazyLoadingProxies().UseSqlite("Data Source=students.db");
    }

    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Course> Courses { get; set; }
    }

    public class Course
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
```

and this program

```C#
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EFGetStarted
{
    class Program
    {
        static void Main()
        {
            Write();
            Read();
        }

        static void Write()
        {
            using (var db = new BloggingContext())
            {
                Student s1 = new Student { Id = 1, Name = "Steven", Courses = new List<Course>() };
                Student s2 = new Student { Id = 2, Name = "Pascal", Courses = new List<Course>() };
                Course c1 = new Course { CourseId = 1, CourseName = "Wiskunde" };
                Course c2 = new Course { CourseId = 2, CourseName = "Geschiedenis" };
                s1.Courses.Add(c1);
                s1.Courses.Add(c2);
                s2.Courses.Add(c1);
                s2.Courses.Add(c2);
                db.Add(c1);
                db.Add(c2);
                db.Add(s1);
                db.Add(s2);
                db.SaveChanges();

            }
        }

        static void Read()
        {
            using (var db = new BloggingContext())
            {
                Student s1 = db.Students.Where(s => s.Id == 1).Single();
                // db.Entry(s1)
                // .Collection(s1 => s1.Courses)
                // .Load();
                // foreach (Course item in s1.Courses)
                // {
                //     Console.WriteLine(item.CourseName);
                // }
                Course c1 = db.Courses.Where(s => s.CourseId == 1).Single();
                // db.Entry(c1)
                // .Collection(c1 => c1.Students)
                // .Load();
                foreach (Student item in c1.Students)
                {
                    Console.WriteLine(item.Name);
                }
            }
        }
    }
}
```

the output is 

```
Steven
Pascal
```

as it should be. If the 'foreach' loop in 'Read' is uncommented (and the 'Write' is commented out), the output is

```
Wiskunde
Geschiedenis
Steven
```

This is unexpected, the output should include 'Pascal' as well. Using expicit loading results in similar unexpected behaviour.

Version:
Entity Framework Core .NET Command-line Tools
5.0.0

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #23475

This is a targeted patch fix which special cases many-to-many loading. I will file an issue for a more general solution using an appropriate general update to query. See #22022.

**Description**

This is a bug in many-to-many relationships, a major new feature in EF Core 5.0. When loading a collection navigation property, the inverse navigation property is marked as loaded. This is not correct, since only entities related to the source entity are loaded. This means that attempting to load the inverse is a no-op because it is already marked as loaded, and hence data is missing in the context.

**Customer Impact**

Related entities are not loaded from the database when they should be, leading to possible data corruption in an application that assumes this is working correctly. This will kind of problem is often hard to find since there is no error, just incorrect data.

**How found**

Customer reported on 5.0.0.

**Test coverage**

We did not have test coverage for this case. However, this isn't why we didn't catch this, since I didn't think about the consequences for the IsLoaded flag here, and only investigation of this issue made me realize the mistake. We have added more test coverage in this PR.

**Regression?**

No; new feature in 5.0.

**Risk**

Medium. The underlying problem is that we ere using `Include` in the generated query to do lazy loading. The behavior of Include is to set the collection as loaded, even if filtered, which means we can't change the default behavior of Include. Therefore, we have introduced a new internal `NotQuiteInclude` method that is processed the same as `Include` in the query pipeline, but then changes the final materialization delegate to indicate that the collection should not be loaded. This is new code path has been done in a way that it is only used for this case, and can be disabled with a quirk switch. It has also been reviewed in detail by the team and we have added more testing.

### CODE REVIEW

File: src/EFCore/Query/IncludeExpression.cs [hunk 1]
```diff
@@ -56,6 +76,11 @@ public class IncludeExpression : Expression, IPrintableExpression
         /// </summary>
         public virtual INavigationBase Navigation { get; }
 
+        /// <summary>
+        ///     True if the navigation will be marked as loaded.
+        /// </summary>
+        public virtual bool SetLoaded { get; }
```
Comment (smitpatel) [inline src/EFCore/Query/IncludeExpression.cs:82]: Will it be ok if we remove this in 6.0? (In case we fix this better way)

Comment (ajcvickers) [reply src/EFCore/Query/IncludeExpression.cs:82]: We should make it pubternal for now.

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs [hunk 2]
```diff
@@ -29,6 +29,7 @@ public EntityReference(IEntityType entityType)
             public bool IsOptional { get; private set; }
             public IncludeTreeNode IncludePaths { get; private set; }
             public IncludeTreeNode LastIncludeTreeNode { get; private set; }
+            public bool SetLoaded { get; private set; } = true;
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs:32]: This should go on the IncludeTreeNode to indicate that the particular Include should not be marked as loaded. It can cause odd issues on EntityReference.

**Comment by smitpatel** [comment]
Add some additional tests around using `context.Entry(e).Collection(e => e.SkipNavigation)` queryable with other includes/filtered-include/join/projection-removing-entity-from-result.

**Comment by ajcvickers** [comment]
@smitpatel Updated and added new tests.

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs [hunk 3]
```diff
@@ -127,7 +130,7 @@ public IncludeTreeNode AddNavigation(INavigationBase navigation)
 
                 if (nodeToAdd == null)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs:131]: If we find existing node, we need to combine setIsLoaded of both.
An example
`entry.Collection(e => e.TwoSkipShared).Query().Include(e => e.OneSkipShared)`

Since the query we generate for collection combining above would be
```C#
context.Set<EntityOne>()
.AsTracking()
.Where(e => e.Id == left.Id)
.SelectMany(e => e.TwoSkipShared)
.NotQuiteInclude(e => e.OneSkipShared.Where(e => e.Id == left.Id))
.Include(e => e.OneSkipShared)
```
In above case we need to market OneSkipShared as loaded.

Another bug (not in this PR but probably exist in 5.0) is that above kind of query will apply include filter even though the user specified Include did not have filter. So user will get incorrect data from what they asked for. 😞

Comment (ajcvickers) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs:135]: First issue is fixed, and tests added. Once setLoaded becomes true it will never become false, and if it was false but we include the same navigation again, then we make it true.

As discussed in triage, please file a separate issue for the filter issue.

**Review by smitpatel — APPROVED** [review]

**Comment by ajcvickers** [comment]
@dotnet/efteam Given the risk, I would appreciate some additional reviews on this. In particular, from @maumar, but also from anyone else. Look for cases where this change may impact other queries, such as the cases that Smit has previously called out.

**Comment by ajcvickers** [comment]
Approved by Tactics for 5.0.2. Please wait for the branch to open before merging.

**Comment by maumar** [comment]
@ajcvickers you could also add test that uses query with Include/FilteredInclude directly and make sure that the other side is not being loaded.

**Review by maumar — APPROVED** [review]
