### PR TITLE
[release/7.0] Fix for some minor bugs around JSON mappings

### LINKED ISSUE #29214: EF7 Json column: constructor with optional enum-parameter throws ArgumentException
I've attached a minimal repo that produces the exception.

https://github.com/alienwareone/EfCoreContructorBinding

### LINKED ISSUE #29217: Json: nullable enums on entities mapped to json don't use enum-to-int converter, rather than string, like for non-nullable enums
in RelationalMapToJsonConvention.ProcessModelFinalizing we are looking for all properties whose clr type IsEnum is true. However, this returns false for the nullable enums. We should take that case into account also

### LINKED ISSUE #29219: Json: error when trying to materialize json entity with nullable property that is missing in the json string - should materialize the property as null instead
## File a bug

* 当查询一组数据如果改类型包含一个JSON列,当该JSON列的特定属性不存在时 查询结果绑定到实体会报错 !

image

### Include your code

```C#
    public class Author
    {
        public string? UserName { get; set; }

        public string? Email { get; set; }

        public string? Address { get; set; }

    }
```

OnModelCreating :

```C#
    modelBuilder.Entity<Blog>()
        .OwnsMany(b => b.Versions, builder =>
        {
            builder.ToJson("Versions");
        })
        .OwnsMany(b => b.Comments, builder =>
        {
            builder.ToJson();
        })
        .OwnsOne(b => b.Author, bulider =>
        {
            bulider.ToJson();
        });
```

```C#

var item = await _dbContext.Blogs.FirstOrDefaultAsync(x => x.Id == 1);   //Error! 

var item2 = await _dbContext.Blogs.FirstOrDefaultAsync(x => x.Id == 2);   //Success ! 

```

### Include stack traces

Id=1 的这行数据是历史数据 插入时 JSON对象并不包含 `Address` 字段, 所以当更新实体对象后 (Author对象新增 Address 字段 ),查询这条记录抛出如下错误: 

```
  System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
     at lambda_method697(Closure, QueryContext, Object[], JsonElement)
     at lambda_method696(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
     at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
     at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
     at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
```

我认为`Address` 属性没有序列化到JSON和` {Address:null ...}` 应该是等价的 而不应该抛出异常! 

### Include provider and version information

EF Core version:  7.0.0-rc.1.22426.7
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 6.0)

### LINKED ISSUE #29225: Json: projecting nullable scalar produces debug.assert in SqlExpression ctor
SqlExpression type can't be nullable value type, JsonScalarExpression blindly passes property type down to the SqlExpression ctor which may cause the issue

### PR DESCRIPTION
**Pull request by maumar**
This is a collection of small fixes for JSON column mapping, which is a major new feature in EF7. We're bringing them together because @maumar has been out on vacation and these are fixes for the minor issues discovered while he was out. We will bring any future fixes individually.

### Descriptions

#29214 - Json column: constructor with optional enum-parameter throws ArgumentException

When producing shaper code for json nullable properties with converters we check if the converter handles null, if not we need to peek into the json value and only pass it thru converter if it's not null, and return null otherwise

#29217 - Json: nullable enums on entities mapped to json don't use enum-to-int converter, rather than string, like for non-nullable enums

In convention code unwrap nullable type when testing for enum properties that we then apply converter to string

#29225 - Json: projecting nullable scalar produces debug.assert in SqlExpression ctor

Unwrap nullable type from property before passing it as type to SqlExpression ctor

#29219 - Json: error when trying to materialize json entity with nullable property that is missing in the json string - should materialize the property as null instead

Modify ExtractJsonProperty method so that it used TryGetProperty when trying to extract nullable properties.

### Customer impact

Fixes for paper cuts in the JSON column mapping feature.

### How found

Customer reported, team testing, and writing samples.

### Regression

No; new feature in EF7.

### Testing

New testing added.

### Risk

Low-risk fixes for polishing.

Fixes #29214
Fixes #29217
Fixes #29225
Fixes #29219

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 1]
```diff
@@ -1504,21 +1504,67 @@ Expression valueExpression
...
+                if (!property.IsNullable || converter.ConvertsNulls)
                 {
-                    resultExpression = Expression.Convert(resultExpression, converter.ProviderClrType);
+                    resultExpression = Expression.Call(
+                        ExtractJsonPropertyMethodInfo,
+                        jsonElementParameter,
+                        Expression.Constant(property.GetJsonPropertyName()),
+                        Expression.Constant(providerClrType));
+
+                    if (resultExpression.Type != providerClrType)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1516]: This will be same type. Are you running in an error without this if?

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 2]
```diff
@@ -1504,21 +1504,67 @@ Expression valueExpression
...
+                    {
+                        resultExpression = Expression.Convert(resultExpression, providerClrType);
+                    }
+
+                    resultExpression = ReplacingExpressionVisitor.Replace(
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1521]: This may need to be converted to property.ClrType

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs (hunk 1 above)
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1516]: ExtractJsonProperty still returns object, so the type mismatch is here. It could go away if I made the adjustment we talked about on tuesday.

File: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs [hunk 3]
```diff
@@ -1504,21 +1504,74 @@ Expression valueExpression
...
+                    var testExpression = Expression.NotEqual(
+                        Expression.Convert(
+                            jsonPropertyVariable,
+                            providerClrType),
+                        Expression.Default(providerClrType));
+
+                    var ifTrueExpression = (Expression)jsonPropertyVariable;
+                    if (ifTrueExpression.Type != converter.ProviderClrType)
+                    {
+                        ifTrueExpression = Expression.Convert(ifTrueExpression, converter.ProviderClrType);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1553]: Move the conversion on `jsonPropertyCall` and inside assign.

Comment (maumar) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1553]: there are two different converts to 2 different types - for the test we convert to (potentially) nullable version and in the ifTrue we convert to the non-nullable. Will clean it all up once the ExtractJsonProperty has typed return type (i.e. your other PR)

Comment (smitpatel) [reply src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:1553]: ooo. Name variable different. Something like typeToRead

**Review by smitpatel — APPROVED** [review]
