### PR TITLE
[SMALL] Fix to #18565 - Throw when a query filter is configured on an owned type

### LINKED ISSUE #18565: Throw when a query filter is configured on an owned type
This can be done through the Metadata API.

### PR DESCRIPTION
**Pull request by maumar**
Added model validation rule.

Fixes #18565

### CODE REVIEW

File: src/EFCore/Infrastructure/ModelValidator.cs [hunk 1]
```diff
@@ -969,11 +969,19 @@ private bool Contains(IForeignKey inheritedFk, IForeignKey derivedFk)
...
             {
-                if (entityType.GetQueryFilter() != null
-                    && entityType.BaseType != null)
+                if (entityType.GetQueryFilter() != null)
                 {
-                    throw new InvalidOperationException(
-                        CoreStrings.BadFilterDerivedType(entityType.GetQueryFilter(), entityType.DisplayName()));
+                    if (entityType.BaseType != null)
+                    {
+                        throw new InvalidOperationException(
```
Comment (maumar) [inline src/EFCore/Infrastructure/ModelValidator.cs:976]: was thinking to combine, but the message looks a bit convoluted.

File: src/EFCore/Infrastructure/ModelValidator.cs [hunk 2]
```diff
@@ -969,11 +969,19 @@ private bool Contains(IForeignKey inheritedFk, IForeignKey derivedFk)
...
+                            CoreStrings.BadFilterDerivedType(entityType.GetQueryFilter(), entityType.DisplayName()));
+                    }
+
+                    if (entityType.IsOwned())
```
Comment (smitpatel) [inline src/EFCore/Infrastructure/ModelValidator.cs:980]: Is owned enough or we need ninja conditions here for weak entities?

Comment (AndriySvyryd) [reply src/EFCore/Infrastructure/ModelValidator.cs:980]: It's perfectly valid to declare a filter on a non-owned weak entity type.

Comment (smitpatel) [reply src/EFCore/Infrastructure/ModelValidator.cs:980]: Now I am confused about difference between owned and weak entity types. 
Since I couldn't find in issue description, can you answer following for my better understanding.
- Why is it invalid for owned entity to have query filter?
- Why is it valid for non-owned weak entity type?

Comment (AndriySvyryd) [reply src/EFCore/Infrastructure/ModelValidator.cs:980]: It's invalid for owned types because they are conceptually part of the owner and shouldn't be filtered out in most cases.
