### PR TITLE
Fixed Lazy loader performance issues

### LINKED ISSUE #35832: Lazy loader performance issues
The current implementation of LazyLoader is using AsyncLocal
the performance issue occurs when the GC collects the AsyncLocal instance created by the LazyLoader

On my tests loading a list of around 570 items takes:
674 ms with AsyncLocal
3 ms without AsyncLocal

Image

This issue is related to #35528 

Code that reproduces the issue
I didn't use BenchmarkDotNet because it takes a very, very long time to complete
and that code reproduces the bug
```
    internal class Program
    {
        static void Main()
        {
            //change the implementation of LazyLoader in TestDbContext class
            var dbContext = new TestDbContext();

            dbContext.LazyLoadEntity.ExecuteDelete();
            dbContext.SomeEntity.ExecuteDelete();

            for (int i = 0; i < 10000; i++)
            {
                dbContext.LazyLoadEntity.Add(new LazyLoadEntity
                {
                    SomeEntity = new SomeEntity
                    {
                        StringData = Random.Shared.Next().ToString()
                    }
                });
            }

            dbContext.SaveChanges();

            dbContext.Dispose();

            // Get rid of any caches
            dbContext = new TestDbContext();

            var sw = Stopwatch.StartNew();

            var list = dbContext.LazyLoadEntity.ToList();

            foreach(var item in list)
            {
                var variable = item.SomeEntity.Id;
            }

            sw.Stop();

            Console.WriteLine($"Elapsed {sw.ElapsedMilliseconds} ms");
        }
    }

    public class TestDbContext : DbContext
    {
        public TestDbContext() : base()
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(CONNECTION_STRING);
            optionsBuilder.UseLazyLoadingProxies();


            //comment/uncomment the implementation
            optionsBuilder.ReplaceService<ILazyLoader, LazyLoaderAsyncLocal>(); //current implementation
            //optionsBuilder.ReplaceService<ILazyLoader, LazyLoaderWithoutAsyncLocal>();


            base.OnConfiguring(optionsBuilder);
        }

        public DbSet<SomeEntity> SomeEntity { get; set; }
        public DbSet<LazyLoadEntity> LazyLoadEntity { get; set; }
    }

    public class LazyLoaderAsyncLocal : ILazyLoader, IInjectableService
    {
        private QueryTrackingBehavior? _queryTrackingBehavior;
        private bool _disposed;
        private bool _detached;
        private IDictionary<string, bool>? _loadedStates;
        private readonly Lock _isLoadingLock = new Lock();
        private readonly Dictionary<(object Entity, string NavigationName), (TaskCompletionSource TaskCompletionSource, AsyncLocal<int> Depth)> _isLoading = new(NavEntryEqualityComparer.Instance);
        private HashSet<string>? _nonLazyNavigations;

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public LazyLoaderAsyncLocal(
            ICurrentDbContext currentContext,
            IDiagnosticsLogger<DbLoggerCategory.Infrastructure> logger)
        {
            Context = currentContext.Context;
            Logger = logger;
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual void Injected(DbContext context, object entity, QueryTrackingBehavior? queryTrackingBehavior, ITypeBase structuralType)
        {
            _queryTrackingBehavior = queryTrackingBehavior;
            _nonLazyNavigations ??= InitNavigationsMetadata(
                structuralType as IEntityType
                ?? throw new NotImplementedException("Navigations on complex types are not supported"));
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual void SetLoaded(
            object entity,
            [CallerMemberName] string navigationName = "",
            bool loaded = true)
        {
            _loadedStates ??= new Dictionary<string, bool>();

            _loadedStates[navigationName] = loaded;
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual bool IsLoaded(object entity, string navigationName = "")
            => _loadedStates != null
                && _loadedStates.TryGetValue(navigationName, out var loaded)
                && loaded;

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        protected virtual IDiagnosticsLogger<DbLoggerCategory.Infrastructure> Logger { get; }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        protected virtual DbContext? Context { get; set; }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        // ReSharper disable once AssignNullToNotNullAttribute
        public virtual void Load(object entity, [CallerMemberName] string navigationName = "")
        {
            var navEntry = (entity, navigationName);

            bool exists;
            (TaskCompletionSource TaskCompletionSource, AsyncLocal<int> Depth) isLoadingValue;

            lock (_isLoadingLock)
            {
                ref var refIsLoadingValue = ref CollectionsMarshal.GetValueRefOrAddDefault(_isLoading, navEntry, out exists);
                if (!exists)
                {
                    refIsLoadingValue = (new(), new());
                }
                isLoadingValue = refIsLoadingValue!;
                isLoadingValue.Depth.Value++;
            }

            if (exists)
            {
                // Only waits for the outermost call on the call stack. See  #35528.
                if (isLoadingValue.Depth.Value == 1)
                {
                    isLoadingValue.TaskCompletionSource.Task.Wait();
                }
                return;
            }

            try
            {
                // ShouldLoad is called after _isLoading.Add because it could attempt to load the property. See #13138.
                if (ShouldLoad(entity, navigationName, out var entry))
                {
                    try
                    {
                        entry.Load(
                            _queryTrackingBehavior == QueryTrackingBehavior.NoTrackingWithIdentityResolution
                                ? LoadOptions.ForceIdentityResolution
                                : LoadOptions.None);
                    }
                    catch
                    {
                        entry.IsLoaded = false;
                        throw;
                    }
                }
            }
            finally
            {
                isLoadingValue.TaskCompletionSource.TrySetResult();
                lock (_isLoadingLock)
                {
                    _isLoading.Remove(navEntry);
                }
            }
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual async Task LoadAsync(
            object entity,
            CancellationToken cancellationToken = default,
            [CallerMemberName] string navigationName = "")
        {
            var navEntry = (entity, navigationName);

            bool exists;
            (TaskCompletionSource TaskCompletionSource, AsyncLocal<int> Depth) isLoadingValue;

            lock (_isLoadingLock)
            {
                ref var refIsLoadingValue = ref CollectionsMarshal.GetValueRefOrAddDefault(_isLoading, navEntry, out exists);
                if (!exists)
                {
                    refIsLoadingValue = (new(), new());
                }
                isLoadingValue = refIsLoadingValue!;
                isLoadingValue.Depth.Value++;
            }

            if (exists)
            {
                // Only waits for the outermost call on the call stack. See  #35528.
                if (isLoadingValue.Depth.Value == 1)
                {
                    await isLoadingValue.TaskCompletionSource.Task.WaitAsync(cancellationToken).ConfigureAwait(false);
                }
                return;
            }

            try
            {
                // ShouldLoad is called after _isLoading.Add because it could attempt to load the property. See #13138.
                if (ShouldLoad(entity, navigationName, out var entry))
                {
                    try
                    {
                        await entry.LoadAsync(
                                   _queryTrackingBehavior == QueryTrackingBehavior.NoTrackingWithIdentityResolution
                                       ? LoadOptions.ForceIdentityResolution
                                       : LoadOptions.None,
                                   cancellationToken).ConfigureAwait(false);
                    }
                    catch
                    {
                        entry.IsLoaded = false;
                        throw;
                    }
                }
            }
            finally
            {
                isLoadingValue.TaskCompletionSource.TrySetResult();
                lock (_isLoadingLock)
                {
                    _isLoading.Remove(navEntry);
                }
            }
        }

        private sealed class NavEntryEqualityComparer : IEqualityComparer<(object Entity, string NavigationName)>
        {
            public static readonly NavEntryEqualityComparer Instance = new();

            private NavEntryEqualityComparer()
            {
            }

            public bool Equals((object Entity, string NavigationName) x, (object Entity, string NavigationName) y)
                => ReferenceEquals(x.Entity, y.Entity)
                    && string.Equals(x.NavigationName, y.NavigationName, StringComparison.Ordinal);

            public int GetHashCode((object Entity, string NavigationName) obj)
                => HashCode.Combine(RuntimeHelpers.GetHashCode(obj.Entity), obj.NavigationName.GetHashCode());
        }

        private bool ShouldLoad(object entity, string navigationName, [NotNullWhen(true)] out NavigationEntry? navigationEntry)
        {
            if (!_detached && !IsLoaded(entity, navigationName))
            {
                if (_nonLazyNavigations == null
                    || !_nonLazyNavigations.Contains(navigationName))
                {
                    if (_disposed)
                    {
                        Logger.LazyLoadOnDisposedContextWarning(Context, entity, navigationName);
                    }
                    else if (Context!.ChangeTracker.LazyLoadingEnabled)
                    {
                        navigationEntry = Context.Entry(entity).Navigation(navigationName); // Will use local-DetectChanges, if enabled.
                        if (!navigationEntry.IsLoaded) // Check again because the nav may be loaded without the loader knowing
                        {
                            Logger.NavigationLazyLoading(Context, entity, navigationName);

                            return true;
                        }
                    }
                }
            }

            navigationEntry = null;
            return false;
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual void Dispose()
        {
            Context = null;
            _disposed = true;
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual bool Detaching(DbContext context, object entity)
        {
            _detached = true;
            Dispose();
            return false;
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual void Attaching(DbContext context, IEntityType entityType, object entity)
        {
            _disposed = false;
            _detached = false;
            Context = context;
            _nonLazyNavigations ??= InitNavigationsMetadata(entityType);
        }

        private HashSet<string> InitNavigationsMetadata(IEntityType entityType)
            => entityType!.GetNavigations()
                .Cast<INavigationBase>()
                .Concat(entityType.GetSkipNavigations())
                .Where(n => !n.LazyLoadingEnabled)
                .Select(t => t.Name)
                .ToHashSet();
    }

    public class LazyLoaderWithoutAsyncLocal : ILazyLoader, IInjectableService
    {
        private QueryTrackingBehavior? _queryTrackingBehavior;
        private bool _disposed;
        private bool _detached;
        private IDictionary<string, bool>? _loadedStates;
        private readonly Lock _isLoadingLock = new Lock();
        private readonly Dictionary<(object Entity, string NavigationName), (TaskCompletionSource TaskCompletionSource, int ThreadId)> _isLoading = new(NavEntryEqualityComparer.Instance);
        private HashSet<string>? _nonLazyNavigations;

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public LazyLoaderWithoutAsyncLocal(
            ICurrentDbContext currentContext,
            IDiagnosticsLogger<DbLoggerCategory.Infrastructure> logger)
        {
            Context = currentContext.Context;
            Logger = logger;
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual void Injected(DbContext context, object entity, QueryTrackingBehavior? queryTrackingBehavior, ITypeBase structuralType)
        {
            _queryTrackingBehavior = queryTrackingBehavior;
            _nonLazyNavigations ??= InitNavigationsMetadata(
                structuralType as IEntityType
                ?? throw new NotImplementedException("Navigations on complex types are not supported"));
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual void SetLoaded(
            object entity,
            [CallerMemberName] string navigationName = "",
            bool loaded = true)
        {
            _loadedStates ??= new Dictionary<string, bool>();

            _loadedStates[navigationName] = loaded;
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual bool IsLoaded(object entity, string navigationName = "")
            => _loadedStates != null
                && _loadedStates.TryGetValue(navigationName, out var loaded)
                && loaded;

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        protected virtual IDiagnosticsLogger<DbLoggerCategory.Infrastructure> Logger { get; }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        protected virtual DbContext? Context { get; set; }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        // ReSharper disable once AssignNullToNotNullAttribute
        public virtual void Load(object entity, [CallerMemberName] string navigationName = "")
        {
            var navEntry = (entity, navigationName);

            bool exists;
            (TaskCompletionSource TaskCompletionSource, int ThreadId) isLoadingValue;
            var threadId = Environment.CurrentManagedThreadId;

            lock (_isLoadingLock)
            {
                ref var refIsLoadingValue = ref CollectionsMarshal.GetValueRefOrAddDefault(_isLoading, navEntry, out exists);
                if (!exists)
                {
                    refIsLoadingValue = (new(), threadId);
                }
                isLoadingValue = refIsLoadingValue!;
            }

            if (exists)
            {
                // If it's the same thread it comes from a recursive ShouldLoad call, and waiting for it makes a deadlock,  See  #35528, #35832.
                if (threadId != isLoadingValue.ThreadId)
                {
                    isLoadingValue.TaskCompletionSource.Task.Wait();
                }
                return;
            }

            try
            {
                // ShouldLoad is called after _isLoading.Add because it could attempt to load the property. See #13138.
                if (ShouldLoad(entity, navigationName, out var entry))
                {
                    try
                    {
                        entry.Load(
                            _queryTrackingBehavior == QueryTrackingBehavior.NoTrackingWithIdentityResolution
                                ? LoadOptions.ForceIdentityResolution
                                : LoadOptions.None);
                    }
                    catch
                    {
                        entry.IsLoaded = false;
                        throw;
                    }
                }
            }
            finally
            {
                isLoadingValue.TaskCompletionSource.TrySetResult();
                lock (_isLoadingLock)
                {
                    _isLoading.Remove(navEntry);
                }
            }
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual async Task LoadAsync(
            object entity,
            CancellationToken cancellationToken = default,
            [CallerMemberName] string navigationName = "")
        {
            var navEntry = (entity, navigationName);

            bool exists;
            (TaskCompletionSource TaskCompletionSource, int ThreadId) isLoadingValue;

            lock (_isLoadingLock)
            {
                ref var refIsLoadingValue = ref CollectionsMarshal.GetValueRefOrAddDefault(_isLoading, navEntry, out exists);
                if (!exists)
                {
                    refIsLoadingValue = (new(), 0);
                }
                isLoadingValue = refIsLoadingValue!;
            }

            if (exists)
            {
                await isLoadingValue.TaskCompletionSource.Task.WaitAsync(cancellationToken).ConfigureAwait(false);
                return;
            }

            try
            {
                // ShouldLoad is called after _isLoading.Add because it could attempt to load the property. See #13138.
                if (ShouldLoad(entity, navigationName, out var entry))
                {
                    try
                    {
                        await entry.LoadAsync(
                                   _queryTrackingBehavior == QueryTrackingBehavior.NoTrackingWithIdentityResolution
                                       ? LoadOptions.ForceIdentityResolution
                                       : LoadOptions.None,
                                   cancellationToken).ConfigureAwait(false);
                    }
                    catch
                    {
                        entry.IsLoaded = false;
                        throw;
                    }
                }
            }
            finally
            {
                isLoadingValue.TaskCompletionSource.TrySetResult();
                lock (_isLoadingLock)
                {
                    _isLoading.Remove(navEntry);
                }
            }
        }

        private sealed class NavEntryEqualityComparer : IEqualityComparer<(object Entity, string NavigationName)>
        {
            public static readonly NavEntryEqualityComparer Instance = new();

            private NavEntryEqualityComparer()
            {
            }

            public bool Equals((object Entity, string NavigationName) x, (object Entity, string NavigationName) y)
                => ReferenceEquals(x.Entity, y.Entity)
                    && string.Equals(x.NavigationName, y.NavigationName, StringComparison.Ordinal);

            public int GetHashCode((object Entity, string NavigationName) obj)
                => HashCode.Combine(RuntimeHelpers.GetHashCode(obj.Entity), obj.NavigationName.GetHashCode());
        }

        private bool ShouldLoad(object entity, string navigationName, [NotNullWhen(true)] out NavigationEntry? navigationEntry)
        {
            if (!_detached && !IsLoaded(entity, navigationName))
            {
                if (_nonLazyNavigations == null
                    || !_nonLazyNavigations.Contains(navigationName))
                {
                    if (_disposed)
                    {
                        Logger.LazyLoadOnDisposedContextWarning(Context, entity, navigationName);
                    }
                    else if (Context!.ChangeTracker.LazyLoadingEnabled)
                    {
                        navigationEntry = Context.Entry(entity).Navigation(navigationName); // Will use local-DetectChanges, if enabled.
                        if (!navigationEntry.IsLoaded) // Check again because the nav may be loaded without the loader knowing
                        {
                            Logger.NavigationLazyLoading(Context, entity, navigationName);

                            return true;
                        }
                    }
                }
            }

            navigationEntry = null;
            return false;
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual void Dispose()
        {
            Context = null;
            _disposed = true;
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual bool Detaching(DbContext context, object entity)
        {
            _detached = true;
            Dispose();
            return false;
        }

        /// <summary>
        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
        ///     any release. You should only use it directly in your code with extreme caution and knowing that
        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
        /// </summary>
        public virtual void Attaching(DbContext context, IEntityType entityType, object entity)
        {
            _disposed = false;
            _detached = false;
            Context = context;
            _nonLazyNavigations ??= InitNavigationsMetadata(entityType);
        }

        private HashSet<string> InitNavigationsMetadata(IEntityType entityType)
            => entityType!.GetNavigations()
                .Cast<INavigationBase>()
                .Concat(entityType.GetSkipNavigations())
                .Where(n => !n.LazyLoadingEnabled)
                .Select(t => t.Name)
                .ToHashSet();
    }


    public class LazyLoadEntity
    {
        [Key]
        public int Id { get; set; }

        [ForeignKey(nameof(SomeEntity))]
        public int SomeEntityId { get; set; }

        [ForeignKey(nameof(SomeEntityId))]
        public virtual SomeEntity SomeEntity { get; set; }
    }

    public class SomeEntity
    {
        [Key]
        public int Id { get; set; }

        public string? StringData { get; set; }
    }
```

### PR DESCRIPTION
**Pull request by henriquewr**
Changed AsyncLocal to ThreadId for better performance
Fixes #35832

### CODE REVIEW

**Comment by roji** [comment]
@henriquewr I'm not very familiar with that particular part of the code, but async code is executed across different threads - every time the code awaits, it may continue executing on a different thread. So checking the thread ID is probably wrong here - the AsyncLocal is being used to propagate the state across different threads.

But I may be misunderstanding things here. @AndriySvyryd assigning this (and #35832) to you as you know the area best.

**Comment by AndriySvyryd** [comment]
I agree with @roji, for recursive lazy loading async calls the thread might change between the outer call and the nested call leading to a deadlock. If the issue is indeed caused by `AsyncLocal` allocations, consider using a static instance for the case when there's only one entry in `_isLoading`.

**Comment by henriquewr** [comment]
@AndriySvyryd 
I removed the threadId and now im using the static AsyncLocal
I didn't realize until now that I don't need to create a new AsyncLocal instance in order to get a unique value on this context

File: src/EFCore/Infrastructure/Internal/LazyLoader.cs [hunk 1]
```diff
@@ -112,25 +113,26 @@ public virtual void Load(object entity, [CallerMemberName] string navigationName
...
 
         lock (_isLoadingLock)
         {
             ref var refIsLoadingValue = ref CollectionsMarshal.GetValueRefOrAddDefault(_isLoading, navEntry, out exists);
             if (!exists)
             {
-                refIsLoadingValue = (new(), new());
+                refIsLoadingValue = new();
             }
+            s_isLoadingCallDepth.Value++;
```
Comment (AndriySvyryd) [inline src/EFCore/Infrastructure/Internal/LazyLoader.cs:125]:
```suggestion
            _isLoadingCallDepth.Value++;
```

File: src/EFCore/Infrastructure/Internal/LazyLoader.cs [hunk 2]
```diff
@@ -156,7 +158,7 @@ public virtual void Load(object entity, [CallerMemberName] string navigationName
         }
         finally
         {
-            isLoadingValue.TaskCompletionSource.TrySetResult();
+            isLoadingValue.TrySetResult();
```
Comment (AndriySvyryd) [inline src/EFCore/Infrastructure/Internal/LazyLoader.cs:161]:
```suggestion
            isLoadingValue.TrySetResult();
            s_isLoadingCallDepth.Value--;
```

**Comment by AndriySvyryd** [comment]
With this approach there still might be a deadlock issue with different lazy loaded navs trying to load the same nav in a nested call, but this use case is probably so rare that we don't need to worry about it.

**Comment by henriquewr** [comment]
@AndriySvyryd 
Instead of decrement AsyncLocal.Value I'm resetting the value to 0 when adding a new entry in the _isLoading dictionary
because I only really need the value in the first call, when the value is added
and to make sure that the state is 0 when the value is needed

**Review by AndriySvyryd — APPROVED** [review]

**Comment by stevendarby** [comment]
Came here from the release notes too

**Comment by roji** [comment]
Corrected the PR title and submitted https://github.com/dotnet/EntityFramework.Docs/pull/5054 to fix the what's new docs.
