### PR TITLE
LanguageNormalizingExpressionVisitor for VB.NET string comparisons

### LINKED ISSUE #19592: The LINQ expression 'CompareString' could not be translated VB.NET
Problem with LINQ Query, fails when compare **string**. The problem occurs only in project language VB.NET.

### Steps to reproduce

Example in VB.NET:
```
Dim DC As Sup.DAL.SupContext = New DAL.SupContext()
Dim filter As String = $"AR4888"
Dim supplierProdResults = (From pa In DC.supplierproduct Where pa.supplierID = filter Select pa).ToList()
```
**The exception:**

> System.InvalidOperationException: 'The LINQ expression 'DbSet<supplierproduct>
>     .Where(s => Operators.CompareString(
>         Left: s.supplierID, 
>         Right: __$VB$Local_filter_0, 
>         TextCompare: False) == 0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'

The same query in C# project works perfectly:
```
Sup.DAL.SupContext DC = new DAL.SupContext();
string filter = "AR4888";
var supplierProdResults = (from pa in DC.supplierproduct where pa.supplierID == filter select pa).ToList();
```

I attach a simplified project, [Download](https://1drv.ms/u/s!AnSJXzxKKqQFivAQh16FJQFgroqJiw?e=lGawiQ) that includes projects and an SQL file to create the database and 1 table with 3 rows.

**Please change connectionstring** for UseSqlServer("...") in OnConfiguring Context

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Framework 4.6.1
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.4)

### PR DESCRIPTION
**Pull request by roji**
Fixes #19592

Note that this currently contains no tests, since that would require us to at least reference Microsoft.VisualBasic.dll, which I can do (or even more extreme, create a VB project).

### CODE REVIEW

File: src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+                && visited.Arguments.Count == 3
+                && visited.Arguments[2] is ConstantExpression textCompareConstantExpression)
+            {
+                return Expression.Call(
+                    _stringCompareMethod,
+                    visited.Arguments[0],
+                    visited.Arguments[1],
+                    (bool)textCompareConstantExpression.Value
+                        ? Expression.Constant(StringComparison.OrdinalIgnoreCase)
+                        : Expression.Constant(StringComparison.Ordinal));
```
Comment (bricelam) [inline src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: Do we translate these overloads to SQL? Should `false` result in the overload without a StringComparison?

File: src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+                }
+            }
+
+            return binaryExpression.Update(visitedLeft, binaryExpression.Conversion, visitedRight);
+
+            static bool IsOrdinalStringCompare(Expression expression)
+                => expression is MethodCallExpression methodCallExpression
+                    && methodCallExpression.Method == _stringCompareMethod
+                    && methodCallExpression.Arguments[2] is ConstantExpression stringComparisonConstantExpression
+                    && (StringComparison)stringComparisonConstantExpression.Value == StringComparison.Ordinal;
```
Comment (bricelam) [inline src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: Should we rewrite OrdinalIgnoreCase to string.Equals(a1, a2, OrdinalIgnoreCase)?

**Comment by bricelam** [comment]
Part of #14572

File: src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs (hunk 1 above)
Comment (roji) [reply src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: > Do we translate these overloads to SQL?

Not at the moment, but we may at some point in the future... PG actually supports str1 > str2 :)

> Should false result in the overload without a StringComparison?

I'm not 100% sure... [string.Compare without StringComparison](https://docs.microsoft.com/en-us/dotnet/api/system.string.compare?view=netframework-4.8#System_String_Compare_System_String_System_String_) is culture-sensitive (as opposed to when passing StringComparison.Ordinal). [The docs for VB's CompareString](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.compilerservices.operators.comparestring?view=netframework-4.8#Microsoft_VisualBasic_CompilerServices_Operators_CompareString_System_String_System_String_System_Boolean_) say that the equality operator produces an expression with TextCompare=False, and if I'm reading everything correctly, the default value of [Option Compare](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/option-compare-statement?view=netframework-4.8) is binary, which is culture-insensitive. But it would be good to have another set of eyes to be sure.

File: src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs (hunk 2 above)
Comment (roji) [reply src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: Good idea, I was lazy - will do.

**Comment by roji** [comment]
Added support for string.Equals(a1, a2, OrdinalIgnoreCase), will wait for your feedback on the first question.

File: src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs (hunk 1 above)
Comment (bricelam) [reply src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: I think we've already put a stake in the ground stating that it's OK to ignore culture while querying. Just honoring the case-sensitivity of Option Compare seems sufficient. So, if using the non-StringComparison overload of StringCompare makes it translate to SQL, that sounds more ideal to me.

But I'm also happy to keep it as-is and wait for #1222.

File: src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+
+        protected override Expression VisitBinary(BinaryExpression binaryExpression)
+        {
+            var visitedLeft = Visit(binaryExpression.Left);
+            var visitedRight = Visit(binaryExpression.Right);
+
+            // In VB.NET, str1 = str2 yields CompareString(str1, str2, false) == 0.
+            // Rewrite this is as a regular equality node.
+            if (binaryExpression.NodeType == ExpressionType.Equal
+                || binaryExpression.NodeType == ExpressionType.NotEqual)
```
Comment (bricelam) [inline src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: Should we handle `>`, `>=`, `<`, and `<=` too? Or does the compiler never generate those

File: src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs (hunk 1 above)
Comment (roji) [reply src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: Makes sense, making the change.

File: src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs (hunk 3 above)
Comment (roji) [reply src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: > Or does the compiler never generate those

Not that I know of. In C#, string > string doesn't compile, and in VB.NET it compiles to `CompareString(s1, s2, false) > 0`; we do translate that above to `string.Compare(s1, s2)`, and it turns out EF Core does translate that, so we get:

```sql
SELECT [b].[Id], [b].[Name]
      FROM [Blogs] AS [b]
      WHERE CASE
          WHEN N'hello' = [b].[Name] THEN 0
          WHEN N'hello' > [b].[Name] THEN 1
          WHEN N'hello' < [b].[Name] THEN -1
      END > 0
```

(now I'll go and do a better translation of that for PG :))

Comment (roji) [reply src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: Note: opened #19733 to do better with that.

Comment (smitpatel) [reply src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: This should have converted to string.Compare in C# rather than trying to convert to equality.

Comment (roji) [reply src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: Any particular reason?

Comment (smitpatel) [reply src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: causes fragmentation in set of optimizations.

Comment (roji) [reply src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs]: I'm sure I'm just being slow or dumb, but could you take a minute and explain exactly what you mean? Fragmentation where, which set of optimizations...

**Comment by kev160967** [comment]
Should this be fixed in EF6? I am working on migrating a solution to net6 that has a VB project which contains EF queries. I'm getting the EmbeddedOperators.CompareString could not be translated error throughout the VB project, but not in the C# projects. I also note that LanguageNormalizingExpressionVisitor doesn't seem to be present in Microsoft.EntityFrameworkCore.Query.Internal in net6. I'm about to take a look at creating it locally and using it as a solution, but looking at the dates on this item and mention of net5, so a little surprised to find its still an issue?
