### PR TITLE
Rerun relationship discovery if an ambiguity has been resolved on the inverse

### LINKED ISSUE #18388: Rerun relationship discovery if an ambiguity has been resolved on the inverse
```C#
modelBuilder
    .Entity<A>()
    .HasOne(a => a.B)
    .WithOne();
```

Should be enough to configure

```C#
public class A
{
    public int Id { get; set; }
    public B B { get; set; }
}

public class B
{
    public int Id { get; set; }
    public A A1 { get; set; }
    public A A2 { get; set; }
}
```

Also run `KeyDiscoveryConvention` when a property is ignored

And remove from ambiguous inverse navigations when an entity type is removed.

### LINKED ISSUE #24521: Unexpected TempId when using EntityTypeBuilder.Ignore
After we upgraded from EF Core 3.0 to EF Core 5.0, we experience some strange behavior when using the EntityTypeBuilder.Ignore method.

Everything worked as expected when we used the following EntityTypeConfigurations with EF Core 3.0.
But a TempId shadow property is added to the generated sql query since we upgraded to EF Core 5.0.

While researching this we temporarily put the 2 configurations below in the same file.
```
public class ExternalGroupConfiguration : IEntityTypeConfiguration<ExternalGroup>
{
	public void Configure(EntityTypeBuilder<ExternalGroup> builder)
	{
		builder.HasKey(t => t.Key);
		builder.Ignore(t => t.Groups);
	}
}

public class GroupConfiguration : IEntityTypeConfiguration<Group>
{
	public void Configure(EntityTypeBuilder<Group> builder)
	{
		builder.HasKey(t => t.Key);
		builder.Ignore(t => t.ExternalGroups);
	}
}
```

What we've found is that the TempId disappears when we put the GroupConfiguration before the ExternalGroupConfiguration.

```
public class GroupConfiguration : IEntityTypeConfiguration<Group>
{
	public void Configure(EntityTypeBuilder<Group> builder)
	{
		builder.HasKey(t => t.Key);
		builder.Ignore(t => t.ExternalGroups);
	}
}

public class ExternalGroupConfiguration : IEntityTypeConfiguration<ExternalGroup>
{
	public void Configure(EntityTypeBuilder<ExternalGroup> builder)
	{
		builder.HasKey(t => t.Key);
		builder.Ignore(t => t.Groups);
	}
}
```

I've added a project to reproduce this.
[ReproduceTempId.zip](https://github.com/dotnet/efcore/files/6212036/ReproduceTempId.zip)

Sidenote: Not changing the order of the configurations, but using the [NotMapped] attribute on the ExternalGroups property in the Group class, does also get rid of the TempId.
```
public class Group
{
	public Guid Key { get; set; }

	protected Group()
	{
	}

	[NotMapped]
	public virtual IReadOnlyCollection<ExternalGroup> ExternalGroups { get; set; }
}
```

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0 (in the reproduce project, but .NET Core 3.1 in our original codebase where the problem occurrs)
Operating system: Windows 10 Pro
IDE: Visual Studio 2019 16.9.0

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Rerun KeyDiscoveryConvention when a property is ignored
Remove the associated FK when a skip navigation is removed
Add IForeignKeyNullNavigationSetConvention
Sort IEntityTypeConfiguration applied from assembly

Fixes #18388
Fixes #24521

### CODE REVIEW

File: src/EFCore/Internal/TypeFullNameComparer.cs [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+            {
+                return -1;
+            }
+
+            if (y == null)
+            {
+                return 1;
+            }
+
+            return StringComparer.Ordinal.Compare(x.Name, y.Name);
```
Comment (smitpatel) [inline src/EFCore/Internal/TypeFullNameComparer.cs:51]: should this use Name or FullName?

**Review by smitpatel — APPROVED** [review]

File: src/EFCore/Internal/TypeFullNameComparer.cs (hunk 1 above)
Comment (AndriySvyryd) [inline src/EFCore/Internal/TypeFullNameComparer.cs:51]:
```suggestion
            return StringComparer.Ordinal.Compare(x.FullName, y.FullName);
```
