### PR TITLE
[5.0.1] Use topological sort to detect identifying relationship cycles.

### LINKED ISSUE #23289: The entity type is part of a relationship cycle involving its primary key
After upgrade to EF Core 5 I got this error
'The entity type 'xxx' is part of a relationship cycle involving its primary key.'

simplified sample  composition

```C#
public class Animal
{
  public int Id {get; set;}
}

public class Pet
{
 public int Id {get; set;}
 public  Animal Animal {get; set;}
}

public class Cat
{
 public int Id {get; set;}
 public  Animal Animal {get; set;}
 public  Cat Cat {get; set;}
}

```

model configs

```C#
Animal
entity.HasKey(r => r.Id);

Pet
entity.HasKey(r => r.Id);
entity.Property(p => p.Id).ValueGeneratedNever();

entity.HasOne(b => b.Animal).WithOne().HasForeignKey<Pet>(r => r.Id).OnDelete(DeleteBehavior.Restrict);

Cat
entity.HasKey(r => r.Id);
entity.Property(p => p.Id).ValueGeneratedNever();

entity.HasOne(b => b.Animal).WithOne().HasForeignKey<Cat>(r => r.Id);
entity.HasOne(b => b.Pet).WithOne().HasForeignKey<Cat>(r => r.Id);

```

the error occurs in EFCore/Infrastructure/ModelValidator.cs
protected virtual void ValidateNoCycles

```C#

while (unvalidatedEntityTypes.Count > 0)
            {
                var rootEntityType = unvalidatedEntityTypes.First();
                reachableTypes.Clear();
                reachableTypes.Add(rootEntityType);
                typesToValidate.Enqueue(rootEntityType);

                while (typesToValidate.Count > 0)
                {
                    var entityType = typesToValidate.Dequeue();
                    var primaryKey = entityType.FindPrimaryKey();
                    if (primaryKey == null)
                    {
                        continue;
                    }

                    foreach (var foreignKey in entityType.GetForeignKeys())
                    {
                        var principalType = foreignKey.PrincipalEntityType;
                        if (!foreignKey.PrincipalKey.IsPrimaryKey()
                            || !unvalidatedEntityTypes.Contains(principalType)
                            || foreignKey.PrincipalEntityType.IsAssignableFrom(entityType)
                            || !PropertyListComparer.Instance.Equals(foreignKey.Properties, primaryKey.Properties))
                        {
                            continue;
                        }

                        if (!reachableTypes.Add(principalType))
                        {
                            throw new InvalidOperationException(CoreStrings.IdentifyingRelationshipCycle(
                                rootEntityType.DisplayName(),
                                primaryKey.Properties.Format()));
                        }

                        typesToValidate.Enqueue(principalType);
                    }
                }

                foreach (var entityType in reachableTypes)
                {
                    unvalidatedEntityTypes.Remove(entityType);
                }
            }

```

I did not understand the purpose of 
!PropertyListComparer.Instance.Equals(foreignKey.Properties, primaryKey.Properties)

on validation cat, reachableTypes contains { cat, pet , animal}
on next loop it will try to add animal because of pet => animal and this occurs => !reachableTypes.Add(principalType)

so to summarize
I can get from cat to pet and from cat to animal
also from pet to animal

just cant find the relationship cycle.

EF Core version: EF Core 5.0.0

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #23289

**Description**

EF Core 5.0 adds validation that detects identifying relationship cycles to prevent infinite recursion. However the algorithm used returned false positive for multiple paths.

**Customer Impact**

Users who have identifying relationships with multiple paths in their model are unable to use them.

**How found**

User-reported for 5.0.0

**Test coverage**

Added in this PR.

**Regression?**

Yes, the affected scenario worked correctly in 3.1

**Risk**

Low. The topological sort implementation has been in use since 1.0 and is thoroughly tested.

### CODE REVIEW

File: src/EFCore/Infrastructure/ModelValidator.cs [hunk 1]
```diff
@@ -463,50 +463,42 @@ private Type FindCandidateNavigationPropertyType(PropertyInfo propertyInfo)
...
-            while (unvalidatedEntityTypes.Count > 0)
+            var useOldBehavior = AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue23289", out var isEnabled)
+                    && isEnabled;
+            if (useOldBehavior)
             {
-                var rootEntityType = unvalidatedEntityTypes.First();
-                reachableTypes.Clear();
-                reachableTypes.Add(rootEntityType);
-                typesToValidate.Enqueue(rootEntityType);
+                return;
```
Comment (smitpatel) [inline src/EFCore/Infrastructure/ModelValidator.cs:470]: old behavior was just to return?

Comment (AndriySvyryd) [reply src/EFCore/Infrastructure/ModelValidator.cs:470]: No, but skipping validation would allow more scenarios if there are any issues with the fix

**Review by smitpatel — APPROVED** [review]

**Comment by ajcvickers** [comment]
Approved by Tactics for 5.0.1.
