### PR TITLE
Fix to #15873 - Query: Identifying columns in the case of distinct

### LINKED ISSUE #15873: Query: Identifying columns in the case of distinct

### LINKED ISSUE #20184: Improve correlated collection key matching
In some cases we can look at outer to determine if inner should start a new group.

### PR DESCRIPTION
**Pull request by maumar**
Added validation step for AddCollectionJoin which checks that if subquery contains Distinct or GroupBy, the projection contains all identifying columns needed to correctly bucket the results during materialization.
Also making sure that identifying columns can be correctly propagated during pushdown and joining - if they are not we mark them as such (by removing identifying columns altogether), so that we can throw exception when these columns are actually needed.

Fixes #15873
Fixes #20184

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -1066,36 +1065,54 @@ private ColumnExpression GenerateOuterColumn(SqlExpression projection, string al
...
             foreach (var identifier in identifiers)
             {
                 if (projectionMap.TryGetValue(identifier.Column, out var outerColumn))
                 {
                     _identifier.Add((outerColumn, identifier.Comparer));
                 }
                 else if (!IsDistinct
-                    && GroupBy.Count == 0)
+                    && GroupBy.Count == 0
+                    || (GroupBy.Count == 1
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1077]: Why count restricted to 1? If grouping by 4 different properties, we can project out the subset we need.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 2]
```diff
@@ -1066,36 +1065,54 @@ private ColumnExpression GenerateOuterColumn(SqlExpression projection, string al
...
+                        && GroupBy.Contains(identifier.Column)))
                 {
                     outerColumn = subquery.GenerateOuterColumn(identifier.Column);
                     _childIdentifiers.Add((outerColumn, identifier.Comparer));
                 }
+                else
+                {
+                    // if we can't propagate any identifier - clear them all instead
+                    // when adding collection join we detect this and throw appropriate exception
+                    _identifier.Clear();
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1113]: Should you be cleaning `_childIdentifiers` here?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 3]
```diff
@@ -2169,14 +2208,23 @@ private ProjectionBindingExpression CreateNewBinding(object binding, Type type)
                     .Remap(joinPredicate);
             }
 
-            if (joinType == JoinType.LeftJoin
-                || joinType == JoinType.OuterApply)
+            // if the subquery that is joined to can't be uniquely identified
+            // then the entire join should also not be marked as non-identifiable
+            if (innerSelectExpression._identifier.Count == 0)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2213]: Same way check for outer also. If outer does not have _identifier then we should not add from inner either.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 4]
```diff
@@ -1543,6 +1564,24 @@ static Expression RemoveConvert(Expression expression)
...
+                    || selectExpression.GroupBy.Count > 0)
+                {
+                    var innerSelectProjectionExpressions = selectExpression._projection.Select(p => p.Expression).ToList();
+                    foreach (var innerSelectIdentifier in selectExpression._identifier)
+                    {
+                        if (!innerSelectProjectionExpressions.Contains(innerSelectIdentifier.Column)
+                            && (selectExpression.GroupBy.Count == 0
+                                || !selectExpression.GroupBy.Contains(innerSelectIdentifier.Column)))
+
+                            throw new InvalidOperationException(RelationalStrings.MissingIdentifyingProjectionInDistinctGroupBySubquery(
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1580]: Inner may not contain identifier even without distinct/groupby if the inner is keyless entity.
```C#
customers.Select(c =>
new {
collection = context.Set<KeylessEntity>().Where(...).ToList()
});
```

Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1580]: it should be fine no? this code only checks that all the identifiers are already in the projection since we can't add anymore. Keyless entities are fine, and they query will only throw if u have another collection afterwards (since there will be no identifiers to add to outer when doing join)

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 2 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1113]: yup, copy paste >.<

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 4 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1578]: How will you detect that earlier collection projection did not add identifier when adding the next collection projection?

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 5]
```diff
@@ -2173,14 +2211,24 @@ private ProjectionBindingExpression CreateNewBinding(object binding, Type type)
...
 
-            if (joinType == JoinType.LeftJoin
-                || joinType == JoinType.OuterApply)
+            // if the subquery that is joined to can't be uniquely identified
+            // then the entire join should also not be marked as non-identifiable
+            if (innerSelectExpression._identifier.Count == 0
+                || _identifier.Count == 0)
             {
-                _identifier.AddRange(innerSelectExpression._identifier.Select(e => (e.Column.MakeNullable(), e.Comparer)));
+                _identifier.Clear();
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:2219]: if `_identifier.Count == 0` then you don't need to clear it. Rewrite conditions that if `_identifier.Count >0` then only you will add from inner.

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 4 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1583]: you are right, will block this scenario also

Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:1584]: This would be dead code now.

**Comment by maumar** [comment]
@smitpatel updated

File: test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs [hunk 6]
```diff
@@ -18,5 +19,9 @@ public NorthwindGroupByQuerySqliteTest(NorthwindQuerySqliteFixture<NoopModelCust
             Fixture.TestSqlLoggerFactory.Clear();
             //Fixture.TestSqlLoggerFactory.SetTestOutputHelper(testOutputHelper);
         }
+
+        // Sqlite does not support cross/outer apply
+        public override Task Select_uncorrelated_collection_with_groupby_multiple_collections_work(bool async) => null;
```
Comment (smitpatel) [inline test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs:24]: assert the outer apply error

**Comment by maumar** [comment]
@Pilchie for RC1 approval.

**Comment by Pilchie** [comment]
Approved for RC1 pending CI completion if merged before 10am Pacific on 2020-09-01.
