### PR TITLE
[release/5.0-rc2] Make newline escaping logic more robust

### LINKED ISSUE #22553: 5.0 RC1 generates invalid idempotent migration's script for SQL Server INSERT INTO statements
Exporting the idempotent migration script on RC1, using the dotnet-ef global tool, when an EntityConfiguration contains a HasData() and is using SQL Server provider, generates invalid SQL like this:

```sql
IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20200915225618_InitialCreate')
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Title') AND [object_id] = OBJECT_ID(N'[Shows]'))
        SET IDENTITY_INSERT [Shows] ON;
    EXEC(CONCAT(N'INSERT INTO [Shows] ([Id], [Title])', CHAR(13), CHAR(10), N'VALUES (1Game of Thrones'')'));
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Title') AND [object_id] = OBJECT_ID(N'[Shows]'))
        SET IDENTITY_INSERT [Shows] OFF;
END;
GO
````

### Steps to reproduce
I created a sample project reproducing the issue: https://github.com/cjaliaga/MigrationScriptIssue

Data class:
```csharp
public class Show
{
    public int Id { get; set; }
    public string Title { get; set; }
}
```
EntityConfiguration:
```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);
    modelBuilder.Entity<Show>().HasData(new Show { Id = 1, Title = "Game of Thrones" });
}
```
Generated migration: https://github.com/cjaliaga/MigrationScriptIssue/blob/master/migration.sql

Global tool output
```
dotnet-ef migrations script -i -p "MigrationScriptIssue" -o "migration.sql" --verbose
Using project 'MigrationScriptIssue\MigrationScriptIssue.csproj'.
Using startup project 'MigrationScriptIssue\MigrationScriptIssue.csproj'.
Writing 'MigrationScriptIssue\obj\MigrationScriptIssue.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=D:\Users\carlo\AppData\Local\Temp\tmp2B32.tmp /verbosity:quiet /nologo MigrationScriptIssue\MigrationScriptIssue.csproj
Writing 'MigrationScriptIssue\obj\MigrationScriptIssue.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=D:\Users\carlo\AppData\Local\Temp\tmp2DE2.tmp /verbosity:quiet /nologo MigrationScriptIssue\MigrationScriptIssue.csproj
Build started...
dotnet build MigrationScriptIssue\MigrationScriptIssue.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.20
Build succeeded.
dotnet exec --depsfile D:\Users\carlo\source\repos\MigrationScriptIssue\MigrationScriptIssue\bin\Debug\netcoreapp3.1\MigrationScriptIssue.deps.json --additionalprobingpath D:\Users\carlo\.nuget\packages --additionalprobingpath D:\Microsoft\Xamarin\NuGet --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig D:\Users\carlo\source\repos\MigrationScriptIssue\MigrationScriptIssue\bin\Debug\netcoreapp3.1\MigrationScriptIssue.runtimeconfig.json D:\Users\carlo\.dotnet\tools\.store\dotnet-ef\5.0.0-rc.1.20451.13\dotnet-ef\5.0.0-rc.1.20451.13\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations script -i -o migration.sql --assembly D:\Users\carlo\source\repos\MigrationScriptIssue\MigrationScriptIssue\bin\Debug\netcoreapp3.1\MigrationScriptIssue.dll --startup-assembly D:\Users\carlo\source\repos\MigrationScriptIssue\MigrationScriptIssue\bin\Debug\netcoreapp3.1\MigrationScriptIssue.dll --project-dir D:\Users\carlo\source\repos\MigrationScriptIssue\MigrationScriptIssue\ --language C# --working-dir D:\Users\carlo\source\repos\MigrationScriptIssue --verbose --root-namespace MigrationScriptIssue
Using assembly 'MigrationScriptIssue'.
Using startup assembly 'MigrationScriptIssue'.
Using application base 'D:\Users\carlo\source\repos\MigrationScriptIssue\MigrationScriptIssue\bin\Debug\netcoreapp3.1'.
Using working directory 'D:\Users\carlo\source\repos\MigrationScriptIssue\MigrationScriptIssue'.
Using root namespace 'MigrationScriptIssue'.
Using project directory 'D:\Users\carlo\source\repos\MigrationScriptIssue\MigrationScriptIssue\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Found DbContext 'ShowsContext'.
Finding DbContext classes in the project...
Using context 'ShowsContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'MigrationScriptIssue'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'MigrationScriptIssue'...
No design-time services were found.
Writing 'migration.sql'...
```

### Further technical details

EF Core version: 5.0.0-rc.1.20451.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows
IDE: Visual Studio 2019 16.7.3

### PR DESCRIPTION
**Pull request by bricelam**
Fixes #22553

### Description

We added some code in 5.0 to escape newlines in generated migrations. Unfortunately, this code was a little naive and missed some important cases. Several customers have hit this using RC1.

### Customer Impact

This will impact many customers, as indicated by the multiple reports we already have against RC1.

### How found

Customer reported on RC1.

### Test coverage

We were lacking test coverage for the escaping. Better test coverage is included in this PR.

### Regression?

Yes, from 3.1.

cc @Pilchie

### CODE REVIEW

File: src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs [hunk 1]
```diff
@@ -161,32 +162,138 @@ protected override void ConfigureParameter(DbParameter parameter)
...
+        {
+            var stringValue = (string)value;
+            var builder = new StringBuilder();
 
-        private static readonly char[] LineBreakChars = { '\r', '\n' };
+            var start = 0;
+            int i;
+            int length;
+            var concatenated = false;
+            var openApostrophe = false;
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs:173]: Consider using a FSM :trollface:

File: src/EFCore.Sqlite.Core/Storage/Internal/SqliteStringTypeMapping.cs [hunk 2]
```diff
@@ -55,25 +57,117 @@ protected override RelationalTypeMapping Clone(RelationalTypeMappingParameters p
         ///     doing so can result in application failures when updating to a new Entity Framework Core release.
         /// </summary>
         protected override string GenerateNonNullSqlLiteral(object value)
-            => EscapeLineBreaks(EscapeSqlLiteral((string)value));
+        {
+            var stringValue = (string)value;
```
Comment (AndriySvyryd) [inline src/EFCore.Sqlite.Core/Storage/Internal/SqliteStringTypeMapping.cs:61]: Extract method to base class, @roji will appreciate it

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore.Sqlite.Core/Storage/Internal/SqliteStringTypeMapping.cs (hunk 2 above)
Comment (bricelam) [reply src/EFCore.Sqlite.Core/Storage/Internal/SqliteStringTypeMapping.cs:61]: I thought about it, but it was too nuanced with Unicode vs ASCII and the potential for alternative escape sequences.

**Comment by bricelam** [comment]
Added one more test string after measuring code coverage of the new method. Now it's at 100% coverage.

**Comment by ajcvickers** [comment]
@bricelam Approved by Tactics.
