### PR TITLE
Change ExecuteUpdate to accept non-expression lambda

### LINKED ISSUE #32018: Accept `Action<SetPropertyCalls>` in `ExecuteUpdate`
I was expecting to find an existing issue for this but I couldn't (if there is one please let me know):
`ExecuteUpdate` currently only accepts an expression, this means you cannot dynamically build an update query, and do things like this:
```csharp
query.ExecuteUpdate(b =>
{
    if (someCondition)
        b.SetProperty(e => e.Something, "Something");
    else
        b.SetProperty(e => e.Foo, "Foo");
    b.SetProperty(e => e.Bar, "Bar")
});
```

But this would be extremely useful and is sometimes very much needed.

IIRC I believe somebody brought this up somewhere in one of the associated issues (probably in #795), but I don't remember what the response from the EF team was. It kind of seems surprising that this isn't already supported (there are [Stack Overflow questions](https://stackoverflow.com/q/75924095/7734384) about it, for example). The expressions passed to `.SetProperty()` are all that matters anyway, so it seems like the `ExecuteUpdate` parameter being an expression is unnecessary, it could've just been an `Action`, but definitely correct me if I'm wrong. Thanks.

**Update:** Found the comment that had mentioned this: https://github.com/dotnet/efcore/issues/795#issuecomment-1204547535 (see surrounding conversation) — Shay then said [this](https://github.com/dotnet/efcore/issues/795#issuecomment-1204548747):
> Ah, could be... @smitpatel will determine whether this is feasible and reasonable to implement.

I don't think there were any updates afterwards.\

### LINKED ISSUE #35361: The order of ExecuteUpdate setters is not preserved
For the following ExecuteUpdate:

```c#
await context.Posts
    .ExecuteUpdateAsync(s => s
        .SetProperty(b => b.Content, b => b.Content + " ( Title was " + b.Title  + ")")
        .SetProperty(b => b.Title, b => "New Title"));
```

... we generate the following SQL:

```sql
UPDATE [p]
SET [p].[Title] = N'New Title',
        [p].[Content] = [p].[Content] + N' ( Title was ' + [p].[Title] + N')'
FROM [Posts] AS [p]
```

Note that the SQL order of the setters is reversed; this is important, as there can be a dependency between the setters. We should preserve the original LINQ ordering.

Originally flagged in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1776

<details>
<summary>Full repro</summary>

```c#
await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

await context.Posts
    .ExecuteUpdateAsync(s => s
        .SetProperty(b => b.Content, b => b.Content + " ( Title was " + b.Title  + ")")
        .SetProperty(b => b.Title, b => "New Title"));

public class BlogContext : DbContext
{
    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0;Encrypt=false")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Post
{
    public int Id { get; set; }
    public string Content { get; set; }
    public string Title { get; set; }
}
```

</details>

### PR DESCRIPTION
**Pull request by roji**
This PR changes ExecuteUpdate to accept `Func<SetPropertyCalls<TSource>, SetPropertyCalls<TSource>>` instead of `Expression<Func<SetPropertyCalls<TSource>, SetPropertyCalls<TSource>>>`. This allows mainly for easy dynamic composition of setters (but has other advantages), and is more in-line with how LINQ operators generally work.

* ExecuteUpdate needs to add an expression node to the tree just like any other operator, so that that node can get translated properly. Previously we just got an expression tree directly as the argument, but now get a `Func`; so this `Func` must be evaluated immediately, and its results (which are a set of property/value selector pairs) integrated into the tree.
* The funcletizer must also be able to properly process the tree fragment produced by ExecuteUpdate; this means that we can't e.g. simply shove a ConstantExpression into it. Instead, we construct a NewArrayExpression representing all the tuples (the funcletizer will visit into it), and later in translation we "parse" that back into the property/value selectors, to be passed to TranslateExecuteUpdate.
* Precompilation of this new mode is tricky in various ways...
    * Before, ExecuteUpdate just got a single expression tree argument, so it was the same as all other LINQ operators; but we now have a non-expression argument, which, when evaluated, produces an expression argument. This requires special handling in precompilation, to parse the user's `SetProperty()` calls and actually evaluate them, just as the ExecuteUpdate operator implementation does for non-precompilation.
    * In effect, precompilation needs to do for ExecuteUpdate exactly what we have been doing for non-precompilation - the code just moves around.

Closes #32018
Closes #35361

### CODE REVIEW

**Comment by roji** [comment]
@ajcvickers this should be ready if you want to take a look.

**Comment by roji** [comment]
@AndriySvyryd any idea why this PR refuses to build?

**Comment by AndriySvyryd** [comment]
> @AndriySvyryd any idea why this PR refuses to build (I'm seeing this happening with other open PRs at the moment)?

Probably an AZDO outage

File: src/EFCore/Query/SetPropertyCalls.cs [hunk 1]
```diff
@@ -1,28 +1,21 @@
...
-///     </para>
-/// </summary>
-/// <remarks>
-///     See <see href="https://aka.ms/efcore-docs-providers">Implementation of database providers and extensions</see>
-///     and <see href="https://aka.ms/efcore-docs-how-query-works">How EF Core queries work</see> for more information and examples.
-/// </remarks>
-/// <typeparam name="TSource">The type of source element on which ExecuteUpdate operation is being applied.</typeparam>
-public sealed class SetPropertyCalls<TSource>
+/// <inheritdoc />
+public sealed class SetPropertyCalls<TSource> : SetPropertyCalls
```
Comment (AndriySvyryd) [inline src/EFCore/Query/SetPropertyCalls.cs:9]: Move to a separate file

**Review by AndriySvyryd — APPROVED** [review]
