### PR TITLE
Fix to #35239 - EF9: SaveChanges() is significantly slower in .NET9 vs. .NET8 when using .ToJson() Mapping vs. PostgreSQL Legacy POCO mapping

### LINKED ISSUE #35239: EF9: SaveChanges() is significantly slower in .NET9 vs. .NET8 when using .ToJson() Mapping vs. PostgreSQL Legacy POCO mapping
We use PostgreSQL and are in the process of migrating from .NET8 to .NET9 and in doing so, changing from the Legacy POCO mapping to the newer `.ToJson()` Mapping.

In the attached sample, there is no data actually being modified.  In all cases, `dbContext.ChangeTracker.HasChanges();` returns false.

**.NET8, version 8.0.11**
Legacy Poco Mapping:  0ms
.ToJson():  300ms

**.NET9, version 9.0.0**
Legacy Poco Mapping:  0ms
.ToJson():  2500ms

In both cases, `.ToJson()` takes longer; however, the difference between .NET8 and .NET9 is 10x more.

The sample references .NET9; however, can be changed to .NET8 for testing.  It also relies on Docker for Testcontainers.PostgreSql

[https://drive.google.com/file/d/1A_VoN9XgrogMEeevV7mtLh5c2s-Ds2rt/view?usp=drive_link](https://drive.google.com/file/d/1A_VoN9XgrogMEeevV7mtLh5c2s-Ds2rt/view?usp=drive_link)

### PR DESCRIPTION
**Pull request by maumar**
Problem was that as part of AOT refactoring we changed way that we build comparers. Specifically, comparers of collections - ListOfValueTypesComparer, ListOfNullableValueTypesComparer and ListOfReferenceTypesComparer. Before those list comparer Compare, Hashcode and Snapshot methods would take as argument element comparer, which was responsible for comparing elements. We need to be able to express these in code for AOT but we are not able to generate constant of type ValueComparer (or ValueComparer<TElement>) that was needed. As a solution, each comparer now stores expression describing how it can be constructed, so we use that instead (as we are perfectly capable to expressing that in code form). Problem is that now every time compare, snapshot or hashcode method is called for array type, we construct new ValueComparer for the element type. As a result in the reported case we would generate 1000s of comparers which all have to be compiled and that causes huge overhead.

Fix is to pass relevant func from the element comparer to the outer comparer. We only passed the element comparer object to the outer Compare/Hashcode/Snapshot function to call that relevant func. This way we avoid constructing redundant comparers.

Fixes #35239

### CODE REVIEW

**Comment by maumar** [comment]
note: this PR only addresses ListOfValueTypesComparer and ListOfNullableValueTypesComparer - the issue also exists for ListOfReferenceTypesComparer and in Cosmos, but those are more tricky to fix as the TElement of the parent comparer doesn't necessarily match the TElement of the element comparer, so it's not always safe to copy over lambdas from element to parent.
THe aim is to make this PR safe enough for potential servicing and as it fixes the reported case (`List<Guid>`)

File: src/EFCore/ChangeTracking/ListOfNullableValueTypesComparer.cs [hunk 1]
```diff
@@ -84,33 +83,30 @@ ValueComparer IInfrastructure<ValueComparer>.Instance
...
-                Expression.Convert(
-                    elementComparer.ConstructorExpression,
-                    typeof(ValueComparer<TElement?>))),
+                elementComparer.SnapshotExpression,
+                Expression.Constant(elementComparer.Type)),
             prm);
     }
 
-    private static bool Compare(IEnumerable<TElement?>? a, IEnumerable<TElement?>? b, ValueComparer<TElement?> elementComparer)
+    private static bool Compare(IEnumerable<TElement?>? a, IEnumerable<TElement?>? b, Func<TElement?, TElement?, bool> elementCompare, Type elementComparerType)
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/ListOfNullableValueTypesComparer.cs:109]: You don't need `elementComparerType`, just use `TElement`

File: src/EFCore/ChangeTracking/ListOfNullableValueTypesComparer.cs [hunk 2]
```diff
@@ -164,29 +160,29 @@ private static bool Compare(IEnumerable<TElement?>? a, IEnumerable<TElement?>? b
...
         {
-            hash.Add(el == null ? 0 : elementComparer.GetHashCode(el));
+            hash.Add(el == null ? 0 : elementGetHashCode(el));
         }
 
         return hash.ToHashCode();
     }
 
-    private static IList<TElement?> Snapshot(IEnumerable<TElement?> source, ValueComparer<TElement?> elementComparer)
+    private static IList<TElement?> Snapshot(IEnumerable<TElement?> source, Func<TElement?, TElement?> elementSnapshot, Type elementComparerType)
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/ListOfNullableValueTypesComparer.cs:178]: Same here

File: src/EFCore/ChangeTracking/ListOfNullableValueTypesComparer.cs (hunk 1 above)
Comment (maumar) [reply src/EFCore/ChangeTracking/ListOfNullableValueTypesComparer.cs:109]: the exception messages themselves don't make any sense to me also, but will fix them in a different PR that's not aimed for servicing

**Comment by roji** [comment]
@maumar for reference, could you include the benchmark results before and after this change, as well as the benchmark code itself?

File: src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs [hunk 3]
```diff
@@ -62,43 +71,143 @@ ValueComparer IInfrastructure<ValueComparer>.Instance
...
-        //o => GetHashCode((IEnumerable)o, elementComparer)
-        return Expression.Lambda<Func<object, int>>(
-            Expression.Call(
-                GetHashCodeMethod,
-                Expression.Convert(
-                    prm,
-                    typeof(IEnumerable)),
-                elementComparer.ConstructorExpression),
-            prm);
+        if (elementComparer is ValueComparer<TElement>)
```
Comment (roji) [inline src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs:104]: This seems like a bit of a hack, introducing a fast and slow path for when the value comparer doesn't match the type of the collection.

I understand that this PR is meant for servicing, but have you explored aligning the element and collection types instead, i.e. making sure the type on the element comparer always matches the TElement of the collection comparer? That seems like it might not be too complicated, introducing a upcast Convert node to the collection's TElement into the element converter (or possibly wrapping the element comparer in e.g. UpcastingValueComparer that would do that).

Comment (maumar) [reply src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs:104]: My current thinking was to introduce different comparer for cases where the types don't match and see what we can do there. Will experiment with the upcasting/wrapping. From what I saw most (almost all?) of these are in the nested collection cases. There is also stuff like `new object[] { 1, 2, 3 }` so the legacy path shouldn't actually be executed in a realistic scenario as these are supported in the model (none of our tests call the slow methods). So for patch I think it should be ok to fall back to the legacy path (we need to keep it anyway for quirk). 

But yeah I would like to have something better as a final fix in 10. We definitely need it when nested collection support is added. Will experiment with aligning type elements like you suggested.

Comment (roji) [reply src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs:104]: I'll just point out that we don't have any particular time pressure on this (9.0.1 has sailed anyway, not sure when the cut-off is for 9.0.2, but not any time soon I think). So we can take our time and do it right, and then see whether backporting that makes sense.

Comment (AndriySvyryd) [reply src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs:104]: My thinking was that we shouldn't support new object[] { 1, 2, 3 }  in 10 at all as that doesn't sound like a particularly useful scenario, and could be a pit of failure when the collection is built dynamically and has the potential of failing at runtime when one of the element types doesn't match. Supporting it would also complicate nested collection implementation.
But I wouldn't want to introduce a breaking change in a patch, so I think it's ok to keep it slow in 9.

Comment (roji) [reply src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs:104]: `new object[] { 1, 2, 3 }` may look useless, but some other scenarios aren't which have the same problem; for example, mixing different concrete types in a polymorphic collection (e.g. spatial types) - see https://github.com/dotnet/efcore/issues/35332#issuecomment-2543016185. I don't think there's a useless query form we can remove here (`new object[] { 1, 2, 3 } `) without also removing legitimate scenarios (e.g. `new Geometry[] { new Point(...), new Polygon(...) }`, which then gets used in the query with Contains over some column).

At the end of the day, the problem here is simply that the element comparer's type doesn't correspond to the collection comparer's; that seems like a problem that we can fix without too much trouble (and why not do that regardless of the trouble we have here - it seems cleaner), and without introducing any breaking changes.

Assuming we agree that aligning the element comparer's type the collection comparer's is the ideal solution here (no breaking change, all queries supported, no perf trouble), then I'd prefer we started with that as the solution, rather than experimenting with hacks and alternative code paths; maybe that fix is patch worthy - we won't know until we try. If it isn't, at that point we can of course do hacks for the 9.0 perf issue.

Comment (AndriySvyryd) [reply src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs:104]: I think that the current change is the lowest risk way of fixing the reported regression in 9.0.x.
@maumar will check, but I believe that the scenarios that don't fall into the "fast path" either don't work at all in 9.0.0 (not counting InMemory) or don't actually use this code.

Perhaps this should just be committed to release/9.0-staging and we can keep discussing the 10.0 implementation in https://github.com/dotnet/efcore/issues/35239

Comment (roji) [reply src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs:104]: > I think that the current change is the lowest risk way of fixing the reported regression in 9.0.x.

It might be, but I'm having a hard time understanding why we're not first looking at the correct/right fix (assuming we agree on what's correct/right here), and **then** evaluating whether it makes sense to backport that or not (and only **then** hacking around). We don't have a close deadilne coming up, so I'd at least want us to try before doing something which we agree isn't the right fix (again, assuming we agree).

Experience shows that when we introduce hacks like this, they very frequently get left in, with a backlog issue saying "look into this" that never gets handled. If we don't have any specific pressure to hack, why not try to just do it right?

Comment (AndriySvyryd) [reply src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs:104]: > It might be, but I'm having a hard time understanding why we're not first looking at the correct/right fix (assuming we agree on what's correct/right here), and then evaluating whether it makes sense to backport that or not (and only then hacking around). We don't have a close deadilne coming up, so I'd at least want us to try before doing something which we agree isn't the right fix (again, assuming we agree).

@maumar can comment on this. He tried, but there have been hurdles, that even if we can overcome the resulting fix would be riskier as the implementation would be significantly different.

The holidays are approaching so, we are closer to an effective deadline then the calendar would suggest, so I think we shouldn't delay the servicing fix that's already good enough while we try to agree on a perfect and elegant solution.

File: src/EFCore/Storage/TypeMappingSourceBase.cs [hunk 4]
```diff
@@ -150,6 +150,8 @@ protected virtual bool TryFindJsonCollectionMapping(
         {
             elementMapping ??= FindMapping(elementType);
 
+            // don't generate mapping for nested collections (i.e. where ElementTypeMapping is not null already)
+            // they are not supported and we can only get into trouble tryong to generate comparers - see #35239
```
Comment (AndriySvyryd) [inline src/EFCore/Storage/TypeMappingSourceBase.cs:154]: Is this comment still relevant?

File: src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs (hunk 3 above)
Comment (roji) [reply src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs:104]: OK. The cut-off for 9.0.2 is January 13th (that's more ~10 days after the holidays), it really seems that we have enough time to at least attempt a better solution here.

In any case, I've gone ahead and implemented what I'd consider the right solution here - a simple ConvertingValueComparer that can be composed over the element value comparer, simply applying Convert nodes and exposing it as the base type (object in this case) (see #35354)

@AndriySvyryd note that this is very similar to what you did in #33887 with [NullableValueComparer](https://github.com/dotnet/efcore/pull/33887/files#diff-41689b7edd3328f2ad2c1cf612b42d36b74116c5bfd6db821a4f00d517a6f412); in fact, the proposed ConvertingValueComparer may be able to replace NullableValueComparer altogether, handling both `Nullable<T>` and arbitrary inheritance scenarios generically (not sure).

I do think there's a version of this which could meet the bar for servicing - it really doesn't seem that big of a deal; but if you're both really against it, we can patch the hack instead. In any case, I don't see a need for the breaking change in #35332, if we can just make sure all the types align cleanly etc.

**Comment by maumar** [comment]
I've updated the pr with cleaner approach. We no longer need the legacy code path, instead we reason about compatibility between lambda signatures (expected in the list comparer method and actual that we get from element comparer). I'm ok with going with the converting comparer as well, which is more elegant and terse solution for sure. Pros of the solution here is no new APIs and a bit simpler Equals/Hashcode/Snapshot code - we don't always need to convert, e.g. when case of list of arrays (List<int[]>), outer comparer expects Equals of signature Func<int[], int[], bool> but element selector is typed as ValueComparer<IEnumerable<int>>. However in this case we can get away with just passing the `Func<IE<int>, IE<int>, bool>` into `Func<int[], int[], bool>`. Problem only appears for snapshot (can't fit `Func<IE<int>, IE<int>>` into `Func<int[], int[]>`) so we do the rewite only there.

**Comment by maumar** [comment]
perf numbers

with warmup, so that comparers are/should be compiled: 
8.0 - 77ms
9.0 - 593ms
9.0.2 -  98ms

no warmup:
8.0 - 84ms
9.0 - 650 ms
9.0.2 - 132ms

Will convert it to proper BDN and post code and more accurate numbers. But the improvement is significant.

File: src/EFCore.Cosmos/ChangeTracking/Internal/StringDictionaryComparer.cs [hunk 5]
```diff
@@ -68,33 +94,68 @@ private static Expression<Func<object, int>> GetHashCodeLambda(ValueComparer ele
     {
         var prm = Expression.Parameter(typeof(object), "o");
 
+        var expectedSignature = typeof(Func<TElement, int>);
+        var actualSignature = typeof(Func<,>).MakeGenericType(elementComparer.Type, typeof(int));
```
Comment (AndriySvyryd) [inline src/EFCore.Cosmos/ChangeTracking/Internal/StringDictionaryComparer.cs:98]: Don't use `MakeGenericType`, compare `TElement` and `elementComparer.Type` instead

File: src/EFCore/ChangeTracking/ListOfValueTypesComparer.cs [hunk 6]
```diff
@@ -81,33 +79,29 @@ private static Expression<Func<IEnumerable<TElement>, int>> GetHashCodeLambda(Va
...
+                elementComparer.HashCodeExpression),
             prm);
     }
 
     private static Expression<Func<IEnumerable<TElement>, IEnumerable<TElement>>> SnapshotLambda(ValueComparer elementComparer)
     {
         var prm = Expression.Parameter(typeof(IEnumerable<TElement>), "source");
 
-        //source => Snapshot(source, (ValueComparer<TElement>)elementComparer)
+        //source => Snapshot(source, elementComparer.SnapShot)
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/ListOfValueTypesComparer.cs:95]:
```suggestion
        //source => Snapshot(source, elementComparer.Snapshot)
```

**Comment by maumar** [comment]
BDN numbers:

8.0.11

| Method          | Mean     | Error   | StdDev  |
|---------------- |---------:|--------:|--------:|
| SaveChangesTest | 172.1 ms | 1.78 ms | 1.58 ms |


9.0

| Method          | Mean    | Error    | StdDev   |
|---------------- |--------:|---------:|---------:|
| SaveChangesTest | 5.487 s | 0.0621 s | 0.0551 s |


9.0.2

| Method          | Mean     | Error   | StdDev  |
|---------------- |---------:|--------:|--------:|
| SaveChangesTest | 179.8 ms | 1.71 ms | 1.43 ms |




benchmark code:

```
// See https://aka.ms/new-console-template for more information
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Running;
using Microsoft.EntityFrameworkCore;

BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args, DefaultConfig.Instance);

public class SaveChangesBenchmark
{
    private MyContext _ctx = new MyContext();

    [GlobalSetup]
    public virtual async Task Initialize()
    {
        var ctx = new MyContext();
        await ctx.Database.EnsureDeletedAsync();
        await ctx.Database.EnsureCreatedAsync();

        var seedData = ReturnSeedData();
        ctx.SampleEntities.AddRange(seedData);
        ctx.SaveChanges();
    }

    [IterationSetup]
    public void Setup()
    {
        _ctx = new MyContext();
        _ctx.ChangeTracker.Clear();

        foreach (var testId in Enumerable.Range(1, 200))
        {
            var src = _ctx.SampleEntities.Where(a => a.TestId == testId).FirstOrDefault();
        }
    }

    [Benchmark]
    public async Task SaveChangesTest()
    {
        await _ctx.SaveChangesAsync();
    }

    private static List<SampleEntity> ReturnSeedData()
    {
        var list = new List<SampleEntity>();

        for (int i = 0; i < 200; i++)
        {
            var s = new SampleEntity
            {
                TestId = i,
                RockId = Guid.NewGuid(),
                SccId = Guid.NewGuid(),
                AnotherId = Guid.NewGuid(),
                IsPushed = false,
                SeId = Guid.NewGuid(),
                SampleId = Guid.NewGuid(),
                Jsons = []
            };

            for (int j = 0; j < 300; j++)
            {
                var studentGradingNeed = new SampleJson
                {
                    ComponentGroupId = Guid.NewGuid(),
                    ComponentId = Guid.NewGuid(),
                    MonthId = Guid.NewGuid(),
                    IsGroupLevel = false,
                    MeasureId = Guid.NewGuid(),
                    OrderedComponentTrackingId = Guid.NewGuid(),
                    Result = new ResultJson
                    {
                        CreatedBy = Guid.NewGuid(),
                        CreatedByName = "Test",
                        CreatedDate = DateTime.UtcNow,
                        LastModifiedBy = Guid.NewGuid(),
                        LastModifiedByName = "Test",
                        LastModifiedDate = DateTime.UtcNow,
                        MarkIdValue = Guid.NewGuid(),
                        NumericValue = 44,
                        CommentIds = new List<Guid> { Guid.NewGuid() },
                        TextValue = "FF"
                    }
                };

                s.Jsons.Add(studentGradingNeed);
            }

            list.Add(s);
        }

        return list;
    }
}

public class MyContext : DbContext
{
    public DbSet<SampleEntity> SampleEntities { get; set; } = null!;

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=ReproSaveChangesBDN;Trusted_Connection=True;MultipleActiveResultSets=true");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<SampleEntity>().OwnsMany(c => c.Jsons, d =>
        {
            d.ToJson();
            d.OwnsOne(e => e.Result);
        });
    }
}


public class SampleEntity
{
    public Guid Id { get; set; }
    public Guid SampleId { get; set; }
    public Guid AnotherId { get; set; }
    public int TestId { get; set; }
    public Guid RockId { get; set; }
    public Guid SccId { get; set; }
    public Guid SeId { get; set; }

    public List<SampleJson> Jsons { get; set; } = [];
    public bool IsPushed { get; set; }
}

public record SampleJson
{

    public Guid TrackingId { get; set; }
    public Guid ComponentGroupId { get; set; }
    public Guid ComponentId { get; set; }
    public Guid? OrderedComponentTrackingId { get; set; }
    public Guid? MonthId { get; set; }
    public Guid? MeasureId { get; set; }
    public bool IsGroupLevel { get; set; }
    public ResultJson? Result { get; set; }
}

public record ResultJson
{
    public string? TextValue { get; set; }
    public decimal? NumericValue { get; set; }
    public Guid? MarkIdValue { get; set; }
    public List<Guid> CommentIds { get; set; } = [];
    public Guid CreatedBy { get; set; }
    public string CreatedByName { get; set; } = null!;
    public DateTime CreatedDate { get; set; }
    public Guid LastModifiedBy { get; set; }
    public string LastModifiedByName { get; set; } = null!;
    public DateTime LastModifiedDate { get; set; }
}

public interface ISampleDbContext
{
    DbSet<SampleEntity> SampleEntities { get; set; }
    void SetConnectionString(string connectionString);
}

```

File: src/EFCore/ChangeTracking/Internal/ConvertingValueComparer.cs [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+///     Used when a collection comparer over e.g. object[] is needed over a specific element type (e.g. int)
+/// </summary>
+/// <remarks>
+///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+///     any release. You should only use it directly in your code with extreme caution and knowing that
+///     doing so can result in application failures when updating to a new Entity Framework Core release.
+/// </remarks>
+public class ConvertingValueComparer<TTo, TFrom> : ValueComparer<TTo>, IInfrastructure<ValueComparer>
+{
```
Comment (maumar) [inline src/EFCore/ChangeTracking/Internal/ConvertingValueComparer.cs:19]: I removed the constraint as conversions happen both ways

in case of `object[] { 1, 2, 3 }` target is target is object and source is int
in case of nested lists (List<List<string>> target is List<string> and source is object (because element comparer is `ListOfReferenceTypesComparer` which is typed as ValueComparer<object>

File: src/EFCore.Cosmos/ChangeTracking/Internal/StringDictionaryComparer.cs [hunk 8]
```diff
@@ -52,14 +52,40 @@ ValueComparer IInfrastructure<ValueComparer>.Instance
         var prm1 = Expression.Parameter(typeof(object), "a");
         var prm2 = Expression.Parameter(typeof(object), "b");
 
+        // we check the compatibility of expected equals lambda signature Func<TElement, TElement, bool>
+        // vs method we actually get from the element comparer, which would be typed to its generic argument
+        // if the expected is assignable from actual we can just do simple call...
+        var expectedSignature = typeof(Func<TElement, TElement, bool>);
+        var actualSignature = typeof(Func<,,>).MakeGenericType(elementComparer.Type, elementComparer.Type, typeof(bool));
```
Comment (AndriySvyryd) [inline src/EFCore.Cosmos/ChangeTracking/Internal/StringDictionaryComparer.cs:59]: Can't you use `ComposeConversion` when creating `StringDictionaryComparer` to avoid this code as well?

File: src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs [hunk 9]
```diff
@@ -77,31 +76,29 @@ private static Expression<Func<object, int>> GetHashCodeLambda(ValueComparer ele
...
 
-        //o => GetHashCode((IEnumerable)o, elementComparer)
         return Expression.Lambda<Func<object, int>>(
             Expression.Call(
                 GetHashCodeMethod,
                 Expression.Convert(
                     prm,
                     typeof(IEnumerable)),
-                elementComparer.ConstructorExpression),
+                    elementComparer.HashCodeExpression),
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/ListOfReferenceTypesComparer.cs:85]:
```suggestion
                elementComparer.HashCodeExpression),
```

File: test/EFCore.Cosmos.FunctionalTests/Scaffolding/Baselines/Basic_cosmos_model/DataEntityType.cs [hunk 10]
```diff
@@ -212,10 +212,10 @@ public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType bas
                 relationshipIndex: -1,
                 storeGenerationIndex: -1);
             list.TypeMapping = CosmosTypeMapping.Default.Clone(
-                comparer: new ListOfReferenceTypesComparer<List<Dictionary<string, int>>, Dictionary<string, int>>(new StringDictionaryComparer<Dictionary<string, int>, int>(new ValueComparer<int>(
-                    bool (int v1, int v2) => v1 == v2,
-                    int (int v) => v,
-                    int (int v) => v))),
+                comparer: new ListOfReferenceTypesComparer<List<Dictionary<string, int>>, Dictionary<string, int>>(new ValueComparer<Dictionary<string, int>>(
```
Comment (AndriySvyryd) [inline test/EFCore.Cosmos.FunctionalTests/Scaffolding/Baselines/Basic_cosmos_model/DataEntityType.cs:215]: To fix this you'd need to modify https://github.com/dotnet/efcore/blob/a7a10ce20a24aa49d2659e2642ef6f320f6a1bc7/src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGenerator.cs#L432 to also look for a constructor that takes `ValueComparer<TFrom>`

**Review by AndriySvyryd — APPROVED** [review]
