### PR TITLE
Query: Add regression test for #23784

### LINKED ISSUE #23784: No coercion operator is defined between types 'System.DateTime' and 'System.Nullable`1[System.TimeSpan]'
# Environment
EF Core version: 5.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.9.0 Preview 2.0

# Issue
Query that should have no nullable values failing to build a query due to coercion issues. involving nullable.

# Code
Query trying to be built:
```C#
    var query = _context.MemberLocations.Include(loc => loc.Zwift).ThenInclude(zwift => zwift.MemberMonthlyStat)
        .Where(row => row.Zwift != null && row.Zwift.MemberMonthlyStat != null) // <-- Note 1.
        .Where(row => row.Latitude.HasValue && row.Longitude.HasValue);

    if (gender == "F" || gender == "M")
    {
        query = query.Where(row => row.Zwift.Gender == gender);
    }

    var finalQuery = query.Select(row => new { row.Latitude, row.Longitude, row.Zwift.Gender, row.ZwiftId, Magnitude = (row.Zwift.MemberMonthlyStat.Duration - DateTime.UnixEpoch).TotalSeconds });

    Console.WriteLine(finalQuery.ToQueryString()); // <-- exception thrown
```

Note 1: added the where clause in the hopes that the query builder would recognise that both Zwift and Zwift.MemberMonthlyStat are non-null, as guessing this might be where a nullable value is getting inferred?

`Duration` is definitely not nullable, and no fields in the SQL table for `MemberMonthlyStat` are nullable either.

# Model classes:
```C#
public partial class MemberLocation
{
    public int ZwiftId { get; set; }
    public double? Latitude { get; set; }
    public double? Longitude { get; set; }

    public virtual Member Zwift { get; set; }
}

public partial class Member
{
    public int ZwiftId { get; set; }
    public string Gender { get; set; }
    /* other fields omitted */

    public virtual MemberLocation MemberLocation { get; set; }
    public virtual MemberMonthlyStat MemberMonthlyStat { get; set; }
}

public partial class MemberMonthlyStat
{
    public int ZwiftId { get; set; }
    public int Events { get; set; }
    public double Distance { get; set; }
    public int Altitude { get; set; }
    public DateTime Duration { get; set; }
    public int Power { get; set; }

    public virtual Member Zwift { get; set; }
}
```
# Stack Trace:
```
System.InvalidOperationException: No coercion operator is defined between types 'System.DateTime' and 'System.Nullable`1[System.TimeSpan]'.
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.CreateGetValueExpression(ParameterExpression dbDataReader, Int32 index, Boolean nullable, RelationalTypeMapping typeMapping, Type type, IPropertyBase property)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression, RelationalCommandCache& relationalCommandCache, LambdaExpression& relatedDataLoaders)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(IQueryable source)
   at BoltMembership.Controllers.MembersController.LocationPointsWithMagnitude(String gender) in C:\Users\jessi\source\repos\BoltMembership\BoltMembership\Controllers\MembersController.cs:line 257
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
```

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #23784

### CODE REVIEW

**Review by maumar — APPROVED** [review]

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs [hunk 1]
```diff
@@ -1823,6 +1823,11 @@ public override Task Regex_IsMatch_MethodCall_constant_input(bool async)
             return AssertTranslationFailed(() => base.Regex_IsMatch_MethodCall_constant_input(async));
         }
 
+        public override Task Datetime_subtraction_TotalDays(bool async)
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs:1826]: do that in relational instead of individual providers?

Comment (smitpatel) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs:1826]: Depends on provider no?, npgsql can actually translate things like this using interval. cc: @roji
