### PR TITLE
Fix optimization of `CASE op WHEN`

### LINKED ISSUE #33867: Invalid optimization of `CASE op WHEN` expressions
The `SqlNullabilityProcessor` performs [invalid optimizations](https://github.com/dotnet/efcore/blob/v8.0.5/src/EFCore.Relational/Query/SqlNullabilityProcessor.cs#L573-L578) of `CASE operand WHEN` expressions.

Specifically, the `testIsCondition` flag is not properly taken into account and
```sql
CASE x
  WHEN TRUE THEN y
END
```
(and some variants) are incorrectly treated as if the operand was not specified and optimized to just `y`.

An example program that showcases the bug is:

```C#
using System;
using System.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;

using var db = new BloggingContext();

db.Database.EnsureDeleted();
db.Database.EnsureCreated();

db.Blogs
    .Select(x => db.Switch(
        x.BlogId > 20,
        false, 1,
        true, 2,
        3
    ))
    .ToList();

public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options
            .LogTo(Console.WriteLine, Microsoft.Extensions.Logging.LogLevel.Information)
            .UseSqlite($"Data Source=test.db");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasDbFunction(typeof(BloggingContext).GetMethod(nameof(Switch))!)
            .HasTranslation(args =>
                new CaseExpression(
					args[0],
					[
						new CaseWhenClause(args[1], args[2]),
						new CaseWhenClause(args[3], args[4]),
					],
					args[5])
            );
    }

    public int Switch(bool o, bool t1, int v1, bool t2, int v2, int v3)
        => throw new NotSupportedException();
}

public class Blog
{
    public int BlogId { get; set; }
}
```

### Include provider and version information

EF Core version: 8.0.6
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 8.0
Operating system: Linux (/WSL)
IDE: Visual Studio Code 1.89.1

### PR DESCRIPTION
**Pull request by ranma42**
The `CASE op WHEN ...` expression was incorrectly optimized as if it were a `CASE WHEN` expression if the test expressions contained a `TRUE` value.

This also makes it possible to use the `CASE op WHEN` expression to avoid duplicating some subexpressions in the translation of the bool to string conversion.

Fixes #33867.

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/Translators/SqlServerObjectToStringTranslator.cs [hunk 1]
```diff
@@ -82,13 +82,14 @@ public SqlServerObjectToStringTranslator(ISqlExpressionFactory sqlExpressionFact
...
                     new[]
                     {
                         new CaseWhenClause(
-                            _sqlExpressionFactory.Equal(instance, _sqlExpressionFactory.Constant(false)),
+                            _sqlExpressionFactory.Constant(false),
                             _sqlExpressionFactory.Constant(false.ToString())),
                         new CaseWhenClause(
-                            _sqlExpressionFactory.Equal(instance, _sqlExpressionFactory.Constant(true)),
+                            _sqlExpressionFactory.Constant(true),
                             _sqlExpressionFactory.Constant(true.ToString()))
```
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/Translators/SqlServerObjectToStringTranslator.cs:93]: Will let @maumar review/approve but this looks great... I remember this form of CASE/WHEN (with an operand) was introduced a bit later back in the day, I don't think we were aware of it originally; so I'm not surprised we have the less efficient other variant in various places - may be worth doing a pass over the code base for those.

[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.SqlServer/Query/Internal/Translators/SqlServerObjectToStringTranslator.cs:93]: I will do the full sweep of our code, but that can be done independently of this PR

**Review by maumar — APPROVED** [review]

**Comment by maumar** [comment]
Thanks @ranma42 - great stuff as always!

File: test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryFixtureBase.cs [hunk 2]
```diff
@@ -129,11 +129,28 @@ protected override void OnModelCreating(ModelBuilder modelBuilder, DbContext con
                 new CaseWhenClause(args[4], args[5]),
             ]))
         );
+
+        modelBuilder.HasDbFunction(
+            typeof(NullSemanticsQueryFixtureBase).GetMethod(nameof(BoolSwitch)),
+            b => b.HasTranslation(args => new CaseExpression(
+                operand: args[0],
+                [
+                    new CaseWhenClause(new SqlConstantExpression(true, typeMapping: BoolTypeMapping.Default), args[1]),
```
Comment (roji) [inline test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryFixtureBase.cs:138]: @ranma42 while bringing the PG provider up to date, this fails because BoolTypeMapping doesn't work there - its literal representation is 1/0, whereas PG has a true boolean type with TRUE/FALSE as its literals. It's no big deal - I'm overriding the definition to use NpgsqlBoolTypeMapping.

If anything, this shows the shortcomings of our current HasTranslation API; users shouldn't need to manually deal with type mappings like this, etc.

Comment (ranma42) [reply test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryFixtureBase.cs:138]: ouch, sorry; is there a simple way to make it more portable?

Comment (roji) [reply test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryFixtureBase.cs:138]: We can always expose some overridable method for providers to construct their boolean type mapping, but honestly it isn't worth it... They can just override the function definition (as I've done).
