### PR TITLE
Finish savepoints

### LINKED ISSUE #20176: Use savepoints to roll back to before SaveChanges for user-managed transactions
In the following code, trying to call `CreateMovementWithTransactionAsync` is not working as expected when trying to get the `DatabaseValue` after a failed `SaveChanges` attempt.
The steps that lead to the problem are described in the comments of the code that follows.

Inside a transaction, we read two rows from the sabe table. the Entity `FinancialAccount` has a `[ConcurrencyCheck]` property.

We do some manipulation to force `[ConcurrencyCheck]` to throw an exception (all explained in the comments).

Since `SaveChanges` threw an exception, we expect the `DatabaseValue` to be equal `OriginalValue`, and not `CurrentValue`.

Important: If the transaction is removed, everything works as expected.

### Steps to reproduce

```C#
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Threading.Tasks;
using Acme.Domain.Business;

namespace Acme.Services
{
    public class CreateMovementService : ICreateMovementService
    {
        private readonly DataContext _dataContext;

        public CreateMovementService(
            DataContext dataContext
        )
        {
            _dataContext = dataContext;
        }

        public async Task CreateMovementWithTransactionAsync()
        {
            using var transaction = _dataContext.Database.BeginTransaction(IsolationLevel.ReadUncommitted);
            //DB Value for sourceAccount is 1
            FinancialAccount sourceAccount = await _dataContext.FinancialAccount.FindAsync(1);
            //DB Value for targetAccount is also 1
            FinancialAccount targetAccount = await _dataContext.FinancialAccount.FindAsync(2);
            await CreateMovementAsync(sourceAccount, targetAccount, 1.0M);
            await transaction.CommitAsync();
        }

        public async Task CreateMovementAsync(FinancialAccount sourceAccount, FinancialAccount targetAccount, decimal amount)
        {
                try
                {
                    //CurrentBalance property has a [ConcurrencyCheck]
                    sourceAccount.CurrentBalance -= amount;
                    //With debugger paused at line 38, I access the Database and change sourceAccount value to 5
                    targetAccount.CurrentBalance += amount;
                    //As expected, trying to save will raise a DbUpdateConcurrencyException
                    await _dataContext.SaveChangesAsync();
                } catch(DbUpdateConcurrencyException)
                {
                    //Here I deal with the concurrency problem, but for explaining the bug I'm just getting values
                    var sourceEntry = _dataContext.Entry(sourceAccount);
                    var targetEntry = _dataContext.Entry(targetAccount);
                    //OK: expected to be 1
                    var originalSource = sourceEntry.OriginalValues.GetValue<decimal>("CurrentBalance");
                    //OK: expected to be 0
                    var currentSource = sourceEntry.CurrentValues.GetValue<decimal>("CurrentBalance");
                    //OK: expected to be 5
                    var databaseSource = sourceEntry.GetDatabaseValues().GetValue<decimal>("CurrentBalance");
                    //OK: expected to be 1
                    var originalTarget = targetEntry.OriginalValues.GetValue<decimal>("CurrentBalance");
                    //OK: expected to be 2
                    var currentTarget = targetEntry.CurrentValues.GetValue<decimal>("CurrentBalance");
                    //NOT OK: expected to be 1 and is actually 2 (CurrentValue)
                    var databaseTarget = targetEntry.GetDatabaseValues().GetValue<decimal>("CurrentBalance");
                }
        }
    }
}
```
### Further technical details

EF Core version: 3.1.2
Database provider: Npgsql
Target framework: 3.1.2
Operating system: Windows
IDE: VSCode

### PR DESCRIPTION
**Pull request by roji**
Finishes off the work started in #20710, see separate commits.

Closes #20176

Note that we still have the open question of whether savepoint APIs should be exposed on IDbContextTransactionManager - this is not dealt with here.

### Savepoint syntax across databases

| Database   | Save                         | Rollback                                          | Release               |
|------------|------------------------------|---------------------------------------------------|-----------------------|
| SQL Server | SAVE { TRAN \| TRANSACTION } | ROLLBACK { TRAN \| TRANSACTION }                  | N/A                   |
| SQLite     | SAVEPOINT                    | ROLLBACK [ TRANSACTION ] TO [ SAVEPOINT ]         | RELEASE [ SAVEPOINT ] |
| PostgreSQL | SAVEPOINT                    | ROLLBACK [ WORK \| TRANSACTION ] TO [ SAVEPOINT ] | RELEASE [ SAVEPOINT ] |
| MySQL      | SAVEPOINT                    | ROLLBACK [ WORK ] TO [ SAVEPOINT ]                | RELEASE SAVEPOINT     |
| Oracle     | SAVEPOINT                    | ROLLBACK [ WORK ] TO [ SAVEPOINT ]                | N/A                   |

Based on the above, this PR has the following default SQL:

* `SAVEPOINT <name>` for save
* `ROLLBACK TO <name>` for rollback
* `RELEASE SAVEPOINT <name>` for release

### CODE REVIEW

File: src/EFCore.Relational/Diagnostics/IDbTransactionInterceptor.cs [hunk 1]
```diff
@@ -320,6 +320,213 @@ public interface IDbTransactionInterceptor : IInterceptor
...
+        ///     the operation is to return the <paramref name="result" /> value passed in.
+        /// </returns>
+        Task<InterceptionResult> RollingBackToSavepointAsync(
+            [NotNull] DbTransaction transaction,
+            [NotNull] TransactionEventData eventData,
+            InterceptionResult result,
+            CancellationToken cancellationToken = default);
+
+        /// <summary>
+        ///     Called immediately after EF calls <see cref="DbTransaction.CommitAsync" />.
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Diagnostics/IDbTransactionInterceptor.cs:450]:
```suggestion
        ///     Called immediately after EF rolls back to a transaction savepoint.
```
