### PR TITLE
Fix to #28845 - JSON: add support for partial update to update just a single scalar property, rather than entire entities

### LINKED ISSUE #28845: JSON: add support for partial update to update just a single scalar property, rather than entire entities
Currently the granularity of JSON partial update is fragment representing an entity type. We should allow for individual properties to be modified (if only 1 property in the entity has been changed there is no need to update the entire entity).

This should be relatively easy - currently we use List<JsonPartialUpdatePathEntry> to reason about common update path, we would need to make this a separate structure with an optional IProperty (set if only 1 property on a given entry has been modified). We can populate the IProperty after we have created the path object in FindJsonPartialUpdateInfo, and then tweak JsonNode generation code if we detect there is a non-null IProperty value for the fragment we are supposed to generate.

I tried that initially but hit some SQL weirdness, where the json element that was being saved as a string rather than object. Just need a bit more research.

### PR DESCRIPTION
**Pull request by maumar**
Optimization for partial updates - when only one property is modified on the entity we can change it directly, rather than rewriting the JSON element for the entire entity.
To avoid string formatting issues we construct faux JSON element and insert the value that is to be the replacement, and then in the update statement we extract the value using JSON_VALUE.
In case of numeric or bool we need an additional convert statement around the value.

Fixes #28845

### CODE REVIEW

File: src/EFCore.Relational/Update/ColumnModification.cs [hunk 1]
```diff
@@ -53,6 +53,7 @@ public ColumnModification(in ColumnModificationParameters columnModificationPara
         _generateParameterName = columnModificationParameters.GenerateParameterName;
         Entry = columnModificationParameters.Entry;
         JsonPath = columnModificationParameters.JsonPath;
+        JsonScalarProperty = columnModificationParameters.JsonScalarProperty;
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Update/ColumnModification.cs:56]: Why not use Property?

File: src/EFCore.Relational/Update/ModificationCommand.cs [hunk 2]
```diff
@@ -322,22 +330,33 @@ private List<IColumnModification> GenerateColumnModifications()
 
         if (jsonEntry)
         {
-            var jsonColumnsUpdateMap = new Dictionary<string, List<JsonPartialUpdatePathEntry>>();
+            var jsonColumnsUpdateMap = new Dictionary<string, JsonPartialUpdateInfo>();
             var processedEntries = new List<IUpdateEntry>();
             foreach (var entry in _entries.Where(e => e.EntityType.IsMappedToJson()))
             {
                 var modifiedMembers = entry.ToEntityEntry().Members.Where(m => m is not NavigationEntry && m.IsModified).ToList();
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Update/ModificationCommand.cs:337]:
```suggestion
                var modifiedMembers = entry.ToEntityEntry().Properties.Where(m => m.IsModified).ToList();
```

File: src/EFCore.Relational/Update/ModificationCommand.cs [hunk 3]
```diff
@@ -251,6 +252,13 @@ public virtual IColumnModification AddColumnModification(in ColumnModificationPa
     protected virtual IColumnModification CreateColumnModification(in ColumnModificationParameters columnModificationParameters)
         => new ColumnModification(columnModificationParameters);
 
+    private sealed class JsonPartialUpdateInfo
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Update/ModificationCommand.cs:255]:
```suggestion
    private struct JsonPartialUpdateInfo
```

File: src/EFCore.Relational/Update/ModificationCommand.cs [hunk 4]
```diff
@@ -322,22 +330,33 @@ private List<IColumnModification> GenerateColumnModifications()
...
                 var modifiedMembers = entry.ToEntityEntry().Members.Where(m => m is not NavigationEntry && m.IsModified).ToList();
                 var jsonColumn = entry.EntityType.GetContainerColumnName()!;
                 var jsonPartialUpdateInfo = FindJsonPartialUpdateInfo(entry, processedEntries);
-                processedEntries.Add(entry);
 
                 if (jsonPartialUpdateInfo == null)
                 {
                     // this entry is a subtree of an entry that we already processed
                     // so we already need to update the parent - no need to have extra entry for the subtree
+                    processedEntries.Add(entry);
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Update/ModificationCommand.cs:345]: Move this to `FindJsonPartialUpdateInfo`

File: test/EFCore.Relational.Specification.Tests/Update/JsonUpdateTestBase.cs [hunk 5]
```diff
@@ -605,6 +605,425 @@ public virtual Task Edit_collection_element_and_reference_at_once()
...
+            ClearLog();
+            await context.SaveChangesAsync();
+        },
+        async context =>
+        {
+            var result = await context.Set<JsonEntityAllTypes>().SingleAsync();
+            Assert.Equal(1237775789U, result.Reference.TestUnsignedInt32);
+            Assert.Equal(1237775789U, result.Collection[0].TestUnsignedInt32);
+        });
+
```
Comment (AndriySvyryd) [inline test/EFCore.Relational.Specification.Tests/Update/JsonUpdateTestBase.cs:1004]: Add a test modifying a property and a navigation on the same entity

File: src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs [hunk 6]
```diff
@@ -152,9 +153,37 @@ public class SqlServerUpdateSqlGenerator : UpdateAndSelectSqlGenerator, ISqlServ
...
+                    || columnModification.JsonScalarProperty.ClrType == typeof(bool);
+
+                if (needsTypeConversion)
+                {
+                    stringBuilder.Append("CAST(");
+                }
+
+                stringBuilder.Append("JSON_VALUE(");
+                base.AppendUpdateColumnValue(updateSqlGeneratorHelper, columnModification, stringBuilder, name, schema);
+                stringBuilder.Append(", '$.v')");
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs:170]: This is not ideal, have you tried using an array instead, so we don't need to have magic strings?

Comment (maumar) [reply src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs:170]: I went for a smallest structure in terms of characters that we need to send over the wire. I can switch to array and access the 1st element, should work just the same

File: src/EFCore.Relational/Update/ModificationCommand.cs (hunk 3 above)
Comment (maumar) [reply src/EFCore.Relational/Update/ModificationCommand.cs:255]: I'm modifying Property and PropertyValue later and also can return null JsonPartialUpdateInfo from FindJsonPartialUpdateInfo, so I find it more convenient to keep as class. Will change to struct if you feel strongly about it tho.

File: src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs (hunk 6 above)
Comment (maumar) [reply src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs:170]: array actually saves a few characters (1 char longer on the access but 4 chars shorter on the json string itself

Comment (AndriySvyryd) [reply src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs]: Ok. And have you tried sending the naked value and using `$`?

**Review by AndriySvyryd — APPROVED** [review]
