### PR TITLE
Provide hook for SQL composability checks

### LINKED ISSUE #19224: Stop preventing composition over common table expressions
#17558 introduced a composability check in order to throw better exceptions when attempting to compose over non-select expressions. The problem is, PostgreSQL fully supports composing over common table expressions (WITH ...), even if SQL Server doesn't (see https://github.com/npgsql/efcore.pg/issues/1153).

We should probably either stop parsing SQL once and for all, or at least provide a hook for provider's to say what's composable and what isn't (if we feel the exception is valuable enough). Note also that the PostgreSQL syntax for invoking stored procedures is CALL as opposed to SQL Server's EXEC, so filtering specifically for stored procedures isn't trivial either.

We should also try to improve on cross-database awareness and testing.

### PR DESCRIPTION
**Pull request by roji**
Fixes #19224

### CODE REVIEW

File: src/EFCore.Relational/Query/QuerySqlGenerator.cs [hunk 1]
```diff
@@ -430,6 +427,20 @@ protected override Expression VisitFromSql(FromSqlExpression fromSqlExpression)
...
 
+        /// <summary>
+        /// Checks whether a given SQL string is composable, i.e. can be embedded as a subquery within a
+        /// larger SQL query.
+        /// </summary>
+        /// <param name="sql"> An SQL string to be checked for composability. </param>
+        /// <exception cref="InvalidOperationException"> The given SQL isn't composable. </exception>
+        protected virtual void CheckComposableSql([NotNull] string sql)
+        {
+            if (_composableSql.IsMatch(sql))
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/QuerySqlGenerator.cs:438]: Check.NotNull

File: src/EFCore.Relational/Query/QuerySqlGenerator.cs [hunk 2]
```diff
@@ -430,6 +427,22 @@ protected override Expression VisitFromSql(FromSqlExpression fromSqlExpression)
             return fromSqlExpression;
         }
 
+        /// <summary>
+        /// Checks whether a given SQL string is composable, i.e. can be embedded as a subquery within a
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/QuerySqlGenerator.cs:431]:
```suggestion
        ///     Checks whether a given SQL string is composable, i.e. can be embedded as a subquery within a
```

File: src/EFCore.Relational/Query/QuerySqlGenerator.cs [hunk 3]
```diff
@@ -430,6 +427,22 @@ protected override Expression VisitFromSql(FromSqlExpression fromSqlExpression)
...
+        /// larger SQL query.
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/QuerySqlGenerator.cs:432]:
```suggestion
        ///     larger SQL query.
```
