### PR TITLE
Query: Fix temporal table tests

### LINKED ISSUE #26047: Temporal tables tests are broken
I submitted a fix in #26039, but @smitpatel didn't like it.

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #26047

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/TemporalManyToManyQuerySqlServerFixture.cs [hunk 1]
```diff
@@ -188,7 +169,8 @@ protected override void OnModelCreating(ModelBuilder modelBuilder, DbContext con
                             e.CompositeId1,
                             e.CompositeId2,
                             e.CompositeId3
-                        })).ToTable(tb => tb.IsTemporal())
+                        }))
+                .ToTable(tb => tb.IsTemporal())
```
Comment (AndriySvyryd) [inline test/EFCore.SqlServer.FunctionalTests/Query/TemporalManyToManyQuerySqlServerFixture.cs:173]: `HasKey` call shouldn't be needed here or in other places

**Review by AndriySvyryd — APPROVED** [review]
