### PR TITLE
Fix to #19023 - Query: Log query plan

### LINKED ISSUE #19023: Query: Log query plan
Current output is
```
      queryContext => new QueryingEnumerable<<>f__AnonymousType1<IEnumerable<Guid>, IEnumerable<Guid>>>(
          (RelationalQueryContext)queryContext,
          RelationalCommandCache,
          null,
          null,
          Func<QueryContext, DbDataReader, ResultContext, int[], ResultCoordinator, <>f__AnonymousType1<IEnumerable<Guid>, IEnumerable<Guid>>>,
          EFSampleApp.MyContext,
          DiagnosticsLogger<Query>
      )
```

Now that we have command caching, nomore useful information on the expression directly.

### PR DESCRIPTION
**Pull request by maumar**
Making RelationalCommandCache printable and printing it's SelectExpression.
Example query plan output:

```
queryContext => new QueryingEnumerable<int>(
    (RelationalQueryContext)queryContext,
    RelationalCommandCache.SelectExpression(
        (Projection Mapping:
            EmptyProjectionMember -> 0
        SELECT ((COUNT((*))))
        FROM (Customers AS c)
        WHERE ((c.CustomerID) == (N'ALFKI')))),
    null,
    ReaderColumn[] { ReaderColumn<int>, },
    Func<QueryContext, DbDataReader, ResultContext, int[], ResultCoordinator, int>,
    TestModels.Northwind.NorthwindRelationalContext,
    DiagnosticsLogger<Query>)
    .Single()
```

Fixes #19023

### CODE REVIEW

File: src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs [hunk 1]
```diff
@@ -17,7 +17,7 @@ namespace Microsoft.EntityFrameworkCore.Query.Internal
     ///     any release. You should only use it directly in your code with extreme caution and knowing that
     ///     doing so can result in application failures when updating to a new Entity Framework Core release.
     /// </summary>
-    public class RelationalCommandCache
+    public class RelationalCommandCache : IPrintableExpression
```
Comment (maumar) [inline src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs]: This is not great (at least the name). Alternative I can think of is adding back RelationalExpressionPrinter and some custom classes to print various types of objects wrapped inside ConstantExpression. 

Adding interface to RelationalCommandCache seems like the lesser of 2 evils. Thoughts?

**Comment by maumar** [comment]
ping/thoughts?

File: src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs (hunk 1 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs]: Internal class, so doesn't matter that much
