### PR TITLE
Make SQL Server scaffolding compatible with Azure Data Explorer

### LINKED ISSUE #34833: Scaffolding against Azure Data Explorer with SQL Server emulation  doesn't work
using connection string of kusto like mention here

trying to scaffold via dotnet ef dbcontext scaffold

got this error

looks like OBJECT_SCHEMA_NAME method is not supported in kusto integration 
https://learn.microsoft.com/en-us/azure/data-explorer/sql-server-emulation-overview

and i see the fix can be by modifying SupportsSequences() by detecting kusto
fix: https://github.com/dotnet/efcore/pull/34832/files

```Microsoft.Data.SqlClient.SqlException (0x80131904): Request is invalid and cannot be processed: Semantic error: OTR0001: Scalar SQL function 'OBJECT_SCHEMA_NAME' is not supported. [line:position=2:5]
RequestId: TDS;906c6b05-c363-4ff3-9eea-0d7a2ef3fbff;10
Time: 2024-10-06T10:30:49.8561434Z
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs:line 2010
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in /_/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlInternalConnection.cs:line 770
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs:line 1421
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs:line 2637
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData() in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs:line 1142
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData() in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs:line 258
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs:line 5171
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs:line 4984      
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs:line 4663
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs:line 4544
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs:line 2043
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:906c6b05-c363-4ff3-9eea-0d7a2ef3fbff
Error Number:40000,State:1,Class:16
Request is invalid and cannot be processed: Semantic error: OTR0001: Scalar SQL function 'OBJECT_SCHEMA_NAME' is not supported. [line:position=2:5]
RequestId: TDS;906c6b05-c363-4ff3-9eea-0d7a2ef3fbff;10
Time: 2024-10-06T10:30:49.8561434Z```

### PR DESCRIPTION
**Pull request by barnuri**
Fixes #34833

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

### CODE REVIEW

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 1]
```diff
@@ -1465,6 +1475,9 @@ private bool SupportsViews()
     private bool SupportsTriggers()
         => IsFullFeaturedEngineEdition();
 
+    private bool IsKusto()
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:1478]: Is there not a more reliable wau to detect Kusto?

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 2]
```diff
@@ -76,6 +76,7 @@ private static readonly Regex PartExtractor
 
     private byte? _compatibilityLevel;
     private EngineEdition? _engineEdition;
+    private string _version;
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:79]: use "string?"

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 3]
```diff
@@ -191,6 +193,14 @@ static EngineEdition GetEngineEdition(DbConnection connection)
             return result != null ? (EngineEdition)Convert.ToInt32(result) : 0;
         }
 
+        static string GetVersion(DbConnection connection)
+        {
+            using var command = connection.CreateCommand();
+            command.CommandText = "SELECT @@VERSION;";
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:199]: What is the output of @@VERSION ?

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 1 above)
Comment (barnuri) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:1478]: didnt found something more elegant, because _compatibilityLevel is 130 and _engineEdition is 5 (detected as sql server)

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 2 above)
Comment (barnuri) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: fixed

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 3 above)
Comment (barnuri) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:199]: Microsoft SQL Kusto

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 4]
```diff
@@ -191,6 +193,14 @@ static EngineEdition GetEngineEdition(DbConnection connection)
...
+            var result = command.ExecuteScalar();
+            return result != null ? result : "";
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:201]: Maybe ensure you can build locally before submitting a PR

`(string)result` might help - and use `string.Empty` iso `""`

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 3 above)
Comment (ErikEJ) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:199]: Please share the full output of @@VERSION on Kusto

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 1 above)
Comment (ErikEJ) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:1478]: 5 is Azure SQL Database, but yes.

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 3 above)
Comment (barnuri) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:199]: this is the full output "Microsoft SQL Kusto"
{4E03D11A-6323-4A58-9259-CC57ABF26FDF}

**Comment by ErikEJ** [comment]
What are the results of

`SELECT SERVERPROPERTY('Edition')`

and

`SELECT SERVERPROPERTY('EditionId')`

**Comment by barnuri** [comment]
> SERVERPROPERTY('EditionId')

tried that too, its sql azure

{54DC3F93-BC5A-4671-8528-D9A22683DA8D}

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 3 above)
Comment (ErikEJ) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:199]: Wow! No version numbers - are you sure you see all the text in that grid?

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 1 above)
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:1478]: I would probably just extend IsFullFeaturedEngineEdition() with

&& !_version.Contains("Kusto", StringComparision.Ordinal)

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 3 above)
Comment (barnuri) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:199]: yeah :)
i screenshot what the server returned

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 5]
```diff
@@ -1464,7 +1464,7 @@ private bool SupportsMemoryOptimizedTable()
         => _compatibilityLevel >= 120 && IsFullFeaturedEngineEdition();
 
     private bool SupportsSequences()
-        => _compatibilityLevel >= 110 && IsFullFeaturedEngineEdition() && !IsKusto();
+        => _compatibilityLevel >= 110 && IsFullFeaturedEngineEdition();
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: nit: Did you leave some white space here?

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 6]
```diff
@@ -1475,11 +1475,8 @@ private bool SupportsViews()
     private bool SupportsTriggers()
         => IsFullFeaturedEngineEdition();
 
-    private bool IsKusto()
-        => _version.Contains("Kusto");
-
     private bool IsFullFeaturedEngineEdition()
-        => _engineEdition is not EngineEdition.SqlDataWarehouse and not EngineEdition.SqlOnDemand and not EngineEdition.DynamicsTdsEndpoint;
+        => _engineEdition is not EngineEdition.SqlDataWarehouse and not EngineEdition.SqlOnDemand and not EngineEdition.DynamicsTdsEndpoint && !_version.Contains("Kusto", StringComparision.Ordinal);
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: Maybe break to a new line - and I think you need to use "version?" to avoid build errors?

**Comment by ErikEJ** [comment]
@barnuri This looks valuable, I will get this added to EF Core Power Tools, including the CLI edition

**Comment by barnuri** [comment]
> @barnuri please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 6 above)
Comment (barnuri) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: change it to be a function with body looks more right, tell me if you feel otherwise

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 5 above)
Comment (barnuri) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: where ? i see no changes after i removed " && !IsKusto()"

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 6 above)
Comment (ErikEJ) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: LGTM!

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 5 above)
Comment (ErikEJ) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: Fixed now

**Comment by ErikEJ** [comment]
What tool are you using for coding this? I had a typo in my guess at spelling 😄

**Comment by barnuri** [comment]
> What tool are you using for coding this? I had a typo in my guess at spelling 😄

using this scaffold cmd
```
dotnet ef dbcontext scaffold "$env:MyConnection" `
    Microsoft.EntityFrameworkCore.SqlServer `
    --output-dir "Models" `
    --context MyDbContext `
    --context-dir DAL `
    --no-onconfiguring `
    --table myTable `
    --force

```

**Comment by barnuri** [comment]
local build passing any idea whats going on ? @ErikEJ

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 7]
```diff
@@ -1465,8 +1476,14 @@ private bool SupportsViews()
     private bool SupportsTriggers()
         => IsFullFeaturedEngineEdition();
 
-    private bool IsFullFeaturedEngineEdition()
-        => _engineEdition is not EngineEdition.SqlDataWarehouse and not EngineEdition.SqlOnDemand and not EngineEdition.DynamicsTdsEndpoint;
+    private bool IsFullFeaturedEngineEdition() 
+    {
+        if (_version != null && _version.Contains("Kusto", StringComparison.Ordinal))
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:1481]: `!string.IsNullOrEmpty(_version)`

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 8]
```diff
@@ -1,6 +1,7 @@
 // Licensed to the .NET Foundation under one or more agreements.
 // The .NET Foundation licenses this file to you under the MIT license.
 
+using System;
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:4]: Probably not needed?

**Review by ErikEJ — APPROVED** [review]
LGTM

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 9]
```diff
@@ -76,6 +77,7 @@ private static readonly Regex PartExtractor
 
     private byte? _compatibilityLevel;
     private EngineEdition? _engineEdition;
+    private string? _version;
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:80]: Maybe rename to _versionInformation?

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 10]
```diff
@@ -191,6 +194,14 @@ static EngineEdition GetEngineEdition(DbConnection connection)
             return result != null ? (EngineEdition)Convert.ToInt32(result) : 0;
         }
 
+        static string GetVersion(DbConnection connection)
```
Comment (ErikEJ) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:197]: static string? GetVersionInformation(DbConnection connection)
{
            using var command = connection.CreateCommand();
            command.CommandText = "SELECT @@VERSION;";
            var result = command.ExecuteScalar();
            return result as string;
   }

**Comment by ErikEJ** [comment]
@barnuri 

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

https://github.com/ErikEJ/EFCorePowerTools/commit/77275a5387fe378ae505f43171a14f4a882906f6

**Comment by barnuri** [comment]
> @barnuri
> 
> I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
> 
> [ErikEJ/EFCorePowerTools@77275a5](https://github.com/ErikEJ/EFCorePowerTools/commit/77275a5387fe378ae505f43171a14f4a882906f6)

how can i use it ?
there is a way to install this version to dotnet tool ? and use it as ```dotnet ef dbcontext scaffold```

**Comment by ErikEJ** [comment]
@barnuri Something similar, yes. Have a look at the readme here: https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/9.1.409-nightly

**Comment by barnuri** [comment]
> @barnuri Something similar, yes. Have a look at the readme here: https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/9.1.409-nightly

steps:
1) dotnet tool install --global ErikEJ.EFCorePowerTools.Cli --version 8.1.409-nightly
2) efcpt "$myconnectionstring" mssql

got this error now

```
Microsoft.Data.SqlClient.SqlException: Request is invalid and cannot be processed: Semantic error: OTR0001: Reference to missing column 't.object_id' [line:position=11:29]
RequestId: TDS;ffcf7bdb-9f2b-4789-b4b8-7384289d2773;11
Time: 2024-10-06T17:38:03.5688957Z
  at void Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
  at void Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
  at void Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, bool callerHasConnectionLock, bool asyncClose)
  at bool Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject    
     stateObj, out bool dataReady)
  at bool Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
  at _SqlMetaDataSet Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
  at void Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, string resetOptionsString, bool isInternal, bool forDescribeParameterEncryption,  
     bool shouldCacheForAlwaysEncrypted)
  at SqlDataReader Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, bool isAsync, int timeout, out Task task,  
     bool asyncWrite, bool inRetry, SqlDataReader ds, bool describeParameterEncryptionRequest)
  at SqlDataReader Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, TaskCompletionSource<object> completion, int  
     timeout, out Task task, out bool usedCache, bool asyncWrite, bool inRetry, string method)
  at SqlDataReader Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, string method)
  at SqlDataReader Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
  at DbDataReader Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
  at void Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.PatchedSqlServerDatabaseModelFactory.GetTables(DbConnection connection, DatabaseModel databaseModel, Func<string,       
     string, string> tableFilter, IReadOnlyDictionary<string, ValueTuple<string, string>> typeAliases, string databaseCollation) in PatchedSqlServerDatabaseModelFactory.cs:650
  at DatabaseModel Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.PatchedSqlServerDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options) in   
     PatchedSqlServerDatabaseModelFactory.cs:154
  at DatabaseModel Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.PatchedSqlServerDatabaseModelFactory.Create(string connectionString, DatabaseModelFactoryOptions options) in   
     PatchedSqlServerDatabaseModelFactory.cs:112
  at DatabaseModel RevEng.Core.TableListBuilder.GetDatabaseModel() in TableListBuilder.cs:132
  at List<TableModel> RevEng.Core.TableListBuilder.GetTableModels() in TableListBuilder.cs:43
  at void ErikEJ.EFCorePowerTools.Services.DisplayService.<>c__DisplayClass7_0`1.<Wait>b__0(StatusContext ctx) in DisplayService.cs:64
  at Task Spectre.Console.Status.<>c__DisplayClass14_0.<Start>b__0(StatusContext ctx) in Status.cs:44
  at void Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in Status.cs:79
  at void Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in Status.cs:120
  at void Spectre.Console.Progress.<>c__DisplayClass32_0`1.<<StartAsync>b__0>d.MoveNext() in Progress.cs:138
  at async Task<T> Spectre.Console.Internal.DefaultExclusivityMode.RunAsync<T>(Func<Task<T>> func) in DefaultExclusivityMode.cs:40
  at async Task<T> Spectre.Console.Progress.StartAsync<T>(Func<ProgressContext, Task<T>> action) in Progress.cs:121
  at async Task<T> Spectre.Console.Status.StartAsync<T>(string status, Func<StatusContext, Task<T>> func) in Status.cs:117
  at async Task Spectre.Console.Status.StartAsync(string status, Func<StatusContext, Task> action) in Status.cs:77
  at void Spectre.Console.Status.Start(string status, Action<StatusContext> action) in Status.cs:48
  at T ErikEJ.EFCorePowerTools.Services.DisplayService.Wait<T>(string message, Func<T> doFunc) in DisplayService.cs:59
  at List<TableModel> ErikEJ.EFCorePowerTools.HostedServices.ScaffoldHostedService.GetTablesAndViews() in ScaffoldHostedService.cs:187
  at async Task ErikEJ.EFCorePowerTools.HostedServices.ScaffoldHostedService.ExecuteAsync(CancellationToken stoppingToken) in ScaffoldHostedService.cs:43
  at async Task Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
  at async Task Microsoft.Extensions.Hosting.Internal.Host.ForeachService<T>(IEnumerable<T> services, CancellationToken token, bool concurrent, bool abortOnFirstException, List<Exception>    
     exceptions, Func<T, CancellationToken, Task> operation)
  at void Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(ref <>c__DisplayClass15_0 )
  at async Task Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
  at async Task<IHost> Microsoft.Extensions.Hosting.HostingAbstractionsHostBuilderExtensions.StartAsync(IHostBuilder hostBuilder, CancellationToken cancellationToken)
  at void ErikEJ.EFCorePowerTools.Program.<>c.<<MainAsync>b__1_1>d.MoveNext() in Program.cs:55
  at async Task<int> ErikEJ.EFCorePowerTools.Program.MainAsync(string[] args) in Program.cs:65
  at async Task<int> ErikEJ.EFCorePowerTools.Program.Main(string[] args) in Program.cs:22
```

**Comment by ErikEJ** [comment]
@barnuri Apparently some integration testing is needed! You can pull the actual queries out of the code snd run them in SSMS or similar

**Comment by barnuri** [comment]
> @barnuri Apparently some integration testing is needed! You can pull the actual queries out of the code snd run them in SSMS or similar

yeah probably but what you sent look as different code 
i wanted to see whats happened after this fix will enter to the scaffolding and continue from there

**Comment by ErikEJ** [comment]
Same code as in EF Core, with some very minor adjustments, actually

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 11]
```diff
@@ -1466,7 +1476,13 @@ private bool SupportsTriggers()
         => IsFullFeaturedEngineEdition();
 
     private bool IsFullFeaturedEngineEdition()
-        => _engineEdition is not EngineEdition.SqlDataWarehouse and not EngineEdition.SqlOnDemand and not EngineEdition.DynamicsTdsEndpoint;
+    {
+        if (_versionInformation != null && _versionInformation.Contains("Kusto", StringComparison.Ordinal))
```
Comment (roji) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:1480]: I'd rather be conservative here and match the entire string ("Microsoft SQL Kusto") rather than have a Contains() check, just to avoid possible false positives etc.

Comment (roji) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:1480]: nit: please keep this method method bodied as before rather than introducing an if.

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 12]
```diff
@@ -76,6 +76,7 @@ private static readonly Regex PartExtractor
 
     private byte? _compatibilityLevel;
     private EngineEdition? _engineEdition;
+    private string? _versionInformation;
```
Comment (roji) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs:79]: nit: rename to `_version` (that's what SQL Server calls it)

Comment (barnuri) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: done

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs (hunk 11 above)
Comment (barnuri) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: done

Comment (barnuri) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: done

**Review by roji — APPROVED** [review]
Thanks, this looks OK to me. @ErikEJ can I ask you to review and approve as well as you're particularly familiar with all this?

**Comment by barnuri** [comment]
> Thanks, this looks OK to me. @ErikEJ can I ask you to review and approve as well as you're particularly familiar with all this?

he already approved

**Comment by ErikEJ** [comment]
@roji @barnuri I am reluctant until @barnuri hase done some smoke testing, looking at the error from EF Core Power Tools above:

`Reference to missing column 't.object_id' [line:position=11:29]`

I believe you should be able to check out the latest Power Tools, and run the efpcpt.8 project, in order to get the query text, and then confirm if there are errors from running against a Kusto DB

**Review by ErikEJ — CHANGES_REQUESTED** [review]
Needs smoke testing

**Comment by barnuri** [comment]
> Needs smoke testing

looks like the inner select is not working inside this query, debugging efreveng80
```
AND NOT EXISTS (SELECT *
    FROM [sys].[extended_properties] AS [ep]
    WHERE [ep].[major_id] = [t].[object_id]
        AND [ep].[minor_id] = 0
        AND [ep].[class] = 1
        AND [ep].[name] = N'microsoft_database_tools_support'
    )
```

**Comment by ErikEJ** [comment]
@barnuri Yikes! Maybe you can rewrite to use a LEFT OUTER JOIN and a NULL check?

https://www.sqlinthewild.co.za/index.php/2010/03/23/left-outer-join-vs-not-exists/

**Comment by barnuri** [comment]
did all the fixes that need in 
https://github.com/ErikEJ/EFCorePowerTools/pull/2564

**Comment by roji** [comment]
> looks like the inner select is not working inside this query, debugging efreveng80

@barnuri if the inner select doesn't work, then this emulatio mode supports only a subset of SQL, and you're unlikely to be very successful using EF with it - EF generates SQL with similar subqueries for various queries, and that will also fail.

**Comment by ErikEJ** [comment]
@roji @barnuri Maybe we should keep these changes in Power Tools for miw and see how it goes?

**Comment by roji** [comment]
I'm not against doing tweaks in EF to accomodate Azure Data Studio, but we need a wider understanding here, i.e. how compatible is ADS really with SQL Server, how usable will it be with EF, etc. Just adding scaffolding capabilities - either to EF or to the Power Tools - doesn't make much sense if nothing is going to work after that's done.

**Comment by ErikEJ** [comment]
And it is Azure Data Explorer ( ADX)

**Comment by roji** [comment]
> Agree, but a way to find out is to enable queries against it based on a Power Tools generated DbContext - as an experimental feature..

I don't think any sort of scaffolding or Power Tools support is needed here, just in order to test what ADX supports and whether it makes sense to use EF with it... That's just something that someone needs to investigate. But of course if you want to add a feature to Power Tools sure :)

**Comment by barnuri** [comment]
> > Agree, but a way to find out is to enable queries against it based on a Power Tools generated DbContext - as an experimental feature..
> 
> I don't think any sort of scaffolding or Power Tools support is needed here, just in order to test what ADX supports and whether it makes sense to use EF with it... That's just something that someone needs to investigate. But of course if you want to add a feature to Power Tools sure :)

after adding those fixes, i got full scaffolding of my db

**Comment by roji** [comment]
@barnuri OK, but what are the actual SQL capabilities of ADX? The subquery above which you converted into a JOIN is a pretty bad sign of the SQL capabilities being very limited.

**Comment by barnuri** [comment]
> @barnuri OK, but what are the actual SQL capabilities of ADX? The subquery above which you converted into a JOIN is a pretty bad sign of the SQL capabilities being very limited.

you are right, but most of the time you dont use sub queries anyway because its had bad performance, and its support the most common simple queries that we need and always we can also make it better it adx too

**Comment by roji** [comment]
Is it only subqueries? Is there documentation anywhere saying what's supported and what isn't?

**Comment by roji** [comment]
Also note that tests seem to be failing.

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs [hunk 13]
```diff
@@ -6452,15 +6447,10 @@ SELECT 1
 IF EXISTS
     (SELECT *
      FROM [sys].[objects] o
+     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6450]: Note that this LEFT JOIN isn't exactly the same as the correlated subquery it is replacing. The previous subquery returned only e.g. tables for which **no** extended property with the name `microsoft_database_tools_support` exists. The new LEFT JOIN does return such tables, it just doesn't join with that specific extended property row.

In other words, if a table with multiple extended properties exists - one of whom is `microsoft_database_tools_support` - then the previous subquery wouldn't return that table, but the new left join would.

@ErikEJ that that sound correct? If so, then this change is probably wrong?

Comment (ErikEJ) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6450]: Well, the purpose is to execlude tables with that extended property, so agree that this changes seems wrong

Comment (barnuri) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6450]: but there is also where to check the join return null

Comment (barnuri) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6450]: This query uses a LEFT JOIN to bring in the related data from the extended_properties table, and then it filters for rows where no matching records exist in extended_properties (i.e., ep.[major_id] IS NULL ensures that there is no match in the joined table). This effectively mimics the behavior of NOT EXISTS.


also tried to use chatgpt to rewrite the query and he give me the same thing that i did
image

Comment (roji) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6450]: > and then it filters for rows where no matching records exist in extended_properties

This is not what it does.

 LEFT JOIN joins on the extended_properties rows; if there are several of these for a given object, you now have multiple rows for the same object - one per extended property that exists for that object. At that point, your WHERE clause filters out only thos rows where the extended property major_id is NULL, but leaves any other rows where it isn't. The rewriting from the subquery to LEFT JOIN is correct only if you can assume there's only one extended_property row per object at most, which clearly isn't the case here.

Comment (barnuri) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6450]: you have any suggestion how to make this query works without exists ?

Comment (barnuri) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6450]: what about doing the op way ?
```sql
IF EXISTS
    SELECT * FROM [sys].[objects] o
    INNER JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
    WHERE [o].[type] != 'U' AND [o].[is_ms_shipped] != 0
SELECT 0 ELSE SELECT 1
```

Comment (barnuri) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6450]: do the op inside the query and if exists return 0 else 1 (before it was 1 else 0)

Comment (barnuri) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6450]: @roji let me know if you thinks its ok, if yes i will fix it in the code and in the tests

Comment (roji) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6450]: @barnuri I'm not sure I understand (what op are you referring to here?), but the above SQL fragment doesn't seem to actually look at the table name... If it's integrated into an existing query, then it's still a correlated subquery, and so presumably not supported.

A way to do this would be to do a separate query for all tables which **do** have the bad extended property (using a regular inner join, and then exclude those tables client-side, in .NET code. That starts to be more of a change to the scaffolding code, just to account for this ADX SQL limitation - I'm not sure I love that idea.

Comment (barnuri) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6450]: @roji found a solution, subqueries is working without referencing query values and without using exists
this query works 
```sql
IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND [o].[object_id] NOT IN (SELECT [ep].[major_id]
        FROM [sys].[extended_properties] AS [ep]
        WHERE [ep].[minor_id] = 0
            AND [ep].[class] = 1
            AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
```

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs [hunk 14]
```diff
@@ -6202,12 +6202,11 @@ IF EXISTS
      FROM [sys].[objects] o
      WHERE [o].[type] = 'U'
      AND [o].[is_ms_shipped] = 0
-     AND NOT EXISTS (SELECT *
-         FROM [sys].[extended_properties] AS [ep]
-         WHERE [ep].[major_id] = [o].[object_id]
-             AND [ep].[minor_id] = 0
-             AND [ep].[class] = 1
-             AND [ep].[name] = N'microsoft_database_tools_support'
+     AND [o].[object_id] NOT IN (SELECT [ep].[major_id]
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6205]: Good work here @barnuri! This indeed replaces a correlated EXISTS subquery with a non-correlated IN. I'd actually accept that as an improvement regardless of the SQL limitations of ADX - we did this improvement in EF's query generation in 8.0, both because the SQL more clearly matches the intent and because it can be (dramatically) faster on some databases (but not on SQL Server).

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs (hunk 13 above)
Comment (roji) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs]: Great, see https://github.com/dotnet/efcore/pull/34832/files#r1798126585.

**Comment by roji** [comment]
@ErikEJ @barnuri after the last modifications, I'm OK with merging the PR as it is. Has the appropriate smoke testing been done, @ErikEJ are you OK with this as well?

**Comment by ErikEJ** [comment]
Let me do a little smoke testing on the Power Tools PR that resembles this

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs (hunk 14 above)
Comment (barnuri) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs:6205]: thanks :)
and thanks for the collaboration 💪🏾

**Comment by ErikEJ** [comment]
@roji @barnuri I have done some smoke testing with the EF Core Power Tools daily build, and everything works as expected.

I like the minimal footprint this PR has. 

🐑 🇮🇹

**Review by roji — APPROVED** [review]

**Comment by roji** [comment]
Merged for 10, thanks for your contribution @barnuri!
