### PR TITLE
Additional refactoring of Null Semantics

### LINKED ISSUE #11464: Query: Nullsemantics are not applied to NOT IN (...)
Test Accessing_optional_property_inside_result_operator_subquery
```
            var names = new[] { "Name1", "Name2" };
            AssertQuery<Level1>(
                l1s => l1s.Where(l1 => names.All(n => l1.OneToOne_Optional_FK.Name != n)),
                l1s => l1s.Where(l1 => names.All(n => Maybe(l1.OneToOne_Optional_FK, () => l1.OneToOne_Optional_FK.Name) != n)));
```
Generated SQL
```SQL
  SELECT [l1].[Id], [l1].[Date], [l1].[Name], [l1].[OneToMany_Optional_Self_InverseId], [l1].[OneToMany_Required_Self_InverseId], [l1].[OneToOne_Optional_SelfId]
  FROM [LevelOne] AS [l1]
  LEFT JOIN [LevelTwo] AS [l1.OneToOne_Optional_FK] ON [l1].[Id] = [l1.OneToOne_Optional_FK].[Level1_Optional_Id]
  WHERE [l1.OneToOne_Optional_FK].[Name] NOT IN (N'Name1', N'Name2')
```
But `[l1.OneToOne_Optional_FK].[Name]` is nullable so we need to append OR `[l1.OneToOne_Optional_FK].[Name] IS NULL`

### LINKED ISSUE #15722: QueryRewrite: remove redundant null semantics terms involving non-null parameters once we know parameter values
Currently when performing null semantics rewrite we assume all parameters are nullable. This is because at that point we don't have the parameter values. 

We should run optimizations after the values are known and simplify fragments like `@prm IS NULL`, `@prm IS NOT NULL` once we know if the parameters are actually null or not.

### LINKED ISSUE #18338: Changing query from == false to ! results in differing queries
Given the following model

```cs
public class Foo
{
    public int Id { get; set; }
    public string Address { get; set; }
    public string Postcode { get; set; }
    public bool Deleted { get; set; }
    public bool NeedsUpdating { get; set; }
}
```

Address and postcode are both optional/nullable.

When writing a query to pull all Foos where `NeedsUpdating` is `true` and the address or postcode are not null, changing `== false` to `!` results in a different query.

I am unsure if this is a bug, a language quirk or something I am missing.

Queries:
```cs
 var foo = await _db.Foos
.Where(c => c.Deleted == false)
.Where(c => c.NeedsUpdating)
.Where(x => string.IsNullOrEmpty(x.Postcode) == false || string.IsNullOrEmpty(x.Address) == false)
 .AnyAsync();
```
results in the following SQL query:
```sql
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Foos] AS [c]
        WHERE (([c].[Deleted] = CAST(0 AS bit)) AND ([c].[NeedsUpdating] = CAST(1 AS bit))) AND ((([c].[Postcode] IS NULL OR (([c].[Postcode] = N'') AND [c].[Postcode] IS NOT NULL)) AND (CAST(0 AS bit) = CAST(1 AS bit))) OR (([c].[Address] IS NULL OR (([c].[Address] = N'') AND [c].[Address] IS NOT NULL)) AND (CAST(0 AS bit) = CAST(1 AS bit))))) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
```
this does not yield the correct SQL query.

However, when changing `== false` to `!`, it works:
```cs
 var foo = await _db.Foos
.Where(c => c.Deleted == false)
.Where(c => c.NeedsUpdating)
.Where(x => !string.IsNullOrEmpty(x.Postcode) || !string.IsNullOrEmpty(x.Address))
 .AnyAsync();
```
results in the following SQL query:
```sql
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Foos] AS [c]
        WHERE (([c].[Deleted] = CAST(0 AS bit)) AND ([c].[NeedsUpdating] = CAST(1 AS bit))) AND (([c].[Postcode] IS NOT NULL AND (([c].[Postcode] <> N'') OR [c].[Postcode] IS NULL)) OR ([c].[Address] IS NOT NULL AND (([c].[Address] <> N'') OR [c].[Address] IS NULL)))) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
```

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: ASP.NET Core 3.0 (sdk 3.0.100)
Operating system: Windows 10 Pro 1903
IDE: Visual Studio 2019 16.3

### LINKED ISSUE #18597: Query: add optimization where non-nullable expression is compared to true/false
We used to optimize the following:

```
op(a, b) == true -> op(a, b)
op(a, b) != false -> op(a, b)
op(a, b) == false -> !op(a, b)
op(a, b) != true -> !op(a, b)
```

We were able to do that, because null semantics rewrite would prune all nulls. This is no longer safe with "simple" null semantics rewrite, which doesnt distinguish between false and null.

We can do it by:
- adding optimization to null semantics directly (we will miss optimizations done in query optimizer later)
- add null detection logic to sql expression optimizer (i.e. duplicate some of the null semantics code)
- merge null semantics with sql optimizer (too complex?),
- add IsNullable property to SqlExpression, so optimizer can just read the value and know what to do (extra API + metadata in SqlExpression, potential problems with extensibility?)

### LINKED ISSUE #18689: Query: make null semantics optimizations provider-specific
There are some null semantics optimizations we can do on SQL Server but not on other providers. We should consider making NullSemanticsRewritingExpressionVisitor provider specific.

example query:

```cs
ctx.Set<Weapon>().Select(
w => new
{
    w.Id,
    IsCartridge = !w.IsAutomatic && w.SynergyWithId == 1
})
```

null semantics rewriting visitor when initially encounters this expression determines that it cant do optimized translation, since its in the projection,
so we get:

```cs
!w.IsAutomatic && w.SynergyWithId == 1 && w.SynergyWithId != null
```

however, later on those conditions get converted to CASE blocks, in which optimized translation would be allowed. 

If null semantics would be a provider specific, it could always assume it can optimize conditions in projection (and maybe other places?), since search condition visitor will convert them all to CASE blocks.

Another optimization:

```cs
ctx.NullSemanticsEntity1.Where(e => e.NullableBoolA == e.BoolB == (e.IntA == e.NullableIntB)));
```

on sql server we can apply optimized translation to the child comparisons, because they get converted to CASE blocks, on other providers we can't.

### LINKED ISSUE #19019: Parameter based optimization tries to order by constant
### Steps to reproduce

What steps can we follow to reproduce the issue?

We ❤ code! Include a complete code listing or attach a simplified project

``` C#
        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task OrderBy_StartsWith_with_null_parameter_as_argument(bool async)
        {
            var prm = (string)null;

            return AssertQuery(
                async,
                ss => ss.Set<Gear>().OrderBy(g => g.FullName.StartsWith(prm)).ThenBy(g => g.Nickname),
                ss => ss.Set<Gear>().OrderBy(g => false).ThenBy(g => g.Nickname),
                assertOrder: true);
        }
```

Got Exceptions? Include both the message and the stack trace
```
 Message: 
    Microsoft.Data.SqlClient.SqlException : A constant expression was encountered in the ORDER BY list, position 1.
  Stack Trace: 
    SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    SqlDataReader.TryConsumeMetaData()
    SqlDataReader.get_MetaData()
    SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
    SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
    SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
    SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
    SqlCommand.ExecuteReader(CommandBehavior behavior)
    SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
    DbCommand.ExecuteReader()
    RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject) line 404
    Enumerator.InitializeReader(DbContext _, Boolean result) line 176
    ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state) line 173
    ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) line 159
    Enumerator.MoveNext() line 125
    LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
    EnumerableHelpers.ToArray[T](IEnumerable`1 source)
    Enumerable.ToArray[TSource](IEnumerable`1 source)
    QueryAsserter`1.AssertQuery[TResult](Func`2 actualQuery, Func`2 expectedQuery, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount, Boolean async, String testMethodName) line 87
    GearsOfWarQuerySqlServerTest.OrderBy_StartsWith_with_null_parameter_as_argument(Boolean async) line 7095
    --- End of stack trace from previous location ---

```

### Further technical details

EF Core version: master
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

### PR DESCRIPTION
**Pull request by maumar**
- moving NullSemantics visitor after 2nd level cache - we need to know the parameter values to properly handle IN expressions wrt null semantics,
- NullSemantics visitor needs to go before SqlExpressionOptimizer and SearchCondition, so those two are also moved after 2nd level cache,
- moving optimizations that depend on knowing the nullability to NullSemantics visitor - optimizer now only contains optimizations that also work in 3-value logic, or when we know nulls can't happen,
- merging InExpressionValuesExpandingExpressionVisitor int NullSemantics visitor, so that we don't apply the rewrite for UseRelationalNulls,
- preventing NulSemantics from performing double visitation when computing non-nullable columns.

Resolves #11464
Resolves #15722
Resolves #18338
Resolves #18597
Resolves #18689
Resolves #19019

### CODE REVIEW

**Comment by maumar** [comment]
@roji

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 1]
```diff
@@ -148,7 +148,11 @@ protected virtual Expression VisitSqlUnaryExpression(SqlUnaryExpression sqlUnary
 
                             break;
 
-                        case SqlBinaryExpression binaryOperand:
+                        // these optimizations are only valid in 2-value logic
+                        // NullSemantics removes all nulls from expressions wrapped around Not
+                        // so the optimizations are safe to do as long as UseRelationalNulls = false
+                        case SqlBinaryExpression binaryOperand
+                            when !_useRelationalNulls:
```
Comment (maumar) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: shall we do those optimizations always (i.e. even when relational nulls == true)? We do that currently which is technically wrong, but perhaps for relational nulls all bets are off

File: src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs [hunk 2]
```diff
@@ -38,17 +38,19 @@ public class RelationalParameterBasedQueryTranslationPostprocessor
...
-                Dependencies.SqlExpressionFactory, parametersValues).Visit(selectExpression);
-
-            if (!ReferenceEquals(selectExpression, inExpressionOptimized))
+            var nullSemanticsOptimized = nullSemanticsRewritingExpressionVisitor.Visit(selectExpression);
+            if (!nullSemanticsRewritingExpressionVisitor.CanCache)
             {
                 canCache = false;
             }
 
             var nullParametersOptimized = new ParameterNullabilityBasedSqlExpressionOptimizingExpressionVisitor(
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs]: ParameterNullabilityBasedSqlExpressionOptimizingExpressionVisitor - name of that visitor is a bit redundant now, since it always knows the parameter values. Are we ok with breaking providers and fixing the names?

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs [hunk 3]
```diff
@@ -343,7 +343,7 @@ public override async Task Default_if_empty_top_level(bool async)
     SELECT [e].[EmployeeID], [e].[City], [e].[Country], [e].[FirstName], [e].[ReportsTo], [e].[Title]
     FROM [Employees] AS [e]
     WHERE [e].[EmployeeID] = -1
-) AS [t] ON 1 = 1");
+) AS [t] ON CAST(1 AS bit) = CAST(1 AS bit)");
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs]: for sql server, should we optimize `CAST(1 AS bit) = CAST(1 AS bit)` to `1 = 1` and `CAST(0 AS bit) = CAST(1 AS bit)` to `0 = 1` everywhere?

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 4]
```diff
@@ -111,56 +123,163 @@ protected override Expression VisitIn(InExpression inExpression)
...
-            return intersectExpression.Update(source1, source2);
+            var inValues = new List<object>();
+            var hasNullValue = false;
+            RelationalTypeMapping typeMapping = null;
+
+            switch (valuesExpression)
+            {
+                case SqlConstantExpression sqlConstant:
+                {
+                    CanCache = false;
```
Comment (maumar) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: disable caching when dealing with constant array, or just parameter?

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 5]
```diff
@@ -370,169 +510,309 @@ protected override Expression VisitSqlBinary(SqlBinaryExpression sqlBinaryExpres
...
-                        _isNullable = true;
-                        _canOptimize = canOptimize;
+                    return boolConstant;
+                }
 
-                        return _sqlExpressionFactory.OrElse(
-                            _sqlExpressionFactory.Equal(newLeft, newRight),
-                            _sqlExpressionFactory.AndAlso(leftIsNull, rightIsNull));
-                    }
+                // TODO: should we do this for parameters also?
```
Comment (maumar) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: if we do, we will prune some of the parameters, converting them to constants effectively. It shouldn't explode our cache since its only for bool values, so perhaps it's worth doing. Thoughts?

File: src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs (hunk 2 above)
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs]: TODO: will clean this up: move _parameterValues to the base visitor and remove this one.

File: src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedQueryTranslationPostprocessor.cs [hunk 6]
```diff
@@ -25,7 +26,10 @@ public class SqlServerParameterBasedQueryTranslationPostprocessor : RelationalPa
             var searchConditionOptimized = (SelectExpression)new SearchConditionConvertingExpressionVisitor(Dependencies.SqlExpressionFactory)
                 .Visit(optimizedSelectExpression);
 
-            return (searchConditionOptimized, canCache);
+            var optimized = (SelectExpression)new SqlExpressionOptimizingExpressionVisitor(
```
Comment (maumar) [inline src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedQueryTranslationPostprocessor.cs]: we need to run this second time again (before those optimizations were made by 2nd level cache optimizer, where SearchCondition was done earlier).

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs [hunk 7]
```diff
@@ -15,13 +14,5 @@ public class SqlServerQueryTranslationPostprocessor : RelationalQueryTranslation
             : base(dependencies, relationalDependencies, queryCompilationContext)
         {
         }
-
```
Comment (maumar) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs]: TODO: will remove (or shall we keep the scaffolding? ;) )

File: src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs [hunk 8]
```diff
@@ -38,17 +37,19 @@ public class RelationalParameterBasedQueryTranslationPostprocessor
...
-            if (!ReferenceEquals(selectExpression, inExpressionOptimized))
+            var nullSemanticsOptimized = nullSemanticsRewritingExpressionVisitor.Visit(selectExpression);
+            if (!nullSemanticsRewritingExpressionVisitor.CanCache)
             {
                 canCache = false;
             }
 
-            var nullParametersOptimized = new ParameterNullabilityBasedSqlExpressionOptimizingExpressionVisitor(
-                Dependencies.SqlExpressionFactory, UseRelationalNulls, parametersValues).Visit(inExpressionOptimized);
+            var nullParametersOptimized = new SqlExpressionOptimizingExpressionVisitor(
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs]: should we create those using DI, or should it be enough for providers to just override Optimize method?

Comment (maumar) [reply src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs]: or perhaps we can add optimize method so that providers can inject their optimizations after our visitor runs, but before FromSqlParameterApplyingExpressionVisitor

Comment (maumar) [reply src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs]: https://github.com/aspnet/EntityFrameworkCore/issues/10514

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 9]
```diff
@@ -370,169 +518,311 @@ protected override Expression VisitSqlBinary(SqlBinaryExpression sqlBinaryExpres
...
+                    right = rightUnary.Operand;
                 }
 
-                var leftIsNull = _sqlExpressionFactory.IsNull(newLeft);
-                var rightIsNull = _sqlExpressionFactory.IsNull(newRight);
+                // a == b <=> !a == !b -> a == b
+                // !a == b <=> a == !b -> a != b
+                // a != b <=> !a != !b -> a != b
+                // !a != b <=> a != !b -> a == b
+                return sqlBinaryExpression.OperatorType == ExpressionType.Equal
```
Comment (roji) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Can simplify with XOR?

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 10]
```diff
@@ -567,31 +857,232 @@ protected override Expression VisitSqlFunction(SqlFunctionExpression sqlFunction
 
         protected override Expression VisitSqlParameter(SqlParameterExpression sqlParameterExpression)
         {
-            // at this point we assume every parameter is nullable, we will filter out the non-nullable ones once we know the actual values
-            _isNullable = true;
+            _isNullable = _parameterValues[sqlParameterExpression.Name] == null;
```
Comment (roji) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: I wonder... we treat null parameters as nullable, but if we treated them as a null *constant* instead, some other optimizations could open up. How about returning an SqlConstantExpression here?

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 11]
```diff
@@ -567,31 +857,232 @@ protected override Expression VisitSqlFunction(SqlFunctionExpression sqlFunction
...
 
-            _canOptimize = canOptimize;
+            var result = sqlUnaryExpression.Update(operand);
+
+            return !_isNullable && sqlUnaryExpression.OperatorType == ExpressionType.Not
+                ? OptimizeNonNullableNotExpression(result)
+                : result;
+        }
+
+        private SqlExpression OptimizeNonNullableNotExpression(SqlUnaryExpression sqlUnaryExpression)
```
Comment (roji) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Should this also be called after rewriting null semantics?

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 12]
```diff
@@ -567,31 +857,232 @@ protected override Expression VisitSqlFunction(SqlFunctionExpression sqlFunction
...
+        {
+            // optimizations below are only correct in 2-value logic
+            if (sqlUnaryExpression.Operand is SqlBinaryExpression sqlBinaryOperand)
```
Comment (roji) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Since the whole method is only interested in binary, I always prefer to inverse the logic and exit early for non-binary, this way we reduce an indentation (easier to read).

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 13]
```diff
@@ -567,31 +857,232 @@ protected override Expression VisitSqlFunction(SqlFunctionExpression sqlFunction
...
+                if (TryNegate(sqlBinaryOperand.OperatorType, out var negated))
+                {
+                    return _sqlExpressionFactory.MakeBinary(
+                        negated,
+                        sqlBinaryOperand.Left,
+                        sqlBinaryOperand.Right,
+                        sqlBinaryOperand.TypeMapping);
+                }
+
+                static bool TryNegate(ExpressionType expressionType, out ExpressionType result)
```
Comment (roji) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Probably better to put local functions at the very end.

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 14]
```diff
@@ -567,31 +857,232 @@ protected override Expression VisitSqlFunction(SqlFunctionExpression sqlFunction
...
+                        && sqlBinaryOperand.OperatorType != ExpressionType.OrElse:
+                {
+                    // in general:
+                    // binaryOp(a, b) == null -> a == null || b == null
+                    // binaryOp(a, b) != null -> a != null && b != null
+                    // for coalesce:
+                    // (a ?? b) == null -> a == null && b == null
+                    // (a ?? b) != null -> a != null || b != null
+                    // for AndAlso, OrElse we can't do this optimization
+                    // we could do something like this, but it seems too complicated:
```
Comment (roji) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Out of curiosity, do we think it's too complicated for us to do, or that it would degrade the overall perf of the SQL query?

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 15]
```diff
@@ -2,25 +2,37 @@
...
+using System.Collections;
 using System.Collections.Generic;
 using System.Linq.Expressions;
 using Microsoft.EntityFrameworkCore.Internal;
 using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
+using Microsoft.EntityFrameworkCore.Storage;
 
 namespace Microsoft.EntityFrameworkCore.Query.Internal
 {
     public class NullSemanticsRewritingExpressionVisitor : SqlExpressionVisitor
```
Comment (roji) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: We should consider renaming this as it now also does general null optimizations (maybe NullabilityHandlingExpressionVisitor or similar?)

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 16]
```diff
@@ -111,56 +123,164 @@ protected override Expression VisitIn(InExpression inExpression)
...
+            switch (valuesExpression)
+            {
+                case SqlConstantExpression sqlConstant:
+                {
+                    CanCache = false;
+                    typeMapping = sqlConstant.TypeMapping;
+                    var values = (IEnumerable)sqlConstant.Value;
+                    foreach (var value in values)
+                    {
+                        if (value == null)
```
[the remark this answers is not in the document]
Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: We don't translate above yet. It requires representation of array on server side.

**Comment by smitpatel** [comment]
>  we can also carry info from right to left just as well.

That may not be correct. The logic of carrying over non-nullability of left to right relies on short-circuiting behavior of `&&` operator. logical operators does not short-circuit from right side.

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 16 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Am I missing something? Can't the above simply be translated as:

```c#
SELECT *
FROM Customers
WHERE 2 IN (1, Id, 3)
```

**Comment by roji** [comment]
>> we can also carry info from right to left just as well.
>
> That may not be correct. The logic of carrying over non-nullability of left to right relies on short-circuiting behavior of && operator. logical operators does not short-circuit from right side.

From my understanding SQL doesn't guarantee any particular evaluation order: [PG docs on this](https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-EXPRESS-EVAL), [some](https://blogs.msdn.microsoft.com/bartd/2011/03/03/dont-depend-on-expression-short-circuiting-in-t-sql-not-even-with-case/) [SQL Server](https://www.sqlservercentral.com/articles/understanding-t-sql-expression-short-circuiting) [links](https://weblogs.sqlteam.com/jeffs/2008/02/22/sql-server-short-circuit/) (I think we discussed this briefly in Redmond). Unless I'm mistaken the query planner is free to evaluate the right-hand side first if it thinks it's cheaper etc.

Also, I'm not 100% sure, but I'm not sure this matters for conjunctions. If one side requires that a column be non-null, then the conjunction can only be true if that is the case, so it shouldn't matter whether the other side contains null-compensating constructs or not... And so we should be able to omit them.

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 16 above)
[the remark this answers is not in the document]
Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: It can be. We did not have customer feedback to add it yet and it works only for Contains.

**Comment by smitpatel** [comment]
While, I was not aware of SQL doing differently, what I wrote pertains to C# short-circuiting behavior. (`&&` operator and not `AND`). The likely way to have short-circuiting arising in SQL tree is going to be from C# behavior (and in most cases user written). So we are capturing most cases where it could be useful right now.

We could check right side also and try to apply left side though first thing would be we need to evaluate if it is going to be correct in all cases. Next, we need to evaluate if cost of doing such processing is worth the perf penalty when C# code would never generate it (hence falls down to translation pipeline generate such code) and translation pipeline can translate it in C# way of short-circuiting. Worst case, it won't be optimized and would be longer SQL.

Even if it is correct, given perf cost, we should not implement it unless we have a specific user reported case where it would be required and it is not arising before issue in pipeline somewhere.

Feel free to file an issue if you feel strongly about it.

**Comment by roji** [comment]
@smitpatel as long as we're implementing this new mechanism (nonNullableColumns), I don't see why we shouldn't just do it right off the bat... we implement many things not explicitly requested by users because we know they're right.

I agree that user-written code is more likely to assume left-to-right short-circuiting behavior (as in C#). However, we also apply various transformations that could result in right-to-left optimization opportunities, making this worthwhile IMHO. For example, consider something like this:

```c#
customers.Where(c => c.Name != x && c.Name > 3)
```

This seems like pretty natural C# code. However, the right-hand side can only be true if c.Name is non-nullable; this could be carried over to the left side, obviating null compensation there.

Maybe before deferring this to another issue we should see what @maumar thinks?

**Comment by smitpatel** [comment]
nonNullable columns is not new thing, it was already there before too.

> Feel free to file an issue if you feel strongly about it.

**Comment by roji** [comment]
Opened #19248

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 17]
```diff
@@ -111,56 +123,164 @@ protected override Expression VisitIn(InExpression inExpression)
...
+                return !hasNullValue || !itemNullable
+                    ? (SqlExpression)_sqlExpressionFactory.Constant(
+                        inExpression.IsNegated,
+                        inExpression.TypeMapping)
+                    : inExpression.IsNegated
+                        ? _sqlExpressionFactory.IsNotNull(item)
+                        : _sqlExpressionFactory.IsNull(item);
+            }
+
+            _isNullable = _isNullable || itemNullable || subqueryNullable;
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: need to set _isNullable before returning from the function below - simplified and moved the logic inside the if block

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 18]
```diff
@@ -111,56 +123,164 @@ protected override Expression VisitIn(InExpression inExpression)
...
+
+            if (!itemNullable
+                || (_canOptimize && !inExpression.IsNegated && !hasNullValue))
+            {
+                // non_nullable IN (1, 2) -> non_nullable IN (1, 2)
+                // non_nullable IN (1, 2, NULL) -> non_nullable IN (1, 2)
+                // non_nullable NOT IN (1, 2) -> non_nullable NOT IN (1, 2)
+                // non_nullable NOT IN (1, 2, NULL) -> non_nullable NOT IN (1, 2)
+                // nullable IN (1, 2) -> nullable IN (1, 2) (optimized)
+                return inExpression.Update(item, inValues, subquery);
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: there could have been null in the values, example 2 and 4 in the comment

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 19]
```diff
@@ -111,56 +123,164 @@ protected override Expression VisitIn(InExpression inExpression)
...
-            var newMatch = (SqlExpression)Visit(likeExpression.Match);
-            var isNullable = _isNullable;
-            _isNullable = false;
-            var newPattern = (SqlExpression)Visit(likeExpression.Pattern);
-            isNullable |= _isNullable;
-            _isNullable = false;
-            var newEscapeChar = (SqlExpression)Visit(likeExpression.EscapeChar);
-            _isNullable |= isNullable;
+            var newTable = (TableExpressionBase)Visit(innerJoinExpression.Table);
+            var newJoinPredicate = VisitJoinPredicate((SqlBinaryExpression)innerJoinExpression.JoinPredicate);
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: c# join follows relational null semantics - we do this to explicitly avoid null semantics rewrites. However, to further complicate things ,if you compare composite keys the comparison behaves like any other c# comparison.
So: `join null equals null` wouldn't match
but: `join { null } equals { null }` would

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 20]
```diff
@@ -181,11 +301,24 @@ private SqlExpression VisitJoinPredicate(SqlBinaryExpression predicate)
...
             if (predicate.OperatorType == ExpressionType.Equal)
             {
-                var newLeft = (SqlExpression)Visit(predicate.Left);
-                var newRight = (SqlExpression)Visit(predicate.Right);
+                _isNullable = false;
+                var left = (SqlExpression)Visit(predicate.Left);
+                var leftNullable = _isNullable;
+                _isNullable = false;
+                var right = (SqlExpression)Visit(predicate.Right);
+                var rightNullable = _isNullable;
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: it doesn't matter - VisitJoinPredicate is always called from JOIN, which then again is part of SelectExpression which is always nullable

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 21]
```diff
@@ -370,169 +518,311 @@ protected override Expression VisitSqlBinary(SqlBinaryExpression sqlBinaryExpres
...
+            return sqlBinaryExpression.Update(left, right);
 
-                // optimized expansion which doesn't distinguish between null and false
-                if (canOptimize
-                    && sqlBinaryExpression.OperatorType == ExpressionType.Equal
-                    && !leftNegated
-                    && !rightNegated)
+            bool? IsTrueOrFalse(SqlExpression sqlExpression)
+            {
+                if (sqlExpression is SqlConstantExpression sqlConstantExpression && sqlConstantExpression.Value is bool boolConstant)
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: yeah, i realized that as well

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 22]
```diff
@@ -111,56 +123,164 @@ protected override Expression VisitIn(InExpression inExpression)
...
+            // adding null comparison term to remove nulls completely from the resulting expression
+            _isNullable = false;
+
+            // nullable IN (1, 2) -> nullable IN (1, 2) AND nullable IS NOT NULL (full)
+            // nullable IN (1, 2, NULL) -> nullable IN (1, 2) OR nullable IS NULL (full)
+            // nullable NOT IN (1, 2) -> nullable NOT IN (1, 2) OR nullable IS NULL (full)
+            // nullable NOT IN (1, 2, NULL) -> nullable NOT IN (1, 2) AND nullable IS NOT NULL (full)
+            return inExpression.IsNegated == hasNullValue
+                ? _sqlExpressionFactory.AndAlso(
+                    inExpression.Update(item, inValues, subquery),
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: I implemented it initially, but the more I look at it, the less I like it. Feels like opening a can of worms - we have other functions where not all arguments are always used (CaseExpression). Also, select expression has a ton of arguments and it could use "targeted" update methods. I'd rather keep 1 method which always takes all the arguments and don't worry/think about which functions need what. Thoughts? @roji @smitpatel

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 13 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: I thought we were supposed to put local functions at the end of relevant block. I was wrong ;) - fixed

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 23]
```diff
@@ -567,31 +857,232 @@ protected override Expression VisitSqlFunction(SqlFunctionExpression sqlFunction
...
+                    return negated.HasValue;
+                }
+            }
+
+            return sqlUnaryExpression;
+        }
+
+        private SqlExpression ProcessNullNotNull(
+            SqlUnaryExpression sqlUnaryExpression,
+            SqlExpression operand,
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: fixed case where it was different and removed the argument

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 14 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: the latter - SQL becomes way too complicated

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 24]
```diff
@@ -567,31 +857,232 @@ protected override Expression VisitSqlFunction(SqlFunctionExpression sqlFunction
...
+            {
+                case SqlConstantExpression sqlConstantOperand:
+                    // null_value_constant is null -> true
+                    // null_value_constant is not null -> false
+                    // not_null_value_constant is null -> false
+                    // not_null_value_constant is not null -> true
+                    return sqlConstantOperand.Value == null
+                        ? _sqlExpressionFactory.Constant(
+                            sqlUnaryExpression.OperatorType == ExpressionType.Equal,
+                            sqlUnaryExpression.TypeMapping)
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: don't have access to it

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 25]
```diff
@@ -111,56 +123,164 @@ protected override Expression VisitIn(InExpression inExpression)
...
+                        inValues.Add(value);
+                    }
+
+                    break;
+                }
+            }
+
+            var processedValues = inValues.Count > 0
+                ? (SqlExpression)Visit(_sqlExpressionFactory.Constant(inValues, typeMapping))
+                : null;
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: makes the check for empty more complicated - need to cast to SqlConstantExpression (or we can assume result is always SqlConstant, but providers could change that behavior), then cast result to List<object> and then test Count. I can do that but not sure if it's much better.

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 26]
```diff
@@ -111,56 +123,164 @@ protected override Expression VisitIn(InExpression inExpression)
...
+
+                        inValues.Add(value);
+                    }
+
+                    break;
+                }
+            }
+
+            var processedValues = inValues.Count > 0
+                ? (SqlExpression)Visit(_sqlExpressionFactory.Constant(inValues, typeMapping))
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: added a comment to fix this when/if we support mix of columns and constants

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 27]
```diff
@@ -370,169 +518,311 @@ protected override Expression VisitSqlBinary(SqlBinaryExpression sqlBinaryExpres
...
+            bool leftNullable,
+            bool rightNullable,
+            bool canOptimize)
+        {
+            var leftNullValue = leftNullable && (left is SqlConstantExpression || left is SqlParameterExpression);
+            var rightNullValue = rightNullable && (right is SqlConstantExpression || right is SqlParameterExpression);
+
+            // a == null -> a IS NULL
+            // a != null -> a IS NOT NULL
+            if (rightNullValue)
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: I'd rather keep the logic as simple as possible, even when it means some duplication.

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 10 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Sounds good

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 11 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: i think it's not needed - null semantics rewrite never ends up with top level IsNull/IsNotNull expression, so this optimization would always be a noop. We run the optimizations on IsNull parts of the null semantics rewrite, so they should be in their minimal form already.

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 25 above)
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: actually, after giving it some more thought I agree that empty list looks better overall - will change

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 28]
```diff
@@ -370,169 +518,311 @@ protected override Expression VisitSqlBinary(SqlBinaryExpression sqlBinaryExpres
...
+                        : _sqlExpressionFactory.Not(right)
+                    : leftTrueFalseValue
+                        ? _sqlExpressionFactory.Not(right)
+                        : right;
+            }
+
+            // only correct in 2-value logic
+            // a == a -> true
+            // a != a -> false
+            if (!leftNullable
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Current optimizations shouldn't make a difference - all cases where rewrite null semantics does something (i.e. weeds out nulls from the expression) and up with AndAlso or OrElse as a top level node, whereas all the optimizations here are for == and !=. Might be worthwhile in the future if/when we come up with more optimizations

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 29]
```diff
@@ -181,11 +301,24 @@ private SqlExpression VisitJoinPredicate(SqlBinaryExpression predicate)
...
-                var newLeft = (SqlExpression)Visit(predicate.Left);
-                var newRight = (SqlExpression)Visit(predicate.Right);
+                _isNullable = false;
+                var left = (SqlExpression)Visit(predicate.Left);
+                var leftNullable = _isNullable;
+                _isNullable = false;
+                var right = (SqlExpression)Visit(predicate.Right);
+                var rightNullable = _isNullable;
+
+                var result = OptimizeComparison(
```
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Not sure what you mean. It should only end up as cross join if the join predicate collapses to tautology, which seems fine to me. And we run those optimizations for inner and outer joins both.

**Comment by maumar** [comment]
@roji @smitpatel new version is up, please take a look. Biggest concern is NullHandling, parts that compute non-nullable columns (especially in binary, but also I might have missed a reset somewhere >.<)

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs (hunk 3 above)
Comment (roji) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs]: Sure, SQL would definitely be nicer!

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 1 above)
Comment (roji) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: At the very least, some stuff here looks like it's correct even for 3-value logic (e.g. `!(a == b) -> (a != b)`), no?

In any case, if something is incorrect for 3-value logic I guess we shouldn't do it, right?

File: src/EFCore.Relational/Query/Internal/NullabilityHandlingExpressionVisitor.cs [hunk 30]
```diff
@@ -0,0 +1,1474 @@
...
+                    _sqlExpressionFactory.IsNull(item));
+        }
+
+        private (SqlConstantExpression processedValues, bool hasNullValue) ProcessInExpressionValues(SqlExpression valuesExpression)
+        {
+            var inValues = new List<object>();
+            var hasNullValue = false;
+            RelationalTypeMapping typeMapping = null;
+
+            if (valuesExpression is SqlConstantExpression
```
Comment (roji) [inline src/EFCore.Relational/Query/Internal/NullabilityHandlingExpressionVisitor.cs]: Just for correctness, what happens if valuesExpression is neither constant nor parameter? I know non-PG database don't support array columns, and even on PG translation will have already transformed the whole thing to something else. But maybe an array with a value converter?

Maybe it's better to just lift this check to VisitIn and just immediately return from there.

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 16 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: OK. Seems pretty simple to me, but we can forget for now if people don't think it's important.

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 22 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: As a general rule, if the invariant of the expression is for exactly one of subquery and values to be null, then ideally it shouldn't be possible to create a violating instance. #19229 was about doing that check in runtime, but doing that at compile-time (via the methods we expose is even better). This both creates a safer type, and documents the invariants very nicely.

Also, as discussed in design, we don't have to generalize every such decision - it seems OK to do this for InExpression, and if we feel that SelectExpression is a different case, have something different. But let's see what @smitpatel has to say :)

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 29 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Yeah, that's pretty much what I meant. If OptimizeComparison reduces the expression to true, we have a cross join. The question is if in Visit{Inner,Left}Join we should check for this case and return a CrossJoinExpression, instead of having an inner/left join with a TRUE constant predicate.

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 19 above)
[the remark this answers is not in the document]
Comment (roji) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Oh, this is new to me...! Very strange that C# has relational null semantics in this one, unique place. So this makes sense...

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 1 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: sounds good!

File: src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs (hunk 8 above)
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs]: will be done in separate PR, if we decide to do it

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 29 above)
[the remark this answers is not in the document]
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: good idea - done

**Comment by maumar** [comment]
another version up @roji @smitpatel

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 31]
```diff
@@ -52,12 +38,27 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
                 SelectExpression selectExpression => VisitSelectExpression(selectExpression),
+                InnerJoinExpression innerJoinExpression => VisitInnerJoinExpression(innerJoinExpression),
                 _ => base.VisitExtension(extensionExpression),
             };
+
+            Expression VisitInnerJoinExpression(InnerJoinExpression innerJoinExpression)
+            {
+                var result = base.VisitExtension(innerJoinExpression);
+
+                return (result is InnerJoinExpression innerJoinExpressionResult
```
Comment (maumar) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: we can only optimize INNER JOIN - if we try this with left join, we get incorrect results if the right side has no elements

File: src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs [hunk 32]
```diff
@@ -46,17 +45,19 @@ public class RelationalParameterBasedQueryTranslationPostprocessor
...
+            var nullabilityHandlingExpressionVisitor = new NullabilityHandlingExpressionVisitor(
+                UseRelationalNulls,
+                Dependencies.SqlExpressionFactory,
+                parametersValues);
 
-            var inExpressionOptimized = new InExpressionValuesExpandingExpressionVisitor(
-                Dependencies.SqlExpressionFactory, parametersValues).Visit(selectExpression);
-
-            if (!ReferenceEquals(selectExpression, inExpressionOptimized))
+            var nullabilityHandled = nullabilityHandlingExpressionVisitor.Visit(selectExpression);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs]: Use same tuple pattern for return type.

File: src/EFCore.Relational/Query/Internal/NullabilityHandlingExpressionVisitor.cs [hunk 33]
```diff
@@ -0,0 +1,1472 @@
...
+            _useRelationalNulls = useRelationalNulls;
+            _sqlExpressionFactory = sqlExpressionFactory;
+            _parameterValues = parameterValues;
+            _canOptimize = true;
+            CanCache = true;
+        }
+
+        private void RestoreNonNullableColumnsList(int counter)
+        {
+            _nonNullableColumns.RemoveRange(counter, _nonNullableColumns.Count - counter);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/NullabilityHandlingExpressionVisitor.cs]: Add a check before calling into RemoveRange if there are additional columns

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 22 above)
[the remark this answers is not in the document]
Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Single method.

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 34]
```diff
@@ -567,31 +857,232 @@ protected override Expression VisitSqlFunction(SqlFunctionExpression sqlFunction
...
+                    result = negated ?? default;
+
+                    return negated.HasValue;
+                }
+            }
+
+            return sqlUnaryExpression;
+        }
+
+        private SqlExpression ProcessNullNotNull(
```
[the remark this answers is not in the document]
Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Why is this protected virtual, who is overriding it and where?

**Comment by maumar** [comment]
@smitpatel @roji new version up, addressing feedback from design meeting, mostly combining null semantics and sql optimizer and applying some optimizations in search condition, so that we don't need to run optimizer after search condition

File: src/EFCore.Relational/Query/FromSqlParameterApplyingExpressionVisitor.cs [hunk 35]
```diff
@@ -0,0 +1,134 @@
...
+        public override Expression Visit(Expression expression)
+        {
+            if (expression is FromSqlExpression fromSql)
+            {
+                if (!_visitedFromSqlExpressions.TryGetValue(fromSql, out var updatedFromSql))
+                {
+                    switch (fromSql.Arguments)
+                    {
+                        case ParameterExpression parameterExpression:
+                            var parameterValues = (object[])_parametersValues[parameterExpression.Name];
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/FromSqlParameterApplyingExpressionVisitor.cs]: Could DRY

**Comment by smitpatel** [comment]
>         public virtual (SelectExpression selectExpression, bool canCache) Optimize(

Tuple members are PascalCase, when you assign them to variable they are camelCase. @AndriySvyryd - thoughts?

---
Refers to: src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs:41 in 5c11423. [](commit_id = 5c114233ab3a9982823640895a2b900afbb6d897, deletion_comment = True)

File: src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs [hunk 36]
```diff
@@ -46,300 +32,24 @@ public class RelationalParameterBasedQueryTranslationPostprocessor
...
-                parametersValues).Visit(nullParametersOptimized);
+                parametersValues).Visit(sqlExpressionOptimized);
 
-            if (!ReferenceEquals(nullParametersOptimized, fromSqlParameterOptimized))
+            if (!ReferenceEquals(sqlExpressionOptimized, fromSqlParameterOptimized))
             {
                 canCache = false;
             }
 
             return (selectExpression: (SelectExpression)fromSqlParameterOptimized, canCache);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs]: Avoid named parameter in this case

File: src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs [hunk 37]
```diff
@@ -42,22 +38,12 @@ public override Expression Process(Expression query)
...
-            {
-                query = new NullSemanticsRewritingExpressionVisitor(SqlExpressionFactory).Visit(query);
-            }
-
             query = OptimizeSqlExpression(query);
 
             return query;
         }
 
         protected virtual Expression OptimizeSqlExpression([NotNull] Expression query)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs]: Obsolete if not breaking
@ajcvickers

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 38]
```diff
@@ -0,0 +1,1723 @@
...
+        protected virtual ISqlExpressionFactory SqlExpressionFactory { get; }
+        protected virtual IReadOnlyDictionary<string, object> ParameterValues { get; }
+        protected virtual List<ColumnExpression> NonNullableColumns { get; } = new List<ColumnExpression>();
+
+        protected virtual bool IsNullable { get; set; }
+        protected virtual bool CanOptimize { get; set; }
+        protected virtual bool CanCache { get; set; }
+
+        public SqlExpressionOptimizingExpressionVisitor(
+            bool useRelationalNulls,
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: bool at the end may be

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 39]
```diff
@@ -0,0 +1,1723 @@
...
+            {
+                NonNullableColumns.RemoveRange(counter, NonNullableColumns.Count - counter);
+            }
+        }
+
+        public virtual (SelectExpression selectExpression, bool canCache) OptimizeSqlExpression([NotNull] SelectExpression selectExpression)
+        {
+            Check.NotNull(selectExpression, nameof(selectExpression));
+
+            var result = (SelectExpression)Visit(selectExpression);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: Inline

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 40]
```diff
@@ -0,0 +1,1723 @@
...
+            // otherwise the result is nullable if any of the WhenClause results OR ElseResult is nullable
+            var isNullable = caseExpression.ElseResult == null;
+
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
+            var canOptimize = CanOptimize;
+            var testIsCondition = caseExpression.Operand == null;
+            CanOptimize = false;
+            var newOperand = (SqlExpression)Visit(caseExpression.Operand);
+
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: Why operand need this restoration? It should be value type on top level so it would never add itself. If it is nested which contain condition then nested element will remove it.

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 41]
```diff
@@ -0,0 +1,1723 @@
...
+        {
+            Check.NotNull(caseExpression, nameof(caseExpression));
+
+            IsNullable = false;
+            // if there is no 'else' there is a possibility of null, when none of the conditions are met
+            // otherwise the result is nullable if any of the WhenClause results OR ElseResult is nullable
+            var isNullable = caseExpression.ElseResult == null;
+
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
+            var canOptimize = CanOptimize;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: Keep isnullable and CanOptimize together with their counterparts

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 42]
```diff
@@ -0,0 +1,1723 @@
...
+            var testIsCondition = caseExpression.Operand == null;
+            CanOptimize = false;
+            var newOperand = (SqlExpression)Visit(caseExpression.Operand);
+
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+
+            var newWhenClauses = new List<CaseWhenClause>();
+            foreach (var whenClause in caseExpression.WhenClauses)
+            {
+                CanOptimize = testIsCondition;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: Reset IsNullable before every visit. It may be redundant in some cases but can become error prone pretty quick

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 43]
```diff
@@ -0,0 +1,1723 @@
...
+
+                var newTest = (SqlExpression)Visit(whenClause.Test);
+                CanOptimize = false;
+                IsNullable = false;
+                var newResult = (SqlExpression)Visit(whenClause.Result);
+                isNullable |= IsNullable;
+                newWhenClauses.Add(new CaseWhenClause(newTest, newResult));
+
+                RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: This shouldn't be here

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 44]
```diff
@@ -0,0 +1,1723 @@
...
+            }
+
+            CanOptimize = false;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: reset

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 45]
```diff
@@ -0,0 +1,1723 @@
...
+            var newElseResult = (SqlExpression)Visit(caseExpression.ElseResult);
+            IsNullable |= isNullable;
+            CanOptimize = canOptimize;
+
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: why

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 46]
```diff
@@ -0,0 +1,1723 @@
...
+
+            return caseExpression.Update(newOperand, newWhenClauses, newElseResult);
+        }
+
+        protected override Expression VisitColumn(ColumnExpression columnExpression)
+        {
+            Check.NotNull(columnExpression, nameof(columnExpression));
+
+            IsNullable = !NonNullableColumns.Contains(columnExpression) && columnExpression.IsNullable;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: put IsNullable check first. Contains on a list is more expensive

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 47]
```diff
@@ -0,0 +1,1723 @@
...
+
+            return columnExpression;
+        }
+
+        protected override Expression VisitCrossApply(CrossApplyExpression crossApplyExpression)
+        {
+            Check.NotNull(crossApplyExpression, nameof(crossApplyExpression));
+
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: DRY with other table expression except for update part.
Optionally can also add abstract method Update on TableExpressionBase

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 48]
```diff
@@ -0,0 +1,1723 @@
...
+        protected override Expression VisitExcept(ExceptExpression exceptExpression)
+        {
+            Check.NotNull(exceptExpression, nameof(exceptExpression));
+
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
+            var canOptimize = CanOptimize;
+            CanOptimize = false;
+            var source1 = (SelectExpression)Visit(exceptExpression.Source1);
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+            var source2 = (SelectExpression)Visit(exceptExpression.Source2);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: reset canOptimize?

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 49]
```diff
@@ -0,0 +1,1723 @@
...
+            return fromSqlExpression;
+        }
+
+        protected override Expression VisitIn(InExpression inExpression)
+        {
+            Check.NotNull(inExpression, nameof(inExpression));
+
+            var canOptimize = CanOptimize;
+            CanOptimize = false;
+            IsNullable = false;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: no remembering of previous IsNullable?

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 50]
```diff
@@ -0,0 +1,1723 @@
...
+            // nullable NOT IN (1, 2, NULL) -> nullable NOT IN (1, 2) AND nullable IS NOT NULL (full)
+            return inExpression.IsNegated == hasNullValue
+                ? SqlExpressionFactory.AndAlso(
+                    inExpression.Update(item, inValues, subquery: null),
+                    SqlExpressionFactory.IsNotNull(item))
+                : SqlExpressionFactory.OrElse(
+                    inExpression.Update(item, inValues, subquery: null),
+                    SqlExpressionFactory.IsNull(item));
+
+            (SqlConstantExpression processedValues, bool hasNullValue) ProcessInExpressionValues(SqlExpression valuesExpression)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: Casing

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 51]
```diff
@@ -0,0 +1,1723 @@
...
+                RelationalTypeMapping typeMapping = null;
+
+                IEnumerable values = null;
+                if (valuesExpression is SqlConstantExpression sqlConstant)
+                {
+                    typeMapping = sqlConstant.TypeMapping;
+                    values = (IEnumerable)sqlConstant.Value;
+                }
+
+                if (valuesExpression is SqlParameterExpression sqlParameter)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: else if

Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: switch block?

---
In reply to: [362989908](https://github.com/aspnet/EntityFrameworkCore/pull/19168#discussion_r362989908) [](ancestors = 362989908)

Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: switch block would also give chance to throw for unknown type which are ignored here.

---
In reply to: [362989948](https://github.com/aspnet/EntityFrameworkCore/pull/19168#discussion_r362989948) [](ancestors = 362989948,362989908)

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 52]
```diff
@@ -0,0 +1,1723 @@
...
+                return inExpression.Update(item, values, subquery: null);
+            }
+
+            // for c# null semantics we need to remove nulls from Values and add IsNull/IsNotNull when necessary
+            var (inValues, hasNullValue) = ProcessInExpressionValues(inExpression.Values);
+
+            CanOptimize = canOptimize;
+
+            // either values array is empty or only contains null
+            if (((List<object>)inValues.Value).Count == 0)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: just project out inner list too rather than accessing casting like this

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 53]
```diff
@@ -0,0 +1,1723 @@
...
+                    if (value == null)
+                    {
+                        hasNullValue = true;
+                        continue;
+                    }
+
+                    inValues.Add(value);
+                }
+
+                // this is only correct if constant values are the only things allowed here, i.e no mixing of constants and columns
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: Remove comment. Mixing cannot be represented in current SQL tree anyway.

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 54]
```diff
@@ -0,0 +1,1723 @@
...
+        protected override Expression VisitInnerJoin(InnerJoinExpression innerJoinExpression)
+        {
+            Check.NotNull(innerJoinExpression, nameof(innerJoinExpression));
+
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
+            var canOptimize = CanOptimize;
+            CanOptimize = false;
+            var newTable = (TableExpressionBase)Visit(innerJoinExpression.Table);
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+            var newJoinPredicate = VisitJoinPredicate((SqlBinaryExpression)innerJoinExpression.JoinPredicate);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: reset canoptimize

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 55]
```diff
@@ -0,0 +1,1723 @@
...
+            return newJoinPredicate is SqlConstantExpression constantJoinPredicate
+                && constantJoinPredicate.Value is bool boolPredicate
+                && boolPredicate
+                ? (Expression)new CrossJoinExpression(newTable)
+                : innerJoinExpression.Update(newTable, newJoinPredicate);
+        }
+
+        protected override Expression VisitIntersect(IntersectExpression intersectExpression)
+        {
+            Check.NotNull(intersectExpression, nameof(intersectExpression));
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: DRY all set operations

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 56]
```diff
@@ -0,0 +1,1723 @@
...
+
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
+            var canOptimize = CanOptimize;
+            CanOptimize = false;
+            var source1 = (SelectExpression)Visit(intersectExpression.Source1);
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+            var source2 = (SelectExpression)Visit(intersectExpression.Source2);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: reset canOptimize

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 57]
```diff
@@ -0,0 +1,1723 @@
...
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
+            var canOptimize = CanOptimize;
+            CanOptimize = false;
+            var newTable = (TableExpressionBase)Visit(leftJoinExpression.Table);
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+            var newJoinPredicate = VisitJoinPredicate((SqlBinaryExpression)leftJoinExpression.JoinPredicate);
+            CanOptimize = canOptimize;
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+
+            return leftJoinExpression.Update(newTable, newJoinPredicate);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: DRY partial

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 40 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: i added the restore everywhere, just in case - will remove

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 58]
```diff
@@ -0,0 +1,1723 @@
...
+
+            return fromSqlExpression;
+        }
+
+        protected override Expression VisitIn(InExpression inExpression)
+        {
+            Check.NotNull(inExpression, nameof(inExpression));
+
+            var canOptimize = CanOptimize;
+            CanOptimize = false;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: Extract a method out which take expression & canoptimize and returns visited expression and nullability

File: src/EFCore.Relational/Query/FromSqlParameterApplyingExpressionVisitor.cs (hunk 35 above)
Comment (maumar) [reply src/EFCore.Relational/Query/FromSqlParameterApplyingExpressionVisitor.cs]: too many differences

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 59]
```diff
@@ -0,0 +1,1723 @@
...
+                    leftNullable,
+                    rightNullable,
+                    CanOptimize);
+
+                CanOptimize = canOptimize;
+
+                return result;
+            }
+
+            if (predicate.OperatorType == ExpressionType.AndAlso)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: switch block

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 60]
```diff
@@ -0,0 +1,1723 @@
...
+                RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+            }
+
+            var orderings = new List<OrderingExpression>();
+            foreach (var ordering in rowNumberExpression.Orderings)
+            {
+                var newOrdering = (OrderingExpression)Visit(ordering);
+                changed |= newOrdering != ordering;
+                orderings.Add(newOrdering);
+                RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: avoid in both foreach

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 61]
```diff
@@ -0,0 +1,1723 @@
...
+            CanOptimize = false;
+
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
+            foreach (var item in selectExpression.Projection)
+            {
+                var updatedProjection = (ProjectionExpression)Visit(item);
+                projections.Add(updatedProjection);
+                changed |= updatedProjection != item;
+
+                RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: Avoid

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 62]
```diff
@@ -0,0 +1,1723 @@
...
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+
+            var limit = (SqlExpression)Visit(selectExpression.Limit);
+            changed |= limit != selectExpression.Limit;
+
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+
+            CanOptimize = canOptimize;
+
+            // we assume SelectExpression can always be null
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: It is not our assumption, it is reality lol

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 63]
```diff
@@ -0,0 +1,1723 @@
...
+        }
+
+        protected override Expression VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression)
+        {
+            Check.NotNull(sqlBinaryExpression, nameof(sqlBinaryExpression));
+
+            IsNullable = false;
+            var canOptimize = CanOptimize;
+
+            CanOptimize = CanOptimize && (sqlBinaryExpression.OperatorType == ExpressionType.AndAlso
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: formatting

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 64]
```diff
@@ -0,0 +1,1723 @@
...
+            if (sqlBinaryExpression.OperatorType != ExpressionType.AndAlso)
+            {
+                RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+            }
+
+            var right = (SqlExpression)Visit(sqlBinaryExpression.Right);
+            var rightNullable = IsNullable;
+            if (sqlBinaryExpression.OperatorType == ExpressionType.OrElse)
+            {
+                var intersect = leftNonNullableColumns.Intersect(NonNullableColumns).ToList();
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: only compute for the columns which were added in this method rather than all previous ones

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 65]
```diff
@@ -0,0 +1,1723 @@
...
+            // nullableStringColumn + NULL -> COALESCE(nullableStringColumn, "") + ""
+            if (sqlBinaryExpression.OperatorType == ExpressionType.Add
+                && sqlBinaryExpression.Type == typeof(string))
+            {
+                if (leftNullable)
+                {
+                    left = AddNullConcatenationProtection(left, sqlBinaryExpression.TypeMapping);
+                }
+
+                if (rightNullable)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: if both nullable only do it once

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 66]
```diff
@@ -0,0 +1,1723 @@
...
+                // we assume that NullSemantics rewrite is only needed (on the current level)
+                // if the optimization didn't make any changes.
+                // Reason is that optimization can/will change the nullability of the resulting expression
+                // and that inforation is not tracked/stored anywhere
+                // so we can no longer rely on nullabilities that we computed earlier (leftNullable, rightNullable)
+                // when performing null semantics rewrite.
+                // It should be fine because current optimizations *radically* change the expression
+                // (e.g. binary -> unary, or binary -> constant)
+                // but we need to pay attention in the future if we introduce more subtle transformations here
+                if (optimized == updated
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: do reference equality of expecting it be same (no rewrite)

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 67]
```diff
@@ -0,0 +1,1723 @@
...
+
+            return result is SqlBinaryExpression sqlBinaryResult
+                && (sqlBinaryExpression.OperatorType == ExpressionType.AndAlso || sqlBinaryExpression.OperatorType == ExpressionType.OrElse)
+                ? SimplifyLogicalSqlBinaryExpression(sqlBinaryResult)
+                : result;
+
+            SqlExpression AddNullConcatenationProtection(SqlExpression argument, RelationalTypeMapping typeMapping)
+                => argument switch
+                {
+                    SqlConstantExpression _ => SqlExpressionFactory.Constant(string.Empty, typeMapping),
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: cache

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 68]
```diff
@@ -0,0 +1,1723 @@
...
+                    SqlParameterExpression _ => SqlExpressionFactory.Constant(string.Empty, typeMapping),
+                    ColumnExpression _ => SqlExpressionFactory.Coalesce(argument, SqlExpressionFactory.Constant(string.Empty, typeMapping)),
+                    _ => argument
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: this could give incorrect results

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 43 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: there could be null columns set in the result - we don't want that information to propagate to another WhenClause

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 69]
```diff
@@ -0,0 +1,1723 @@
...
+                return sqlBinaryExpression.OperatorType == ExpressionType.Equal ^ leftNegated == rightNegated
+                    ? SqlExpressionFactory.NotEqual(left, right)
+                    : SqlExpressionFactory.Equal(left, right);
+            }
+
+            return sqlBinaryExpression.Update(left, right);
+
+            bool? IsTrueOrFalse(SqlExpression sqlExpression)
+            {
+                if (sqlExpression is SqlConstantExpression sqlConstantExpression && sqlConstantExpression.Value is bool boolConstant)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: why only constant and not parameter?

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 44 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: if null column information is added when visiting else it shouldn't propagate outside the CaseExpression

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 45 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: if null column information is added when visiting else it shouldn't propagate outside the CaseExpression

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 44 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: added helper method

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 70]
```diff
@@ -0,0 +1,1723 @@
...
+                        sqlConstantOperand.Value == null ^ sqlUnaryExpression.OperatorType == ExpressionType.NotEqual,
+                        sqlUnaryExpression.TypeMapping);
+
+                case SqlParameterExpression sqlParameterOperand:
+                    // null_value_parameter is null -> true
+                    // null_value_parameter is not null -> false
+                    // not_null_value_parameter is null -> false
+                    // not_null_value_parameter is not null -> true
+                    return SqlExpressionFactory.Constant(
+                        ParameterValues[sqlParameterOperand.Name] == null ^ sqlUnaryExpression.OperatorType == ExpressionType.NotEqual,
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: DRY with constant case

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 71]
```diff
@@ -0,0 +1,1723 @@
...
+                    switch (sqlUnaryOperand.OperatorType)
+                    {
+                        case ExpressionType.Convert:
+                        case ExpressionType.Not:
+                        case ExpressionType.Negate:
+                            // op(a) is null -> a is null
+                            // op(a) is not null -> a is not null
+                            return ProcessNullNotNull(
+                                SqlExpressionFactory.MakeUnary(
+                                    sqlUnaryExpression.OperatorType,
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: >sqlUnaryExpression [](start = 36, length = 18)

Could do sqlUnaryExpression.Update(sqlUnaryOperand.Operand)

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 72]
```diff
@@ -0,0 +1,1723 @@
...
+                            negated,
+                            sqlBinaryOperand.Left,
+                            sqlBinaryOperand.Right,
+                            sqlBinaryOperand.TypeMapping);
+                    }
+                }
+                break;
+            }
+
+            //var sqlUnaryOperand = sqlUnaryExpression.Operand as SqlUnaryExpression;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: ?

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 73]
```diff
@@ -0,0 +1,1723 @@
...
+                if (leftNullable && rightNullable)
+                {
+                    // ?a != ?b <=> !(?a) != !(?b) -> [(a != b) || (a == null || b == null)] && (a != null || b != null)
+                    // !(?a) != ?b <=> ?a != !(?b) -> [(a == b) || (a == null || b == null)] && (a != null || b != null)
+                    return leftNegated == rightNegated
+                        ? ExpandNullableNotEqualNullable(left, right, leftIsNull, leftIsNotNull, rightIsNull, rightIsNotNull)
+                        : ExpandNegatedNullableNotEqualNullable(left, right, leftIsNull, leftIsNotNull, rightIsNull, rightIsNotNull);
+                }
+
+                if (leftNullable)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: use same set of if conditions.

Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: as above block

---
In reply to: [363009379](https://github.com/aspnet/EntityFrameworkCore/pull/19168#discussion_r363009379) [](ancestors = 363009379)

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 74]
```diff
@@ -0,0 +1,1723 @@
...
+        {
+            Check.NotNull(sqlFunctionExpression, nameof(sqlFunctionExpression));
+
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
+            var canOptimize = CanOptimize;
+            CanOptimize = false;
+
+            var newInstance = (SqlExpression)Visit(sqlFunctionExpression.Instance);
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+            var newArguments = new SqlExpression[sqlFunctionExpression.Arguments.Count];
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: use niladic flag to avoid allocation

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 75]
```diff
@@ -0,0 +1,1723 @@
...
+            var source1 = (SelectExpression)Visit(unionExpression.Source1);
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+            var source2 = (SelectExpression)Visit(unionExpression.Source2);
+            CanOptimize = canOptimize;
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+
+            return unionExpression.Update(source1, source2);
+        }
+
+        private List<ColumnExpression> FindNonNullableColumns(SqlExpression sqlExpression)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: Where is this being used?

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 76]
```diff
@@ -0,0 +1,1723 @@
...
+        }
+
+        // ?a == ?b -> [(a == b) && (a != null && b != null)] || (a == null && b == null))
+        //
+        // a | b | F1 = a == b | F2 = (a != null && b != null) | F3 = F1 && F2 |
+        //   |   |             |                               |               |
+        // 0 | 0 | 1           | 1                             | 1             |
+        // 0 | 1 | 0           | 1                             | 0             |
+        // 0 | N | N           | 0                             | 0             |
+        // 1 | 0 | 0           | 1
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: could avoid line breaks if not necessary

Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: ?

File: src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs [hunk 77]
```diff
@@ -23,34 +23,58 @@ public class SearchConditionConvertingExpressionVisitor : SqlExpressionVisitor
...
-        }
+            => sqlExpression is SqlConstantExpression sqlConstantExpression
+                && sqlConstantExpression.Value is bool boolValue
+                ? _sqlExpressionFactory.Equal(
+                    boolValue
+                        ? _sqlExpressionFactory.Constant(1)
+                        : _sqlExpressionFactory.Constant(0),
+                    _sqlExpressionFactory.Constant(1))
+                : _sqlExpressionFactory.Equal(
+                sqlExpression,
```
Comment (smitpatel) [inline src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs]: indent

File: src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs [hunk 78]
```diff
@@ -23,34 +23,58 @@ public class SearchConditionConvertingExpressionVisitor : SqlExpressionVisitor
...
+                _sqlExpressionFactory.Constant(true));
+
+        // !(a == b) -> (a != b)
+        // !(a != b) -> (a == b)
+        private SqlExpression SimplifyNegatedBinary(SqlExpression sqlExpression)
+            => sqlExpression is SqlUnaryExpression sqlUnaryExpression
+                && sqlUnaryExpression.OperatorType == ExpressionType.Not
```
Comment (smitpatel) [inline src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs]: IsLogicalNot

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs (hunk 7 above)
Comment (smitpatel) [reply src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs]: remove internal?
@ajcvickers

---
In reply to: [354103808](https://github.com/aspnet/EntityFrameworkCore/pull/19168#discussion_r354103808) [](ancestors = 354103808)

File: test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs [hunk 79]
```diff
@@ -45,15 +45,15 @@ public override async Task String_contains_on_argument_with_wildcard_constant(bo
                 //
                 @"SELECT [f].[FirstName]
 FROM [FunkyCustomers] AS [f]
-WHERE CHARINDEX(N'%B%a%r', [f].[FirstName]) <= 0",
+WHERE NOT (CHARINDEX(N'%B%a%r', [f].[FirstName]) > 0)",
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs]: by design reverted optimization?

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs [hunk 80]
```diff
@@ -1171,10 +1171,8 @@ public override void Contains_over_entityType_with_null_should_rewrite_to_identi
             base.Contains_over_entityType_with_null_should_rewrite_to_identity_equality();
 
             AssertSql(
-                @"@__entity_equality_p_0_OrderID=NULL (DbType = Int32)
-
-SELECT CASE
-    WHEN @__entity_equality_p_0_OrderID IN (
+                @"SELECT CASE
+    WHEN NULL IN (
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs]: Null in subquery is never null if inner is non-nullable

Comment (smitpatel) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs]: Null in subquery is always null even if it matches is null in (NULL) which returns null.

---
In reply to: [363009999](https://github.com/aspnet/EntityFrameworkCore/pull/19168#discussion_r363009999) [](ancestors = 363009999)

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs [hunk 81]
```diff
@@ -1182,7 +1182,7 @@ public override async Task Indexof_with_emptystring(bool async)
 
             AssertSql(
                 @"SELECT CASE
-    WHEN N'' = N'' THEN 0
+    WHEN 1 = 1 THEN 0
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs]: Optimize

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs [hunk 82]
```diff
@@ -1690,7 +1690,7 @@ public override async Task All_after_GroupBy_aggregate2(bool async)
         SELECT 1
         FROM [Orders] AS [o]
         GROUP BY [o].[CustomerID]
-        HAVING SUM([o].[OrderID]) < 0) THEN CAST(1 AS bit)
+        HAVING NOT (SUM([o].[OrderID]) >= 0)) THEN CAST(1 AS bit)
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs]: Why Not leaves space after it!!! :volcano:

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 55 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: with helper method those got reduced to 2 lines - not worth DRYing

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 60 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: we need to reset after every visit - we dont want information to propagate from one element to another. Now done in a helper method so its easier on the eyes.

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 55 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: Elaborate more. They do exactly same processing. Add abstract Update method in SetOperationBase.

File: src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs (hunk 37 above)
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs]: seems like it could be useful for some providers wanting to add optimizations that can be done before 2nd level cache

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 47 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: no need anymore, collapsed to one line

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 49 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: we never do - IsNullable always resets at the start of the visit and we only look at it's value after visitation is complete

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 55 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: this is how they look right now:

```cs
            var source1 = (SelectExpression)VisitInternal(intersectExpression.Source1);
            var source2 = (SelectExpression)VisitInternal(intersectExpression.Source2);

            return intersectExpression.Update(source1, source2);
```

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 57 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: non needed due to helper method

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 61 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: we need it so that nullable comuln information doesn't propagate between projections. However now we handle it in the helper method so the code looks cleaner

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 65 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: need to do it on both sides at least in the case of column

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 67 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: moved from switch expression to elvis

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 75 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: nowhere - removed

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 76 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: too many arguments, @AndriySvyryd would be unhappy ;)

Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: removed

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 72 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: removed

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 69 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: we dont want to lose parameterized queries here

File: test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs (hunk 79 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs]: yes, the optimization is not valid in general for this case - it will go back to the optimized form once we know the function metadata and can determine that the charindex(firstName) is never nullable

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs (hunk 81 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs]: already tracked by #19295

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs (hunk 82 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs]: you wrote that code :trollface:

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 70 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: not worth - abstracting out whether value of Constant/Parameter is null is too much work

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 41 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: largely obsoleted by using a helper method

File: test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs (hunk 80 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs]: filed: https://github.com/aspnet/EntityFrameworkCore/issues/19499

**Comment by maumar** [comment]
PR feedback addressed @smitpatel

File: src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs [hunk 83]
```diff
@@ -38,308 +24,32 @@ public class RelationalParameterBasedQueryTranslationPostprocessor
...
-        public virtual (SelectExpression selectExpression, bool canCache) Optimize(
+        public virtual (SelectExpression, bool) Optimize(
             [NotNull] SelectExpression selectExpression,
             [NotNull] IReadOnlyDictionary<string, object> parametersValues)
         {
             Check.NotNull(selectExpression, nameof(selectExpression));
             Check.NotNull(parametersValues, nameof(parametersValues));
 
             var canCache = true;
+            var (sqlExpressionOptimized, optimizerCanCache) = new SqlExpressionOptimizingExpressionVisitor(
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs]: NullSemantics in name

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 84]
```diff
@@ -0,0 +1,1543 @@
...
+
+                nullable |= Nullable;
+                newWhenClauses.Add(new CaseWhenClause(newTest, newResult));
+                RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+            }
+
+            var newElseResult = (SqlExpression)VisitInternal(caseExpression.ElseResult);
+            Nullable |= nullable;
+            Optimize = optimize;
+            RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: VisitInternal will take care of resetting this

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 85]
```diff
@@ -0,0 +1,1543 @@
...
+
+            return existsExpression.Update(
+                (SelectExpression)VisitInternal(existsExpression.Subquery));
+        }
+
+        protected override Expression VisitFromSql(FromSqlExpression fromSqlExpression)
+        {
+            Check.NotNull(fromSqlExpression, nameof(fromSqlExpression));
+
+            return fromSqlExpression;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: return Check.NotNUll

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 86]
```diff
@@ -0,0 +1,1543 @@
...
+                        hasNullValue = true;
+                        continue;
+                    }
+
+                    inValues.Add(value);
+                }
+
+                var processedValuesExpression = (SqlConstantExpression)VisitInternal(SqlExpressionFactory.Constant(inValues, typeMapping));
+
+                return (processedValuesExpression, (List<object>)processedValuesExpression.Value, hasNullValue);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: just use inValues

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 87]
```diff
@@ -0,0 +1,1543 @@
...
+                    if (value == null)
+                    {
+                        hasNullValue = true;
+                        continue;
+                    }
+
+                    inValues.Add(value);
+                }
+
+                var processedValuesExpression = (SqlConstantExpression)VisitInternal(SqlExpressionFactory.Constant(inValues, typeMapping));
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: do you really need to visit this?

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 88]
```diff
@@ -0,0 +1,1543 @@
...
+            return leftJoinExpression.Update(newTable, newJoinPredicate);
+        }
+
+        private SqlExpression VisitJoinPredicate(SqlBinaryExpression predicate)
+        {
+            switch (predicate.OperatorType)
+            {
+                case ExpressionType.Equal:
+                {
+                    var left = (SqlExpression)VisitInternal(predicate.Left, optimize: true);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: should rename to allowOptimizedExpansion. optimize seems misleading

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 89]
```diff
@@ -0,0 +1,1543 @@
...
+                default:
+                    throw new InvalidOperationException("Unexpected join predicate shape: " + predicate);
+            }
+        }
+
+        protected override Expression VisitLike(LikeExpression likeExpression)
+        {
+            var match = (SqlExpression)VisitInternal(likeExpression.Match);
+            var matchNullable = Nullable;
+            var pattern = (SqlExpression)VisitInternal(likeExpression.Pattern);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: Try making visit internal generic on T so you can avoid this casting

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 90]
```diff
@@ -0,0 +1,1543 @@
...
+
+            return projectionExpression.Update(
+                (SqlExpression)VisitInternal(projectionExpression.Expression));
+        }
+
+        protected override Expression VisitRowNumber(RowNumberExpression rowNumberExpression)
+        {
+            Check.NotNull(rowNumberExpression, nameof(rowNumberExpression));
+
+            var optimize = Optimize;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: >optimize [](start = 16, length = 8)

VisitInternal will preserve optimize, no?

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 91]
```diff
@@ -0,0 +1,1543 @@
...
+            if (sqlBinaryExpression.OperatorType != ExpressionType.AndAlso)
+            {
+                RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+            }
+
+            var right = (SqlExpression)Visit(sqlBinaryExpression.Right);
+            var rightNullable = Nullable;
+            if (sqlBinaryExpression.OperatorType == ExpressionType.OrElse)
+            {
+                var rightNonNullableColumns = NonNullableColumns.Skip(currentNonNullableColumnsCount).ToList();
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: >rightNonNullableColumns [](start = 20, length = 23)

Inline variable and avoid ToList allocation

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 92]
```diff
@@ -0,0 +1,1543 @@
...
+                RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+                NonNullableColumns.AddRange(intersect);
+            }
+            else if (sqlBinaryExpression.OperatorType != ExpressionType.AndAlso)
+            {
+                // in case of AndAlso we already have what we need as the column information propagates from left to right
+                RestoreNonNullableColumnsList(currentNonNullableColumnsCount);
+            }
+
+            if (sqlBinaryExpression.OperatorType == ExpressionType.Coalesce)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: never true

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs [hunk 93]
```diff
@@ -0,0 +1,1543 @@
...
+namespace Microsoft.EntityFrameworkCore.Query
+{
+    public class SqlExpressionOptimizingExpressionVisitor : SqlExpressionVisitor
+    {
+        protected virtual bool UseRelationalNulls { get; }
+        protected virtual ISqlExpressionFactory SqlExpressionFactory { get; }
+        protected virtual IReadOnlyDictionary<string, object> ParameterValues { get; }
+        protected virtual List<ColumnExpression> NonNullableColumns { get; } = new List<ColumnExpression>();
+
+        protected virtual bool Nullable { get; set; }
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: discussed encapsulation of nullabe/optimize & nonnullable columns

File: src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs (hunk 83 above)
Comment (maumar) [reply src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs]: NullabilityBasedSqlProcessingExpressionVisitor

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 87 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: nope, removing

File: src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs (hunk 89 above)
Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: i was debating it, doesn't change much IMO but I can add it, sure

Comment (maumar) [reply src/EFCore.Relational/Query/SqlExpressionOptimizingExpressionVisitor.cs]: i was debating it, doesn't change much IMO but I can add it, sure

File: src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs [hunk 94]
```diff
@@ -23,34 +23,58 @@ public class SearchConditionConvertingExpressionVisitor : SqlExpressionVisitor
...
+                : _sqlExpressionFactory.Equal(
+                    sqlExpression,
+                    _sqlExpressionFactory.Constant(true));
+
+        // !(a == b) -> (a != b)
+        // !(a != b) -> (a == b)
+        private SqlExpression SimplifyNegatedBinary(SqlExpression sqlExpression)
+            => sqlExpression is SqlUnaryExpression sqlUnaryExpression
+                && sqlUnaryExpression.IsLogicalNot()
+                && (sqlUnaryExpression.Type == typeof(bool) || sqlUnaryExpression.Type == typeof(bool?))
```
Comment (smitpatel) [inline src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs]: IsLogicalNot already checks for type. Remove.

File: src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs [hunk 95]
```diff
@@ -0,0 +1,1493 @@
...
+        }
+
+        /// <summary>
+        ///     Method that handles visitation of SqlExpression nodes. All provider specific nodes should be handled by this method in the provider specific implementation of <see cref="NullabilityBasedSqlProcessingExpressionVisitor"/>.
+        ///     Depending on the settings, the method sets up state for the actual visitation, cleans up after the visitation is complete
+        ///     and returns resulting expression along with it's nullability.
+        /// </summary>
+        /// <typeparam name="TResult">Type of the resulting expression. </typeparam>
+        /// <param name="expression">Expression that is to be visited. </param>
+        /// <param name="allowOptimizedExpansion">True if null semantics inside the expression can be expanded in the optimized way (i.e. <see langword="null"/> and <see langword="false"/> are interchangable), false otherwise. </param>
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs]: @AndriySvyryd @bricelam - guidance on usage of langword? or c? or nothing for null?

File: src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs [hunk 96]
```diff
@@ -0,0 +1,1493 @@
...
+        /// <param name="restoreNonNullableColumnInformation">True if method should reset the number of non-nullable columns after the visitation is complete, false otherwise. </param>
+        /// <returns> Tuple representing visited expression and it's nullability. </returns>
+        protected virtual (TResult ResultExpression, bool Nullable) VisitInternal<TResult>(
+            [CanBeNull] Expression expression,
+            bool allowOptimizedExpansion = false,
+            bool restoreNonNullableColumnInformation = true)
+            where TResult : Expression
+        {
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs]: short circuit for null expression before setting up all the states.

File: src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs [hunk 97]
```diff
@@ -0,0 +1,1493 @@
...
+        protected override Expression VisitCase(CaseExpression caseExpression)
+        {
+            Check.NotNull(caseExpression, nameof(caseExpression));
+
+            // if there is no 'else' there is a possibility of null, when none of the conditions are met
+            // otherwise the result is nullable if any of the WhenClause results OR ElseResult is nullable
+            var nullable = caseExpression.ElseResult == null;
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
+
+            var operand = VisitInternal<SqlExpression>(caseExpression.Operand).ResultExpression;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs]: Do we have a test where operand is nullable?

File: src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs [hunk 98]
```diff
@@ -0,0 +1,1493 @@
...
+            var currentNonNullableColumnsCount = NonNullableColumns.Count;
+
+            var (left, leftNullable) = VisitInternal<SqlExpression>(
+                sqlBinaryExpression.Left,
+                allowOptimizedExpansion: _allowOptimizedExpansion,
+                restoreNonNullableColumnInformation: false);
+
+            var leftNonNullableColumns = NonNullableColumns.Skip(currentNonNullableColumnsCount).ToList();
+
+            _nullable = false;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs]: VisitInternal on right resets this.

File: src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs (hunk 97 above)
Comment (maumar) [reply src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs]: yup, SpatialQuerySqlServerGeographyTest.OgcGeometryType

**Comment by maumar** [comment]
@smitpatel another update

File: src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs (hunk 95 above)
Comment (maumar) [reply src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs]: removed the langword as we don't seem to be using it anywhere else
