### PR TITLE
Fix to #19128 - Query: Error for queries with enum parameters whose value is of underlying type but the value expected by type mapping is the actual enum type

### LINKED ISSUE #19128: Query: Error for queries with enum parameters whose value is of underlying type but the value expected by type mapping is the actual enum type
### Steps to reproduce

I have the following query:

```c#
result.Items = await query.Select(a => new MedicalReportSectionListView()
{
	Id = a.Id,
	OperatorId = a.OperatorId,
	Name = a.Name,
	Order = a.Order,
	DefaultContent = a.DefaultContent,
	Hidden = (a.Flags & MedicalReportSectionFlags.Private) != 0,
	Active = (a.Flags & MedicalReportSectionFlags.Active) != 0
}).ToArrayAsync();
```
the issue is in:

`Hidden = (a.Flags & MedicalReportSectionFlags.Private) != 0,`

Entity:
```c#
[Flags]
public enum MedicalReportSectionFlags
{
	None = 0x0,
	Active = 0x1,
	Private = 0x2,
	Attachment= 0x4
}
public class MedicalReportSection
{
	[Key]
	public int Id { get; set; }
	public Guid OperatorId { get; set; }
	public string Name { get; set; }
	public int Order { get; set; }
	public string DefaultContent { get; set; }
	public virtual Operator Operator { get; set; }
	public MedicalReportSectionFlags Flags { get; set; }
}

```
Model:
```c#
public class MedicalReportSectionListView
{
	public int Id { get; set; }
	public Guid OperatorId { get; set; }
	public string Name { get; set; }
	public int Order { get; set; }
	public string DefaultContent { get; set; }
	public bool Hidden { get; set; }
	public bool Active { get; set; }
}
```
Stack trace:
```
System.InvalidCastException
  HResult=0x80004002
  Message=Invalid cast from 'System.Int32' to 'DocSpecial.Data.Entities.MedicalReportSectionFlags'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.Int32.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.<InitializeReaderAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToArrayAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DocSpecial.Core.MedicalReportSectionListHandler.<ExecuteWorkAsync>d__0.MoveNext() in D:\Development\IctMakers\Git\DocSpecial\DocSpecial.Core\Commands\MedicalReportSectionListHandler.cs:line 42

  This exception was originally thrown at this call stack:
	System.Convert.DefaultToType(System.IConvertible, System.Type, System.IFormatProvider)
	int.System.IConvertible.ToType(System.Type, System.IFormatProvider)
	System.Convert.ChangeType(object, System.Type, System.IFormatProvider)
	System.Convert.ChangeType(object, System.Type)
	Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(System.Data.Common.DbCommand, string, object, bool?)
	Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(System.Data.Common.DbCommand, object)
	Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(System.Data.Common.DbCommand, System.Collections.Generic.IReadOnlyDictionary<string, object>)
	Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(Microsoft.EntityFrameworkCore.Storage.RelationalCommandParameterObject, System.Guid, Microsoft.EntityFrameworkCore.Diagnostics.DbCommandMethod)
    ...
    [Call Stack Truncated]

```
Thanks 

### Further technical details

EF Core version: 5.0.0-alpha1.19552.2 - 3.1.0-preview3.19554.8
Database provider: SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10 - 1903
IDE: Visual Studio 2019 Preview 16.4.0 Preview 6.0

### PR DESCRIPTION
**Pull request by maumar**
Problem was that we were not correctly compensating for type differences between parameter value and the DbParameter type (determined from type mapping). This can happen when the parameter is explicitly typed as the underlying type, but in the query the type is inferred from other side of binary expression etc.

Fix is to detect the case when expected parameter value is Enum, but the actual type is the underlying type and convert the value back to the enum type, just like we do for constants.

Fixes #19128

### CODE REVIEW

File: src/EFCore.Relational/Storage/RelationalTypeMapping.cs [hunk 1]
```diff
@@ -456,6 +458,15 @@ public virtual RelationalTypeMapping Clone(in RelationalTypeMappingInfo mappingI
             return parameter;
         }
 
+        // Enum when compared to constant will always have constant of integral type
```
Comment (smitpatel) [inline src/EFCore.Relational/Storage/RelationalTypeMapping.cs]: Comment needs to update for constant/parameter

**Comment by maumar** [comment]
@ajcvickers, Smit wanted you too look at this as well
