### PR TITLE
Fix for 21133. IndexAttribute properties did not have the right TypeMappings

### LINKED ISSUE #21133: Indexes specified by attribute do not change type mappings appropriately
When I have this entity type:

```C#
public class User
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```
And configure it like this:
```C#
modelBuilder.Entity<User>().HasIndex(e => e.Name);
```
Then EF uses the "key or index" mapping for the string type, which results in this:

```sql
CREATE TABLE [Users] (
    [Id] int NOT NULL IDENTITY,
    [Name] nvarchar(450) NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY ([Id])
);

CREATE INDEX [IX_Users_Name] ON [Users] ([Name]);
```

Notice that `nvarchar(450)` is used.

However, if I do this:

```C#
[Index(nameof(User.Name))]
public class User
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```
Then creating the database throws because Name is still using `nvarchar(max)`.

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Users] (
          [Id] int NOT NULL IDENTITY,
          [Name] nvarchar(max) NULL,
          CONSTRAINT [PK_Users] PRIMARY KEY ([Id])
      );
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE INDEX [IX_Users_Name] ON [Users] ([Name]);
Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Column 'Name' in table 'Users' is of a type that is invalid for use as a key column in an index.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at Program.Main() in /home/ajcvickers/AllTogetherNow/Daily/Daily.cs:line 22
ClientConnectionId:ac59a862-d8f7-44f8-95be-c95a41b4b94d
Error Number:1919,State:1,Class:16
```

### PR DESCRIPTION
**Pull request by lajones**
Fixes #21133 .
IndexAttribute properties did not have the right TypeMappings. Also create indexes before ModelFinalizing to allow fluent api overrides.

### CODE REVIEW

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs [hunk 1]
```diff
@@ -33,9 +35,48 @@ public IndexAttributeConvention([NotNull] ProviderConventionSetBuilderDependenci
...
+        {
+            CheckIndexAttributesAndEnsureIndex(
+                modelBuilder.Metadata.GetEntityTypes(), false);
+        }
+
+        private void CheckIndexAttributesAndEnsureIndex(
+            IEnumerable<IConventionEntityType> entityTypes,
+            bool shouldEnsureIndexOrFailSilently)
+        {
+            foreach (var entityType in entityTypes)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:79]: Move the loop outside to avoid creating a collection when only one entity type is supplied

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs [hunk 2]
```diff
@@ -33,9 +35,48 @@ public IndexAttributeConvention([NotNull] ProviderConventionSetBuilderDependenci
...
+            IConventionModelBuilder modelBuilder,
+            IConventionContext<IConventionModelBuilder> context)
+        {
+            CheckIndexAttributesAndEnsureIndex(
+                modelBuilder.Metadata.GetEntityTypes(), false);
+        }
+
+        private void CheckIndexAttributesAndEnsureIndex(
+            IEnumerable<IConventionEntityType> entityTypes,
+            bool shouldEnsureIndexOrFailSilently)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:77]: rename to something without 'or', like `shouldThrow`

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs [hunk 3]
```diff
@@ -33,9 +35,48 @@ public IndexAttributeConvention([NotNull] ProviderConventionSetBuilderDependenci
...
+
+        /// <inheritdoc/>
+        public virtual void ProcessEntityTypeBaseTypeChanged(
+            IConventionEntityTypeBuilder entityTypeBuilder,
+            IConventionEntityType newBaseType,
+            IConventionEntityType oldBaseType,
+            IConventionContext<IConventionEntityType> context)
+        {
+            CheckIndexAttributesAndEnsureIndex(
+                entityTypeBuilder.Metadata.GetDerivedTypesInclusive(), true);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:54]: No need to call it on the derived types. Also can exit early if `oldBaseType` is `null`

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs [hunk 4]
```diff
@@ -33,9 +35,48 @@ public IndexAttributeConvention([NotNull] ProviderConventionSetBuilderDependenci
...
+        }
+
+        /// <inheritdoc/>
+        public virtual void ProcessPropertyAdded(
+            IConventionPropertyBuilder propertyBuilder,
+            IConventionContext<IConventionPropertyBuilder> context)
+        {
+            CheckIndexAttributesAndEnsureIndex(
+                propertyBuilder.Metadata.DeclaringEntityType.GetDerivedTypesInclusive(), true);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:63]: Thinking more about this case I realized that it would have a significant perf impact only to make a corner case work better. So I changed my mind: we shouldn't run this on PropertyAdded and instead add the missing indexes on ModelFinalizing. This should give us the best of both worlds: indexes will be created early in most cases and it won't have a big impact on perf.

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs [hunk 5]
```diff
@@ -48,6 +89,11 @@ public virtual void ProcessModelFinalizing(IConventionModelBuilder modelBuilder,
                         {
                             if (ignoredMembers.Contains(propertyName))
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:90]: Call `entityType.Builder.IsIgnored(propertyName, true)` instead, it takes the configuration source into account

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs (hunk 2 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:77]: With the change to `ModelFinalizing` below such that it is now ensuring the index, that works.

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs (hunk 3 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:54]: What if you have classes: `C` inherits from `B` inherits from `A`. `C` has an index which references a property on `A`, when we call `B.HasBaseType(null)` don't we want to revisit the index on `C`?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:54]: That index should be recreated by the InternalEntityTypeBuilder. Add a test to make sure

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs [hunk 6]
```diff
@@ -70,6 +116,11 @@ public virtual void ProcessModelFinalizing(IConventionModelBuilder modelBuilder,
                             var property = entityType.FindProperty(propertyName);
                             if (property == null)
                             {
+                                if (shouldEnsureIndexOrFailSilently)
+                                {
+                                    return;
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:121]: You can try to create the property in case there's a matching CLR property that wasn't discovered by convention (e.g. it's private)

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs (hunk 3 above)
Comment (smitpatel) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:54]: What about other way around?
IndexAttribute on `C` uses a property which is not defined on `C` or `B` and `A` has that property but currently not set as base type of `B`. When we set `A` as a base type of `B`, now `C` can create the index because `A` provided that property.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:54]: @smitpatel That is a corner case and will be handled on ModelFinalizing

Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:54]: Not sure why an index on `B` would need this call, but one on `C` would not, but I'll add the test and see.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:54]: > Not sure why an index on B would need this call, but one on C would not, but I'll add the test and see.

An index on B wouldn't need this call either. This call is for an index on A.

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs (hunk 5 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:90]: This is causing test failures. Let's discuss.

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs (hunk 6 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:121]: That doesn't feel like it should be `IndexAttibuteConvention`'s responsibility. Do you have any other examples of conventions creating properties like this?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:121]: Any convention that works on property names specified in an attribute would do this. For now the only other one is `ForeignKeyPropertyDiscoveryConvention`

File: src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs [hunk 7]
```diff
@@ -228,6 +228,37 @@ public interface IConventionEntityTypeBuilder : IConventionAnnotatableBuilder
         /// <returns> <see langword="true" /> if the entity type can be marked as keyless. </returns>
         bool CanRemoveKey(bool fromDataAnnotation = false);
 
+        /// <summary>
+        ///     Configures an index on the specified property names.
+        ///     If there is an existing index on the given list of properyt names,
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs:233]: Typo in proprty

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs [hunk 8]
```diff
@@ -33,79 +34,170 @@ public IndexAttributeConvention([NotNull] ProviderConventionSetBuilderDependenci
...
-                if (entityType.ClrType != null)
+                CheckIndexAttributesAndEnsureIndex(entityType, true);
+            }
+        }
+
+        private void CheckIndexAttributesAndEnsureIndex(
+            IConventionEntityType entityType,
+            bool shouldThrow)
+        {
+            if (entityType.ClrType != null)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:74]: Invert condition for readability

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs [hunk 9]
```diff
@@ -33,79 +34,170 @@ public IndexAttributeConvention([NotNull] ProviderConventionSetBuilderDependenci
...
+                    IConventionIndexBuilder indexBuilder = null;
+                    if (!shouldThrow)
                     {
                         var indexProperties = new List<IConventionProperty>();
                         foreach (var propertyName in indexAttribute.PropertyNames)
                         {
-                            if (ignoredMembers.Contains(propertyName))
+                            // TODO Change this to the IsIgnored() which takes
+                            // fromDataAnnotation, when bug 21220 is fixed.
+                            if (entityType.IsIgnored(propertyName))
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:87]: This check is redundant now and can be removed

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs [hunk 10]
```diff
@@ -33,79 +34,170 @@ public IndexAttributeConvention([NotNull] ProviderConventionSetBuilderDependenci
...
+            }
+        }
+
+        private void CheckIgnoredProperties(
+            IndexAttribute indexAttribute,
+            IConventionEntityType entityType)
+        {
+            foreach (var propertyName in indexAttribute.PropertyNames)
+            {
+                if (entityType.IsIgnored(propertyName))
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:149]: should use configuration source.

Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:149]: That's what wasn't working. @AndriySvyryd and I discussed this yesterday and decided to do this for now.

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs (hunk 9 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:87]: Agreed.

File: src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs (hunk 8 above)
Comment (lajones) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:74]: ? You mean `if (null != entityType.ClrType)`?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs:74]: No, I mean
```C#
if (entityType.ClrType == null)
{
    return;
}
```
