### PR TITLE
Preserve synchronization context in ExecutionStrategy

### LINKED ISSUE #26763: SaveChangesAsync doesn't preserve the sync context across retries
In [this Helix build](https://dev.azure.com/dnceng/public/_build/results?buildId=1477673&view=logs&j=f95328f7-07f5-5106-5c2a-5dc7069f305c) we have the following [test failure](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-efcore-refs-pull-26723-merge-4311429c9bd948b5bf/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.dll/1/console.284d46c7.log?sv=2019-07-07&se=2021-12-09T12%3A00%3A16Z&sr=c&sp=rl&sig=l1vTnIZuvkC6JKjKDoOd%2Ftqf0tVmhUikM%2FhejIgooRk%3D), seems to be flaky:

```
    Microsoft.EntityFrameworkCore.Query.QueryBugsTest.SaveChangesAsync_accepts_changes_with_ConfigureAwait_true_22841 [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        D:\a\_work\1\s\test\EFCore.SqlServer.FunctionalTests\Query\QueryBugsTest.cs(9132,0): at Microsoft.EntityFrameworkCore.Query.QueryBugsTest.SaveChangesAsync_accepts_changes_with_ConfigureAwait_true_22841()
        --- End of stack trace from previous location ---
```

### PR DESCRIPTION
**Pull request by roji**
Fixes #26763

### CODE REVIEW

**Review by AndriySvyryd — APPROVED** [review]

File: src/EFCore/Storage/ExecutionStrategy.cs [hunk 1]
```diff
@@ -332,7 +332,7 @@ public virtual bool RetriesOnFailure
 
                 Current = this;
                 var result = await operation(Dependencies.CurrentContext.Context, state, cancellationToken)
-                    .ConfigureAwait(false);
+                    .ConfigureAwait(true);
```
Comment (AndriySvyryd) [inline src/EFCore/Storage/ExecutionStrategy.cs:335]: Don't you also need to change `ExecuteAsync` above?

Comment (roji) [reply src/EFCore/Storage/ExecutionStrategy.cs:335]: I don't think so - there's only ever one async invocation invocation there, and after that we immediately return. So the user's sync context is used for that one operation, and we don't care on what thread the continuation is scheduled on. Makes sense?
