### PR TITLE
Query: Disallow FromSql/TVF with TPT

### LINKED ISSUE #21508: Query: Disallow FromSql on TPT/TPC
Currently it is likely to just fail abruptly. We can either make it work or throw when used on TPT hierarchy.

### PR DESCRIPTION
**Pull request by smitpatel**
- Throw exception when using FromSql* methods
- Throw if a TVF is mapped to TPT
- Throw if construction of SelectExpression with custom TableExpression is done when TPT

Resolves #21508

### CODE REVIEW

File: src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs [hunk 1]
```diff
@@ -130,6 +131,13 @@ public override void Validate(IModel model, IDiagnosticsLogger<DbLoggerCategory.
                         throw new InvalidOperationException(RelationalStrings.DbFunctionInvalidReturnEntityType(
                             dbFunction.ModelName, dbFunction.ReturnType.ShortDisplayName(), elementType.ShortDisplayName()));
                     }
+
+                    if (entityType.BaseType != null || entityType.GetDerivedTypes().Any()
+                        && entityType.GetDiscriminatorProperty() == null)
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:136]: I'm not sure that we support TPH, do we have any tests?

Comment (smitpatel) [reply src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs:136]: Probably not tests but it just works due to design.
